### ISSUE TITLE
Add 'Ramon L. Perez Photography' to the 'Artisst' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1002]
Requesting to add 'Ramon L. Perez Photography' to the 'Artisst' category. 

Details follow: 
```yml 
- name: Ramon L. Perez Photography
      url: https://ramonlperez.weebly.com/
      img: 
      region: na
      country: US
      city: San Antonio
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Ramon L. Perez Photography](https://ramonlperez.weebly.com/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/ramonlperez.weebly.com/](https://www.alexa.com/siteinfo/ramonlperez.weebly.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
