### ISSUE TITLE
Add 'Barbershop.no' to the 'Retail OR health&beauty' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1003]
Requesting to add 'Barbershop.no' to the 'Retail OR health&beauty' category. 

Details follow: 
```yml 
- name: Barbershop.no
      url: https://barbershop.no
      img: 
      twitter: BarbershopNorge
      facebook: barbershop.no
      email_address: hei@barbershop.no
      region: eu
      country: !!str NO
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Barbershop.no](https://pbs.twimg.com/profile_images/2613594871/1l39bm242segnd9y6jkj_400x400.jpeg)

[Link to Barbershop.no](https://barbershop.no)
If needed, try the twitter handles profile image: [twitter.com/BarbershopNorge](https://twitter.com/BarbershopNorge)
If needed, try the facebook handles profile image: [fb.com/barbershop.no/](https://fb.com/barbershop.no/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/barbershop.no](https://www.alexa.com/siteinfo/barbershop.no)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
