### ISSUE TITLE
Add 'kitsystem' to the 'retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1004]
Requesting to add 'kitsystem' to the 'retailer' category. 

Details follow: 
```yml 
- name: kitsystem
      url: https://www.kitsystem.ru/
      img: 
      facebook: %D0%9A%D0%B8%D0%A2-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-%D0%98%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-1193561714111227/
      email_address: info@kitsystem.ru
      region: as
      country: RU
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://www.kitsystem.ru/blog/info/oplachivayte-tovary-i-uslugi-kriptovalyutoy
```

Resources for adding this merchant:
Logo Provided:
![kitsystem](https://www.kitsystem.ru/sites/default/files/0_my_files/img/logo/logo_ok.png)

[Link to kitsystem](https://www.kitsystem.ru/)
If needed, try the facebook handles profile image: [fb.com/%D0%9A%D0%B8%D0%A2-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-%D0%98%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-1193561714111227/](https://fb.com/%D0%9A%D0%B8%D0%A2-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-%D0%98%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82-%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD-1193561714111227/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.kitsystem.ru/](https://www.alexa.com/siteinfo/www.kitsystem.ru/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
