### ISSUE TITLE
Add bot telegram accept BitcoinCash

### ISSUE THREAD

**Issue by JMilkan** [acceptbitcoincash/acceptbitcoincash#1005]
Requesting to add SexRoulette to the Adult category. Details follow:

```yml

- name: SexRoulette
url: @SexRouletteBot_bot
img: 
twitter: 
facebook: 
region: Global
country: Global
city: Global
bch: yes
btc: no
othercrypto: no
doc: 
```
Resources for adding this merchant: https://telegram.me/SexRouletteBot_bot

Logo:
![photo_2018-05-30_13-35-57](https://user-images.githubusercontent.com/39765589/40718271-b89351aa-640f-11e8-92c4-853ffc2c9db4.jpg)
