### ISSUE TITLE
Add 'Clockwork Crypto' to the 'Apparel and Merchandise' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1006]
Requesting to add 'Clockwork Crypto' to the 'Apparel and Merchandise' category. 

Details follow: 
```yml 
- name: Clockwork Crypto
      url: https://clockworkcrypto.com
      img: 
      twitter: clockwork_crypto
      facebook: clockworkcrypto
      email_address: admin@clockworkcrypto.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Nothing special, just checkout and select coinpayments."
```

Resources for adding this merchant:
Logo Provided:
![Clockwork Crypto](https://pbs.twimg.com/profile_images/1000514669293981697/BK4WWJKU_400x400.jpg)

[Link to Clockwork Crypto](https://clockworkcrypto.com)
If needed, try the twitter handles profile image: [twitter.com/clockwork_crypto](https://twitter.com/clockwork_crypto)
If needed, try the facebook handles profile image: [fb.com/clockworkcrypto](https://fb.com/clockworkcrypto)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/clockworkcrypto.com](https://www.alexa.com/siteinfo/clockworkcrypto.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
