### ISSUE TITLE
Add 'Antwerp Or' to the 'Jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1008]
Requesting to add 'Antwerp Or' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: Antwerp Or
      url: https://www.antwerpor.com
      img: 
      twitter: AntwerpOr
      facebook: AntwerpOr
      email_address: support@antwerpor.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.antwerpor.com/blog/2017-08-18%20We%20Are%20Now%20Accepting%20Bitcoin%20Payments
```

Resources for adding this merchant:
Logo Provided:
![Antwerp Or](https://www.antwerpor.com/images/128.png)

[Link to Antwerp Or](https://www.antwerpor.com)
If needed, try the twitter handles profile image: [twitter.com/AntwerpOr](https://twitter.com/AntwerpOr)
If needed, try the facebook handles profile image: [fb.com/AntwerpOr](https://fb.com/AntwerpOr)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.antwerpor.com](https://www.alexa.com/siteinfo/www.antwerpor.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
