### ISSUE TITLE
Add 'CoinStorage.Guru' to the 'Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1010]
Requesting to add 'CoinStorage.Guru' to the 'Security' category. 

Details follow: 
```yml 
- name: CoinStorage.Guru
      url: https://coinstorage.guru/
      img: 
      twitter: coinstorageguru
      email_address: sales@coinstorage.guru
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Click on Proceed to Checkout and choose CoinPayments.net"
```

Resources for adding this merchant:
Logo Provided:
![CoinStorage.Guru](https://coinstorage.guru/wp-content/uploads/2018/02/coinstorage-logo-verson-3.png)

[Link to CoinStorage.Guru](https://coinstorage.guru/)
If needed, try the twitter handles profile image: [twitter.com/coinstorageguru](https://twitter.com/coinstorageguru)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/coinstorage.guru/](https://www.alexa.com/siteinfo/coinstorage.guru/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
