### ISSUE TITLE
Requesting to add ACE Hack Ware to the Retail category.

### ISSUE THREAD

**Issue by eronstrom** [acceptbitcoincash/acceptbitcoincash#1014]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add ACE Hack Ware to the Retail (or maybe security?) category. Details follow:

```yml

- name: ACE Hack Ware
  url: https://acehackware.com/
  img: https://cdn.shopify.com/s/files/1/0078/8862/t/11/assets/logo.png?6464949470617337605
  twitter: acehackware
  facebook: acehackware
  region: NA (ships world-wide)
  country: US (ships world-wide)
  city: 
  bch: yes
  btc: yes
  othercrypto: yes
  doc: none
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
