### ISSUE TITLE
Add 'igiftcards' to the 'Utilities' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1017]
Requesting to add 'igiftcards' to the 'Utilities' category. 

Details follow: 
```yml 
- name: igiftcards
      url: https://igiftcards.nl
      img: 
      region: eu
      country: NL
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: Note: several other country domains: fr/de/at/it/es exist as well
      exceptions: 
        text: "Choose Bitcoin (Not cryptocurrencies)"
```

Resources for adding this merchant:
[Link to igiftcards](https://igiftcards.nl)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/igiftcards.nl](https://www.alexa.com/siteinfo/igiftcards.nl)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
