### ISSUE TITLE
Add '★★★ Bit 🔥 Soul 🔥 Kitchen ★★★' to the 'Food sharing ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1019]
Requesting to add '★★★ Bit 🔥 Soul 🔥 Kitchen ★★★' to the 'Food sharing ' category. 

Details follow: 
```yml 
- name: ★★★ Bit 🔥 Soul 🔥 Kitchen ★★★
      url: https://bit-soul-kitchen.org
      img: 
      twitter: BitSoulKitchen
      facebook: BitcoinSoulKitchen
      email_address: info@bit-soul-kitchen.org
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://bitcointalk.org/index.php?topic=4406105.0
```

Resources for adding this merchant:
Logo Provided:
![★★★ Bit 🔥 Soul 🔥 Kitchen ★★★](http://bit-soul-kitchen.org/wp-content/uploads/2018/06/Bit-Soul-Kitchen-e1527938332140.jpg)

[Link to ★★★ Bit 🔥 Soul 🔥 Kitchen ★★★](https://bit-soul-kitchen.org)
If needed, try the twitter handles profile image: [twitter.com/BitSoulKitchen](https://twitter.com/BitSoulKitchen)
If needed, try the facebook handles profile image: [fb.com/BitcoinSoulKitchen](https://fb.com/BitcoinSoulKitchen)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bit-soul-kitchen.org](https://www.alexa.com/siteinfo/bit-soul-kitchen.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
