### ISSUE TITLE
Add 'CentroBill' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1024]
Requesting to add 'CentroBill' to the 'Payments' category. 

Details follow: 
```yml 
- name: CentroBill
      url: https://centrobill.com/
      img: 
      facebook: centrobill
      email_address: support@centrobill.com
      bch: No
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "A lot of porn sites are using this payment processor to accept BTC"
```

Resources for adding this merchant:
Logo Provided:
![CentroBill](https://centrobill.com/consumer/images/logo.png)

[Link to CentroBill](https://centrobill.com/)
If needed, try the facebook handles profile image: [fb.com/centrobill](https://fb.com/centrobill)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/centrobill.com/](https://www.alexa.com/siteinfo/centrobill.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
