### ISSUE TITLE
Add 'METAVERSEXXX' to the 'Porn (Virtual Reality)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1025]
Requesting to add 'METAVERSEXXX' to the 'Porn (Virtual Reality)' category. 

Details follow: 
```yml 
- name: METAVERSEXXX
      url: https://metaversexxx.com/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "First name , second name ... is required but if fake information is submited you are redirected to the payment windows too (there you can choose BCH)"
```

Resources for adding this merchant:
Logo Provided:
![METAVERSEXXX](https://metaversexxx.com/wp-content/uploads/2017/01/Nicoles-test-logo5.jpg)

[Link to METAVERSEXXX](https://metaversexxx.com/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/metaversexxx.com/](https://www.alexa.com/siteinfo/metaversexxx.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
