### ISSUE TITLE
Add 'All Girls Flash' to the 'Sites/Networks (adult)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1026]
Requesting to add 'All Girls Flash' to the 'Sites/Networks (adult)' category. 

Details follow: 
```yml 
- name: All Girls Flash
      url: https://www.allgirlsflash.me/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![All Girls Flash](https://static1.dditscdn.com/cob/site/lsl/233200/image/picture/logo.png?vlwmi)

[Link to All Girls Flash](https://www.allgirlsflash.me/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.allgirlsflash.me/](https://www.alexa.com/siteinfo/www.allgirlsflash.me/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
