### ISSUE TITLE
Add 'Porn.com' to the 'Sites/Networks (adult)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1027]
Requesting to add 'Porn.com' to the 'Sites/Networks (adult)' category. 

Details follow: 
```yml 
- name: Porn.com
      url: https://www.porn.com
      img: 
      bch: No
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Porn.com](https://mediav.porn.com/images/logo_red.png)

[Link to Porn.com](https://www.porn.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.porn.com](https://www.alexa.com/siteinfo/www.porn.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
