### ISSUE TITLE
Add 'TeenMegaWorld' to the 'Sites/Netoworks (Adult)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1028]
Requesting to add 'TeenMegaWorld' to the 'Sites/Netoworks (Adult)' category. 

Details follow: 
```yml 
- name: TeenMegaWorld
      url: https://teenmegaworld.net
      img: 
      twitter: TeenMegaWorld
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![TeenMegaWorld](https://pbs.twimg.com/profile_images/832154440446668800/cuLx_uD-_400x400.jpg)

[Link to TeenMegaWorld](https://teenmegaworld.net)
If needed, try the twitter handles profile image: [twitter.com/TeenMegaWorld](https://twitter.com/TeenMegaWorld)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/teenmegaworld.net](https://www.alexa.com/siteinfo/teenmegaworld.net)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
