### ISSUE TITLE
Add 'Girlsdoporn' to the 'Sites/Networks (Adult)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1029]
Requesting to add 'Girlsdoporn' to the 'Sites/Networks (Adult)' category. 

Details follow: 
```yml 
- name: Girlsdoporn
      url: http://www.girlsdoporn.com/
      img: 
      twitter: girlsdoporn
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Girlsdoporn](http://tourcdn.girlsdoporn.com/img/girls-do-porn-logo.png)

[Link to Girlsdoporn](http://www.girlsdoporn.com/)
If needed, try the twitter handles profile image: [twitter.com/girlsdoporn](https://twitter.com/girlsdoporn)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.girlsdoporn.com/](https://www.alexa.com/siteinfo/www.girlsdoporn.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
