### ISSUE TITLE
Add 'Strip Chat' to the 'Live Cams (Adult)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1030]
Requesting to add 'Strip Chat' to the 'Live Cams (Adult)' category. 

Details follow: 
```yml 
- name: Strip Chat
      url: https://stripchat.com/
      img: 
      twitter: stripchat
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Strip Chat](https://pbs.twimg.com/profile_images/852508619337854976/z5t2huBL_400x400.jpg)

[Link to Strip Chat](https://stripchat.com/)
If needed, try the twitter handles profile image: [twitter.com/stripchat](https://twitter.com/stripchat)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/stripchat.com/](https://www.alexa.com/siteinfo/stripchat.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
