### ISSUE TITLE
Add 'P2P Japanese' to the 'Education' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1031]
Requesting to add 'P2P Japanese' to the 'Education' category. 

Details follow: 
```yml 
- name: P2P Japanese
      url: https://p2pjapanese.github.io
      img: 
      email_address: kaosmile1022@yahoo.co.jp
      country: JP
      city: Osaka, Kyoto
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://p2pjapanese.github.io
      exceptions: 
        text: "Copied from the website:

1. Contact me by email to arrange a lesson.

Please provide:

- Preferred days/times in your time zone:
- Preferred location (skype or place in Kyoto/Osaka):

For a trial lesson, also please provide:

- Current Japanese ability:
- Objective (if any):
- Time zone:

2. We agree on a meeting time and place by email.
3. I send a QR-code invoice for payment.
4. You can pay any time before the lesson.
5. We do a 1 hour Japanese lesson at the agreed time/place."
```

Resources for adding this merchant:
Logo Provided:
![P2P Japanese](https://github.com/P2PJapanese/P2PJapanese.github.io/blob/master/assets/p2pj-128.png)

[Link to P2P Japanese](https://p2pjapanese.github.io)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/p2pjapanese.github.io](https://www.alexa.com/siteinfo/p2pjapanese.github.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
