### ISSUE TITLE
Add 'Twitch' to the 'Entretainment' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1033]
Requesting to add 'Twitch' to the 'Entretainment' category. 

Details follow: 
```yml 
- name: Twitch
      url: https://www.twitch.tv/
      img: 
      twitter: twitch
      facebook: twitch
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Twitch](https://www.muylinux.com/wp-content/uploads/2017/10/twitch.png)

[Link to Twitch](https://www.twitch.tv/)
If needed, try the twitter handles profile image: [twitter.com/twitch](https://twitter.com/twitch)
If needed, try the facebook handles profile image: [fb.com/twitch](https://fb.com/twitch)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.twitch.tv/](https://www.alexa.com/siteinfo/www.twitch.tv/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
