### ISSUE TITLE
Add 'Crypto Discounts Australia ' to the 'E-commerce' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1034]
Requesting to add 'Crypto Discounts Australia ' to the 'E-commerce' category. 

Details follow: 
```yml 
- name: Crypto Discounts Australia 
      url: https://www.cryptodiscounts.com.au
      img: 
      twitter: Cryptodiscounts
      facebook: Cryptodiscountsaustralia
      email_address: admin@cryptodiscounts.com.au
      country: AU
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/8o6tto/proudly_accepting_bitcoin_cash/?utm_source=share&utm_medium=android_app
      exceptions: 
        text: "No"
```

Resources for adding this merchant:
Logo Provided:
![Crypto Discounts Australia ](https://www.cryptodiscounts.com.au/wp-content/uploads/2018/04/logo5-2.png)

[Link to Crypto Discounts Australia ](https://www.cryptodiscounts.com.au)
If needed, try the twitter handles profile image: [twitter.com/Cryptodiscounts](https://twitter.com/Cryptodiscounts)
If needed, try the facebook handles profile image: [fb.com/Cryptodiscountsaustralia](https://fb.com/Cryptodiscountsaustralia)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cryptodiscounts.com.au](https://www.alexa.com/siteinfo/www.cryptodiscounts.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
