### ISSUE TITLE
Add 'Jack Leonard' to the 'Design / UX/UI design consultancy ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1035]
Requesting to add 'Jack Leonard' to the 'Design / UX/UI design consultancy ' category. 

Details follow: 
```yml 
- name: Jack Leonard
      url: http://jackleonard.me
      img: 
      twitter: jackleonardme
      email_address: me@jackleonard.me
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Jack Leonard](http://jackleonard.me)
If needed, try the twitter handles profile image: [twitter.com/jackleonardme](https://twitter.com/jackleonardme)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/jackleonard.me](https://www.alexa.com/siteinfo/jackleonard.me)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
