### ISSUE TITLE
Add 'Adamant Barbell' to the 'Health' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1036]
Requesting to add 'Adamant Barbell' to the 'Health' category. 

Details follow: 
```yml 
- name: Adamant Barbell
      url: https://www.adamantbarbell.com/
      img: 
      twitter: adamantbarbell
      facebook: adamantbarbell
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Adamant Barbell](https://i.imgur.com/hBc9dd5.jpg?2)

[Link to Adamant Barbell](https://www.adamantbarbell.com/)
If needed, try the twitter handles profile image: [twitter.com/adamantbarbell](https://twitter.com/adamantbarbell)
If needed, try the facebook handles profile image: [fb.com/adamantbarbell](https://fb.com/adamantbarbell)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.adamantbarbell.com/](https://www.alexa.com/siteinfo/www.adamantbarbell.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
