### ISSUE TITLE
Add bot telegram accept Bitcoin Cash

### ISSUE THREAD

**Issue by JMilkan** [acceptbitcoincash/acceptbitcoincash#1037]
Requesting to add Shortlink Revealer to the Donations category. Details follow:

```yml
- name: Shortlink Revealer
  url: https://telegram.me/Shortlink_Revealer_Bot
  img: 
  bch: yes
  btc: no
  othercrypto: no
```

Resources for adding this merchant: https://telegram.me/Shortlink_Revealer_Bot

Logo:
![dfsfdds](https://user-images.githubusercontent.com/39765589/41005536-35219250-691e-11e8-8521-172a63ae4d25.png)
