### ISSUE TITLE
Add 'Democracy at Work' to the 'Non-Profit' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1043]
Requesting to add 'Democracy at Work' to the 'Non-Profit' category. 

Details follow: 
```yml 
- name: Democracy at Work
      url: https://www.democracyatwork.info/donate
      img: 
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Democracy at Work](https://www.democracyatwork.info/donate)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.democracyatwork.info/donate](https://www.alexa.com/siteinfo/www.democracyatwork.info/donate)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
