### ISSUE TITLE
Add 'Namecheap' to the 'domain registrar, webhosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1044]
Requesting to add 'Namecheap' to the 'domain registrar, webhosting' category. 

Details follow: 
```yml 
- name: Namecheap
      url: https://www.namecheap.com
      img: 
      twitter: Namecheap
      facebook: Namecheap
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: they accept Bitcoin via BitPay (website footer)
      exceptions: 
        text: "first must top up account, select Bitcoin as payment method, BitPay invoice can be paid by BCH"
```

Resources for adding this merchant:
Logo Provided:
![Namecheap](https://02.files.namecheap.com/cdn/464/assets/img/logos/namecheap.png)

[Link to Namecheap](https://www.namecheap.com)
If needed, try the twitter handles profile image: [twitter.com/Namecheap](https://twitter.com/Namecheap)
If needed, try the facebook handles profile image: [fb.com/Namecheap](https://fb.com/Namecheap)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.namecheap.com](https://www.alexa.com/siteinfo/www.namecheap.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
