### ISSUE TITLE
Add 'Bitport.io' to the 'Torrent Downloader' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1045]
Requesting to add 'Bitport.io' to the 'Torrent Downloader' category. 

Details follow: 
```yml 
- name: Bitport.io
      url: https://bitport.io
      img: bitportio.png
      twitter: bitport_io
      facebook: bitportio
      email_address: info@bitport.io
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Bitport.io](http://torrentadvice.com/wp-content/uploads/2018/01/bitport-logo.png)

[Link to Bitport.io](https://bitport.io)
If needed, try the twitter handles profile image: [twitter.com/bitport_io](https://twitter.com/bitport_io)
If needed, try the facebook handles profile image: [fb.com/bitportio/](https://fb.com/bitportio/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bitport.io](https://www.alexa.com/siteinfo/bitport.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
