### ISSUE TITLE
Add 'AirVPN' to the 'VPN' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1046]
Requesting to add 'AirVPN' to the 'VPN' category. 

Details follow: 
```yml 
- name: AirVPN
      url: https://airvpn.org/
      img: 
      twitter: airvpn
      facebook: airvpn.org
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "via coinpayments.net"
```

Resources for adding this merchant:
Logo Provided:
![AirVPN](https://anonfile.com/ga78Nbe2b6/airvpn.jpg)

[Link to AirVPN](https://airvpn.org/)
If needed, try the twitter handles profile image: [twitter.com/airvpn](https://twitter.com/airvpn)
If needed, try the facebook handles profile image: [fb.com/airvpn.org](https://fb.com/airvpn.org)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/airvpn.org/](https://www.alexa.com/siteinfo/airvpn.org/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
