### ISSUE TITLE
Add 'Mamas Banh – Vietnamese Culinary Diversity' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1047]
Requesting to add 'Mamas Banh – Vietnamese Culinary Diversity' to the 'Food' category. 

Details follow: 
```yml 
- name: Mamas Banh – Vietnamese Culinary Diversity
      url: http://mamasbanh.com/
      img: mamasbanh.png
      facebook: mamasbanh
      email_address: daiquy@mamasbanh.com
      region: eu
      city: Berlin
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Mamas Banh – Vietnamese Culinary Diversity](https://anonfile.com/g98cN5eabc/mamas-banh_128.png)

[Link to Mamas Banh – Vietnamese Culinary Diversity](http://mamasbanh.com/)
If needed, try the facebook handles profile image: [fb.com/mamasbanh](https://fb.com/mamasbanh)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/mamasbanh.com/](https://www.alexa.com/siteinfo/mamasbanh.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
