### ISSUE TITLE
Add 'ATHEIST / The Meaningful Shoe Company' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1048]
Requesting to add 'ATHEIST / The Meaningful Shoe Company' to the 'Retail' category. 

Details follow: 
```yml 
- name: ATHEIST / The Meaningful Shoe Company
      url: http://www.atheistberlin.com/
      img: AtheistShoes.png
      twitter: AtheistShoes
      facebook: AtheistShoes
      bch: Yes
      btc: No
      othercrypto: No
      exceptions: 
        text: "Ask them or visit their shop in Berlin"
```

Resources for adding this merchant:
Logo Provided:
![ATHEIST / The Meaningful Shoe Company](http://www.atheistberlin.com/skin/frontend/atheist/default/images/logo.png)

[Link to ATHEIST / The Meaningful Shoe Company](http://www.atheistberlin.com/)
If needed, try the twitter handles profile image: [twitter.com/AtheistShoes](https://twitter.com/AtheistShoes)
If needed, try the facebook handles profile image: [fb.com/AtheistShoes](https://fb.com/AtheistShoes)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.atheistberlin.com/](https://www.alexa.com/siteinfo/www.atheistberlin.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
