### ISSUE TITLE
Add 'Lieferando' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1049]
Requesting to add 'Lieferando' to the 'Food' category. 

Details follow: 
```yml 
- name: Lieferando
      url: https://www.lieferando.de/
      img: 
      twitter: lieferando
      region: eu
      country: DE
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "Accepts Bitcoin Cash via Bitpay so you have to select "Bitcoin" a the payment option first "
```

Resources for adding this merchant:
Logo Provided:
![Lieferando](https://pbs.twimg.com/profile_images/684003886953328640/voBe-uVb_bigger.png)

[Link to Lieferando](https://www.lieferando.de/)
If needed, try the twitter handles profile image: [twitter.com/lieferando](https://twitter.com/lieferando)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.lieferando.de/](https://www.alexa.com/siteinfo/www.lieferando.de/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
