### ISSUE TITLE
Add 'Carmi Margarette Sorila' to the 'BCH' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1050]
Requesting to add 'Carmi Margarette Sorila' to the 'BCH' category. 

Details follow: 
```yml 
- name: Carmi Margarette Sorila
      url: https://blockchair.com/bitcoin-cash/transaction/a72249c0e23d389d100d2b22cd692eef7e52940ea77786ed92f7cc9612306452
      img: 
      email_address: cbsorila@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Carmi Margarette Sorila](https://blockchair.com/bitcoin-cash/transaction/a72249c0e23d389d100d2b22cd692eef7e52940ea77786ed92f7cc9612306452)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/blockchair.com/bitcoin-cash/transaction/a72249c0e23d389d100d2b22cd692eef7e52940ea77786ed92f7cc9612306452](https://www.alexa.com/siteinfo/blockchair.com/bitcoin-cash/transaction/a72249c0e23d389d100d2b22cd692eef7e52940ea77786ed92f7cc9612306452)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
