### ISSUE TITLE
Add 'Canine Solutions' to the 'Pet sitting, Dog Walking, Dog Boarding' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1051]
Requesting to add 'Canine Solutions' to the 'Pet sitting, Dog Walking, Dog Boarding' category. 

Details follow: 
```yml 
- name: Canine Solutions
      url: http://www.robsdogwalking.com
      img: 
      email_address: reiding@comcast.net
      region: na
      country: US
      city: Tallahassee
      state: FL
      bch: Yes
      btc: No
      othercrypto: Yes
      exceptions: 
        text: "Have a PayPal account. Will send invoice with cryto currency payment address in PayPal invoice note section."
```

Resources for adding this merchant:
Logo Provided:
![Canine Solutions](http://www.robsdogwalking.com/about.html)

[Link to Canine Solutions](http://www.robsdogwalking.com)
If needed, try the twitter handles profile image: [twitter.com/None.NSA get lost already](https://twitter.com/None.NSA get lost already)
If needed, try the facebook handles profile image: [fb.com/None,NSA get lost already](https://fb.com/None,NSA get lost already)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.robsdogwalking.com](https://www.alexa.com/siteinfo/www.robsdogwalking.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
