### ISSUE TITLE
Add 'Blockchainbottle ' to the 'Online Liquor store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1052]
Requesting to add 'Blockchainbottle ' to the 'Online Liquor store' category. 

Details follow: 
```yml 
- name: Blockchainbottle 
      url: https://www.blockchainbottle.net 
      img: Blockchainbottle.png
      facebook: Blockchainbottle
      email_address: info@blockchainbottle.net
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/CryptoCurrency/comments/8nsipq/started_an_online_crypto_only_liquor_store_after/
```

Resources for adding this merchant:
Logo Provided:
![Blockchainbottle ](https://pbs.twimg.com/profile_images/994744360095944704/OS2vPzfx.jpg)

[Link to Blockchainbottle ](https://www.blockchainbottle.net )
If needed, try the twitter handles profile image: [twitter.com/Blockchainbottle](https://twitter.com/Blockchainbottle)
If needed, try the facebook handles profile image: [fb.com/Blockchainbottle](https://fb.com/Blockchainbottle)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.blockchainbottle.net ](https://www.alexa.com/siteinfo/www.blockchainbottle.net )

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
