### ISSUE TITLE
Add 'ECOSYSTEMS Retail' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1053]
Requesting to add 'ECOSYSTEMS Retail' to the 'Retail' category. 

Details follow: 
```yml 
- name: ECOSYSTEMS Retail
      url: https://store.ecosystems-group.co.uk
      img: 
      email_address: store@ecosystems-group.co.uk
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/8qanek/new_refurbished_laptops_and_pcs_pay_with_bitcoin/
```

Resources for adding this merchant:
Logo Provided:
![ECOSYSTEMS Retail](https://store.ecosystems-group.co.uk/img/ecosystems-retail-ltd-new-used-and-refurbished-computers-logo-1528197030.jpg)

[Link to ECOSYSTEMS Retail](https://store.ecosystems-group.co.uk)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/store.ecosystems-group.co.uk](https://www.alexa.com/siteinfo/store.ecosystems-group.co.uk)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
