### ISSUE TITLE
Add 'Morello International' to the 'Italian food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1054]
Requesting to add 'Morello International' to the 'Italian food' category. 

Details follow: 
```yml 
- name: Morello International
      url: https://www.morelloint.com
      img: morelloIntl.png
      email_address: framore@morelloint.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Morello International](http://morelloint.com/sites/default/files/new_logo.png)

[Link to Morello International](https://www.morelloint.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.morelloint.com](https://www.alexa.com/siteinfo/www.morelloint.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
