### ISSUE TITLE
Add 'Cryptone.Media' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1055]
Requesting to add 'Cryptone.Media' to the 'Retail' category. 

Details follow: 
```yml 
- name: Cryptone.Media
      url: http://www.cryptonemedia.com
      img: CryptoneMedia.png
      twitter: CryptoneMedia
      facebook: cryptonemedia
      email_address: cryptone.media@gmail.com
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/CryptoneMedia/status/1007057798201528320
      exceptions: 
        text: "Select Other Payment Options at Check Out"
```

Resources for adding this merchant:
Logo Provided:
![Cryptone.Media](https://pbs.twimg.com/profile_images/982838162568499200/qTsypDVp_400x400.jpg)

[Link to Cryptone.Media](http://www.cryptonemedia.com)
If needed, try the twitter handles profile image: [twitter.com/CryptoneMedia](https://twitter.com/CryptoneMedia)
If needed, try the facebook handles profile image: [fb.com/cryptonemedia](https://fb.com/cryptonemedia)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cryptonemedia.com](https://www.alexa.com/siteinfo/www.cryptonemedia.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
