### ISSUE TITLE
add Lazy Pyramid to retail category

### ISSUE THREAD

**Issue by eronstrom** [acceptbitcoincash/acceptbitcoincash#1056]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add The Lazy Pyramid to the Retail category. Details follow:

```yml

- name: Lazy Pyramid
  url: https://lazypyramid.com/
  img: lazypyramid.png
  twitter: TheLazyPyramid
  facebook: lazypyramid
  bch: yes
  btc: yes
  othercrypto: yes
  keywords:
  - coinpayments
  - coinbase commerce
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
