### ISSUE TITLE
Add TheIndoleShop to the Other Catagory 

### ISSUE THREAD

**Issue by JettScythe** [acceptbitcoincash/acceptbitcoincash#1057]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**theindoleshop**}} to the {{**Other**}} category. Details follow:

```yml

- name: TheIndoleShop
  url: https://theindoleshop.com
  img: 
  facebook: The-Indole-Shop-780184475490111
  region: na
  country: CA
  city: Hamilton
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://theindoleshop.com/faq/
```

Reddit: https://www.reddit.com/user/theindoleshop

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
