### ISSUE TITLE
Add 'Servercow' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1059]
Requesting to add 'Servercow' to the 'Hosting' category. 

Details follow: 
```yml 
- name: Servercow
      url: https://www.servercow.de
      img: servercow.png
      facebook: servercow
      email_address: info@servercow.de
      region: eu
      country: DE
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Servercow](https://www.servercow.de/img/cow_globe.svg)

[Link to Servercow](https://www.servercow.de/)
If needed, try the facebook handles profile image: [fb.com/servercow](https://fb.com/servercow)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.servercow.de/](https://www.alexa.com/siteinfo/www.servercow.de/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
