### ISSUE TITLE
https://cashflow.fm | A payment processor supporting 0-conf and live payment updates

### ISSUE THREAD

**Issue by jbirer** [acceptbitcoincash/acceptbitcoincash#1064]
Requesting to add **CashFlow** to the **Payments** category. Details follow:

```yml

- name: CashFlow
  url: https://cashflow.fm
  img: URL_to_image
  region: Middle East
  country: TR
  city: Istanbul
  bch: yes
  btc: no
  othercrypto: no
  doc: https://cashflow.fm/doc
```
