### ISSUE TITLE
Add 'ARTLy - Arts&Crypto Shop' to the 'Art' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1068]
Requesting to add 'ARTLy - Arts&Crypto Shop' to the 'Art' category. 

Details follow: 
```yml 
- name: ARTLy - Arts&Crypto Shop
      url: https://shop.gohuozumi.com/
      img: 
      email_address: shop.goh@gmail.com
      region: as
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![ARTLy - Arts&Crypto Shop](https://lh3.googleusercontent.com/-PiCBgRGAkAU/AAAAAAAAAAI/AAAAAAAAAB8/B5x-aGuXndk/s120-p-rw-no-il/photo.jpg)

[Link to ARTLy - Arts&Crypto Shop](https://shop.gohuozumi.com/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/shop.gohuozumi.com/](https://www.alexa.com/siteinfo/shop.gohuozumi.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
