### ISSUE TITLE
Add 'Paykassa' to the 'Payments, Wallet' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1069]
Requesting to add 'Paykassa' to the 'Payments, Wallet' category. 

Details follow: 
```yml 
- name: Paykassa
      url: https://paykassa.pro
      img: 
      email_address: support@paykassa.pro
      region: eu
      country: RU
      city: Moscow
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://habr.com/post/351550/
```

Resources for adding this merchant:
Logo Provided:
![Paykassa](https://paykassa.pro/accept/)

[Link to Paykassa](https://paykassa.pro)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/paykassa.pro](https://www.alexa.com/siteinfo/paykassa.pro)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
