### ISSUE TITLE
Add 'Perivoli Guest Rooms' to the 'Accommodation' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1072]
Requesting to add 'Perivoli Guest Rooms' to the 'Accommodation' category. 

Details follow: 
```yml 
- name: Perivoli Guest Rooms
      url: https://www.guest-rooms.com
      img: 
      facebook: perivoli.guest.rooms
      email_address: itzortzak@gmail.com
      region: eu
      country: GR
      city: Kokkinos Pirgos
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.guest-rooms.com/2018/06/bitcoin-cash-and-bitcoin-core-accepted.html
      exceptions: 
        text: "Paying a Bitcoin invoice from your wallet can be done through a Bitcoin address or a the QR Code. "
```

Resources for adding this merchant:
Logo Provided:
![Perivoli Guest Rooms](https://3.bp.blogspot.com/-rLbTcqCdT3s/WpOolWnzWmI/AAAAAAAACXg/V0aF1BBRIbEYvoM7oMKexDN562A7hVGfgCLcBGAs/s1600/Perivoli%2Bplex.jpg)

[Link to Perivoli Guest Rooms](https://www.guest-rooms.com)
If needed, try the facebook handles profile image: [fb.com/perivoli.guest.rooms](https://fb.com/perivoli.guest.rooms)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.guest-rooms.com](https://www.alexa.com/siteinfo/www.guest-rooms.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
