### ISSUE TITLE
Add 'My iTutoring' to the 'Education' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1073]
Requesting to add 'My iTutoring' to the 'Education' category. 

Details follow: 
```yml 
- name: My iTutoring
      url: https://www.my-itutoring.com
      img: 
      twitter: itzortzak
      facebook: my.iTutoring
      email_address: itzortzak@gmail.com
      country: GR
      city: Kokkinos Pirgos
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: http://www.my-itutoring.com/2018/06/bitcoin-cash-and-bitcoin-core-accepted.html
      exceptions: 
        text: "Paying a Bitcoin invoice from your wallet can be done through a Bitcoin address or a the QR Code."
```

Resources for adding this merchant:
Logo Provided:
![My iTutoring](https://scontent.fath3-4.fna.fbcdn.net/v/t1.0-9/20953275_101662830555157_566512207998041803_n.png?_nc_cat=0&oh=0e13d3fdcb8b347d9930d325010b225d&oe=5BBAAE46)

[Link to My iTutoring](https://www.my-itutoring.com)
If needed, try the twitter handles profile image: [twitter.com/itzortzak](https://twitter.com/itzortzak)
If needed, try the facebook handles profile image: [fb.com/my.iTutoring](https://fb.com/my.iTutoring)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.my-itutoring.com](https://www.alexa.com/siteinfo/www.my-itutoring.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
