### ISSUE TITLE
Add 'South Lexican Translations' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1074]
Requesting to add 'South Lexican Translations' to the 'Services' category. 

Details follow: 
```yml 
- name: South Lexican Translations
      url: https://www.lexicon-translations.com
      img: 
      facebook: south.lexicon.translations
      email_address: itzortzak@gmail.com
      country: GR
      city: Kokkinos Pirgos
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.lexicon-translations.com/2018/06/bitcoin-cash-and-bitcoin-core-accepted.html
      exceptions: 
        text: "Paying a Bitcoin invoice from your wallet can be done through a Bitcoin address or a the QR Code."
```

Resources for adding this merchant:
Logo Provided:
![South Lexican Translations](https://2.bp.blogspot.com/-g3tN45pQFA0/WutoiNiCviI/AAAAAAAACiA/qT0Uxj6O2TEzDxJdJiT6vwK4DrfAHla6wCLcBGAs/s1600/Lexicon-100x70-%25CE%25B2.jpg)

[Link to South Lexican Translations](https://www.lexicon-translations.com)
If needed, try the facebook handles profile image: [fb.com/south.lexicon.translations](https://fb.com/south.lexicon.translations)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.lexicon-translations.com](https://www.alexa.com/siteinfo/www.lexicon-translations.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
