### ISSUE TITLE
Add 'CoinDeal' to the 'Cryptocurrency Exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1075]
Requesting to add 'CoinDeal' to the 'Cryptocurrency Exchange' category. 

Details follow: 
```yml 
- name: CoinDeal
      url: https://coindeal.com/
      img: 
      twitter: coin_deal
      facebook: CoinDealCom/
      email_address: katarzyna.pergol@coindeal.com
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://frontend.coindeal.com/market/trade.html?pair=BCH/BTC
      exceptions: 
        text: "No"
```

Resources for adding this merchant:
Logo Provided:
![CoinDeal](https://coindeal.com/images/logo-circle.svg)

[Link to CoinDeal](https://coindeal.com/)
If needed, try the twitter handles profile image: [twitter.com/coin_deal](https://twitter.com/coin_deal)
If needed, try the facebook handles profile image: [fb.com/CoinDealCom/](https://fb.com/CoinDealCom/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/coindeal.com/](https://www.alexa.com/siteinfo/coindeal.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
