### ISSUE TITLE
Add 'www.mojave.cafe' to the 'General' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1076]
Requesting to add 'www.mojave.cafe' to the 'General' category. 

Details follow: 
```yml 
- name: www.mojave.cafe
      url: https://www.mojave.cafe
      img: 
      email_address: info@mojave.cafe
      region: na
      country: US
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to www.mojave.cafe](https://www.mojave.cafe)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.mojave.cafe](https://www.alexa.com/siteinfo/www.mojave.cafe)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
