### ISSUE TITLE
Add 'Satoshi Game' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1077]
Requesting to add 'Satoshi Game' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Satoshi Game
      url: https://satoshi.game
      img: 
      twitter: SatoshiGameVip
      facebook: satoshigamevip
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Satoshi Game](https://pbs.twimg.com/profile_images/949982906746789889/6q_3fwjh_400x400.jpg)

[Link to Satoshi Game](https://satoshi.game)
If needed, try the twitter handles profile image: [twitter.com/SatoshiGameVip](https://twitter.com/SatoshiGameVip)
If needed, try the facebook handles profile image: [fb.com/satoshigamevip](https://fb.com/satoshigamevip)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/satoshi.game](https://www.alexa.com/siteinfo/satoshi.game)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
