### ISSUE TITLE
Add 'Baron Fig' to the 'High quality paper notebooks, pens, & backpacks.' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1078]
Requesting to add 'Baron Fig' to the 'High quality paper notebooks, pens, & backpacks.' category. 

Details follow: 
```yml 
- name: Baron Fig
      url: https://www.baronfig.com/
      img: 
      twitter: baronfig
      facebook: baronfig
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Baron Fig](https://cdn.shopify.com/s/files/1/0543/1257/t/30/assets/baron-fig_logo_fig-wine_01.svg?4053066089918738554)

[Link to Baron Fig](https://www.baronfig.com/)
If needed, try the twitter handles profile image: [twitter.com/baronfig](https://twitter.com/baronfig)
If needed, try the facebook handles profile image: [fb.com/baronfig](https://fb.com/baronfig)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.baronfig.com/](https://www.alexa.com/siteinfo/www.baronfig.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
