### ISSUE TITLE
Add 'bchvenezuela' to the 'Donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1082]
Requesting to add 'bchvenezuela' to the 'Donations' category. 

Details follow: 
```yml 
- name: bchvenezuela
      url: https://twitter.com/bchvenezuela
      img: 
      twitter: bchvenezuela
      email_address: bitcoincashve01798@gmail.com
      region: sa
      country: VE
      city: Caracas
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.yours.org/content/crowdfunding-for-the-home-for-the-elderly-padre-machado-c2c23a94c71f
```

Resources for adding this merchant:
Logo Provided:
![bchvenezuela](https://pbs.twimg.com/profile_images/1007120290915201024/IdCkIKZd_400x400.jpg)

[Link to bchvenezuela](https://twitter.com/bchvenezuela)
If needed, try the twitter handles profile image: [twitter.com/bchvenezuela](https://twitter.com/bchvenezuela)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/twitter.com/bchvenezuela](https://www.alexa.com/siteinfo/twitter.com/bchvenezuela)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
