### ISSUE TITLE
BitcoinCash Explorer bot Telegram

### ISSUE THREAD

**Issue by JMilkan** [acceptbitcoincash/acceptbitcoincash#1083]
---------------
Requesting to add {{**BitcoinCash Explorer bot**}} to the {{**Donations**}} category. Details follow:

```yml

- name: BitcoinCash Explorer
  url: https://telegram.me/BitcionCashExplorer_bot
  bch: yes
  btc: no
  othercrypto: no
  
```

Resources for adding this merchant: https://telegram.me/BitcoinCashExplorer_bot

Logo:
![a](https://user-images.githubusercontent.com/39765589/41896834-f573a428-7925-11e8-936f-0c1ca8bb4e36.png)
