### ISSUE TITLE
Add 'Bitcoin Cash Football' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1086]
Requesting to add 'Bitcoin Cash Football' to the 'Gaming' category. 

Details follow: 
```yml 
- name: Bitcoin Cash Football
      url: https://BitcoinCashFootball.com/
      img: 
      twitter: PeanutManEric
      email_address: Eric@BitcoinCashFootball.com
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Bitcoin Cash Football](https://BitcoinCashFootball.com/images/logo.png)

[Link to Bitcoin Cash Football](https://BitcoinCashFootball.com/)
If needed, try the twitter handles profile image: [twitter.com/PeanutManEric](https://twitter.com/PeanutManEric)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/BitcoinCashFootball.com/](https://www.alexa.com/siteinfo/BitcoinCashFootball.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
