### ISSUE TITLE
Add 'PETER EDWARD' to the 'Bitcoin ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1087]
Requesting to add 'PETER EDWARD' to the 'Bitcoin ' category. 

Details follow: 
```yml 
- name: PETER EDWARD
      url: https://bws.bitcoin.com/bws/api
      img: 
      twitter: Haveno twitter 
      facebook: Yes
      email_address: peter_degerman92@hotmail.se
      region: sa
      country: BF
      city: SKELLEFTEÅ
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to PETER EDWARD](https://bws.bitcoin.com/bws/api)
If needed, try the twitter handles profile image: [twitter.com/Haveno twitter ](https://twitter.com/Haveno twitter )
If needed, try the facebook handles profile image: [fb.com/Yes](https://fb.com/Yes)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bws.bitcoin.com/bws/api](https://www.alexa.com/siteinfo/bws.bitcoin.com/bws/api)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
