### ISSUE TITLE
Add 'BCHPLS.io' to the 'Point of Sale system' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1090]
Requesting to add 'BCHPLS.io' to the 'Point of Sale system' category. 

Details follow: 
```yml 
- name: BCHPLS.io
      url: https://bchpls.io/
      img: bchplsPOS.png
      twitter: bchplsPOS
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![BCHPLS.io](https://twitter.com/bchplsPOS)

[Link to BCHPLS.io](https://bchpls.io/)
If needed, try the twitter handles profile image: [twitter.com/bchplsPOS](https://twitter.com/bchplsPOS)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bchpls.io/](https://www.alexa.com/siteinfo/bchpls.io/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bchpls.io/](https://www.scamadviser.com/check-website/bchpls.io/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bchpls.io/](https://www.trustpilot.com/review/bchpls.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
