### ISSUE TITLE
Add 'purse.io' to the 'Merchant' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1091]
Requesting to add 'purse.io' to the 'Merchant' category. 

Details follow: 
```yml 
- name: purse.io
      url: https://purse.io
      img: 
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://twitter.com/PurseIO/status/1011869616522649605?s=19
```

Resources for adding this merchant:
[Link to purse.io](https://purse.io)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/purse.io](https://www.alexa.com/siteinfo/purse.io)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/purse.io](https://www.scamadviser.com/check-website/purse.io)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/purse.io](https://www.trustpilot.com/review/purse.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
