### ISSUE TITLE
Add 'fancy.com' to the 'Retail/online merchant' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1092]
Requesting to add 'fancy.com' to the 'Retail/online merchant' category. 

Details follow: 
```yml 
- name: fancy.com
      url: https://fancy.com
      img: 
      twitter: fancy
      facebook: Fancy
      email_address: hello@fancy.com
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://modernconsensus.com/cryptocurrencies/bitcoin/fancy-coinbase-bitpay-bitcoin-cash/
      keywords:
      - bitpay
```

Resources for adding this merchant:
Logo Provided:
![fancy.com](https://pbs.twimg.com/profile_images/468935020732624896/qOgbupyh_400x400.png)

[Link to fancy.com](https://fancy.com)
If needed, try the twitter handles profile image: [twitter.com/fancy?lang=en](https://twitter.com/fancy?lang=en)
If needed, try the facebook handles profile image: [fb.com/Fancy/](https://fb.com/Fancy/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/fancy.com](https://www.alexa.com/siteinfo/fancy.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/fancy.com](https://www.scamadviser.com/check-website/fancy.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/fancy.com](https://www.trustpilot.com/review/fancy.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
