### ISSUE TITLE
Add 'BCHPLS.io' to the 'Point-of-sale solutions' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1093]
Requesting to add 'BCHPLS.io' to the 'Point-of-sale solutions' category. 

Details follow: 
```yml 
- name: BCHPLS.io
      url: https://bchpls.io/
      img: 
      twitter: bchplsPOS
      email_address: support@bchpls.io
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/8lkfym/bchplsio_a_free_bitcoin_cash_pointofsale_system/
```

Resources for adding this merchant:
Logo Provided:
![BCHPLS.io](https://bchpls.io/wp-content/uploads/2018/06/logo-icon-511x511-1-e1530169635450.png)

[Link to BCHPLS.io](https://bchpls.io/)
If needed, try the twitter handles profile image: [twitter.com/bchplsPOS](https://twitter.com/bchplsPOS)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bchpls.io/](https://www.alexa.com/siteinfo/bchpls.io/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bchpls.io/](https://www.scamadviser.com/check-website/bchpls.io/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bchpls.io/](https://www.trustpilot.com/review/bchpls.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
