### ISSUE TITLE
Add 'BCHBrand.com' to the 'Apparel ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1094]
Requesting to add 'BCHBrand.com' to the 'Apparel ' category. 

Details follow: 
```yml 
- name: BCHBrand.com
      url: https://www.bchbrand.com
      img: bchbrand.png
      twitter: bchbrand
      facebook: bchpls
      email_address: bchbrand@gmail.com
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/bchbrand/status/1012390120018923523
```

Resources for adding this merchant:
Logo Provided:
![BCHBrand.com](https://pbs.twimg.com/profile_images/1012388200243871744/eUJrPKvz_400x400.jpg)

[Link to BCHBrand.com](https://www.bchbrand.com)
If needed, try the twitter handles profile image: [twitter.com/bchbrand](https://twitter.com/bchbrand)
If needed, try the facebook handles profile image: [fb.com/bchpls](https://fb.com/bchpls)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.bchbrand.com](https://www.alexa.com/siteinfo/www.bchbrand.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.bchbrand.com](https://www.scamadviser.com/check-website/www.bchbrand.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.bchbrand.com](https://www.trustpilot.com/review/www.bchbrand.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
