### ISSUE TITLE
Add 'VPN SURF' to the 'VPN' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1097]
Requesting to add 'VPN SURF' to the 'VPN' category. 

Details follow: 
```yml 
- name: VPN SURF
      url: https://vpn.surf
      img: 
      email_address: sales@vpn.surf
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to VPN SURF](https://vpn.surf)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/vpn.surf](https://www.alexa.com/siteinfo/vpn.surf)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/vpn.surf](https://www.scamadviser.com/check-website/vpn.surf)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/vpn.surf](https://www.trustpilot.com/review/vpn.surf)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
