### ISSUE TITLE
Add 'Coini Shoes' to the 'Clothing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1098]
Requesting to add 'Coini Shoes' to the 'Clothing' category. 

Details follow: 
```yml 
- name: Coini Shoes
      url: https://coinish.online/
      email_address: sales@coinish.online
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Coini Shoes](https://prnt.sc/k1kdnp)

[Link to Coini Shoes](https://coinish.online/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/coinish.online/](https://www.alexa.com/siteinfo/coinish.online/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/coinish.online/](https://www.scamadviser.com/check-website/coinish.online/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/coinish.online/](https://www.trustpilot.com/review/coinish.online/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
