### ISSUE TITLE
Add 'RealityRipple Software' to the 'Software, Developer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1101]
Requesting to add 'RealityRipple Software' to the 'Software, Developer' category. 

Details follow: 
```yml 
- name: RealityRipple Software
      url: https://realityripple.com
      img: 
      email_address: webmaster@RealityRipple.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Donations accepted at <https://realityripple.com/donate.php>, purchase of Advanced Mouse Manager software at <https://realityripple.com/Software/Applications/Advanced-Mouse-Manager/>"
```

Resources for adding this merchant:
Logo Provided:
![RealityRipple Software](https://realityripple.com/favicon-96x96.png)

[Link to RealityRipple Software](https://realityripple.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/realityripple.com](https://www.alexa.com/siteinfo/realityripple.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/realityripple.com](https://www.scamadviser.com/check-website/realityripple.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/realityripple.com](https://www.trustpilot.com/review/realityripple.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
