### ISSUE TITLE
Add 'Switchain' to the 'Crypto Exchanges' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1102]
Requesting to add 'Switchain' to the 'Crypto Exchanges' category. 

Details follow: 
```yml 
- name: Switchain
      url: https://switchain.com
      img: switchaindotcom.png
      twitter: switchaindotcom
      email_address: support@switchain.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Switchain](https://pbs.twimg.com/profile_images/978296131343077376/N0nk7QRy_400x400.jpg)

[Link to Switchain](https://switchain.com)
If needed, try the twitter handles profile image: [twitter.com/switchaindotcom](https://twitter.com/switchaindotcom)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/switchain.com](https://www.alexa.com/siteinfo/switchain.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/switchain.com](https://www.scamadviser.com/check-website/switchain.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/switchain.com](https://www.trustpilot.com/review/switchain.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
