### ISSUE TITLE
Add 'Lionel Nation ' to the 'Youtube Fan shop ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1105]
Requesting to add 'Lionel Nation ' to the 'Youtube Fan shop ' category. 

Details follow: 
```yml 
- name: Lionel Nation 
      url: https://www.cafepress.com/theofficiallionelnationstore
      img: 
      bch: No
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Lionel Nation ](https://www.cafepress.com/theofficiallionelnationstore)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cafepress.com/theofficiallionelnationstore](https://www.alexa.com/siteinfo/www.cafepress.com/theofficiallionelnationstore)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.cafepress.com/theofficiallionelnationstore](https://www.scamadviser.com/check-website/www.cafepress.com/theofficiallionelnationstore)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.cafepress.com/theofficiallionelnationstore](https://www.trustpilot.com/review/www.cafepress.com/theofficiallionelnationstore)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
