### ISSUE TITLE
Add 'Spend Crypto Here' to the 'Viral Merchandise' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1106]
Requesting to add 'Spend Crypto Here' to the 'Viral Merchandise' category. 

Details follow: 
```yml 
- name: Spend Crypto Here
      url: https://spendcryptohere.com
      img: 
      facebook: Spendcryptohere
      email_address: spendceyptohere@gmail.com
      region: na
      country: US
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Spend Crypto Here](https://www.facebook.com/470427573402230/photos/a.470430176735303.1073741827.470427573402230/470430076735313/?type=3)

[Link to Spend Crypto Here](https://spendcryptohere.com)
If needed, try the facebook handles profile image: [fb.com/Spendcryptohere](https://fb.com/Spendcryptohere)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/spendcryptohere.com](https://www.alexa.com/siteinfo/spendcryptohere.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/spendcryptohere.com](https://www.scamadviser.com/check-website/spendcryptohere.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/spendcryptohere.com](https://www.trustpilot.com/review/spendcryptohere.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
