### ISSUE TITLE
Add 'Efilenka' to the 'Jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1107]
Requesting to add 'Efilenka' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: Efilenka
      url: https://t.me/Efilenka
      img: 
      facebook: profile.php?id=100012520656584
      email_address: morenita250685@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://t.me/Efilenka
```

Resources for adding this merchant:
Logo Provided:
![Efilenka](https://pp.userapi.com/c631620/v631620275/44b95/vURtMG8mz0Q.jpg)

[Link to Efilenka](https://t.me/Efilenka)
If needed, try the facebook handles profile image: [fb.com/profile.php?id=100012520656584](https://fb.com/profile.php?id=100012520656584)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/t.me/Efilenka](https://www.alexa.com/siteinfo/t.me/Efilenka)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/t.me/Efilenka](https://www.scamadviser.com/check-website/t.me/Efilenka)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/t.me/Efilenka](https://www.trustpilot.com/review/t.me/Efilenka)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
