### ISSUE TITLE
Add 'MaxVaping' to the 'Vaping Supplies' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1108]
Requesting to add 'MaxVaping' to the 'Vaping Supplies' category. 

Details follow: 
```yml 
- name: MaxVaping
      url: https://maxvaping.com/
      img: 
      twitter: MaxVapingStore
      facebook: MaxVapingStore
      email_address: phil@maxvaping.com
      region: na
      country: US
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://maxvaping.com/pages/bitcoin-vaping-supplies
      exceptions: 
        text: "No"
```

Resources for adding this merchant:
Logo Provided:
![MaxVaping](https://cdn.shopify.com/s/files/1/0213/2688/files/mv-logo-500.jpg)

[Link to MaxVaping](https://maxvaping.com/)
If needed, try the twitter handles profile image: [twitter.com/MaxVapingStore](https://twitter.com/MaxVapingStore)
If needed, try the facebook handles profile image: [fb.com/MaxVapingStore](https://fb.com/MaxVapingStore)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/maxvaping.com/](https://www.alexa.com/siteinfo/maxvaping.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/maxvaping.com/](https://www.scamadviser.com/check-website/maxvaping.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/maxvaping.com/](https://www.trustpilot.com/review/maxvaping.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
