### ISSUE TITLE
Add 'MaxeJuice' to the 'Vape Juice e-Liquid' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1109]
Requesting to add 'MaxeJuice' to the 'Vape Juice e-Liquid' category. 

Details follow: 
```yml 
- name: MaxeJuice
      url: https://maxejuice.com/
      img: 
      twitter: MaxVapingStore
      facebook: MaxVapingStore
      email_address: phil@maxvaping.com
      region: na
      country: US
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://maxejuice.com/pages/bitcoin-eliquid
      exceptions: 
        text: "No"
```

Resources for adding this merchant:
Logo Provided:
![MaxeJuice](https://cdn.shopify.com/s/files/1/0660/0031/files/mv-logo-500.jpg)

[Link to MaxeJuice](https://maxejuice.com/)
If needed, try the twitter handles profile image: [twitter.com/MaxVapingStore](https://twitter.com/MaxVapingStore)
If needed, try the facebook handles profile image: [fb.com/MaxVapingStore](https://fb.com/MaxVapingStore)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/maxejuice.com/](https://www.alexa.com/siteinfo/maxejuice.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/maxejuice.com/](https://www.scamadviser.com/check-website/maxejuice.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/maxejuice.com/](https://www.trustpilot.com/review/maxejuice.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
