### ISSUE TITLE
Add 'Smart Bitcoin Investments' to the 'Finance Blog' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1115]
Requesting to add 'Smart Bitcoin Investments' to the 'Finance Blog' category. 

Details follow: 
```yml 
- name: Smart Bitcoin Investments
      url: https://www.smartbitcoininvestments.com/
      img: 
      twitter: 401kbitcoin
      facebook: CryptocurrencyIRA
      email_address: info@smartbitcoininvestments.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.smartbitcoininvestments.com/
```

Resources for adding this merchant:
Logo Provided:
![Smart Bitcoin Investments](https://pbs.twimg.com/profile_images/963290894089650176/eGH8Eqk-_400x400.jpg)

[Link to Smart Bitcoin Investments](https://www.smartbitcoininvestments.com/)
If needed, try the twitter handles profile image: [twitter.com/401kbitcoin](https://twitter.com/401kbitcoin)
If needed, try the facebook handles profile image: [fb.com/CryptocurrencyIRA](https://fb.com/CryptocurrencyIRA)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.smartbitcoininvestments.com/](https://www.alexa.com/siteinfo/www.smartbitcoininvestments.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.smartbitcoininvestments.com/](https://www.scamadviser.com/check-website/www.smartbitcoininvestments.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.smartbitcoininvestments.com/](https://www.trustpilot.com/review/www.smartbitcoininvestments.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
