### ISSUE TITLE
Add 'Eyerim' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1116]
Requesting to add 'Eyerim' to the 'Retail' category. 

Details follow: 
```yml 
- name: Eyerim
      url: https://www.eyerim.cz/
      img: 
      region: eu
      country: CZ
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "via BitPay"
```

Resources for adding this merchant:
Logo Provided:
![Eyerim](https://d2yf2khfiwi4te.cloudfront.net/skin/frontend/eyerim/default/images/eyerim-logo.svg)

[Link to Eyerim](https://www.eyerim.cz/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.eyerim.cz/](https://www.alexa.com/siteinfo/www.eyerim.cz/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.eyerim.cz/](https://www.scamadviser.com/check-website/www.eyerim.cz/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.eyerim.cz/](https://www.trustpilot.com/review/www.eyerim.cz/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
