### ISSUE TITLE
Add 'Mission Belt' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1121]
Requesting to add 'Mission Belt' to the 'Retail' category. 

Details follow: 
```yml 
- name: Mission Belt
      url: https://missionbelt.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Mission Belt](https://missionbelt.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/missionbelt.com](https://www.alexa.com/siteinfo/missionbelt.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/missionbelt.com](https://www.scamadviser.com/check-website/missionbelt.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/missionbelt.com](https://www.trustpilot.com/review/missionbelt.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
