### ISSUE TITLE
Add 'www.ibuypokemon.com' to the 'Pokemon TCG' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1122]
Requesting to add 'www.ibuypokemon.com' to the 'Pokemon TCG' category. 

Details follow: 
```yml 
- name: www.ibuypokemon.com
      url: https://www.ibuypokemon.com
      img: 
      facebook: facebook.com/ibuypokemon
      email_address: ibuypokemoncom@gmail.com
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![www.ibuypokemon.com](https://cdn.shopify.com/s/files/1/2369/8865/files/IbuyPokemonlogo_ae458b47-035a-4d16-8c86-e8acdd34964f_360x.jpg?v=1507515967)

[Link to www.ibuypokemon.com](https://www.ibuypokemon.com)
If needed, try the facebook handles profile image: [fb.com/facebook.com/ibuypokemon](https://fb.com/facebook.com/ibuypokemon)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.ibuypokemon.com](https://www.alexa.com/siteinfo/www.ibuypokemon.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.ibuypokemon.com](https://www.scamadviser.com/check-website/www.ibuypokemon.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.ibuypokemon.com](https://www.trustpilot.com/review/www.ibuypokemon.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
