### ISSUE TITLE
Add 'CashPay' to the 'Spend and Replace Wallet' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1123]
Requesting to add 'CashPay' to the 'Spend and Replace Wallet' category. 

Details follow: 
```yml 
- name: CashPay
      url: https://www.cashpay.solutions/how-to-enable-spend-and-replace/
      img: 
      twitter: CashPayWallet
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://twitter.com/CashPayWallet/status/1015524837643743232
      exceptions: 
        text: "Must have a coinbase.com account"
```

Resources for adding this merchant:
Logo Provided:
![CashPay](https://pbs.twimg.com/profile_images/1012680688372469760/lJSvOoIF_400x400.jpg)

[Link to CashPay](https://www.cashpay.solutions/how-to-enable-spend-and-replace/)
If needed, try the twitter handles profile image: [twitter.com/CashPayWallet](https://twitter.com/CashPayWallet)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cashpay.solutions/how-to-enable-spend-and-replace/](https://www.alexa.com/siteinfo/www.cashpay.solutions/how-to-enable-spend-and-replace/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.cashpay.solutions/how-to-enable-spend-and-replace/](https://www.scamadviser.com/check-website/www.cashpay.solutions/how-to-enable-spend-and-replace/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.cashpay.solutions/how-to-enable-spend-and-replace/](https://www.trustpilot.com/review/www.cashpay.solutions/how-to-enable-spend-and-replace/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
