### ISSUE TITLE
Add 'La Casa Del Habano' to the 'Merchant (Cuban Cigars)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1124]
Requesting to add 'La Casa Del Habano' to the 'Merchant (Cuban Cigars)' category. 

Details follow: 
```yml 
- name: La Casa Del Habano
      url: http://www.lcdh.com/
      img: 
      twitter: lcdhstkitts?lang=en
      facebook: lcdhstkitts/
      email_address: info@lcdh.kn
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/8wwvyt/la_casa_del_habano_st_kitts_authentic_cuban/
```

Resources for adding this merchant:
Logo Provided:
![La Casa Del Habano](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-1/p200x200/31530948_1924578110937457_7753743724059820032_n.jpg?_nc_cat=0&oh=2d991683446aaa33cacd54f27f1f05fa&oe=5BD8CA11)

[Link to La Casa Del Habano](http://www.lcdh.com/)
If needed, try the twitter handles profile image: [twitter.com/lcdhstkitts?lang=en](https://twitter.com/lcdhstkitts?lang=en)
If needed, try the facebook handles profile image: [fb.com/lcdhstkitts/](https://fb.com/lcdhstkitts/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.lcdh.com/](https://www.alexa.com/siteinfo/www.lcdh.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.lcdh.com/](https://www.scamadviser.com/check-website/www.lcdh.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.lcdh.com/](https://www.trustpilot.com/review/www.lcdh.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
