### ISSUE TITLE
Add 'La Casa Del Habano St. Kittd' to the 'Cuban Cigars' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1125]
Requesting to add 'La Casa Del Habano St. Kittd' to the 'Cuban Cigars' category. 

Details follow: 
```yml 
- name: La Casa Del Habano St. Kittd
      url: https://www.lcdh.com
      img: 
      twitter: lcdhstkitts
      facebook: lcdhstkitts
      email_address: info@lcdh.com
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.instagram.com/p/Bk_UHxLFzSr/
      exceptions: 
        text: "At checkout choose Pay with Bitcoin Cash, then scan the QR Code with your Bitcoin Cash wallet to pay."
```

Resources for adding this merchant:
Logo Provided:
![La Casa Del Habano St. Kittd](https://www.lacasadelhabano.kn/wp-content/uploads/2018/07/lcdh400x400.jpg)

[Link to La Casa Del Habano St. Kittd](https://www.lcdh.com)
If needed, try the twitter handles profile image: [twitter.com/lcdhstkitts](https://twitter.com/lcdhstkitts)
If needed, try the facebook handles profile image: [fb.com/lcdhstkitts](https://fb.com/lcdhstkitts)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.lcdh.com](https://www.alexa.com/siteinfo/www.lcdh.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.lcdh.com](https://www.scamadviser.com/check-website/www.lcdh.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.lcdh.com](https://www.trustpilot.com/review/www.lcdh.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
