### ISSUE TITLE
Add 'Locks Keys and More' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1126]
Requesting to add 'Locks Keys and More' to the 'Services' category. 

Details follow: 
```yml 
- name: Locks Keys and More
      url: https://lockskeysandmore.com
      img: 
      facebook: lockskeysandmore
      email_address: lockskeysandmore@gmail.com
      region: na
      country: US
      city: El Paso, Texas
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Locks Keys and More](https://lockskeysandmore.com)
If needed, try the facebook handles profile image: [fb.com/lockskeysandmore](https://fb.com/lockskeysandmore)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/lockskeysandmore.com](https://www.alexa.com/siteinfo/lockskeysandmore.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/lockskeysandmore.com](https://www.scamadviser.com/check-website/lockskeysandmore.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/lockskeysandmore.com](https://www.trustpilot.com/review/lockskeysandmore.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
