### ISSUE TITLE
Requesting to add Ghost Gunner to the Retail category.

### ISSUE THREAD

**Issue by eronstrom** [acceptbitcoincash/acceptbitcoincash#1127]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add Ghost Gunner to the Retail category. Details follow:

```yml

- name: Ghost Gunner
  url: https://ghostgunner.net
  img: https://cdn.shopify.com/s/files/1/0206/7642/t/5/assets/logo.png?10751136393498116884
  twitter: DefDist
  facebook: DefenseDistributed
  region: na
  country: us
  bch: yes
  btc: yes
  othercrypto: yes
```
