### ISSUE TITLE
Add 'Gully Flip' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1130]
Requesting to add 'Gully Flip' to the 'Retail' category. 

Details follow: 
```yml 
- name: Gully Flip
      url: https://gullyflip.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Gully Flip](https://gullyflip.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/gullyflip.com](https://www.alexa.com/siteinfo/gullyflip.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/gullyflip.com](https://www.scamadviser.com/check-website/gullyflip.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/gullyflip.com](https://www.trustpilot.com/review/gullyflip.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
