### ISSUE TITLE
Add 'Putlockers4u' to the 'Media' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1131]
Requesting to add 'Putlockers4u' to the 'Media' category. 

Details follow: 
```yml 
- name: Putlockers4u
      url: https://putlockers4u.com
      img: 
      twitter: putlockers4u
      email_address: putlockers4u.com@gmail.com
      region: eu
      city: NeYork
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Putlockers4u](http://putlockers4u.com/img/video.png)

[Link to Putlockers4u](https://putlockers4u.com)
If needed, try the twitter handles profile image: [twitter.com/putlockers4u](https://twitter.com/putlockers4u)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/putlockers4u.com](https://www.alexa.com/siteinfo/putlockers4u.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/putlockers4u.com](https://www.scamadviser.com/check-website/putlockers4u.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/putlockers4u.com](https://www.trustpilot.com/review/putlockers4u.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
