### ISSUE TITLE
Add 'senang.online' to the 'Internet Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1132]
Requesting to add 'senang.online' to the 'Internet Services' category. 

Details follow: 
```yml 
- name: senang.online
      url: https://web.senang.online
      img: 
      twitter: senangonline
      facebook: senangdotonline
      email_address: so@senang.online
      country: MY
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://web.senang.online/support
      exceptions: 
        text: "Link to complete payment at Support page"
```

Resources for adding this merchant:
Logo Provided:
![senang.online](https://web.senang.online/getImage.php?src=logo.gif)

[Link to senang.online](https://web.senang.online)
If needed, try the twitter handles profile image: [twitter.com/senangonline](https://twitter.com/senangonline)
If needed, try the facebook handles profile image: [fb.com/senangdotonline](https://fb.com/senangdotonline)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/web.senang.online](https://www.alexa.com/siteinfo/web.senang.online)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/web.senang.online](https://www.scamadviser.com/check-website/web.senang.online)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/web.senang.online](https://www.trustpilot.com/review/web.senang.online)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
