### ISSUE TITLE
Add 'Betty's Place' to the 'Restaurant ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1133]
Requesting to add 'Betty's Place' to the 'Restaurant ' category. 

Details follow: 
```yml 
- name: Betty's Place
      url: https://www.businessdailyafrica.com/news/counties/Bitcoins-take-root-in-Nyeri-town-despite-CBK-warning/4003142-4648456-7mcqpcz/index.html
      img: 
      region: af
      country: KE
      city: Nyeri
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Betty's Place](https://www.businessdailyafrica.com/news/counties/Bitcoins-take-root-in-Nyeri-town-despite-CBK-warning/4003142-4648456-7mcqpcz/index.html)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.businessdailyafrica.com/news/counties/Bitcoins-take-root-in-Nyeri-town-despite-CBK-warning/4003142-4648456-7mcqpcz/index.html](https://www.alexa.com/siteinfo/www.businessdailyafrica.com/news/counties/Bitcoins-take-root-in-Nyeri-town-despite-CBK-warning/4003142-4648456-7mcqpcz/index.html)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.businessdailyafrica.com/news/counties/Bitcoins-take-root-in-Nyeri-town-despite-CBK-warning/4003142-4648456-7mcqpcz/index.html](https://www.scamadviser.com/check-website/www.businessdailyafrica.com/news/counties/Bitcoins-take-root-in-Nyeri-town-despite-CBK-warning/4003142-4648456-7mcqpcz/index.html)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.businessdailyafrica.com/news/counties/Bitcoins-take-root-in-Nyeri-town-despite-CBK-warning/4003142-4648456-7mcqpcz/index.html](https://www.trustpilot.com/review/www.businessdailyafrica.com/news/counties/Bitcoins-take-root-in-Nyeri-town-despite-CBK-warning/4003142-4648456-7mcqpcz/index.html)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
