### ISSUE TITLE
Add 'MARDUK.io' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1135]
Requesting to add 'MARDUK.io' to the 'Gambling' category. 

Details follow: 
```yml 
- name: MARDUK.io
      url: https://MARDUK.io
      img: 
      email_address: info@marduk.io
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![MARDUK.io](https://marduk.io/img/small_logo.png)

[Link to MARDUK.io](https://MARDUK.io)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/MARDUK.io](https://www.alexa.com/siteinfo/MARDUK.io)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/MARDUK.io](https://www.scamadviser.com/check-website/MARDUK.io)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/MARDUK.io](https://www.trustpilot.com/review/MARDUK.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
