### ISSUE TITLE
Add 'Crypto and Tech Gear' to the 'Apparel/Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1136]
Requesting to add 'Crypto and Tech Gear' to the 'Apparel/Accessories' category. 

Details follow: 
```yml 
- name: Crypto and Tech Gear
      url: https://cryptoandtechgear.com/
      img: 
      facebook: Cryptoand Tech Gear
      email_address: btcltcethmerch@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/8syam5/check_out_my_apparel_website_i_am_expanding_my/
      exceptions: 
        text: "Select Coinbase Commerce or CoinPayments at checkout"
```

Resources for adding this merchant:
Logo Provided:
![Crypto and Tech Gear](http://tinypic.com/r/vie32r/9)

[Link to Crypto and Tech Gear](https://cryptoandtechgear.com/)
If needed, try the facebook handles profile image: [fb.com/Cryptoand Tech Gear](https://fb.com/Cryptoand Tech Gear)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/cryptoandtechgear.com/](https://www.alexa.com/siteinfo/cryptoandtechgear.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/cryptoandtechgear.com/](https://www.scamadviser.com/check-website/cryptoandtechgear.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/cryptoandtechgear.com/](https://www.trustpilot.com/review/cryptoandtechgear.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
