### ISSUE TITLE
Add 'Crypto Pro Shop' to the 'Cryptocurrency Apparel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1137]
Requesting to add 'Crypto Pro Shop' to the 'Cryptocurrency Apparel' category. 

Details follow: 
```yml 
- name: Crypto Pro Shop
      url: https://cryptopro.shop
      img: 
      twitter: Crypto_Pro_Shop
      facebook: TheCryptoProShop
      email_address: social.media@cryptopro.shop
      country: US
      city: Denver
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://cryptopro.shop/cryptocurrency-clothing-store/
      exceptions: 
        text: "Upon placing your order, an email will be sent from CoinPayments.net regarding how much BCH to send and to what address.  When the BCH is received, your order will be processed."
```

Resources for adding this merchant:
Logo Provided:
![Crypto Pro Shop](https://storage.googleapis.com/crypto-pro-shop-cdn/2018/07/1d4ce63e-cps-1x1-128px.png)

[Link to Crypto Pro Shop](https://cryptopro.shop)
If needed, try the twitter handles profile image: [twitter.com/Crypto_Pro_Shop](https://twitter.com/Crypto_Pro_Shop)
If needed, try the facebook handles profile image: [fb.com/TheCryptoProShop](https://fb.com/TheCryptoProShop)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/cryptopro.shop](https://www.alexa.com/siteinfo/cryptopro.shop)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/cryptopro.shop](https://www.scamadviser.com/check-website/cryptopro.shop)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/cryptopro.shop](https://www.trustpilot.com/review/cryptopro.shop)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
