### ISSUE TITLE
Add 'Findmate' to the 'Social/Dating' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1138]
Requesting to add 'Findmate' to the 'Social/Dating' category. 

Details follow: 
```yml 
- name: Findmate
      url: https://findmate.app/
      img: 
      twitter: FindmateApp
      facebook: FindmateApp
      email_address: findmate.asia@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://findmate.app/content/bitcoin
```

Resources for adding this merchant:
Logo Provided:
![Findmate](https://findmate.app//favicons/favicon-128.png)

[Link to Findmate](https://findmate.app/)
If needed, try the twitter handles profile image: [twitter.com/FindmateApp](https://twitter.com/FindmateApp)
If needed, try the facebook handles profile image: [fb.com/FindmateApp](https://fb.com/FindmateApp)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/findmate.app/](https://www.alexa.com/siteinfo/findmate.app/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/findmate.app/](https://www.scamadviser.com/check-website/findmate.app/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/findmate.app/](https://www.trustpilot.com/review/findmate.app/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
