### ISSUE TITLE
Add 'Protosbay' to the 'Ecommerce' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1139]
Requesting to add 'Protosbay' to the 'Ecommerce' category. 

Details follow: 
```yml 
- name: Protosbay
      url: https://www.protosbay.com
      img: 
      twitter: protosbay
      facebook: protosbay
      email_address: admin@protosbay.com
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/8yap0y/bitcoin_cash_now_on_protosbay_amazon_ebay_but/
```

Resources for adding this merchant:
[Link to Protosbay](https://www.protosbay.com)
If needed, try the twitter handles profile image: [twitter.com/protosbay](https://twitter.com/protosbay)
If needed, try the facebook handles profile image: [fb.com/protosbay](https://fb.com/protosbay)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.protosbay.com](https://www.alexa.com/siteinfo/www.protosbay.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.protosbay.com](https://www.scamadviser.com/check-website/www.protosbay.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.protosbay.com](https://www.trustpilot.com/review/www.protosbay.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
