### ISSUE TITLE
Add 'Bitzillions' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1140]
Requesting to add 'Bitzillions' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Bitzillions
      url: https://bitzillions.com
      img: 
      twitter: SatoshiBones
      email_address: contact@bitzillions.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://medium.com/@bitzillions/bitcoin-cash-lessons-from-a-block-size-canary-db4a7f020d7
      exceptions: 
        text: "SatoshiBones 1 is played on-chain with BCH (no BTC).   For off-chain BCH please use cash address format."
```

Resources for adding this merchant:
Logo Provided:
![Bitzillions](https://onchain.bitzillions.com/satoshibones/images/bitzillions_logo_128_128.png)

[Link to Bitzillions](https://bitzillions.com)
If needed, try the twitter handles profile image: [twitter.com/SatoshiBones](https://twitter.com/SatoshiBones)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bitzillions.com](https://www.alexa.com/siteinfo/bitzillions.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bitzillions.com](https://www.scamadviser.com/check-website/bitzillions.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bitzillions.com](https://www.trustpilot.com/review/bitzillions.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
