### ISSUE TITLE
Add 'Uptown Aces' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1141]
Requesting to add 'Uptown Aces' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Uptown Aces
      url: https://uptownaces.eu/
      img: 
      facebook: uptownaces/
      email_address: support@uptownaces.eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://uptownaces.eu/banking/deposit-methods
```

Resources for adding this merchant:
Logo Provided:
![Uptown Aces](https://www.facebook.com/uptownaces/photos/a.414763728673357.1073741825.414762875340109/414763745340022/?type=1&theater)

[Link to Uptown Aces](https://uptownaces.eu/)
If needed, try the facebook handles profile image: [fb.com/uptownaces/](https://fb.com/uptownaces/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/uptownaces.eu/](https://www.alexa.com/siteinfo/uptownaces.eu/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/uptownaces.eu/](https://www.scamadviser.com/check-website/uptownaces.eu/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/uptownaces.eu/](https://www.trustpilot.com/review/uptownaces.eu/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
