### ISSUE TITLE
Add 'Crypto Wild' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1142]
Requesting to add 'Crypto Wild' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Crypto Wild
      url: https://www.cryptowild.com/
      img: 
      twitter: CryptoWild777
      facebook: CryptoWild/
      email_address: support@cryptowild.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://usethebitcoin.com/cryptowild-the-newest-online-casino-accepts-bitcoin-litecoin-bitcoin-cash-and-ethereum/
```

Resources for adding this merchant:
Logo Provided:
![Crypto Wild](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-1/p200x200/30442738_481798572235821_5036634716963340288_n.jpg?_nc_cat=0&oh=a505cc09bd40a6b67f33cdb9bc1508f2&oe=5BE6F40E)

[Link to Crypto Wild](https://www.cryptowild.com/)
If needed, try the twitter handles profile image: [twitter.com/CryptoWild777](https://twitter.com/CryptoWild777)
If needed, try the facebook handles profile image: [fb.com/CryptoWild/](https://fb.com/CryptoWild/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cryptowild.com/](https://www.alexa.com/siteinfo/www.cryptowild.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.cryptowild.com/](https://www.scamadviser.com/check-website/www.cryptowild.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.cryptowild.com/](https://www.trustpilot.com/review/www.cryptowild.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
