### ISSUE TITLE
Add 'Betchain' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1143]
Requesting to add 'Betchain' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Betchain
      url: https://www.betchain.com/
      img: 
      twitter: betchain?lang=en
      facebook: BetChain/
      email_address: support@betchain.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.betchain.com/payment-methods
```

Resources for adding this merchant:
Logo Provided:
![Betchain](https://pbs.twimg.com/profile_images/418696131292299264/hzbK5KMP_400x400.png)

[Link to Betchain](https://www.betchain.com/)
If needed, try the twitter handles profile image: [twitter.com/betchain?lang=en](https://twitter.com/betchain?lang=en)
If needed, try the facebook handles profile image: [fb.com/BetChain/](https://fb.com/BetChain/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.betchain.com/](https://www.alexa.com/siteinfo/www.betchain.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.betchain.com/](https://www.scamadviser.com/check-website/www.betchain.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.betchain.com/](https://www.trustpilot.com/review/www.betchain.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
