### ISSUE TITLE
Add 'Sloto'Cash' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1144]
Requesting to add 'Sloto'Cash' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Sloto'Cash
      url: https://www.slotocash.im/en
      img: 
      facebook: SlotoCash.Casino/
      email_address: support@slotocash.im
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.slotocash.im/en/banking/deposit-methods
      exceptions: 
        text: "Deposits only. Withdrawals must be in other coins."
```

Resources for adding this merchant:
Logo Provided:
![Sloto'Cash](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-1/p200x200/16938458_1351433481587612_288646406611468696_n.jpg?_nc_cat=0&oh=230e0f370220b6867fb38fb433c45a26&oe=5BE1D433)

[Link to Sloto'Cash](https://www.slotocash.im/en)
If needed, try the facebook handles profile image: [fb.com/SlotoCash.Casino/](https://fb.com/SlotoCash.Casino/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.slotocash.im/en](https://www.alexa.com/siteinfo/www.slotocash.im/en)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.slotocash.im/en](https://www.scamadviser.com/check-website/www.slotocash.im/en)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.slotocash.im/en](https://www.trustpilot.com/review/www.slotocash.im/en)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
