### ISSUE TITLE
Add 'FortuneJack' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1145]
Requesting to add 'FortuneJack' to the 'Gambling' category. 

Details follow: 
```yml 
- name: FortuneJack
      url: https://fortunejack.com/
      img: 
      twitter: fortunejackcom?lang=en
      facebook: fjcasino/
      email_address: support@fortunejack.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://fortunejack.com/bitcoincash-gambling
```

Resources for adding this merchant:
Logo Provided:
![FortuneJack](https://pbs.twimg.com/profile_images/798591262324617216/EaVDxTJ-_400x400.jpg)

[Link to FortuneJack](https://fortunejack.com/)
If needed, try the twitter handles profile image: [twitter.com/fortunejackcom?lang=en](https://twitter.com/fortunejackcom?lang=en)
If needed, try the facebook handles profile image: [fb.com/fjcasino/](https://fb.com/fjcasino/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/fortunejack.com/](https://www.alexa.com/siteinfo/fortunejack.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/fortunejack.com/](https://www.scamadviser.com/check-website/fortunejack.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/fortunejack.com/](https://www.trustpilot.com/review/fortunejack.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
