### ISSUE TITLE
Add 'Casino Extreme' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1146]
Requesting to add 'Casino Extreme' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Casino Extreme
      url: https://casinoextreme.eu/
      img: 
      twitter: casinoextreme?lang=en
      facebook: casinoextremeonline/
      email_address: support@casinoextreme.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://casinoextreme.eu/banking
      exceptions: 
        text: "They only accept Bitcoin Cash deposits. Withdrawals have to be done with another coin."
```

Resources for adding this merchant:
Logo Provided:
![Casino Extreme](https://pbs.twimg.com/profile_images/771759514743955456/R2QQEWkm_400x400.jpg)

[Link to Casino Extreme](https://casinoextreme.eu/)
If needed, try the twitter handles profile image: [twitter.com/casinoextreme?lang=en](https://twitter.com/casinoextreme?lang=en)
If needed, try the facebook handles profile image: [fb.com/casinoextremeonline/](https://fb.com/casinoextremeonline/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/casinoextreme.eu/](https://www.alexa.com/siteinfo/casinoextreme.eu/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/casinoextreme.eu/](https://www.scamadviser.com/check-website/casinoextreme.eu/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/casinoextreme.eu/](https://www.trustpilot.com/review/casinoextreme.eu/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
