### ISSUE TITLE
Add 'Red Stag Casino' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1147]
Requesting to add 'Red Stag Casino' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Red Stag Casino
      url: https://www.redstagcasino.eu/
      img: 
      twitter: redstagcasino
      facebook: RedStagCasino/
      email_address: support@redstagcasino.eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.redstagcasino.eu/banking
      exceptions: 
        text: "They only accept Bitcoin Cash deposits. Withdrawals must be done with a different coin."
```

Resources for adding this merchant:
Logo Provided:
![Red Stag Casino](https://pbs.twimg.com/profile_images/378800000640505997/2dd917297301c16751296e14ed324ca9_400x400.jpeg)

[Link to Red Stag Casino](https://www.redstagcasino.eu/)
If needed, try the twitter handles profile image: [twitter.com/redstagcasino](https://twitter.com/redstagcasino)
If needed, try the facebook handles profile image: [fb.com/RedStagCasino/](https://fb.com/RedStagCasino/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.redstagcasino.eu/](https://www.alexa.com/siteinfo/www.redstagcasino.eu/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.redstagcasino.eu/](https://www.scamadviser.com/check-website/www.redstagcasino.eu/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.redstagcasino.eu/](https://www.trustpilot.com/review/www.redstagcasino.eu/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
