### ISSUE TITLE
Add 'Win A Day Casino' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1148]
Requesting to add 'Win A Day Casino' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Win A Day Casino
      url: https://www.winadaycasino.eu/
      img: 
      twitter: winadaycasino?lang=en
      facebook: WinADayCasino/
      email_address: support@winadaycasino.eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.winadaycasino.eu/en/bitcoin-cash
      exceptions: 
        text: "Withdrawals are only done on Wednesdays. You can deposit anytime."
```

Resources for adding this merchant:
Logo Provided:
![Win A Day Casino](https://pbs.twimg.com/profile_images/542994926129016833/87GnmlRS_400x400.jpeg)

[Link to Win A Day Casino](https://www.winadaycasino.eu/)
If needed, try the twitter handles profile image: [twitter.com/winadaycasino?lang=en](https://twitter.com/winadaycasino?lang=en)
If needed, try the facebook handles profile image: [fb.com/WinADayCasino/](https://fb.com/WinADayCasino/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.winadaycasino.eu/](https://www.alexa.com/siteinfo/www.winadaycasino.eu/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.winadaycasino.eu/](https://www.scamadviser.com/check-website/www.winadaycasino.eu/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.winadaycasino.eu/](https://www.trustpilot.com/review/www.winadaycasino.eu/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
