### ISSUE TITLE
Add 'Slotland' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1149]
Requesting to add 'Slotland' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Slotland
      url: https://www.slotland.eu/
      img: 
      twitter: slotland?lang=en
      facebook: Slotland/
      email_address: support@slotland.eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.slotland.eu/en/banking
      exceptions: 
        text: "They only do withdrawals on Tuesdays. You can deposit anytime."
```

Resources for adding this merchant:
Logo Provided:
![Slotland](https://pbs.twimg.com/profile_images/65352023/S_400x400.jpg)

[Link to Slotland](https://www.slotland.eu/)
If needed, try the twitter handles profile image: [twitter.com/slotland?lang=en](https://twitter.com/slotland?lang=en)
If needed, try the facebook handles profile image: [fb.com/Slotland/](https://fb.com/Slotland/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.slotland.eu/](https://www.alexa.com/siteinfo/www.slotland.eu/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.slotland.eu/](https://www.scamadviser.com/check-website/www.slotland.eu/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.slotland.eu/](https://www.trustpilot.com/review/www.slotland.eu/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
