### ISSUE TITLE
Add 'Tutanota' to the 'Software' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1150]
Requesting to add 'Tutanota' to the 'Software' category. 

Details follow: 
```yml 
- name: Tutanota
      url: https://tutanota.com/
      img: 
      twitter: TutanotaTeam
      facebook: tutanota/
      email_address: hello@tutao.de
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://tutanota.com/blog/posts/bitcoin-cash-bch
```

Resources for adding this merchant:
Logo Provided:
![Tutanota](https://tutanota.com/images/tutanota-logo_en.svg)

[Link to Tutanota](https://tutanota.com/)
If needed, try the twitter handles profile image: [twitter.com/TutanotaTeam](https://twitter.com/TutanotaTeam)
If needed, try the facebook handles profile image: [fb.com/tutanota/](https://fb.com/tutanota/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/tutanota.com/](https://www.alexa.com/siteinfo/tutanota.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/tutanota.com/](https://www.scamadviser.com/check-website/tutanota.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/tutanota.com/](https://www.trustpilot.com/review/tutanota.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
