### ISSUE TITLE
Add 'https://mycelium.com/' to the 'Wallet' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1151]
Requesting to add 'https://mycelium.com/' to the 'Wallet' category. 

Details follow: 
```yml 
- name: https://mycelium.com/
      url: https://mycelium.com/
      img: 
      email_address: protected@bahnhof.se
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "Download BCH module"
```

Resources for adding this merchant:
[Link to https://mycelium.com/](https://mycelium.com/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/mycelium.com/](https://www.alexa.com/siteinfo/mycelium.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/mycelium.com/](https://www.scamadviser.com/check-website/mycelium.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/mycelium.com/](https://www.trustpilot.com/review/mycelium.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
