### ISSUE TITLE
Add 'Bitcoin Cash Dozer' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1155]
Requesting to add 'Bitcoin Cash Dozer' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Bitcoin Cash Dozer
      url: https://dozer.cash/
      img: 
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Bitcoin Cash Dozer](https://dozer.cash/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/dozer.cash/](https://www.alexa.com/siteinfo/dozer.cash/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/dozer.cash/](https://www.scamadviser.com/check-website/dozer.cash/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/dozer.cash/](https://www.trustpilot.com/review/dozer.cash/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
