### ISSUE TITLE
Add 'Friedel Richter Restaurant' to the 'food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1156]
Requesting to add 'Friedel Richter Restaurant' to the 'food' category. 

Details follow: 
```yml 
- name: Friedel Richter Restaurant
      url: https://www.friedelrichter.de/
      img: 
      facebook: friedelrichterrestaurant
      region: eu
      country: DE
      city: Berlin
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Friedel Richter Restaurant](https://www.friedelrichter.de/)
If needed, try the facebook handles profile image: [fb.com/friedelrichterrestaurant](https://fb.com/friedelrichterrestaurant)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.friedelrichter.de/](https://www.alexa.com/siteinfo/www.friedelrichter.de/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.friedelrichter.de/](https://www.scamadviser.com/check-website/www.friedelrichter.de/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.friedelrichter.de/](https://www.trustpilot.com/review/www.friedelrichter.de/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
