### ISSUE TITLE
Add 'Doll Junction' to the 'sex dolls' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1157]
Requesting to add 'Doll Junction' to the 'sex dolls' category. 

Details follow: 
```yml 
- name: Doll Junction
      url: https://dolljunction.com/
      img: 
      twitter: dolljunction
      email_address: support@dolljunction.com
      bch: No
      btc: No
      othercrypto: No
      exceptions: 
        text: "No"
```

Resources for adding this merchant:
Logo Provided:
![Doll Junction](https://dolljunction.com/wp-content/uploads/2017/04/doll-logo.png)

[Link to Doll Junction](https://dolljunction.com/)
If needed, try the twitter handles profile image: [twitter.com/dolljunction](https://twitter.com/dolljunction)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/dolljunction.com/](https://www.alexa.com/siteinfo/dolljunction.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/dolljunction.com/](https://www.scamadviser.com/check-website/dolljunction.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/dolljunction.com/](https://www.trustpilot.com/review/dolljunction.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
