### ISSUE TITLE
Add 'My-doll' to the 'Adult' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1158]
Requesting to add 'My-doll' to the 'Adult' category. 

Details follow: 
```yml 
- name: My-doll
      url: https://www.my-doll.com/
      img: 
      twitter: mydolldotcom
      email_address: support@my-doll.com
      bch: No
      btc: No
      othercrypto: No
      exceptions: 
        text: "NO"
```

Resources for adding this merchant:
Logo Provided:
![My-doll](https://www.my-doll.com/wp-content/uploads/2016/11/logo.png)

[Link to My-doll](https://www.my-doll.com/)
If needed, try the twitter handles profile image: [twitter.com/mydolldotcom](https://twitter.com/mydolldotcom)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.my-doll.com/](https://www.alexa.com/siteinfo/www.my-doll.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.my-doll.com/](https://www.scamadviser.com/check-website/www.my-doll.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.my-doll.com/](https://www.trustpilot.com/review/www.my-doll.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
