### ISSUE TITLE
Add 'Joy Studio' to the 'Ecommerce Women Sport' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1161]
Requesting to add 'Joy Studio' to the 'Ecommerce Women Sport' category. 

Details follow: 
```yml 
- name: Joy Studio
      url: https://joystudio.fr
      img: 
      email_address: joystudioparis@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Joy Studio](https://cdn.shopify.com/s/files/1/0106/8941/3177/files/JOY_STUDIO_bcba7201-b960-4989-a75d-78fc845f0eef.png?v=1528727512)

[Link to Joy Studio](https://joystudio.fr)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/joystudio.fr](https://www.alexa.com/siteinfo/joystudio.fr)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/joystudio.fr](https://www.scamadviser.com/check-website/joystudio.fr)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/joystudio.fr](https://www.trustpilot.com/review/joystudio.fr)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
