### ISSUE TITLE
Add 'Skrill' to the 'Crypto Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1162]
Requesting to add 'Skrill' to the 'Crypto Services' category. 

Details follow: 
```yml 
- name: Skrill
      url: https://www.skrill.com/en-us/
      img: 
      twitter: skrill?lang=en
      facebook: Skrillpayments/
      email_address: help@skrill.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.paysafe.com/paysafegroup/news/detail/skrill-wallet-users-can-now-instantly-buy-and-sell-cryptocurrencies/
```

Resources for adding this merchant:
Logo Provided:
![Skrill](https://pbs.twimg.com/profile_images/651330786684092416/FNElMMB__400x400.jpg)

[Link to Skrill](https://www.skrill.com/en-us/)
If needed, try the twitter handles profile image: [twitter.com/skrill?lang=en](https://twitter.com/skrill?lang=en)
If needed, try the facebook handles profile image: [fb.com/Skrillpayments/](https://fb.com/Skrillpayments/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.skrill.com/en-us/](https://www.alexa.com/siteinfo/www.skrill.com/en-us/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.skrill.com/en-us/](https://www.scamadviser.com/check-website/www.skrill.com/en-us/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.skrill.com/en-us/](https://www.trustpilot.com/review/www.skrill.com/en-us/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
