### ISSUE TITLE
Add 'Cameron Lee' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1163]
Requesting to add 'Cameron Lee' to the 'Retail' category. 

Details follow: 
```yml 
- name: Cameron Lee
      url: https://www.cameronleeworldwide.com/
      img: 
      twitter: cameronleemusic
      email_address: support@cameronleeworldwide.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Cameron Lee](https://pbs.twimg.com/profile_images/1009990856680472577/NI5vOC2L_400x400.jpg)

[Link to Cameron Lee](https://www.cameronleeworldwide.com/)
If needed, try the twitter handles profile image: [twitter.com/cameronleemusic](https://twitter.com/cameronleemusic)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cameronleeworldwide.com/](https://www.alexa.com/siteinfo/www.cameronleeworldwide.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.cameronleeworldwide.com/](https://www.scamadviser.com/check-website/www.cameronleeworldwide.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.cameronleeworldwide.com/](https://www.trustpilot.com/review/www.cameronleeworldwide.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
