### ISSUE TITLE
Add 'Window cleaner in Marbella' to the 'Window cleaning' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1165]
Requesting to add 'Window cleaner in Marbella' to the 'Window cleaning' category. 

Details follow: 
```yml 
- name: Window cleaner in Marbella
      url: https://members.webs.com/sites/?from_login=1
      img: 
      email_address: djedwards@email.com
      region: eu
      country: ES
      city: Marbella
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Window cleaner in Marbella](https://members.webs.com/sites/?from_login=1)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/members.webs.com/sites/?from_login=1](https://www.alexa.com/siteinfo/members.webs.com/sites/?from_login=1)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/members.webs.com/sites/?from_login=1](https://www.scamadviser.com/check-website/members.webs.com/sites/?from_login=1)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/members.webs.com/sites/?from_login=1](https://www.trustpilot.com/review/members.webs.com/sites/?from_login=1)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
