### ISSUE TITLE
Add 'OVPN' to the 'security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1166]
Requesting to add 'OVPN' to the 'security' category. 

Details follow: 
```yml 
- name: OVPN
      url: https://www.ovpn.com
      img: 
      twitter: OVPN_official
      facebook: OVPNcom
      email_address: support@ovpn.com
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.ovpn.com/en/tos
      exceptions: 
        text: "Bitpay payment processor used."
```

Resources for adding this merchant:
Logo Provided:
![OVPN](https://pbs.twimg.com/profile_images/702116890882265090/mxv4JUzf_400x400.png)

[Link to OVPN](https://www.ovpn.com)
If needed, try the twitter handles profile image: [twitter.com/OVPN_official](https://twitter.com/OVPN_official)
If needed, try the facebook handles profile image: [fb.com/OVPNcom](https://fb.com/OVPNcom)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.ovpn.com](https://www.alexa.com/siteinfo/www.ovpn.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.ovpn.com](https://www.scamadviser.com/check-website/www.ovpn.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.ovpn.com](https://www.trustpilot.com/review/www.ovpn.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
