### ISSUE TITLE
Add 'The Big Coin' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1167]
Requesting to add 'The Big Coin' to the 'Services' category. 

Details follow: 
```yml 
- name: The Big Coin
      url: https://www.thebigcoin.io
      img: 
      facebook: TheBigCoin.io/
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.thebigcoin.io/faq
      exceptions: 
        text: "They only accept Bitcoin Cash if you contact them first."
```

Resources for adding this merchant:
Logo Provided:
![The Big Coin](https://scontent-sea1-1.xx.fbcdn.net/v/t1.0-9/21078588_126535434647853_4806649006173149004_n.png?_nc_cat=0&oh=68a08853d416a7337bc11e972d348fe0&oe=5BD12ECB)

[Link to The Big Coin](https://www.thebigcoin.io)
If needed, try the facebook handles profile image: [fb.com/TheBigCoin.io/](https://fb.com/TheBigCoin.io/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.thebigcoin.io](https://www.alexa.com/siteinfo/www.thebigcoin.io)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.thebigcoin.io](https://www.scamadviser.com/check-website/www.thebigcoin.io)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.thebigcoin.io](https://www.trustpilot.com/review/www.thebigcoin.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
