### ISSUE TITLE
Add 'Paid By Coins' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1168]
Requesting to add 'Paid By Coins' to the 'Services' category. 

Details follow: 
```yml 
- name: Paid By Coins
      url: https://paidbycoins.com/
      img: 
      twitter: PaidByCoins
      facebook: paidbycoins/
      email_address: info@paidbycoins.com
      region: oc
      country: AU
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://paidbycoins.com/
```

Resources for adding this merchant:
Logo Provided:
![Paid By Coins](https://pbs.twimg.com/profile_images/940400371058360321/ZuW8s1uC_400x400.jpg)

[Link to Paid By Coins](https://paidbycoins.com/)
If needed, try the twitter handles profile image: [twitter.com/PaidByCoins](https://twitter.com/PaidByCoins)
If needed, try the facebook handles profile image: [fb.com/paidbycoins/](https://fb.com/paidbycoins/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/paidbycoins.com/](https://www.alexa.com/siteinfo/paidbycoins.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/paidbycoins.com/](https://www.scamadviser.com/check-website/paidbycoins.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/paidbycoins.com/](https://www.trustpilot.com/review/paidbycoins.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
