### ISSUE TITLE
Add 'Domestic' to the 'Donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1169]
Requesting to add 'Domestic' to the 'Donations' category. 

Details follow: 
```yml 
- name: Domestic
      url: https://domestic.pythonanywhere.com/
      img: 
      email_address: domestic.citsemod@protonmail.com
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://domestic.pythonanywhere.com/donations
```

Resources for adding this merchant:
[Link to Domestic](https://domestic.pythonanywhere.com/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/domestic.pythonanywhere.com/](https://www.alexa.com/siteinfo/domestic.pythonanywhere.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/domestic.pythonanywhere.com/](https://www.scamadviser.com/check-website/domestic.pythonanywhere.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/domestic.pythonanywhere.com/](https://www.trustpilot.com/review/domestic.pythonanywhere.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
