### ISSUE TITLE
Add 'Bitcoin People Online' to the 'Cryptoservices' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1170]
Requesting to add 'Bitcoin People Online' to the 'Cryptoservices' category. 

Details follow: 
```yml 
- name: Bitcoin People Online
      url: https://bitcoinpeople.online/
      img: 
      twitter: _BitcoinPeople
      facebook: bitcoinpeopleonline/
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Some merchants listed on the site do not accept BCH. The website is a place for independent crypto-accepting merchants to sell things. Each merchant is different."
```

Resources for adding this merchant:
Logo Provided:
![Bitcoin People Online](https://pbs.twimg.com/profile_images/936576005342416897/XIk7yEpX_400x400.jpg)

[Link to Bitcoin People Online](https://bitcoinpeople.online/)
If needed, try the twitter handles profile image: [twitter.com/_BitcoinPeople](https://twitter.com/_BitcoinPeople)
If needed, try the facebook handles profile image: [fb.com/bitcoinpeopleonline/](https://fb.com/bitcoinpeopleonline/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bitcoinpeople.online/](https://www.alexa.com/siteinfo/bitcoinpeople.online/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bitcoinpeople.online/](https://www.scamadviser.com/check-website/bitcoinpeople.online/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bitcoinpeople.online/](https://www.trustpilot.com/review/bitcoinpeople.online/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
