### ISSUE TITLE
Add 'The Ocean Cleanup' to the 'Donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1171]
Requesting to add 'The Ocean Cleanup' to the 'Donations' category. 

Details follow: 
```yml 
- name: The Ocean Cleanup
      url: https://www.theoceancleanup.com
      img: theoceancleanup.png
      twitter: theoceancleanup
      facebook: TheOceanCleanup
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.theoceancleanup.com/fund/
```

Resources for adding this merchant:
Logo Provided:
![The Ocean Cleanup](https://pbs.twimg.com/profile_images/470560466704404481/18--E1xh_400x400.png)

[Link to The Ocean Cleanup](https://www.theoceancleanup.com)
If needed, try the twitter handles profile image: [twitter.com/theoceancleanup](https://twitter.com/theoceancleanup)
If needed, try the facebook handles profile image: [fb.com/TheOceanCleanup/](https://fb.com/TheOceanCleanup/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.theoceancleanup.com](https://www.alexa.com/siteinfo/www.theoceancleanup.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.theoceancleanup.com](https://www.scamadviser.com/check-website/www.theoceancleanup.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.theoceancleanup.com](https://www.trustpilot.com/review/www.theoceancleanup.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
