### ISSUE TITLE
Add 'Tip-Top Shop' to the 'Clothing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1172]
Requesting to add 'Tip-Top Shop' to the 'Clothing' category. 

Details follow: 
```yml 
- name: Tip-Top Shop
      url: https://tiptopshop.pagekite.me
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Tip-Top Shop](https://tiptopshop.pagekite.me)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/tiptopshop.pagekite.me](https://www.alexa.com/siteinfo/tiptopshop.pagekite.me)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/tiptopshop.pagekite.me](https://www.scamadviser.com/check-website/tiptopshop.pagekite.me)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/tiptopshop.pagekite.me](https://www.trustpilot.com/review/tiptopshop.pagekite.me)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
