### ISSUE TITLE
Add 'Hope Team Help for Africa' to the 'donation human needs' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1173]
Requesting to add 'Hope Team Help for Africa' to the 'donation human needs' category. 

Details follow: 
```yml 
- name: Hope Team Help for Africa
      url: https://hope-team-help-for-africa.github.io/page/
      img: HopeTeamHelp4Africa.png
      twitter: PatrickGiroux14
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Hope Team Help for Africa](https://i.imgur.com/qxRozBw.jpg?3)

[Link to Hope Team Help for Africa](https://hope-team-help-for-africa.github.io/page/)
If needed, try the twitter handles profile image: [twitter.com/PatrickGiroux14](https://twitter.com/PatrickGiroux14)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/hope-team-help-for-africa.github.io/page/](https://www.alexa.com/siteinfo/hope-team-help-for-africa.github.io/page/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/hope-team-help-for-africa.github.io/page/](https://www.scamadviser.com/check-website/hope-team-help-for-africa.github.io/page/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/hope-team-help-for-africa.github.io/page/](https://www.trustpilot.com/review/hope-team-help-for-africa.github.io/page/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
