### ISSUE TITLE
Add 'Cosmos Clinic' to the 'Health & Beauty' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1176]
Requesting to add 'Cosmos Clinic' to the 'Health & Beauty' category. 

Details follow: 
```yml 
- name: Cosmos Clinic
      url: https://www.cosmosclinic.com.au/
      img: 
      facebook: CosmosClinic
      email_address: info@cosmosclinic.com.au
      region: oc
      country: AU
      city: Adelaide
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.cosmosclinic.com.au/blog/cosmetic-treatments-using-bitcoin/
      exceptions: 
        text: "No"
```

Resources for adding this merchant:
Logo Provided:
![Cosmos Clinic](https://i.imgur.com/C2WDuWE.jpg)

[Link to Cosmos Clinic](https://www.cosmosclinic.com.au/)
If needed, try the facebook handles profile image: [fb.com/CosmosClinic](https://fb.com/CosmosClinic)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cosmosclinic.com.au/](https://www.alexa.com/siteinfo/www.cosmosclinic.com.au/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.cosmosclinic.com.au/](https://www.scamadviser.com/check-website/www.cosmosclinic.com.au/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.cosmosclinic.com.au/](https://www.trustpilot.com/review/www.cosmosclinic.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
