### ISSUE TITLE
Add 'starcertification' to the 'devloper' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1177]
Requesting to add 'starcertification' to the 'devloper' category. 

Details follow: 
```yml 
- name: starcertification
      url: https://www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert
      img: 
      email_address: starcertificationus@gmail.com
      country: US
      city: Glendale CA
      bch: No
      btc: No
      othercrypto: Yes
      doc: https://www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert
      exceptions: 
        text: "no"
```

Resources for adding this merchant:
[Link to starcertification](https://www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert](https://www.alexa.com/siteinfo/www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert](https://www.scamadviser.com/check-website/www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert](https://www.trustpilot.com/review/www.starcertification.org/Certifications/Certificate/Ethical-Hacking-Expert)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
