### ISSUE TITLE
Add '/bumho lee' to the 'Lifestyle' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1180]
Requesting to add '/bumho lee' to the 'Lifestyle' category. 

Details follow: 
```yml 
- name: /bumho lee
      url: https://blog.naver.com/asdfgpoin
      img: 
      region: as
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to /bumho lee](https://blog.naver.com/asdfgpoin)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/blog.naver.com/asdfgpoin](https://www.alexa.com/siteinfo/blog.naver.com/asdfgpoin)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/blog.naver.com/asdfgpoin](https://www.scamadviser.com/check-website/blog.naver.com/asdfgpoin)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/blog.naver.com/asdfgpoin](https://www.trustpilot.com/review/blog.naver.com/asdfgpoin)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
