### ISSUE TITLE
Add 'GoMach5' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1183]
Requesting to add 'GoMach5' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: GoMach5
      url: https://www.gomach5.com
      img: 
      email_address: markh@gomach5.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to GoMach5](https://www.gomach5.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.gomach5.com](https://www.alexa.com/siteinfo/www.gomach5.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.gomach5.com](https://www.scamadviser.com/check-website/www.gomach5.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.gomach5.com](https://www.trustpilot.com/review/www.gomach5.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
