### ISSUE TITLE
Add 'The Goddess Nyxx' to the 'Social, Other' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1184]
Requesting to add 'The Goddess Nyxx' to the 'Social, Other' category. 

Details follow: 
```yml 
- name: The Goddess Nyxx
  url: https://thegoddessnyxx.com/
  img: GoddessNyxx
  twitter: TheGoddessNyxx
  bch: Yes
  btc: Yes
  othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![The Goddess Nyxx](https://s8.postimg.cc/70zr1dpn9/GNLogo128.png)

[Link to The Goddess Nyxx](https://thegoddessnyxx.com/)
If needed, try the twitter handles profile image: [twitter.com/TheGoddessNyxx](https://twitter.com/TheGoddessNyxx)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/thegoddessnyxx.com/](https://www.alexa.com/siteinfo/thegoddessnyxx.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/thegoddessnyxx.com/](https://www.scamadviser.com/check-website/thegoddessnyxx.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/thegoddessnyxx.com/](https://www.trustpilot.com/review/thegoddessnyxx.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
