### ISSUE TITLE
Add 'Mason Bar' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1185]
Requesting to add 'Mason Bar' to the 'Food' category. 

Details follow: 
```yml 
- name: Mason Bar
      url: http://t.dianping.com/deal/20656559
      img: 
      region: as
      country: CN
      city: Beijing
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://twitter.com/nishantsharma87/status/958396424269385729
      exceptions: 
        text: "Remember to ask the bartender the price of the drink in BCH before paying. The bar uses an exchange rate that may be different from the one that you use."
```

Resources for adding this merchant:
Logo Provided:
![Mason Bar](http://i68.tinypic.com/2e1y71c.jpg)

[Link to Mason Bar](http://t.dianping.com/deal/20656559)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/t.dianping.com/deal/20656559](https://www.alexa.com/siteinfo/t.dianping.com/deal/20656559)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/t.dianping.com/deal/20656559](https://www.scamadviser.com/check-website/t.dianping.com/deal/20656559)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/t.dianping.com/deal/20656559](https://www.trustpilot.com/review/t.dianping.com/deal/20656559)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
