### ISSUE TITLE
Add 'CoinWISE' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1186]
Requesting to add 'CoinWISE' to the 'Payments' category. 

Details follow: 
```yml 
- name: CoinWISE
      url: https://coinwise.io
      img: 
      twitter: coinwisebr
      facebook: coinwisebr
      email_address: coinwise@coinwise.br
      region: sa
      country: BR
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![CoinWISE](https://www.google.com.br/search?q=coinwise+logo&rlz=1C5CHFA_enBR719BR719&tbm=isch&source=iu&ictx=1&fir=uGNZ1TWzI3_2eM%253A%252CuBU1bX_3mqtpJM%252C_&usg=AFrqEzcW1F73_7kAOadL_oEIp0-iDwjtsQ&sa=X&ved=2ahUKEwi2war3gNvcAhUJTZAKHT-MBVsQ9QEwAHoECAMQBA#imgrc=BahykAa-47qTPM:)

[Link to CoinWISE](https://coinwise.io)
If needed, try the twitter handles profile image: [twitter.com/coinwisebr](https://twitter.com/coinwisebr)
If needed, try the facebook handles profile image: [fb.com/coinwisebr](https://fb.com/coinwisebr)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/coinwise.io](https://www.alexa.com/siteinfo/coinwise.io)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/coinwise.io](https://www.scamadviser.com/check-website/coinwise.io)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/coinwise.io](https://www.trustpilot.com/review/coinwise.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
