### ISSUE TITLE
Add 'Cyberghost' to the 'VPN service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1188]
Requesting to add 'Cyberghost' to the 'VPN service' category. 

Details follow: 
```yml 
- name: Cyberghost
      url: https://www.cyberghostvpn.com
      img: 
      twitter: CyberGhost_EN
      facebook: cyberghostvpn
      email_address: webmaster@cyberghost.ro
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Cyberghost](https://assets.cgvpn.info/themes/yellow/img/cyberghost.png)

[Link to Cyberghost](https://www.cyberghostvpn.com)
If needed, try the twitter handles profile image: [twitter.com/CyberGhost_EN](https://twitter.com/CyberGhost_EN)
If needed, try the facebook handles profile image: [fb.com/cyberghostvpn](https://fb.com/cyberghostvpn)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cyberghostvpn.com](https://www.alexa.com/siteinfo/www.cyberghostvpn.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.cyberghostvpn.com](https://www.scamadviser.com/check-website/www.cyberghostvpn.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.cyberghostvpn.com](https://www.trustpilot.com/review/www.cyberghostvpn.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
