### ISSUE TITLE
Add 'Ethiopiaid' to the 'Donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1189]
Requesting to add 'Ethiopiaid' to the 'Donations' category. 

Details follow: 
```yml 
- name: Ethiopiaid
      url: https://ethiopiaid.org.au/
      img: 
      twitter: ethiopiaidaus
      facebook: EthiopiaidAus
      email_address: info@ethiopiaid.org.au
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://ethiopiaid.org.au/blog/ethiopiaid-cryptocurrency-donation
```

Resources for adding this merchant:
Logo Provided:
![Ethiopiaid](https://drive.google.com/open?id=1UAlRPR2lBmw-aHUNemPt_CnimRKTlZC0)

[Link to Ethiopiaid](https://ethiopiaid.org.au/)
If needed, try the twitter handles profile image: [twitter.com/ethiopiaidaus](https://twitter.com/ethiopiaidaus)
If needed, try the facebook handles profile image: [fb.com/EthiopiaidAus](https://fb.com/EthiopiaidAus)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/ethiopiaid.org.au/](https://www.alexa.com/siteinfo/ethiopiaid.org.au/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/ethiopiaid.org.au/](https://www.scamadviser.com/check-website/ethiopiaid.org.au/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/ethiopiaid.org.au/](https://www.trustpilot.com/review/ethiopiaid.org.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
