### ISSUE TITLE
Add 'LagaiPhone' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1190]
Requesting to add 'LagaiPhone' to the 'Services' category. 

Details follow: 
```yml 
- name: LagaiPhone
      url: https://lagaiphone.se/
      img: 
      twitter: Lagaiphone
      facebook: LagaiPhone.se
      email_address: info@lagaiphone.se
      region: eu
      country: SE
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Ask for payment by Bitcoin Cash in store or by e-mail."
```

Resources for adding this merchant:
Logo Provided:
![LagaiPhone](https://lagaiphone.se/wp-content/uploads/2015/03/cropped-apple-touch-icon-precomposed-1-32x32.png)

[Link to LagaiPhone](https://lagaiphone.se/)
If needed, try the twitter handles profile image: [twitter.com/Lagaiphone](https://twitter.com/Lagaiphone)
If needed, try the facebook handles profile image: [fb.com/LagaiPhone.se](https://fb.com/LagaiPhone.se)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/lagaiphone.se/](https://www.alexa.com/siteinfo/lagaiphone.se/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/lagaiphone.se/](https://www.scamadviser.com/check-website/lagaiphone.se/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/lagaiphone.se/](https://www.trustpilot.com/review/lagaiphone.se/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
