### ISSUE TITLE
Ethiopiaid Australia accepting Bitcoin Cash

### ISSUE THREAD

**Issue by EthiopiaidAus** [acceptbitcoincash/acceptbitcoincash#1191]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Ethiopiaid Australia**}} to the {{**Donations**}} category. Details follow:

```yml

- name: Ethiopiaid Australia
  url: https://ethiopiaid.org.au/
  img: https://drive.google.com/file/d/1UAlRPR2lBmw-aHUNemPt_CnimRKTlZC0/view?usp=sharing
  twitter: ethiopiaidaus
  facebook: EthiopiaidAus
  region: oc
  country: AU
  city: Melbourne
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://ethiopiaid.org.au/blog/ethiopiaid-cryptocurrency-donation
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
