### ISSUE TITLE
Add 'Bitcoin Cash Magazine' to the 'Entertainment' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1194]
Requesting to add 'Bitcoin Cash Magazine' to the 'Entertainment' category. 

Details follow: 
```yml 
- name: Bitcoin Cash Magazine
      url: https://bitcoincashmag.com
      img: 
      twitter: bitcoincashmag
      email_address: admin@bitcoincashmag.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://old.reddit.com/r/btc/comments/95v9vi/come_and_check_out_the_new_bitcoin_cash_magazine
```

Resources for adding this merchant:
Logo Provided:
![Bitcoin Cash Magazine](https://pbs.twimg.com/profile_images/991322270042935297/6_lNWiaA_400x400.jpg)

[Link to Bitcoin Cash Magazine](https://bitcoincashmag.com)
If needed, try the twitter handles profile image: [twitter.com/bitcoincashmag](https://twitter.com/bitcoincashmag)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bitcoincashmag.com](https://www.alexa.com/siteinfo/bitcoincashmag.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bitcoincashmag.com](https://www.scamadviser.com/check-website/bitcoincashmag.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bitcoincashmag.com](https://www.trustpilot.com/review/bitcoincashmag.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
