### ISSUE TITLE
Add 'Dish' to the 'Entertainment' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1195]
Requesting to add 'Dish' to the 'Entertainment' category. 

Details follow: 
```yml 
- name: Dish
      url: https://www.dish.com/
      img: 
      twitter: dish?lang=en
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.prnewswire.com/news-releases/dish-adds-bitcoin-cash-as-option-for-customers-migrates-to-bitpay-for-cryptocurrency-payment-processing-300694617.html
      exceptions: 
        text: "Bitpay"
```

Resources for adding this merchant:
Logo Provided:
![Dish](https://pbs.twimg.com/profile_images/761209763317231618/0Fp12MiX_400x400.jpg)

[Link to Dish](https://www.dish.com/)
If needed, try the twitter handles profile image: [twitter.com/dish?lang=en](https://twitter.com/dish?lang=en)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.dish.com/](https://www.alexa.com/siteinfo/www.dish.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.dish.com/](https://www.scamadviser.com/check-website/www.dish.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.dish.com/](https://www.trustpilot.com/review/www.dish.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
