### ISSUE TITLE
Add 'jam' to the 'USA' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1196]
Requesting to add 'jam' to the 'USA' category. 

Details follow: 
```yml 
- name: jam
      url: https://docs.google.com/forms/d/e/1FAIpQLSd9jTEzqTfeaECJAirLg7BMcbF4B9Vl9PFFuskzEo5rslP8pw/formResponse
      img: 
      twitter: james
      facebook: james
      email_address: leehun906@gmail.com
      country: AE
      city: paris
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.facebook.com/20531316728/posts/10154009990506729/
      exceptions: 
        text: "james"
```

Resources for adding this merchant:
Logo Provided:
![jam](https://www.google.com/search?q=ronaldo&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi8y_rstOHcAhXLXCsKHQcsBfQQ_AUICigB&biw=1366&bih=693#imgrc=vixUjSD5TRqGQM:)

[Link to jam](https://docs.google.com/forms/d/e/1FAIpQLSd9jTEzqTfeaECJAirLg7BMcbF4B9Vl9PFFuskzEo5rslP8pw/formResponse)
If needed, try the twitter handles profile image: [twitter.com/james](https://twitter.com/james)
If needed, try the facebook handles profile image: [fb.com/james](https://fb.com/james)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/docs.google.com/forms/d/e/1FAIpQLSd9jTEzqTfeaECJAirLg7BMcbF4B9Vl9PFFuskzEo5rslP8pw/formResponse](https://www.alexa.com/siteinfo/docs.google.com/forms/d/e/1FAIpQLSd9jTEzqTfeaECJAirLg7BMcbF4B9Vl9PFFuskzEo5rslP8pw/formResponse)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/docs.google.com/forms/d/e/1FAIpQLSd9jTEzqTfeaECJAirLg7BMcbF4B9Vl9PFFuskzEo5rslP8pw/formResponse](https://www.scamadviser.com/check-website/docs.google.com/forms/d/e/1FAIpQLSd9jTEzqTfeaECJAirLg7BMcbF4B9Vl9PFFuskzEo5rslP8pw/formResponse)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/docs.google.com/forms/d/e/1FAIpQLSd9jTEzqTfeaECJAirLg7BMcbF4B9Vl9PFFuskzEo5rslP8pw/formResponse](https://www.trustpilot.com/review/docs.google.com/forms/d/e/1FAIpQLSd9jTEzqTfeaECJAirLg7BMcbF4B9Vl9PFFuskzEo5rslP8pw/formResponse)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
