### ISSUE TITLE
Add 'Aulerion' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1197]
Requesting to add 'Aulerion' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: Aulerion
      url: https://www.aulerion.com
      img: 
      twitter: aulerion
      facebook: aulerion
      email_address: support@aulerion.com
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Aulerion](https://pbs.twimg.com/profile_images/1022891907335249920/1l3Y_Chu_400x400.jpg)

[Link to Aulerion](https://www.aulerion.com)
If needed, try the twitter handles profile image: [twitter.com/aulerion](https://twitter.com/aulerion)
If needed, try the facebook handles profile image: [fb.com/aulerion](https://fb.com/aulerion)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.aulerion.com](https://www.alexa.com/siteinfo/www.aulerion.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.aulerion.com](https://www.scamadviser.com/check-website/www.aulerion.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.aulerion.com](https://www.trustpilot.com/review/www.aulerion.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
