### ISSUE TITLE
Add 'The Coffee Bean ' to the 'Retail ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1199]
Requesting to add 'The Coffee Bean ' to the 'Retail ' category. 

Details follow: 
```yml 
- name: The Coffee Bean 
      url: http://www.sarahscoffee.com
      img: 
      twitter: coffeeandcare
      facebook: coffeeandcare
      email_address: sales@sarahscoffee.com
      country: GB
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![The Coffee Bean ](https://pbs.twimg.com/profile_images/830103510976966656/3cFmdfSK.jpg)

[Link to The Coffee Bean ](http://www.sarahscoffee.com)
If needed, try the twitter handles profile image: [twitter.com/coffeeandcare](https://twitter.com/coffeeandcare)
If needed, try the facebook handles profile image: [fb.com/coffeeandcare](https://fb.com/coffeeandcare)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.sarahscoffee.com](https://www.alexa.com/siteinfo/www.sarahscoffee.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.sarahscoffee.com](https://www.scamadviser.com/check-website/www.sarahscoffee.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.sarahscoffee.com](https://www.trustpilot.com/review/www.sarahscoffee.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
