### ISSUE TITLE
Add 'disRupt Ávila' to the 'Espacio Coworking' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1200]
Requesting to add 'disRupt Ávila' to the 'Espacio Coworking' category. 

Details follow: 
```yml 
- name: disRupt Ávila
      url: http://disruptavila.com
      img: 
      twitter: disruptavila
      facebook: disruptavila
      email_address: info@disruptavila.com
      region: eu
      country: ES
      city: Ávila
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: http://disruptavila.com/
      exceptions: 
        text: "select cryptocurrency payments"
```

Resources for adding this merchant:
Logo Provided:
![disRupt Ávila](http://disruptavila.com/wordpress/img/logo2018.png)

[Link to disRupt Ávila](http://disruptavila.com)
If needed, try the twitter handles profile image: [twitter.com/disruptavila](https://twitter.com/disruptavila)
If needed, try the facebook handles profile image: [fb.com/disruptavila](https://fb.com/disruptavila)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/disruptavila.com](https://www.alexa.com/siteinfo/disruptavila.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/disruptavila.com](https://www.scamadviser.com/check-website/disruptavila.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/disruptavila.com](https://www.trustpilot.com/review/disruptavila.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
