### ISSUE TITLE
Add 'CoolWallet S' to the 'Wallets' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1201]
Requesting to add 'CoolWallet S' to the 'Wallets' category. 

Details follow: 
```yml 
- name: CoolWallet S
      url: https://coolwallet.io
      img: 
      twitter: coolwallet
      facebook: coolwallet
      email_address: support@coolbitx.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![CoolWallet S](https://pbs.twimg.com/profile_images/969405671601987585/S3EhqxJD_400x400.jpg)

[Link to CoolWallet S](https://coolwallet.io)
If needed, try the twitter handles profile image: [twitter.com/coolwallet](https://twitter.com/coolwallet)
If needed, try the facebook handles profile image: [fb.com/coolwallet](https://fb.com/coolwallet)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/coolwallet.io](https://www.alexa.com/siteinfo/coolwallet.io)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/coolwallet.io](https://www.scamadviser.com/check-website/coolwallet.io)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/coolwallet.io](https://www.trustpilot.com/review/coolwallet.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
