### ISSUE TITLE
Add 'Mofobit' to the 'Retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1202]
Requesting to add 'Mofobit' to the 'Retailer' category. 

Details follow: 
```yml 
- name: Mofobit
      url: https://mofobit.com
      img: 
      twitter: Mofobit
      facebook: MofoBit
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Mofobit](https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-0/cp0/e15/q65/p200x200/33030079_621380491528084_5764928258306998272_n.png.jpg?_nc_cat=0&efg=eyJpIjoidCJ9&oh=960cebea3018c939dc9cf0174a7b9f79&oe=5BF18119)

[Link to Mofobit](https://mofobit.com)
If needed, try the twitter handles profile image: [twitter.com/Mofobit](https://twitter.com/Mofobit)
If needed, try the facebook handles profile image: [fb.com/MofoBit](https://fb.com/MofoBit)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/mofobit.com](https://www.alexa.com/siteinfo/mofobit.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/mofobit.com](https://www.scamadviser.com/check-website/mofobit.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/mofobit.com](https://www.trustpilot.com/review/mofobit.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
