### ISSUE TITLE
Add 'Fivebucks.com' to the 'Freelance' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1203]
Requesting to add 'Fivebucks.com' to the 'Freelance' category. 

Details follow: 
```yml 
- name: Fivebucks.com
      url: https://fivebucks.com
      img: 
      twitter: fivebuckscom
      facebook: fivebuckscom
      email_address: inquiries@fivebucks.com
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.yours.org/content/fivebucks--the-only-truly-global-freelance-services-marketplace-is-now-20d53893af96
```

Resources for adding this merchant:
Logo Provided:
![Fivebucks.com](https://ibb.co/hmsUwU)

[Link to Fivebucks.com](https://fivebucks.com)
If needed, try the twitter handles profile image: [twitter.com/fivebuckscom](https://twitter.com/fivebuckscom)
If needed, try the facebook handles profile image: [fb.com/fivebuckscom](https://fb.com/fivebuckscom)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/fivebucks.com](https://www.alexa.com/siteinfo/fivebucks.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/fivebucks.com](https://www.scamadviser.com/check-website/fivebucks.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/fivebucks.com](https://www.trustpilot.com/review/fivebucks.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
