### ISSUE TITLE
Add 'Sun Kratom Việt Nam' to the 'Kratom' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1204]
Requesting to add 'Sun Kratom Việt Nam' to the 'Kratom' category. 

Details follow: 
```yml 
- name: Sun Kratom Việt Nam
      url: https://vi.sunkratom.com
      img: 
      twitter: sunkratom
      facebook: sunkratomvi
      email_address: support@sunkratom.com
      region: as
      country: VN
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Sun Kratom Việt Nam](https://sunkratom.com/content/uploads/2017/06/sun_kratom_logo_small-1.png)

[Link to Sun Kratom Việt Nam](https://vi.sunkratom.com)
If needed, try the twitter handles profile image: [twitter.com/sunkratom](https://twitter.com/sunkratom)
If needed, try the facebook handles profile image: [fb.com/sunkratomvi](https://fb.com/sunkratomvi)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/vi.sunkratom.com](https://www.alexa.com/siteinfo/vi.sunkratom.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/vi.sunkratom.com](https://www.scamadviser.com/check-website/vi.sunkratom.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/vi.sunkratom.com](https://www.trustpilot.com/review/vi.sunkratom.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
