### ISSUE TITLE
Add 'Hushed' to the 'Utilities/Mobile App' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1205]
Requesting to add 'Hushed' to the 'Utilities/Mobile App' category. 

Details follow: 
```yml 
- name: Hushed
      url: https://hushed.com/
      img: 
      twitter: hushedapp?lang=en
      email_address: support@hushed.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://hushed.com/payment-step-1/
```

Resources for adding this merchant:
Logo Provided:
![Hushed](https://pbs.twimg.com/profile_images/908796685140267008/4RJIUdE4_400x400.jpg)

[Link to Hushed](https://hushed.com/)
If needed, try the twitter handles profile image: [twitter.com/hushedapp?lang=en](https://twitter.com/hushedapp?lang=en)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/hushed.com/](https://www.alexa.com/siteinfo/hushed.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/hushed.com/](https://www.scamadviser.com/check-website/hushed.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/hushed.com/](https://www.trustpilot.com/review/hushed.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
