### ISSUE TITLE
Add 'Keys4Coins' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1206]
Requesting to add 'Keys4Coins' to the 'Gaming' category. 

Details follow: 
```yml 
- name: Keys4Coins
      url: https://www.keys4coins.com/product-category/steam/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Keys4Coins](https://www.keys4coins.com/product-category/steam/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.keys4coins.com/product-category/steam/](https://www.alexa.com/siteinfo/www.keys4coins.com/product-category/steam/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.keys4coins.com/product-category/steam/](https://www.scamadviser.com/check-website/www.keys4coins.com/product-category/steam/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.keys4coins.com/product-category/steam/](https://www.trustpilot.com/review/www.keys4coins.com/product-category/steam/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
