### ISSUE TITLE
Add 'That Ring Shop' to the 'Jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1207]
Requesting to add 'That Ring Shop' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: That Ring Shop
      url: https://thatringshop.com/
      img: 
      twitter: thatringshop
      email_address: hello@thatringshop.com
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![That Ring Shop](https://drive.google.com/open?id=0B8ecgPJ8j0vvYmtMejh5MnBGTG8)

[Link to That Ring Shop](https://thatringshop.com/)
If needed, try the twitter handles profile image: [twitter.com/thatringshop](https://twitter.com/thatringshop)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/thatringshop.com/](https://www.alexa.com/siteinfo/thatringshop.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/thatringshop.com/](https://www.scamadviser.com/check-website/thatringshop.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/thatringshop.com/](https://www.trustpilot.com/review/thatringshop.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
