### ISSUE TITLE
Add 'virtualrealporn' to the 'Adult ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1209]
Requesting to add 'virtualrealporn' to the 'Adult ' category. 

Details follow: 
```yml 
- name: virtualrealporn
      url: https://virtualrealporn.com
      img: 
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to virtualrealporn](https://virtualrealporn.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/virtualrealporn.com](https://www.alexa.com/siteinfo/virtualrealporn.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/virtualrealporn.com](https://www.scamadviser.com/check-website/virtualrealporn.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/virtualrealporn.com](https://www.trustpilot.com/review/virtualrealporn.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
