### ISSUE TITLE
Add 'wankz' to the 'Porn' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1210]
Requesting to add 'wankz' to the 'Porn' category. 

Details follow: 
```yml 
- name: wankz
      url: https://www.wankz.com
      img: 
      bch: No
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "They have their own alt coin https://www.wankcoin.com/ You can buy wankcoin with btc  and use that to pay for the site."
```

Resources for adding this merchant:
[Link to wankz](https://www.wankz.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.wankz.com](https://www.alexa.com/siteinfo/www.wankz.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.wankz.com](https://www.scamadviser.com/check-website/www.wankz.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.wankz.com](https://www.trustpilot.com/review/www.wankz.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
