### ISSUE TITLE
Add 'https://www.wankcoin.com/' to the 'Alt coin for the adult industry ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1211]
Requesting to add 'https://www.wankcoin.com/' to the 'Alt coin for the adult industry ' category. 

Details follow: 
```yml 
- name: https://www.wankcoin.com/
      url: https://www.wankcoin.com/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to https://www.wankcoin.com/](https://www.wankcoin.com/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.wankcoin.com/](https://www.alexa.com/siteinfo/www.wankcoin.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.wankcoin.com/](https://www.scamadviser.com/check-website/www.wankcoin.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.wankcoin.com/](https://www.trustpilot.com/review/www.wankcoin.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
