### ISSUE TITLE
Add 'Alagoria' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1212]
Requesting to add 'Alagoria' to the 'Retail' category. 

Details follow: 
```yml 
- name: Alagoria
      url: https://alagoria.com
      img: 
      twitter: ShopAlagoria
      facebook: ShopAlagoria
      email_address: support@alagoria.com
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Alagoria](https://alagoria.com)
If needed, try the twitter handles profile image: [twitter.com/ShopAlagoria](https://twitter.com/ShopAlagoria)
If needed, try the facebook handles profile image: [fb.com/ShopAlagoria](https://fb.com/ShopAlagoria)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/alagoria.com](https://www.alexa.com/siteinfo/alagoria.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/alagoria.com](https://www.scamadviser.com/check-website/alagoria.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/alagoria.com](https://www.trustpilot.com/review/alagoria.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
