### ISSUE TITLE
Add 'OOSEOO Internetmarketing' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1213]
Requesting to add 'OOSEOO Internetmarketing' to the 'Services' category. 

Details follow: 
```yml 
- name: OOSEOO Internetmarketing
      url: https://www.ooseoo.com
      img: 
      twitter: OOSEOO
      facebook: OOSEOO
      email_address: info@ooseoo.com
      region: eu
      country: NL
      city: Amersfoort
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![OOSEOO Internetmarketing](https://pbs.twimg.com/profile_images/461091242588119040/AQACGAVk_400x400.png)

[Link to OOSEOO Internetmarketing](https://www.ooseoo.com)
If needed, try the twitter handles profile image: [twitter.com/OOSEOO](https://twitter.com/OOSEOO)
If needed, try the facebook handles profile image: [fb.com/OOSEOO](https://fb.com/OOSEOO)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.ooseoo.com](https://www.alexa.com/siteinfo/www.ooseoo.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.ooseoo.com](https://www.scamadviser.com/check-website/www.ooseoo.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.ooseoo.com](https://www.trustpilot.com/review/www.ooseoo.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
