### ISSUE TITLE
Add 'Coinbase Commerce' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1214]
Requesting to add 'Coinbase Commerce' to the 'Payments' category. 

Details follow: 
```yml 
- name: Coinbase Commerce
      url: https://commerce.coinbase.com/
      img: 
      twitter: commercecb?lang=en
      email_address: commerce@coinbase.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/CommerceCB/status/1031599823852425216
```

Resources for adding this merchant:
Logo Provided:
![Coinbase Commerce](https://pbs.twimg.com/profile_images/986703121681231873/XBOpwic0_400x400.jpg)

[Link to Coinbase Commerce](https://commerce.coinbase.com/)
If needed, try the twitter handles profile image: [twitter.com/commercecb?lang=en](https://twitter.com/commercecb?lang=en)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/commerce.coinbase.com/](https://www.alexa.com/siteinfo/commerce.coinbase.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/commerce.coinbase.com/](https://www.scamadviser.com/check-website/commerce.coinbase.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/commerce.coinbase.com/](https://www.trustpilot.com/review/commerce.coinbase.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
