### ISSUE TITLE
Add 'Celestial Jewelers' to the 'Jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1217]
Requesting to add 'Celestial Jewelers' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: Celestial Jewelers
      url: http://www.celestialjeweler.com
      img: 
      twitter: CelestialJewler
      facebook: celestialjewelers
      email_address: email@celestialjeweler.com
      region: na
      country: US
      city: Atlanta Georgia
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: http://www.celestialjeweler.com
      exceptions: 
        text: "Call our store"
```

Resources for adding this merchant:
[Link to Celestial Jewelers](http://www.celestialjeweler.com)
If needed, try the twitter handles profile image: [twitter.com/CelestialJewler](https://twitter.com/CelestialJewler)
If needed, try the facebook handles profile image: [fb.com/celestialjewelers](https://fb.com/celestialjewelers)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.celestialjeweler.com](https://www.alexa.com/siteinfo/www.celestialjeweler.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.celestialjeweler.com](https://www.scamadviser.com/check-website/www.celestialjeweler.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.celestialjeweler.com](https://www.trustpilot.com/review/www.celestialjeweler.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
