### ISSUE TITLE
New merchant Inet

### ISSUE THREAD

**Issue by vuego** [acceptbitcoincash/acceptbitcoincash#1218]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**site_name_here**}} to the {{**category_name_here**}} category. Details follow:

```yml

- name: Inet
  url: https://www.inet.se/
  img: https://www.inet.se/gfx/ext/226/logos/symbol/inet-symbol-rgb.png
  twitter: inetse
  facebook: inet.se
  region: eu
  country: se
  city: Göteborg, Uddevalla, Stockholm, Järfälla and Malmö
  bch: yes
  btc: yes
  othercrypto: no
  doc: https://www.inet.se/info/677/2018-05-03-nu-kan-du-betala-med-kryptovalutor-pa-inet
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
