### ISSUE TITLE
Add 'BestMixer.io' to the 'Multicurrency crypto mixer ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1222]
Requesting to add 'BestMixer.io' to the 'Multicurrency crypto mixer ' category. 

Details follow: 
```yml 
- name: BestMixer.io
      url: https://bestmixer.io/en
      img: 
      email_address: bestmixer@protonmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://bestmixer.io/en/resources/blog/is_bitcoin_cash_anonymous_should_i_use_a_bitcoin_cash_mixer
```

Resources for adding this merchant:
[Link to BestMixer.io](https://bestmixer.io/en)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bestmixer.io/en](https://www.alexa.com/siteinfo/bestmixer.io/en)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bestmixer.io/en](https://www.scamadviser.com/check-website/bestmixer.io/en)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bestmixer.io/en](https://www.trustpilot.com/review/bestmixer.io/en)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
