### ISSUE TITLE
Add 'The Real Bitcoin Club' to the 'Restaurants, Bars, Shops' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1224]
Requesting to add 'The Real Bitcoin Club' to the 'Restaurants, Bars, Shops' category. 

Details follow: 
```yml 
- name: The Real Bitcoin Club
      url: https://map.therealbitcoin.club
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to The Real Bitcoin Club](https://map.therealbitcoin.club)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/map.therealbitcoin.club](https://www.alexa.com/siteinfo/map.therealbitcoin.club)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/map.therealbitcoin.club](https://www.scamadviser.com/check-website/map.therealbitcoin.club)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/map.therealbitcoin.club](https://www.trustpilot.com/review/map.therealbitcoin.club)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
