### ISSUE TITLE
Add 'Swedron' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1226]
Requesting to add 'Swedron' to the 'Retail' category. 

Details follow: 
```yml 
- name: Swedron
      url: https://www.swedron.se
      img: 
      twitter: swedronsverige
      facebook: swedronsverige
      email_address: info@swedron.se
      region: eu
      country: SE
      city: No
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Swedron](https://yt3.ggpht.com/-sKgkV1tAcdw/AAAAAAAAAAI/AAAAAAAAAAA/bdx2erQNwJQ/s100-mo-c-c0xffffffff-rj-k-no/photo.jpg)

[Link to Swedron](https://www.swedron.se)
If needed, try the twitter handles profile image: [twitter.com/swedronsverige](https://twitter.com/swedronsverige)
If needed, try the facebook handles profile image: [fb.com/swedronsverige](https://fb.com/swedronsverige)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.swedron.se](https://www.alexa.com/siteinfo/www.swedron.se)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.swedron.se](https://www.scamadviser.com/check-website/www.swedron.se)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.swedron.se](https://www.trustpilot.com/review/www.swedron.se)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
