### ISSUE TITLE
Add 'Regenscape' to the 'Skin Care' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1227]
Requesting to add 'Regenscape' to the 'Skin Care' category. 

Details follow: 
```yml 
- name: Regenscape
      url: https://regenscape.com/index.php/shop/
      img: 
      facebook: regenscape/
      email_address: evan@regenscape.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://regenscape.com/index.php/2018/07/07/how-to-get-started-in-bitcoin-for-free/
      exceptions: 
        text: "We are set up with coinpayments.net"
```

Resources for adding this merchant:
Logo Provided:
![Regenscape](http://regenscape.com/wp-content/uploads/2017/10/Logo-from-facebook-e1535849284965.jpg)

[Link to Regenscape](https://regenscape.com/index.php/shop/)
If needed, try the facebook handles profile image: [fb.com/regenscape/](https://fb.com/regenscape/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/regenscape.com/index.php/shop/](https://www.alexa.com/siteinfo/regenscape.com/index.php/shop/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/regenscape.com/index.php/shop/](https://www.scamadviser.com/check-website/regenscape.com/index.php/shop/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/regenscape.com/index.php/shop/](https://www.trustpilot.com/review/regenscape.com/index.php/shop/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
