### ISSUE TITLE
Please Review Sun Kratom

### ISSUE THREAD

**Issue by kmajor** [acceptbitcoincash/acceptbitcoincash#1228]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{Sun Kratom}} to the {{**Retail**}} category. Details follow:

```yml

- name: Sun Kratom 
  url: https://sunkratom.com
  img: https://sunkratom.com/content/uploads/2017/06/sun_kratom_logo_small-1.png
  twitter: sunkratom
  facebook: sunkratom
  region: na
  country: US
  city: 
  bch: yes
  btc: yes
  othercrypto: yes
  doc:
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
