### ISSUE TITLE
Add 'Indiequid' to the 'Online Retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1229]
Requesting to add 'Indiequid' to the 'Online Retailer' category. 

Details follow: 
```yml 
- name: Indiequid
      url: https://indiequid.com/
      img: 
      facebook: Indiequid-1750338658349419
      email_address: jeandelarue2002@hotmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.facebook.com/1750338658349419/photos/a.1750368655013086/1753884191328199/
```

Resources for adding this merchant:
Logo Provided:
![Indiequid](https://cdn.shopify.com/s/files/1/0034/3146/5030/files/racoonv2_180x@2x.png?v=1535611204)

[Link to Indiequid](https://indiequid.com/)
If needed, try the facebook handles profile image: [fb.com/Indiequid-1750338658349419](https://fb.com/Indiequid-1750338658349419)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/indiequid.com/](https://www.alexa.com/siteinfo/indiequid.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/indiequid.com/](https://www.scamadviser.com/check-website/indiequid.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/indiequid.com/](https://www.trustpilot.com/review/indiequid.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
