### ISSUE TITLE
Add 'Iozeta' to the 'IoT' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1230]
Requesting to add 'Iozeta' to the 'IoT' category. 

Details follow: 
```yml 
- name: Iozeta
      url: https://www.iozeta.com
      img: 
      twitter: iozeta
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Iozeta](https://www.iozeta.com/wp-content/uploads/2018/09/iozeta-128x128.png)

[Link to Iozeta](https://www.iozeta.com)
If needed, try the twitter handles profile image: [twitter.com/iozeta](https://twitter.com/iozeta)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.iozeta.com](https://www.alexa.com/siteinfo/www.iozeta.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.iozeta.com](https://www.scamadviser.com/check-website/www.iozeta.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.iozeta.com](https://www.trustpilot.com/review/www.iozeta.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
