### ISSUE TITLE
Add 'MarketingPont.com' to the 'Digital Marketing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1231]
Requesting to add 'MarketingPont.com' to the 'Digital Marketing' category. 

Details follow: 
```yml 
- name: MarketingPont.com
      url: https://marketingpont.com/
      img: 
      twitter: marketingpont
      facebook: marketingpont
      email_address: info@marketingpont.com
      region: sa
      country: AR
      city: Buenos Aires
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![MarketingPont.com](https://marketingpont.com/wp-content/uploads/2018/09/marketingpont_com-logo-twitter.png)

[Link to MarketingPont.com](https://marketingpont.com/)
If needed, try the twitter handles profile image: [twitter.com/marketingpont](https://twitter.com/marketingpont)
If needed, try the facebook handles profile image: [fb.com/marketingpont](https://fb.com/marketingpont)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/marketingpont.com/](https://www.alexa.com/siteinfo/marketingpont.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/marketingpont.com/](https://www.scamadviser.com/check-website/marketingpont.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/marketingpont.com/](https://www.trustpilot.com/review/marketingpont.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
