### ISSUE TITLE
Add ' Nature Provides - Shilajit' to the 'Health & Beauty' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1232]
Requesting to add ' Nature Provides - Shilajit' to the 'Health & Beauty' category. 

Details follow: 
```yml 
- name:  Nature Provides - Shilajit
      url: https://mountain-blood.com/
      img: 
      facebook: NatureProvidesLtd
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![ Nature Provides - Shilajit](https://cdn.shopify.com/s/files/1/1889/5775/files/NPLogo_website_450x.png?v=1534781315)

[Link to  Nature Provides - Shilajit](https://mountain-blood.com/)
If needed, try the facebook handles profile image: [fb.com/NatureProvidesLtd](https://fb.com/NatureProvidesLtd)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/mountain-blood.com/](https://www.alexa.com/siteinfo/mountain-blood.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/mountain-blood.com/](https://www.scamadviser.com/check-website/mountain-blood.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/mountain-blood.com/](https://www.trustpilot.com/review/mountain-blood.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
