### ISSUE TITLE
Add 'WP-GPL' to the 'Software' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1234]
Requesting to add 'WP-GPL' to the 'Software' category. 

Details follow: 
```yml 
- name: WP-GPL
      url: https://wp-gpl.org
      img: 
      email_address: jack@wp-gpl.org
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://wp-gpl.org
```

Resources for adding this merchant:
[Link to WP-GPL](https://wp-gpl.org)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/wp-gpl.org](https://www.alexa.com/siteinfo/wp-gpl.org)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/wp-gpl.org](https://www.scamadviser.com/check-website/wp-gpl.org)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/wp-gpl.org](https://www.trustpilot.com/review/wp-gpl.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
