### ISSUE TITLE
Add 'Iru Doramas Translation Services' to the 'Translation services - English to Spanish' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1235]
Requesting to add 'Iru Doramas Translation Services' to the 'Translation services - English to Spanish' category. 

Details follow: 
```yml 
- name: Iru Doramas Translation Services
      url: http://www.irudoramas.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Iru Doramas Translation Services](http://www.irudoramas.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.irudoramas.com](https://www.alexa.com/siteinfo/www.irudoramas.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.irudoramas.com](https://www.scamadviser.com/check-website/www.irudoramas.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.irudoramas.com](https://www.trustpilot.com/review/www.irudoramas.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
