### ISSUE TITLE
Add 'Spin and win BCH' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1236]
Requesting to add 'Spin and win BCH' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Spin and win BCH
      url: https://spinbch.com/
      img: 
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Spin and win BCH](https://spinbch.com/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/spinbch.com/](https://www.alexa.com/siteinfo/spinbch.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/spinbch.com/](https://www.scamadviser.com/check-website/spinbch.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/spinbch.com/](https://www.trustpilot.com/review/spinbch.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
