### ISSUE TITLE
Add 'SpinBCH.com' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1237]
Requesting to add 'SpinBCH.com' to the 'Gambling' category. 

Details follow: 
```yml 
- name: SpinBCH.com
      url: https://SpinBCH.com/
      img: 
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to SpinBCH.com](https://SpinBCH.com/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/SpinBCH.com/](https://www.alexa.com/siteinfo/SpinBCH.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/SpinBCH.com/](https://www.scamadviser.com/check-website/SpinBCH.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/SpinBCH.com/](https://www.trustpilot.com/review/SpinBCH.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
