### ISSUE TITLE
Add 'Salzkeller' to the 'Health & Beauty' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1238]
Requesting to add 'Salzkeller' to the 'Health & Beauty' category. 

Details follow: 
```yml 
- name: Salzkeller
      url: https://www.salzkeller.ch/
      img: 
      facebook: salzkellerchur
      email_address: mail@salzkeller.ch
      region: eu
      country: CH
      city: Chur
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/9d8nxl/float_with_bitcoin_cash_spa_in_chur_switzerland/
```

Resources for adding this merchant:
Logo Provided:
![Salzkeller](https://dashboard.coin-garden.io/assets/images/pos/117/logo_small.png)

[Link to Salzkeller](https://www.salzkeller.ch/)
If needed, try the facebook handles profile image: [fb.com/salzkellerchur](https://fb.com/salzkellerchur)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.salzkeller.ch/](https://www.alexa.com/siteinfo/www.salzkeller.ch/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.salzkeller.ch/](https://www.scamadviser.com/check-website/www.salzkeller.ch/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.salzkeller.ch/](https://www.trustpilot.com/review/www.salzkeller.ch/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
