### ISSUE TITLE
Add 'Tarriss' to the 'Products' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1239]
Requesting to add 'Tarriss' to the 'Products' category. 

Details follow: 
```yml 
- name: Tarriss
      url: https://tarriss.com/
      img: 
      twitter: tarrissgear
      facebook: tarrisstravelgear
      email_address: marketing-directories@tarriss.com
      country: US
      city: No. It is applicable to any city.
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Tarriss](https://tarriss.com/)
If needed, try the twitter handles profile image: [twitter.com/tarrissgear](https://twitter.com/tarrissgear)
If needed, try the facebook handles profile image: [fb.com/tarrisstravelgear](https://fb.com/tarrisstravelgear)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/tarriss.com/](https://www.alexa.com/siteinfo/tarriss.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/tarriss.com/](https://www.scamadviser.com/check-website/tarriss.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/tarriss.com/](https://www.trustpilot.com/review/tarriss.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
