### ISSUE TITLE
Add 'Greyman Design ' to the 'Graphic Design ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1240]
Requesting to add 'Greyman Design ' to the 'Graphic Design ' category. 

Details follow: 
```yml 
- name: Greyman Design 
      url: http://greymandesign.com
      img: 
      facebook: greymandesign/
      email_address: greymandesign@protonmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.facebook.com/greymandesign/photos/a.1542343829244355/1541847729293965/?type=3&theater
```

Resources for adding this merchant:
[Link to Greyman Design ](http://greymandesign.com)
If needed, try the facebook handles profile image: [fb.com/greymandesign/](https://fb.com/greymandesign/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/greymandesign.com](https://www.alexa.com/siteinfo/greymandesign.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/greymandesign.com](https://www.scamadviser.com/check-website/greymandesign.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/greymandesign.com](https://www.trustpilot.com/review/greymandesign.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
