### ISSUE TITLE
Add 'More Stamps Global' to the 'Acommodation, Transport' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1241]
Requesting to add 'More Stamps Global' to the 'Acommodation, Transport' category. 

Details follow: 
```yml 
- name: More Stamps Global
      url: https://www.morestamps.global
      img: 
      twitter: MoreStamps
      facebook: MoreStampsGlobal
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![More Stamps Global](https://scontent.fmuc3-1.fna.fbcdn.net/v/t1.0-0/cp0/e15/q65/p200x200/35415637_205418453429791_4176408280026841088_n.jpg?_nc_cat=0&oh=adf6d2a6c87247fc7f492ee61ef5d3ed&oe=5C14B262)

[Link to More Stamps Global](https://www.morestamps.global)
If needed, try the twitter handles profile image: [twitter.com/MoreStamps](https://twitter.com/MoreStamps)
If needed, try the facebook handles profile image: [fb.com/MoreStampsGlobal](https://fb.com/MoreStampsGlobal)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.morestamps.global](https://www.alexa.com/siteinfo/www.morestamps.global)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.morestamps.global](https://www.scamadviser.com/check-website/www.morestamps.global)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.morestamps.global](https://www.trustpilot.com/review/www.morestamps.global)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
