### ISSUE TITLE
Add 'Norderly' to the 'Services' category

### ISSUE THREAD

**Issue by fraktar** [acceptbitcoincash/acceptbitcoincash#1243]
Requesting to add **Norderly** to the **Developer** or **Services** category. Details follow:

```yml

- name: Norderly
  url: https://www.norderly.com
  img: https://www.norderly.com/assets/nOrderly-header.png
  region: na, eu
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://www.norderly.com/accepting-bitcoin-cash-payment-logo/
```

This is a website that offers custom graphics such as logo design. Currentlly it is accepting Bitcoin Cash, Bitcoin & Ethereum as payment methods. 

Consider adding a **Design** category.
