### ISSUE TITLE
Add 'Shuttle Delivery' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1244]
Requesting to add 'Shuttle Delivery' to the 'Food' category. 

Details follow: 
```yml 
- name: Shuttle Delivery
      url: https://www.shuttledelivery.co.kr/en
      img: 
      twitter: shuttledelivery
      facebook: ShuttleDeliveryCo
      email_address: info@shuttledelivery.co.kr
      region: as
      country: KR
      city: Seoul
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/9gb01i/you_can_now_use_bitcoin_bch_to_buy_any_kind_of/
```

Resources for adding this merchant:
Logo Provided:
![Shuttle Delivery](https://www.shuttledelivery.co.kr/favicon.ico)

[Link to Shuttle Delivery](https://www.shuttledelivery.co.kr/en)
If needed, try the twitter handles profile image: [twitter.com/shuttledelivery](https://twitter.com/shuttledelivery)
If needed, try the facebook handles profile image: [fb.com/ShuttleDeliveryCo](https://fb.com/ShuttleDeliveryCo)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.shuttledelivery.co.kr/en](https://www.alexa.com/siteinfo/www.shuttledelivery.co.kr/en)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.shuttledelivery.co.kr/en](https://www.scamadviser.com/check-website/www.shuttledelivery.co.kr/en)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.shuttledelivery.co.kr/en](https://www.trustpilot.com/review/www.shuttledelivery.co.kr/en)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
