### ISSUE TITLE
Add 'Molon Labe Brand' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1245]
Requesting to add 'Molon Labe Brand' to the 'Retail' category. 

Details follow: 
```yml 
- name: Molon Labe Brand
      url: https://www.molonlabebrand.com/
      img: 
      facebook: molonlabe0
      email_address: molonlabe@molonlabebrand.com
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://www.facebook.com/molonlabe0/photos/a.676830492689110/676830459355780/?type=3&theater
```

Resources for adding this merchant:
Logo Provided:
![Molon Labe Brand](https://www.facebook.com/molonlabe0/photos/a.676837279355098/676837289355097/?type=3&theater)

[Link to Molon Labe Brand](https://www.molonlabebrand.com/)
If needed, try the facebook handles profile image: [fb.com/molonlabe0](https://fb.com/molonlabe0)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.molonlabebrand.com/](https://www.alexa.com/siteinfo/www.molonlabebrand.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.molonlabebrand.com/](https://www.scamadviser.com/check-website/www.molonlabebrand.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.molonlabebrand.com/](https://www.trustpilot.com/review/www.molonlabebrand.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
