### ISSUE TITLE
Add 'Inet.se' to the 'Computer parts' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1246]
Requesting to add 'Inet.se' to the 'Computer parts' category. 

Details follow: 
```yml 
- name: Inet.se
      url: https://www.inet.se/
      img: 
      twitter: inetse
      facebook: inet.se
      email_address: info@inet.se
      region: eu
      country: SE
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Inet.se](https://inetimg2.se/img/logo/inet-logo-rgb-pos.svg)

[Link to Inet.se](https://www.inet.se/)
If needed, try the twitter handles profile image: [twitter.com/inetse](https://twitter.com/inetse)
If needed, try the facebook handles profile image: [fb.com/inet.se](https://fb.com/inet.se)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.inet.se/](https://www.alexa.com/siteinfo/www.inet.se/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.inet.se/](https://www.scamadviser.com/check-website/www.inet.se/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.inet.se/](https://www.trustpilot.com/review/www.inet.se/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
