### ISSUE TITLE
Add 'Cointopay International B.V.' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1247]
Requesting to add 'Cointopay International B.V.' to the 'Payments' category. 

Details follow: 
```yml 
- name: Cointopay International B.V.
      url: https://cointopay.com
      img: 
      twitter: cointopay
      email_address: info@cointopay.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://cointopay.com/SearchResults.jsp?s=bitcoin+cash
      exceptions: 
        text: "Enable/Select it when signing up or enable it under Account > Wallet Preference"
```

Resources for adding this merchant:
Logo Provided:
![Cointopay International B.V.](https://pbs.twimg.com/profile_images/628576295924793346/PsNQuAyI_400x400.png)

[Link to Cointopay International B.V.](https://cointopay.com)
If needed, try the twitter handles profile image: [twitter.com/cointopay](https://twitter.com/cointopay)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/cointopay.com](https://www.alexa.com/siteinfo/cointopay.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/cointopay.com](https://www.scamadviser.com/check-website/cointopay.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/cointopay.com](https://www.trustpilot.com/review/cointopay.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
