### ISSUE TITLE
Add 'LensProxy' to the 'contact lenses' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1248]
Requesting to add 'LensProxy' to the 'contact lenses' category. 

Details follow: 
```yml 
- name: LensProxy
      url: https://lensproxy.com
      img: 
      email_address: lensproxy@gmail.com
      bch: Yes
      btc: No
      othercrypto: No
      doc: footer / FAQ
```

Resources for adding this merchant:
Logo Provided:
![LensProxy](https://lensproxy.com/assets/img/logos/logo.png)

[Link to LensProxy](https://lensproxy.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/lensproxy.com](https://www.alexa.com/siteinfo/lensproxy.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/lensproxy.com](https://www.scamadviser.com/check-website/lensproxy.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/lensproxy.com](https://www.trustpilot.com/review/lensproxy.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
