### ISSUE TITLE
Add 'Shuttle Delivery' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1249]
Requesting to add 'Shuttle Delivery' to the 'Food' category. 

Details follow: 
```yml 
- name: Shuttle Delivery
      url: https://www.shuttledelivery.co.kr/en
      img: 
      twitter: ShuttleDelivery
      facebook: ShuttleDeliveryCo
      region: as
      country: KR
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.coinwelt.de/2018/09/seoul-lieferservice-shuttle-delivery-akzeptiert-bitcoin-cash/
```

Resources for adding this merchant:
Logo Provided:
![Shuttle Delivery](https://scontent.fmuc3-1.fna.fbcdn.net/v/t1.0-0/cp0/e15/q65/p200x200/24909925_1451938328237556_3922439756839630182_n.png.jpg?_nc_cat=0&oh=f8edcf5f8965c2b9c43f87b769305eb8&oe=5C1E39FE)

[Link to Shuttle Delivery](https://www.shuttledelivery.co.kr/en)
If needed, try the twitter handles profile image: [twitter.com/ShuttleDelivery](https://twitter.com/ShuttleDelivery)
If needed, try the facebook handles profile image: [fb.com/ShuttleDeliveryCo](https://fb.com/ShuttleDeliveryCo)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.shuttledelivery.co.kr/en](https://www.alexa.com/siteinfo/www.shuttledelivery.co.kr/en)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.shuttledelivery.co.kr/en](https://www.scamadviser.com/check-website/www.shuttledelivery.co.kr/en)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.shuttledelivery.co.kr/en](https://www.trustpilot.com/review/www.shuttledelivery.co.kr/en)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
