### ISSUE TITLE
Add 'Nail Confidential' to the 'Beauty' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1250]
Requesting to add 'Nail Confidential' to the 'Beauty' category. 

Details follow: 
```yml 
- name: Nail Confidential
      url: http://nailconfidential.com
      img: 
      twitter: NailConf_Demi
      email_address: demi@nailconfidential.com
      region: na
      country: US
      city: Glendale/Los Angeles area
      bch: Yes
      btc: No
      othercrypto: No
      doc: nailconfidential.com
```

Resources for adding this merchant:
Logo Provided:
![Nail Confidential](https://pbs.twimg.com/profile_images/979212765444243456/mMj7dbtO_400x400.jpg)

[Link to Nail Confidential](http://nailconfidential.com)
If needed, try the twitter handles profile image: [twitter.com/NailConf_Demi](https://twitter.com/NailConf_Demi)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/nailconfidential.com](https://www.alexa.com/siteinfo/nailconfidential.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/nailconfidential.com](https://www.scamadviser.com/check-website/nailconfidential.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/nailconfidential.com](https://www.trustpilot.com/review/nailconfidential.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
