### ISSUE TITLE
Add 'Peaceful Warrior BCH' to the 'Jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1251]
Requesting to add 'Peaceful Warrior BCH' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: Peaceful Warrior BCH
      url: https://peacefulwarrior.cash
      img: 
      twitter: PWBCH
      email_address: peacefulwarriorbch@gmail.com
      bch: Yes
      btc: No
      othercrypto: No
      exceptions: 
        text: "Coinbase"
```

Resources for adding this merchant:
Logo Provided:
![Peaceful Warrior BCH](https://cdn.shopify.com/s/files/1/0076/1213/7590/files/1._Logo_Default_DONTTOUCH_x100@2x.png?v=1533215794)

[Link to Peaceful Warrior BCH](https://peacefulwarrior.cash)
If needed, try the twitter handles profile image: [twitter.com/PWBCH](https://twitter.com/PWBCH)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/peacefulwarrior.cash](https://www.alexa.com/siteinfo/peacefulwarrior.cash)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/peacefulwarrior.cash](https://www.scamadviser.com/check-website/peacefulwarrior.cash)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/peacefulwarrior.cash](https://www.trustpilot.com/review/peacefulwarrior.cash)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
