### ISSUE TITLE
Add 'BitClub Network' to the 'Bitcoin Mining' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1255]
Requesting to add 'BitClub Network' to the 'Bitcoin Mining' category. 

Details follow: 
```yml 
- name: BitClub Network
      url: https://bitclub.bz/easybitcoin
      img: 
      email_address: easybitcoin@tutanota.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to BitClub Network](https://bitclub.bz/easybitcoin)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bitclub.bz/easybitcoin](https://www.alexa.com/siteinfo/bitclub.bz/easybitcoin)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bitclub.bz/easybitcoin](https://www.scamadviser.com/check-website/bitclub.bz/easybitcoin)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bitclub.bz/easybitcoin](https://www.trustpilot.com/review/bitclub.bz/easybitcoin)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
