### ISSUE TITLE
Add 'ozdingo' to the 'Online Store: Health & Beauty, Home & Garden, Pet Supplies, Toys & Gadgets, Electronics, Farming Supplies, Tools & Hardware, and more.' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1263]
Requesting to add 'ozdingo' to the 'Online Store: Health & Beauty, Home & Garden, Pet Supplies, Toys & Gadgets, Electronics, Farming Supplies, Tools & Hardware, and more.' category. 

Details follow: 
```yml 
- name: ozdingo
      url: https://ozdingo.com.au/
      img: 
      twitter: ozdingo_au
      facebook: ozdingo.com.au
      email_address: info@ozdingo.com
      country: AU
      city: Free Shipping Australia Wide - DHL Global Shipping
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/ozdingo_au/status/1044001528187514881
      exceptions: 
        text: "Available at checkout as part of payment options"
```

Resources for adding this merchant:
Logo Provided:
![ozdingo](https://cdn.shopify.com/s/files/1/1070/6400/t/23/assets/logo.png?759751692955862702)

[Link to ozdingo](https://ozdingo.com.au/)
If needed, try the twitter handles profile image: [twitter.com/ozdingo_au](https://twitter.com/ozdingo_au)
If needed, try the facebook handles profile image: [fb.com/ozdingo.com.au](https://fb.com/ozdingo.com.au)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/ozdingo.com.au/](https://www.alexa.com/siteinfo/ozdingo.com.au/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/ozdingo.com.au/](https://www.scamadviser.com/check-website/ozdingo.com.au/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/ozdingo.com.au/](https://www.trustpilot.com/review/ozdingo.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
