### ISSUE TITLE
Add 'Fivebucks' to the 'Freelance services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1269]
Requesting to add 'Fivebucks' to the 'Freelance services' category. 

Details follow: 
```yml 
- name: Fivebucks
      url: https://fivebucks.com/
      img: 
      twitter: fivebuckscom
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Fivebucks](https://memo.cash/img/profilepics/131HonjNwGVDM8mFUR6wq9trZ7fLHSgJCq-128x128.png?id=600)

[Link to Fivebucks](https://fivebucks.com/)
If needed, try the twitter handles profile image: [twitter.com/fivebuckscom](https://twitter.com/fivebuckscom)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/fivebucks.com/](https://www.alexa.com/siteinfo/fivebucks.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/fivebucks.com/](https://www.scamadviser.com/check-website/fivebucks.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/fivebucks.com/](https://www.trustpilot.com/review/fivebucks.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
