### ISSUE TITLE
Add 'iMANIA.dk' to the 'Smartphone accessories and repairs' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1270]
Requesting to add 'iMANIA.dk' to the 'Smartphone accessories and repairs' category. 

Details follow: 
```yml 
- name: iMANIA.dk
      url: https://www.imania.dk/
      img: 
      twitter: iManiadk
      region: eu
      country: DK
      city: Aalborg
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.imania.dk/bitcoin.htm
```

Resources for adding this merchant:
Logo Provided:
![iMANIA.dk](https://www.imania.dk/mediafiles/images/iManiaLilleDK.png)

[Link to iMANIA.dk](https://www.imania.dk/)
If needed, try the twitter handles profile image: [twitter.com/iManiadk](https://twitter.com/iManiadk)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.imania.dk/](https://www.alexa.com/siteinfo/www.imania.dk/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.imania.dk/](https://www.scamadviser.com/check-website/www.imania.dk/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.imania.dk/](https://www.trustpilot.com/review/www.imania.dk/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
