### ISSUE TITLE
Add 'HoneySexDoll' to the 'Adult Sex Doll' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1271]
Requesting to add 'HoneySexDoll' to the 'Adult Sex Doll' category. 

Details follow: 
```yml 
- name: HoneySexDoll
      url: https://honeysexdoll.com
      img: 
      facebook: honeysexdoll
      email_address: support@honeysexdoll.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Just follow the checkout process and pay as selecting the Cryptocoin"
```

Resources for adding this merchant:
[Link to HoneySexDoll](https://honeysexdoll.com)
If needed, try the facebook handles profile image: [fb.com/honeysexdoll](https://fb.com/honeysexdoll)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/honeysexdoll.com](https://www.alexa.com/siteinfo/honeysexdoll.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/honeysexdoll.com](https://www.scamadviser.com/check-website/honeysexdoll.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/honeysexdoll.com](https://www.trustpilot.com/review/honeysexdoll.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
