### ISSUE TITLE
Add '13-37.org electronics' to the 'Electronics' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1272]
Requesting to add '13-37.org electronics' to the 'Electronics' category. 

Details follow: 
```yml 
- name: 13-37.org electronics
      url: https://13-37.org/en/
      img: 
      email_address: info@13-37.org
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Coingate payment processor"
```

Resources for adding this merchant:
[Link to 13-37.org electronics](https://13-37.org/en/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/13-37.org/en/](https://www.alexa.com/siteinfo/13-37.org/en/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/13-37.org/en/](https://www.scamadviser.com/check-website/13-37.org/en/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/13-37.org/en/](https://www.trustpilot.com/review/13-37.org/en/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
