### ISSUE TITLE
Add 'Law Offices of Jason D. Knott, P.A.' to the 'Legal' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1273]
Requesting to add 'Law Offices of Jason D. Knott, P.A.' to the 'Legal' category. 

Details follow: 
```yml 
- name: Law Offices of Jason D. Knott, P.A.
      url: https://www.lawofficesofjasonknott.com/
      img: 
      twitter: IntlTaxLawyers
      facebook: lawofficesjasonknott
      email_address: contact@knott-firm.com
      country: US
      city: Lakewood Ranch
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.lawofficesofjasonknott.com/makepayment
```

Resources for adding this merchant:
Logo Provided:
![Law Offices of Jason D. Knott, P.A.](https://www.lawofficesofjasonknott.com/img/logo.png)

[Link to Law Offices of Jason D. Knott, P.A.](https://www.lawofficesofjasonknott.com/)
If needed, try the twitter handles profile image: [twitter.com/IntlTaxLawyers](https://twitter.com/IntlTaxLawyers)
If needed, try the facebook handles profile image: [fb.com/lawofficesjasonknott](https://fb.com/lawofficesjasonknott)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.lawofficesofjasonknott.com/](https://www.alexa.com/siteinfo/www.lawofficesofjasonknott.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.lawofficesofjasonknott.com/](https://www.scamadviser.com/check-website/www.lawofficesofjasonknott.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.lawofficesofjasonknott.com/](https://www.trustpilot.com/review/www.lawofficesofjasonknott.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
