### ISSUE TITLE
Add 'Trendy Stone Jewelry' to the 'Health & Beauty' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1274]
Requesting to add 'Trendy Stone Jewelry' to the 'Health & Beauty' category. 

Details follow: 
```yml 
- name: Trendy Stone Jewelry
      url: https://www.trendystonejewelry.com/
      img: 
      twitter: TrendyStone
      facebook: trendystonejewelry
      email_address: sales@trendystonejewelry.com
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://twitter.com/TrendyStone/status/1033799974788771841
```

Resources for adding this merchant:
Logo Provided:
![Trendy Stone Jewelry](https://www.trendystonejewelry.com/skin/frontend/default/theme563/images/logo.gif)

[Link to Trendy Stone Jewelry](https://www.trendystonejewelry.com/)
If needed, try the twitter handles profile image: [twitter.com/TrendyStone](https://twitter.com/TrendyStone)
If needed, try the facebook handles profile image: [fb.com/trendystonejewelry](https://fb.com/trendystonejewelry)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.trendystonejewelry.com/](https://www.alexa.com/siteinfo/www.trendystonejewelry.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.trendystonejewelry.com/](https://www.scamadviser.com/check-website/www.trendystonejewelry.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.trendystonejewelry.com/](https://www.trustpilot.com/review/www.trendystonejewelry.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
