### ISSUE TITLE
Add 'Senang.Online Domain Names & Website Hosting' to the 'Domains' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1275]
Requesting to add 'Senang.Online Domain Names & Website Hosting' to the 'Domains' category. 

Details follow: 
```yml 
- name: Senang.Online Domain Names & Website Hosting
      url: https://web.senang.online
      img: 
      twitter: senangonline
      facebook: 1021871104598115
      email_address: so@senang.online
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://t.me/SenangBit/724
      exceptions: 
        text: "1. Submit order and choose PAY OFFLINE to get total amount due in your choice of fiat (RM, USD etc.).

2. Make payment for the billed amount in fiat - choose BCH:

>>> https://gocps.net/mipgcsffd4tb1jml9x1c2xl3

- The amount in BCH shown has been adjusted to reflect a time-sensitive, discounted price - complete the payment in shown period.

3. Contact us to acknowledge your payment: http://senang.online/support"
```

Resources for adding this merchant:
Logo Provided:
![Senang.Online Domain Names & Website Hosting](https://cdnassets.com/ui/resellerdata/30000_59999/47767/supersite2/supersite/themes/EliteGreen-ResponsiveTheme/images/logo.gif)

[Link to Senang.Online Domain Names & Website Hosting](https://web.senang.online)
If needed, try the twitter handles profile image: [twitter.com/senangonline](https://twitter.com/senangonline)
If needed, try the facebook handles profile image: [fb.com/1021871104598115](https://fb.com/1021871104598115)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/web.senang.online](https://www.alexa.com/siteinfo/web.senang.online)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/web.senang.online](https://www.scamadviser.com/check-website/web.senang.online)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/web.senang.online](https://www.trustpilot.com/review/web.senang.online)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
