### ISSUE TITLE
Add 'Voipbuster' to the 'voip' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1276]
Requesting to add 'Voipbuster' to the 'voip' category. 

Details follow: 
```yml 
- name: Voipbuster
      url: https://voipbuster.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "bitpay"
```

Resources for adding this merchant:
Logo Provided:
![Voipbuster](http://www.voipbuster.com/public/assets/images/logo.gif)

[Link to Voipbuster](https://voipbuster.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/voipbuster.com](https://www.alexa.com/siteinfo/voipbuster.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/voipbuster.com](https://www.scamadviser.com/check-website/voipbuster.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/voipbuster.com](https://www.trustpilot.com/review/voipbuster.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
