### ISSUE TITLE
Add 'People's Pub' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1278]
Requesting to add 'People's Pub' to the 'Food' category. 

Details follow: 
```yml 
- name: People's Pub
      url: https://www.facebook.com/PeoplesPub/
      img: 
      email_address: peoplespubnb@gmail.com
      region: na
      country: CA
      city: St. Stephen
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.facebook.com/PeoplesPub/posts/2191402587761488?__xts__[0]=68.ARDV3h_2LCDcnrKFR5AGXpYCINQWV4AzpV8qZCCQtHN1Flr5oq8u_7CgUsAJaj15q4iAg8ogKxXER76JJOs76GeNaUdAvFKm-QSGiqKHGrkcz4jhHJ7JSQoVbLWl67YuBtZrChp05Pm5N9P2iBjTVOiU63ndHwvfn1m8x_GQn_dRQTOY8kSPbw&__tn__=-R
```

Resources for adding this merchant:
[Link to People's Pub](https://www.facebook.com/PeoplesPub/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.facebook.com/PeoplesPub/](https://www.alexa.com/siteinfo/www.facebook.com/PeoplesPub/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.facebook.com/PeoplesPub/](https://www.scamadviser.com/check-website/www.facebook.com/PeoplesPub/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.facebook.com/PeoplesPub/](https://www.trustpilot.com/review/www.facebook.com/PeoplesPub/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
