### ISSUE TITLE
Add 'MmoGah.com' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1280]
Requesting to add 'MmoGah.com' to the 'Gaming' category. 

Details follow: 
```yml 
- name: MmoGah.com
      url: https://www.mmogah.com/
      img: 
      twitter: mmogah_com
      facebook: MmoGahGold
      email_address: mmogah@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Select Coinbase Commerce during checkout then select bitcoin cash."
```

Resources for adding this merchant:
Logo Provided:
![MmoGah.com](https://cdn.mmogah.com/Public/imagesqt/Mmogah.png)

[Link to MmoGah.com](https://www.mmogah.com/)
If needed, try the twitter handles profile image: [twitter.com/mmogah_com](https://twitter.com/mmogah_com)
If needed, try the facebook handles profile image: [fb.com/MmoGahGold](https://fb.com/MmoGahGold)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.mmogah.com/](https://www.alexa.com/siteinfo/www.mmogah.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.mmogah.com/](https://www.scamadviser.com/check-website/www.mmogah.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.mmogah.com/](https://www.trustpilot.com/review/www.mmogah.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
