### ISSUE TITLE
Add 'G-Nome Computers' to the 'IT, Computer Repairs, Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1284]
Requesting to add 'G-Nome Computers' to the 'IT, Computer Repairs, Retail' category. 

Details follow: 
```yml 
- name: G-Nome Computers
      url: https://www.g-nome.co.za/
      img: 
      email_address: info@g-nome.co.za
      region: af
      country: ZA
      city: Johannesburg
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.g-nome.co.za/
      exceptions: 
        text: "No"
```

Resources for adding this merchant:
[Link to G-Nome Computers](https://www.g-nome.co.za/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.g-nome.co.za/](https://www.alexa.com/siteinfo/www.g-nome.co.za/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.g-nome.co.za/](https://www.scamadviser.com/check-website/www.g-nome.co.za/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.g-nome.co.za/](https://www.trustpilot.com/review/www.g-nome.co.za/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
