### ISSUE TITLE
Add 'CryptoLamboMerch.com' to the 'Crypto themed apparel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1285]
Requesting to add 'CryptoLamboMerch.com' to the 'Crypto themed apparel' category. 

Details follow: 
```yml 
- name: CryptoLamboMerch.com
      url: https://www.cryptolambomerch.com
      img: 
      email_address: joel.holsinger@yahoo.com
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to CryptoLamboMerch.com](https://www.cryptolambomerch.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.cryptolambomerch.com](https://www.alexa.com/siteinfo/www.cryptolambomerch.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.cryptolambomerch.com](https://www.scamadviser.com/check-website/www.cryptolambomerch.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.cryptolambomerch.com](https://www.trustpilot.com/review/www.cryptolambomerch.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
