### ISSUE TITLE
Add 'DotcomWriters' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1286]
Requesting to add 'DotcomWriters' to the 'Services' category. 

Details follow: 
```yml 
- name: DotcomWriters
      url: http://dotcomwriters.com
      img: 
      twitter: dotcomwriters
      email_address: admin@dotcomwriters.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "User must contact the admin to make a custom request. This may be done through the contact form."
```

Resources for adding this merchant:
Logo Provided:
![DotcomWriters](http://dotcomwriters.com/wp-content/uploads/2017/08/cropped-DotComWriters-1.png)

[Link to DotcomWriters](http://dotcomwriters.com)
If needed, try the twitter handles profile image: [twitter.com/dotcomwriters](https://twitter.com/dotcomwriters)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/dotcomwriters.com](https://www.alexa.com/siteinfo/dotcomwriters.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/dotcomwriters.com](https://www.scamadviser.com/check-website/dotcomwriters.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/dotcomwriters.com](https://www.trustpilot.com/review/dotcomwriters.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
