### ISSUE TITLE
Add 'Bitcoin MXN' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1287]
Requesting to add 'Bitcoin MXN' to the 'Services' category. 

Details follow: 
```yml 
- name: Bitcoin MXN
      url: http://bitcoinmxn.com/enviar-ico/
      img: 
      twitter: mxn_bitcoin
      facebook: bitcoinmxnoficial/
      email_address: admin@bitcoinmxn.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Use the contact form when requesting a press release or other service."
```

Resources for adding this merchant:
Logo Provided:
![Bitcoin MXN](https://pbs.twimg.com/profile_images/939872367534321664/ZQy2qW5v_400x400.jpg)

[Link to Bitcoin MXN](http://bitcoinmxn.com/enviar-ico/)
If needed, try the twitter handles profile image: [twitter.com/mxn_bitcoin](https://twitter.com/mxn_bitcoin)
If needed, try the facebook handles profile image: [fb.com/bitcoinmxnoficial/](https://fb.com/bitcoinmxnoficial/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bitcoinmxn.com/enviar-ico/](https://www.alexa.com/siteinfo/bitcoinmxn.com/enviar-ico/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bitcoinmxn.com/enviar-ico/](https://www.scamadviser.com/check-website/bitcoinmxn.com/enviar-ico/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bitcoinmxn.com/enviar-ico/](https://www.trustpilot.com/review/bitcoinmxn.com/enviar-ico/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
