### ISSUE TITLE
Add 'FabFox.co.uk' to the 'Jewellery' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1288]
Requesting to add 'FabFox.co.uk' to the 'Jewellery' category. 

Details follow: 
```yml 
- name: FabFox.co.uk
      url: https://FabFox.co.uk
      img: 
      twitter: FabFoxUK
      facebook: FabFox.co.uk
      email_address: online@fabfox.co.uk
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Simply pay at checkout"
```

Resources for adding this merchant:
Logo Provided:
![FabFox.co.uk](https://fabfox.co.uk/wp-content/uploads/2018/07/fab-fox-logo-2-tilted.png)

[Link to FabFox.co.uk](https://FabFox.co.uk)
If needed, try the twitter handles profile image: [twitter.com/FabFoxUK](https://twitter.com/FabFoxUK)
If needed, try the facebook handles profile image: [fb.com/FabFox.co.uk](https://fb.com/FabFox.co.uk)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/FabFox.co.uk](https://www.alexa.com/siteinfo/FabFox.co.uk)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/FabFox.co.uk](https://www.scamadviser.com/check-website/FabFox.co.uk)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/FabFox.co.uk](https://www.trustpilot.com/review/FabFox.co.uk)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
