### ISSUE TITLE
Add 'Satoshing' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1289]
Requesting to add 'Satoshing' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Satoshing
      url: https://www.satoshing.com
      img: 
      twitter: satoshingcom
      email_address: info@satoshing.com
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Satoshing](https://www.satoshing.com/satologo.png)

[Link to Satoshing](https://www.satoshing.com)
If needed, try the twitter handles profile image: [twitter.com/satoshingcom](https://twitter.com/satoshingcom)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.satoshing.com](https://www.alexa.com/siteinfo/www.satoshing.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.satoshing.com](https://www.scamadviser.com/check-website/www.satoshing.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.satoshing.com](https://www.trustpilot.com/review/www.satoshing.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
