### ISSUE TITLE
Add 'Little Fish Store' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1290]
Requesting to add 'Little Fish Store' to the 'Retail' category. 

Details follow: 
```yml 
- name: Little Fish Store
      url: https://littlefishstore.com
      img: 
      facebook: buyshrimpandfishonline
      email_address: lfs@littlefishstore.com
      region: na
      country: US
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Little Fish Store](https://cdn.shopify.com/s/files/1/0050/7091/3651/files/Little-Fish-Store-128x128px.png)

[Link to Little Fish Store](https://littlefishstore.com)
If needed, try the facebook handles profile image: [fb.com/buyshrimpandfishonline](https://fb.com/buyshrimpandfishonline)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/littlefishstore.com](https://www.alexa.com/siteinfo/littlefishstore.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/littlefishstore.com](https://www.scamadviser.com/check-website/littlefishstore.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/littlefishstore.com](https://www.trustpilot.com/review/littlefishstore.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
