### ISSUE TITLE
Add 'Stake' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1291]
Requesting to add 'Stake' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Stake
      url: https://stake.com/
      img: 
      twitter: stake
      facebook: StakeCasino/
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/btc/comments/9ml8ee/stakecom_the_most_popular_crypto_casino_now/
      exceptions: 
        text: "Direct transaction - no payment processor"
```

Resources for adding this merchant:
Logo Provided:
![Stake](https://miro.medium.com/fit/c/240/240/1*ODxRJaZQK6v-rvEDUqHfqA.png)

[Link to Stake](https://stake.com/)
If needed, try the twitter handles profile image: [twitter.com/stake](https://twitter.com/stake)
If needed, try the facebook handles profile image: [fb.com/StakeCasino/](https://fb.com/StakeCasino/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/stake.com/](https://www.alexa.com/siteinfo/stake.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/stake.com/](https://www.scamadviser.com/check-website/stake.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/stake.com/](https://www.trustpilot.com/review/stake.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
