### ISSUE TITLE
Add 'NEWPARTS' to the 'Transport & Travel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1292]
Requesting to add 'NEWPARTS' to the 'Transport & Travel' category. 

Details follow: 
```yml 
- name: NEWPARTS
      url: https://www.newparts.com/
      img: 
      twitter: New_Parts
      facebook: NewPartsAutoParts/
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://news.bitcoin.com/online-automotive-parts-retailer-newparts-now-accepts-bitcoin-cash/
```

Resources for adding this merchant:
Logo Provided:
![NEWPARTS](https://www.newparts.com/Portals/10263/title-5.png)

[Link to NEWPARTS](https://www.newparts.com/)
If needed, try the twitter handles profile image: [twitter.com/New_Parts](https://twitter.com/New_Parts)
If needed, try the facebook handles profile image: [fb.com/NewPartsAutoParts/](https://fb.com/NewPartsAutoParts/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.newparts.com/](https://www.alexa.com/siteinfo/www.newparts.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.newparts.com/](https://www.scamadviser.com/check-website/www.newparts.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.newparts.com/](https://www.trustpilot.com/review/www.newparts.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
