### ISSUE TITLE
Add 'Cubebrush' to the 'Art ressources' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1293]
Requesting to add 'Cubebrush' to the 'Art ressources' category. 

Details follow: 
```yml 
- name: Cubebrush
      url: https://cubebrush.co
      img: 
      twitter: cubebrush
      facebook: cubebrush
      email_address: hello@cubebrush.co
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://cubebrush.co/blog/cubebrush-now-accepts-bitcoin
```

Resources for adding this merchant:
Logo Provided:
![Cubebrush](https://pbs.twimg.com/profile_images/898876059092787201/qDNOL0sM_400x400.jpg)

[Link to Cubebrush](https://cubebrush.co)
If needed, try the twitter handles profile image: [twitter.com/cubebrush](https://twitter.com/cubebrush)
If needed, try the facebook handles profile image: [fb.com/cubebrush](https://fb.com/cubebrush)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/cubebrush.co](https://www.alexa.com/siteinfo/cubebrush.co)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/cubebrush.co](https://www.scamadviser.com/check-website/cubebrush.co)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/cubebrush.co](https://www.trustpilot.com/review/cubebrush.co)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
