### ISSUE TITLE
Add 'FastX.io' to the 'Crypto Exchanges' category

### ISSUE THREAD

**Issue by rokanost** [acceptbitcoincash/acceptbitcoincash#1295]
Requesting to add 'FastX.io' to the 'Crypto Exchanges' category. Details follow:

```yml

- name: FastX
  url: https://fastx.io
  img: https://fastx.io/images/fastx_logo.jpg
  twitter: fastxcrypto
  facebook: fastxcrypto
  region: oc
  country: AU
  city: SYDNEY
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://fastx.io/disclosure
```
