### ISSUE TITLE
Add 'Apia Inn Samoa' to the 'Accomodation' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1305]
Requesting to add 'Apia Inn Samoa' to the 'Accomodation' category. 

Details follow: 
```yml 
- name: Apia Inn Samoa
      url: https://www.apiainnsamoa.com
      img: 
      twitter: apiainnsamoa
      facebook: apiainnsamoa
      email_address: info@apiainnsamoa.com
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.apiainnsamoa.com/now-accepting-bitcoin-cash/
```

Resources for adding this merchant:
[Link to Apia Inn Samoa](https://www.apiainnsamoa.com)
If needed, try the twitter handles profile image: [twitter.com/apiainnsamoa](https://twitter.com/apiainnsamoa)
If needed, try the facebook handles profile image: [fb.com/apiainnsamoa](https://fb.com/apiainnsamoa)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.apiainnsamoa.com](https://www.alexa.com/siteinfo/www.apiainnsamoa.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.apiainnsamoa.com](https://www.scamadviser.com/check-website/www.apiainnsamoa.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.apiainnsamoa.com](https://www.trustpilot.com/review/www.apiainnsamoa.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
