### ISSUE TITLE
Add 'Dope! Gallery' to the 'Fine Art' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1306]
Requesting to add 'Dope! Gallery' to the 'Fine Art' category. 

Details follow: 
```yml 
- name: Dope! Gallery
      url: https://dope.gallery
      img: 
      facebook: letartbeyourdope/
      email_address: info@dope.gallery
      region: as
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Dope! Gallery](https://dope.gallery)
If needed, try the facebook handles profile image: [fb.com/letartbeyourdope/](https://fb.com/letartbeyourdope/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/dope.gallery](https://www.alexa.com/siteinfo/dope.gallery)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/dope.gallery](https://www.scamadviser.com/check-website/dope.gallery)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/dope.gallery](https://www.trustpilot.com/review/dope.gallery)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
