### ISSUE TITLE
Add 'DAVDroid' to 'Donations/Software' category

### ISSUE THREAD

**Issue by haplo** [acceptbitcoincash/acceptbitcoincash#1307]
Requesting to add DAVDroid to the Donations/Software category. Details follow:

```yml

- name: DAVDroid
  url: https://www.davdroid.com/donate/
  img: DAVDroid.png
  twitter: davdroidapp
  facebook: 
  region: eu
  country: AT
  city: Bad Vöslau
  bch: yes
  btc: yes
  othercrypto: no
  doc: https://twitter.com/davdroidapp/status/1045246447682310146
```

DAVDroid is an open-source Android app that allows syncing of contacts and calendars to many WebDAV-enabled backends, such as Nextcloud.
