### ISSUE TITLE
Add 'TheBigCoin' to the 'Crypto Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1308]
Requesting to add 'TheBigCoin' to the 'Crypto Services' category. 

Details follow: 
```yml 
- name: TheBigCoin
      url: https://www.thebigcoin.io
      img: 
      twitter: thebigcoin_io
      facebook: TheBigCoin.io/
      email_address: support@thebigcoin.io
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.thebigcoin.io/pay-with-bitcoin-cash
```

Resources for adding this merchant:
Logo Provided:
![TheBigCoin](https://pbs.twimg.com/profile_images/1032208154094960640/v6YTsUkl_400x400.jpg)

[Link to TheBigCoin](https://www.thebigcoin.io)
If needed, try the twitter handles profile image: [twitter.com/thebigcoin_io](https://twitter.com/thebigcoin_io)
If needed, try the facebook handles profile image: [fb.com/TheBigCoin.io/](https://fb.com/TheBigCoin.io/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.thebigcoin.io](https://www.alexa.com/siteinfo/www.thebigcoin.io)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.thebigcoin.io](https://www.scamadviser.com/check-website/www.thebigcoin.io)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.thebigcoin.io](https://www.trustpilot.com/review/www.thebigcoin.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
