### ISSUE TITLE
Add 'BitSoapBox' to the 'Social' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1311]
Requesting to add 'BitSoapBox' to the 'Social' category. 

Details follow: 
```yml 
- name: BitSoapBox
      url: http://bitsoapbox.com
      img: 
      twitter: bitsoapbox
      email_address: admin@dotcomwriters.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Select Bitcoin Cash Payment under user options."
```

Resources for adding this merchant:
Logo Provided:
![BitSoapBox](https://pbs.twimg.com/profile_images/378800000127515990/7677d25f7fb05877492ce6240a952f8c_400x400.jpeg)
[Picresize Starter Link](http://www.picresize.com/api?fetch=https://pbs.twimg.com/profile_images/378800000127515990/7677d25f7fb05877492ce6240a952f8c_400x400.jpeg)

[Link to BitSoapBox](http://bitsoapbox.com)
If needed, try the twitter handles profile image: [twitter.com/bitsoapbox](https://twitter.com/bitsoapbox)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bitsoapbox.com](https://www.alexa.com/siteinfo/bitsoapbox.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bitsoapbox.com](https://www.scamadviser.com/check-website/bitsoapbox.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bitsoapbox.com](https://www.trustpilot.com/review/bitsoapbox.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
