### ISSUE TITLE
Add 'CoinPoint Group' to the 'Marketing ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1312]
Requesting to add 'CoinPoint Group' to the 'Marketing ' category. 

Details follow: 
```yml 
- name: CoinPoint Group
      url: https://www.coinpoint.net/
      img: 
      twitter: coinpointnet
      facebook: coinpoint
      email_address: oron@coinpoint.net
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![CoinPoint Group](https://www.coinpoint.net/wp-content/uploads/2016/02/coinpoint-black-300x62.png)
[Picresize Starter Link](http://www.picresize.com/api?fetch=https://pbs.twimg.com/profile_images/811390325428133889/UOKdPobQ_400x400.jpg)

[Link to CoinPoint Group](https://www.coinpoint.net/)
If needed, try the twitter handles profile image: [twitter.com/coinpointnet](https://twitter.com/coinpointnet)
If needed, try the facebook handles profile image: [fb.com/coinpoint/](https://fb.com/coinpoint/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.coinpoint.net/](https://www.alexa.com/siteinfo/www.coinpoint.net/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.coinpoint.net/](https://www.scamadviser.com/check-website/www.coinpoint.net/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.coinpoint.net/](https://www.trustpilot.com/review/www.coinpoint.net/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
