### ISSUE TITLE
Add 'Bitcoin Casino Affiliates' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1313]
Requesting to add 'Bitcoin Casino Affiliates' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Bitcoin Casino Affiliates
      url: https://www.bitcoincasinoaffiliates.com/
      img: 
      twitter: BitcoinCasinoA
      facebook: bitcoincasinoaffiliates/
      email_address: support@bitcoincasinoaffiliates.com
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Bitcoin Casino Affiliates](https://imgur.com/paOnfw7)
[Picresize Starter Link](http://www.picresize.com/api?fetch=https://imgur.com/paOnfw7)

[Link to Bitcoin Casino Affiliates](https://www.bitcoincasinoaffiliates.com/)
If needed, try the twitter handles profile image: [twitter.com/BitcoinCasinoA](https://twitter.com/BitcoinCasinoA)
If needed, try the facebook handles profile image: [fb.com/bitcoincasinoaffiliates/](https://fb.com/bitcoincasinoaffiliates/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.bitcoincasinoaffiliates.com/](https://www.alexa.com/siteinfo/www.bitcoincasinoaffiliates.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.bitcoincasinoaffiliates.com/](https://www.scamadviser.com/check-website/www.bitcoincasinoaffiliates.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.bitcoincasinoaffiliates.com/](https://www.trustpilot.com/review/www.bitcoincasinoaffiliates.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
