### ISSUE TITLE
Add 'Betcoin.Cash' to the 'Sports Tipping' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1315]
Requesting to add 'Betcoin.Cash' to the 'Sports Tipping' category. 

Details follow: 
```yml 
- name: Betcoin.Cash
      url: https://www.betcoin.cash/
      img: 
      twitter: BetcoinCash
      email_address: betcoin.cash@betcoin.cash
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Betcoin.Cash](https://imgur.com/GqV6B8G)
[Picresize Starter Link](http://www.picresize.com/api?fetch=https://imgur.com/GqV6B8G)

[Link to Betcoin.Cash](https://www.betcoin.cash/)
If needed, try the twitter handles profile image: [twitter.com/BetcoinCash](https://twitter.com/BetcoinCash)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.betcoin.cash/](https://www.alexa.com/siteinfo/www.betcoin.cash/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.betcoin.cash/](https://www.scamadviser.com/check-website/www.betcoin.cash/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.betcoin.cash/](https://www.trustpilot.com/review/www.betcoin.cash/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
