### ISSUE TITLE
Add '1gbits.com' to the 'datacenter' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1316]
Requesting to add '1gbits.com' to the 'datacenter' category. 

Details follow: 
```yml 
- name: 1gbits.com
      url: https://1gbits.com
      img: 
      twitter: 1gbits
      facebook: 1gbits
      email_address: sales@1gbits.com
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![1gbits.com](https://www.dash.org/assets/img/merchants/1gbits.jpg)
[Picresize Starter Link](http://www.picresize.com/api?fetch=https://www.dash.org/assets/img/merchants/1gbits.jpg)

[Link to 1gbits.com](https://1gbits.com)
If needed, try the twitter handles profile image: [twitter.com/1gbits](https://twitter.com/1gbits)
If needed, try the facebook handles profile image: [fb.com/1gbits](https://fb.com/1gbits)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/1gbits.com](https://www.alexa.com/siteinfo/1gbits.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/1gbits.com](https://www.scamadviser.com/check-website/1gbits.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/1gbits.com](https://www.trustpilot.com/review/1gbits.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
