### ISSUE TITLE
Add 'MAMACHA' to the 'Cafe' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1318]
Requesting to add 'MAMACHA' to the 'Cafe' category. 

Details follow: 
```yml 
- name: MAMACHA
      url: https://mamacha.nyc/
      img: 
      email_address: hello@mamacha.nyc
      region: na
      country: US
      city: New York City
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "They provide a QR code using a mobile app."
```

Resources for adding this merchant:
Logo Provided:
![MAMACHA](https://imgur.com/a/BujktIl)
[Link to MAMACHA](https://mamacha.nyc/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/mamacha.nyc/](https://www.alexa.com/siteinfo/mamacha.nyc/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/mamacha.nyc/](https://www.scamadviser.com/check-website/mamacha.nyc/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/mamacha.nyc/](https://www.trustpilot.com/review/mamacha.nyc/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @woodser
