### ISSUE TITLE
Add 'XBL4BTC.com' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1321]
Requesting to add 'XBL4BTC.com' to the 'Gaming' category. 

Details follow: 
```yml 
- name: XBL4BTC.com
      url: https://XBL4BTC.com
      img: 
      twitter: Eternalsale
      email_address: admin@xbl4btc.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to XBL4BTC.com](https://XBL4BTC.com)
If needed, try the twitter handles profile image: [twitter.com/Eternalsale](https://twitter.com/Eternalsale)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/XBL4BTC.com](https://www.alexa.com/siteinfo/XBL4BTC.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/XBL4BTC.com](https://www.scamadviser.com/check-website/XBL4BTC.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/XBL4BTC.com](https://www.trustpilot.com/review/XBL4BTC.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
