### ISSUE TITLE
Add 'Eternal Summer Sale' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1322]
Requesting to add 'Eternal Summer Sale' to the 'Gaming' category. 

Details follow: 
```yml 
- name: Eternal Summer Sale
      url: https://eternalsummersale.com
      img: 
      twitter: EternalSale
      email_address: admin@eternalsummersale.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Eternal Summer Sale](https://eternalsummersale.com/wp-content/uploads/2017/11/logo.png)
[Link to Eternal Summer Sale](https://eternalsummersale.com)
If needed, try the twitter handles profile image: [twitter.com/EternalSale](https://twitter.com/EternalSale)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/eternalsummersale.com](https://www.alexa.com/siteinfo/eternalsummersale.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/eternalsummersale.com](https://www.scamadviser.com/check-website/eternalsummersale.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/eternalsummersale.com](https://www.trustpilot.com/review/eternalsummersale.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
