### ISSUE TITLE
Add 'Modoboa' to the 'Developer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1323]
Requesting to add 'Modoboa' to the 'Developer' category. 

Details follow: 
```yml 
- name: Modoboa
      url: https://modoboa.org/en/
      img: 
      twitter: modoboa_mail
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://modoboa.org/en/weblog/2018/01/05/bitcoin-cash-donations/
```

Resources for adding this merchant:
Logo Provided:
![Modoboa](https://avatars3.githubusercontent.com/u/10832897?s=400&v=4)
[Link to Modoboa](https://modoboa.org/en/)
If needed, try the twitter handles profile image: [twitter.com/modoboa_mail](https://twitter.com/modoboa_mail)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/modoboa.org/en/](https://www.alexa.com/siteinfo/modoboa.org/en/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/modoboa.org/en/](https://www.scamadviser.com/check-website/modoboa.org/en/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/modoboa.org/en/](https://www.trustpilot.com/review/modoboa.org/en/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
