### ISSUE TITLE
Add 'Bitsler' to the 'Casino' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1324]
Requesting to add 'Bitsler' to the 'Casino' category. 

Details follow: 
```yml 
- name: Bitsler
      url: https://bitsler.com
      img: 
      twitter: BitSler
      facebook: BitSler
      email_address: support@bitsler.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://blog.bitsler.com/post/changelog-update-1-8-1-30-11
```

Resources for adding this merchant:
Logo Provided:
![Bitsler](https://b.bitcdn.host/gallery/f8cb688b9413cc6c.png)
[Link to Bitsler](https://bitsler.com)
If needed, try the twitter handles profile image: [twitter.com/BitSler](https://twitter.com/BitSler)
If needed, try the facebook handles profile image: [fb.com/BitSler](https://fb.com/BitSler)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bitsler.com](https://www.alexa.com/siteinfo/bitsler.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bitsler.com](https://www.scamadviser.com/check-website/bitsler.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bitsler.com](https://www.trustpilot.com/review/bitsler.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @IsildurX
Request made by Twitter user [TheRealSkyeAP](https://twitter.com/TheRealSkyeAP/), be sure to send out a tweet when this request has been added.
