### ISSUE TITLE
Add 'The Crypto Lawyers, LLP' to the 'Legal Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1325]
Requesting to add 'The Crypto Lawyers, LLP' to the 'Legal Services' category. 

Details follow: 
```yml 
- name: The Crypto Lawyers, LLP
      url: https://thecryptolawyers.com
      img: 
      twitter: CryptoLawyerLLP
      email_address: info@thecryptolawyers.com
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![The Crypto Lawyers, LLP](https://pbs.twimg.com/profile_images/1029598250297380864/TbQyx_g7_400x400.jpg)
[Link to The Crypto Lawyers, LLP](https://thecryptolawyers.com)
If needed, try the twitter handles profile image: [twitter.com/CryptoLawyerLLP](https://twitter.com/CryptoLawyerLLP)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/thecryptolawyers.com](https://www.alexa.com/siteinfo/thecryptolawyers.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/thecryptolawyers.com](https://www.scamadviser.com/check-website/thecryptolawyers.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/thecryptolawyers.com](https://www.trustpilot.com/review/thecryptolawyers.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
