### ISSUE TITLE
Add 'Mohd alif ' to the 'Merchant' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1327]
Requesting to add 'Mohd alif ' to the 'Merchant' category. 

Details follow: 
```yml 
- name: Mohd alif 
      url: https://koy69.com
      img: 
      email_address: punkofguns@gmail.com
      country: MY
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Mohd alif ](https://koy69.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/koy69.com](https://www.alexa.com/siteinfo/koy69.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/koy69.com](https://www.scamadviser.com/check-website/koy69.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/koy69.com](https://www.trustpilot.com/review/koy69.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @Mohdalif77
Request made by Twitter user [No](https://twitter.com/No/), be sure to send out a tweet when this request has been added.
