### ISSUE TITLE
Add 'electrocatstore.com' to the 'Retail' category

### ISSUE THREAD

**Issue by Nisc3d** [acceptbitcoincash/acceptbitcoincash#1331]
---------------
Requesting to add electrocatstore.com to the Retail category. Details follow:

```yml

- name: electrocatstore.com
  url: https://www.electrocatstore.com/
  img: https://cdn.shopify.com/s/files/1/0045/1064/6339/files/customlogo_360x.png?v=1537808759
  twitter: ElectroCatStore
  facebook: ElectroCat
  region: eu
  country: EE
  bch: yes
  btc: yes
  othercrypto: yes
```
