### ISSUE TITLE
Add 'Jafer Basit' to the 'yes' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1334]
Requesting to add 'Jafer Basit' to the 'yes' category. 

Details follow: 
```yml 
- name: Jafer Basit
      url: http://www.youtube.com/c/AMBONEWS
      img: 
      twitter: ambonews
      facebook: jaferbasit
      email_address: Oromiaharme79@gmail.com
      region: af
      country: KE
      city: Nairobi
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Jafer Basit](http://www.youtube.com/c/AMBONEWS)
[Link to Jafer Basit](http://www.youtube.com/c/AMBONEWS)
If needed, try the twitter handles profile image: [twitter.com/ambonews](https://twitter.com/ambonews)
If needed, try the facebook handles profile image: [fb.com/jaferbasit](https://fb.com/jaferbasit)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.youtube.com/c/AMBONEWS](https://www.alexa.com/siteinfo/www.youtube.com/c/AMBONEWS)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.youtube.com/c/AMBONEWS](https://www.scamadviser.com/check-website/www.youtube.com/c/AMBONEWS)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.youtube.com/c/AMBONEWS](https://www.trustpilot.com/review/www.youtube.com/c/AMBONEWS)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @jaferbasit
Request made by Twitter user [ambonews](https://twitter.com/ambonews/), be sure to send out a tweet when this request has been added.
