### ISSUE TITLE
Add 'Bit2Bill' to the 'Cryptoservices' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1337]
Requesting to add 'Bit2Bill' to the 'Cryptoservices' category. 

Details follow: 
```yml 
- name: Bit2Bill
      url: https://www.bit2bill.com.au
      img: 
      twitter: bit2bill
      facebook: bit2bill
      email_address: support@bit2bill.com.au
      region: oc
      country: AU
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: http://blog.bit2bill.com.au/release/adding-new-cryptocurrency-bitcoin-cash/
```

Resources for adding this merchant:
Logo Provided:
![Bit2Bill](https://www.bit2bill.com.au/images/bit2bill-icon-100.png)
[Link to Bit2Bill](https://www.bit2bill.com.au)
If needed, try the twitter handles profile image: [twitter.com/bit2bill](https://twitter.com/bit2bill)
If needed, try the facebook handles profile image: [fb.com/bit2bill](https://fb.com/bit2bill)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.bit2bill.com.au](https://www.alexa.com/siteinfo/www.bit2bill.com.au)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.bit2bill.com.au](https://www.scamadviser.com/check-website/www.bit2bill.com.au)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.bit2bill.com.au](https://www.trustpilot.com/review/www.bit2bill.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
