### ISSUE TITLE
Add 'Paybis' to the 'exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1338]
Requesting to add 'Paybis' to the 'exchange' category. 

Details follow: 
```yml 
- name: Paybis
      url: https://paybis.com/
      img: 
      twitter: paybis_com
      facebook: paybis
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Paybis](https://pbs.twimg.com/profile_images/758657861727780864/FDsIBfo-_400x400.jpg)
[Link to Paybis](https://paybis.com/)
If needed, try the twitter handles profile image: [twitter.com/paybis_com](https://twitter.com/paybis_com)
If needed, try the facebook handles profile image: [fb.com/paybis](https://fb.com/paybis)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/paybis.com/](https://www.alexa.com/siteinfo/paybis.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/paybis.com/](https://www.scamadviser.com/check-website/paybis.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/paybis.com/](https://www.trustpilot.com/review/paybis.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
