### ISSUE TITLE
Add 'Liquido24' to the 'retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1339]
Requesting to add 'Liquido24' to the 'retailer' category. 

Details follow: 
```yml 
- name: Liquido24
      url: https://www.liquido24.de
      img: 
      facebook: liquido24
      country: DE
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.liquido24.de/zahlungsarten
      exceptions: 
        text: "over BitPay"
```

Resources for adding this merchant:
Logo Provided:
![Liquido24](https://scontent-frt3-1.xx.fbcdn.net/v/t1.0-1/12998458_848989478562366_1575162654295466991_n.png?_nc_cat=105&_nc_ht=scontent-frt3-1.xx&oh=772df1a4b956d53a1cffbcf822a24cde&oe=5C8A6436)
[Link to Liquido24](https://www.liquido24.de)
If needed, try the facebook handles profile image: [fb.com/liquido24](https://fb.com/liquido24)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.liquido24.de](https://www.alexa.com/siteinfo/www.liquido24.de)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.liquido24.de](https://www.scamadviser.com/check-website/www.liquido24.de)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.liquido24.de](https://www.trustpilot.com/review/www.liquido24.de)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
