### ISSUE TITLE
Add 'Die Kondomotheke' to the 'retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1340]
Requesting to add 'Die Kondomotheke' to the 'retailer' category. 

Details follow: 
```yml 
- name: Die Kondomotheke
      url: https://www.kondomotheke.de
      img: 
      twitter: kondomotheke
      facebook: kondomotheke
      country: DE
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.kondomotheke.de/shipping.php?osCsid=b43rm0a4880lm7i2bjaglsdva7
```

Resources for adding this merchant:
Logo Provided:
![Die Kondomotheke](https://pbs.twimg.com/profile_images/873261177689837568/j-waPBxN_400x400.jpg)
[Link to Die Kondomotheke](https://www.kondomotheke.de)
If needed, try the twitter handles profile image: [twitter.com/kondomotheke](https://twitter.com/kondomotheke)
If needed, try the facebook handles profile image: [fb.com/kondomotheke](https://fb.com/kondomotheke)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.kondomotheke.de](https://www.alexa.com/siteinfo/www.kondomotheke.de)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.kondomotheke.de](https://www.scamadviser.com/check-website/www.kondomotheke.de)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.kondomotheke.de](https://www.trustpilot.com/review/www.kondomotheke.de)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
