### ISSUE TITLE
Add 'Coffee4crypto' to the 'food/drinks' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1348]
Requesting to add 'Coffee4crypto' to the 'food/drinks' category. 

Details follow: 
```yml 
- name: Coffee4crypto
      url: https://www.crypto4coffee.com
      img: 
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Coffee4crypto](https://www.crypto4coffee.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.crypto4coffee.com](https://www.alexa.com/siteinfo/www.crypto4coffee.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.crypto4coffee.com](https://www.scamadviser.com/check-website/www.crypto4coffee.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.crypto4coffee.com](https://www.trustpilot.com/review/www.crypto4coffee.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
