### ISSUE TITLE
Add 'Shark Snot' to the 'freediving' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1350]
Requesting to add 'Shark Snot' to the 'freediving' category. 

Details follow: 
```yml 
- name: Shark Snot
      url: https://www.sharksnot.com/
      img: 
      twitter: sharksnot
      facebook: sharksnot
      email_address: info@sharksnot.com
      region: na
      country: US
      bch: Yes
      btc: No
      othercrypto: No
      exceptions: 
        text: "Use Coinbase Commerce at checkout"
```

Resources for adding this merchant:
Logo Provided:
![Shark Snot](https://cdn.shopify.com/s/files/1/0881/6238/files/White_square_blue_circle_with_logo_120x.png?v=1540862719)
[Link to Shark Snot](https://www.sharksnot.com/)
If needed, try the twitter handles profile image: [twitter.com/sharksnot](https://twitter.com/sharksnot)
If needed, try the facebook handles profile image: [fb.com/sharksnot](https://fb.com/sharksnot)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.sharksnot.com/](https://www.alexa.com/siteinfo/www.sharksnot.com/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.sharksnot.com/](https://www.scamadviser.com/check-website/www.sharksnot.com/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.sharksnot.com/](https://www.trustpilot.com/review/www.sharksnot.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
