### ISSUE TITLE
Add '7BitCasino' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1351]
Requesting to add '7BitCasino' to the 'Gambling' category. 

Details follow: 
```yml 
- name: 7BitCasino
      url: https://7bitcasino.com
      img: 
      email_address: anthony@7bitpartners.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to 7BitCasino](https://7bitcasino.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/7bitcasino.com](https://www.alexa.com/siteinfo/7bitcasino.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/7bitcasino.com](https://www.scamadviser.com/check-website/7bitcasino.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/7bitcasino.com](https://www.trustpilot.com/review/7bitcasino.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
