### ISSUE TITLE
Add "Tong Jerky" to the "Retail" Category

### ISSUE THREAD

**Issue by joshmcintyre** [acceptbitcoincash/acceptbitcoincash#1352]
Requesting to add {{**Tong Jerky**}} to the {{**Retail**}} category. Details follow:

I discussed this with the founder of Tong Jerky on Reddit. He was posting a thank you to crypto users in the btc and litecoin subs and I said we could list him if they would like!

```yml

- name: Tong Jerky
  url: https://tongjerky.com
  img: 
  twitter: tongjerky
  facebook: tongjerky
  region: NA
  country: US
  city: Los Angeles?
  bch: yes
  btc: no
  othercrypto: yes
  doc: https://www.reddit.com/r/Bitcoincash/comments/9tea84/a_thank_you_to_all_bitcoincash/?st=jo04efsm&sh=b6863994
```
