### ISSUE TITLE
Add 'DataQuest Digital Pty Ltd' to the 'web hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1365]
Requesting to add 'DataQuest Digital Pty Ltd' to the 'web hosting' category. 

Details follow: 
```yml 
- name: DataQuest Digital Pty Ltd
  url: https://dataquestdigital.com.au/
  img: DataQuestDigitalPtyLtd.png 
  twitter: dq_digital
  facebook: dqdigital
  email_address: dataquestdigital@gmail.com
  country: AU
  bch: No
  btc: No
  othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![DataQuest Digital Pty Ltd](https://dataquestdigital.com.au/wp-content/uploads/2018/05/DQ-Digital-new-logo.png)
[Link to DataQuest Digital Pty Ltd](https://dataquestdigital.com.au/)
If needed, try the twitter handles profile image: [twitter.com/dq_digital](https://twitter.com/dq_digital)
If needed, try the facebook handles profile image: [fb.com/dqdigital](https://fb.com/dqdigital)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/dataquestdigital.com.au/](https://www.alexa.com/siteinfo/dataquestdigital.com.au/)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/dataquestdigital.com.au/](https://www.scamadviser.com/check-website/dataquestdigital.com.au/)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/dataquestdigital.com.au/](https://www.trustpilot.com/review/dataquestdigital.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
