### ISSUE TITLE
Add 'BCHFORUM' to the 'Forum' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1413]
Requesting to add 'BCHFORUM' to the 'Forum' category. 

Details follow: 
```yml 
- name: BCHFORUM
  url: https://bchforum.org
  img: BCHFORUM.png 
  bch: Yes
  btc: No
  othercrypto: No
  twitter: bchforum
  email_address: info@bchforum.org
```

Resources for adding this merchant:
[Link to BCHFORUM](https://bchforum.org)
If needed, try the twitter handles profile image: [twitter.com/bchforum](https://twitter.com/bchforum)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bchforum.org](https://www.alexa.com/siteinfo/bchforum.org)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/bchforum.org](https://www.scamadviser.com/check-website/bchforum.org)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/bchforum.org](https://www.trustpilot.com/review/bchforum.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
