### ISSUE TITLE
Add 'Mike and mikea' to the 'Angles' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1433]
Requesting to add 'Mike and mikea' to the 'Angles' category. 

Details follow: 
```yml 
- name: Mike and mikea
  url: http://www.facebook.com
  img: Mikeandmikea.png 
  bch: true
  btc: true
  othercrypto: true
  facebook: mikeazucena
  email_address: mikeaZucena4@gmail.com
  region: na
  country: CA
  city: Ontario
  doc: All the way
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://bandlab.com)
[Link to Mike and mikea](http://www.facebook.com)
If needed, try the facebook handles profile image: [fb.com/mikeazucena](https://fb.com/mikeazucena)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.facebook.com](https://www.alexa.com/siteinfo/www.facebook.com)
Maybe you might want to check Scam Adviser: [https://www.scamadviser.com/check-website/www.facebook.com](https://www.scamadviser.com/check-website/www.facebook.com)
Maybe you might want to check Trust Pilot: [https://www.trustpilot.com/review/www.facebook.com](https://www.trustpilot.com/review/www.facebook.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @durian
Request made by Twitter user [mikes](https://twitter.com/mikes/), be sure to send out a tweet when this request has been added.
