### ISSUE TITLE
Add honest.cash

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#1472]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{Honest.cash}} to the {{Social}} category. Details follow:

```yml

- name: Honest.cash
  url: https://honest.cash/
  img: honest-cash.png
  twitter: honest_cash
  bch: yes
  bsv: no
  btc: no
  othercrypto: no
  doc: https://honest.cash/honest_cash/honestcash-wallet-update-132
  keywords:
  - blog
  - micropayment
  - tipping
```
