### ISSUE TITLE
Add 'Myratos.com' to the 'Online Store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1479]
Requesting to add 'Myratos.com' to the 'Online Store' category. 

Details follow: 
```yml 
- name: Myratos.com
  url: https://myratos.com
  img: Myratoscom.png
  bch: true
  btc: false
  othercrypto: false
  twitter: myratos3
  email_address: info@myratos.com
  doc: https://twitter.com/Myratos3/status/1080163516617768961
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://myratos.com/wp-content/uploads/2018/12/cropped-Myratos-Logo-New-32x32.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1067851355392495618/0Q9FSsKO_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/n/a/picture)
[Link to Myratos.com](https://myratos.com)
Check their Twitter Page: [twitter.com/myratos3](https://twitter.com/myratos3)
Check their Facebook Page: [fb.com/n/a](https://fb.com/n/a)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/myratos.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/myratos.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/myratos.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
