### ISSUE TITLE
Add 'John BE Martins' to the 'Book Store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1481]
Requesting to add 'John BE Martins' to the 'Book Store' category. 

Details follow: 
```yml 
- name: John BE Martins
  url: https://johnbemartins.com
  img: JohnBEMartins.png
  bch: true
  btc: true
  othercrypto: false
  twitter: jbemartins
  facebook: johnmartinsfanpage
  email_address: jbemartins@gmail.com
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/666936151513702401/zJ_oTy_r_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/johnmartinsfanpage/picture)
[Link to John BE Martins](https://johnbemartins.com)
Check their Twitter Page: [twitter.com/jbemartins](https://twitter.com/jbemartins)
Check their Facebook Page: [fb.com/johnmartinsfanpage](https://fb.com/johnmartinsfanpage)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/johnbemartins.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/johnbemartins.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/johnbemartins.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [jbemartins](https://twitter.com/jbemartins/), be sure to send out a tweet when this request has been added.
