### ISSUE TITLE
Add 'Honest Cash' to the 'Content Writing ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1483]
Requesting to add 'Honest Cash' to the 'Content Writing ' category. 

Details follow: 
```yml 
- name: Honest Cash
  url: https://honest.cash
  img: HonestCash.png
  bch: true
  btc: false
  othercrypto: false
  twitter: honest_cash
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://honest.cash/img/honest-long-logo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1066377153254760448/zJP5xjrY_normal.jpg)
[Link to Honest Cash](https://honest.cash)
Check their Twitter Page: [twitter.com/honest_cash](https://twitter.com/honest_cash)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/honest.cash)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/honest.cash)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/honest.cash)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
