### ISSUE TITLE
Add 'Seto IPTV' to the 'Entertainment/IPTV' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1488]
Requesting to add 'Seto IPTV' to the 'Entertainment/IPTV' category. 

Details follow: 
```yml 
- name: Seto IPTV
  url: https://setoiptv.world
  img: SetoIPTV.png
  bch: true
  btc: true
  othercrypto: true
  twitter: setoiptv
  email_address: contact@setoiptv.world
  doc: https://setoiptv.world/index.php/faq/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/999140442573688832/jsiTC50e_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/999140442573688832/jsiTC50e_normal.jpg)
[Link to Seto IPTV](https://setoiptv.world)
Check their Twitter Page: [twitter.com/setoiptv](https://twitter.com/setoiptv)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/setoiptv.world)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/setoiptv.world)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/setoiptv.world)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
