### ISSUE TITLE
Add 'Remotes And Keys' to the 'Auto Parts' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1489]
Requesting to add 'Remotes And Keys' to the 'Auto Parts' category. 

Details follow: 
```yml 
- name: Remotes And Keys
  url: https://www.remotesandkeys.com.
  img: RemotesAndKeys.png
  bch: true
  btc: true
  othercrypto: true
  twitter: remotesandkeys
  email_address: help@remotesandkeys.com
  region: na
  doc: https://www.remotesandkeys.com/articles/remotes-and-keys-now-accepts-cryptocurrencies-btc
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.autolocksmithfinder.com/upload/MG/TN/4/MGArticle-14-Photo1.jpg?ts=b16c162f-2545-4198-a237-5449a55c2225)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/470677721194852352/156eA8Rf_normal.jpeg)
[Link to Remotes And Keys](https://www.remotesandkeys.com.)
Check their Twitter Page: [twitter.com/remotesandkeys](https://twitter.com/remotesandkeys)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.remotesandkeys.com.)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.remotesandkeys.com.)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.remotesandkeys.com.)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
