### ISSUE TITLE
Add 'Horus Hosting' to the 'Web Hosting, Domains' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1499]
Requesting to add 'Horus Hosting' to the 'Web Hosting, Domains' category. 

Details follow: 
```yml 
- name: Horus Hosting
  url: https://horushosting.com
  img: HorusHosting.png
  bch: true
  btc: true
  othercrypto: true
  email_address: contact@horushosting.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://horushosting.com/assets/img/logo.png)
[Link to Horus Hosting](https://horushosting.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/horushosting.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/horushosting.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/horushosting.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
