### ISSUE TITLE
Add 'Psychology Practice Balans Training' to the 'Online psychology and therapy' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1506]
Requesting to add 'Psychology Practice Balans Training' to the 'Online psychology and therapy' category. 

Details follow: 
```yml 
- name: Psychology Practice Balans Training
  url: https://www.balanstraining.nl
  img: PsychologyPracticeBalansTraining.png
  bch: true
  btc: true
  othercrypto: false
  email_address: balanstraining@gmail.com
```

Resources for adding this merchant:
[Link to Psychology Practice Balans Training](https://www.balanstraining.nl)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.balanstraining.nl)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.balanstraining.nl)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.balanstraining.nl)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
