### ISSUE TITLE
Add 'Hearts Desire' to the 'Coffee' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1514]
Requesting to add 'Hearts Desire' to the 'Coffee' category. 

Details follow: 
```yml 
- name: Hearts Desire
  url: https://www.facebook.com/hearts.desire.311/
  img: HeartsDesire.png
  bch: true
  btc: false
  othercrypto: false
  facebook: hearts.desire.311
  region: eu
  country: IE
  city: Sligo
  doc: https://www.reddit.com/r/btc/
  exceptions:
    text: "Just ask Tony"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://scontent.fdub3-1.fna.fbcdn.net/v/t1.0-9/12718138_1076846032337725_5255044223923377873_n.jpg?_nc_cat=101&_nc_ht=scontent.fdub3-1.fna&oh=1b50985235103d133b0238ea544d2403&oe=5D28A430)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/hearts.desire.311/picture)
[Link to Hearts Desire](https://www.facebook.com/hearts.desire.311/)
Check their Facebook Page: [fb.com/hearts.desire.311](https://fb.com/hearts.desire.311)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.facebook.com/hearts.desire.311/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.facebook.com/hearts.desire.311/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.facebook.com/hearts.desire.311/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
