### ISSUE TITLE
Add 'brother printer' to the 'printer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1517]
Requesting to add 'brother printer' to the 'printer' category. 

Details follow: 
```yml 
- name: brother printer
  url: https://www.brother-printer-support-numbers.com/driver/
  img: brotherprinter.png
  bch: true
  btc: true
  othercrypto: true
  email_address: samikshagirdhar.azureink@gmail.com
  region: na
  country: US
  city: united states
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.brother-printer-support-numbers.com/wp-content/uploads/2018/05/brother-printer-support-1.jpg)
[Link to brother printer](https://www.brother-printer-support-numbers.com/driver/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.brother-printer-support-numbers.com/driver/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.brother-printer-support-numbers.com/driver/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.brother-printer-support-numbers.com/driver/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
