### ISSUE TITLE
Add 'Lingo.cash' to the 'Translation Service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1523]
Requesting to add 'Lingo.cash' to the 'Translation Service' category. 

Details follow: 
```yml 
- name: Lingo.cash
  url: https://lingo.cash
  img: Lingocash.png
  bch: true
  btc: false
  othercrypto: false
  twitter: lingo_cash_t9n
  email_address: translations@lingo.cash
  doc: https://www.lingo.cash/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1095779533595262976/wiDqrFPX_400x400.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1095779533595262976/wiDqrFPX_normal.png)
[Link to Lingo.cash](https://lingo.cash)
Check their Twitter Page: [twitter.com/lingo_cash_t9n](https://twitter.com/lingo_cash_t9n)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/lingo.cash)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/lingo.cash)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/lingo.cash)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [lingo_cash_t9n](https://twitter.com/lingo_cash_t9n/), be sure to send out a tweet when this request has been added.
