### ISSUE TITLE
Add 'X Crypto Market' to the 'Online Marketplace ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1537]
Requesting to add 'X Crypto Market' to the 'Online Marketplace ' category. 

Details follow: 
```yml 
- name: X Crypto Market
  url: https://xcryptomarket.com/
  img: XCryptoMarket.png
  bch: true
  btc: false
  othercrypto: true
```

Resources for adding this merchant:
[Link to X Crypto Market](https://xcryptomarket.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/xcryptomarket.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/xcryptomarket.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/xcryptomarket.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [xcryptomarket](https://twitter.com/xcryptomarket/), be sure to send out a tweet when this request has been added.
