### ISSUE TITLE
Olympian Bitcoin Store: submission to be listed

### ISSUE THREAD

**Issue by OlympianBitcoin** [acceptbitcoincash/acceptbitcoincash#1540]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Olympian Bitcoin Store**}} to the {{**Retail**}} category. Details follow:

```yml

- name: Olympian Bitcoin Store
  url: https://olympianbitcoin.store/
  img: https://i.imgur.com/oRKKxOW.png
  twitter: OlympianBitcoin
  facebook: facebook_username
  region: eu
  country: GR
  city: LITOCHORO
  bch: yes
  bsv: yes
  btc: yes
  othercrypto: yes
  doc: https://olympianbitcoin.store/pages/faq
  keywords:
  - crypto merch
  - tshirts
  - t shirts
  - bitcoin hats
  - bitcoin t shirts
  - handcrafted
  - crypto art
  - crypto mugs
  - crypto hats 
```

With our online Bitcoin store it is possible to buy truly unique and crazy crypto merch, including t-shirts, hats, mugs, pillows and handcrafted art. Buy with Zeus and enjoy all things crypto!

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
