### ISSUE TITLE
Add 'Taskopus' to the 'Don't know' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1547]
Requesting to add 'Taskopus' to the 'Don't know' category. 

Details follow: 
```yml 
- name: Taskopus
  url: https://taskopus.io/
  img: Taskopus.png
  bch: true
  btc: false
  othercrypto: false
  email_address: simon@taskopus.io
```

Resources for adding this merchant:
[Link to Taskopus](https://taskopus.io/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/taskopus.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/taskopus.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/taskopus.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
