### ISSUE TITLE
Add 'hhttps://ripple-xrp-global-network.mn.co/' to the 'Consultant' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1549]
Requesting to add 'hhttps://ripple-xrp-global-network.mn.co/' to the 'Consultant' category. 

Details follow: 
```yml 
- name: hhttps://ripple-xrp-global-network.mn.co/
  url: https://ripple-xrp-global-network.mn.co/
  img: hhttpsripplexrpglobalnetworkmnco.png
  bch: true
  btc: true
  othercrypto: true
  email_address: hrhcynthiamichelelara@gmail.com
```

Resources for adding this merchant:
[Link to hhttps://ripple-xrp-global-network.mn.co/](https://ripple-xrp-global-network.mn.co/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/ripple-xrp-global-network.mn.co/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/ripple-xrp-global-network.mn.co/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/ripple-xrp-global-network.mn.co/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @empresaria
Request made by Twitter user [hrhlara](https://twitter.com/hrhlara/), be sure to send out a tweet when this request has been added.
