### ISSUE TITLE
Add 'Super-Savvy's' to the 'e-retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1551]
Requesting to add 'Super-Savvy's' to the 'e-retail' category. 

Details follow: 
```yml 
- name: Super-Savvy's
  url: https://savvys.co.uk
  img: SuperSavvys.png
  bch: true
  btc: false
  othercrypto: true
  twitter: notyet
  facebook: notyet
  email_address: info@savvys.co.uk
  region: eu
  country: GB
  city: No  As a start up new products daily new countries as soon as we can manage
  exceptions:
    text: "Via coinbase commerce"
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/24989492/________normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/notyet/picture)
[Link to Super-Savvy's](https://savvys.co.uk)
Check their Twitter Page: [twitter.com/notyet](https://twitter.com/notyet)
Check their Facebook Page: [fb.com/notyet](https://fb.com/notyet)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/savvys.co.uk)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/savvys.co.uk)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/savvys.co.uk)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
