### ISSUE TITLE
Add 'SurgeryPrevention.TODAY' to the 'Health & Beauty | Alternative Medicine too (please list on both)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1559]
Requesting to add 'SurgeryPrevention.TODAY' to the 'Health & Beauty | Alternative Medicine too (please list on both)' category. 

Details follow: 
```yml 
- name: SurgeryPrevention.TODAY
  url: http://SurgeryPrevention.TODAY
  img: SurgeryPreventionTODAY.png
  bch: true
  btc: true
  othercrypto: true
  email_address: BOOKINGS@SurgeryPrevention.TODAY
  country: US
  city: San Diego, California and Ensenada, Baja California Mexico
  exceptions:
    text: "No, just send to the BCH address"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://scontent-lax3-1.cdninstagram.com/vp/e204bddf8d5073a38988becc36697479/5D2C7BD5/t51.2885-19/s150x150/53547702_2541387199247629_6635128605737222144_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com)
[Link to SurgeryPrevention.TODAY](http://SurgeryPrevention.TODAY)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/SurgeryPrevention.TODAY)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/SurgeryPrevention.TODAY)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/SurgeryPrevention.TODAY)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
