### ISSUE TITLE
Add 'FastPainRelief.TV' to the 'Health + Alternative Medicine (please list in both)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1560]
Requesting to add 'FastPainRelief.TV' to the 'Health + Alternative Medicine (please list in both)' category. 

Details follow: 
```yml 
- name: FastPainRelief.TV
  url: http://FastPainRelief.TV
  img: FastPainReliefTV.png
  bch: true
  btc: true
  othercrypto: true
  email_address: BOOKINGS@FastPainRelief.LIVE
  country: US
  city: San Diego California and Ensenada, Baja California Mexico
  exceptions:
    text: "Just use the proper BCH address"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fmullerchiropractic.com%2Fwp-content%2Fuploads%2F2014%2F07%2FBack-Pain-01.png&f=1)
[Link to FastPainRelief.TV](http://FastPainRelief.TV)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/FastPainRelief.TV)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/FastPainRelief.TV)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/FastPainRelief.TV)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
