### ISSUE TITLE
Add 'FastPainRelief.LIVE' to the 'Health + Alternative Medicine (please list in both)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1561]
Requesting to add 'FastPainRelief.LIVE' to the 'Health + Alternative Medicine (please list in both)' category. 

Details follow: 
```yml 
- name: FastPainRelief.LIVE
  url: http://FastPainRelief.LIVE
  img: FastPainReliefLIVE.png
  bch: true
  btc: true
  othercrypto: true
  email_address: BOOKINGS@FastPainRelief.LIVE
  country: US
  city: San Diego California, and Tijuana/Ensenada Baja California Mexico
  exceptions:
    text: "Just send to the proper BCH address"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fkeywestorthopedics.com%2Fwp-content%2Fuploads%2F2014%2F11%2Fpain1.jpg&f=1)
[Link to FastPainRelief.LIVE](http://FastPainRelief.LIVE)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/FastPainRelief.LIVE)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/FastPainRelief.LIVE)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/FastPainRelief.LIVE)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
