### ISSUE TITLE
Add 'BetterHealthAnswers.com' to the 'Health + Alternative Medicine (please list in both)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1562]
Requesting to add 'BetterHealthAnswers.com' to the 'Health + Alternative Medicine (please list in both)' category. 

Details follow: 
```yml 
- name: BetterHealthAnswers.com
  url: http://BetterHealthAnswers.com
  img: BetterHealthAnswerscom.png
  bch: true
  btc: true
  othercrypto: true
  email_address: BOOKINGS@BetterHealthAnswers.com
  country: MX
  city: Tijuana and Ensenada and San Diego
  exceptions:
    text: "Use the proper BCH address"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Facupuncturemississaugaclinic.com%2Fwp-content%2Fuploads%2F2014%2F11%2FPain-Relief.jpg&f=1)
[Link to BetterHealthAnswers.com](http://BetterHealthAnswers.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/BetterHealthAnswers.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/BetterHealthAnswers.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/BetterHealthAnswers.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
