### ISSUE TITLE
Add 'Steve Lagace' to the 'Consultant' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1585]
Requesting to add 'Steve Lagace' to the 'Consultant' category. 

Details follow: 
```yml 
- name: Steve Lagace
  url: https://stevelagace.simdif.com/
  img: SteveLagace.png
  bch: true
  btc: true
  othercrypto: true
  email_address: stevelagace@icloud.com
  region: na
  country: CA
```

Resources for adding this merchant:
[Link to Steve Lagace](https://stevelagace.simdif.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/stevelagace.simdif.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/stevelagace.simdif.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/stevelagace.simdif.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
