### ISSUE TITLE
Add 'RABANO SUNGLASSES' to the 'SHOP ONLINE' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1586]
Requesting to add 'RABANO SUNGLASSES' to the 'SHOP ONLINE' category. 

Details follow: 
```yml 
- name: RABANO SUNGLASSES
  url: https://rabano.online/
  img: RABANOSUNGLASSES.png
  bch: true
  btc: true
  othercrypto: true
  email_address: hola@rabano.online
  region: eu
  country: ES
  city: Barcelona
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0027/9835/4478/files/rabano-logo_f10127c3-db49-4bab-919c-7fa6a7a800c5_540x.png?v=1554915514)
[Link to RABANO SUNGLASSES](https://rabano.online/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/rabano.online/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/rabano.online/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/rabano.online/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
