### ISSUE TITLE
Add 'Ascential Marketing' to the 'Web Design, SEO & Programming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1590]
Requesting to add 'Ascential Marketing' to the 'Web Design, SEO & Programming' category. 

Details follow: 
```yml 
- name: Ascential Marketing
  url: https://www.ascentialdigitalmarketing.com
  img: AscentialMarketing.png
  bch: true
  btc: true
  othercrypto: true
  email_address: sales@ascentialmarketing.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.ascentialdigitalmarketing.com/wp-content/themes/ascential/dist/images/ascential-digital-logo-header-r1.png)
[Link to Ascential Marketing](https://www.ascentialdigitalmarketing.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ascentialdigitalmarketing.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ascentialdigitalmarketing.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ascentialdigitalmarketing.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
