### ISSUE TITLE
Add 'Sherilyn Shop' to the 'Bags and Shoes' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1592]
Requesting to add 'Sherilyn Shop' to the 'Bags and Shoes' category. 

Details follow: 
```yml 
- name: Sherilyn Shop
  url: https://SherilynShop.com
  img: SherilynShop.png
  bch: true
  btc: true
  othercrypto: true
  facebook: sherilynshop
  email_address: sherilynshopofficial@gmail.com
  country: US
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/sherilynshop/picture)
[Link to Sherilyn Shop](https://SherilynShop.com)
Check their Facebook Page: [fb.com/sherilynshop](https://fb.com/sherilynshop)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/SherilynShop.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/SherilynShop.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/SherilynShop.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
