### ISSUE TITLE
Add 'Sherilyn Shop' to the 'Shoes and Bags ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1593]
Requesting to add 'Sherilyn Shop' to the 'Shoes and Bags ' category. 

Details follow: 
```yml 
- name: Sherilyn Shop
  url: https://Sherilynshop.com/
  img: SherilynShop.png
  bch: true
  btc: true
  othercrypto: true
  twitter: sherilynshop
  facebook: sherilynshop
  email_address: Sherilynshopofficial@yahoo.com
  doc: https://sherilynshop.com/
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1120989892270387201/6Ze-LnXv_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/sherilynshop/picture)
[Link to Sherilyn Shop](https://Sherilynshop.com/)
Check their Twitter Page: [twitter.com/sherilynshop](https://twitter.com/sherilynshop)
Check their Facebook Page: [fb.com/sherilynshop](https://fb.com/sherilynshop)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/Sherilynshop.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/Sherilynshop.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/Sherilynshop.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [sherilynshop](https://twitter.com/sherilynshop/), be sure to send out a tweet when this request has been added.
