### ISSUE TITLE
Add 'VituVipi' to the 'E-commerce, Retail and Wholesale ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1598]
Requesting to add 'VituVipi' to the 'E-commerce, Retail and Wholesale ' category. 

Details follow: 
```yml 
- name: VituVipi
  url: https://vituvipi.online
  img: VituVipi.png
  bch: true
  btc: false
  othercrypto: true
  email_address: vituvipi@vituvipi.online
  country: CD
  city: Kinshasa 
  exceptions:
    text: "Method of payment during checkout"
```

Resources for adding this merchant:
[Link to VituVipi](https://vituvipi.online)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/vituvipi.online)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/vituvipi.online)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/vituvipi.online)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @patnew
