### ISSUE TITLE
Add 'SengiCoin' to the 'CryptoCurrency Trading Platform ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1599]
Requesting to add 'SengiCoin' to the 'CryptoCurrency Trading Platform ' category. 

Details follow: 
```yml 
- name: SengiCoin
  url: https://sengicoin.com
  img: SengiCoin.png
  bch: true
  btc: false
  othercrypto: true
  email_address: support@sengicoin.com
  country: CD
  city: Kinshasa 
```

Resources for adding this merchant:
[Link to SengiCoin](https://sengicoin.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/sengicoin.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/sengicoin.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/sengicoin.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @patnew
