### ISSUE TITLE
Add 'Homecashbitcoin.com' to the 'Money coins' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1606]
Requesting to add 'Homecashbitcoin.com' to the 'Money coins' category. 

Details follow: 
```yml 
- name: Homecashbitcoin.com
  url: https://www.homebitcoin.com/app
  img: Homecashbitcoincom.png
  bch: true
  btc: true
  othercrypto: true
  email_address: alansalgado090@gmail.com
  country: US
  city: silver spring
```

Resources for adding this merchant:
[Link to Homecashbitcoin.com](https://www.homebitcoin.com/app)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.homebitcoin.com/app)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.homebitcoin.com/app)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.homebitcoin.com/app)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @nomine
