### ISSUE TITLE
Add Atomic Wallet to the Wallets Category

### ISSUE THREAD

**Issue by centralizedtransformer** [acceptbitcoincash/acceptbitcoincash#1611]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{Atomic Wallet}} to the {{wallets}} category. Details follow:

```yml

- name: Atomic Wallet
  url: https://atomicwallet.io
  img: https://atomicwallet.io/css/images/AtomicWalletIcon.svg
  twitter: atomicwallet
  facebook: https://www.facebook.com/atomicwallet
  region: eu
  country: ISO 3166-2:EE
  city: Tallinn
  bch: yes
  bsv: yes
  btc: yes
  othercrypto: yes
  doc: https://atomicwallet.io/bitcoin-cash-wallet
  keywords:
  - Bitcoin Cash Wallet
  - Atomic Wallet
```
