### ISSUE TITLE
Add 'Liam Gaughan [Production / Performance / Tuition]' to the 'Music /Arts' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1615]
Requesting to add 'Liam Gaughan [Production / Performance / Tuition]' to the 'Music /Arts' category. 

Details follow: 
```yml 
- name: Liam Gaughan [Production / Performance / Tuition]
  url: https://www.liamgaughan.com
  img: LiamGaughanProductionPerformanceTuition.png
  bch: true
  btc: true
  othercrypto: true
  twitter: liamgaughan
  facebook: liamgaughanppt
  email_address: liamgaughan@gmail.com
  doc: http://www.liamgaughan.com - it's on the header!
  exceptions:
    text: "Any invoice can be cleared via BCH for a 10% discount."
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/590872558888685568/Ov6v4E9F_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/liamgaughanppt/picture)
[Link to Liam Gaughan [Production / Performance / Tuition]](https://www.liamgaughan.com)
Check their Twitter Page: [twitter.com/liamgaughan](https://twitter.com/liamgaughan)
Check their Facebook Page: [fb.com/liamgaughanppt](https://fb.com/liamgaughanppt)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.liamgaughan.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.liamgaughan.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.liamgaughan.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [liamgaughan](https://twitter.com/liamgaughan/), be sure to send out a tweet when this request has been added.
