### ISSUE TITLE
Add 'KiteSurfSUP' to the 'Sports Equipment ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1616]
Requesting to add 'KiteSurfSUP' to the 'Sports Equipment ' category. 

Details follow: 
```yml 
- name: KiteSurfSUP
  url: https://kitesurfsupuae.myshopify.com
  img: KiteSurfSUP.png
  bch: true
  btc: true
  othercrypto: true
  facebook: naishofuae
  email_address: leigh@kitesurfsup.com
  doc: https://kitesurfsupuae.myshopify.com/blogs/news
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/naishofuae/picture)
[Link to KiteSurfSUP](https://kitesurfsupuae.myshopify.com)
Check their Facebook Page: [fb.com/naishofuae](https://fb.com/naishofuae)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/kitesurfsupuae.myshopify.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/kitesurfsupuae.myshopify.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/kitesurfsupuae.myshopify.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
