### ISSUE TITLE
Add 'ExpressVPN' to the 'https://acceptbitcoin.cash/#security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1619]
Requesting to add 'ExpressVPN' to the 'https://acceptbitcoin.cash/#security' category. 

Details follow: 
```yml 
- name: ExpressVPN
  url: https://www.expressvpn.com
  img: ExpressVPN.png
  bch: true
  btc: true
  othercrypto: false
  twitter: expressvpn
  facebook: expressvpn
  exceptions:
    text: "Bitpay Bip70 - Additional contact info - live chat on site"
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1007177892512423938/sg81HlfT_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/expressvpn/picture)
[Link to ExpressVPN](https://www.expressvpn.com)
Check their Twitter Page: [twitter.com/expressvpn](https://twitter.com/expressvpn)
Check their Facebook Page: [fb.com/expressvpn](https://fb.com/expressvpn)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.expressvpn.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.expressvpn.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.expressvpn.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
