### ISSUE TITLE
Add 'Coinprepr®' to the 'Blog/Newsletter' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1624]
Requesting to add 'Coinprepr®' to the 'Blog/Newsletter' category. 

Details follow: 
```yml 
- name: Coinprepr®
  url: https://www.coinprepr.com
  img: Coinprepr.png
  bch: true
  btc: true
  othercrypto: true
  twitter: coinprepr
  facebook: coinprepr
  email_address: coinprepr@gmail.com
  country: US
  doc: https://coinprepr.com/about-us/
  exceptions:
    text: "No, just scan QR code with camera."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1135771672643100673/Ii-QVC0A_400x400.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1135771672643100673/Ii-QVC0A_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/coinprepr/picture)
[Link to Coinprepr®](https://www.coinprepr.com)
Check their Twitter Page: [twitter.com/coinprepr](https://twitter.com/coinprepr)
Check their Facebook Page: [fb.com/coinprepr](https://fb.com/coinprepr)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.coinprepr.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.coinprepr.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.coinprepr.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
