### ISSUE TITLE
Add 'Satoshi Master S.A.S' to the 'ATM' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1628]
Requesting to add 'Satoshi Master S.A.S' to the 'ATM' category. 

Details follow: 
```yml 
- name: Satoshi Master S.A.S
  url: https://www.satoshimaster.io
  img: SatoshiMasterSAS.png
  bch: true
  btc: false
  othercrypto: true
  twitter: satoshimasterco
  facebook: satoshimasterco
  email_address: media@satoshimaster.io
  region: sa
  country: CO
  city: Bogota
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://satoshimaster.io/wp-content/uploads/2019/03/logo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1138466281961730048/aInUWrcv_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/satoshimasterco/picture)
[Link to Satoshi Master S.A.S](https://www.satoshimaster.io)
Check their Twitter Page: [twitter.com/satoshimasterco](https://twitter.com/satoshimasterco)
Check their Facebook Page: [fb.com/satoshimasterco](https://fb.com/satoshimasterco)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.satoshimaster.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.satoshimaster.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.satoshimaster.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
