### ISSUE TITLE
Add 'Rejuvenation Clinics of Australia' to the 'Skin Care Clinic' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1631]
Requesting to add 'Rejuvenation Clinics of Australia' to the 'Skin Care Clinic' category. 

Details follow: 
```yml 
- name: Rejuvenation Clinics of Australia
  url: https://www.rejuvaustralia.com.au/
  img: RejuvenationClinicsofAustralia.png
  bch: false
  btc: true
  othercrypto: false
  twitter: rejuvaustralia
  facebook: rejuvaustralia
  email_address: info@rejuvaustralia.com.au
  region: oc
  country: AU
  city: Sydney
  doc: https://www.rejuvaustralia.com.au/pricing-payment/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/694317965185937408/yUA6Yt1i_400x400.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/694317965185937408/yUA6Yt1i_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/rejuvaustralia/picture)
[Link to Rejuvenation Clinics of Australia](https://www.rejuvaustralia.com.au/)
Check their Twitter Page: [twitter.com/rejuvaustralia](https://twitter.com/rejuvaustralia)
Check their Facebook Page: [fb.com/rejuvaustralia](https://fb.com/rejuvaustralia)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.rejuvaustralia.com.au/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.rejuvaustralia.com.au/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.rejuvaustralia.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
