### ISSUE TITLE
Add 'Peaceful Warrior' to the 'Specialty (Jewelry, Skin care, Beauty, Consulting)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1640]
Requesting to add 'Peaceful Warrior' to the 'Specialty (Jewelry, Skin care, Beauty, Consulting)' category. 

Details follow: 
```yml 
- name: Peaceful Warrior
  url: https://peacefulwarrior.cash
  img: PeacefulWarrior.png
  bch: true
  btc: true
  othercrypto: true
  twitter: pwdotcash
  email_address: info@peacefulwarrior.com
  doc: https://peacefulwarrior.cash/payments
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1083754982166286336/zUy1PT6o_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1083754982166286336/zUy1PT6o_normal.jpg)
[Link to Peaceful Warrior](https://peacefulwarrior.cash)
Check their Twitter Page: [twitter.com/pwdotcash](https://twitter.com/pwdotcash)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/peacefulwarrior.cash)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/peacefulwarrior.cash)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/peacefulwarrior.cash)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
