### ISSUE TITLE
Add 'Mind Research & Development' to the 'Health, Pharma, Cannabis, Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1665]
Requesting to add 'Mind Research & Development' to the 'Health, Pharma, Cannabis, Food' category. 

Details follow: 
```yml 
- name: Mind Research & Development
  url: https://www.mindrnd.com
  img: MindResearchDevelopment.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.mindrnd.com/logo.png)
[Link to Mind Research & Development](https://www.mindrnd.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.mindrnd.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.mindrnd.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.mindrnd.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
