### ISSUE TITLE
Add 'FSBO Crypto' to the 'Real Estate' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1666]
Requesting to add 'FSBO Crypto' to the 'Real Estate' category. 

Details follow: 
```yml 
- name: FSBO Crypto
  url: https://www.fsbocrypto.com
  img: FSBOCrypto.png
  bch: true
  btc: true
  othercrypto: true
  region: na
  country: US
```

Resources for adding this merchant:
[Link to FSBO Crypto](https://www.fsbocrypto.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.fsbocrypto.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.fsbocrypto.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.fsbocrypto.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
