### ISSUE TITLE
Add 'Vini.az' to the 'Auto services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1672]
Requesting to add 'Vini.az' to the 'Auto services' category. 

Details follow: 
```yml 
- name: Vini.az
  url: https://vini.az/en
  img: Viniaz.png
  bch: true
  btc: true
  othercrypto: true
  twitter: viniazerbaijan
  facebook: viniazerbaijan
  email_address: support@vini.az
  exceptions:
    text: "No, everything is automatic and online"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://vini.az/site/img/logo-en.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1073477280859447296/vrXELz9U_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/viniazerbaijan/picture)
[Link to Vini.az](https://vini.az/en)
Check their Twitter Page: [twitter.com/viniazerbaijan](https://twitter.com/viniazerbaijan)
Check their Facebook Page: [fb.com/viniazerbaijan](https://fb.com/viniazerbaijan)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/vini.az/en)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/vini.az/en)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/vini.az/en)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
