### ISSUE TITLE
Add 'Subway Hockenheim' to the 'Food, Fast-Food, Vegan, Vegetarian, Family-Friendly' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1673]
Requesting to add 'Subway Hockenheim' to the 'Food, Fast-Food, Vegan, Vegetarian, Family-Friendly' category. 

Details follow: 
```yml 
- name: Subway Hockenheim
  url: https://www.kaufda.de/Filialen/Hockenheim/Subway-Gleisstrasse/v-f113732940
  img: SubwayHockenheim.png
  bch: true
  btc: false
  othercrypto: false
  email_address: rismansanj@yahoo.de
  region: eu
  country: DE
  city: Hockenheim
  exceptions:
    text: "Bip70 Payment preferred (Anypay/Bitpay)"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.subway.com/~/media/USA/Images/Branding/subway-logo-new.png?h=44&la=de-DE&w=222&hash=EEAF19AF51A8B0B183A30AC33A920959546D919E)
[Link to Subway Hockenheim](https://www.kaufda.de/Filialen/Hockenheim/Subway-Gleisstrasse/v-f113732940)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.kaufda.de/Filialen/Hockenheim/Subway-Gleisstrasse/v-f113732940)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.kaufda.de/Filialen/Hockenheim/Subway-Gleisstrasse/v-f113732940)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.kaufda.de/Filialen/Hockenheim/Subway-Gleisstrasse/v-f113732940)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [kaeptnkook](https://twitter.com/kaeptnkook/), be sure to send out a tweet when this request has been added.
