### ISSUE TITLE
Add 'Travala' to the 'Travel and Transport (Hotels)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1674]
Requesting to add 'Travala' to the 'Travel and Transport (Hotels)' category. 

Details follow: 
```yml 
- name: Travala
  url: https://www.travala.com/
  img: Travala.png
  bch: true
  btc: true
  othercrypto: true
  twitter: travalacom
  facebook: travala
  doc: https://twitter.com/travalacom/status/1109452903922565120
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1067317622134304768/Ka8WvUE9_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1067317622134304768/Ka8WvUE9_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/travala/picture)
[Link to Travala](https://www.travala.com/)
Check their Twitter Page: [twitter.com/travalacom](https://twitter.com/travalacom)
Check their Facebook Page: [fb.com/travala](https://fb.com/travala)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.travala.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.travala.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.travala.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
