### ISSUE TITLE
Add 'KratomMex' to the 'kratom' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1675]
Requesting to add 'KratomMex' to the 'kratom' category. 

Details follow: 
```yml 
- name: KratomMex
  url: https://kratommex.com
  img: KratomMex.png
  bch: true
  btc: true
  othercrypto: true
  twitter: kratommex
  facebook: kratommex
  email_address: kratommex@protonmail.com
  region: na
  country: MX
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1133034024035864577/68ir5Jjp_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/kratommex/picture)
[Link to KratomMex](https://kratommex.com)
Check their Twitter Page: [twitter.com/kratommex](https://twitter.com/kratommex)
Check their Facebook Page: [fb.com/kratommex](https://fb.com/kratommex)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/kratommex.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/kratommex.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/kratommex.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
