### ISSUE TITLE
Add 'Siam Society' to the 'Vacation Rentals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1678]
Requesting to add 'Siam Society' to the 'Vacation Rentals' category. 

Details follow: 
```yml 
- name: Siam Society
  url: https://siamsociety.com
  img: SiamSociety.png
  bch: true
  btc: true
  othercrypto: true
  twitter: siamsociety
  facebook: siamsocietyrealestate
  email_address: paultvanslyke@gmail.com
  region: as
  country: TH
  city: Hua Hin
  doc: https://siamsociety.com/we-accept-bitcoin-bitcoin-cash-ethereum-for-rental-payments/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://siamsociety.com//wp-content/uploads/2019/07/siamsocietyrealestate_logo.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/586331891734708226/54-J2aeG_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/siamsocietyrealestate/picture)
[Link to Siam Society](https://siamsociety.com)
Check their Twitter Page: [twitter.com/siamsociety](https://twitter.com/siamsociety)
Check their Facebook Page: [fb.com/siamsocietyrealestate](https://fb.com/siamsocietyrealestate)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/siamsociety.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/siamsociety.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/siamsociety.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [siamsociety](https://twitter.com/siamsociety/), be sure to send out a tweet when this request has been added.
