### ISSUE TITLE
Add 'Executive Homes Hua Hin' to the 'Vacation Rentals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1679]
Requesting to add 'Executive Homes Hua Hin' to the 'Vacation Rentals' category. 

Details follow: 
```yml 
- name: Executive Homes Hua Hin
  url: https://www.executive-homes-huahin.com
  img: ExecutiveHomesHuaHin.png
  bch: true
  btc: true
  othercrypto: true
  twitter: huahomes
  email_address: paultvanslyke@gmail.com
  region: as
  country: TH
  city: Hua Hin
  doc: https://www.executive-homes-huahin.com/bitcoin-bitcoin-cash-ethereum-accepted-here/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.executive-homes-huahin.com/wp-content/uploads/2019/08/Executive-Homes-Logo-copy.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1095538189513584640/dT6I6Nhu_normal.jpg)
[Link to Executive Homes Hua Hin](https://www.executive-homes-huahin.com)
Check their Twitter Page: [twitter.com/huahomes](https://twitter.com/huahomes)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.executive-homes-huahin.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.executive-homes-huahin.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.executive-homes-huahin.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [huahomes](https://twitter.com/huahomes/), be sure to send out a tweet when this request has been added.
