### ISSUE TITLE
Add 'lavikatoranto' to the 'computer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1680]
Requesting to add 'lavikatoranto' to the 'computer' category. 

Details follow: 
```yml 
- name: lavikatoranto
  url: http://www.norton-com-setup.me/
  img: lavikatoranto.png
  bch: true
  btc: true
  othercrypto: true
  region: an
  country: US
  city: new york
```

Resources for adding this merchant:
[Link to lavikatoranto](http://www.norton-com-setup.me/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.norton-com-setup.me/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.norton-com-setup.me/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.norton-com-setup.me/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
