### ISSUE TITLE
Add 'Bitcoin Gift Cards' to the 'gift cards, Australian, retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1682]
Requesting to add 'Bitcoin Gift Cards' to the 'gift cards, Australian, retail' category. 

Details follow: 
```yml 
- name: Bitcoin Gift Cards
  url: https://bch.bitcoingiftcards.com.au/
  img: BitcoinGiftCards.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cards4coins
  facebook: bitcoingiftcards
  email_address: support@bitcoingiftcards.com.au
  region: oc
  country: AU
  doc: https://www.facebook.com/bitcoingiftcards/posts/1868229166614145
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://bch.bitcoingiftcards.com.au/wp-content/uploads/2019/08/btcgc-logo-square.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/378800000477550708/cec63bc626affb285b6bdc248bc700df_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/bitcoingiftcards/picture)
[Link to Bitcoin Gift Cards](https://bch.bitcoingiftcards.com.au/)
Check their Twitter Page: [twitter.com/cards4coins](https://twitter.com/cards4coins)
Check their Facebook Page: [fb.com/bitcoingiftcards](https://fb.com/bitcoingiftcards)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bch.bitcoingiftcards.com.au/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bch.bitcoingiftcards.com.au/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bch.bitcoingiftcards.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @rmwb
