### ISSUE TITLE
Add 'Michel Fortin' to the 'Software' category

### ISSUE THREAD

**Issue by michelf** [acceptbitcoincash/acceptbitcoincash#1683]
Requesting to add **Michel Fortin** to the **Software** category. Details follow:

```yml

- name: Michel Fortin
  url: https://michelf.ca/
  img: michelf.png
  twitter: michel_fortin
  bch: yes
  bsv: no
  btc: no
  othercrypto: no
  keywords:
  - mac
  - macOS 
  - translation
  - screen
  - colors
  - xliff
```
![img](https://michelf.ca/apple-touch-icon.png)

Selling some Mac apps for tweaking on-screen colors, helping the color blind, and editing XLIFF files for translating apps.
