### ISSUE TITLE
Add 'AGRsicurezza' to the 'Business Consulting Service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1697]
Requesting to add 'AGRsicurezza' to the 'Business Consulting Service' category. 

Details follow: 
```yml 
- name: AGRsicurezza
  url: https://www.agrsicurezza.it/
  img: AGRsicurezza.png
  bch: true
  btc: true
  othercrypto: true
  twitter: agrsicurezza
  email_address: contattaci@agrsicurezza.com
  region: eu
  country: IT
  city: Ancona
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1036888280745299968/-4gwOD9r_normal.jpg)
[Link to AGRsicurezza](https://www.agrsicurezza.it/)
Check their Twitter Page: [twitter.com/agrsicurezza](https://twitter.com/agrsicurezza)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.agrsicurezza.it/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.agrsicurezza.it/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.agrsicurezza.it/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
