### ISSUE TITLE
Add 'WolfBot' to the 'Trading Software' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1699]
Requesting to add 'WolfBot' to the 'Trading Software' category. 

Details follow: 
```yml 
- name: WolfBot
  url: https://wolfbot.org/
  img: WolfBot.png
  bch: true
  btc: true
  othercrypto: true
  twitter: ekliptor
  facebook: wolftradingbot
  email_address: admin@wolfbot.org
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://wolfbot.org/wp-content/uploads/2018/05/icon_512-300x300.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1006490107698790401/FwTtLrz2_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/wolftradingbot/picture)
[Link to WolfBot](https://wolfbot.org/)
Check their Twitter Page: [twitter.com/ekliptor](https://twitter.com/ekliptor)
Check their Facebook Page: [fb.com/wolftradingbot](https://fb.com/wolftradingbot)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/wolfbot.org/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/wolfbot.org/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/wolfbot.org/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @ekliptor
