### ISSUE TITLE
Change BCH Gallery?

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#1712]
Hey @pokkst I've seen you around so I wanted to open this and mention you here to help this. I noticed the following information we have in wallets.yml is no longer a valid URL but your base URL is still showing the Project. Is there a direct link I can update this too?
```yml

- name: BCHgallery
  url: https://pokkst.xyz/info/bchgallery/
  bch: true
  btc: false
  othercrypto: false
```
