### ISSUE TITLE
Replace Bitcoin Superstore with anchor-x.io in CryptoServices

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#1713]
We need to add in AnchorX in place of Bitcoin Superstore

```yml

- name: AnchorX
  url: https://anchor-x.io
  img: anchor-x.png
  twitter: AnchorX_io
  facebook: bitcoinsuperstore
  bch: true
  btc: true
  othercrypto: true
```
