### ISSUE TITLE
Add 'Avast.ru' to the 'Frilanser' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1728]
Requesting to add 'Avast.ru' to the 'Frilanser' category. 

Details follow: 
```yml 
- name: Avast.ru
  url: http://avast.ru
  img: Avastru.png
  bch: true
  btc: false
  othercrypto: false
  facebook: pitercukermanfacebook.com
  email_address: cucoin209@yandex.ru
  region: na
  country: RU
  city: Lenigrad
  exceptions:
    text: "dgobs#43545; ✏"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://qr.ai/qyp93)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/pitercukermanfacebook.com/picture)
[Link to Avast.ru](http://avast.ru)
Check their Facebook Page: [fb.com/pitercukermanfacebook.com](https://fb.com/pitercukermanfacebook.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/avast.ru)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/avast.ru)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/avast.ru)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [ruliksvei](https://twitter.com/ruliksvei/), be sure to send out a tweet when this request has been added.
