### ISSUE TITLE
Add 'foodforests' to the 'Forestry and agriculture' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1729]
Requesting to add 'foodforests' to the 'Forestry and agriculture' category. 

Details follow: 
```yml 
- name: foodforests
  url: https://www.foodforests.eu
  img: foodforests.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to foodforests](https://www.foodforests.eu)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.foodforests.eu)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.foodforests.eu)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.foodforests.eu)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
