### ISSUE TITLE
Add 'Healthier Matters' to the 'Blog' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1730]
Requesting to add 'Healthier Matters' to the 'Blog' category. 

Details follow: 
```yml 
- name: Healthier Matters
  url: https://healthiermatters.com/
  img: HealthierMatters.png
  bch: true
  btc: false
  othercrypto: true
  twitter: healthiermatter
  facebook: healthiermatter
  email_address: bolvar4lichking@gmail.com
  region: eu
  country: GB
  city: London
  doc: https://healthiermatters.com/advertise-with-us
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://healthiermatters.com/wp-content/uploads/healthiermatters.com/Healthier-Matters-logo-2x.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1089852247813603328/OD92yzy4_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/healthiermatter/picture)
[Link to Healthier Matters](https://healthiermatters.com/)
Check their Twitter Page: [twitter.com/healthiermatter](https://twitter.com/healthiermatter)
Check their Facebook Page: [fb.com/healthiermatter](https://fb.com/healthiermatter)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/healthiermatters.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/healthiermatters.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/healthiermatters.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [healthiermatter](https://twitter.com/healthiermatter/), be sure to send out a tweet when this request has been added.
