### ISSUE TITLE
Add 'Minds Eye Hemp' to the 'CBD & Hemp Oil' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1731]
Requesting to add 'Minds Eye Hemp' to the 'CBD & Hemp Oil' category. 

Details follow: 
```yml 
- name: Minds Eye Hemp
  url: http://www.mindseyehemp.com
  img: MindsEyeHemp.png
  bch: true
  btc: true
  othercrypto: true
  facebook: minds-eye-hemp-112665780154625
  email_address: hello@mindseyehemp.com
  region: na
  country: US
  exceptions:
    text: "No - coinbase commerce"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/RWhY2Pj.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/minds-eye-hemp-112665780154625/picture)
[Link to Minds Eye Hemp](http://www.mindseyehemp.com)
Check their Facebook Page: [fb.com/minds-eye-hemp-112665780154625](https://fb.com/minds-eye-hemp-112665780154625)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.mindseyehemp.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.mindseyehemp.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.mindseyehemp.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
