### ISSUE TITLE
Add 'Craig’s iRepair, Etc.' to the 'Cellphone repair' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1732]
Requesting to add 'Craig’s iRepair, Etc.' to the 'Cellphone repair' category. 

Details follow: 
```yml 
- name: Craig’s iRepair, Etc.
  url: http://www.craigsirepairetc.com
  img: CraigsiRepairEtc.png
  bch: true
  btc: true
  othercrypto: true
  email_address: craigsirepair@gmail.com
  region: na
  country: US
  city: Springfield, VT
```

Resources for adding this merchant:
[Link to Craig’s iRepair, Etc.](http://www.craigsirepairetc.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.craigsirepairetc.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.craigsirepairetc.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.craigsirepairetc.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
