### ISSUE TITLE
Add 'Ancient Path Naturals' to the 'Home Garden' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1739]
Requesting to add 'Ancient Path Naturals' to the 'Home Garden' category. 

Details follow: 
```yml 
- name: Ancient Path Naturals
  url: https://ancientpathnaturals.com/
  img: AncientPathNaturals.png
  bch: true
  btc: true
  othercrypto: true
  facebook: ancientpathnaturals
  email_address: ancientpathnaturals@pm.me
  exceptions:
    text: "Coinpayments.net or thru direct wallet transfer"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://ancientpathnaturals.com/)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/ancientpathnaturals/picture)
[Link to Ancient Path Naturals](https://ancientpathnaturals.com/)
Check their Facebook Page: [fb.com/ancientpathnaturals](https://fb.com/ancientpathnaturals)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/ancientpathnaturals.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/ancientpathnaturals.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/ancientpathnaturals.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
