### ISSUE TITLE
Add 'CBD Giant' to the 'Health Shop ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1741]
Requesting to add 'CBD Giant' to the 'Health Shop ' category. 

Details follow: 
```yml 
- name: CBD Giant
  url: https://www.cbdgiant.co.uk
  img: CBDGiant.png
  bch: true
  btc: false
  othercrypto: true
  email_address: hello@cbdgiant.co.uk
  region: eu
  city: Headley
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0200/2927/6260/files/R2_1.png?1942)
[Link to CBD Giant](https://www.cbdgiant.co.uk)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cbdgiant.co.uk)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cbdgiant.co.uk)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cbdgiant.co.uk)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
