### ISSUE TITLE
Add 'AirVPN' to the 'VPN' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1750]
Requesting to add 'AirVPN' to the 'VPN' category. 

Details follow: 
```yml 
- name: AirVPN
  url: https://airvpn.org/
  img: AirVPN.png
  bch: true
  btc: true
  othercrypto: true
  twitter: airvpn
  facebook: airvpn.org
  doc: https://airvpn.org/forums/topic/43868-several-cryptocurrencies-accepted-directly/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/2812060055/33fa8d9e3084debda8c29cb7e33d9ec0_bigger.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/2812060055/33fa8d9e3084debda8c29cb7e33d9ec0_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/airvpn.org/picture)
[Link to AirVPN](https://airvpn.org/)
Check their Twitter Page: [twitter.com/airvpn](https://twitter.com/airvpn)
Check their Facebook Page: [fb.com/airvpn.org](https://fb.com/airvpn.org)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/airvpn.org/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/airvpn.org/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/airvpn.org/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
