### ISSUE TITLE
Add 'Crazy Calm CBD Coffee' to the 'Food and Beverage' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1752]
Requesting to add 'Crazy Calm CBD Coffee' to the 'Food and Beverage' category. 

Details follow: 
```yml 
- name: Crazy Calm CBD Coffee
  url: https://www.crazycalm.co
  img: CrazyCalmCBDCoffee.png
  bch: true
  btc: true
  othercrypto: true
  twitter: crazycalmco
  email_address: matt@crazycalm.co
  region: na
  country: US
  doc: https://www.crazycalm.co/launch-cc/
  exceptions:
    text: "Simply choose "Pay with crypto" at checkout and a 10% discount is automatically applied."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.crazycalm.co/wp-content/uploads/2019/09/Crazy_Calm_Logo_Black-032.svg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1196467250800340994/cvBmhiIQ_normal.jpg)
[Link to Crazy Calm CBD Coffee](https://www.crazycalm.co)
Check their Twitter Page: [twitter.com/crazycalmco](https://twitter.com/crazycalmco)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.crazycalm.co)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.crazycalm.co)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.crazycalm.co)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [mattaaron](https://twitter.com/mattaaron/), be sure to send out a tweet when this request has been added.
