### ISSUE TITLE
Add 'Crazy Calm' to the 'food and beverage' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1753]
Requesting to add 'Crazy Calm' to the 'food and beverage' category. 

Details follow: 
```yml 
- name: Crazy Calm
  url: https://www.crazycalm.co
  img: CrazyCalm.png
  bch: true
  btc: true
  othercrypto: true
  twitter: crazycalmco
  email_address: matt@crazycalm.co
  region: na
  country: US
  doc: https://news.bitcoin.com/cbd-coffee-company-leverages-censorship-resistant-nature-of-crypto/
  exceptions:
    text: "Coinbase Commerce 10% discount"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.crazycalm.co/wp-content/uploads/2019/09/bitcoin_cash_icon-e1576134174464.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1196467250800340994/cvBmhiIQ_normal.jpg)
[Link to Crazy Calm](https://www.crazycalm.co)
Check their Twitter Page: [twitter.com/crazycalmco](https://twitter.com/crazycalmco)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.crazycalm.co)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.crazycalm.co)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.crazycalm.co)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
