### ISSUE TITLE
Add 'Bit4.Sale' to the 'Cryptocurrency Exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1754]
Requesting to add 'Bit4.Sale' to the 'Cryptocurrency Exchange' category. 

Details follow: 
```yml 
- name: Bit4.Sale
  url: https://bit4.sale/
  img: BitSale.png
  bch: true
  btc: false
  othercrypto: true
  twitter: bit4sale
  facebook: bit4sale
  email_address: hello@bit4.sale
  region: eu
  exceptions:
    text: "Provide their Bitcoin cash wallet address where BCH will be sent to"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/Bit4Sale/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1040159542968049664/-QFrVxWg_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/bit4sale/picture)
[Link to Bit4.Sale](https://bit4.sale/)
Check their Twitter Page: [twitter.com/bit4sale](https://twitter.com/bit4sale)
Check their Facebook Page: [fb.com/bit4sale](https://fb.com/bit4sale)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bit4.sale/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bit4.sale/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bit4.sale/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
