### ISSUE TITLE
Add 'HostUp' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1756]
Requesting to add 'HostUp' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: HostUp
  url: https://hostup.org/
  img: HostUp.png
  bch: true
  btc: true
  othercrypto: false
  twitter: hostup
  facebook: hostupdotorg
  email_address: contact@hostup.org
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://hostup.org/img/logo-128x.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1119997535559589888/HA4ns_1d_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/hostupdotorg/picture)
[Link to HostUp](https://hostup.org/)
Check their Twitter Page: [twitter.com/hostup](https://twitter.com/hostup)
Check their Facebook Page: [fb.com/hostupdotorg](https://fb.com/hostupdotorg)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/hostup.org/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/hostup.org/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/hostup.org/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
