### ISSUE TITLE
Add 'De Fietsknecht' to the 'Bicycles, repairs and parts' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1757]
Requesting to add 'De Fietsknecht' to the 'Bicycles, repairs and parts' category. 

Details follow: 
```yml 
- name: De Fietsknecht
  url: https://fietsknecht.nl
  img: DeFietsknecht.png
  bch: true
  btc: false
  othercrypto: true
  twitter: fietsknecht
  facebook: defietsknecht
  email_address: info@fietsknecht.nl
  region: eu
  country: NL
  doc: https://fietsknecht.nl/index.php?route=extension/news/news&news_id=2
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://fietsknecht.nl/image/logo60x60.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1171082054026575872/PnguvfN1_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/defietsknecht/picture)
[Link to De Fietsknecht](https://fietsknecht.nl)
Check their Twitter Page: [twitter.com/fietsknecht](https://twitter.com/fietsknecht)
Check their Facebook Page: [fb.com/defietsknecht](https://fb.com/defietsknecht)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/fietsknecht.nl)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/fietsknecht.nl)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/fietsknecht.nl)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
