### ISSUE TITLE
Add 'Anonymous Ads' to the 'Ad network' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1763]
Requesting to add 'Anonymous Ads' to the 'Ad network' category. 

Details follow: 
```yml 
- name: Anonymous Ads
  url: https://a-ads.com/
  img: AnonymousAds.png
  bch: false
  btc: true
  othercrypto: true
  twitter: aads_network
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://a-ads.com/assets/A-ads-logo-754e2ba4942503ce81508f9f9c0c9500.svg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/966412016318631942/spqpyvtB_normal.jpg)
[Link to Anonymous Ads](https://a-ads.com/)
Check their Twitter Page: [twitter.com/aads_network](https://twitter.com/aads_network)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/a-ads.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/a-ads.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/a-ads.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
