### ISSUE TITLE
Requesting to add {{read.cash}} to the {{Social}} category

### ISSUE THREAD

**Issue by Telesfor1** [acceptbitcoincash/acceptbitcoincash#1764]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{read.cash}} to the {{Social}} category. Details follow:

```yml

- name: read.cash
  url: https://read.cash
  img: 
  twitter: 
  facebook: 
  region: 
  country: 
  city: 
  bch: yes
  bsv: no
  btc: no
  othercrypto: no
  doc: https://read.cash/@Read.Cash/what-is-readcash-7b0bfcfc
  keywords:
  - blogging platform
  - blog
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
