### ISSUE TITLE
Add 'Crazy Calm CBD Coffee' to the 'CBD' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1766]
Requesting to add 'Crazy Calm CBD Coffee' to the 'CBD' category. 

Details follow: 
```yml 
- name: Crazy Calm CBD Coffee
  url: https://www.crazycalm.co
  img: CrazyCalmCBDCoffee.png
  bch: true
  btc: true
  othercrypto: true
  twitter: crazycalmco
  region: na
  country: US
  city: The whole country
  doc: https://straininsider.com/cannabis-and-crypto-match-made-in-heaven/
  exceptions:
    text: "Nope."
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1220176769501843456/IFpusWGM_normal.jpg)
[Link to Crazy Calm CBD Coffee](https://www.crazycalm.co)
Check their Twitter Page: [twitter.com/crazycalmco](https://twitter.com/crazycalmco)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.crazycalm.co)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.crazycalm.co)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.crazycalm.co)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
