### ISSUE TITLE
Add 'Bitcoin Cash Offline Wallet' to the 'Bitcoin Cash Offline Vault' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1767]
Requesting to add 'Bitcoin Cash Offline Wallet' to the 'Bitcoin Cash Offline Vault' category. 

Details follow: 
```yml 
- name: Bitcoin Cash Offline Wallet
  url: https://ba.net/bitcoin-cash-offline-wallet
  img: BitcoinCashOfflineWallet.png
  bch: true
  btc: true
  othercrypto: false
  twitter: fonosip
  email_address: iphone@ba.net
  doc: https://www.reddit.com/r/btc/comments/7zu73p/bitcoin_cash_offline_wallet_beta/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://ba.net/offline-bch/bchvault.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1882084194/banet-icon-large_normal.png)
[Link to Bitcoin Cash Offline Wallet](https://ba.net/bitcoin-cash-offline-wallet)
Check their Twitter Page: [twitter.com/fonosip](https://twitter.com/fonosip)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/ba.net/bitcoin-cash-offline-wallet)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/ba.net/bitcoin-cash-offline-wallet)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/ba.net/bitcoin-cash-offline-wallet)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [fonosip](https://twitter.com/fonosip/), be sure to send out a tweet when this request has been added.
