### ISSUE TITLE
Add 'Second Opinion Physician' to the 'Telemedicine Functional Medicine Healthcare and Lab Testing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1769]
Requesting to add 'Second Opinion Physician' to the 'Telemedicine Functional Medicine Healthcare and Lab Testing' category. 

Details follow: 
```yml 
- name: Second Opinion Physician
  url: https://www.secondopinionphysician.com
  img: SecondOpinionPhysician.png
  bch: true
  btc: false
  othercrypto: true
  facebook: secondopinionphysician
  email_address: drdave@secondopinionphysician.com
  country: US
  city: Atlanta
  doc: https://www.secondopinionphysician.com/about-us/medical-practice-accepts-bitcoin-consultations-lab-testing/
  exceptions:
    text: "No, simply send to BTC address at checkout"
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/secondopinionphysician/picture)
[Link to Second Opinion Physician](https://www.secondopinionphysician.com)
Check their Facebook Page: [fb.com/secondopinionphysician](https://fb.com/secondopinionphysician)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.secondopinionphysician.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.secondopinionphysician.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.secondopinionphysician.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @secondopiniondoc
