### ISSUE TITLE
Add 'Earth Solutions' to the 'Aromatherapy Gifts, Essential Oils and Sterling Silver Jewerly' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1770]
Requesting to add 'Earth Solutions' to the 'Aromatherapy Gifts, Essential Oils and Sterling Silver Jewerly' category. 

Details follow: 
```yml 
- name: Earth Solutions
  url: https://www.earthsolutions.com
  img: EarthSolutions.png
  bch: true
  btc: false
  othercrypto: true
  facebook: earthsolutionsaromatherapy
  email_address: customerservice@earthsolutions.com
  country: US
  city: Atlanta
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/earthsolutionsaromatherapy/picture)
[Link to Earth Solutions](https://www.earthsolutions.com)
Check their Facebook Page: [fb.com/earthsolutionsaromatherapy](https://fb.com/earthsolutionsaromatherapy)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.earthsolutions.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.earthsolutions.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.earthsolutions.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @secondopiniondoc
