### ISSUE TITLE
Add 'Elite Campgrounds' to the 'Camping ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1773]
Requesting to add 'Elite Campgrounds' to the 'Camping ' category. 

Details follow: 
```yml 
- name: Elite Campgrounds
  url: https://www.elite-campgrounds.com
  img: EliteCampgrounds.png
  bch: true
  btc: false
  othercrypto: true
```

Resources for adding this merchant:
[Link to Elite Campgrounds](https://www.elite-campgrounds.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.elite-campgrounds.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.elite-campgrounds.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.elite-campgrounds.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
