### ISSUE TITLE
Add 'Accepted Here' to the 'Directories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1774]
Requesting to add 'Accepted Here' to the 'Directories' category. 

Details follow: 
```yml 
- name: Accepted Here
  url: https://www.acceptedhere.io/
  img: AcceptedHere.png
  bch: true
  btc: true
  othercrypto: true
  twitter: accepted_here
  facebook: -
  email_address: hello@acceptedhere.io
  doc: https://www.acceptedhere.io/stats/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/JT2d2NU.jpg?1)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1154435957157969920/-GE7aY0p_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/-/picture)
[Link to Accepted Here](https://www.acceptedhere.io/)
Check their Twitter Page: [twitter.com/accepted_here](https://twitter.com/accepted_here)
Check their Facebook Page: [fb.com/-](https://fb.com/-)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.acceptedhere.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.acceptedhere.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.acceptedhere.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [accepted_here](https://twitter.com/accepted_here/), be sure to send out a tweet when this request has been added.
