### ISSUE TITLE
Add 'Crypto Supply' to the 'Fashion and Apparel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1775]
Requesting to add 'Crypto Supply' to the 'Fashion and Apparel' category. 

Details follow: 
```yml 
- name: Crypto Supply
  url: https://crypto-supply.com/
  img: CryptoSupply.png
  bch: true
  btc: true
  othercrypto: true
  email_address: info@crypto-supply.com
```

Resources for adding this merchant:
[Link to Crypto Supply](https://crypto-supply.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/crypto-supply.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/crypto-supply.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/crypto-supply.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
