### ISSUE TITLE
Add 'Santosa Detox/Wellness Center and Vegan Restaurant' to the 'Restaurant / Wellness' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1777]
Requesting to add 'Santosa Detox/Wellness Center and Vegan Restaurant' to the 'Restaurant / Wellness' category. 

Details follow: 
```yml 
- name: Santosa Detox/Wellness Center and Vegan Restaurant
  url: https://www.santosaphuket.com/
  img: SantosaDetoxWellnessCenterandVeganRestaurant.png
  bch: true
  btc: true
  othercrypto: false
  facebook: santosaphuket
  email_address: crypto@bgb.villas
  doc: https://www.santosaphuket.com/ (specified in the bottom of the home page)
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.santosaphuket.com/wp-content/uploads/2020/02/Logo-santosa-piccolo-crypto-1.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/santosaphuket/picture)
[Link to Santosa Detox/Wellness Center and Vegan Restaurant](https://www.santosaphuket.com/)
Check their Facebook Page: [fb.com/santosaphuket](https://fb.com/santosaphuket)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.santosaphuket.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.santosaphuket.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.santosaphuket.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
