### ISSUE TITLE
Add 'luxemiss' to the 'gifts for her' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1778]
Requesting to add 'luxemiss' to the 'gifts for her' category. 

Details follow: 
```yml 
- name: luxemiss
  url: https://luxemiss.com
  img: luxemiss.png
  bch: true
  btc: true
  othercrypto: true
  twitter: luxemisshq
  facebook: luxemisshq
  email_address: media@luxemiss.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/luxemisshq/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1215509578726592513/J4XJe-hN_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/luxemisshq/picture)
[Link to luxemiss](https://luxemiss.com)
Check their Twitter Page: [twitter.com/luxemisshq](https://twitter.com/luxemisshq)
Check their Facebook Page: [fb.com/luxemisshq](https://fb.com/luxemisshq)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/luxemiss.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/luxemiss.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/luxemiss.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @luxemiss
Request made by Twitter user [luxemisshq](https://twitter.com/luxemisshq/), be sure to send out a tweet when this request has been added.
