### ISSUE TITLE
Add 'luxegift' to the 'gift guide + gift ideas accepting $BCH' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1779]
Requesting to add 'luxegift' to the 'gift guide + gift ideas accepting $BCH' category. 

Details follow: 
```yml 
- name: luxegift
  url: https://luxegift.co
  img: luxegift.png
  bch: true
  btc: true
  othercrypto: true
  twitter: luxegiftco
  facebook: luxegiftco
  email_address: media@luxegift.co
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/luxegiftco/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1224851508329472000/dXQ9ZE1R_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/luxegiftco/picture)
[Link to luxegift](https://luxegift.co)
Check their Twitter Page: [twitter.com/luxegiftco](https://twitter.com/luxegiftco)
Check their Facebook Page: [fb.com/luxegiftco](https://fb.com/luxegiftco)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/luxegift.co)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/luxegift.co)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/luxegift.co)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @luxegift
Request made by Twitter user [luxegiftco](https://twitter.com/luxegiftco/), be sure to send out a tweet when this request has been added.
