### ISSUE TITLE
Add 'jessica escorts' to the 'kolkata escorts' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1780]
Requesting to add 'jessica escorts' to the 'kolkata escorts' category. 

Details follow: 
```yml 
- name: jessica escorts
  url: https://www.jessicaescortsservices.com/
  img: jessicaescorts.png
  bch: false
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to jessica escorts](https://www.jessicaescortsservices.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.jessicaescortsservices.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.jessicaescortsservices.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.jessicaescortsservices.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
