### ISSUE TITLE
Swapzone

### ISSUE THREAD

**Issue by SwapzoneIO** [acceptbitcoincash/acceptbitcoincash#1781]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Swapzone**}} to the {{**Crypto Exchanges**}} category. Details follow:

```yml

- name: Swapzone
  url: https://swapzone.io/
  img: https://swapzone.io/assets/svg/2f7I8Km.svg
  twitter: swapzoneio
  region: eu
  bch: yes
  bsv: yes
  btc: yes
  othercrypto: yes
  doc: https://swapzone.io/how-to/
  keywords:
  - altcoins
  - exchange aggregator
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
