### ISSUE TITLE
Add 'Bitopia' to the 'Marketing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1791]
Requesting to add 'Bitopia' to the 'Marketing' category. 

Details follow: 
```yml 
- name: Bitopia
  url: https://bitopia.io
  img: Bitopia.png
  bch: true
  btc: true
  othercrypto: true
  email_address: bitopianio@gmail.com
  exceptions:
    text: "Use our contact form to make a payment request in BCH."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://scontent.fpac2-1.fna.fbcdn.net/v/t1.0-1/18519958_740393022798953_7125772069343491410_n.jpg?_nc_cat=110&_nc_sid=dbb9e7&_nc_oc=AQnFl5XBh7GKsVQegvFf-xKyXahXJ7_WVITY1aupwcD1XzRn4lzQ8YcLAjobPEBjgws&_nc_ht=scontent.fpac2-1.fna&oh=6c50d5ea628fdf64539927b1b909e1b2&oe=5F03884C)
[Link to Bitopia](https://bitopia.io)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitopia.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitopia.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitopia.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
