### ISSUE TITLE
Add 'Daniel Smukalla' to the 'Film and Video' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1794]
Requesting to add 'Daniel Smukalla' to the 'Film and Video' category. 

Details follow: 
```yml 
- name: Daniel Smukalla
  url: https://www.smukalla.com/
  img: DanielSmukalla.png
  bch: true
  btc: true
  othercrypto: true
  email_address: smukalla@protonmail.com
  country: KR
  city: Seoul
  exceptions:
    text: "cryptocameraman.com"
```

Resources for adding this merchant:
[Link to Daniel Smukalla](https://www.smukalla.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.smukalla.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.smukalla.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.smukalla.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
