### ISSUE TITLE
Add 'Yunizon Eyewear' to the 'Consumer Goods' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1795]
Requesting to add 'Yunizon Eyewear' to the 'Consumer Goods' category. 

Details follow: 
```yml 
- name: Yunizon Eyewear
  url: http://yunizoneyewear.com/
  img: YunizonEyewear.png
  bch: true
  btc: false
  othercrypto: true
  facebook: yunizoneyewearus
  email_address: rebecca.lay@yunizoneyewear.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.facebook.com/293241597980673/photos/531877720783725/)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/yunizoneyewearus/picture)
[Link to Yunizon Eyewear](http://yunizoneyewear.com/)
Check their Facebook Page: [fb.com/yunizoneyewearus](https://fb.com/yunizoneyewearus)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/yunizoneyewear.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/yunizoneyewear.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/yunizoneyewear.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
