### ISSUE TITLE
Add 'Alexane Johnson' to the 'news' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1797]
Requesting to add 'Alexane Johnson' to the 'news' category. 

Details follow: 
```yml 
- name: Alexane Johnson
  url: https://www.cryptoknowmics.com/news/meaning-of-hodl
  img: AlexaneJohnson.png
  bch: true
  btc: true
  othercrypto: true
  email_address: Alexanejohnson12@gmail.com
  country: US
  city: bristol
  exceptions:
    text: "ya"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://d3cdhgujr8otwi.cloudfront.net/logo/logoicon.jpg)
[Link to Alexane Johnson](https://www.cryptoknowmics.com/news/meaning-of-hodl)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cryptoknowmics.com/news/meaning-of-hodl)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cryptoknowmics.com/news/meaning-of-hodl)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cryptoknowmics.com/news/meaning-of-hodl)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
