### ISSUE TITLE
Add 'BCH Shop' to the 'Online shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1798]
Requesting to add 'BCH Shop' to the 'Online shop' category. 

Details follow: 
```yml 
- name: BCH Shop
  url: https://bchuganda.com
  img: BCHShop.png
  bch: true
  btc: false
  othercrypto: false
  twitter: bchuganda
  email_address: jabzrodgers@gmail.com
  region: af
  country: UG
  city: KAMPALA
  exceptions:
    text: "No as long as one has BCH on the Wallet and completes the payment"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.screencast.com/t/fQnXBpvVW)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1241675266881130497/XjpDDOyO_normal.jpg)
[Link to BCH Shop](https://bchuganda.com)
Check their Twitter Page: [twitter.com/bchuganda](https://twitter.com/bchuganda)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bchuganda.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bchuganda.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bchuganda.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
