### ISSUE TITLE
Add 'DeBounce' to the 'Email Validation' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1799]
Requesting to add 'DeBounce' to the 'Email Validation' category. 

Details follow: 
```yml 
- name: DeBounce
  url: https://debounce.io
  img: DeBounce.png
  bch: true
  btc: true
  othercrypto: true
  twitter: debounceio
  email_address: mark@debounce.io
  doc: https://debounce.io/pricing/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn2.hubspot.net/hubfs/7019471/debounce-square-800x800.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1028254264630685696/sfHhCoZc_normal.jpg)
[Link to DeBounce](https://debounce.io)
Check their Twitter Page: [twitter.com/debounceio](https://twitter.com/debounceio)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/debounce.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/debounce.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/debounce.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
