### ISSUE TITLE
Add 'JASGOOD' to the 'Clothing/Belt' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1801]
Requesting to add 'JASGOOD' to the 'Clothing/Belt' category. 

Details follow: 
```yml 
- name: JASGOOD
  url: https://www.jasgood.com/
  img: JASGOOD.png
  bch: true
  btc: true
  othercrypto: true
  facebook: jasgood-103790587762346
  email_address: info@jasgood.com
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0068/1128/7611/files/jasgood.png?v=1573551816)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/jasgood-103790587762346/picture)
[Link to JASGOOD](https://www.jasgood.com/)
Check their Facebook Page: [fb.com/jasgood-103790587762346](https://fb.com/jasgood-103790587762346)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.jasgood.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.jasgood.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.jasgood.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
