### ISSUE TITLE
Add 'Amkha Seed' to the 'Rare and Heirloom Seeds' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1804]
Requesting to add 'Amkha Seed' to the 'Rare and Heirloom Seeds' category. 

Details follow: 
```yml 
- name: Amkha Seed
  url: https://www.amkhaseed.com
  img: AmkhaSeed.png
  bch: true
  btc: true
  othercrypto: true
  twitter: amkhaseed
  facebook: amkhaseed
  email_address: contact@amkhaseed.com
  region: na
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/1420/8798/files/Web_logo_500px.jpg?v=1585428114)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/761056866986106880/xI0V7hS3_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/amkhaseed/picture)
[Link to Amkha Seed](https://www.amkhaseed.com)
Check their Twitter Page: [twitter.com/amkhaseed](https://twitter.com/amkhaseed)
Check their Facebook Page: [fb.com/amkhaseed](https://fb.com/amkhaseed)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.amkhaseed.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.amkhaseed.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.amkhaseed.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [amkhaseed](https://twitter.com/amkhaseed/), be sure to send out a tweet when this request has been added.
