### ISSUE TITLE
Add 'Lone Star Flower' to the 'Alternative Medicine' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1805]
Requesting to add 'Lone Star Flower' to the 'Alternative Medicine' category. 

Details follow: 
```yml 
- name: Lone Star Flower
  url: https://lonestarflower.com
  img: LoneStarFlower.png
  bch: true
  btc: true
  othercrypto: true
  twitter: lonestarflower
  email_address: jonathan@lonestarflower.com
  region: na
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://lonestarflower.com/wp-content/uploads/2020/02/logo_transparent-1.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1224834063237832710/gkLQvwxv_normal.jpg)
[Link to Lone Star Flower](https://lonestarflower.com)
Check their Twitter Page: [twitter.com/lonestarflower](https://twitter.com/lonestarflower)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/lonestarflower.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/lonestarflower.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/lonestarflower.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [lonestarflower](https://twitter.com/lonestarflower/), be sure to send out a tweet when this request has been added.
