### ISSUE TITLE
Add 'Bitcoin Mall' to the 'Electronics/Gift Cards' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1806]
Requesting to add 'Bitcoin Mall' to the 'Electronics/Gift Cards' category. 

Details follow: 
```yml 
- name: Bitcoin Mall
  url: https://bitcoinmall.info
  img: BitcoinMall.png
  bch: true
  btc: true
  othercrypto: true
  twitter: mallbitcoin
  facebook: bitcoinmallofficial
  email_address: support@bitcoinmall.info
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://bitcoinmall.info/wp-content/uploads/2019/08/large-1.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1171513812920356864/_-C_sjFp_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/bitcoinmallofficial/picture)
[Link to Bitcoin Mall](https://bitcoinmall.info)
Check their Twitter Page: [twitter.com/mallbitcoin](https://twitter.com/mallbitcoin)
Check their Facebook Page: [fb.com/bitcoinmallofficial](https://fb.com/bitcoinmallofficial)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitcoinmall.info)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitcoinmall.info)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitcoinmall.info)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
