### ISSUE TITLE
Add 'RevolutionHosting' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1807]
Requesting to add 'RevolutionHosting' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: RevolutionHosting
  url: https://rhosting.it
  img: RevolutionHosting.png
  bch: false
  btc: true
  othercrypto: true
  twitter: rhprovider
  facebook: revolutionhosting
  email_address: info@rhosting.it
  doc: https://t.me/rhosting/84
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://rhosting.it/images/opt/logonav.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1056608317248864257/2iir_Chf_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/revolutionhosting/picture)
[Link to RevolutionHosting](https://rhosting.it)
Check their Twitter Page: [twitter.com/rhprovider](https://twitter.com/rhprovider)
Check their Facebook Page: [fb.com/revolutionhosting](https://fb.com/revolutionhosting)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/rhosting.it)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/rhosting.it)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/rhosting.it)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
