### ISSUE TITLE
Add 'Lwallet' to the 'Internet Shop (We are selling crypto devices)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1808]
Requesting to add 'Lwallet' to the 'Internet Shop (We are selling crypto devices)' category. 

Details follow: 
```yml 
- name: Lwallet
  url: https://lwallet.com.ua
  img: Lwallet.png
  bch: true
  btc: true
  othercrypto: true
  email_address: dmytro@lwallet.com.ua
  region: eu
  country: UA
  city: Kiev
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://lwallet.com.ua/wp-content/uploads/2019/09/logo_png_v2-1.png)
[Link to Lwallet](https://lwallet.com.ua)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/lwallet.com.ua)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/lwallet.com.ua)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/lwallet.com.ua)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
