### ISSUE TITLE
Add 'TheDigitalPickup' to the 'Online Dating Advice' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1809]
Requesting to add 'TheDigitalPickup' to the 'Online Dating Advice' category. 

Details follow: 
```yml 
- name: TheDigitalPickup
  url: https://TheDigitalPickup.com
  img: TheDigitalPickup.png
  bch: true
  btc: true
  othercrypto: true
  twitter: qxdc
  email_address: qxtrue@protonmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/Gx182Xi.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1195182399392366593/9iqmAmSf_normal.jpg)
[Link to TheDigitalPickup](https://TheDigitalPickup.com)
Check their Twitter Page: [twitter.com/qxdc](https://twitter.com/qxdc)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/TheDigitalPickup.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/TheDigitalPickup.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/TheDigitalPickup.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
