### ISSUE TITLE
Add 'BitHost.io' to the 'VPS hosting, Cloud Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1811]
Requesting to add 'BitHost.io' to the 'VPS hosting, Cloud Hosting' category. 

Details follow: 
```yml 
- name: BitHost.io
  url: https://bithost.io
  img: BitHostio.png
  bch: true
  btc: false
  othercrypto: true
  twitter: bithostio
  email_address: support@bithost.io
  country: US
  city: No
  exceptions:
    text: "We use coinpayments.net as a processor."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1250338932459327489/ShOLl-I7_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1250338932459327489/ShOLl-I7_normal.jpg)
[Link to BitHost.io](https://bithost.io)
Check their Twitter Page: [twitter.com/bithostio](https://twitter.com/bithostio)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bithost.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bithost.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bithost.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [bithostio](https://twitter.com/bithostio/), be sure to send out a tweet when this request has been added.
