### ISSUE TITLE
Add 'SuperBitHost.com' to the 'Webhosting, Dedicated server, VPS, Domain, SSL Certificate' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1812]
Requesting to add 'SuperBitHost.com' to the 'Webhosting, Dedicated server, VPS, Domain, SSL Certificate' category. 

Details follow: 
```yml 
- name: SuperBitHost.com
  url: https://www.superbithost.com
  img: SuperBitHostcom.png
  bch: true
  btc: false
  othercrypto: true
  twitter: superbithost
  email_address: support@superbithost.com
  city: no
  exceptions:
    text: "We use www.coinpayments.net as a processor."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.superbithost.com/assets/img/logo.svg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/715934984398311424/lFXgixnr_normal.jpg)
[Link to SuperBitHost.com](https://www.superbithost.com)
Check their Twitter Page: [twitter.com/superbithost](https://twitter.com/superbithost)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.superbithost.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.superbithost.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.superbithost.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
