### ISSUE TITLE
Add 'aDriving' to the 'Driving School' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1816]
Requesting to add 'aDriving' to the 'Driving School' category. 

Details follow: 
```yml 
- name: aDriving
  url: https://www.adriving.co.uk/
  img: aDriving.png
  bch: true
  btc: true
  othercrypto: false
  twitter: adrivingsch
  facebook: adriving.co.uk
  email_address: info@adriving.co.uk
  region: eu
  country: GB
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1211060283688534016/rzgZSDTP_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/adriving.co.uk/picture)
[Link to aDriving](https://www.adriving.co.uk/)
Check their Twitter Page: [twitter.com/adrivingsch](https://twitter.com/adrivingsch)
Check their Facebook Page: [fb.com/adriving.co.uk](https://fb.com/adriving.co.uk)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.adriving.co.uk/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.adriving.co.uk/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.adriving.co.uk/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
