### ISSUE TITLE
Add 'BitBirdy' to the 'Online Shopping' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1817]
Requesting to add 'BitBirdy' to the 'Online Shopping' category. 

Details follow: 
```yml 
- name: BitBirdy
  url: https://www.bitbirdy.com
  img: BitBirdy.png
  bch: true
  btc: false
  othercrypto: false
  twitter: bitbirdy
  facebook: bitbirdy
  email_address: bitbirdyshop@gmail.com
  doc: https://twitter.com/BitBirdy/status/1252651602978181120?s=20
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://scontent-atl3-1.xx.fbcdn.net/v/t1.0-9/94489897_105873391105440_2723160813585039360_o.png?_nc_cat=107&_nc_sid=09cbfe&_nc_ohc=iZfrwIy8tGYAX97j42V&_nc_ht=scontent-atl3-1.xx&oh=84b42ce4439f496de316a204f327d58a&oe=5EC597E9)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1247698748916056065/ioroonZl_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/bitbirdy/picture)
[Link to BitBirdy](https://www.bitbirdy.com)
Check their Twitter Page: [twitter.com/bitbirdy](https://twitter.com/bitbirdy)
Check their Facebook Page: [fb.com/bitbirdy](https://fb.com/bitbirdy)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.bitbirdy.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.bitbirdy.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.bitbirdy.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [bitbirdy](https://twitter.com/bitbirdy/), be sure to send out a tweet when this request has been added.
