### ISSUE TITLE
Add 'BitLaunch' to the 'Cloud Computing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1819]
Requesting to add 'BitLaunch' to the 'Cloud Computing' category. 

Details follow: 
```yml 
- name: BitLaunch
  url: https://bitlaunch.io
  img: BitLaunch.png
  bch: true
  btc: true
  othercrypto: true
  twitter: bitlaunchio
  email_address: support@bitlaunch.io
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://bitlaunch.io/img/logo_circle_128.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/944667097736630272/LJYyE9W__normal.jpg)
[Link to BitLaunch](https://bitlaunch.io)
Check their Twitter Page: [twitter.com/bitlaunchio](https://twitter.com/bitlaunchio)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitlaunch.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitlaunch.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitlaunch.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @bitlaunchio
Request made by Twitter user [bitlaunchio](https://twitter.com/bitlaunchio/), be sure to send out a tweet when this request has been added.
