### ISSUE TITLE
Add 'Swapzone' to the 'cryptocurrency exchange aggregator ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1820]
Requesting to add 'Swapzone' to the 'cryptocurrency exchange aggregator ' category. 

Details follow: 
```yml 
- name: Swapzone
  url: https://swapzone.io/
  img: Swapzone.png
  bch: true
  btc: true
  othercrypto: true
  twitter: swapzoneio
  email_address: roxanne@swapzone.io
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://swapzone.io/press)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1201485896387846144/n-iaqBo0_normal.png)
[Link to Swapzone](https://swapzone.io/)
Check their Twitter Page: [twitter.com/swapzoneio](https://twitter.com/swapzoneio)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/swapzone.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/swapzone.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/swapzone.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [swapzoneio](https://twitter.com/swapzoneio/), be sure to send out a tweet when this request has been added.
