### ISSUE TITLE
Add 'onFOMO' to the 'Cryptocurrency exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1821]
Requesting to add 'onFOMO' to the 'Cryptocurrency exchange' category. 

Details follow: 
```yml 
- name: onFOMO
  url: https://onfomo.com/en/
  img: onFOMO.png
  bch: true
  btc: false
  othercrypto: true
  exceptions:
    text: "To buy BCH, users need to verify their identity and provide a BCH wallet"
```

Resources for adding this merchant:
[Link to onFOMO](https://onfomo.com/en/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/onfomo.com/en/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/onfomo.com/en/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/onfomo.com/en/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
