### ISSUE TITLE
Add 'postale.io' to the 'Domain email service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1824]
Requesting to add 'postale.io' to the 'Domain email service' category. 

Details follow: 
```yml 
- name: postale.io
  url: https://postale.io
  img: postaleio.png
  bch: true
  btc: false
  othercrypto: true
  email_address: support@postale.io
  doc: https://postale.io/donate
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://postale.io/build/images/logo.svg)
[Link to postale.io](https://postale.io)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/postale.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/postale.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/postale.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @emmainthesky
