### ISSUE TITLE
Add 'Dragon Aromas Poppers Manufacturer' to the 'Poppers' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1825]
Requesting to add 'Dragon Aromas Poppers Manufacturer' to the 'Poppers' category. 

Details follow: 
```yml 
- name: Dragon Aromas Poppers Manufacturer
  url: https://dragon-aromas.com/
  img: DragonAromasPoppersManufacturer.png
  bch: true
  btc: true
  othercrypto: true
  email_address: dragonmanufacture@gmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://dragon-aromas.com/wp-content/uploads/2020/04/logo.png)
[Link to Dragon Aromas Poppers Manufacturer](https://dragon-aromas.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/dragon-aromas.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/dragon-aromas.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/dragon-aromas.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
