### ISSUE TITLE
Add 'Online Underwear Store Dimari Lingerie' to the 'Lingerie' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1826]
Requesting to add 'Online Underwear Store Dimari Lingerie' to the 'Lingerie' category. 

Details follow: 
```yml 
- name: Online Underwear Store Dimari Lingerie
  url: https://dimarilingerie.com/en/
  img: OnlineUnderwearStoreDimariLingerie.png
  bch: true
  btc: true
  othercrypto: true
  twitter: dimariportugal
  facebook: dimariportugal
  email_address: dimarilingerie@gmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/DimariPortugal/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1165915071459024896/KGCl0plP_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/dimariportugal/picture)
[Link to Online Underwear Store Dimari Lingerie](https://dimarilingerie.com/en/)
Check their Twitter Page: [twitter.com/dimariportugal](https://twitter.com/dimariportugal)
Check their Facebook Page: [fb.com/dimariportugal](https://fb.com/dimariportugal)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/dimarilingerie.com/en/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/dimarilingerie.com/en/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/dimarilingerie.com/en/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [dimariportugal](https://twitter.com/dimariportugal/), be sure to send out a tweet when this request has been added.
