### ISSUE TITLE
Add 'Valerie Ferreira lopes' to the 'Gandi SAS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1828]
Requesting to add 'Valerie Ferreira lopes' to the 'Gandi SAS' category. 

Details follow: 
```yml 
- name: Valerie Ferreira lopes
  url: http://www.wideo.fr/
  img: ValerieFerreiralopes.png
  bch: true
  btc: true
  othercrypto: true
  facebook: www.wideo.fr
  email_address: dlili0702@hotmail.fr
  region: eu
  country: FR
  city: Artix
  exceptions:
    text: "Bitcoin"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://www.wideo.fr/)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/www.wideo.fr/picture)
[Link to Valerie Ferreira lopes](http://www.wideo.fr/)
Check their Facebook Page: [fb.com/www.wideo.fr](https://fb.com/www.wideo.fr)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.wideo.fr/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.wideo.fr/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.wideo.fr/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @bitcoin
Request made by Twitter user [bitcoin](https://twitter.com/bitcoin/), be sure to send out a tweet when this request has been added.
