### ISSUE TITLE
Add 'Planet Express' to the 'Logistics services / online shopping' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1833]
Requesting to add 'Planet Express' to the 'Logistics services / online shopping' category. 

Details follow: 
```yml 
- name: Planet Express
  url: https://planetexpress.com/
  img: PlanetExpress.png
  bch: true
  btc: true
  othercrypto: false
  twitter: myplanetexpress
  facebook: myplanetexpress
  email_address: help@planetexpress.com
  doc: https://planetexpress.com/2018/12/11/planet-express-now-accepts-bitcoin/
  exceptions:
    text: "https://planetexpress.com/payment-methods/"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/877609821104680960/Px8XFEec_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/877609821104680960/Px8XFEec_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/myplanetexpress/picture)
[Link to Planet Express](https://planetexpress.com/)
Check their Twitter Page: [twitter.com/myplanetexpress](https://twitter.com/myplanetexpress)
Check their Facebook Page: [fb.com/myplanetexpress](https://fb.com/myplanetexpress)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/planetexpress.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/planetexpress.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/planetexpress.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
