### ISSUE TITLE
Add 'Süle' to the 'Law firm' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1834]
Requesting to add 'Süle' to the 'Law firm' category. 

Details follow: 
```yml 
- name: Süle
  url: https://sulelaw.com
  img: Sle.png
  bch: false
  btc: false
  othercrypto: false
  email_address: info@sulelaw.com
  region: eu
  country: DE
  city: Berlin
  doc: https://germantrademark.sulelaw.com/list-of-goods-of-german-trademarks/
```

Resources for adding this merchant:
[Link to Süle](https://sulelaw.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/sulelaw.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/sulelaw.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/sulelaw.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
