### ISSUE TITLE
Add 'Valerie Ferreira lopes' to the 'Valerie Ferreira lopes' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1839]
Requesting to add 'Valerie Ferreira lopes' to the 'Valerie Ferreira lopes' category. 

Details follow: 
```yml 
- name: Valerie Ferreira lopes
  url: https://shop.gandi.net/fr/domain/transfer
  img: ValerieFerreiralopes.png
  bch: true
  btc: true
  othercrypto: true
  facebook: shop.gandi.net/fr/domain/transfer
  email_address: valerieleo64150@gmail.com
  region: eu
  country: FR
  city: Artix
  exceptions:
    text: "https://shop.gandi.net/fr/domain/transfer"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://shop.gandi.net/fr/domain/transfer)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/shop.gandi.net/fr/domain/transfer/picture)
[Link to Valerie Ferreira lopes](https://shop.gandi.net/fr/domain/transfer)
Check their Facebook Page: [fb.com/shop.gandi.net/fr/domain/transfer](https://fb.com/shop.gandi.net/fr/domain/transfer)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/shop.gandi.net/fr/domain/transfer)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/shop.gandi.net/fr/domain/transfer)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/shop.gandi.net/fr/domain/transfer)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @shop.gandi.net/fr/domain/transfer
Request made by Twitter user [shop.gandi.net/fr/domain/transfer](https://twitter.com/shop.gandi.net/fr/domain/transfer/), be sure to send out a tweet when this request has been added.
