### ISSUE TITLE
Add 'Leo Lopes' to the 'Leo Lopes' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1840]
Requesting to add 'Leo Lopes' to the 'Leo Lopes' category. 

Details follow: 
```yml 
- name: Leo Lopes
  url: https://shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer
  img: LeoLopes.png
  bch: true
  btc: true
  othercrypto: true
  facebook: shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer
  email_address: leolopes@hotmail.fr
  region: eu
  country: FR
  city: Leo Lopes
  exceptions:
    text: "Gandi SAS"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer/picture)
[Link to Leo Lopes](https://shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer)
Check their Facebook Page: [fb.com/shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer](https://fb.com/shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer
Request made by Twitter user [shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer](https://twitter.com/shop.gandi.net/fr/1d6110f2-6c17-11ea-ae05-00163ea99cff/domain/transfer/), be sure to send out a tweet when this request has been added.
