### ISSUE TITLE
Add 'CryptoFairPlay' to the 'Bitcoin Casino' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1846]
Requesting to add 'CryptoFairPlay' to the 'Bitcoin Casino' category. 

Details follow: 
```yml 
- name: CryptoFairPlay
  url: https://www.cryptofairplay.com/
  img: CryptoFairPlay.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cryptofairplay
  facebook: cryptofairplay
  email_address: arsen.cryptofairplay@gmail.com
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1219647006546722822/KOiXL4a4_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/cryptofairplay/picture)
[Link to CryptoFairPlay](https://www.cryptofairplay.com/)
Check their Twitter Page: [twitter.com/cryptofairplay](https://twitter.com/cryptofairplay)
Check their Facebook Page: [fb.com/cryptofairplay](https://fb.com/cryptofairplay)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cryptofairplay.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cryptofairplay.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cryptofairplay.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
