### ISSUE TITLE
Add 'Bahram Rismansanj' to the 'Foodstore' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1847]
Requesting to add 'Bahram Rismansanj' to the 'Foodstore' category. 

Details follow: 
```yml 
- name: Bahram Rismansanj
  url: https://www.subway.com/de-DE
  img: BahramRismansanj.png
  bch: true
  btc: false
  othercrypto: false
  twitter: subway
  facebook: subwaydeutschland
  email_address: contact@bchghana.org
  region: eu
  country: DE
  city: Hockenheim
  exceptions:
    text: "Need QR code scanner to pay"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.subway.com/~/media/USA/Images/Branding/subway-logo-new.png?h=44&la=de-DE&w=222&hash=EEAF19AF51A8B0B183A30AC33A920959546D919E)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/763049278306652160/1AgT2EJt_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/subwaydeutschland/picture)
[Link to Bahram Rismansanj](https://www.subway.com/de-DE)
Check their Twitter Page: [twitter.com/subway](https://twitter.com/subway)
Check their Facebook Page: [fb.com/subwaydeutschland](https://fb.com/subwaydeutschland)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.subway.com/de-DE)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.subway.com/de-DE)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.subway.com/de-DE)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @kronkmeister
Request made by Twitter user [koushbch](https://twitter.com/koushbch/), be sure to send out a tweet when this request has been added.
