### ISSUE TITLE
Add 'blocstock' to the 'eCommerce store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1848]
Requesting to add 'blocstock' to the 'eCommerce store' category. 

Details follow: 
```yml 
- name: blocstock
  url: https://blocstock.com/
  img: blocstock.png
  bch: true
  btc: true
  othercrypto: true
  twitter: blocstockmarke1
  email_address: blocstock@yandex.com
  region: eu
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://ibb.co/pvm6jdj)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1276997513212506112/xpbkrtcV_normal.jpg)
[Link to blocstock](https://blocstock.com/)
Check their Twitter Page: [twitter.com/blocstockmarke1](https://twitter.com/blocstockmarke1)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/blocstock.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/blocstock.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/blocstock.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
