### ISSUE TITLE
Add 'Agio support solutions' to the 'business' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1849]
Requesting to add 'Agio support solutions' to the 'business' category. 

Details follow: 
```yml 
- name: Agio support solutions
  url: https://www.agiosupport.com/crypto-payment-and-wallet
  img: Agiosupportsolutions.png
  bch: true
  btc: true
  othercrypto: true
  email_address: agio.official05@gmail.com
  region: as
  country: IN
  city: noida
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn-images-1.medium.com/max/800/1*PEFUGruEJb0OSWLBddZVpA.png)
[Link to Agio support solutions](https://www.agiosupport.com/crypto-payment-and-wallet)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.agiosupport.com/crypto-payment-and-wallet)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.agiosupport.com/crypto-payment-and-wallet)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.agiosupport.com/crypto-payment-and-wallet)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
