### ISSUE TITLE
Add 'Get Freelancy' to the 'Marketing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1850]
Requesting to add 'Get Freelancy' to the 'Marketing' category. 

Details follow: 
```yml 
- name: Get Freelancy
  url: https://getfreelancy.com
  img: GetFreelancy.png
  bch: true
  btc: true
  othercrypto: true
  email_address: getfreelancy@protonmail.com
  doc: https://getfreelancy.com/now-accepting-crypto-for-advertising-space/
  exceptions:
    text: "2 options: send an email to the admin via admin@getfreelancy.com and request to pay for advertising via cryptocurrency or Click on the "buy me coffee" and send me a private message through the donation platform."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://getfreelancy.com/wp-content/uploads/2020/07/29f3a4e5-cced-4a4c-816d-af230e4309f9_200x200-80x80.png)
[Link to Get Freelancy](https://getfreelancy.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/getfreelancy.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/getfreelancy.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/getfreelancy.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
