### ISSUE TITLE
Add 'Bitvape' to the 'Vaporizers' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1856]
Requesting to add 'Bitvape' to the 'Vaporizers' category. 

Details follow: 
```yml 
- name: Bitvape
  url: https://bitvape.com.au
  img: Bitvape.png
  bch: true
  btc: true
  othercrypto: true
  twitter: bitvapeau
  email_address: sales@bitvape.com.au
  region: oc
  country: AU
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://bitvape.com.au/wp-content/uploads/2020/07/bitvapelogo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1281766204462395392/GBobV6gi_normal.jpg)
[Link to Bitvape](https://bitvape.com.au)
Check their Twitter Page: [twitter.com/bitvapeau](https://twitter.com/bitvapeau)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitvape.com.au)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitvape.com.au)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitvape.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
