### ISSUE TITLE
Add 'https://www.bkp365.com/' to the 'Backup' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1861]
Requesting to add 'https://www.bkp365.com/' to the 'Backup' category. 

Details follow: 
```yml 
- name: https://www.bkp365.com/
  url: https://www.bkp365.com/
  img: httpswwwbkpcom.png
  bch: true
  btc: false
  othercrypto: true
  twitter: bkp365
  email_address: paras@bkp365.com
  country: IN
  doc: https://www.bkp365.com/cloud-backup-services-in-india/
  exceptions:
    text: "Yes, contact enquiy@bkp365.com"
```

Resources for adding this merchant:
[Link to https://www.bkp365.com/](https://www.bkp365.com/)
Check their Twitter Page: [twitter.com/bkp365](https://twitter.com/bkp365)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.bkp365.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.bkp365.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.bkp365.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
