### ISSUE TITLE
Add 'All insurance shop' to the 'insurance' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1863]
Requesting to add 'All insurance shop' to the 'insurance' category. 

Details follow: 
```yml 
- name: All insurance shop
  url: https://www.allinsuranceshop.com/
  img: Allinsuranceshop.png
  bch: false
  btc: false
  othercrypto: false
  facebook: yes
  email_address: orbitofficaluse@gmail.com
  region: as
  country: US
  city: Jacksonville
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL]( https://www.allinsuranceshop.com/)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/yes/picture)
[Link to All insurance shop](https://www.allinsuranceshop.com/)
Check their Facebook Page: [fb.com/yes](https://fb.com/yes)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.allinsuranceshop.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.allinsuranceshop.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.allinsuranceshop.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
