### ISSUE TITLE
Add 'https://smokdeals.com/' to the 'Product' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1864]
Requesting to add 'https://smokdeals.com/' to the 'Product' category. 

Details follow: 
```yml 
- name: https://smokdeals.com/
  url: https://smokdeals.com/
  img: httpssmokdealscom.png
  bch: false
  btc: false
  othercrypto: false
  email_address: mikestarc123@gmail.com
  region: na
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://smokdeals.com/wp-content/uploads/2020/02/Smok-Deals-logo.png)
[Link to https://smokdeals.com/](https://smokdeals.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/smokdeals.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/smokdeals.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/smokdeals.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
