### ISSUE TITLE
Add 'XenPods' to the 'Vaporizers' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1867]
Requesting to add 'XenPods' to the 'Vaporizers' category. 

Details follow: 
```yml 
- name: XenPods
  url: https://xenpods.com.au
  img: XenPods.png
  bch: true
  btc: true
  othercrypto: false
  email_address: admin@xenpods.com.au
  region: oc
  country: AU
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://xenpods.com.au/wp-content/uploads/2020/08/icon2-b.png)
[Link to XenPods](https://xenpods.com.au)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/xenpods.com.au)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/xenpods.com.au)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/xenpods.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
