### ISSUE TITLE
Add 'Dundle.com' to the 'giftcards' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1868]
Requesting to add 'Dundle.com' to the 'giftcards' category. 

Details follow: 
```yml 
- name: Dundle.com
  url: https://dundle.com
  img: Dundlecom.png
  bch: true
  btc: true
  othercrypto: true
  exceptions:
    text: "Select the coinpayments option on the payment page"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://dundle.com/resources/images/themes/logos/dundle.com/default-logo-new.svg)
[Link to Dundle.com](https://dundle.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/dundle.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/dundle.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/dundle.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
