### ISSUE TITLE
Add 'Fidu Properties' to the 'Real Estate' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1872]
Requesting to add 'Fidu Properties' to the 'Real Estate' category. 

Details follow: 
```yml 
- name: Fidu Properties
  url: https://www.299.com
  img: FiduProperties.png
  bch: true
  btc: true
  othercrypto: false
  email_address: fiduseo@gmail.com
  country: US
  city: Dubai
```

Resources for adding this merchant:
[Link to Fidu Properties](https://www.299.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.299.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.299.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.299.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
