### ISSUE TITLE
Add 'Changeangel' to the 'Crypto Swap' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1875]
Requesting to add 'Changeangel' to the 'Crypto Swap' category. 

Details follow: 
```yml 
- name: Changeangel
  url: https://changeangel.io
  img: Changeangel.png
  bch: true
  btc: true
  othercrypto: true
  twitter: changeangel_io
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://changeangel.io/images/ca-logo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1226350193878106112/jW0cUF9i_normal.jpg)
[Link to Changeangel](https://changeangel.io)
Check their Twitter Page: [twitter.com/changeangel_io](https://twitter.com/changeangel_io)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/changeangel.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/changeangel.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/changeangel.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
