### ISSUE TITLE
Add 'AnimatedLab' to the 'GFX service / Design' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1876]
Requesting to add 'AnimatedLab' to the 'GFX service / Design' category. 

Details follow: 
```yml 
- name: AnimatedLab
  url: https://animatedlab.com/
  img: AnimatedLab.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to AnimatedLab](https://animatedlab.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/animatedlab.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/animatedlab.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/animatedlab.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
