### ISSUE TITLE
Add 'Smoke Emporium' to the 'Dry Herb Vaporizers' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1877]
Requesting to add 'Smoke Emporium' to the 'Dry Herb Vaporizers' category. 

Details follow: 
```yml 
- name: Smoke Emporium
  url: https://www.smokeemporium.com.au/
  img: SmokeEmporium.png
  bch: true
  btc: true
  othercrypto: true
  email_address: info@smokeemporium.com.au
  country: AU
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0199/1612/8356/files/Se-grey-mini-128.png?v=1598352358)
[Link to Smoke Emporium](https://www.smokeemporium.com.au/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.smokeemporium.com.au/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.smokeemporium.com.au/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.smokeemporium.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
