### ISSUE TITLE
Add 'OperaVPS' to the 'VPS Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1885]
Requesting to add 'OperaVPS' to the 'VPS Hosting' category. 

Details follow: 
```yml 
- name: OperaVPS
  url: https://operavps.com
  img: OperaVPS.png
  bch: true
  btc: true
  othercrypto: false
  twitter: operavps
  facebook: operavpslc
  email_address: support@operavps.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/operavps/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1294967228383756290/smo9cNi5_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/operavpslc/picture)
[Link to OperaVPS](https://operavps.com)
Check their Twitter Page: [twitter.com/operavps](https://twitter.com/operavps)
Check their Facebook Page: [fb.com/operavpslc](https://fb.com/operavpslc)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/operavps.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/operavps.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/operavps.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [operavps](https://twitter.com/operavps/), be sure to send out a tweet when this request has been added.
