### ISSUE TITLE
Requesting to add `http://member.cash/` to the `Social` category.

### ISSUE THREAD

**Issue by Real-FEELS** [acceptbitcoincash/acceptbitcoincash#1886]
Requesting to add http://member.cash/ to the Social category. Details follow:

```yml

- name: member.cash
  url: http://member.cash/
  img: https://raw.githubusercontent.com/memberapp/memberapp.github.io/master/img/membericon.svg
  bch: YES
  bsv: NO
  btc: NO
  othercrypto: NO
  doc: https://github.com/memberapp/memberapp.github.io
  keywords:
  - memo
  - twitter
  - member
```
