### ISSUE TITLE
Add 'kristof kaehler' to the 'memo.cash' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1889]
Requesting to add 'kristof kaehler' to the 'memo.cash' category. 

Details follow: 
```yml 
- name: kristof kaehler
  url: https://memo.cash/u/18t4sVHKqr
  img: kristofkaehler.png
  bch: true
  btc: true
  othercrypto: true
  facebook: kriskeahler
  email_address: baby636@outlook.de
  region: eu
  country: DE
  city: goslar
  exceptions:
    text: "https:/facebook.com/memo.cash/u/18t4sVHKqr"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://memo.cash/u/18t4sVHKqr)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/kriskeahler/picture)
[Link to kristof kaehler](https://memo.cash/u/18t4sVHKqr)
Check their Facebook Page: [fb.com/kriskeahler](https://fb.com/kriskeahler)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/memo.cash/u/18t4sVHKqr)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/memo.cash/u/18t4sVHKqr)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/memo.cash/u/18t4sVHKqr)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @baby636
Request made by Twitter user [baby636](https://twitter.com/baby636/), be sure to send out a tweet when this request has been added.
