### ISSUE TITLE
Add 'Buy RDP - Web Pundits' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1891]
Requesting to add 'Buy RDP - Web Pundits' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: Buy RDP - Web Pundits
  url: https://webpundits.in
  img: BuyRDPWebPundits.png
  bch: true
  btc: true
  othercrypto: true
  twitter: webpundits
  facebook: webpundits
  email_address: support@webpundits.in
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/649608540160569344/BrBY2UHL_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/webpundits/picture)
[Link to Buy RDP - Web Pundits](https://webpundits.in)
Check their Twitter Page: [twitter.com/webpundits](https://twitter.com/webpundits)
Check their Facebook Page: [fb.com/webpundits](https://fb.com/webpundits)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/webpundits.in)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/webpundits.in)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/webpundits.in)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [webpundits](https://twitter.com/webpundits/), be sure to send out a tweet when this request has been added.
