### ISSUE TITLE
Add 'Tragic Servers' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1894]
Requesting to add 'Tragic Servers' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: Tragic Servers
  url: https://tragicservers.com/
  img: TragicServers.png
  bch: true
  btc: true
  othercrypto: true
  twitter: tragicservers
  facebook: tragicservers
  doc: https://i.redd.it/vnbdjyhl9an51.png
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1068248457163337728/AnQibl-c_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1068248457163337728/AnQibl-c_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/tragicservers/picture)
[Link to Tragic Servers](https://tragicservers.com/)
Check their Twitter Page: [twitter.com/tragicservers](https://twitter.com/tragicservers)
Check their Facebook Page: [fb.com/tragicservers](https://fb.com/tragicservers)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/tragicservers.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/tragicservers.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/tragicservers.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
