### ISSUE TITLE
Add 'Lyra Hosting' to the 'Offshore Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1895]
Requesting to add 'Lyra Hosting' to the 'Offshore Hosting' category. 

Details follow: 
```yml 
- name: Lyra Hosting
  url: https://lyrahosting.com/
  img: LyraHosting.png
  bch: true
  btc: true
  othercrypto: true
  email_address: mirror@lyrahosting.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://lyrahosting.com/wp-content/uploads/2020/09/128px.png)
[Link to Lyra Hosting](https://lyrahosting.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/lyrahosting.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/lyrahosting.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/lyrahosting.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
