### ISSUE TITLE
Add 'BestBuyRDP' to the 'Web Hosting / VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1897]
Requesting to add 'BestBuyRDP' to the 'Web Hosting / VPS' category. 

Details follow: 
```yml 
- name: BestBuyRDP
  url: https://bestbuyrdp.com
  img: BestBuyRDP.png
  bch: true
  btc: true
  othercrypto: true
  email_address: bestbuyrdp@gmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://share.getcloudapp.com/bLuREppJ)
[Link to BestBuyRDP](https://bestbuyrdp.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bestbuyrdp.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bestbuyrdp.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bestbuyrdp.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
