### ISSUE TITLE
Add 'Punktid.ee' to the 'computer games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1900]
Requesting to add 'Punktid.ee' to the 'computer games' category. 

Details follow: 
```yml 
- name: Punktid.ee
  url: https://punktid.ee
  img: Punktidee.png
  bch: false
  btc: false
  othercrypto: false
  region: eu
```

Resources for adding this merchant:
[Link to Punktid.ee](https://punktid.ee)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/punktid.ee)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/punktid.ee)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/punktid.ee)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
