### ISSUE TITLE
Add 'Crypto Cove' to the 'Apparel & Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1904]
Requesting to add 'Crypto Cove' to the 'Apparel & Accessories' category. 

Details follow: 
```yml 
- name: Crypto Cove
  url: https://www.cryptocove.io
  img: CryptoCove.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cryptocove
  facebook: cryptocove
  email_address: info@cryptocove.io
  exceptions:
    text: "On front page the Bitcoin Cash Symbol. https://cryptocove.io/search?type=product&q=bitcoin+cash*"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0268/9705/5838/files/brandmark-design_44_300x.png?v=1601717660)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/934508269183422464/WYCFMOLo_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/cryptocove/picture)
[Link to Crypto Cove](https://www.cryptocove.io)
Check their Twitter Page: [twitter.com/cryptocove](https://twitter.com/cryptocove)
Check their Facebook Page: [fb.com/cryptocove](https://fb.com/cryptocove)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cryptocove.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cryptocove.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cryptocove.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
