### ISSUE TITLE
Add 'Free Ads' to the 'Classifieds' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1906]
Requesting to add 'Free Ads' to the 'Classifieds' category. 

Details follow: 
```yml 
- name: Free Ads
  url: https://www.freeads.cloud
  img: FreeAds.png
  bch: true
  btc: true
  othercrypto: true
  email_address: support@freeads.cloud
  region: oc
  country: AU
  exceptions:
    text: "Sellers will instruct buyers"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.linkpicture.com/q/090356667c7639d6735f99896208a2e2-32bits-256.png)
[Link to Free Ads](https://www.freeads.cloud)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.freeads.cloud)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.freeads.cloud)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.freeads.cloud)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
