### ISSUE TITLE
Add 'Smart Touch' to the 'Marketing ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1907]
Requesting to add 'Smart Touch' to the 'Marketing ' category. 

Details follow: 
```yml 
- name: Smart Touch
  url: https://www.smarttouch.me/
  img: SmartTouch.png
  bch: false
  btc: true
  othercrypto: true
  region: af
  country: BH
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.smarttouch.me/)
[Link to Smart Touch](https://www.smarttouch.me/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.smarttouch.me/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.smarttouch.me/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.smarttouch.me/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
