### ISSUE TITLE
Add 'Evolution Host' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1910]
Requesting to add 'Evolution Host' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: Evolution Host
  url: https://evolution-host.com/
  img: EvolutionHost.png
  bch: true
  btc: true
  othercrypto: true
  twitter: evohostin
  facebook: evolutionhosting
  email_address: business@evolution-host.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://evolution-host.com//images/logo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1183053071435419648/xZ7Pr5lu_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/evolutionhosting/picture)
[Link to Evolution Host](https://evolution-host.com/)
Check their Twitter Page: [twitter.com/evohostin](https://twitter.com/evohostin)
Check their Facebook Page: [fb.com/evolutionhosting](https://fb.com/evolutionhosting)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/evolution-host.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/evolution-host.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/evolution-host.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
