### ISSUE TITLE
Add 'Cheap Lightning' to the 'Games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1911]
Requesting to add 'Cheap Lightning' to the 'Games' category. 

Details follow: 
```yml 
- name: Cheap Lightning
  url: https://www.cheaplightning.com
  img: CheapLightning.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cheap_lightning
  email_address: sales@cheaplightning.com
  doc: https://www.cheaplightning.com/bitcoin/
  exceptions:
    text: "Just select it at checkout."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1176076066961551361/XaBm3Wgo_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1176076066961551361/XaBm3Wgo_normal.jpg)
[Link to Cheap Lightning](https://www.cheaplightning.com)
Check their Twitter Page: [twitter.com/cheap_lightning](https://twitter.com/cheap_lightning)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cheaplightning.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cheaplightning.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cheaplightning.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [cheaplightning](https://twitter.com/cheaplightning/), be sure to send out a tweet when this request has been added.
