### ISSUE TITLE
Add 'Rapidgator' to the 'Cloud Computing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1912]
Requesting to add 'Rapidgator' to the 'Cloud Computing' category. 

Details follow: 
```yml 
- name: Rapidgator
  url: https://rapidgator.net
  img: Rapidgator.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to Rapidgator](https://rapidgator.net)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/rapidgator.net)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/rapidgator.net)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/rapidgator.net)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
