### ISSUE TITLE
Add 'WpHostsell' to the 'Technology' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1913]
Requesting to add 'WpHostsell' to the 'Technology' category. 

Details follow: 
```yml 
- name: WpHostsell
  url: https://wphostsell.com/
  img: WpHostsell.png
  bch: false
  btc: false
  othercrypto: false
  facebook: belayethossain
  email_address: wphostsell3@gmail.com
  region: as
  country: BD
  city: Dhaka
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/belayethossain/picture)
[Link to WpHostsell](https://wphostsell.com/)
Check their Facebook Page: [fb.com/belayethossain](https://fb.com/belayethossain)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/wphostsell.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/wphostsell.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/wphostsell.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
