### ISSUE TITLE
Wallet Service

### ISSUE THREAD

**Issue by birdwatcher4life** [acceptbitcoincash/acceptbitcoincash#1915]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**site_name_here**}} to the {{**category_name_here**}} category. Details follow:

```yml

- name: Oxis
  url: https://www.oxis.com
  img: https://i.postimg.cc/1z28BkrF/oxis-wallet.png
  twitter: oxisdotcom
  facebook: 
  region: oc
  country: MH
  city: 
  bch: yes
  bsv: yes
  btc: yes
  othercrypto: yes
  doc: https://support.oxis.com/
  keywords:
  - wallet
  - bitcoin
```

Oxis also allows users to exchange cryptocurrency in-app.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
