### ISSUE TITLE
new BCH acceptance: borgbase

### ISSUE THREAD

**Issue by zander** [acceptbitcoincash/acceptbitcoincash#1916]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add borgbase.com to the Backup & Sync category. Details follow:

```yml

- name: borgbase.com
  url: https://www.borgbase.com/
  img: https://files.qmax.us/vorta/vorta-512px.png
  twitter: borg_base 
  facebook: 
  region: na, eu
  country: online
  city: online
  bch: yes
  bsv: no
  btc: yes
  othercrypto: yes
  doc: https://twitter.com/borg_base/status/1323864715450220544
  keywords:
  - borg
  - encrypted-backup
  - opensource
```

This uses coinbase commerce.

ps. logo comes from https://github.com/borgbase/vorta/
