### ISSUE TITLE
Add 'BITFERA' to the 'Bitcoins' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1917]
Requesting to add 'BITFERA' to the 'Bitcoins' category. 

Details follow: 
```yml 
- name: BITFERA
  url: https://bitfera.com/
  img: BITFERA.png
  bch: true
  btc: true
  othercrypto: true
  email_address: bitfera4cripto@gmail.com
  region: na
  country: US
```

Resources for adding this merchant:
[Link to BITFERA](https://bitfera.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitfera.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitfera.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitfera.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
