### ISSUE TITLE
Add 'KillStar' to the 'Fashion & Lifestyle' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1918]
Requesting to add 'KillStar' to the 'Fashion & Lifestyle' category. 

Details follow: 
```yml 
- name: KillStar
  url: https://killstar.com
  img: KillStar.png
  bch: true
  btc: true
  othercrypto: true
  twitter: killstar
  facebook: killstar
  email_address: customerservice@killstar.com
  exceptions:
    text: "Select Coinbase Commerce payment option during chekout"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/pic/profile_images%2F880057331534491648%2Fr8pUIabE.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/880057331534491648/r8pUIabE_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/killstar/picture)
[Link to KillStar](https://killstar.com)
Check their Twitter Page: [twitter.com/killstar](https://twitter.com/killstar)
Check their Facebook Page: [fb.com/killstar](https://fb.com/killstar)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/killstar.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/killstar.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/killstar.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
