### ISSUE TITLE
Add 'P2Gamer' to the 'Game key and service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1920]
Requesting to add 'P2Gamer' to the 'Game key and service' category. 

Details follow: 
```yml 
- name: P2Gamer
  url: https://www.p2gamer.com/
  img: PGamer.png
  bch: false
  btc: false
  othercrypto: false
  email_address: affiliate@p2gamer.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.p2gamer.com/wp-content/uploads/16/P2Gamer223logo.png)
[Link to P2Gamer](https://www.p2gamer.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.p2gamer.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.p2gamer.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.p2gamer.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
