### ISSUE TITLE
Add 'Satta' to the 'https' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1923]
Requesting to add 'Satta' to the 'https' category. 

Details follow: 
```yml 
- name: Satta
  url: https://bhiwadisatta.com
  img: Satta.png
  bch: true
  btc: true
  othercrypto: true
  email_address: mubarikhusain.k@gmail.com
  region: na
  country: CH
  city: Jdjd
```

Resources for adding this merchant:
[Link to Satta](https://bhiwadisatta.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bhiwadisatta.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bhiwadisatta.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bhiwadisatta.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
