### ISSUE TITLE
Add 'eloboostcrypto' to the 'League of legends boosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1925]
Requesting to add 'eloboostcrypto' to the 'League of legends boosting' category. 

Details follow: 
```yml 
- name: eloboostcrypto
  url: https://tufana7.wixsite.com/website
  img: eloboostcrypto.png
  bch: false
  btc: false
  othercrypto: false
  email_address: eloboostcrypto@gmail.com
```

Resources for adding this merchant:
[Link to eloboostcrypto](https://tufana7.wixsite.com/website)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/tufana7.wixsite.com/website)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/tufana7.wixsite.com/website)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/tufana7.wixsite.com/website)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
