### ISSUE TITLE
Add 'Coinremitter' to the 'Crypto Payment Gateway' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1926]
Requesting to add 'Coinremitter' to the 'Crypto Payment Gateway' category. 

Details follow: 
```yml 
- name: Coinremitter
  url: http://coinremitter.com/
  img: Coinremitter.png
  bch: true
  btc: true
  othercrypto: true
  twitter: coinremitter
  email_address: jm1gteam@gmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://coinremitter.com/assets/img/home-new/logo-black.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1180335034856656896/nLEb0smq_normal.jpg)
[Link to Coinremitter](http://coinremitter.com/)
Check their Twitter Page: [twitter.com/coinremitter](https://twitter.com/coinremitter)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/coinremitter.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/coinremitter.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/coinremitter.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
