### ISSUE TITLE
Add 'WebsiteCopier' to the 'Web Development' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1927]
Requesting to add 'WebsiteCopier' to the 'Web Development' category. 

Details follow: 
```yml 
- name: WebsiteCopier
  url: https://websitecopier.net/
  img: WebsiteCopier.png
  bch: true
  btc: true
  othercrypto: true
  facebook: websitecopiernet-100615131886619
  email_address: hello@websitecopier.net
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://websitecopier.net/assets/img/logowhite.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/websitecopiernet-100615131886619/picture)
[Link to WebsiteCopier](https://websitecopier.net/)
Check their Facebook Page: [fb.com/websitecopiernet-100615131886619](https://fb.com/websitecopiernet-100615131886619)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/websitecopier.net/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/websitecopier.net/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/websitecopier.net/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
