### ISSUE TITLE
Add 'Dundle' to the 'Gift cards' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1928]
Requesting to add 'Dundle' to the 'Gift cards' category. 

Details follow: 
```yml 
- name: Dundle
  url: https://dundle.com/
  img: Dundle.png
  bch: true
  btc: true
  othercrypto: true
  twitter: dundle_com
  facebook: dundlecom
  doc: https://www.reddit.com/r/btc/comments/k7tqmb/why_are_people_still_using_bitrefill_have_we_not/
  exceptions:
    text: "Choose "Bitcoin" as payment option and you'll be directed to Bitpay, where Bitcoin Cash wallets like Electron-Cash are accepted."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://dundle.com/resources/images/themes/logos/dundle.com/default-logo-new.svg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1232990175116001282/FkPTRxys_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/dundlecom/picture)
[Link to Dundle](https://dundle.com/)
Check their Twitter Page: [twitter.com/dundle_com](https://twitter.com/dundle_com)
Check their Facebook Page: [fb.com/dundlecom](https://fb.com/dundlecom)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/dundle.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/dundle.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/dundle.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
