### ISSUE TITLE
Add 'Lingeriehot.fr' to the 'Lingerie' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1929]
Requesting to add 'Lingeriehot.fr' to the 'Lingerie' category. 

Details follow: 
```yml 
- name: Lingeriehot.fr
  url: https://lingeriehot.fr/
  img: Lingeriehotfr.png
  bch: true
  btc: true
  othercrypto: true
  twitter: gerielinhot
  facebook: gerielinhot
  email_address: Contact@lingeriehot.fr
  region: eu
  country: FR
  city: camon
  exceptions:
    text: "non"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0074/4780/6003/files/lh2_280x.png?v=1606492999)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1235372045984247808/iRHsaIlZ_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/gerielinhot/picture)
[Link to Lingeriehot.fr](https://lingeriehot.fr/)
Check their Twitter Page: [twitter.com/gerielinhot](https://twitter.com/gerielinhot)
Check their Facebook Page: [fb.com/gerielinhot](https://fb.com/gerielinhot)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/lingeriehot.fr/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/lingeriehot.fr/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/lingeriehot.fr/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
