### ISSUE TITLE
Add 'Virtual Systems' to the 'Internet Service Provider' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1931]
Requesting to add 'Virtual Systems' to the 'Internet Service Provider' category. 

Details follow: 
```yml 
- name: Virtual Systems
  url: https://vsys.host
  img: VirtualSystems.png
  bch: true
  btc: true
  othercrypto: true
  twitter: vsyshost
  facebook: vsyshost
  email_address: lv@vsys.host
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://scontent.fiev22-1.fna.fbcdn.net/v/t1.0-9/104749633_4777167318991800_5947613884012666215_o.png?_nc_cat=108&ccb=2&_nc_sid=09cbfe&_nc_ohc=4omdzZdlyKYAX-bZOrh&_nc_ht=scontent.fiev22-1.fna&oh=3462edfd12ae33bcb6205d0c81d7b182&oe=5FF9C1D4)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1275417111960137729/uPkqw3yK_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/vsyshost/picture)
[Link to Virtual Systems](https://vsys.host)
Check their Twitter Page: [twitter.com/vsyshost](https://twitter.com/vsyshost)
Check their Facebook Page: [fb.com/vsyshost](https://fb.com/vsyshost)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/vsys.host)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/vsys.host)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/vsys.host)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [vsyshost](https://twitter.com/vsyshost/), be sure to send out a tweet when this request has been added.
