### ISSUE TITLE
Add 'Bitfortip | Tip Bitcoins as an incentive. Earn Bitcoins for being helpful.' to the 'Social network ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1932]
Requesting to add 'Bitfortip | Tip Bitcoins as an incentive. Earn Bitcoins for being helpful.' to the 'Social network ' category. 

Details follow: 
```yml 
- name: Bitfortip | Tip Bitcoins as an incentive. Earn Bitcoins for being helpful.
  url: https://www.bitfortip.com/
  img: BitfortipTipBitcoinsasanincentiveEarnBitcoinsforbeinghelpful.png
  bch: true
  btc: true
  othercrypto: true
  twitter: bitfortip
  email_address: contact@bitfortip.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.bitfortip.com/images/logo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1269641735463985154/G__jgRc1_normal.jpg)
[Link to Bitfortip | Tip Bitcoins as an incentive. Earn Bitcoins for being helpful.](https://www.bitfortip.com/)
Check their Twitter Page: [twitter.com/bitfortip](https://twitter.com/bitfortip)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.bitfortip.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.bitfortip.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.bitfortip.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
