### ISSUE TITLE
Add 'Probemas' to the 'E-commerce Store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1934]
Requesting to add 'Probemas' to the 'E-commerce Store' category. 

Details follow: 
```yml 
- name: Probemas
  url: https://probemas.com
  img: Probemas.png
  bch: true
  btc: false
  othercrypto: true
  twitter: probemas
  email_address: ben@probemas.com
  doc: https://probemas.com/blog/buy-rs-gold-with-bitcoin
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://probemas.com/static/images/webp/new_logo.webp)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1258298299343347712/XXNVoctF_normal.png)
[Link to Probemas](https://probemas.com)
Check their Twitter Page: [twitter.com/probemas](https://twitter.com/probemas)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/probemas.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/probemas.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/probemas.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [probemas](https://twitter.com/probemas/), be sure to send out a tweet when this request has been added.
