### ISSUE TITLE
Add 'Era of africa buisness' to the 'Food, p2p payment' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1935]
Requesting to add 'Era of africa buisness' to the 'Food, p2p payment' category. 

Details follow: 
```yml 
- name: Era of africa buisness
  url: https://memo.cash/profile/1qdhgmvgzafxtufa5XEdtV2aC76voUUMU
  img: Eraofafricabuisness.png
  bch: true
  btc: true
  othercrypto: true
  facebook: dzdt84
  email_address: cirtablockchain@gmail.com
  exceptions:
    text: "Yes AFC SLP token"
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/dzdt84/picture)
[Link to Era of africa buisness](https://memo.cash/profile/1qdhgmvgzafxtufa5XEdtV2aC76voUUMU)
Check their Facebook Page: [fb.com/dzdt84](https://fb.com/dzdt84)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/memo.cash/profile/1qdhgmvgzafxtufa5XEdtV2aC76voUUMU)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/memo.cash/profile/1qdhgmvgzafxtufa5XEdtV2aC76voUUMU)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/memo.cash/profile/1qdhgmvgzafxtufa5XEdtV2aC76voUUMU)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [mehdibm84331475](https://twitter.com/mehdibm84331475/), be sure to send out a tweet when this request has been added.
