### ISSUE TITLE
Add 'Beaugé Hypno' to the 'Santé' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1936]
Requesting to add 'Beaugé Hypno' to the 'Santé' category. 

Details follow: 
```yml 
- name: Beaugé Hypno
  url: https://beauge-hypno.com
  img: BeaugHypno.png
  bch: true
  btc: false
  othercrypto: true
  twitter: beaugeben
  facebook: beaugehypno
  email_address: beaugehypno@gmail.com
  region: eu
  country: FR
  doc: https://beauge-hypno.com/divers/bitcoin-et-cryptomonnaies-acceptees/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://beauge-hypno.com/wp-content/uploads/2019/08/favicon-ipad-retina.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1030363411119517696/X9J8s3NO_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/beaugehypno/picture)
[Link to Beaugé Hypno](https://beauge-hypno.com)
Check their Twitter Page: [twitter.com/beaugeben](https://twitter.com/beaugeben)
Check their Facebook Page: [fb.com/beaugehypno](https://fb.com/beaugehypno)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/beauge-hypno.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/beauge-hypno.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/beauge-hypno.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [beaugeben](https://twitter.com/beaugeben/), be sure to send out a tweet when this request has been added.
