### ISSUE TITLE
Add 'Jay Kirby Ties' to the 'Men's Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1938]
Requesting to add 'Jay Kirby Ties' to the 'Men's Accessories' category. 

Details follow: 
```yml 
- name: Jay Kirby Ties
  url: https://www.jaykirby.com.au
  img: JayKirbyTies.png
  bch: true
  btc: false
  othercrypto: true
  email_address: jaykirbyties@gmail.com
  country: AU
  city: Kew East
```

Resources for adding this merchant:
[Link to Jay Kirby Ties](https://www.jaykirby.com.au)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.jaykirby.com.au)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.jaykirby.com.au)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.jaykirby.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
