### ISSUE TITLE
Add 'WHMCS Global Services' to the 'WHMCS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1939]
Requesting to add 'WHMCS Global Services' to the 'WHMCS' category. 

Details follow: 
```yml 
- name: WHMCS Global Services
  url: https://whmcsglobalservices.com/
  img: WHMCSGlobalServices.png
  bch: false
  btc: true
  othercrypto: false
  twitter: infowgs
  facebook: whmcsglobalservices
  email_address: whmcsglobalservices1@gmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://whmcsglobalservices.com/wp-content/uploads/2017/11/logo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1088047575478034432/4aljvlzz_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/whmcsglobalservices/picture)
[Link to WHMCS Global Services](https://whmcsglobalservices.com/)
Check their Twitter Page: [twitter.com/infowgs](https://twitter.com/infowgs)
Check their Facebook Page: [fb.com/whmcsglobalservices](https://fb.com/whmcsglobalservices)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/whmcsglobalservices.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/whmcsglobalservices.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/whmcsglobalservices.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
