### ISSUE TITLE
Add 'BigBang' to the 'Electronics' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1940]
Requesting to add 'BigBang' to the 'Electronics' category. 

Details follow: 
```yml 
- name: BigBang
  url: https://www.bigbang.si/
  img: BigBang.png
  bch: true
  btc: true
  othercrypto: true
  region: eu
  country: SI
  exceptions:
    text: "BigBang uses GoCrypto payment processor"
```

Resources for adding this merchant:
[Link to BigBang](https://www.bigbang.si/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.bigbang.si/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.bigbang.si/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.bigbang.si/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
