### ISSUE TITLE
Add 'Toys4sex' to the 'Adult health' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1941]
Requesting to add 'Toys4sex' to the 'Adult health' category. 

Details follow: 
```yml 
- name: Toys4sex
  url: https://toys4sex.com.au
  img: Toyssex.png
  bch: true
  btc: true
  othercrypto: true
  email_address: sales@toys4sex.com.au
  country: AU
  doc: https://toys4sex.com.au/shipping-payment-methods-2/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://adultshop.b-cdn.net/wp-content/uploads/2018/12/512-51-t4slogo-300x300.png)
[Link to Toys4sex](https://toys4sex.com.au)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/toys4sex.com.au)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/toys4sex.com.au)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/toys4sex.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
