### ISSUE TITLE
Add 'SEOBetter' to the 'Online courses' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1942]
Requesting to add 'SEOBetter' to the 'Online courses' category. 

Details follow: 
```yml 
- name: SEOBetter
  url: https://seobetter.com/courses
  img: SEOBetter.png
  bch: true
  btc: true
  othercrypto: true
  facebook: seobetter1
  email_address: admin@seobetter.com
  doc: https://seobetter.com/terms-and-conditions/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://seobetter.b-cdn.net/wp-content/uploads/2020/01/cropped-seobetter-logo500x500-3.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/seobetter1/picture)
[Link to SEOBetter](https://seobetter.com/courses)
Check their Facebook Page: [fb.com/seobetter1](https://fb.com/seobetter1)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/seobetter.com/courses)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/seobetter.com/courses)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/seobetter.com/courses)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
