### ISSUE TITLE
Add 'Natural Pet Shop' to the 'Pets' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1943]
Requesting to add 'Natural Pet Shop' to the 'Pets' category. 

Details follow: 
```yml 
- name: Natural Pet Shop
  url: https://naturalpetshop.com.au
  img: NaturalPetShop.png
  bch: true
  btc: true
  othercrypto: true
  email_address: sales@naturalpetshop.com.au
  region: oc
  country: AU
  doc: https://naturalpetshop.com.au/about-the-natural-pet-shop/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://naturalpetshop.com.au)
[Link to Natural Pet Shop](https://naturalpetshop.com.au)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/naturalpetshop.com.au)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/naturalpetshop.com.au)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/naturalpetshop.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
