### ISSUE TITLE
Add 'Yesfuns' to the 'Fashion' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1945]
Requesting to add 'Yesfuns' to the 'Fashion' category. 

Details follow: 
```yml 
- name: Yesfuns
  url: HTTP://www.yesfuns.com
  img: Yesfuns.png
  bch: true
  btc: true
  othercrypto: true
  facebook: yesfunsjersey
  email_address: Marketing@yesfuns.com
  country: US
  city: no
  exceptions:
    text: "www.yesfuns.com"
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/yesfunsjersey/picture)
[Link to Yesfuns](HTTP://www.yesfuns.com)
Check their Facebook Page: [fb.com/yesfunsjersey](https://fb.com/yesfunsjersey)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/HTTP://www.yesfuns.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/HTTP://www.yesfuns.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/HTTP://www.yesfuns.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
