### ISSUE TITLE
Add 'Global Cannah' to the 'Alt. Medicine' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1946]
Requesting to add 'Global Cannah' to the 'Alt. Medicine' category. 

Details follow: 
```yml 
- name: Global Cannah
  url: https://cannah.net/en_US/
  img: GlobalCannah.png
  bch: true
  btc: true
  othercrypto: true
  facebook: globalcannah
  email_address: contact@cannah.net
  doc: https://old.reddit.com/r/btc/comments/kr0q2d/cbd_estore_for_europe_btc_eth_ltc_usdc_doge_trx/gi7ip8q/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cannah.net/wp-content/uploads/2020/03/79931308_2183533605276297_5516210709400125440_n.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/globalcannah/picture)
[Link to Global Cannah](https://cannah.net/en_US/)
Check their Facebook Page: [fb.com/globalcannah](https://fb.com/globalcannah)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cannah.net/en_US/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cannah.net/en_US/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cannah.net/en_US/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
