### ISSUE TITLE
Add 'Webhosting24' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1947]
Requesting to add 'Webhosting24' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: Webhosting24
  url: https://www.webhosting24.com/
  img: Webhosting.png
  bch: true
  btc: true
  othercrypto: true
  twitter: webhosting24
  facebook: webhosting24
  email_address: billing@webhosting24.com
  doc: https://www.webhosting24.com/cp/index.php?rp=/announcements/35/Cryptocurrency-update-now-accepting-BTC-BCH-ETC-LTH-XMR-DASH-DOGE-and-many-others.html
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/699650627832565760/FCsrvWUy_400x400.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/699650627832565760/FCsrvWUy_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/webhosting24/picture)
[Link to Webhosting24](https://www.webhosting24.com/)
Check their Twitter Page: [twitter.com/webhosting24](https://twitter.com/webhosting24)
Check their Facebook Page: [fb.com/webhosting24](https://fb.com/webhosting24)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.webhosting24.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.webhosting24.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.webhosting24.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [webhosting24](https://twitter.com/webhosting24/), be sure to send out a tweet when this request has been added.
