### ISSUE TITLE
Add 'instababe' to the 'adult (sexcam)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1948]
Requesting to add 'instababe' to the 'adult (sexcam)' category. 

Details follow: 
```yml 
- name: instababe
  url: https://instababe.fr
  img: instababe.png
  bch: true
  btc: false
  othercrypto: true
  twitter: babes_insta
  facebook: instabe.fr
  email_address: instababes.fr@gmail.com
  country: FR
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cams.images-dnxlive.com/whitelabel/logo/19629.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1323713379069054979/YGe5uE5m_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/instabe.fr/picture)
[Link to instababe](https://instababe.fr)
Check their Twitter Page: [twitter.com/babes_insta](https://twitter.com/babes_insta)
Check their Facebook Page: [fb.com/instabe.fr](https://fb.com/instabe.fr)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/instababe.fr)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/instababe.fr)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/instababe.fr)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
