### ISSUE TITLE
Add 'RW Studio' to the 'Art & Design' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1949]
Requesting to add 'RW Studio' to the 'Art & Design' category. 

Details follow: 
```yml 
- name: RW Studio
  url: http://www.ricoworl.com
  img: RWStudio.png
  bch: true
  btc: true
  othercrypto: true
  facebook: ricoworl
  email_address: rico.worl@gmail.com
  country: US
  city: Juneau
  exceptions:
    text: "www.ricoworl.com"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0054/6786/5186/files/logo_designing-05_360x.png?v=1538199200)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/ricoworl/picture)
[Link to RW Studio](http://www.ricoworl.com)
Check their Facebook Page: [fb.com/ricoworl](https://fb.com/ricoworl)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ricoworl.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ricoworl.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ricoworl.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
