### ISSUE TITLE
Add 'Jay Kirby' to the 'Men's Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1951]
Requesting to add 'Jay Kirby' to the 'Men's Accessories' category. 

Details follow: 
```yml 
- name: Jay Kirby
  url: https://www.jaykirby.com.au
  img: JayKirby.png
  bch: true
  btc: true
  othercrypto: true
  facebook: jay-kirby-101579448214279
  email_address: jaykirbyties@gmail.com
  country: AU
  exceptions:
    text: "www.jaykirby.com.au"
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/jay-kirby-101579448214279/picture)
[Link to Jay Kirby](https://www.jaykirby.com.au)
Check their Facebook Page: [fb.com/jay-kirby-101579448214279](https://fb.com/jay-kirby-101579448214279)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.jaykirby.com.au)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.jaykirby.com.au)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.jaykirby.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
