### ISSUE TITLE
Add 'parfumerie eternelle' to the 'Beauty and health' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1953]
Requesting to add 'parfumerie eternelle' to the 'Beauty and health' category. 

Details follow: 
```yml 
- name: parfumerie eternelle
  url: https://parfumerieeternelle.com/
  img: parfumerieeternelle.png
  bch: false
  btc: false
  othercrypto: true
  twitter: peternelle
  facebook: parfumerieeternelle
  email_address: parfumeireeternelle@gmail.com
  country: CA
  city: Laval
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0003/3406/9788/files/web-logo-new-01-6_800x_3b2fb257-87bd-491a-9ea5-9278e89df980_800x.png?v=1565034749)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/752702958886936576/xbAohPbF_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/parfumerieeternelle/picture)
[Link to parfumerie eternelle](https://parfumerieeternelle.com/)
Check their Twitter Page: [twitter.com/peternelle](https://twitter.com/peternelle)
Check their Facebook Page: [fb.com/parfumerieeternelle](https://fb.com/parfumerieeternelle)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/parfumerieeternelle.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/parfumerieeternelle.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/parfumerieeternelle.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
