### ISSUE TITLE
Crypto payment gateway, NOWPayments.io

### ISSUE THREAD

**Issue by artillar** [acceptbitcoincash/acceptbitcoincash#1955]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add **NOWPayments** to the **Payments** category. Details follow:

```yml

- name: NOWPayments
  url: https://nowpayments.io/
  img: https://nowpayments.io/images/logo/sharing_image.png
  twitter: NOWPayments_io
  facebook: NOWPayments.io
  region: af
  country: SC
  city: Mahe
  bch: yes
  bsv: yes
  btc: yes
  othercrypto: yes
  doc: https://nowpayments.io/supported-coins
  keywords:
  - crypto payment
  - payment gateway
```

NOWPayments is a cryptocurrency payment gateway that supports a wide variety of cryptocurrencies. The service is custody-free, has competitive fees, and is available worldwide.

– Over 50 cryptocurrencies are accepted on the platform with an in-built exchange feature;
– API, widgets, plugins and a donation button are all easy to integrate;
– It is a non-custodial service ensuring the security of your funds;
– A very simple setup.
