### ISSUE TITLE
Add 'buy gold bars' to the 'marketing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1958]
Requesting to add 'buy gold bars' to the 'marketing' category. 

Details follow: 
```yml 
- name: buy gold bars
  url: https://buygoldbars.xyz
  img: buygoldbars.png
  bch: true
  btc: true
  othercrypto: true
  email_address: sales@buygoldbars.xyz
  country: CA
  city: toronto
```

Resources for adding this merchant:
[Link to buy gold bars](https://buygoldbars.xyz)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/buygoldbars.xyz)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/buygoldbars.xyz)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/buygoldbars.xyz)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
