### ISSUE TITLE
Add 'Obscure belts' to the 'Leather goods' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1959]
Requesting to add 'Obscure belts' to the 'Leather goods' category. 

Details follow: 
```yml 
- name: Obscure belts
  url: https://www.obscurebelts.com/
  img: Obscurebelts.png
  bch: true
  btc: true
  othercrypto: true
  twitter: obscurebelts
  facebook: obscurebelts
  email_address: info@obscurebelts.com
  region: na
  country: US
  city: no
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/obscurebelts/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/573322013130932224/1tC0yiVS_normal.jpeg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/obscurebelts/picture)
[Link to Obscure belts](https://www.obscurebelts.com/)
Check their Twitter Page: [twitter.com/obscurebelts](https://twitter.com/obscurebelts)
Check their Facebook Page: [fb.com/obscurebelts](https://fb.com/obscurebelts)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.obscurebelts.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.obscurebelts.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.obscurebelts.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
