### ISSUE TITLE
Add 'SplicePackage' to the 'Package Forwarding' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1960]
Requesting to add 'SplicePackage' to the 'Package Forwarding' category. 

Details follow: 
```yml 
- name: SplicePackage
  url: https://splicepackages.com/
  img: SplicePackage.png
  bch: false
  btc: false
  othercrypto: true
```

Resources for adding this merchant:
[Link to SplicePackage](https://splicepackages.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/splicepackages.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/splicepackages.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/splicepackages.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
