### ISSUE TITLE
Add 'Plugin Fox' to the 'Music/Audio production' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1962]
Requesting to add 'Plugin Fox' to the 'Music/Audio production' category. 

Details follow: 
```yml 
- name: Plugin Fox
  url: https://pluginfox.co/
  img: PluginFox.png
  bch: true
  btc: true
  othercrypto: true
  twitter: pluginfox
  facebook: pluginfox
  email_address: support@pluginfox.co
  exceptions:
    text: "Select BitPay at checkout"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/udFxSOf.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1149674619684708353/0jnBDyTB_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/pluginfox/picture)
[Link to Plugin Fox](https://pluginfox.co/)
Check their Twitter Page: [twitter.com/pluginfox](https://twitter.com/pluginfox)
Check their Facebook Page: [fb.com/pluginfox](https://fb.com/pluginfox)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/pluginfox.co/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/pluginfox.co/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/pluginfox.co/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
