### ISSUE TITLE
Add 'Veteran Vlogger' to the 'Vlogging Accessories. Entertainment. Video Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1963]
Requesting to add 'Veteran Vlogger' to the 'Vlogging Accessories. Entertainment. Video Accessories' category. 

Details follow: 
```yml 
- name: Veteran Vlogger
  url: https://veteranvlogger.com/
  img: VeteranVlogger.png
  bch: true
  btc: true
  othercrypto: true
  facebook: veteran-vlogger-104678878235185
  email_address: info@100kinvesting.com
  country: US
  doc: https://veteranvlogger.com/pages/faqs under payment methods
  exceptions:
    text: "They place their order, provide the shipping, and then use Coin Payments gateway to process the order."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0521/7216/1200/files/logo_200x.png?v=1609510654)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/veteran-vlogger-104678878235185/picture)
[Link to Veteran Vlogger](https://veteranvlogger.com/)
Check their Facebook Page: [fb.com/veteran-vlogger-104678878235185](https://fb.com/veteran-vlogger-104678878235185)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/veteranvlogger.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/veteranvlogger.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/veteranvlogger.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
