### ISSUE TITLE
Add 'Lightpost Winery' to the 'wine' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1964]
Requesting to add 'Lightpost Winery' to the 'wine' category. 

Details follow: 
```yml 
- name: Lightpost Winery
  url: https://www.lightpostwinery.com/Cryptocurrency-test
  img: LightpostWinery.png
  bch: true
  btc: false
  othercrypto: true
  email_address: info@lightpostwinery.com
  region: na
  country: US
```

Resources for adding this merchant:
[Link to Lightpost Winery](https://www.lightpostwinery.com/Cryptocurrency-test)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.lightpostwinery.com/Cryptocurrency-test)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.lightpostwinery.com/Cryptocurrency-test)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.lightpostwinery.com/Cryptocurrency-test)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
