### ISSUE TITLE
Add 'Bookies' to the 'Business' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1965]
Requesting to add 'Bookies' to the 'Business' category. 

Details follow: 
```yml 
- name: Bookies
  url: https://store21.sumup.link
  img: Bookies.png
  bch: true
  btc: true
  othercrypto: true
  email_address: dubble0d@gmail.com
  country: VG
  city: Walsall
  exceptions:
    text: "bitcoincash:qpyvtlg5wy89d9gxky2cpt7wd0563rrr9udrc7r3lg"
```

Resources for adding this merchant:
[Link to Bookies](https://store21.sumup.link)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/store21.sumup.link)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/store21.sumup.link)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/store21.sumup.link)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @dubble0d
Request made by Twitter user [dubble0d](https://twitter.com/dubble0d/), be sure to send out a tweet when this request has been added.
