### ISSUE TITLE
Add 'krise636' to the 'bchd-bch-btc' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1966]
Requesting to add 'krise636' to the 'bchd-bch-btc' category. 

Details follow: 
```yml 
- name: krise636
  url: https://memo.cash/u/18t4sVHKqr
  img: krise.png
  bch: true
  btc: true
  othercrypto: true
  twitter: krise636
  facebook: memo.cash18t4svhkqr
  email_address: baby636@outlook.de
  region: eu
  country: DE
  city: Goslar
  exceptions:
    text: "qpt8z56sjcng8eux4pgvl7msnns2fzj05st7gytwm3"
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1334000055209111553/uxYXwBEf_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/memo.cash18t4svhkqr/picture)
[Link to krise636](https://memo.cash/u/18t4sVHKqr)
Check their Twitter Page: [twitter.com/krise636](https://twitter.com/krise636)
Check their Facebook Page: [fb.com/memo.cash18t4svhkqr](https://fb.com/memo.cash18t4svhkqr)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/memo.cash/u/18t4sVHKqr)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/memo.cash/u/18t4sVHKqr)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/memo.cash/u/18t4sVHKqr)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @baby636
Request made by Twitter user [krise636](https://twitter.com/krise636/), be sure to send out a tweet when this request has been added.
