### ISSUE TITLE
Add 'Liberty Smoke & Vapor' to the 'glass pipes' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1967]
Requesting to add 'Liberty Smoke & Vapor' to the 'glass pipes' category. 

Details follow: 
```yml 
- name: Liberty Smoke & Vapor
  url: http://rollingpapers.com
  img: LibertySmokeVapor.png
  bch: true
  btc: false
  othercrypto: true
  email_address: paperspro@gmail.com
  region: na
  country: US
  city: SPOKANE
```

Resources for adding this merchant:
[Link to Liberty Smoke & Vapor](http://rollingpapers.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/rollingpapers.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/rollingpapers.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/rollingpapers.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @libertysmoke&vapor
