### ISSUE TITLE
Add 'Snowboard Shop' to the 'Winter Sports' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1968]
Requesting to add 'Snowboard Shop' to the 'Winter Sports' category. 

Details follow: 
```yml 
- name: Snowboard Shop
  url: http://rollingpapers.com
  img: SnowboardShop.png
  bch: true
  btc: false
  othercrypto: true
  region: na
```

Resources for adding this merchant:
[Link to Snowboard Shop](http://rollingpapers.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/rollingpapers.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/rollingpapers.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/rollingpapers.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
