### ISSUE TITLE
Add 'certificate of web site is expired' to the 'certificate of web site is expired ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1969]
Requesting to add 'certificate of web site is expired' to the 'certificate of web site is expired ' category. 

Details follow: 
```yml 
- name: certificate of web site is expired
  url: https://acceptbitcoin.cash
  img: certificateofwebsiteisexpired.png
  bch: true
  btc: false
  othercrypto: false
  email_address: unknown@acceptbitcoin.cash
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://acceptbitcoin.cash)
[Link to certificate of web site is expired](https://acceptbitcoin.cash)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/acceptbitcoin.cash)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/acceptbitcoin.cash)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/acceptbitcoin.cash)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
