### ISSUE TITLE
Add 'BoostUpvotes' to the 'Marketing services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1970]
Requesting to add 'BoostUpvotes' to the 'Marketing services' category. 

Details follow: 
```yml 
- name: BoostUpvotes
  url: https://boostupvotes.com
  img: BoostUpvotes.png
  bch: true
  btc: true
  othercrypto: true
  twitter: boostupvotes
  email_address: support@boostupvotes.com
  exceptions:
    text: "No, built in at checkout."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://boostupvotes.com/wp-content/uploads/2020/10/cropped-Group-11.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/937170007993315329/NYKVrNxX_normal.jpg)
[Link to BoostUpvotes](https://boostupvotes.com)
Check their Twitter Page: [twitter.com/boostupvotes](https://twitter.com/boostupvotes)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/boostupvotes.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/boostupvotes.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/boostupvotes.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
