### ISSUE TITLE
Add 'Pono T-shirts' to the 'casual wear' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1971]
Requesting to add 'Pono T-shirts' to the 'casual wear' category. 

Details follow: 
```yml 
- name: Pono T-shirts
  url: https://ponotshirts.com
  img: PonoTshirts.png
  bch: true
  btc: true
  othercrypto: false
  facebook: n/a
  email_address: admin@ponotshirts.com
  doc: https://i0.wp.com/ponotshirts.com/wp-content/uploads/2021/01/Btc-bch.png?resize=416%2C200&ssl=1
  exceptions:
    text: "checkout and pick BCH or BTC"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i1.wp.com/ponotshirts.com/wp-content/uploads/2020/12/cropped-logo3.png?w=492&ssl=1)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/n/a/picture)
[Link to Pono T-shirts](https://ponotshirts.com)
Check their Facebook Page: [fb.com/n/a](https://fb.com/n/a)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/ponotshirts.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/ponotshirts.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/ponotshirts.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
