### ISSUE TITLE
Add 'Jamones Sin Fronteras' to the 'Gourmet Online Store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1973]
Requesting to add 'Jamones Sin Fronteras' to the 'Gourmet Online Store' category. 

Details follow: 
```yml 
- name: Jamones Sin Fronteras
  url: https://www.jamonessinfronteras.com
  img: JamonesSinFronteras.png
  bch: true
  btc: false
  othercrypto: true
  twitter: jamonessinf
  facebook: jamonessinf
  email_address: info@jamonessinfronteras.com
  region: na
  country: US
  city: Nationwide 
  exceptions:
    text: "Website purchase"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.jamonessinfronteras.com/wp-content/uploads/2016/10/LogoFacturas.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/663845744802185216/EChWA_iP_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/jamonessinf/picture)
[Link to Jamones Sin Fronteras](https://www.jamonessinfronteras.com)
Check their Twitter Page: [twitter.com/jamonessinf](https://twitter.com/jamonessinf)
Check their Facebook Page: [fb.com/jamonessinf](https://fb.com/jamonessinf)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.jamonessinfronteras.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.jamonessinfronteras.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.jamonessinfronteras.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @jamonessinfronteras
