### ISSUE TITLE
Add 'SwapSwop' to the 'Exchange platform' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1976]
Requesting to add 'SwapSwop' to the 'Exchange platform' category. 

Details follow: 
```yml 
- name: SwapSwop
  url: https://swapswop.io/
  img: SwapSwop.png
  bch: true
  btc: false
  othercrypto: true
  twitter: swapswopio
  facebook: swapswopio
  email_address: henlo@swapswop.io
  doc: https://twitter.com/swapswopio/status/1363098950220316672
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://api.swapswop.io/static/white_bg_128128.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1361981602230906883/QFx_-kHj_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/swapswopio/picture)
[Link to SwapSwop](https://swapswop.io/)
Check their Twitter Page: [twitter.com/swapswopio](https://twitter.com/swapswopio)
Check their Facebook Page: [fb.com/swapswopio](https://fb.com/swapswopio)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/swapswop.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/swapswop.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/swapswop.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [swapswopio](https://twitter.com/swapswopio/), be sure to send out a tweet when this request has been added.
