### ISSUE TITLE
Add 'Via Design Ltd' to the 'Design' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1977]
Requesting to add 'Via Design Ltd' to the 'Design' category. 

Details follow: 
```yml 
- name: Via Design Ltd
  url: https://www.viadesign.co.nz/
  img: ViaDesignLtd.png
  bch: true
  btc: true
  othercrypto: true
  email_address: dean@viadesign.co.nz
  region: oc
  country: NZ
```

Resources for adding this merchant:
[Link to Via Design Ltd](https://www.viadesign.co.nz/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.viadesign.co.nz/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.viadesign.co.nz/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.viadesign.co.nz/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [drmepaaec](https://twitter.com/drmepaaec/), be sure to send out a tweet when this request has been added.
