### ISSUE TITLE
Add 'SALLY SOKLAY NGIM' to the 'GOOGLE.COM' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1978]
Requesting to add 'SALLY SOKLAY NGIM' to the 'GOOGLE.COM' category. 

Details follow: 
```yml 
- name: SALLY SOKLAY NGIM
  url: https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:d5183871-27c8-499c-a94e-e3b6f486aa29
  img: SALLYSOKLAYNGIM.png
  bch: true
  btc: true
  othercrypto: true
  twitter: ngim_sally
  facebook: advertistingyoutube'sgoogledevelopers
  email_address: nsallysoklay@gmail.com
  country: US
  city: STOCKTON
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:d5183871-27c8-499c-a94e-e3b6f486aa29)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1361643313397334018/R4Yf0ACi_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/advertistingyoutube'sgoogledevelopers/picture)
[Link to SALLY SOKLAY NGIM](https://documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:d5183871-27c8-499c-a94e-e3b6f486aa29)
Check their Twitter Page: [twitter.com/ngim_sally](https://twitter.com/ngim_sally)
Check their Facebook Page: [fb.com/advertistingyoutube'sgoogledevelopers](https://fb.com/advertistingyoutube'sgoogledevelopers)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:d5183871-27c8-499c-a94e-e3b6f486aa29)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:d5183871-27c8-499c-a94e-e3b6f486aa29)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/documentcloud.adobe.com/link/review?uri=urn:aaid:scds:US:d5183871-27c8-499c-a94e-e3b6f486aa29)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @sallysoklayngim
Request made by Twitter user [ngim_sallyngimstagram](https://twitter.com/ngim_sallyngimstagram/), be sure to send out a tweet when this request has been added.
