### ISSUE TITLE
Add 'Auto Coin Cars' to the 'Automotive ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1981]
Requesting to add 'Auto Coin Cars' to the 'Automotive ' category. 

Details follow: 
```yml 
- name: Auto Coin Cars
  url: https://www.autocoincars.com
  img: AutoCoinCars.png
  bch: true
  btc: true
  othercrypto: true
  twitter: autocoincars
  email_address: info@autocoincars.com
  region: eu
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1200288646999490560/198CHLpe_normal.jpg)
[Link to Auto Coin Cars](https://www.autocoincars.com)
Check their Twitter Page: [twitter.com/autocoincars](https://twitter.com/autocoincars)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.autocoincars.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.autocoincars.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.autocoincars.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
