### ISSUE TITLE
Add 'windguru.com' to the 'Wind Forcast' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1982]
Requesting to add 'windguru.com' to the 'Wind Forcast' category. 

Details follow: 
```yml 
- name: windguru.com
  url: https://www.windguru.cz/
  img: windgurucom.png
  bch: true
  btc: true
  othercrypto: true
  email_address: vhornik@seznam.cz
```

Resources for adding this merchant:
[Link to windguru.com](https://www.windguru.cz/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.windguru.cz/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.windguru.cz/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.windguru.cz/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
