### ISSUE TITLE
Add '33mail' to the 'Communication, Utilities' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1983]
Requesting to add '33mail' to the 'Communication, Utilities' category. 

Details follow: 
```yml 
- name: 33mail
  url: https://www.33mail.com/
  img: mail.png
  bch: true
  btc: true
  othercrypto: true
  twitter: 33mail
  email_address: support@33mail.com
  exceptions:
    text: "Register free account first, email support@33mail.com for BCH address and advise once paid for Pro account"
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1273424807/nospam_normal.png)
[Link to 33mail](https://www.33mail.com/)
Check their Twitter Page: [twitter.com/33mail](https://twitter.com/33mail)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.33mail.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.33mail.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.33mail.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @mixchad
