### ISSUE TITLE
Add 'Salmon ETC' to the 'Fresh and Canned Fish' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1984]
Requesting to add 'Salmon ETC' to the 'Fresh and Canned Fish' category. 

Details follow: 
```yml 
- name: Salmon ETC
  url: https://salmonetc.com
  img: SalmonETC.png
  bch: true
  btc: false
  othercrypto: true
  facebook: salmonetcfirstcity
  email_address: admin@salmonetc.com
  region: na
  country: US
  city: No
  exceptions:
    text: "Place order and email"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://salmonetc.com/wp-content/uploads/2020/04/gfx_web-logo_2020-01-530x189.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/salmonetcfirstcity/picture)
[Link to Salmon ETC](https://salmonetc.com)
Check their Facebook Page: [fb.com/salmonetcfirstcity](https://fb.com/salmonetcfirstcity)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/salmonetc.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/salmonetc.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/salmonetc.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
