### ISSUE TITLE
Add 'Nootropix UAE' to the 'Dietary Supplement' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1985]
Requesting to add 'Nootropix UAE' to the 'Dietary Supplement' category. 

Details follow: 
```yml 
- name: Nootropix UAE
  url: https://nootropix.shop
  img: NootropixUAE.png
  bch: true
  btc: true
  othercrypto: true
  twitter: nootropix_info
  facebook: nootropix.shop
  email_address: support@nootropix.shop
  region: as
  country: AE
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.nootropix.shop/wp-content/uploads/2021/03/Nootropix-UAE-Logo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1144713449303420929/Wqe3PUjy_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/nootropix.shop/picture)
[Link to Nootropix UAE](https://nootropix.shop)
Check their Twitter Page: [twitter.com/nootropix_info](https://twitter.com/nootropix_info)
Check their Facebook Page: [fb.com/nootropix.shop](https://fb.com/nootropix.shop)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/nootropix.shop)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/nootropix.shop)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/nootropix.shop)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @alalimoe
Request made by Twitter user [fymo_oe](https://twitter.com/fymo_oe/), be sure to send out a tweet when this request has been added.
