### ISSUE TITLE
Add 'Tail Treasures' to the 'Custom Pet Products' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1986]
Requesting to add 'Tail Treasures' to the 'Custom Pet Products' category. 

Details follow: 
```yml 
- name: Tail Treasures
  url: https://tailtreasures.com
  img: TailTreasures.png
  bch: true
  btc: true
  othercrypto: true
  facebook: tailtreasuresstore
  email_address: support@tailtreasures.com
  region: na
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0318/8506/6380/files/Tail_Treasures_Logo_1200x370_7083c605-b00f-4cd2-8c02-00d7cc24b3de_180x.png?v=1610151176)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/tailtreasuresstore/picture)
[Link to Tail Treasures](https://tailtreasures.com)
Check their Facebook Page: [fb.com/tailtreasuresstore](https://fb.com/tailtreasuresstore)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/tailtreasures.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/tailtreasures.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/tailtreasures.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @mikeytag
