### ISSUE TITLE
Add 'letsolar' to the 'New energy' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1987]
Requesting to add 'letsolar' to the 'New energy' category. 

Details follow: 
```yml 
- name: letsolar
  url: https://www.letsolar.com
  img: letsolar.png
  bch: true
  btc: true
  othercrypto: true
  email_address: 787315618@qq.com
  country: CN
  city: GuangDong ShenZhen
```

Resources for adding this merchant:
[Link to letsolar](https://www.letsolar.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.letsolar.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.letsolar.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.letsolar.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
