### ISSUE TITLE
Add 'Sail Old San Juan' to the 'Travel Tourism' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1989]
Requesting to add 'Sail Old San Juan' to the 'Travel Tourism' category. 

Details follow: 
```yml 
- name: Sail Old San Juan
  url: https://sailoldsanjuan.com/
  img: SailOldSanJuan.png
  bch: true
  btc: true
  othercrypto: true
  facebook: sailoldsanjuan
  email_address: reserve@sailoldsanjuan.com
  region: na
  country: PR
  city: San Juan
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/sailoldsanjuan/picture)
[Link to Sail Old San Juan](https://sailoldsanjuan.com/)
Check their Facebook Page: [fb.com/sailoldsanjuan](https://fb.com/sailoldsanjuan)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/sailoldsanjuan.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/sailoldsanjuan.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/sailoldsanjuan.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
