### ISSUE TITLE
Add 'Delidakis & Associates P.C.' to the 'Accounting - Tax' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1990]
Requesting to add 'Delidakis & Associates P.C.' to the 'Accounting - Tax' category. 

Details follow: 
```yml 
- name: Delidakis & Associates P.C.
  url: https://www.delidakis.com
  img: DelidakisAssociatesPC.png
  bch: true
  btc: true
  othercrypto: true
  email_address: finance@delidakis.com
  region: eu
```

Resources for adding this merchant:
[Link to Delidakis & Associates P.C.](https://www.delidakis.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.delidakis.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.delidakis.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.delidakis.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
