### ISSUE TITLE
Add 'Freeward' to the 'Reward app' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1991]
Requesting to add 'Freeward' to the 'Reward app' category. 

Details follow: 
```yml 
- name: Freeward
  url: https://freeward.net
  img: Freeward.png
  bch: true
  btc: true
  othercrypto: true
  facebook: freewardofficial
  email_address: support@freeward.net
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/freewardofficial/picture)
[Link to Freeward](https://freeward.net)
Check their Facebook Page: [fb.com/freewardofficial](https://fb.com/freewardofficial)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/freeward.net)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/freeward.net)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/freeward.net)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
