### ISSUE TITLE
Add 'necati kara' to the 'bitcoin' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1992]
Requesting to add 'necati kara' to the 'bitcoin' category. 

Details follow: 
```yml 
- name: necati kara
  url: https://www.ometv.de
  img: necatikara.png
  bch: true
  btc: false
  othercrypto: false
  region: as
  country: AM
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.ometv.de/okcupid/)
[Link to necati kara](https://www.ometv.de)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ometv.de)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ometv.de)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ometv.de)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
