### ISSUE TITLE
Add 'Crypto for the Homeless' to the 'donations: human rights' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1993]
Requesting to add 'Crypto for the Homeless' to the 'donations: human rights' category. 

Details follow: 
```yml 
- name: Crypto for the Homeless
  url: http://www.cryptoforthehomeless.org
  img: CryptofortheHomeless.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cryptofthl
  facebook: cryptofthl
  email_address: cryptofthl@gmail.com
  region: na
  country: US
  city: No
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/cilsXcL.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1247991755447787520/rEe9RYp-_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/cryptofthl/picture)
[Link to Crypto for the Homeless](http://www.cryptoforthehomeless.org)
Check their Twitter Page: [twitter.com/cryptofthl](https://twitter.com/cryptofthl)
Check their Facebook Page: [fb.com/cryptofthl](https://fb.com/cryptofthl)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cryptoforthehomeless.org)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cryptoforthehomeless.org)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cryptoforthehomeless.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
