### ISSUE TITLE
Add 'Prompt.Cash' to the 'Payment Processor' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1995]
Requesting to add 'Prompt.Cash' to the 'Payment Processor' category. 

Details follow: 
```yml 
- name: Prompt.Cash
  url: https://prompt.cash/
  img: PromptCash.png
  bch: true
  btc: false
  othercrypto: false
  twitter: cashprompt
  doc: https://news.bitcoin.com/developers-launch-first-hosted-noncustodial-payment-processor-bitcoin-cash/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cashtippr.com/wp-content/uploads/2021/04/logo_128.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1351940257516720129/ZiEcbt9t_normal.jpg)
[Link to Prompt.Cash](https://prompt.cash/)
Check their Twitter Page: [twitter.com/cashprompt](https://twitter.com/cashprompt)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/prompt.cash/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/prompt.cash/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/prompt.cash/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @prompt-cash
Request made by Twitter user [ekliptor](https://twitter.com/ekliptor/), be sure to send out a tweet when this request has been added.
