### ISSUE TITLE
Add 'TOY SNOWMAN' to the 'Toy store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1996]
Requesting to add 'TOY SNOWMAN' to the 'Toy store' category. 

Details follow: 
```yml 
- name: TOY SNOWMAN
  url: https://toysnowman.com/
  img: TOYSNOWMAN.png
  bch: true
  btc: true
  othercrypto: true
  facebook: toysnowman
  email_address: amir@toysnowman.com
  region: na
  country: CA
  doc: https://toysnowman.com/blogs/news/toy-snowman-now-accepts-bitcoin-payments
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/toysnowman/picture)
[Link to TOY SNOWMAN](https://toysnowman.com/)
Check their Facebook Page: [fb.com/toysnowman](https://fb.com/toysnowman)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/toysnowman.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/toysnowman.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/toysnowman.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
