### ISSUE TITLE
Add 'Kozmodans' to the 'Blog' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1998]
Requesting to add 'Kozmodans' to the 'Blog' category. 

Details follow: 
```yml 
- name: Kozmodans
  url: https://www.kozmodans.com
  img: Kozmodans.png
  bch: true
  btc: false
  othercrypto: false
  twitter: kozmodans
  email_address: iletisim@kozmodans.com
  region: eu
  exceptions:
    text: "We accept Bitcoin Cash for Sessions"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.kozmodans.com/wp-content/uploads/2019/08/Kozmodans-logo-ince-uzun.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1311852753518551042/FcOgrTgl_normal.jpg)
[Link to Kozmodans](https://www.kozmodans.com)
Check their Twitter Page: [twitter.com/kozmodans](https://twitter.com/kozmodans)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.kozmodans.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.kozmodans.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.kozmodans.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
