### ISSUE TITLE
Add 'The Code Fish' to the 'Software Developer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1999]
Requesting to add 'The Code Fish' to the 'Software Developer' category. 

Details follow: 
```yml 
- name: The Code Fish
  url: https://codecanyon.net/user/thecodefish/portfolio
  img: TheCodeFish.png
  bch: true
  btc: true
  othercrypto: true
  twitter: thecodefish1
  email_address: robertrich320@gmail.com
  region: na
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://s3.envato.com/files/315829004/Icon%2080x80.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1371833417894072320/DrmV1T0B_normal.jpg)
[Link to The Code Fish](https://codecanyon.net/user/thecodefish/portfolio)
Check their Twitter Page: [twitter.com/thecodefish1](https://twitter.com/thecodefish1)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/codecanyon.net/user/thecodefish/portfolio)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/codecanyon.net/user/thecodefish/portfolio)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/codecanyon.net/user/thecodefish/portfolio)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
