### ISSUE TITLE
Add 'Crypto Degens' to the 'Bitcoin' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2001]
Requesting to add 'Crypto Degens' to the 'Bitcoin' category. 

Details follow: 
```yml 
- name: Crypto Degens
  url: https://bc.game/
  img: CryptoDegens.png
  bch: true
  btc: true
  othercrypto: true
  country: US
```

Resources for adding this merchant:
[Link to Crypto Degens](https://bc.game/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bc.game/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bc.game/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bc.game/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
