### ISSUE TITLE
Add 'Devil Daves Bloody Mary Seasoning' to the 'Food & Drink' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2004]
Requesting to add 'Devil Daves Bloody Mary Seasoning' to the 'Food & Drink' category. 

Details follow: 
```yml 
- name: Devil Daves Bloody Mary Seasoning
  url: https://devildaves.com
  img: DevilDavesBloodyMarySeasoning.png
  bch: true
  btc: false
  othercrypto: true
  twitter: devil_davesbm
  facebook: devildavesbloodymary
  email_address: contact@devildaves.com
  region: na
  country: US
  exceptions:
    text: "Normal checkout on a Shopify Platform"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/SmHjXol.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1247297127300173824/e71Cj1-C_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/devildavesbloodymary/picture)
[Link to Devil Daves Bloody Mary Seasoning](https://devildaves.com)
Check their Twitter Page: [twitter.com/devil_davesbm](https://twitter.com/devil_davesbm)
Check their Facebook Page: [fb.com/devildavesbloodymary](https://fb.com/devildavesbloodymary)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/devildaves.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/devildaves.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/devildaves.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
