### ISSUE TITLE
Add 'Bitvape' to the 'Tobacco & Vapes' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2006]
Requesting to add 'Bitvape' to the 'Tobacco & Vapes' category. 

Details follow: 
```yml 
- name: Bitvape
  url: https://bitvape.com.au
  img: Bitvape.png
  bch: true
  btc: true
  othercrypto: true
  email_address: admin@bitvape.com.au
  region: oc
  country: AU
  doc: https://bitvape.com.au/we-are-now-accepting-bitcoin-cash-bch/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/qRL1p67.png)
[Link to Bitvape](https://bitvape.com.au)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitvape.com.au)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitvape.com.au)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitvape.com.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
