### ISSUE TITLE
Add 'Cart&Pod' to the 'Vape Supplies' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2007]
Requesting to add 'Cart&Pod' to the 'Vape Supplies' category. 

Details follow: 
```yml 
- name: Cart&Pod
  url: https://cartandpod.com
  img: CartPod.png
  bch: true
  btc: false
  othercrypto: false
  twitter: johnbrowncanna
  email_address: info@cartandpod.com
  doc: https://www.reddit.com/r/btc/comments/mwjex2/cartandpodcom_now_takes_crypto_only_the_real/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cartandpod.com/)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1381706802383912960/S_ubN5ar_normal.jpg)
[Link to Cart&Pod](https://cartandpod.com)
Check their Twitter Page: [twitter.com/johnbrowncanna](https://twitter.com/johnbrowncanna)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cartandpod.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cartandpod.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cartandpod.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
