### ISSUE TITLE
Add 'Midnight Oasis' to the 'Retail Smoke Shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2009]
Requesting to add 'Midnight Oasis' to the 'Retail Smoke Shop' category. 

Details follow: 
```yml 
- name: Midnight Oasis
  url: https://www.MidnightOasis.com
  img: MidnightOasis.png
  bch: true
  btc: false
  othercrypto: true
  email_address: christodd420@gmail.com
  region: na
  country: US
  city: Kent
```

Resources for adding this merchant:
[Link to Midnight Oasis](https://www.MidnightOasis.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.MidnightOasis.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.MidnightOasis.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.MidnightOasis.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
