### ISSUE TITLE
Add 'Roseland Digital' to the 'Web Developer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2011]
Requesting to add 'Roseland Digital' to the 'Web Developer' category. 

Details follow: 
```yml 
- name: Roseland Digital
  url: https://roselanddigital.com/
  img: RoselandDigital.png
  bch: true
  btc: true
  othercrypto: true
  twitter: roselanddigital
  facebook: roselanddigital
  email_address: JR@RoselandDigital.com
  doc: https://roselanddigital.com/cryptocurrency
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://roselanddigital.com/images/ROSELAND_DIGITAL_SQR_660.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1374424983569494022/mtkXVI8m_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/roselanddigital/picture)
[Link to Roseland Digital](https://roselanddigital.com/)
Check their Twitter Page: [twitter.com/roselanddigital](https://twitter.com/roselanddigital)
Check their Facebook Page: [fb.com/roselanddigital](https://fb.com/roselanddigital)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/roselanddigital.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/roselanddigital.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/roselanddigital.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [roselanddigital](https://twitter.com/roselanddigital/), be sure to send out a tweet when this request has been added.
