### ISSUE TITLE
Add 'Hyke & Byke' to the 'Sports goods, outdoor gear' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2012]
Requesting to add 'Hyke & Byke' to the 'Sports goods, outdoor gear' category. 

Details follow: 
```yml 
- name: Hyke & Byke
  url: https://www.hykeandbyke.com/
  img: HykeByke.png
  bch: true
  btc: true
  othercrypto: false
  facebook: hykeandbyke
  email_address: tamara@wldm.io
  region: na
  doc: https://www.hykeandbyke.com/collections/top-sellers/products/yosemite-2p-backpacking-tent
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://assets.trailspace.com/assets/9/b/b/7768507/hykebyke.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/hykeandbyke/picture)
[Link to Hyke & Byke](https://www.hykeandbyke.com/)
Check their Facebook Page: [fb.com/hykeandbyke](https://fb.com/hykeandbyke)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.hykeandbyke.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.hykeandbyke.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.hykeandbyke.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
