### ISSUE TITLE
Request to add Hyke & Byke to your merchants list 

### ISSUE THREAD

**Issue by Tamicaa** [acceptbitcoincash/acceptbitcoincash#2013]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Hyke & Byke**}} to the {{**Sport & Outdoor Gear**}} category. Details follow:

```yml

- name: Hyke & Byke
  url: https://www.hykeandbyke.com/
  img: https://assets.trailspace.com/assets/9/b/b/7768507/hykebyke.jpg
  twitter: twitter_username_no_@_symbol
  facebook: https://www.facebook.com/hykeandbyke
  region: na
 country: ISO 3166-2:US
  city: Denver
  bch: no
  bsv: no
  btc: yes
  othercrypto: no
  doc: https://www.hykeandbyke.com/collections/down-sleeping-bags/products/eolus-800-fill-power-0-f-goose-down-sleeping-bag
  keywords:
  - outdoor gear
  - sporting goods
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
