### ISSUE TITLE
Add 'Alt Brew' to the 'Coffee Shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2015]
Requesting to add 'Alt Brew' to the 'Coffee Shop' category. 

Details follow: 
```yml 
- name: Alt Brew
  url: https://www.facebook.com/Alt-Brew-1325275994229457/
  img: AltBrew.png
  bch: true
  btc: false
  othercrypto: false
  facebook: alt-brew-1325275994229457
  email_address: altbrew@outlook.com
  region: oc
  country: AU
  city: Townsville
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.facebook.com/1325275994229457/photos/a.1325279294229127/1391671874256535/?__tn__=%3C)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/alt-brew-1325275994229457/picture)
[Link to Alt Brew](https://www.facebook.com/Alt-Brew-1325275994229457/)
Check their Facebook Page: [fb.com/alt-brew-1325275994229457](https://fb.com/alt-brew-1325275994229457)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.facebook.com/Alt-Brew-1325275994229457/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.facebook.com/Alt-Brew-1325275994229457/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.facebook.com/Alt-Brew-1325275994229457/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
