### ISSUE TITLE
Add 'Website Downloader' to the 'Web Development' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2016]
Requesting to add 'Website Downloader' to the 'Web Development' category. 

Details follow: 
```yml 
- name: Website Downloader
  url: https://websitedownloader.org
  img: WebsiteDownloader.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to Website Downloader](https://websitedownloader.org)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/websitedownloader.org)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/websitedownloader.org)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/websitedownloader.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
