### ISSUE TITLE
Add 'Charles Oziouls Toulouse' to the 'Audio editor, sound engineer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2017]
Requesting to add 'Charles Oziouls Toulouse' to the 'Audio editor, sound engineer' category. 

Details follow: 
```yml 
- name: Charles Oziouls Toulouse
  url: https://www.soundcloud.com/charles-musique
  img: CharlesOzioulsToulouse.png
  bch: true
  btc: true
  othercrypto: true
  twitter: thisismyrurl
  email_address: charles.ozioulstoulouse@gmail.com
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/409319441/10730_143171398080_518458080_2393850_3903898_n_normal.jpg)
[Link to Charles Oziouls Toulouse](https://www.soundcloud.com/charles-musique)
Check their Twitter Page: [twitter.com/thisismyrurl](https://twitter.com/thisismyrurl)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.soundcloud.com/charles-musique)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.soundcloud.com/charles-musique)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.soundcloud.com/charles-musique)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
