### ISSUE TITLE
Add 'Smile Dental Design' to the 'Dental' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2018]
Requesting to add 'Smile Dental Design' to the 'Dental' category. 

Details follow: 
```yml 
- name: Smile Dental Design
  url: https://smiledentaldesign.com/
  img: SmileDentalDesign.png
  bch: true
  btc: false
  othercrypto: false
  twitter: smiledental_il
  facebook: smiledentaldesignwheeling
  email_address: smiledentaldesign@gmail.com
  region: na
  country: US
  city: Chicago
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://smiledentaldesign.com/wp-content/uploads/2020/06/sdd_logo_small2.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/780399206594912256/XR42nzvT_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/smiledentaldesignwheeling/picture)
[Link to Smile Dental Design](https://smiledentaldesign.com/)
Check their Twitter Page: [twitter.com/smiledental_il](https://twitter.com/smiledental_il)
Check their Facebook Page: [fb.com/smiledentaldesignwheeling](https://fb.com/smiledentaldesignwheeling)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/smiledentaldesign.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/smiledentaldesign.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/smiledentaldesign.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
