### ISSUE TITLE
Add 'Country Auto Sales Calgary' to the 'dealership' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2020]
Requesting to add 'Country Auto Sales Calgary' to the 'dealership' category. 

Details follow: 
```yml 
- name: Country Auto Sales Calgary
  url: https://calgarycrypto.ca
  img: CountryAutoSalesCalgary.png
  bch: true
  btc: true
  othercrypto: true
  email_address: car@calgarycrypto.ca
  region: na
  country: CA
  city: Calgary
  doc: https://calgarycrypto.ca/autosales.html
  exceptions:
    text: "Mail to car@calgarycrypto.ca or call +14035889447"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.countryautosalescalgary.com/wp-content/uploads/2020/11/logo-small.png)
[Link to Country Auto Sales Calgary](https://calgarycrypto.ca)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/calgarycrypto.ca)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/calgarycrypto.ca)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/calgarycrypto.ca)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [bchpizza.org](https://twitter.com/bchpizza.org/), be sure to send out a tweet when this request has been added.
