### ISSUE TITLE
Add 'Canwest Travel' to the 'travel agency' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2021]
Requesting to add 'Canwest Travel' to the 'travel agency' category. 

Details follow: 
```yml 
- name: Canwest Travel
  url: https://reddeer.cash/
  img: CanwestTravel.png
  bch: true
  btc: true
  othercrypto: true
  email_address: travel@reddeer.cash
  region: na
  country: CA
  city: Red Deer
  doc: https://reddeer.cash/travel.html
  exceptions:
    text: "Email travel@reddeer.cash or call 1 (800) 565-8598"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://canwest.travel/wp-content/uploads/2018/12/canwest-topleft-logo.png?d0879c&d0879c)
[Link to Canwest Travel](https://reddeer.cash/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/reddeer.cash/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/reddeer.cash/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/reddeer.cash/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [bchpizza_org](https://twitter.com/bchpizza_org/), be sure to send out a tweet when this request has been added.
