### ISSUE TITLE
Add 'Gaiagora' to the 'Retail Online' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2023]
Requesting to add 'Gaiagora' to the 'Retail Online' category. 

Details follow: 
```yml 
- name: Gaiagora
  url: https://www.gaiagora.com
  img: Gaiagora.png
  bch: false
  btc: false
  othercrypto: true
  email_address: corey.haag@gaiagora.com
```

Resources for adding this merchant:
[Link to Gaiagora](https://www.gaiagora.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.gaiagora.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.gaiagora.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.gaiagora.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
