### ISSUE TITLE
Add 'Bono Shop' to the 'Jewelry & Fashion' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2024]
Requesting to add 'Bono Shop' to the 'Jewelry & Fashion' category. 

Details follow: 
```yml 
- name: Bono Shop
  url: https://bonogifts.store/
  img: BonoShop.png
  bch: true
  btc: false
  othercrypto: true
  email_address: bonoshopmail@gmail.com
  country: US
  doc: https://bonogifts.store/products/open-back-long-sleeve-top-backless-sexy-shirt-women-sexy-harajuku-open-back-top-women-s-cropped-long-sleeve-tee-summer-casual-tops
  exceptions:
    text: "Pay either with the coinbase commerce gateway or if you want to pay directly to our wallet adress without passing through coinbase commerce and contact us when you have completed the transaction or before and we will guide you through every step
+ 
for the cripto option you will have 20% off with the coupon code CRIPTOSALE"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.etsystatic.com/isla/a19762/45711305/isla_280x280.45711305_j9c8au8d.jpg?version=0)
[Link to Bono Shop](https://bonogifts.store/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bonogifts.store/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bonogifts.store/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bonogifts.store/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
