### ISSUE TITLE
Add '2cash' to the 'Crypto-commerce' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2028]
Requesting to add '2cash' to the 'Crypto-commerce' category. 

Details follow: 
```yml 
- name: 2cash
  url: https://www.2cash.io/
  img: cash.png
  bch: true
  btc: true
  othercrypto: true
  twitter: 2cashnetwork
  facebook: 2cashnetwork
  email_address: contact@2cash.io
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.2cash.io/assets/images/2cash-logo-80x80.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1014930000926072832/4swwaPx0_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/2cashnetwork/picture)
[Link to 2cash](https://www.2cash.io/)
Check their Twitter Page: [twitter.com/2cashnetwork](https://twitter.com/2cashnetwork)
Check their Facebook Page: [fb.com/2cashnetwork](https://fb.com/2cashnetwork)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.2cash.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.2cash.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.2cash.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
