### ISSUE TITLE
Add 'prophaze.com' to the 'Api Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2029]
Requesting to add 'prophaze.com' to the 'Api Security' category. 

Details follow: 
```yml 
- name: prophaze.com
  url: https://prophaze.com/
  img: prophazecom.png
  bch: false
  btc: false
  othercrypto: false
  twitter: yes
  facebook: yes
  email_address: anoop@prophaze.com
  city: no
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://media-exp1.licdn.com/dms/image/C560BAQEC7j3_PQTlPw/company-logo_200_200/0/1598054396808?e=1631750400&v=beta&t=3YD-V1IsozMmE5nn7Rbr_vhO8Xh5uiv0jyB0tKsCMYI)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/962842169890430976/JGv-XReJ_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/yes/picture)
[Link to prophaze.com](https://prophaze.com/)
Check their Twitter Page: [twitter.com/yes](https://twitter.com/yes)
Check their Facebook Page: [fb.com/yes](https://fb.com/yes)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/prophaze.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/prophaze.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/prophaze.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
