### ISSUE TITLE
Add 'Amir Parvinchi MD Inc' to the 'Medical Office' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2030]
Requesting to add 'Amir Parvinchi MD Inc' to the 'Medical Office' category. 

Details follow: 
```yml 
- name: Amir Parvinchi MD Inc
  url: www.drparvinchi.com
  img: AmirParvinchiMDInc.png
  bch: true
  btc: false
  othercrypto: false
  region: na
  country: US
  city: Los Angeles 
```

Resources for adding this merchant:
[Link to Amir Parvinchi MD Inc](www.drparvinchi.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.drparvinchi.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.drparvinchi.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.drparvinchi.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
