### ISSUE TITLE
Add 'AWISEE' to the 'Link Building Agency ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2031]
Requesting to add 'AWISEE' to the 'Link Building Agency ' category. 

Details follow: 
```yml 
- name: AWISEE
  url: https://awisee.com
  img: AWISEE.png
  bch: true
  btc: false
  othercrypto: true
  email_address: hi@awisee.com
  city: Worldwide
  doc: http://awisee.com/blog/bitcoin-cash
  exceptions:
    text: "Coinbase Commerce"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://awisee.com)
[Link to AWISEE](https://awisee.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/awisee.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/awisee.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/awisee.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
