### ISSUE TITLE
Add 'MMORPGMALL' to the 'GAME Store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2032]
Requesting to add 'MMORPGMALL' to the 'GAME Store' category. 

Details follow: 
```yml 
- name: MMORPGMALL
  url: https://mmorpgmall.com
  img: MMORPGMALL.png
  bch: true
  btc: true
  othercrypto: true
  twitter: mmorpgmall1
  email_address: support@mmorpgmall.com
  country: US
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1337285639503400960/gejeajyV_normal.jpg)
[Link to MMORPGMALL](https://mmorpgmall.com)
Check their Twitter Page: [twitter.com/mmorpgmall1](https://twitter.com/mmorpgmall1)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/mmorpgmall.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/mmorpgmall.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/mmorpgmall.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
