### ISSUE TITLE
Add 'Bitlive' to the 'cryptocurrency exchange aggregator ' category

### ISSUE THREAD

**Issue by Bitlive-pro** [acceptbitcoincash/acceptbitcoincash#2034]
Requesting to add 'bitlive' to the 'cryptocurrency exchange aggregator ' category.

Details follow:

```yml

- name: bitlive
  url: https://bitlive.pro/
  img: https://bitlive.pro/uploads/2021/06/logo-32x32.png
  bch: true
  btc: true
  othercrypto: true
  email_address: pr@bitlive.pro
```
