### ISSUE TITLE
Add 'MELISSA TRI' to the 'Aaa' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2036]
Requesting to add 'MELISSA TRI' to the 'Aaa' category. 

Details follow: 
```yml 
- name: MELISSA TRI
  url: https://acceptbitcoin.cash/
  img: MELISSATRI.png
  bch: true
  btc: true
  othercrypto: true
  email_address: tthibeaultm@gmail.com
  region: na
  country: CA
  city: Montréal
```

Resources for adding this merchant:
[Link to MELISSA TRI](https://acceptbitcoin.cash/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/acceptbitcoin.cash/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/acceptbitcoin.cash/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/acceptbitcoin.cash/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
