### ISSUE TITLE
Add 'Brazzers' to the 'Xxxx' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2039]
Requesting to add 'Brazzers' to the 'Xxxx' category. 

Details follow: 
```yml 
- name: Brazzers
  url: Brazzers.com
  img: Brazzers.png
  bch: true
  btc: false
  othercrypto: false
  facebook: ola
  email_address: dani220305@hotmail.con
  region: sa
  country: AE
  city: Ola
  exceptions:
    text: "Ola"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](htt/Brazzers.com)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/ola/picture)
[Link to Brazzers](Brazzers.com)
Check their Facebook Page: [fb.com/ola](https://fb.com/ola)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/Brazzers.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/Brazzers.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/Brazzers.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @ola
Request made by Twitter user [ola](https://twitter.com/ola/), be sure to send out a tweet when this request has been added.
