### ISSUE TITLE
Add 'Yolanda Gutiérrez Gómez' to the 'Adulto' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2041]
Requesting to add 'Yolanda Gutiérrez Gómez' to the 'Adulto' category. 

Details follow: 
```yml 
- name: Yolanda Gutiérrez Gómez
  url: www.pay.me/@yolidecastillo
  img: YolandaGutirrezGmez.png
  bch: true
  btc: true
  othercrypto: true
  facebook: yoligómez
  email_address: Yolidecastillo84@gmail.com
  region: na
  country: MX
  city: Saltillo 
  exceptions:
    text: "Identidad"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](paypal.com/bussines.com)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/yoligómez/picture)
[Link to Yolanda Gutiérrez Gómez](www.pay.me/@yolidecastillo)
Check their Facebook Page: [fb.com/yoligómez](https://fb.com/yoligómez)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.pay.me/@yolidecastillo)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.pay.me/@yolidecastillo)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.pay.me/@yolidecastillo)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @yolidecastillo84gmail.com
Request made by Twitter user [yolidecastillo84](https://twitter.com/yolidecastillo84/), be sure to send out a tweet when this request has been added.
