### ISSUE TITLE
Add 'Cheaplightning.com' to the 'Japanese Retro Video Games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2043]
Requesting to add 'Cheaplightning.com' to the 'Japanese Retro Video Games' category. 

Details follow: 
```yml 
- name: Cheaplightning.com
  url: https://www.cheaplightning.com
  img: Cheaplightningcom.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cheap_lightning
  email_address: questions@cheaplightning.com
  doc: https://www.cheaplightning.com/bitcoin/
  exceptions:
    text: "Wait for the QR code to appear"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://www.cheaplightning.com/wp-content/uploads/2019/12/cropped-NEW-CL-logo-only-10-2019.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1176076066961551361/XaBm3Wgo_normal.jpg)
[Link to Cheaplightning.com](https://www.cheaplightning.com)
Check their Twitter Page: [twitter.com/cheap_lightning](https://twitter.com/cheap_lightning)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cheaplightning.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cheaplightning.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cheaplightning.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
