### ISSUE TITLE
Add 'My BCH Merch Store' to the 'Bitcoin Cash Related Merchandise & Apparel  ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2044]
Requesting to add 'My BCH Merch Store' to the 'Bitcoin Cash Related Merchandise & Apparel  ' category. 

Details follow: 
```yml 
- name: My BCH Merch Store
  url: https://mybchmerch.store
  img: MyBCHMerchStore.png
  bch: true
  btc: false
  othercrypto: false
  email_address: jotechhelp@gmail.com
  doc: https://www.reddit.com/r/btc/comments/olivzn/bitcoin_cash_cashers_baseball_jersey/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
  exceptions:
    text: "Just click Coinbase Commerce on Check Out. 15% of ALL BCH Purchases will be redistributed via Chaintip and other BCH support services."
```

Resources for adding this merchant:
[Link to My BCH Merch Store](https://mybchmerch.store)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/mybchmerch.store)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/mybchmerch.store)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/mybchmerch.store)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [alienantbag](https://twitter.com/alienantbag/), be sure to send out a tweet when this request has been added.
