### ISSUE TITLE
Add 'nachhaltig4future' to the 'blog' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2045]
Requesting to add 'nachhaltig4future' to the 'blog' category. 

Details follow: 
```yml 
- name: nachhaltig4future
  url: https://nachhaltig4future.de
  img: nachhaltigfuture.png
  bch: true
  btc: false
  othercrypto: true
  twitter: nachhaltig4f
  facebook: nachhaltig4future
  email_address: info@nachhaltig4future.de
  region: eu
  country: DE
  doc: https://nachhaltig4future.de/unterstuetzen/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1383806351009144840/N2EI99jK_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1383806351009144840/N2EI99jK_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/nachhaltig4future/picture)
[Link to nachhaltig4future](https://nachhaltig4future.de)
Check their Twitter Page: [twitter.com/nachhaltig4f](https://twitter.com/nachhaltig4f)
Check their Facebook Page: [fb.com/nachhaltig4future](https://fb.com/nachhaltig4future)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/nachhaltig4future.de)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/nachhaltig4future.de)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/nachhaltig4future.de)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [nachhaltig4f](https://twitter.com/nachhaltig4f/), be sure to send out a tweet when this request has been added.
