### ISSUE TITLE
Add 'Junub Open Space' to the 'Organization ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2047]
Requesting to add 'Junub Open Space' to the 'Organization ' category. 

Details follow: 
```yml 
- name: Junub Open Space
  url: https://facebook.com/junubopenspace
  img: JunubOpenSpace.png
  bch: true
  btc: true
  othercrypto: true
  twitter: junubos
  facebook: junubopenspace
  email_address: info@junubos.org
  region: af
  country: SS
  city: All state of South Sudan
  exceptions:
    text: "No really"
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1305148392495083520/zX_Aupa4_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/junubopenspace/picture)
[Link to Junub Open Space](https://facebook.com/junubopenspace)
Check their Twitter Page: [twitter.com/junubos](https://twitter.com/junubos)
Check their Facebook Page: [fb.com/junubopenspace](https://fb.com/junubopenspace)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/facebook.com/junubopenspace)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/facebook.com/junubopenspace)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/facebook.com/junubopenspace)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [junubos](https://twitter.com/junubos/), be sure to send out a tweet when this request has been added.
