### ISSUE TITLE
Add 'Wow Girls' to the 'Adult Website' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2049]
Requesting to add 'Wow Girls' to the 'Adult Website' category. 

Details follow: 
```yml 
- name: Wow Girls
  url: https://www.wowgirls.com
  img: WowGirls.png
  bch: true
  btc: true
  othercrypto: true
  twitter: wowgirls_news
  doc: https://www.wowgirls.com/crypto-join
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://send.tresorit.com/a#C0Spd_g7fKeUUC_0BunhJw)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1091255560626933760/XVCzLP4V_normal.jpg)
[Link to Wow Girls](https://www.wowgirls.com)
Check their Twitter Page: [twitter.com/wowgirls_news](https://twitter.com/wowgirls_news)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.wowgirls.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.wowgirls.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.wowgirls.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
