### ISSUE TITLE
Add 'Ultra Films' to the 'Adult Website' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2050]
Requesting to add 'Ultra Films' to the 'Adult Website' category. 

Details follow: 
```yml 
- name: Ultra Films
  url: https://www.ultrafilms.com/
  img: UltraFilms.png
  bch: true
  btc: true
  othercrypto: true
  doc: https://www.ultrafilms.com/crypto-join
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://send.tresorit.com/a#aH2nS2YfNLZiZGpi4lAK4g)
[Link to Ultra Films](https://www.ultrafilms.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ultrafilms.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ultrafilms.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ultrafilms.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
