### ISSUE TITLE
Add 'Wow Porn' to the 'Adult Website' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2051]
Requesting to add 'Wow Porn' to the 'Adult Website' category. 

Details follow: 
```yml 
- name: Wow Porn
  url: https://www.wowporn.com/
  img: WowPorn.png
  bch: true
  btc: true
  othercrypto: true
  doc: https://www.wowporn.com/crypto-join
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://send.tresorit.com/a#s2zOgidpNOinp7xpypab3g)
[Link to Wow Porn](https://www.wowporn.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.wowporn.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.wowporn.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.wowporn.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
