### ISSUE TITLE
Add 'All Fine Girls' to the 'Adult Website' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2052]
Requesting to add 'All Fine Girls' to the 'Adult Website' category. 

Details follow: 
```yml 
- name: All Fine Girls
  url: https://www.allfinegirls.com/
  img: AllFineGirls.png
  bch: true
  btc: true
  othercrypto: true
  exceptions:
    text: "https://www.allfinegirls.com/crypto-join"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://send.tresorit.com/a#adHim6Ysvm5jPiMshLH_jQ)
[Link to All Fine Girls](https://www.allfinegirls.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.allfinegirls.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.allfinegirls.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.allfinegirls.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
