### ISSUE TITLE
Add 'www.sentipaywallet.com' to the 'Payments and rewards points ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2053]
Requesting to add 'www.sentipaywallet.com' to the 'Payments and rewards points ' category. 

Details follow: 
```yml 
- name: www.sentipaywallet.com
  url: https://play.google.com/store/apps/details?id=com.vaival.sentipaywallet
  img: wwwsentipaywalletcom.png
  bch: true
  btc: false
  othercrypto: true
  twitter: sentipay
  facebook: none
  email_address: business@sentipaywallet.com
  country: ZA
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.google.com/search?q=senti+Pay&client=ms-android-huawei-rev1&prmd=vni&sxsrf=ALeKk03wCZT39_eGzBuqBw98r8JNtlyeog:1627506947890&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjp-v3r14byAhUUecAKHaLeCr8Q_AUoA3oECAIQAw&biw=424&bih=771#imgrc=RssAULxyod9aNM)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1297570478509494274/X01pgJM1_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/none/picture)
[Link to www.sentipaywallet.com](https://play.google.com/store/apps/details?id=com.vaival.sentipaywallet)
Check their Twitter Page: [twitter.com/sentipay](https://twitter.com/sentipay)
Check their Facebook Page: [fb.com/none](https://fb.com/none)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/play.google.com/store/apps/details?id=com.vaival.sentipaywallet)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/play.google.com/store/apps/details?id=com.vaival.sentipaywallet)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/play.google.com/store/apps/details?id=com.vaival.sentipaywallet)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
