### ISSUE TITLE
Add 'LIFX' to the 'Smart Home Lighting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2054]
Requesting to add 'LIFX' to the 'Smart Home Lighting' category. 

Details follow: 
```yml 
- name: LIFX
  url: lifx.com
  img: LIFX.png
  bch: true
  btc: true
  othercrypto: true
  twitter: lifx
  facebook: lifx
  email_address: ecommerce@lifx.co
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0219/0638/files/lifx_logo_9ae0aa6d-07df-41ba-b96d-0f400323e1b1_140x.png?v=1575366323)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1231788324022439937/zS6itnI4_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/lifx/picture)
[Link to LIFX](lifx.com)
Check their Twitter Page: [twitter.com/lifx](https://twitter.com/lifx)
Check their Facebook Page: [fb.com/lifx](https://fb.com/lifx)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/lifx.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/lifx.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/lifx.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
