### ISSUE TITLE
Add 'Xolos Ramirez' to the 'dog breeder' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2055]
Requesting to add 'Xolos Ramirez' to the 'dog breeder' category. 

Details follow: 
```yml 
- name: Xolos Ramirez
  url: https://www.xolosramirez.com
  img: XolosRamirez.png
  bch: true
  btc: false
  othercrypto: true
  twitter: xolosramirez1
  facebook: xolosramirez1
  email_address: xolosramirez@protonmail.com
  region: na
  country: US
  city: San Diego
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/xolosramirez1/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1358563938372354048/mrmaFsyz_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/xolosramirez1/picture)
[Link to Xolos Ramirez](https://www.xolosramirez.com)
Check their Twitter Page: [twitter.com/xolosramirez1](https://twitter.com/xolosramirez1)
Check their Facebook Page: [fb.com/xolosramirez1](https://fb.com/xolosramirez1)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.xolosramirez.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.xolosramirez.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.xolosramirez.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
