### ISSUE TITLE
Add 'Zen-et-sante.fr' to the 'Semi précious stones & jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2058]
Requesting to add 'Zen-et-sante.fr' to the 'Semi précious stones & jewelry' category. 

Details follow: 
```yml 
- name: Zen-et-sante.fr
  url: https://zen-et-sante.fr/
  img: Zenetsantefr.png
  bch: true
  btc: false
  othercrypto: true
  email_address: contact@zen-et-sante.fr
  country: FR
```

Resources for adding this merchant:
[Link to Zen-et-sante.fr](https://zen-et-sante.fr/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/zen-et-sante.fr/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/zen-et-sante.fr/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/zen-et-sante.fr/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
