### ISSUE TITLE
Add 'พูนทรัพย์' to the '10000' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2060]
Requesting to add 'พูนทรัพย์' to the '10000' category. 

Details follow: 
```yml 
- name: พูนทรัพย์
  url: poonsupnoe@goail.com
  img: พูนทรัพย์.png
  bch: true
  btc: true
  othercrypto: true
  country: CA
```

Resources for adding this merchant:
[Link to พูนทรัพย์](poonsupnoe@goail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/poonsupnoe@goail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/poonsupnoe@goail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/poonsupnoe@goail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @020313893248
