### ISSUE TITLE
Add 'Trademark Hardware' to the 'Door and Cabinet Hardware' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2062]
Requesting to add 'Trademark Hardware' to the 'Door and Cabinet Hardware' category. 

Details follow: 
```yml 
- name: Trademark Hardware
  url: https://www.tmhardware.com/
  img: TrademarkHardware.png
  bch: true
  btc: true
  othercrypto: true
  twitter: tmhardware
  facebook: n/a
  email_address: customerservice@tmhardware.com
  region: na
  country: US
  city: All
  doc: https://twitter.com/tmhardware/status/1389976974005768194
  exceptions:
    text: "Click on "Coin Payments""
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/tmhardware/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/865638468168241152/FBsjIVxx_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/n/a/picture)
[Link to Trademark Hardware](https://www.tmhardware.com/)
Check their Twitter Page: [twitter.com/tmhardware](https://twitter.com/tmhardware)
Check their Facebook Page: [fb.com/n/a](https://fb.com/n/a)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.tmhardware.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.tmhardware.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.tmhardware.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @n/a
Request made by Twitter user [tmhardware](https://twitter.com/tmhardware/), be sure to send out a tweet when this request has been added.
