### ISSUE TITLE
CoinRemitter Listing

### ISSUE THREAD

**Issue by design-app-web** [acceptbitcoincash/acceptbitcoincash#2066]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{CoinRemitter}} to the {{Payments}} category. Details follow:

```yml

- name: CoinRemitter
  url: https://coinremitter.com/
  img: https://coinremitter.com/assets/img/home-new/logo-black.png
  twitter: coinremitter
  region: en
  country: Singapore
  bch: yes
  bsv: no
  btc: yes
  othercrypto: yes
  doc: https://coinremitter.com/docs
  keywords:
  - crypto payment gateway
  - payment gateway
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
