### ISSUE TITLE
Add 'WebAcademy™' to the 'Internet Services > Education' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2067]
Requesting to add 'WebAcademy™' to the 'Internet Services > Education' category. 

Details follow: 
```yml 
- name: WebAcademy™
  url: https://webacade.my
  img: WebAcademy.png
  bch: true
  btc: true
  othercrypto: false
  twitter: webacademycc
  facebook: webacademy.cc
  region: as
  country: MY
  exceptions:
    text: "They use Blockonomics payment gateway"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://s3.ap-southeast-1.amazonaws.com/webacade.my/img/logo-emblem-128px.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1394544180718817288/jZMAQ9JX_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/webacademy.cc/picture)
[Link to WebAcademy™](https://webacade.my)
Check their Twitter Page: [twitter.com/webacademycc](https://twitter.com/webacademycc)
Check their Facebook Page: [fb.com/webacademy.cc](https://fb.com/webacademy.cc)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/webacade.my)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/webacade.my)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/webacade.my)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
