### ISSUE TITLE
Add 'One Surgery' to the 'Merchandise including BCH branded goods' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2068]
Requesting to add 'One Surgery' to the 'Merchandise including BCH branded goods' category. 

Details follow: 
```yml 
- name: One Surgery
  url: https://shop.one.surgery
  img: OneSurgery.png
  bch: true
  btc: false
  othercrypto: false
  twitter: onedotsurgery
  email_address: admin@one.surgery
  doc: https://twitter.com/OneDotSurgery/status/1447867494107160580?t=3mVb2d2ViwHuVShTbgspDQ&s=19
  exceptions:
    text: "No, pay online through standard gateway"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://static2.one.surgery/wp-content/uploads/2021/10/20211012_105949_0000.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/992884387761934336/Cz8ol9tV_normal.jpg)
[Link to One Surgery](https://shop.one.surgery)
Check their Twitter Page: [twitter.com/onedotsurgery](https://twitter.com/onedotsurgery)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/shop.one.surgery)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/shop.one.surgery)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/shop.one.surgery)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [onedotsurgery](https://twitter.com/onedotsurgery/), be sure to send out a tweet when this request has been added.
