### ISSUE TITLE
Add 'Rob White Consulting' to the 'Construction' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2070]
Requesting to add 'Rob White Consulting' to the 'Construction' category. 

Details follow: 
```yml 
- name: Rob White Consulting
  url: https://www.facebook.com/RobWhiteConsulting
  img: RobWhiteConsulting.png
  bch: true
  btc: false
  othercrypto: false
  facebook: robwhiteconsulting
  email_address: consulting@robwhite.com.au
  region: oc
  country: AU
  city: Geraldton
  exceptions:
    text: "Standard non-custodian instructions as per invoices"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://scontent.fper7-1.fna.fbcdn.net/v/t1.6435-9/53857839_423890205086231_2961005837465681920_n.jpg?_nc_cat=103&ccb=1-5&_nc_sid=09cbfe&_nc_ohc=d753_gHgknoAX-QbE91&_nc_ht=scontent.fper7-1.fna&oh=ae6dfdfe117af20ca9458c1e88828451&oe=61948CBD)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/robwhiteconsulting/picture)
[Link to Rob White Consulting](https://www.facebook.com/RobWhiteConsulting)
Check their Facebook Page: [fb.com/robwhiteconsulting](https://fb.com/robwhiteconsulting)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.facebook.com/RobWhiteConsulting)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.facebook.com/RobWhiteConsulting)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.facebook.com/RobWhiteConsulting)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
