### ISSUE TITLE
BQuest.cash

### ISSUE THREAD

**Issue by Sydwell** [acceptbitcoincash/acceptbitcoincash#2071]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

Requesting to add {{BQuest}} to the {{**Cryto Services**}} category. Details follow:

```yml

- name: BQuest 
  url: https://bquest.cash
  img: https://bquest.cash/wp-content/uploads/2020/06/bquest-logo3-toresize-e1591037259494.png
  twitter:BQuest_Online@BquestOnline
  facebook: @bquestonline
  region: af
  country: ZA
  city: Cape Town
  bch: yes
  bsv:no
  btc: no
  othercrypto: no
  doc:  https://bquest.cash/announcement.html
  keywords:
  - WhatsApp
  - Airtime
  - Data
  - Electricity
  - Water
  - Buy
  - Credit Card
  - Debit Card
  - Cash Account
  - SLP
  - NFT
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
