### ISSUE TITLE
Add 'Herb Vapes AiVapes.com' to the 'Tobacco / Vapes' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2074]
Requesting to add 'Herb Vapes AiVapes.com' to the 'Tobacco / Vapes' category. 

Details follow: 
```yml 
- name: Herb Vapes AiVapes.com
  url: https://aivapes.com
  img: HerbVapesAiVapescom.png
  bch: true
  btc: true
  othercrypto: true
  twitter: aivapes
  facebook: aivapes
  email_address: month@aivapes.com
  region: na
  country: US
  city: Rich Creek
  doc: https://twitter.com/AiVapes/status/1459324470129303559
  exceptions:
    text: "Add to Cart and follow payment Gateway, Click "Chat with Us""
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://aivapes.com/pub/media/logo/stores/1/pnglogo.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1434464549147713537/RyAv7ocr_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/aivapes/picture)
[Link to Herb Vapes AiVapes.com](https://aivapes.com)
Check their Twitter Page: [twitter.com/aivapes](https://twitter.com/aivapes)
Check their Facebook Page: [fb.com/aivapes](https://fb.com/aivapes)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/aivapes.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/aivapes.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/aivapes.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [aivapes](https://twitter.com/aivapes/), be sure to send out a tweet when this request has been added.
