### ISSUE TITLE
Add 'TTOPI' to the 'Handmade Products' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2075]
Requesting to add 'TTOPI' to the 'Handmade Products' category. 

Details follow: 
```yml 
- name: TTOPI
  url: https://ttopi.ca/
  img: TTOPI.png
  bch: true
  btc: true
  othercrypto: true
  twitter: ttopi_inc
  facebook: ttopi.inc
  email_address: directors@ttopi.ca
  region: na
  country: CA
  city: Calgary
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.google.com/search?q=ttopi&tbm=isch&ved=2ahUKEwicrqnVyKL0AhUaGTQIHTYiCpgQ2-cCegQIABAA&oq=ttopi&gs_lcp=CgNpbWcQDDIHCCMQ7wMQJzIFCAAQgAQyBggAEAcQHjIGCAAQBxAeMgYIABAHEB4yBggAEAcQHjIGCAAQBxAeMgYIABAHEB4yBggAEAcQHjIGCAAQBxAeOgYIABAFEB5Q7wZY7wZg-RRoAHAAeACAAVOIAZoBkgEBMpgBAKABAaoBC2d3cy13aXotaW1nwAEB&sclient=img&ei=756WYdz6H5qy0PEPtsSowAk&bih=660&biw=1200&rlz=1C5CHFA_enCA940CA940#imgrc=BplxyoyvvVpHpM)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1327325391191609344/KWQeP0S2_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/ttopi.inc/picture)
[Link to TTOPI](https://ttopi.ca/)
Check their Twitter Page: [twitter.com/ttopi_inc](https://twitter.com/ttopi_inc)
Check their Facebook Page: [fb.com/ttopi.inc](https://fb.com/ttopi.inc)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/ttopi.ca/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/ttopi.ca/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/ttopi.ca/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @ttopi
Request made by Twitter user [ttopi_inc](https://twitter.com/ttopi_inc/), be sure to send out a tweet when this request has been added.
