### ISSUE TITLE
Add 'Kingofood' to the 'grocery' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2076]
Requesting to add 'Kingofood' to the 'grocery' category. 

Details follow: 
```yml 
- name: Kingofood
  url: https://www.kingofood.com/
  img: Kingofood.png
  bch: true
  btc: false
  othercrypto: true
  facebook: kingofood.official
  email_address: andrea@cronlineshop.it
  region: eu
  exceptions:
    text: "on checkout select " bitcoin and other crypto " option"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.kingofood.com/img/kingofood-logo-1620936237.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/kingofood.official/picture)
[Link to Kingofood](https://www.kingofood.com/)
Check their Facebook Page: [fb.com/kingofood.official](https://fb.com/kingofood.official)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.kingofood.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.kingofood.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.kingofood.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
