### ISSUE TITLE
Add 'Coinsbee.com' to the 'Giftcards' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2079]
Requesting to add 'Coinsbee.com' to the 'Giftcards' category. 

Details follow: 
```yml 
- name: Coinsbee.com
  url: https://www.coinsbee.com/
  img: Coinsbeecom.png
  bch: true
  btc: true
  othercrypto: true
  twitter: coinsbee
  facebook: coinsbee
  doc: https://beincrypto.com/coinsbee-review-buy-gift-cards-with-bitcoin-other-crypto/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.coinsbee.com/img/coinsbee_assets/coinsbee_coin_square-darkbg.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1144388414340501504/ynNkpFcR_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/coinsbee/picture)
[Link to Coinsbee.com](https://www.coinsbee.com/)
Check their Twitter Page: [twitter.com/coinsbee](https://twitter.com/coinsbee)
Check their Facebook Page: [fb.com/coinsbee](https://fb.com/coinsbee)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.coinsbee.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.coinsbee.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.coinsbee.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
