### ISSUE TITLE
Add 'Jesus Gaganting Garcia' to the 'Gcash account 09364415256 Jesus Garcia' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2080]
Requesting to add 'Jesus Gaganting Garcia' to the 'Gcash account 09364415256 Jesus Garcia' category. 

Details follow: 
```yml 
- name: Jesus Gaganting Garcia
  url: annpapasin@gmail.com
  img: JesusGagantingGarcia.png
  bch: true
  btc: true
  othercrypto: true
  facebook: anniebugz35gmail.com
  email_address: jesusgarcia122279@gmail.com
  country: PH
  city: Zamboanga city
  exceptions:
    text: "Sent to my HUSBAND 
GCASH account 09364415256"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](URL/annpapasin@gmail.com)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/anniebugz35gmail.com/picture)
[Link to Jesus Gaganting Garcia](annpapasin@gmail.com)
Check their Facebook Page: [fb.com/anniebugz35gmail.com](https://fb.com/anniebugz35gmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/annpapasin@gmail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/annpapasin@gmail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/annpapasin@gmail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @annpapasin/annpapasingmail.com
Request made by Twitter user [annpapasingmail.com](https://twitter.com/annpapasingmail.com/), be sure to send out a tweet when this request has been added.
