### ISSUE TITLE
Add 'Ann  Papasin/slotocash casino' to the 'Online games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2081]
Requesting to add 'Ann  Papasin/slotocash casino' to the 'Online games' category. 

Details follow: 
```yml 
- name: Ann  Papasin/slotocash casino
  url: http//:slotocash.im
  img: AnnPapasinslotocashcasino.png
  bch: false
  btc: false
  othercrypto: true
  facebook: annpapasingmail.com
  email_address: annpapasin@gmail.com
  region: as
  country: PH
  city: Zamboanga
  exceptions:
    text: "Philipines  PESO, sent to my husband account GCASH #  09364415256 
account name: JESUS GARCIA"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](URL//:JPG PHOTO 1:1)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/annpapasingmail.com/picture)
[Link to Ann  Papasin/slotocash casino](http//:slotocash.im)
Check their Facebook Page: [fb.com/annpapasingmail.com](https://fb.com/annpapasingmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/http//:slotocash.im)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/http//:slotocash.im)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/http//:slotocash.im)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @annpapasingmail.com
Request made by Twitter user [annpapasingmail.com](https://twitter.com/annpapasingmail.com/), be sure to send out a tweet when this request has been added.
