### ISSUE TITLE
Add 'Parcel Forwarding Poland' to the 'Packages forwarding' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2082]
Requesting to add 'Parcel Forwarding Poland' to the 'Packages forwarding' category. 

Details follow: 
```yml 
- name: Parcel Forwarding Poland
  url: https://www.parcelpoland.com
  img: ParcelForwardingPoland.png
  bch: true
  btc: true
  othercrypto: true
  twitter: reshippoland
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/908233834197602304/ggHG0740_normal.jpg)
[Link to Parcel Forwarding Poland](https://www.parcelpoland.com)
Check their Twitter Page: [twitter.com/reshippoland](https://twitter.com/reshippoland)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.parcelpoland.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.parcelpoland.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.parcelpoland.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
