### ISSUE TITLE
Add 'betanysports' to the 'Marketing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2084]
Requesting to add 'betanysports' to the 'Marketing' category. 

Details follow: 
```yml 
- name: betanysports
  url: https://betanysports.eu/
  img: betanysports.png
  bch: true
  btc: true
  othercrypto: true
  email_address: dave@betanysports.eu
  region: na
  country: US
```

Resources for adding this merchant:
[Link to betanysports](https://betanysports.eu/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/betanysports.eu/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/betanysports.eu/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/betanysports.eu/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
