### ISSUE TITLE
Add 'ZebPay' to the 'Cryptocurrency Exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2085]
Requesting to add 'ZebPay' to the 'Cryptocurrency Exchange' category. 

Details follow: 
```yml 
- name: ZebPay
  url: https://zebpay.com/
  img: ZebPay.png
  bch: false
  btc: false
  othercrypto: false
  email_address: sudhakiran1002@gmail.com
  region: as
  country: IN
```

Resources for adding this merchant:
[Link to ZebPay](https://zebpay.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/zebpay.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/zebpay.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/zebpay.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
