### ISSUE TITLE
Add 'THE RESOLUTION CORPORATION' to the 'TAX PREPARATION' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2087]
Requesting to add 'THE RESOLUTION CORPORATION' to the 'TAX PREPARATION' category. 

Details follow: 
```yml 
- name: THE RESOLUTION CORPORATION
  url: WWW.THERESOLUTIONINC.COM
  img: THERESOLUTIONCORPORATION.png
  bch: true
  btc: false
  othercrypto: true
  facebook: theresolution
  email_address: thomasreply@yahoo.com
  country: US
  city: Virginia Beach
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/cynthia38472749)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/theresolution/picture)
[Link to THE RESOLUTION CORPORATION](WWW.THERESOLUTIONINC.COM)
Check their Facebook Page: [fb.com/theresolution](https://fb.com/theresolution)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/WWW.THERESOLUTIONINC.COM)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/WWW.THERESOLUTIONINC.COM)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/WWW.THERESOLUTIONINC.COM)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @resolutioncorp
Request made by Twitter user [theresolution](https://twitter.com/theresolution/), be sure to send out a tweet when this request has been added.
