### ISSUE TITLE
Add '$Cashapp' to the 'Send me the money right now how much ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2088]
Requesting to add '$Cashapp' to the 'Send me the money right now how much ' category. 

Details follow: 
```yml 
- name: $Cashapp
  url: https//www.drive.com
  img: Cashapp.png
  bch: true
  btc: true
  othercrypto: false
  facebook: $karen745
  email_address: cherryspa1750@gmail.com
  country: US
  city: California 
  exceptions:
    text: "Cash only"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](www.cashapp.com)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/$karen745/picture)
[Link to $Cashapp](https//www.drive.com)
Check their Facebook Page: [fb.com/$karen745](https://fb.com/$karen745)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/https//www.drive.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/https//www.drive.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/https//www.drive.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @$karen745
Request made by Twitter user [btc](https://twitter.com/btc/), be sure to send out a tweet when this request has been added.
