### ISSUE TITLE
Add 'Saamaja' to the 'Educationa' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2090]
Requesting to add 'Saamaja' to the 'Educationa' category. 

Details follow: 
```yml 
- name: Saamaja
  url: https://saamaja.com
  img: Saamaja.png
  bch: false
  btc: false
  othercrypto: true
  twitter: saamajaconnect
  facebook: saamajaconnect
  email_address: connect@saamaja.com
  country: IN
  city: No
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://saamaja.com)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1460640755907584004/Kz31U7Gg_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/saamajaconnect/picture)
[Link to Saamaja](https://saamaja.com)
Check their Twitter Page: [twitter.com/saamajaconnect](https://twitter.com/saamajaconnect)
Check their Facebook Page: [fb.com/saamajaconnect](https://fb.com/saamajaconnect)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/saamaja.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/saamaja.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/saamaja.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
