### ISSUE TITLE
Add 'cloudzy' to the 'cloud computing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2091]
Requesting to add 'cloudzy' to the 'cloud computing' category. 

Details follow: 
```yml 
- name: cloudzy
  url: https://cloudzy.com/
  img: cloudzy.png
  bch: true
  btc: true
  othercrypto: false
  email_address: emma.andorson@cloudzy.com
  doc: https://support.cloudzy.com/login
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cloudzy.com/wp-content/uploads/cropped-cloudzy_logo-1.png)
[Link to cloudzy](https://cloudzy.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cloudzy.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cloudzy.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cloudzy.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @cloudzy
