### ISSUE TITLE
Add 'Software Verde' to the 'Developers' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2092]
Requesting to add 'Software Verde' to the 'Developers' category. 

Details follow: 
```yml 
- name: Software Verde
  url: https://www.softwareverde.com
  img: SoftwareVerde.png
  bch: true
  btc: false
  othercrypto: false
  twitter: softwareverde
  facebook: softwareverde
  email_address: value@softwareverde.com
  region: na
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://lh3.googleusercontent.com/-oAiumtKhg9k/AAAAAAAAAAI/AAAAAAAAAAA/GBrQdAn12X0/s44-p-k-no-ns-nd/photo.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/902899443787210753/GsUKUDBI_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/softwareverde/picture)
[Link to Software Verde](https://www.softwareverde.com)
Check their Twitter Page: [twitter.com/softwareverde](https://twitter.com/softwareverde)
Check their Facebook Page: [fb.com/softwareverde](https://fb.com/softwareverde)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.softwareverde.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.softwareverde.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.softwareverde.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
