### ISSUE TITLE
Add 'Varidata' to the 'Dedicated Server Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2094]
Requesting to add 'Varidata' to the 'Dedicated Server Hosting' category. 

Details follow: 
```yml 
- name: Varidata
  url: https://www.varidata.com/
  img: Varidata.png
  bch: false
  btc: false
  othercrypto: true
  twitter: no
  facebook: no
  email_address: sales@varidata.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.varidata.com/wp-content/uploads/2021/09/varidata_logo_white_-748x480_hor_web-1.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1485978381141176323/C46g-pe3_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/no/picture)
[Link to Varidata](https://www.varidata.com/)
Check their Twitter Page: [twitter.com/no](https://twitter.com/no)
Check their Facebook Page: [fb.com/no](https://fb.com/no)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.varidata.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.varidata.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.varidata.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
