### ISSUE TITLE
Add 'Nestor diaz' to the 'Bsc' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2095]
Requesting to add 'Nestor diaz' to the 'Bsc' category. 

Details follow: 
```yml 
- name: Nestor diaz
  url: www.google.com.ve
  img: Nestordiaz.png
  bch: true
  btc: true
  othercrypto: true
  twitter: nestordiaz76
  facebook: nestordiaz76
  email_address: nestordiaz76@gmail.com
  region: sa
  country: VE
  city: Caicara de maturin monagas 
  exceptions:
    text: "Bnb,btc"
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1482205363411820545/Qs0Z1ZjF_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/nestordiaz76/picture)
[Link to Nestor diaz](www.google.com.ve)
Check their Twitter Page: [twitter.com/nestordiaz76](https://twitter.com/nestordiaz76)
Check their Facebook Page: [fb.com/nestordiaz76](https://fb.com/nestordiaz76)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.google.com.ve)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.google.com.ve)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.google.com.ve)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @neno76
Request made by Twitter user [nestordiaz76](https://twitter.com/nestordiaz76/), be sure to send out a tweet when this request has been added.
