### ISSUE TITLE
Add 'Keyante James' to the 'Trading ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2098]
Requesting to add 'Keyante James' to the 'Trading ' category. 

Details follow: 
```yml 
- name: Keyante James
  url: bitcom.com/my account
  img: KeyanteJames.png
  bch: true
  btc: true
  othercrypto: true
  email_address: keyantejames825@gmail.com
  country: US
  city: Doyline
```

Resources for adding this merchant:
[Link to Keyante James](bitcom.com/my account)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitcom.com/my account)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitcom.com/my account)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitcom.com/my account)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @keekee
