### ISSUE TITLE
Add 'Sagil' to the 'Luxury Watches Jewlery Houseware and Decoration ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2100]
Requesting to add 'Sagil' to the 'Luxury Watches Jewlery Houseware and Decoration ' category. 

Details follow: 
```yml 
- name: Sagil
  url: https://sagilparis.com/
  img: Sagil.png
  bch: true
  btc: false
  othercrypto: true
  facebook: sagilparis
  email_address: sagilshop@gmail.com
  city: Paris
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0257/8238/6767/files/Artboard_1_200x@2x.jpg?v=1588593504)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/sagilparis/picture)
[Link to Sagil](https://sagilparis.com/)
Check their Facebook Page: [fb.com/sagilparis](https://fb.com/sagilparis)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/sagilparis.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/sagilparis.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/sagilparis.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
