### ISSUE TITLE
Add 'Bitcoin Recarga' to the 'Phone' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2101]
Requesting to add 'Bitcoin Recarga' to the 'Phone' category. 

Details follow: 
```yml 
- name: Bitcoin Recarga
  url: http://bitcoinrecarga.pe/
  img: BitcoinRecarga.png
  bch: true
  btc: true
  othercrypto: true
  facebook: web.bitcoinrecarga
  email_address: bitcoinrecarga@gmail.com
  region: sa
  country: PE
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://bitcoinrecarga.pe/img/logotipo.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/web.bitcoinrecarga/picture)
[Link to Bitcoin Recarga](http://bitcoinrecarga.pe/)
Check their Facebook Page: [fb.com/web.bitcoinrecarga](https://fb.com/web.bitcoinrecarga)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitcoinrecarga.pe/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitcoinrecarga.pe/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitcoinrecarga.pe/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [bitcoinrecarga](https://twitter.com/bitcoinrecarga/), be sure to send out a tweet when this request has been added.
