### ISSUE TITLE
Add 'Testandtren.com' to the 'Cosmetics ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2102]
Requesting to add 'Testandtren.com' to the 'Cosmetics ' category. 

Details follow: 
```yml 
- name: Testandtren.com
  url: https://testandtren.com/
  img: Testandtrencom.png
  bch: true
  btc: false
  othercrypto: true
  email_address: jwardell1212@icloud.com
  country: US
  city: No
  exceptions:
    text: "Order number (found on the order confirmation page after placing an order)
Name with which the order was placed
Intended email address used to place the order
Billing address or zip code
Article number/s ordered"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://testandtren.com/)
[Link to Testandtren.com](https://testandtren.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/testandtren.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/testandtren.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/testandtren.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
