### ISSUE TITLE
Add 'Edgar Esteban Escamilla Ramírez' to the 'Grasias' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2104]
Requesting to add 'Edgar Esteban Escamilla Ramírez' to the 'Grasias' category. 

Details follow: 
```yml 
- name: Edgar Esteban Escamilla Ramírez
  url: eescamillaramirez0@gmail.com
  img: EdgarEstebanEscamillaRamrez.png
  bch: true
  btc: true
  othercrypto: true
  facebook: edgarestebanescamillaramírez
  email_address: eescamillaramirez0@gmail.com
  country: ZA
  city: México
  exceptions:
    text: "Edgar Esteban Escamilla Ramírez"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](eescamillaramirez0@gmail.com)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/edgarestebanescamillaramírez/picture)
[Link to Edgar Esteban Escamilla Ramírez](eescamillaramirez0@gmail.com)
Check their Facebook Page: [fb.com/edgarestebanescamillaramírez](https://fb.com/edgarestebanescamillaramírez)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/eescamillaramirez0@gmail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/eescamillaramirez0@gmail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/eescamillaramirez0@gmail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @edgaresteban
Request made by Twitter user [edgarestebanescamillaramírez](https://twitter.com/edgarestebanescamillaramírez/), be sure to send out a tweet when this request has been added.
