### ISSUE TITLE
Add 'Goblis Foundation' to the 'Nonprofit' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2105]
Requesting to add 'Goblis Foundation' to the 'Nonprofit' category. 

Details follow: 
```yml 
- name: Goblis Foundation
  url: https://www.goblisfoundation.org/
  img: GoblisFoundation.png
  bch: true
  btc: true
  othercrypto: true
  twitter: goblisfound
  facebook: goblisfoundation
  email_address: donations@goblisfoundation.org
  region: af
  country: KE
  doc: https://www.goblisfoundation.org/donate/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.goblisfoundation.org/wp-content/uploads/2020/09/FullLogo_NoBuffer-1.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1205832194456981505/09oKDlQ7_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/goblisfoundation/picture)
[Link to Goblis Foundation](https://www.goblisfoundation.org/)
Check their Twitter Page: [twitter.com/goblisfound](https://twitter.com/goblisfound)
Check their Facebook Page: [fb.com/goblisfoundation](https://fb.com/goblisfoundation)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.goblisfoundation.org/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.goblisfoundation.org/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.goblisfoundation.org/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [iwaithakaw](https://twitter.com/iwaithakaw/), be sure to send out a tweet when this request has been added.
