### ISSUE TITLE
Add 'High Fidelity' to the ' Apparel & Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2108]
Requesting to add 'High Fidelity' to the ' Apparel & Accessories' category. 

Details follow: 
```yml 
- name: High Fidelity
  url: https://highfidelity.us
  img: HighFidelity.png
  bch: true
  btc: true
  othercrypto: true
  twitter: highfidelityus
  facebook: highfidelity.us
  email_address: support@highfidelity.us
  region: na
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0507/3476/0142/files/HiFi-23_400x400.png?v=1613496307)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1391465001223966728/0Ew3vQtU_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/highfidelity.us/picture)
[Link to High Fidelity](https://highfidelity.us)
Check their Twitter Page: [twitter.com/highfidelityus](https://twitter.com/highfidelityus)
Check their Facebook Page: [fb.com/highfidelity.us](https://fb.com/highfidelity.us)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/highfidelity.us)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/highfidelity.us)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/highfidelity.us)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
