### ISSUE TITLE
Add 'WagerWeb.eu' to the 'Sports Betting, Casino' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2109]
Requesting to add 'WagerWeb.eu' to the 'Sports Betting, Casino' category. 

Details follow: 
```yml 
- name: WagerWeb.eu
  url: https://www.wagerweb.eu
  img: WagerWebeu.png
  bch: true
  btc: false
  othercrypto: true
  facebook: wagerwebnet
  email_address: affiliates@wagerweb.com
  region: na
  exceptions:
    text: "Open an account"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://img.pr.com/release/1304/254995/pressrelease_254995_1366828143.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/wagerwebnet/picture)
[Link to WagerWeb.eu](https://www.wagerweb.eu)
Check their Facebook Page: [fb.com/wagerwebnet](https://fb.com/wagerwebnet)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.wagerweb.eu)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.wagerweb.eu)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.wagerweb.eu)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @n/a
