### ISSUE TITLE
Add 'NearlyFreeSpeech.NET' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2110]
Requesting to add 'NearlyFreeSpeech.NET' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: NearlyFreeSpeech.NET
  url: https://www.nearlyfreespeech.net/
  img: NearlyFreeSpeechNET.png
  bch: false
  btc: false
  othercrypto: false
  doc: https://www.nearlyfreespeech.net/about/faq#Payment
  exceptions:
    text: "To clarify: NearlyFreeSpeech.NET has not supported any cryptocurrency for quite some time now, and they have no plans to return."
```

Resources for adding this merchant:
[Link to NearlyFreeSpeech.NET](https://www.nearlyfreespeech.net/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.nearlyfreespeech.net/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.nearlyfreespeech.net/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.nearlyfreespeech.net/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
