### ISSUE TITLE
Add 'BestBuyRdp' to the 'Web-Hosting VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2113]
Requesting to add 'BestBuyRdp' to the 'Web-Hosting VPS' category. 

Details follow: 
```yml 
- name: BestBuyRdp
  url: https://bestbuyrdp.com
  img: BestBuyRdp.png
  bch: true
  btc: true
  othercrypto: true
  twitter: bestbuyrdp1
  facebook: bestbuyrdp
  email_address: bestbuyrdp@gmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://p183.p1.n0.cdn.getcloudapp.com/items/WnuyLwDO/9963d51c-2c82-4152-aa18-1f2ec56cd2d3.jpeg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1525884952512184321/u6sOQa-M_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/bestbuyrdp/picture)
[Link to BestBuyRdp](https://bestbuyrdp.com)
Check their Twitter Page: [twitter.com/bestbuyrdp1](https://twitter.com/bestbuyrdp1)
Check their Facebook Page: [fb.com/bestbuyrdp](https://fb.com/bestbuyrdp)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bestbuyrdp.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bestbuyrdp.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bestbuyrdp.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
