### ISSUE TITLE
Add 'Salasiah binti matsaad' to the 'Food service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2114]
Requesting to add 'Salasiah binti matsaad' to the 'Food service' category. 

Details follow: 
```yml 
- name: Salasiah binti matsaad
  url: httpa//url.salasiah.net
  img: Salasiahbintimatsaad.png
  bch: true
  btc: true
  othercrypto: false
  twitter: zulhelmi86
  facebook: salasiahmatsaad18
  email_address: mzulhelmisalasiah@gmail.com
  country: MY
  city: Selama
  exceptions:
    text: "No payment i can finance"
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/2423717990/Destop_322_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/salasiahmatsaad18/picture)
[Link to Salasiah binti matsaad](httpa//url.salasiah.net)
Check their Twitter Page: [twitter.com/zulhelmi86](https://twitter.com/zulhelmi86)
Check their Facebook Page: [fb.com/salasiahmatsaad18](https://fb.com/salasiahmatsaad18)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/httpa//url.salasiah.net)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/httpa//url.salasiah.net)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/httpa//url.salasiah.net)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @mzulhelmisalasiahgmail.com
Request made by Twitter user [mohdzul98969266](https://twitter.com/mohdzul98969266/), be sure to send out a tweet when this request has been added.
