### ISSUE TITLE
Add 'WeebCastle' to the 'Mood Lamps' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2116]
Requesting to add 'WeebCastle' to the 'Mood Lamps' category. 

Details follow: 
```yml 
- name: WeebCastle
  url: https://www.weebcastle.com
  img: WeebCastle.png
  bch: true
  btc: true
  othercrypto: true
  twitter: weebcastlelamps
  facebook: weebcastle
  email_address: info@weebcastle.com
  doc: https://twitter.com/_minisatoshi/status/1529517700350869506?s=20&t=LQozkvbZ0Pppu0AfwG0SpA
  exceptions:
    text: "Just go to checkout and there will be an option to select Pay with Coinbase Commerce, then just select Bitcoin Cash!"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0545/0206/4315/files/Weebcastle_logo_bbf1888d-0ecc-4dce-a32d-1f7ca3228009_x70@2x.png?v=1614120097)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1526938394546274306/q7XOeAEE_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/weebcastle/picture)
[Link to WeebCastle](https://www.weebcastle.com)
Check their Twitter Page: [twitter.com/weebcastlelamps](https://twitter.com/weebcastlelamps)
Check their Facebook Page: [fb.com/weebcastle](https://fb.com/weebcastle)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.weebcastle.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.weebcastle.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.weebcastle.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [minisatoshi](https://twitter.com/minisatoshi/), be sure to send out a tweet when this request has been added.
