### ISSUE TITLE
WeebCastle now accepts Bitcoin Cash!

### ISSUE THREAD

**Issue by minisat0shi** [acceptbitcoincash/acceptbitcoincash#2117]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Weeb Castle**}} to the {{**Art & Design**}} category. Details follow:

```yml

- name: WeebCastle
  url: https://www.weebcastle.com
  img: https://cdn.shopify.com/s/files/1/0545/0206/4315/files/Weebcastle_logo_bbf1888d-0ecc-4dce-a32d-1f7ca3228009_x70@2x.png?v=1614120097
  twitter: weebcastlelamps
  facebook: https://www.facebook.com/weebcastle/
  region: Global
  country: N/A
  city: N/A
  bch: yes
  bsv: no
  btc: yes
  othercrypto: yes
  doc: https://twitter.com/_minisatoshi/status/1529517700350869506?s=20&t=ArVMqui2APGMtDkWORIILA
  keywords:
  - mood
  - lamp
  - anime
  - waifu
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
