### ISSUE TITLE
Add 'Chantelle' to the 'Trading life' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2118]
Requesting to add 'Chantelle' to the 'Trading life' category. 

Details follow: 
```yml 
- name: Chantelle
  url: c.s.may
  img: Chantelle.png
  bch: true
  btc: true
  othercrypto: true
  facebook: maychantelle95gmail.com
  email_address: maychantelle95@gmail.com
  region: sa
  country: ZA
  city: Cape Town
  exceptions:
    text: "Mo"
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/maychantelle95gmail.com/picture)
[Link to Chantelle](c.s.may)
Check their Facebook Page: [fb.com/maychantelle95gmail.com](https://fb.com/maychantelle95gmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/c.s.may)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/c.s.may)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/c.s.may)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @chantelle
