### ISSUE TITLE
Add 'Esporas Mexico' to the 'Spores Fungiculture' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2119]
Requesting to add 'Esporas Mexico' to the 'Spores Fungiculture' category. 

Details follow: 
```yml 
- name: Esporas Mexico
  url: www.esporasmexico.com
  img: EsporasMexico.png
  bch: true
  btc: true
  othercrypto: true
  email_address: esporasmexico@protonmail.com
  region: na
  country: MX
```

Resources for adding this merchant:
[Link to Esporas Mexico](www.esporasmexico.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.esporasmexico.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.esporasmexico.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.esporasmexico.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
