### ISSUE TITLE
Add 'Cannabox' to the 'smoking accessories ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2120]
Requesting to add 'Cannabox' to the 'smoking accessories ' category. 

Details follow: 
```yml 
- name: Cannabox
  url: https://www.cannabox.com
  img: Cannabox.png
  bch: false
  btc: false
  othercrypto: true
  twitter: cannabox
  facebook: cannabox
  email_address: mike@cannabox.com
  region: na
  country: US
  city: n/a
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.cannabox.com/cropped-logo-png/)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1201235630165901312/3n-buceY_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/cannabox/picture)
[Link to Cannabox](https://www.cannabox.com)
Check their Twitter Page: [twitter.com/cannabox](https://twitter.com/cannabox)
Check their Facebook Page: [fb.com/cannabox](https://fb.com/cannabox)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.cannabox.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.cannabox.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.cannabox.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
