### ISSUE TITLE
Add 'Izzy's Koala World' to the 'Public Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2121]
Requesting to add 'Izzy's Koala World' to the 'Public Services' category. 

Details follow: 
```yml 
- name: Izzy's Koala World
  url: https://www.facebook.com/izzyskoalaworld
  img: IzzysKoalaWorld.png
  bch: true
  btc: true
  othercrypto: true
  twitter: alibee3184
  facebook: izzyskoalaworld
  email_address: maggievet@bigpond.com
  region: oc
  country: AU
  city: Magnetic Island
  doc: https://youtu.be/cZvM70W1M5A
  exceptions:
    text: "qz7qg4s2yjcn302wsz52tlew7e4j3pngjcnfsu8hfm"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1444546942667608067/mHZ7ry6r_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1444546942667608067/mHZ7ry6r_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/izzyskoalaworld/picture)
[Link to Izzy's Koala World](https://www.facebook.com/izzyskoalaworld)
Check their Twitter Page: [twitter.com/alibee3184](https://twitter.com/alibee3184)
Check their Facebook Page: [fb.com/izzyskoalaworld](https://fb.com/izzyskoalaworld)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.facebook.com/izzyskoalaworld)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.facebook.com/izzyskoalaworld)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.facebook.com/izzyskoalaworld)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [alibee3184](https://twitter.com/alibee3184/), be sure to send out a tweet when this request has been added.
