### ISSUE TITLE
Add 'Hungry Dog Pet Supplies' to the 'Pets & Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2122]
Requesting to add 'Hungry Dog Pet Supplies' to the 'Pets & Services' category. 

Details follow: 
```yml 
- name: Hungry Dog Pet Supplies
  url: https://www.google.com.au/maps/place/Hungry+Dog+Pet+Supplies/@-19.2456025,146.6736637,16.71z/data=!3m1!5s0x6bd5f6f2e4773bfb:0x55f0c5888fc7c5b0!4m5!3m4!1s0x6bd5f7d10d051f2b:0x1d2eb4c349df9435!8m2!3d-19.2458453!4d146.6752947?hl=en-GB&authuser=0
  img: HungryDogPetSupplies.png
  bch: true
  btc: true
  othercrypto: false
  facebook: hungry-dog-pet-supplies-100273979028306
  email_address: admin@hungrydogpetsupplies.com.au
  region: oc
  country: AU
  city: Townsville
  doc: https://youtu.be/07npcew1F_o
  exceptions:
    text: "In Stall Purchase"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://scontent-syd2-1.xx.fbcdn.net/v/t39.30808-6/234303939_100680315654339_2052045276984229235_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=m7DtBxH3XOYAX_YPWUx&tn=TZ64AOveFaO-jlF4&_nc_ht=scontent-syd2-1.xx&oh=00_AT8g3DRKSE4IOfcApvNUnaFlymUnlW31lmiI7rEE2MzzIg&oe=62A6C78A)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/hungry-dog-pet-supplies-100273979028306/picture)
[Link to Hungry Dog Pet Supplies](https://www.google.com.au/maps/place/Hungry+Dog+Pet+Supplies/@-19.2456025,146.6736637,16.71z/data=!3m1!5s0x6bd5f6f2e4773bfb:0x55f0c5888fc7c5b0!4m5!3m4!1s0x6bd5f7d10d051f2b:0x1d2eb4c349df9435!8m2!3d-19.2458453!4d146.6752947?hl=en-GB&authuser=0)
Check their Facebook Page: [fb.com/hungry-dog-pet-supplies-100273979028306](https://fb.com/hungry-dog-pet-supplies-100273979028306)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.google.com.au/maps/place/Hungry+Dog+Pet+Supplies/@-19.2456025,146.6736637,16.71z/data=!3m1!5s0x6bd5f6f2e4773bfb:0x55f0c5888fc7c5b0!4m5!3m4!1s0x6bd5f7d10d051f2b:0x1d2eb4c349df9435!8m2!3d-19.2458453!4d146.6752947?hl=en-GB&authuser=0)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.google.com.au/maps/place/Hungry+Dog+Pet+Supplies/@-19.2456025,146.6736637,16.71z/data=!3m1!5s0x6bd5f6f2e4773bfb:0x55f0c5888fc7c5b0!4m5!3m4!1s0x6bd5f7d10d051f2b:0x1d2eb4c349df9435!8m2!3d-19.2458453!4d146.6752947?hl=en-GB&authuser=0)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.google.com.au/maps/place/Hungry+Dog+Pet+Supplies/@-19.2456025,146.6736637,16.71z/data=!3m1!5s0x6bd5f6f2e4773bfb:0x55f0c5888fc7c5b0!4m5!3m4!1s0x6bd5f7d10d051f2b:0x1d2eb4c349df9435!8m2!3d-19.2458453!4d146.6752947?hl=en-GB&authuser=0)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
