### ISSUE TITLE
Add 'Cameron & Co Dentist' to the 'Professional Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2123]
Requesting to add 'Cameron & Co Dentist' to the 'Professional Services' category. 

Details follow: 
```yml 
- name: Cameron & Co Dentist
  url: https://www.google.com/maps/place/Cameron+and+Co+Dental+Townsville/@-19.2951102,146.7768379,17z/data=!3m1!4b1!4m5!3m4!1s0x6bd5f984200af7a9:0x2d3bb934eb01dbda!8m2!3d-19.2951102!4d146.7790266?hl=en-US
  img: CameronCoDentist.png
  bch: true
  btc: false
  othercrypto: false
  facebook: cameronandcodental
  email_address: hello@cameronandco.com.au
  region: oc
  country: AU
  city: Townsville
  doc: https://youtu.be/VrR8E7bGtCQ
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://images.squarespace-cdn.com/content/v1/5e6a99c7bf77f1191c3da4f9/1584046788828-H2OVZ6BZQKX37V28R6YR/CameronandCologo1000px+black.png?format=1500w)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/cameronandcodental/picture)
[Link to Cameron & Co Dentist](https://www.google.com/maps/place/Cameron+and+Co+Dental+Townsville/@-19.2951102,146.7768379,17z/data=!3m1!4b1!4m5!3m4!1s0x6bd5f984200af7a9:0x2d3bb934eb01dbda!8m2!3d-19.2951102!4d146.7790266?hl=en-US)
Check their Facebook Page: [fb.com/cameronandcodental](https://fb.com/cameronandcodental)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.google.com/maps/place/Cameron+and+Co+Dental+Townsville/@-19.2951102,146.7768379,17z/data=!3m1!4b1!4m5!3m4!1s0x6bd5f984200af7a9:0x2d3bb934eb01dbda!8m2!3d-19.2951102!4d146.7790266?hl=en-US)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.google.com/maps/place/Cameron+and+Co+Dental+Townsville/@-19.2951102,146.7768379,17z/data=!3m1!4b1!4m5!3m4!1s0x6bd5f984200af7a9:0x2d3bb934eb01dbda!8m2!3d-19.2951102!4d146.7790266?hl=en-US)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.google.com/maps/place/Cameron+and+Co+Dental+Townsville/@-19.2951102,146.7768379,17z/data=!3m1!4b1!4m5!3m4!1s0x6bd5f984200af7a9:0x2d3bb934eb01dbda!8m2!3d-19.2951102!4d146.7790266?hl=en-US)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
