### ISSUE TITLE
Add 'EcoBIM CONSTRUCTION' to the 'Maîtrise d'oeuvre' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2124]
Requesting to add 'EcoBIM CONSTRUCTION' to the 'Maîtrise d'oeuvre' category. 

Details follow: 
```yml 
- name: EcoBIM CONSTRUCTION
  url: www.ecobimconstruction.fr
  img: EcoBIMCONSTRUCTION.png
  bch: true
  btc: true
  othercrypto: true
  email_address: contact@ecobimconstruction.fr
  region: eu
  country: FR
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i0.wp.com/www.ecobimconstruction.fr/wp-content/uploads/2022/03/Plan-de-travail-13-copie-6-1.png?w=645&ssl=1)
[Link to EcoBIM CONSTRUCTION](www.ecobimconstruction.fr)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ecobimconstruction.fr)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ecobimconstruction.fr)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ecobimconstruction.fr)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
