### ISSUE TITLE
Add 'CooliceHost' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2125]
Requesting to add 'CooliceHost' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: CooliceHost
  url: https://coolicehost.com/
  img: CooliceHost.png
  bch: true
  btc: true
  othercrypto: true
  facebook: coolicehost
  email_address: office@coolicehost.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://coolicehost.com/assets/img/logo.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/coolicehost/picture)
[Link to CooliceHost](https://coolicehost.com/)
Check their Facebook Page: [fb.com/coolicehost](https://fb.com/coolicehost)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/coolicehost.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/coolicehost.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/coolicehost.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
