### ISSUE TITLE
Add 'Knockerball Saint Louis' to the 'Entertainment rental' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2126]
Requesting to add 'Knockerball Saint Louis' to the 'Entertainment rental' category. 

Details follow: 
```yml 
- name: Knockerball Saint Louis
  url: knockerballstlouis.com
  img: KnockerballSaintLouis.png
  bch: true
  btc: true
  othercrypto: true
  facebook: knockerballstlouis
  email_address: knockerballsaintlouis@gmail.com
  region: na
  country: US
  city: St. Louis
  exceptions:
    text: "Nothing specific other than standard procedure"
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/knockerballstlouis/picture)
[Link to Knockerball Saint Louis](knockerballstlouis.com)
Check their Facebook Page: [fb.com/knockerballstlouis](https://fb.com/knockerballstlouis)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/knockerballstlouis.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/knockerballstlouis.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/knockerballstlouis.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
