### ISSUE TITLE
Add 'Salahuddin Ayyubi Foundation' to the 'Donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2127]
Requesting to add 'Salahuddin Ayyubi Foundation' to the 'Donations' category. 

Details follow: 
```yml 
- name: Salahuddin Ayyubi Foundation
  url: https://cryptorelief.salahuddinayyubi.org
  img: SalahuddinAyyubiFoundation.png
  bch: true
  btc: false
  othercrypto: true
  twitter: saf_foundation_
  facebook: salahuddinayyubifoundation
  email_address: contact@salahuddinayyubi.org
  country: IN
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1463519988464054277/Bp1hIvni_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/salahuddinayyubifoundation/picture)
[Link to Salahuddin Ayyubi Foundation](https://cryptorelief.salahuddinayyubi.org)
Check their Twitter Page: [twitter.com/saf_foundation_](https://twitter.com/saf_foundation_)
Check their Facebook Page: [fb.com/salahuddinayyubifoundation](https://fb.com/salahuddinayyubifoundation)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cryptorelief.salahuddinayyubi.org)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cryptorelief.salahuddinayyubi.org)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cryptorelief.salahuddinayyubi.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
