### ISSUE TITLE
Add 'Cloudzy' to the 'VPS hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2129]
Requesting to add 'Cloudzy' to the 'VPS hosting' category. 

Details follow: 
```yml 
- name: Cloudzy
  url: cloudzy.com
  img: Cloudzy.png
  bch: true
  btc: true
  othercrypto: true
  email_address: david@cloudzy.com
  doc: https://cloudzy.com/anonymous-vps/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cloudzy.com/wp-content/uploads/cropped-cloudzy_logo-1.png)
[Link to Cloudzy](cloudzy.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cloudzy.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cloudzy.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cloudzy.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
