### ISSUE TITLE
Add 'Troop Messenger' to the 'Software and Application' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2130]
Requesting to add 'Troop Messenger' to the 'Software and Application' category. 

Details follow: 
```yml 
- name: Troop Messenger
  url: https://www.troopmessenger.com/
  img: TroopMessenger.png
  bch: false
  btc: false
  othercrypto: true
  twitter: troopmessenger
  facebook: troopmessenger
  email_address: asloobalam8@gmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.troopmessenger.com/img/home-images/logo.svg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1430843057272881158/RyV2DMWj_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/troopmessenger/picture)
[Link to Troop Messenger](https://www.troopmessenger.com/)
Check their Twitter Page: [twitter.com/troopmessenger](https://twitter.com/troopmessenger)
Check their Facebook Page: [fb.com/troopmessenger](https://fb.com/troopmessenger)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.troopmessenger.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.troopmessenger.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.troopmessenger.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
