### ISSUE TITLE
Add 'Skytoken' to the 'TOKEN ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2131]
Requesting to add 'Skytoken' to the 'TOKEN ' category. 

Details follow: 
```yml 
- name: Skytoken
  url: http://skybo4393365.sitebuilder.name.tools/
  img: Skytoken.png
  bch: true
  btc: true
  othercrypto: true
  facebook: charlie_wilsom
  email_address: skycommunitytoken@gmail.com
  region: eu
  city: Texas
  doc: http://bitcoininvestmensworld.tumblr.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://skybo4393365.sitebuilder.name.tools/)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/charlie_wilsom/picture)
[Link to Skytoken](http://skybo4393365.sitebuilder.name.tools/)
Check their Facebook Page: [fb.com/charlie_wilsom](https://fb.com/charlie_wilsom)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/skybo4393365.sitebuilder.name.tools/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/skybo4393365.sitebuilder.name.tools/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/skybo4393365.sitebuilder.name.tools/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
