### ISSUE TITLE
Add 'Tasteless' to the 'Adult Shops' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2132]
Requesting to add 'Tasteless' to the 'Adult Shops' category. 

Details follow: 
```yml 
- name: Tasteless
  url: tasteless.io
  img: Tasteless.png
  bch: false
  btc: false
  othercrypto: false
  city: Existing listing, domain for sale.
```

Resources for adding this merchant:
[Link to Tasteless](tasteless.io)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/tasteless.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/tasteless.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/tasteless.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
