### ISSUE TITLE
Add 'ServerWhere' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2135]
Requesting to add 'ServerWhere' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: ServerWhere
  url: https://www.serverwhere.com/
  img: ServerWhere.png
  bch: true
  btc: true
  othercrypto: true
  twitter: serverwhere
  facebook: serverwhere
  email_address: mail@serverwhere.com
  city: No
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://twitter.com/serverwhere/photo)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1371170523435122690/C2gANU5Y_normal.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/serverwhere/picture)
[Link to ServerWhere](https://www.serverwhere.com/)
Check their Twitter Page: [twitter.com/serverwhere](https://twitter.com/serverwhere)
Check their Facebook Page: [fb.com/serverwhere](https://fb.com/serverwhere)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.serverwhere.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.serverwhere.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.serverwhere.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @nogithubaccount
Request made by Twitter user [dimitaravramov](https://twitter.com/dimitaravramov/), be sure to send out a tweet when this request has been added.
