### ISSUE TITLE
Add 'Servers Guru' to the 'Hosting providers' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2136]
Requesting to add 'Servers Guru' to the 'Hosting providers' category. 

Details follow: 
```yml 
- name: Servers Guru
  url: https://servers.guru
  img: ServersGuru.png
  bch: true
  btc: true
  othercrypto: true
  email_address: contact@servers.guru
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://servers.guru/wp-content/uploads/2021/07/cropped-favicon-2.png)
[Link to Servers Guru](https://servers.guru)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/servers.guru)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/servers.guru)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/servers.guru)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
