### ISSUE TITLE
Add 'Namsat Systems Accounting' to the 'Accounting services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2137]
Requesting to add 'Namsat Systems Accounting' to the 'Accounting services' category. 

Details follow: 
```yml 
- name: Namsat Systems Accounting
  url: https://namsat.biz/
  img: NamsatSystemsAccounting.png
  bch: true
  btc: true
  othercrypto: false
  email_address: tas@namsat.biz
  region: oc
  country: AU
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://namsat.biz/wp-content/uploads/2021/06/Namsat-logo_600.png)
[Link to Namsat Systems Accounting](https://namsat.biz/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/namsat.biz/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/namsat.biz/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/namsat.biz/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
