### ISSUE TITLE
Add 'buy-clash' to the 'Clash of Clans account, Video Games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2138]
Requesting to add 'buy-clash' to the 'Clash of Clans account, Video Games' category. 

Details follow: 
```yml 
- name: buy-clash
  url: https://buy-clash.com/
  img: buyclash.png
  bch: true
  btc: true
  othercrypto: true
  twitter: buy_clash
  email_address: support@buy-clash.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://buy-clash.com/wp-content/uploads/2020/08/logo-buyclash.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1293844286895783937/lHURzxiZ_normal.jpg)
[Link to buy-clash](https://buy-clash.com/)
Check their Twitter Page: [twitter.com/buy_clash](https://twitter.com/buy_clash)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/buy-clash.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/buy-clash.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/buy-clash.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
