### ISSUE TITLE
Add 'Lynda San' to the 'Gambling - Sportsbook & Casino' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2140]
Requesting to add 'Lynda San' to the 'Gambling - Sportsbook & Casino' category. 

Details follow: 
```yml 
- name: Lynda San
  url: https://www.wagerweb.eu
  img: LyndaSan.png
  bch: true
  btc: true
  othercrypto: true
  email_address: csd@wagerweb.com
  region: na
```

Resources for adding this merchant:
[Link to Lynda San](https://www.wagerweb.eu)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.wagerweb.eu)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.wagerweb.eu)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.wagerweb.eu)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
