### ISSUE TITLE
Add 'Fast Solar Permit Services' to the 'Renewable Energy ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2142]
Requesting to add 'Fast Solar Permit Services' to the 'Renewable Energy ' category. 

Details follow: 
```yml 
- name: Fast Solar Permit Services
  url: https://fastsolarpermitservices.com
  img: FastSolarPermitServices.png
  bch: true
  btc: true
  othercrypto: true
  facebook: fastsolarpermitservices
  email_address: fastsolarpermitservices@gmail.com
  region: na
  country: US
  city: All cities
  doc: https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Ffastsolarpermitservices%2Fposts%2Fpfbid021Xg6AJWNDm6yWDbpbG87sW6DnVG2fQEne9KRqWYoqvTXwWBDdb5tcwjhDusJjJL2l
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://fastsolarpermitservices.com/wp-content/uploads/2022/06/fast-solar-permit-services-small-png-logo.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/fastsolarpermitservices/picture)
[Link to Fast Solar Permit Services](https://fastsolarpermitservices.com)
Check their Facebook Page: [fb.com/fastsolarpermitservices](https://fb.com/fastsolarpermitservices)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/fastsolarpermitservices.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/fastsolarpermitservices.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/fastsolarpermitservices.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
