### ISSUE TITLE
Add 'Elis' to the 'Sports shoes' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2143]
Requesting to add 'Elis' to the 'Sports shoes' category. 

Details follow: 
```yml 
- name: Elis
  url: https://elissports.com/
  img: Elis.png
  bch: true
  btc: true
  othercrypto: true
  twitter: elis_sportsuk
  facebook: elissportsuk
  email_address: info@elissports.com
  region: eu
  doc: https://elissports.com/blogs/news/pay-at-elis-sports-with-cryptocurrencies
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1549747573849837568/rARJyjDb.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1549747573849837568/rARJyjDb_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/elissportsuk/picture)
[Link to Elis](https://elissports.com/)
Check their Twitter Page: [twitter.com/elis_sportsuk](https://twitter.com/elis_sportsuk)
Check their Facebook Page: [fb.com/elissportsuk](https://fb.com/elissportsuk)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/elissports.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/elissports.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/elissports.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [elis_sportsuk](https://twitter.com/elis_sportsuk/), be sure to send out a tweet when this request has been added.
