### ISSUE TITLE
Add 'Buy-clash' to the 'Gaming' category

### ISSUE THREAD

**Issue by Buy-clash** [acceptbitcoincash/acceptbitcoincash#2144]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Buy-clash**}} to the {{**Gaming**}} category. Details follow:

```yml

- name: Buy-clash
  url: https://buy-clash.com/
  img: [URL_to_image](https://buy-clash.com/wp-content/uploads/2022/07/buyclash.png)
  twitter: buy_clash
  region: na
  country: US
  bch: yes
  bsv: no
  btc: yes
  othercrypto: yes
  keywords:
  - buy clash of clans account
  - Clash of Clans account for sale
```
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/buy-clash.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/buy-clash.com/)
