### ISSUE TITLE
Add 'Saskatchewn' to the 'Bitcoin ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2149]
Requesting to add 'Saskatchewn' to the 'Bitcoin ' category. 

Details follow: 
```yml 
- name: Saskatchewn
  url: https://df0289407@gmail.com
  img: Saskatchewn.png
  bch: true
  btc: false
  othercrypto: false
  email_address: lovenohate40@gmail.coml
  country: RE
  doc: Https://bitcoinar
  exceptions:
    text: "Visa"
```

Resources for adding this merchant:
[Link to Saskatchewn](https://df0289407@gmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/df0289407@gmail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/df0289407@gmail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/df0289407@gmail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @dghostly
