### ISSUE TITLE
Add 'Private WebHost' to the 'Cloud Computing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2152]
Requesting to add 'Private WebHost' to the 'Cloud Computing' category. 

Details follow: 
```yml 
- name: Private WebHost
  url: https://privateweb.top/
  img: PrivateWebHost.png
  bch: true
  btc: true
  othercrypto: true
  facebook: theydonotusefacebook.
  email_address: privhost@riseup.net
  doc: https://privateweb.top/index.php?rp=/announcements/17/New-payment-methods-Bitcoin-Litecoin-Bitcoin-Cash-Monero.html
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://privateweb.top/templates/hostino/images/logo.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/theydonotusefacebook./picture)
[Link to Private WebHost](https://privateweb.top/)
Check their Facebook Page: [fb.com/theydonotusefacebook.](https://fb.com/theydonotusefacebook.)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/privateweb.top/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/privateweb.top/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/privateweb.top/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
