### ISSUE TITLE
Add 'Crypto Goodies' to the 'Apparel & Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2154]
Requesting to add 'Crypto Goodies' to the 'Apparel & Accessories' category. 

Details follow: 
```yml 
- name: Crypto Goodies
  url: https://cryptogoodies.shop
  img: CryptoGoodies.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cryptogoodiesx
  facebook: cryptogoodies.shop
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1409589993023094786/Kl0UAEGO_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1409589993023094786/Kl0UAEGO_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/cryptogoodies.shop/picture)
[Link to Crypto Goodies](https://cryptogoodies.shop)
Check their Twitter Page: [twitter.com/cryptogoodiesx](https://twitter.com/cryptogoodiesx)
Check their Facebook Page: [fb.com/cryptogoodies.shop](https://fb.com/cryptogoodies.shop)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cryptogoodies.shop)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cryptogoodies.shop)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cryptogoodies.shop)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
