### ISSUE TITLE
Add 'VPS Makers' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2155]
Requesting to add 'VPS Makers' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: VPS Makers
  url: https://vpsmakers.com
  img: VPSMakers.png
  bch: true
  btc: false
  othercrypto: true
  twitter: vpsmakers
  email_address: info@vpsmakers.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](	https://vpsmakers.com/wp-content/uploads/2022/07/logo-vps-makers-e1661155086312.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1563442159247773697/NwKgcsJ6_normal.png)
[Link to VPS Makers](https://vpsmakers.com)
Check their Twitter Page: [twitter.com/vpsmakers](https://twitter.com/vpsmakers)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/vpsmakers.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/vpsmakers.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/vpsmakers.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
