### ISSUE TITLE
Add 'Foxly URL Shortner' to the 'URL shortner' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2156]
Requesting to add 'Foxly URL Shortner' to the 'URL shortner' category. 

Details follow: 
```yml 
- name: Foxly URL Shortner
  url: https://foxlyme.com/
  img: FoxlyURLShortner.png
  bch: false
  btc: false
  othercrypto: false
  email_address: maxycharl1@gmail.com
  region: as
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.google.com/search?q=foxlyme&sxsrf=ALiCzsaBeBKvdFbFfU0iNEmptNvYXCO2cA:1661969853320&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjA7O-V2PH5AhWmxIsBHc1LDcwQ_AUoA3oECAIQBQ&biw=1920&bih=937&dpr=1#imgrc=O8CKwNv41CC_2M)
[Link to Foxly URL Shortner](https://foxlyme.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/foxlyme.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/foxlyme.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/foxlyme.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
