### ISSUE TITLE
Add 'Wholesale Shopping' to the 'Fashion Clothing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2157]
Requesting to add 'Wholesale Shopping' to the 'Fashion Clothing' category. 

Details follow: 
```yml 
- name: Wholesale Shopping
  url: https://www.wholesaleshopping.co.uk/
  img: WholesaleShopping.png
  bch: false
  btc: false
  othercrypto: false
  email_address: sales@wholesaleshopping.co.uk
  country: GB
  city: no
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.wholesaleshopping.co.uk/)
[Link to Wholesale Shopping](https://www.wholesaleshopping.co.uk/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.wholesaleshopping.co.uk/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.wholesaleshopping.co.uk/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.wholesaleshopping.co.uk/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
