### ISSUE TITLE
Add 'PillenService' to the 'pharma' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2158]
Requesting to add 'PillenService' to the 'pharma' category. 

Details follow: 
```yml 
- name: PillenService
  url: https://pillenservice.com/
  img: PillenService.png
  bch: true
  btc: false
  othercrypto: true
  region: eu
  country: DE
  city: n
```

Resources for adding this merchant:
[Link to PillenService](https://pillenservice.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/pillenservice.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/pillenservice.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/pillenservice.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
