### ISSUE TITLE
Americas Cardroom

### ISSUE THREAD

**Issue by MaFi01** [acceptbitcoincash/acceptbitcoincash#216]
_Please fill in the template below, and don't worry about exact formatting, just do your best!_

Requesting to add {{ Americas Cardroom }} to the {{ Gambling }} category. Details follow:

```yml

- name: Americas Cardroom
  url: https://americascardroom.eu
  twitter: ACR_POKER
  facebook: americascardroomnet
  img: https://americascardroom.eu/images/acreu_account_header_logo.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://www.americascardroom.eu/bitcoin-cash-cryptocurrency/
  exceptions:
    text: "general_comments_or_notes_here___do_not_remove_quotes"
```
