### ISSUE TITLE
Add 'Akankshagurgaon' to the 'Call girls in Gurgaon' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2161]
Requesting to add 'Akankshagurgaon' to the 'Call girls in Gurgaon' category. 

Details follow: 
```yml 
- name: Akankshagurgaon
  url: http://akankshagurgaon.in
  img: Akankshagurgaon.png
  bch: false
  btc: false
  othercrypto: false
  twitter: no
  facebook: no
  email_address: janusigh483@gmail.com
  country: IN
  city: Gurugram Haryana
  exceptions:
    text: "only Cash"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://akankshagurgaon.in)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1485978381141176323/C46g-pe3_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/no/picture)
[Link to Akankshagurgaon](http://akankshagurgaon.in)
Check their Twitter Page: [twitter.com/no](https://twitter.com/no)
Check their Facebook Page: [fb.com/no](https://fb.com/no)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/akankshagurgaon.in)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/akankshagurgaon.in)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/akankshagurgaon.in)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
