### ISSUE TITLE
Add 'ANQ Finance' to the 'Crypto Lending' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2165]
Requesting to add 'ANQ Finance' to the 'Crypto Lending' category. 

Details follow: 
```yml 
- name: ANQ Finance
  url: https://anq.finance/
  img: ANQFinance.png
  bch: true
  btc: true
  othercrypto: true
  twitter: anqfinance
  facebook: anqfinance
  email_address: abhimanyusingh4494@gmail.com
  region: as
  country: IN
  city: No
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://drive.google.com/file/d/1V_rTzt2HzGIjEVfMXFB3f8BctzSOEv0p/view?usp=sharing)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1555919794649681921/ogl-eTyG_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/anqfinance/picture)
[Link to ANQ Finance](https://anq.finance/)
Check their Twitter Page: [twitter.com/anqfinance](https://twitter.com/anqfinance)
Check their Facebook Page: [fb.com/anqfinance](https://fb.com/anqfinance)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/anq.finance/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/anq.finance/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/anq.finance/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [anqfinance](https://twitter.com/anqfinance/), be sure to send out a tweet when this request has been added.
