### ISSUE TITLE
Add 'Cyber Legion' to the 'cyber security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2166]
Requesting to add 'Cyber Legion' to the 'cyber security' category. 

Details follow: 
```yml 
- name: Cyber Legion
  url: https://cyberlegion.io
  img: CyberLegion.png
  bch: true
  btc: true
  othercrypto: true
  twitter: clegion1
  email_address: office@cyberlegion.io
  country: GB
  city: London
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cyberlegion.io/wp-content/uploads/2022/04/cropped-Colorlogo-nobackground_1d3c4ae6144b38be5c6bdfe2c7274288-1.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1510187537767317512/4JIm7Wgy_normal.png)
[Link to Cyber Legion](https://cyberlegion.io)
Check their Twitter Page: [twitter.com/clegion1](https://twitter.com/clegion1)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cyberlegion.io)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cyberlegion.io)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cyberlegion.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
