### ISSUE TITLE
Add 'Dr. Paul Kramer Chiropractor' to the 'Chiropractic Practice' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2168]
Requesting to add 'Dr. Paul Kramer Chiropractor' to the 'Chiropractic Practice' category. 

Details follow: 
```yml 
- name: Dr. Paul Kramer Chiropractor
  url: www.drpaulkramerchiropractor.com
  img: DrPaulKramerChiropractor.png
  bch: true
  btc: true
  othercrypto: true
  email_address: drpaulkramer@gmail.com
  region: na
  country: US
  city: Lisbon, Wisconsin
  exceptions:
    text: "Use at time of payment."
```

Resources for adding this merchant:
[Link to Dr. Paul Kramer Chiropractor](www.drpaulkramerchiropractor.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.drpaulkramerchiropractor.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.drpaulkramerchiropractor.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.drpaulkramerchiropractor.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
