### ISSUE TITLE
Add 'acceptbitcoin.ro' to the 'travel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2169]
Requesting to add 'acceptbitcoin.ro' to the 'travel' category. 

Details follow: 
```yml 
- name: acceptbitcoin.ro
  url: acceptbitcoin.ro
  img: acceptbitcoinro.png
  bch: true
  btc: true
  othercrypto: true
  email_address: arnautoiu.f@gmail.com
  region: eu
  country: RO
  city: Bucuresti Sector 4
```

Resources for adding this merchant:
[Link to acceptbitcoin.ro](acceptbitcoin.ro)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/acceptbitcoin.ro)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/acceptbitcoin.ro)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/acceptbitcoin.ro)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
