### ISSUE TITLE
[adult category] spacefucker forum

### ISSUE THREAD

**Issue by spacefucker** [acceptbitcoincash/acceptbitcoincash#2170]
---------------
Requesting to add SpaceFucker to the Adult -> Sites & Networks category. Details follow:

```yml

- name: Space Fucker
  url: https://www.spacefucker.com/
  img: https://www.spacefucker.com/styles/default/xenforo/sflogo5.png
  twitter: https://twitter.com/spacefuckercom
  region: worldwide
  bch: yes
  bsv: no
  btc: yes
  othercrypto: yes
  doc: https://www.spacefucker.com/threads/spacefucker-paid-features.363314/
  keywords:
  - adult forum
  - sex forum
  - adult network
  - sex
  - adult
  - porn
  - porno
```

> Add more information here if necessary.

All membership upgrades and donations on the site go through Bitcoin Cash (BCH) by default if user will not ask for other cryptocurrency.

  region: worldwide
