### ISSUE TITLE
Add 'Chiron Scientific' to the 'Health/Wellness/Supplements' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2171]
Requesting to add 'Chiron Scientific' to the 'Health/Wellness/Supplements' category. 

Details follow: 
```yml 
- name: Chiron Scientific
  url: https://www.ChironScientific.com
  img: ChironScientific.png
  bch: true
  btc: true
  othercrypto: true
  twitter: chironscience
  facebook: chironscientific
  email_address: info@chironscientific.com
  doc: https://chironscientific.com/payments/
  exceptions:
    text: "Select the crypto payments option in the shopping cart during checkout"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://chironscientific.com/wp-content/uploads/2021/07/LogoFinal-300px-Trans-ChironScientific.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1421197836620795906/kbvmlTAs_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/chironscientific/picture)
[Link to Chiron Scientific](https://www.ChironScientific.com)
Check their Twitter Page: [twitter.com/chironscience](https://twitter.com/chironscience)
Check their Facebook Page: [fb.com/chironscientific](https://fb.com/chironscientific)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ChironScientific.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ChironScientific.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ChironScientific.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
