### ISSUE TITLE
Add 'Amelia Johannsen Ceramics' to the 'Art & Design' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2173]
Requesting to add 'Amelia Johannsen Ceramics' to the 'Art & Design' category. 

Details follow: 
```yml 
- name: Amelia Johannsen Ceramics
  url: https://www.ameliajohannsen.com/
  img: AmeliaJohannsenCeramics.png
  bch: true
  btc: true
  othercrypto: true
  twitter: ameliajcreate
  facebook: ameliajohannsenceramics
  email_address: hello@ameliajohannsen.com
  doc: https://twitter.com/AmeliaJCreate/status/1585199952762114054?s=20&t=ULeZtfHbBptMYyNDutMZ8Q
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.ameliajohannsen.com/wp-content/uploads/2019/10/amelia-johannsen-ceramics-logo-150x150-1.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1484469420860874755/oGyO2DVu_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/ameliajohannsenceramics/picture)
[Link to Amelia Johannsen Ceramics](https://www.ameliajohannsen.com/)
Check their Twitter Page: [twitter.com/ameliajcreate](https://twitter.com/ameliajcreate)
Check their Facebook Page: [fb.com/ameliajohannsenceramics](https://fb.com/ameliajohannsenceramics)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ameliajohannsen.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ameliajohannsen.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ameliajohannsen.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [ameliajcreate](https://twitter.com/ameliajcreate/), be sure to send out a tweet when this request has been added.
