### ISSUE TITLE
Add 'L'Art du Chanvre' to the 'Online shop - Hemp products' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2174]
Requesting to add 'L'Art du Chanvre' to the 'Online shop - Hemp products' category. 

Details follow: 
```yml 
- name: L'Art du Chanvre
  url: https://lartduchanvre.fr/
  img: LArtduChanvre.png
  bch: true
  btc: false
  othercrypto: true
  twitter: lartduchanvre
  email_address: contact@lartduchanvre.fr
  region: eu
  country: FR
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/0556/9708/0374/files/LOGO_BOLD_JPEG_211f3c5d-296b-4b6f-9802-a0220ee2200f.jpg?v=1665737268)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1577325647587950594/aFZH426H_normal.jpg)
[Link to L'Art du Chanvre](https://lartduchanvre.fr/)
Check their Twitter Page: [twitter.com/lartduchanvre](https://twitter.com/lartduchanvre)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/lartduchanvre.fr/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/lartduchanvre.fr/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/lartduchanvre.fr/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
