### ISSUE TITLE
Add 'Comete Maison' to the 'Apparel & Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2175]
Requesting to add 'Comete Maison' to the 'Apparel & Accessories' category. 

Details follow: 
```yml 
- name: Comete Maison
  url: https://cometemaison.com
  img: CometeMaison.png
  bch: true
  btc: true
  othercrypto: true
  twitter: cometemaison
  email_address: contact@cometemaison.com
  doc: https://twitter.com/CometeMaison/status/1588969876273569793
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/UIwKNvt.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1586371024693694464/SxxMIOZ5_normal.jpg)
[Link to Comete Maison](https://cometemaison.com)
Check their Twitter Page: [twitter.com/cometemaison](https://twitter.com/cometemaison)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cometemaison.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cometemaison.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cometemaison.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [cometemaison](https://twitter.com/cometemaison/), be sure to send out a tweet when this request has been added.
