### ISSUE TITLE
Add 'Lurelin Village' to the 'Apartments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2176]
Requesting to add 'Lurelin Village' to the 'Apartments' category. 

Details follow: 
```yml 
- name: Lurelin Village
  url: https://www.booking.com/hotel/gh/lurelin-village.html
  img: LurelinVillage.png
  bch: true
  btc: true
  othercrypto: true
  region: af
  country: GH
  city: Accra
```

Resources for adding this merchant:
[Link to Lurelin Village](https://www.booking.com/hotel/gh/lurelin-village.html)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.booking.com/hotel/gh/lurelin-village.html)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.booking.com/hotel/gh/lurelin-village.html)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.booking.com/hotel/gh/lurelin-village.html)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
