### ISSUE TITLE
Add 'Toldos Madrid' to the 'Servicios' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2178]
Requesting to add 'Toldos Madrid' to the 'Servicios' category. 

Details follow: 
```yml 
- name: Toldos Madrid
  url: https://twitter.com/MadridToldos
  img: ToldosMadrid.png
  bch: true
  btc: true
  othercrypto: true
  email_address: harold.bubuz@gmail.com
  region: eu
  country: ES
  city: Madrid
```

Resources for adding this merchant:
[Link to Toldos Madrid](https://twitter.com/MadridToldos)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/twitter.com/MadridToldos)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/twitter.com/MadridToldos)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/twitter.com/MadridToldos)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
