### ISSUE TITLE
Add 'Anytask.com' to the 'Freelance Platform ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2179]
Requesting to add 'Anytask.com' to the 'Freelance Platform ' category. 

Details follow: 
```yml 
- name: Anytask.com
  url: https://www.Anytask.com
  img: Anytaskcom.png
  bch: false
  btc: false
  othercrypto: true
  twitter: anytaskofficial
  facebook: anytaskofficial
  email_address: marketing@anytask.com
  city: no
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.Anytask.com)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1576888035547004929/IRXew2Vp_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/anytaskofficial/picture)
[Link to Anytask.com](https://www.Anytask.com)
Check their Twitter Page: [twitter.com/anytaskofficial](https://twitter.com/anytaskofficial)
Check their Facebook Page: [fb.com/anytaskofficial](https://fb.com/anytaskofficial)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.Anytask.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.Anytask.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.Anytask.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
