### ISSUE TITLE
Add Hungry.dk

### ISSUE THREAD

**Issue by Albeos90** [acceptbitcoincash/acceptbitcoincash#218]
_Please fill in the template below, and don't worry about exact formatting, just do your best!_

Requesting to add {{https://www.hungry.dk/ }} to the {{ Food }} category. Details follow:

```yml

- name: Hungry.dk
  url: https://www.hungry.dk/
  twitter: @Hungrydk
  facebook: Hungry.dk
  img: https://www.plecto.com/static/img/case-study/hungry-logo.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_article_or_help_guide_etc
  exceptions:
    text: "general_comments_or_notes_here___do_not_remove_quotes"
```
