### ISSUE TITLE
Add 'Vivalatina Jewelry Shop' to the 'Jewelry business' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2180]
Requesting to add 'Vivalatina Jewelry Shop' to the 'Jewelry business' category. 

Details follow: 
```yml 
- name: Vivalatina Jewelry Shop
  url: https://vivalatina-shop.com/
  img: VivalatinaJewelryShop.png
  bch: true
  btc: false
  othercrypto: true
  email_address: mail@vivalatina.fr
  region: na
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://cdn.shopify.com/s/files/1/2590/3848/files/logo_v3_600x.png?v=1618250446)
[Link to Vivalatina Jewelry Shop](https://vivalatina-shop.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/vivalatina-shop.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/vivalatina-shop.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/vivalatina-shop.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
