### ISSUE TITLE
Add 'Halim' to the 'Sk' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2181]
Requesting to add 'Halim' to the 'Sk' category. 

Details follow: 
```yml 
- name: Halim
  url: https://gpay.app.goo.gl/apN41h
  img: Halim.png
  bch: true
  btc: true
  othercrypto: true
  twitter: halimsl
  facebook: halimsk
  email_address: halimsk7869@gamli.com
  country: IN
  city: https://gpay.app.goo.gl/apN41h
  exceptions:
    text: "Halimsk"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://gpay.app.goo.gl/apN41h)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/471337731058966528/m8SeRHX3_normal.jpeg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/halimsk/picture)
[Link to Halim](https://gpay.app.goo.gl/apN41h)
Check their Twitter Page: [twitter.com/halimsl](https://twitter.com/halimsl)
Check their Facebook Page: [fb.com/halimsk](https://fb.com/halimsk)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/gpay.app.goo.gl/apN41h)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/gpay.app.goo.gl/apN41h)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/gpay.app.goo.gl/apN41h)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
