### ISSUE TITLE
Add 'Manzanares Hair Restoration Center' to the 'Hair Transplant Company' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2182]
Requesting to add 'Manzanares Hair Restoration Center' to the 'Hair Transplant Company' category. 

Details follow: 
```yml 
- name: Manzanares Hair Restoration Center
  url: https://Drfrank@manzanar3shairph.com/
  img: ManzanaresHairRestorationCenter.png
  bch: true
  btc: true
  othercrypto: true
  twitter: microncus13
  facebook: michaelacustodio13gmail.com
  email_address: michaelacustodio13@gmail.com
  city: Philippines/Global
  doc: https://Binance.com/
  exceptions:
    text: "Coins.ph/Coinbase/Binance Exchange etc."
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1580276900005437440/CSTAAPhY_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/michaelacustodio13gmail.com/picture)
[Link to Manzanares Hair Restoration Center](https://Drfrank@manzanar3shairph.com/)
Check their Twitter Page: [twitter.com/microncus13](https://twitter.com/microncus13)
Check their Facebook Page: [fb.com/michaelacustodio13gmail.com](https://fb.com/michaelacustodio13gmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/Drfrank@manzanar3shairph.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/Drfrank@manzanar3shairph.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/Drfrank@manzanar3shairph.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @micreates
Request made by Twitter user [microncus13](https://twitter.com/microncus13/), be sure to send out a tweet when this request has been added.
