### ISSUE TITLE
Add '0743828443' to the '0743828443' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2184]
Requesting to add '0743828443' to the '0743828443' category. 

Details follow: 
```yml 
- name: 0743828443
  url: charomohamed454@gmail.com
  img: .png
  bch: true
  btc: true
  othercrypto: true
  facebook: 0743828443
  email_address: charomohamed454@gmail.com
  country: KE
  city: 0743828443
  exceptions:
    text: "0743828443"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](charomohamed454@gmail.com)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/0743828443/picture)
[Link to 0743828443](charomohamed454@gmail.com)
Check their Facebook Page: [fb.com/0743828443](https://fb.com/0743828443)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/charomohamed454@gmail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/charomohamed454@gmail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/charomohamed454@gmail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @0743828443
Request made by Twitter user [0743828443](https://twitter.com/0743828443/), be sure to send out a tweet when this request has been added.
