### ISSUE TITLE
Add 'Suburban Carry' to the 'Protection' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2185]
Requesting to add 'Suburban Carry' to the 'Protection' category. 

Details follow: 
```yml 
- name: Suburban Carry
  url: https://www.suburbancarry.com
  img: SuburbanCarry.png
  bch: true
  btc: true
  othercrypto: true
  twitter: suburbancarry
  facebook: suburbancarry
  email_address: chris@suburbancarry.com
  region: na
  country: US
  doc: https://suburbancarry.com/2022/12/21/we-accept-crypto/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://suburbancarry.com/wp-content/uploads/event-manager-uploads/event_banner/2021/09/SC_Logo_300.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1432899861280694274/1H6ZvUl6_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/suburbancarry/picture)
[Link to Suburban Carry](https://www.suburbancarry.com)
Check their Twitter Page: [twitter.com/suburbancarry](https://twitter.com/suburbancarry)
Check their Facebook Page: [fb.com/suburbancarry](https://fb.com/suburbancarry)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.suburbancarry.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.suburbancarry.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.suburbancarry.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [suburbancarry](https://twitter.com/suburbancarry/), be sure to send out a tweet when this request has been added.
