### ISSUE TITLE
Add 'Arturo1999' to the 'Arturo1998' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2188]
Requesting to add 'Arturo1999' to the 'Arturo1998' category. 

Details follow: 
```yml 
- name: Arturo1999
  url: https.facebook.com
  img: Arturo.png
  bch: true
  btc: true
  othercrypto: true
  region: na
  country: US
  city: Yes
```

Resources for adding this merchant:
[Link to Arturo1999](https.facebook.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/https.facebook.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/https.facebook.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/https.facebook.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
