### ISSUE TITLE
Add 'Vikhost' to the 'Dedicated servers & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2191]
Requesting to add 'Vikhost' to the 'Dedicated servers & VPS' category. 

Details follow: 
```yml 
- name: Vikhost
  url: https://vikhost.com/
  img: Vikhost.png
  bch: true
  btc: false
  othercrypto: true
  twitter: vikhost
  facebook: vikhost
  email_address: info@vikhost.com
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1058464928678535168/UmhfTEUa_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/vikhost/picture)
[Link to Vikhost](https://vikhost.com/)
Check their Twitter Page: [twitter.com/vikhost](https://twitter.com/vikhost)
Check their Facebook Page: [fb.com/vikhost](https://fb.com/vikhost)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/vikhost.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/vikhost.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/vikhost.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
