### ISSUE TITLE
Add 'bitcoin-wear.com' to the 'Bitcoin Merchandising' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2195]
Requesting to add 'bitcoin-wear.com' to the 'Bitcoin Merchandising' category. 

Details follow: 
```yml 
- name: bitcoin-wear.com
  url: https://bitcoin-wear.com
  img: bitcoinwearcom.png
  bch: false
  btc: true
  othercrypto: false
  twitter: bitcoin_wear_
  email_address: office@bitcoin-wear.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1611889565219831809/PLhJD0wk_400x400.jpg)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1611889565219831809/PLhJD0wk_normal.jpg)
[Link to bitcoin-wear.com](https://bitcoin-wear.com)
Check their Twitter Page: [twitter.com/bitcoin_wear_](https://twitter.com/bitcoin_wear_)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitcoin-wear.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitcoin-wear.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitcoin-wear.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [bitcoin_wear_](https://twitter.com/bitcoin_wear_/), be sure to send out a tweet when this request has been added.
