### ISSUE TITLE
Add 'Amber Rodrigues' to the 'Finance ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2196]
Requesting to add 'Amber Rodrigues' to the 'Finance ' category. 

Details follow: 
```yml 
- name: Amber Rodrigues
  url: Cashapp.com
  img: AmberRodrigues.png
  bch: true
  btc: true
  othercrypto: true
  email_address: amberrodrigues823@gmail.com
  city: Ponca city
  exceptions:
    text: ""
```

Resources for adding this merchant:
[Link to Amber Rodrigues](Cashapp.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/Cashapp.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/Cashapp.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/Cashapp.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
