### ISSUE TITLE
Add 'Apirone.com' to the 'Payment gateway' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2198]
Requesting to add 'Apirone.com' to the 'Payment gateway' category. 

Details follow: 
```yml 
- name: Apirone.com
  url: https://apirone.com/
  img: Apironecom.png
  bch: true
  btc: true
  othercrypto: true
  twitter: apirone_com
  facebook: apirone
  email_address: founder@apirone.com
  country: EE
  city: Tallinn
```

Resources for adding this merchant:
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/1486758911248158724/eXd3nyFg_normal.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/apirone/picture)
[Link to Apirone.com](https://apirone.com/)
Check their Twitter Page: [twitter.com/apirone_com](https://twitter.com/apirone_com)
Check their Facebook Page: [fb.com/apirone](https://fb.com/apirone)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/apirone.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/apirone.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/apirone.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
