### ISSUE TITLE
Add 'Amazon' to the 'Hair' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2200]
Requesting to add 'Amazon' to the 'Hair' category. 

Details follow: 
```yml 
- name: Amazon
  url: amazon.com
  img: Amazon.png
  bch: true
  btc: true
  othercrypto: true
  facebook: cheyennecarolhannigan
  email_address: hannigancheyennecarol@gmail.com
  region: na
  country: US
  city: Los Angeles 
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/cheyennecarolhannigan/picture)
[Link to Amazon](amazon.com)
Check their Facebook Page: [fb.com/cheyennecarolhannigan](https://fb.com/cheyennecarolhannigan)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/amazon.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/amazon.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/amazon.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @crybaby
