### ISSUE TITLE
Add 'adam' to the 'game' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2201]
Requesting to add 'adam' to the 'game' category. 

Details follow: 
```yml 
- name: adam
  url: realmshosting.com/fivem
  img: adam.png
  bch: false
  btc: true
  othercrypto: true
  region: na
```

Resources for adding this merchant:
[Link to adam](realmshosting.com/fivem)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/realmshosting.com/fivem)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/realmshosting.com/fivem)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/realmshosting.com/fivem)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
