### ISSUE TITLE
Add 'Securednet' to the 'Hosting/Domain' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2208]
Requesting to add 'Securednet' to the 'Hosting/Domain' category. 

Details follow: 
```yml 
- name: Securednet
  url: https://securednet.su/clients/ / https://securednet.su/
  img: Securednet.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to Securednet](https://securednet.su/clients/ / https://securednet.su/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/securednet.su/clients/ / https://securednet.su/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/securednet.su/clients/ / https://securednet.su/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/securednet.su/clients/ / https://securednet.su/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
