### ISSUE TITLE
Add 'Ghana Ghana in Ghetto Ghana Ghana' to the 'Ghana' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2209]
Requesting to add 'Ghana Ghana in Ghetto Ghana Ghana' to the 'Ghana' category. 

Details follow: 
```yml 
- name: Ghana Ghana in Ghetto Ghana Ghana
  url: www.Facebook.com
  img: GhanaGhanainGhettoGhanaGhana.png
  bch: true
  btc: true
  othercrypto: true
  facebook: ghana
  email_address: hamadahamadagml@yahoo.com
  region: af
  country: AL
  city: Ghana
  exceptions:
    text: "Ghana"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](www.Facebook.com)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/ghana/picture)
[Link to Ghana Ghana in Ghetto Ghana Ghana](www.Facebook.com)
Check their Facebook Page: [fb.com/ghana](https://fb.com/ghana)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.Facebook.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.Facebook.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.Facebook.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
