### ISSUE TITLE
Add 'Bitcoin VPS Cloud' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2210]
Requesting to add 'Bitcoin VPS Cloud' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: Bitcoin VPS Cloud
  url: https://bitcoinvps.cloud
  img: BitcoinVPSCloud.png
  bch: true
  btc: true
  othercrypto: true
  email_address: me@bitcoinvps.cloud
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://bitcoinvps.cloud/logos/bitcoinvpscloud.svg)
[Link to Bitcoin VPS Cloud](https://bitcoinvps.cloud)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bitcoinvps.cloud)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bitcoinvps.cloud)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bitcoinvps.cloud)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
