### ISSUE TITLE
Add 'MoreMins' to the 'Communication, Utilities' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2212]
Requesting to add 'MoreMins' to the 'Communication, Utilities' category. 

Details follow: 
```yml 
- name: MoreMins
  url: https://www.moremins.com/en
  img: MoreMins.png
  bch: true
  btc: true
  othercrypto: true
  email_address: info@moremins.com
  doc: https://www.moremins.com/en/crypto
```

Resources for adding this merchant:
[Link to MoreMins](https://www.moremins.com/en)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.moremins.com/en)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.moremins.com/en)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.moremins.com/en)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
