### ISSUE TITLE
Add 'Mr. Satoshi' to the 'Apparel & Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2213]
Requesting to add 'Mr. Satoshi' to the 'Apparel & Accessories' category. 

Details follow: 
```yml 
- name: Mr. Satoshi
  url: https://mrsatoshi.com
  img: MrSatoshi.png
  bch: false
  btc: true
  othercrypto: false
  email_address: support@mrsatoshi.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.postimg.cc/HLMRLGVR/Logo-Mr-Satoshi-Main.png)
[Link to Mr. Satoshi](https://mrsatoshi.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/mrsatoshi.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/mrsatoshi.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/mrsatoshi.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [mrsatoshistore](https://twitter.com/mrsatoshistore/), be sure to send out a tweet when this request has been added.
