### ISSUE TITLE
Add 'MoreMins - cheap global telco services. Virtual numbers, virtual SIM cards, eSIM data, calls and SMS' to the 'Communications, Voip' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2215]
Requesting to add 'MoreMins - cheap global telco services. Virtual numbers, virtual SIM cards, eSIM data, calls and SMS' to the 'Communications, Voip' category. 

Details follow: 
```yml 
- name: MoreMins - cheap global telco services. Virtual numbers, virtual SIM cards, eSIM data, calls and SMS
  url: https://www.moremins.com/en
  img: MoreMinscheapglobaltelcoservicesVirtualnumbersvirtualSIMcardseSIMdatacallsandSMS.png
  bch: true
  btc: true
  othercrypto: true
  facebook: moremins
  email_address: info@moremins.com
  city: MoreMins services can be ordered in 160+ countries
  doc: https://www.moremins.com/en/crypto
  exceptions:
    text: "Pay by crypto currency on MoreMins website shop"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://pub.email-messaging.com/email/1/image?id=YWNjb3VudC8zMjgxMTIvY29udGVudC83YWVlMzNkZi1iM2JjLTQ0MDYtYWIzMS05NmI0OTRhYTc0NWY=)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/moremins/picture)
[Link to MoreMins - cheap global telco services. Virtual numbers, virtual SIM cards, eSIM data, calls and SMS](https://www.moremins.com/en)
Check their Facebook Page: [fb.com/moremins](https://fb.com/moremins)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.moremins.com/en)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.moremins.com/en)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.moremins.com/en)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @moreminsteam
Request made by Twitter user [wedon'tusetwitter](https://twitter.com/wedon'tusetwitter/), be sure to send out a tweet when this request has been added.
