### ISSUE TITLE
Add 'BnB Tunisie' to the 'Real Estate' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2216]
Requesting to add 'BnB Tunisie' to the 'Real Estate' category. 

Details follow: 
```yml 
- name: BnB Tunisie
  url: https://www.bnb.tn
  img: BnBTunisie.png
  bch: false
  btc: true
  othercrypto: true
  email_address: contact@bnb.tn
  region: af
  country: TN
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.bnb.tn/wp-content/uploads/2021/04/new-bnb-logo-150x150.png)
[Link to BnB Tunisie](https://www.bnb.tn)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.bnb.tn)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.bnb.tn)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.bnb.tn)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @besrourms
