### ISSUE TITLE
Add 'TODD'S MUSIC EXPRESS' to the 'MUSICAL INSTRUMENT SALES & REPAIRS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2222]
Requesting to add 'TODD'S MUSIC EXPRESS' to the 'MUSICAL INSTRUMENT SALES & REPAIRS' category. 

Details follow: 
```yml 
- name: TODD'S MUSIC EXPRESS
  url: www.toddsmusic.com
  img: TODDSMUSICEXPRESS.png
  bch: true
  btc: true
  othercrypto: true
  email_address: toddsmusicexpress@gmail.com
  region: na
  country: US
  city: NEW ORLEANS
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://www.toddsmusicexpress.com/Images/toddslogo.jpg)
[Link to TODD'S MUSIC EXPRESS](www.toddsmusic.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.toddsmusic.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.toddsmusic.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.toddsmusic.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
