### ISSUE TITLE
Add 'RDP.Monster' to the 'Hosting (Windows RDP)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2223]
Requesting to add 'RDP.Monster' to the 'Hosting (Windows RDP)' category. 

Details follow: 
```yml 
- name: RDP.Monster
  url: https://rdp.monster
  img: RDPMonster.png
  bch: true
  btc: true
  othercrypto: true
  email_address: contact@stellar-group.fr
  exceptions:
    text: "Footer (use of Coinbase Commerce) : https://rdp.monster"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.ibb.co/K6mG9Jf/rdp-monster-logo.png)
[Link to RDP.Monster](https://rdp.monster)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/rdp.monster)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/rdp.monster)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/rdp.monster)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
