### ISSUE TITLE
Add 'Google' to the 'Receiving' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2225]
Requesting to add 'Google' to the 'Receiving' category. 

Details follow: 
```yml 
- name: Google
  url: https://docs.google.com/presentation/d/e/2PACX-1vRicgJVVEBzEXjxGGcS7bF7Q5gVAWdoAB8Zdi4ffNtuTYWV4shKl7qab_hJBpb1Dqoy-ytJXeGBXvE-/pub?start=false&loop=false&delayms=3000#pw9ULDWOmp8LKrE876lzbcbS8
  img: Google.png
  bch: true
  btc: false
  othercrypto: true
  email_address: dilla86tams@gmail.com
  country: GU
  city: Agana Heights
  exceptions:
    text: "]"
```

Resources for adding this merchant:
[Link to Google](https://docs.google.com/presentation/d/e/2PACX-1vRicgJVVEBzEXjxGGcS7bF7Q5gVAWdoAB8Zdi4ffNtuTYWV4shKl7qab_hJBpb1Dqoy-ytJXeGBXvE-/pub?start=false&loop=false&delayms=3000#pw9ULDWOmp8LKrE876lzbcbS8)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/docs.google.com/presentation/d/e/2PACX-1vRicgJVVEBzEXjxGGcS7bF7Q5gVAWdoAB8Zdi4ffNtuTYWV4shKl7qab_hJBpb1Dqoy-ytJXeGBXvE-/pub?start=false&loop=false&delayms=3000#pw9ULDWOmp8LKrE876lzbcbS8)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/docs.google.com/presentation/d/e/2PACX-1vRicgJVVEBzEXjxGGcS7bF7Q5gVAWdoAB8Zdi4ffNtuTYWV4shKl7qab_hJBpb1Dqoy-ytJXeGBXvE-/pub?start=false&loop=false&delayms=3000#pw9ULDWOmp8LKrE876lzbcbS8)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/docs.google.com/presentation/d/e/2PACX-1vRicgJVVEBzEXjxGGcS7bF7Q5gVAWdoAB8Zdi4ffNtuTYWV4shKl7qab_hJBpb1Dqoy-ytJXeGBXvE-/pub?start=false&loop=false&delayms=3000#pw9ULDWOmp8LKrE876lzbcbS8)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
