### ISSUE TITLE
Add 'Kevin Lee' to the 'Gun Supplier' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2226]
Requesting to add 'Kevin Lee' to the 'Gun Supplier' category. 

Details follow: 
```yml 
- name: Kevin Lee
  url: https://www.ronsgunsct.com/
  img: KevinLee.png
  bch: true
  btc: true
  othercrypto: true
  email_address: kevilee084@gmail.com
  country: US
  city: East Lyme, CT
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://images.pexels.com/photos/5202381/pexels-photo-5202381.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1)
[Link to Kevin Lee](https://www.ronsgunsct.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ronsgunsct.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ronsgunsct.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ronsgunsct.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
