### ISSUE TITLE
Add 'Chiron Scientific' to the 'Supplements' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2227]
Requesting to add 'Chiron Scientific' to the 'Supplements' category. 

Details follow: 
```yml 
- name: Chiron Scientific
  url: https://www.ChironScientific.com
  img: ChironScientific.png
  bch: true
  btc: true
  othercrypto: true
  email_address: info@chironscientific.com
  doc: https://chironscientific.com/payments/
  exceptions:
    text: "It must be selected during the cypto checkout proceedure in the the shopping cart"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://chironscientific.com/wp-content/uploads/2021/07/LogoFinal-250px-Trans-ChironScientific.png)
[Link to Chiron Scientific](https://www.ChironScientific.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ChironScientific.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ChironScientific.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ChironScientific.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
