### ISSUE TITLE
Add 'Bitcoincash/ALIEN3Dwireless' to the 'CryptoBlockchain' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2229]
Requesting to add 'Bitcoincash/ALIEN3Dwireless' to the 'CryptoBlockchain' category. 

Details follow: 
```yml 
- name: Bitcoincash/ALIEN3Dwireless
  url: https://readme.com
  img: BitcoincashALIENDwireless.png
  bch: true
  btc: true
  othercrypto: true
  facebook: saulpalominoramos
  email_address: alien3dsatnetwork@gmail.com
  country: MX
  city: Mexicali
  exceptions:
    text: "Facility and strong security"
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/saulpalominoramos/picture)
[Link to Bitcoincash/ALIEN3Dwireless](https://readme.com)
Check their Facebook Page: [fb.com/saulpalominoramos](https://fb.com/saulpalominoramos)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/readme.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/readme.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/readme.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @alien3dsaul
