### ISSUE TITLE
Add Bovada to Gambling Category

### ISSUE THREAD

**Issue by zan56** [acceptbitcoincash/acceptbitcoincash#223]
_Please fill in the template below, and don't worry about exact formatting, just do your best!_

Requesting to add {{ Bovada }} to the {{ Gambling }} category. Details follow:

```yml

- name: Bovada.com
  url: https://www.bovada.lv/
  twitter:
  facebook: 
  img: https://cdn13-a.imagestore.lv/static/site10/bovada-logo_0.png
  bcc: yes
  btc: yes
  othercrypto: no
  doc:
  exceptions:
    text: "general_comments_or_notes_here___do_not_remove_quotes"
```
