### ISSUE TITLE
Add 'rdp.monster' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2230]
Requesting to add 'rdp.monster' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: rdp.monster
  url: https://rdp.monster
  img: rdpmonster.png
  bch: true
  btc: true
  othercrypto: true
  email_address: contact@stellar-group.fr
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/zygbp3E.png)
[Link to rdp.monster](https://rdp.monster)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/rdp.monster)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/rdp.monster)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/rdp.monster)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
