### ISSUE TITLE
Add 'Vezk Ltda' to the 'Modelado 3d y Impresión 3d' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2231]
Requesting to add 'Vezk Ltda' to the 'Modelado 3d y Impresión 3d' category. 

Details follow: 
```yml 
- name: Vezk Ltda
  url: https://vezkltda.com/
  img: VezkLtda.png
  bch: true
  btc: true
  othercrypto: true
  facebook: web.profile.php?id=100090177728767
  email_address: contacto@vezkltda.com
  region: sa
  country: CL
  city: Valparaiso
  exceptions:
    text: "No Solo Usar Nuestra Pasarela De Pago Crypto"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i0.wp.com/vezkltda.com/wp-content/uploads/2023/07/logo11_4_202645.png?w=600&ssl=1)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/web.profile.php?id=100090177728767/picture)
[Link to Vezk Ltda](https://vezkltda.com/)
Check their Facebook Page: [fb.com/web.profile.php?id=100090177728767](https://fb.com/web.profile.php?id=100090177728767)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/vezkltda.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/vezkltda.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/vezkltda.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
