### ISSUE TITLE
Add 'Donald Hughes Acupuncture' to the 'Acupuncture, Massage, Chinese Herbs' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2232]
Requesting to add 'Donald Hughes Acupuncture' to the 'Acupuncture, Massage, Chinese Herbs' category. 

Details follow: 
```yml 
- name: Donald Hughes Acupuncture
  url: donaldhugheslac.com
  img: DonaldHughesAcupuncture.png
  bch: true
  btc: true
  othercrypto: false
  email_address: donaldhugheslac@gmail.com
  region: na
  country: US
  city: Albany, California (San Francisco Bay Area)
```

Resources for adding this merchant:
[Link to Donald Hughes Acupuncture](donaldhugheslac.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/donaldhugheslac.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/donaldhugheslac.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/donaldhugheslac.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
