### ISSUE TITLE
Add 'ManfredK' to the 'Website Design & Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2233]
Requesting to add 'ManfredK' to the 'Website Design & Hosting' category. 

Details follow: 
```yml 
- name: ManfredK
  url: https://www.manfredk.com
  img: ManfredK.png
  bch: true
  btc: false
  othercrypto: false
  email_address: websites@manfredk.com
  country: CY
  doc: https://www.manfredk.com/bitcoin-accepted-here/
```

Resources for adding this merchant:
[Link to ManfredK](https://www.manfredk.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.manfredk.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.manfredk.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.manfredk.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
