### ISSUE TITLE
Add 'Zelta' to the 'Cryptocurrency Exchanges' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2237]
Requesting to add 'Zelta' to the 'Cryptocurrency Exchanges' category. 

Details follow: 
```yml 
- name: Zelta
  url: https://zelta.io/
  img: Zelta.png
  bch: true
  btc: true
  othercrypto: true
  facebook: zelta.io
  email_address: zeltamarketing1@gmail.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1610980039197364224/mj3ARJe-_400x400.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/zelta.io/picture)
[Link to Zelta](https://zelta.io/)
Check their Facebook Page: [fb.com/zelta.io](https://fb.com/zelta.io)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/zelta.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/zelta.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/zelta.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [pika_pika_mofo](https://twitter.com/pika_pika_mofo/), be sure to send out a tweet when this request has been added.
