### ISSUE TITLE
Add 'Yo' to the 'Go' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2238]
Requesting to add 'Yo' to the 'Go' category. 

Details follow: 
```yml 
- name: Yo
  url: https://cryptotabfarm.com/go/3NKSAHKY
  img: Yo.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to Yo](https://cryptotabfarm.com/go/3NKSAHKY)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cryptotabfarm.com/go/3NKSAHKY)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cryptotabfarm.com/go/3NKSAHKY)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cryptotabfarm.com/go/3NKSAHKY)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
