### ISSUE TITLE
Add Unit Wallet to Wallet Category

### ISSUE THREAD

**Issue by zan56** [acceptbitcoincash/acceptbitcoincash#224]
_Please fill in the template below, and don't worry about exact formatting, just do your best!_

Requesting to add {{ Unit Wallet }} to the {{ Wallet }} category. Details follow:

```yml

- name: Unit Wallet
  url: https://www.unitwallet.co/
  twitter: Unit Wallet@UnitWallet
  facebook: 
  img: https://b.thumbs.redditmedia.com/i_7bmRm-77b73bTUFDRxIZwebQ1okjQ96eoXc8LJLxw.jpg
  bcc: yes
  btc: no
  othercrypto: no
  doc: 
  exceptions:
    text: "general_comments_or_notes_here___do_not_remove_quotes"
```
