### ISSUE TITLE
Add 'uThrive Labs' to the 'Alternative Health' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2240]
Requesting to add 'uThrive Labs' to the 'Alternative Health' category. 

Details follow: 
```yml 
- name: uThrive Labs
  url: https://uthrivelabs.com
  img: uThriveLabs.png
  bch: true
  btc: true
  othercrypto: true
  facebook: none.
  email_address: uthrive@tutamail.com
  region: na
  country: US
  city: All cities
  doc: https://www.reddit.com/r/Bitcoincash/
  exceptions:
    text: "Email your order & shipment address for a quote"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1703555326065160192/Ue6qDY2U_400x400.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/none./picture)
[Link to uThrive Labs](https://uthrivelabs.com)
Check their Facebook Page: [fb.com/none.](https://fb.com/none.)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/uthrivelabs.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/uthrivelabs.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/uthrivelabs.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
