### ISSUE TITLE
Add 'Premier' to the 'Local corner store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2241]
Requesting to add 'Premier' to the 'Local corner store' category. 

Details follow: 
```yml 
- name: Premier
  url: https://www.google.co.uk/maps/place/Premier,+New+Bridge+St,+Newcastle+upon+Tyne+NE1+8BS,+United+Kingdom/@54.9738184,-1.6006235,19z/data=!4m14!1m7!3m6!1s0x487e70c0ac914c09:0x9e1c356e764d0fa6!2sUnite+Students+-+Quay+Point+Studios,+Melbourne+St,+Newcastle+upon+Tyne+NE1+2JB,+United+Kingdom!8m2!3d54.9733379!4d-1.6003907!16s%2Fg%2F11bwqblz4r!3m5!1s0x487e7104434d2a1f:0x14f379223da5902f!8m2!3d54.9738006!4d-1.6007283!16s%2Fg%2F11ghrtvf83
  img: Premier.png
  bch: true
  btc: false
  othercrypto: false
  email_address: psS7nij3@protonmail.com
  region: eu
  country: GB
  city: Newcastle upon tyne
  exceptions:
    text: "No, invoices generated using btc.com app then customer scans and sends"
```

Resources for adding this merchant:
[Link to Premier](https://www.google.co.uk/maps/place/Premier,+New+Bridge+St,+Newcastle+upon+Tyne+NE1+8BS,+United+Kingdom/@54.9738184,-1.6006235,19z/data=!4m14!1m7!3m6!1s0x487e70c0ac914c09:0x9e1c356e764d0fa6!2sUnite+Students+-+Quay+Point+Studios,+Melbourne+St,+Newcastle+upon+Tyne+NE1+2JB,+United+Kingdom!8m2!3d54.9733379!4d-1.6003907!16s%2Fg%2F11bwqblz4r!3m5!1s0x487e7104434d2a1f:0x14f379223da5902f!8m2!3d54.9738006!4d-1.6007283!16s%2Fg%2F11ghrtvf83)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.google.co.uk/maps/place/Premier,+New+Bridge+St,+Newcastle+upon+Tyne+NE1+8BS,+United+Kingdom/@54.9738184,-1.6006235,19z/data=!4m14!1m7!3m6!1s0x487e70c0ac914c09:0x9e1c356e764d0fa6!2sUnite+Students+-+Quay+Point+Studios,+Melbourne+St,+Newcastle+upon+Tyne+NE1+2JB,+United+Kingdom!8m2!3d54.9733379!4d-1.6003907!16s%2Fg%2F11bwqblz4r!3m5!1s0x487e7104434d2a1f:0x14f379223da5902f!8m2!3d54.9738006!4d-1.6007283!16s%2Fg%2F11ghrtvf83)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.google.co.uk/maps/place/Premier,+New+Bridge+St,+Newcastle+upon+Tyne+NE1+8BS,+United+Kingdom/@54.9738184,-1.6006235,19z/data=!4m14!1m7!3m6!1s0x487e70c0ac914c09:0x9e1c356e764d0fa6!2sUnite+Students+-+Quay+Point+Studios,+Melbourne+St,+Newcastle+upon+Tyne+NE1+2JB,+United+Kingdom!8m2!3d54.9733379!4d-1.6003907!16s%2Fg%2F11bwqblz4r!3m5!1s0x487e7104434d2a1f:0x14f379223da5902f!8m2!3d54.9738006!4d-1.6007283!16s%2Fg%2F11ghrtvf83)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.google.co.uk/maps/place/Premier,+New+Bridge+St,+Newcastle+upon+Tyne+NE1+8BS,+United+Kingdom/@54.9738184,-1.6006235,19z/data=!4m14!1m7!3m6!1s0x487e70c0ac914c09:0x9e1c356e764d0fa6!2sUnite+Students+-+Quay+Point+Studios,+Melbourne+St,+Newcastle+upon+Tyne+NE1+2JB,+United+Kingdom!8m2!3d54.9733379!4d-1.6003907!16s%2Fg%2F11bwqblz4r!3m5!1s0x487e7104434d2a1f:0x14f379223da5902f!8m2!3d54.9738006!4d-1.6007283!16s%2Fg%2F11ghrtvf83)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
