### ISSUE TITLE
Add 'Crypto Luxury Store' to the 'Clothing Store, Jewelries, Electronics, Luxury Online Store ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2242]
Requesting to add 'Crypto Luxury Store' to the 'Clothing Store, Jewelries, Electronics, Luxury Online Store ' category. 

Details follow: 
```yml 
- name: Crypto Luxury Store
  url: https://crypto-luxury.shop/
  img: CryptoLuxuryStore.png
  bch: true
  btc: true
  othercrypto: true
  email_address: support@crypto-luxury.shop
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.ibb.co/V3z4vbR/logo.jpg)
[Link to Crypto Luxury Store](https://crypto-luxury.shop/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/crypto-luxury.shop/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/crypto-luxury.shop/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/crypto-luxury.shop/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
