### ISSUE TITLE
Add 'Alexandre dos santos' to the 'Atualizar nesse sistema da carteira que eu estou ativando para receber e pagar com esses' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2243]
Requesting to add 'Alexandre dos santos' to the 'Atualizar nesse sistema da carteira que eu estou ativando para receber e pagar com esses' category. 

Details follow: 
```yml 
- name: Alexandre dos santos
  url: esse cadastro é as6492414@gmail.com
  img: Alexandredossantos.png
  bch: true
  btc: true
  othercrypto: true
  facebook: alexandredossantosas6492414gmail.com
  email_address: as6492414@gmail.com
  country: BR
  city: Eu fico agradecido e aguardo resposta precisa ter que já está em ações nacional e internacional Btc ETHEURO REAL USDT real Bitcoin compra vendas REAL USDT dividendost Cristo 
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](este é meu Facebook Alexandre Santos então eu tô atualizando meu sistema de endereço de e-mail que a avenida Dr fórum Bartolomeu Barros salgadinho número 4 apartamento 12 Juazeiro do Norte Ceará e estas são as críticas que está em ações em movimento rendas ativas Btc ETHEURO REAL USDT dividendost Cristo as6492414@gmail.com)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/alexandredossantosas6492414gmail.com/picture)
[Link to Alexandre dos santos](esse cadastro é as6492414@gmail.com)
Check their Facebook Page: [fb.com/alexandredossantosas6492414gmail.com](https://fb.com/alexandredossantosas6492414gmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/esse cadastro é as6492414@gmail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/esse cadastro é as6492414@gmail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/esse cadastro é as6492414@gmail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
