### ISSUE TITLE
Add 'Rigly.io' to the 'Mining Hashrate Marketplace / Cloud Mining' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2244]
Requesting to add 'Rigly.io' to the 'Mining Hashrate Marketplace / Cloud Mining' category. 

Details follow: 
```yml 
- name: Rigly.io
  url: https://www.rigly.io/
  img: Riglyio.png
  bch: false
  btc: true
  othercrypto: false
  email_address: karan@rigly.io
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://blog.rigly.io/content/images/2022/11/rigly_5.png)
[Link to Rigly.io](https://www.rigly.io/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.rigly.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.rigly.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.rigly.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [trustlessmining](https://twitter.com/trustlessmining/), be sure to send out a tweet when this request has been added.
