### ISSUE TITLE
Add 'Apple http://107.12.72.70[all%20fields]' to the '123456' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2246]
Requesting to add 'Apple http://107.12.72.70[all%20fields]' to the '123456' category. 

Details follow: 
```yml 
- name: Apple http://107.12.72.70[all%20fields]
  url: beis.gov.uk
  img: Applehttpallfields.png
  bch: true
  btc: true
  othercrypto: true
  facebook: facebook:a0740129
  email_address: appleid@id.apple.com
  country: GB
  city: 哈克尼, 倫敦
  doc: https://t.me/@id1599139195
  exceptions:
    text: "compliance@paypal.com"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.gov.uk/government/publications/the-uk-sanctions-list)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/facebook:a0740129/picture)
[Link to Apple http://107.12.72.70[all%20fields]](beis.gov.uk)
Check their Facebook Page: [fb.com/facebook:a0740129](https://fb.com/facebook:a0740129)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/beis.gov.uk)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/beis.gov.uk)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/beis.gov.uk)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @orderuntilofoude3c
Request made by Twitter user [reading_order](https://twitter.com/reading_order/), be sure to send out a tweet when this request has been added.
