### ISSUE TITLE
Add 'SERVERS GURU' to the 'Cloud computing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2247]
Requesting to add 'SERVERS GURU' to the 'Cloud computing' category. 

Details follow: 
```yml 
- name: SERVERS GURU
  url: https://servers.guru/
  img: SERVERSGURU.png
  bch: true
  btc: true
  othercrypto: true
  doc: https://old.reddit.com/r/Bitcoincash/comments/vf43p1/anonymous_hosting_with_bitcoin_cash/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://tawk.link/64a24ab4cc26a871b025f404/kb/logo/_1lfPRlz--.png)
[Link to SERVERS GURU](https://servers.guru/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/servers.guru/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/servers.guru/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/servers.guru/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
