### ISSUE TITLE
Add 'Quangdo3112@gmail.com' to the 'Quangdo3112@gmail.com' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2248]
Requesting to add 'Quangdo3112@gmail.com' to the 'Quangdo3112@gmail.com' category. 

Details follow: 
```yml 
- name: Quangdo3112@gmail.com
  url: Quangdo3112@gmail.com
  img: Quangdogmailcom.png
  bch: true
  btc: false
  othercrypto: true
  facebook: wondyshinegmail.com
  email_address: Quangdo3112@gmail.com
  region: sa
  exceptions:
    text: "qp7e72ad98yxy4l59lqgffzm5j65x4k0yvlca558cs"
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/wondyshinegmail.com/picture)
[Link to Quangdo3112@gmail.com](Quangdo3112@gmail.com)
Check their Facebook Page: [fb.com/wondyshinegmail.com](https://fb.com/wondyshinegmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/Quangdo3112@gmail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/Quangdo3112@gmail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/Quangdo3112@gmail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @qp7e72ad98yxy4l59lqgffzm5j65x4k0yvlca558cs
Request made by Twitter user [quangdo3112gmail.com](https://twitter.com/quangdo3112gmail.com/), be sure to send out a tweet when this request has been added.
