### ISSUE TITLE
Add 'bizibiqtz' to the 'BTC donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2249]
Requesting to add 'bizibiqtz' to the 'BTC donations' category. 

Details follow: 
```yml 
- name: bizibiqtz
  url: Https://bizibiqtz.cheddarup.com
  img: bizibiqtz.png
  bch: true
  btc: true
  othercrypto: true
  email_address: sanmarcos51285@gmail.com
  country: US
  city: Austin 
  exceptions:
    text: "qr8q7lpk6e8xfjf58q6044ef6uqggps93vezkfretf"
```

Resources for adding this merchant:
[Link to bizibiqtz](Https://bizibiqtz.cheddarup.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/Https://bizibiqtz.cheddarup.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/Https://bizibiqtz.cheddarup.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/Https://bizibiqtz.cheddarup.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
