### ISSUE TITLE
Add 'Mantas8' to the 'Grubliauskas' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2250]
Requesting to add 'Mantas8' to the 'Grubliauskas' category. 

Details follow: 
```yml 
- name: Mantas8
  url: www.reddit.com
  img: Mantas.png
  bch: true
  btc: true
  othercrypto: true
  facebook: mantasgrubliauskas
  email_address: grubliauskasmantas0@gmail.com
  region: eu
  country: LT
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/mantasgrubliauskas/picture)
[Link to Mantas8](www.reddit.com)
Check their Facebook Page: [fb.com/mantasgrubliauskas](https://fb.com/mantasgrubliauskas)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.reddit.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.reddit.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.reddit.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @mantas
