### ISSUE TITLE
Add 'Shopping Spout US' to the 'Coupon' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2251]
Requesting to add 'Shopping Spout US' to the 'Coupon' category. 

Details follow: 
```yml 
- name: Shopping Spout US
  url: https://www.shoppingspout.us/
  img: ShoppingSpoutUS.png
  bch: false
  btc: true
  othercrypto: true
  facebook: shoppingspout
  email_address: d45654822@gmail.com
  region: sa
  country: US
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://images.shoppingspout.us/shoppingspout-logo.webp)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/shoppingspout/picture)
[Link to Shopping Spout US](https://www.shoppingspout.us/)
Check their Facebook Page: [fb.com/shoppingspout](https://fb.com/shoppingspout)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.shoppingspout.us/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.shoppingspout.us/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.shoppingspout.us/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @deanjones
Request made by Twitter user [shoppingspout](https://twitter.com/shoppingspout/), be sure to send out a tweet when this request has been added.
