### ISSUE TITLE
Add 'HostStage' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2253]
Requesting to add 'HostStage' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: HostStage
  url: https://www.host-stage.net
  img: HostStage.png
  bch: true
  btc: true
  othercrypto: true
  facebook: hoststage
  email_address: v.royant@host-stage.net
  city: No 
  doc: https://www.host-stage.net/annoucements/hoststage-now-accept-bitcoincash/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.host-stage.net/wp-content/uploads/2019/06/logo.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/hoststage/picture)
[Link to HostStage](https://www.host-stage.net)
Check their Facebook Page: [fb.com/hoststage](https://fb.com/hoststage)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.host-stage.net)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.host-stage.net)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.host-stage.net)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [hoststage](https://twitter.com/hoststage/), be sure to send out a tweet when this request has been added.
