### ISSUE TITLE
Add 'Currency' to the 'Bitcoin ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2255]
Requesting to add 'Currency' to the 'Bitcoin ' category. 

Details follow: 
```yml 
- name: Currency
  url: tommymills247365@gmail.com
  img: Currency.png
  bch: true
  btc: true
  othercrypto: true
  email_address: tommymills247365@gmail.com
  region: na
  exceptions:
    text: "tommymills247365@gmail.com"
```

Resources for adding this merchant:
[Link to Currency](tommymills247365@gmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/tommymills247365@gmail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/tommymills247365@gmail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/tommymills247365@gmail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
