### ISSUE TITLE
Add 'Private WebHost' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2256]
Requesting to add 'Private WebHost' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: Private WebHost
  url: https://privateweb.ch/
  img: PrivateWebHost.png
  bch: true
  btc: true
  othercrypto: true
  facebook: n/a
  email_address: contact@privateweb.ch
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://privateweb.ch/assets/img/logo.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/n/a/picture)
[Link to Private WebHost](https://privateweb.ch/)
Check their Facebook Page: [fb.com/n/a](https://fb.com/n/a)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/privateweb.ch/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/privateweb.ch/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/privateweb.ch/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
