### ISSUE TITLE
Add 'Wayport Travel Corp' to the 'Luxury Travel Agency' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2257]
Requesting to add 'Wayport Travel Corp' to the 'Luxury Travel Agency' category. 

Details follow: 
```yml 
- name: Wayport Travel Corp
  url: https://www.wayporttravel.com/
  img: WayportTravelCorp.png
  bch: true
  btc: false
  othercrypto: true
  email_address: wes@wayporttravel.com
```

Resources for adding this merchant:
[Link to Wayport Travel Corp](https://www.wayporttravel.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.wayporttravel.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.wayporttravel.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.wayporttravel.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
