### ISSUE TITLE
Add 'Top Tree Herbs' to the 'Tea, Kratom' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2258]
Requesting to add 'Top Tree Herbs' to the 'Tea, Kratom' category. 

Details follow: 
```yml 
- name: Top Tree Herbs
  url: https://toptreeherbs.com/
  img: TopTreeHerbs.png
  bch: false
  btc: true
  othercrypto: false
  facebook: toptreeherbs
  email_address: contact@toptreeherbs.com
  region: na
  country: US
  city: Most US cities and states
  doc: https://toptreeherbs.com/buy-kratom-online/
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://toptreeherbs.com/wp-content/uploads/2023/12/Top-Tree-Herbs-Kratom-Tea-Logo-TTH.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/toptreeherbs/picture)
[Link to Top Tree Herbs](https://toptreeherbs.com/)
Check their Facebook Page: [fb.com/toptreeherbs](https://fb.com/toptreeherbs)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/toptreeherbs.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/toptreeherbs.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/toptreeherbs.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [toptreetea](https://twitter.com/toptreetea/), be sure to send out a tweet when this request has been added.
