### ISSUE TITLE
Add 'ClientVPS' to the 'Hosting,VPS,Domain' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2259]
Requesting to add 'ClientVPS' to the 'Hosting,VPS,Domain' category. 

Details follow: 
```yml 
- name: ClientVPS
  url: https://www.clientvps.com
  img: ClientVPS.png
  bch: true
  btc: true
  othercrypto: true
  email_address: info@clientvps.com
  exceptions:
    text: "Yes, Customers can ask us in onlinechat or tickets for Bitcoin Cash wallet to pay directly"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.clientvps.com/images/footer-logo.webp)
[Link to ClientVPS](https://www.clientvps.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.clientvps.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.clientvps.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.clientvps.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
