### ISSUE TITLE
Requesting to add G2A.com to Gaming category

### ISSUE THREAD

**Issue by memalley** [acceptbitcoincash/acceptbitcoincash#226]
Requesting to add G2A.com to Gaming category. Details follow:

```yml

- name: G2A
  url: https://www.g2a.com/
  twitter: G2a_com
  facebook: G2Acom
  img: https://upload.wikimedia.org/wikipedia/commons/9/95/G2A_Limited_company_logo.jpg
  bcc: no
  btc: yes
  othercrypto: no
  doc: https://www.prnewswire.com/news-releases/gaming-giant-g2a-now-accepts-bitcoin-through-partnership-with-bitpay-532144142.html
  exceptions:
    text: ""
```
