### ISSUE TITLE
Add 'Hosterfy' to the 'Hosting/Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2260]
Requesting to add 'Hosterfy' to the 'Hosting/Gaming' category. 

Details follow: 
```yml 
- name: Hosterfy
  url: https://www.hosterfy.com/fr
  img: Hosterfy.png
  bch: false
  btc: false
  othercrypto: false
  facebook: hosterfy
  email_address: contact@hosterfy.com
  region: eu
  country: FR
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.hosterfy.com/assets/images/resources/v4/logos/hosterfy-logo-1000x1000-color.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/hosterfy/picture)
[Link to Hosterfy](https://www.hosterfy.com/fr)
Check their Facebook Page: [fb.com/hosterfy](https://fb.com/hosterfy)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.hosterfy.com/fr)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.hosterfy.com/fr)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.hosterfy.com/fr)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
