### ISSUE TITLE
Add 'Infinita Graphics & Web' to the 'Web design' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2261]
Requesting to add 'Infinita Graphics & Web' to the 'Web design' category. 

Details follow: 
```yml 
- name: Infinita Graphics & Web
  url: https://www.infinita.biz
  img: InfinitaGraphicsWeb.png
  bch: true
  btc: true
  othercrypto: true
  email_address: info@infinita.biz
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://infinita.biz/wp-content/uploads/2024/01/infinita-300x300px.jpg)
[Link to Infinita Graphics & Web](https://www.infinita.biz)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.infinita.biz)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.infinita.biz)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.infinita.biz)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
