### ISSUE TITLE
Add 'BCHGANG Link Directory' to the 'Directories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2263]
Requesting to add 'BCHGANG Link Directory' to the 'Directories' category. 

Details follow: 
```yml 
- name: BCHGANG Link Directory
  url: https://bchgang.org
  img: BCHGANGLinkDirectory.png
  bch: true
  btc: false
  othercrypto: false
  email_address: georg@bchgang.org
```

Resources for adding this merchant:
[Link to BCHGANG Link Directory](https://bchgang.org)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bchgang.org)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bchgang.org)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bchgang.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @georgengelmann
Request made by Twitter user [georg_engelmann](https://twitter.com/georg_engelmann/), be sure to send out a tweet when this request has been added.
