### ISSUE TITLE
Add 'Ankh Organics' to the 'Psychedelics/Cannabis' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2264]
Requesting to add 'Ankh Organics' to the 'Psychedelics/Cannabis' category. 

Details follow: 
```yml 
- name: Ankh Organics
  url: https://t.me/+xAfLrxLYMu9mNDQx
  img: AnkhOrganics.png
  bch: true
  btc: false
  othercrypto: true
  facebook: ankhorganicsco
  email_address: ankh_organics@protonmail.ch
  region: na
  country: US
  doc: https://t.me/c/1343514826/477
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.facebook.com/photo/?fbid=496596725809726&set=a.496596689143063&__tn__=%3C)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/ankhorganicsco/picture)
[Link to Ankh Organics](https://t.me/+xAfLrxLYMu9mNDQx)
Check their Facebook Page: [fb.com/ankhorganicsco](https://fb.com/ankhorganicsco)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/t.me/+xAfLrxLYMu9mNDQx)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/t.me/+xAfLrxLYMu9mNDQx)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/t.me/+xAfLrxLYMu9mNDQx)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
