### ISSUE TITLE
Add 'Skhron' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2265]
Requesting to add 'Skhron' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: Skhron
  url: https://skhron.com.ua/
  img: Skhron.png
  bch: true
  btc: true
  othercrypto: true
  email_address: pr+acceptbitcoincash@skhron.com.ua
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://skhron.com.ua/assets/img/logo-square.png)
[Link to Skhron](https://skhron.com.ua/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/skhron.com.ua/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/skhron.com.ua/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/skhron.com.ua/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
