### ISSUE TITLE
Add 'Crypto Luxury Store' to the 'E-commerce' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2266]
Requesting to add 'Crypto Luxury Store' to the 'E-commerce' category. 

Details follow: 
```yml 
- name: Crypto Luxury Store
  url: https://crypto-luxury.io/
  img: CryptoLuxuryStore.png
  bch: true
  btc: true
  othercrypto: true
  email_address: support_team@crypto-luxury.io
  city: No. It is Global service.
  doc: https://crypto-luxury.io/how-to-shop-with-crypto-at-crypto-luxury-store/
  exceptions:
    text: "No."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1720042495898193920/QOKcnjBV_400x400.jpg)
[Link to Crypto Luxury Store](https://crypto-luxury.io/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/crypto-luxury.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/crypto-luxury.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/crypto-luxury.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
