### ISSUE TITLE
Add 'Gift Card Space' to the 'E-commerce' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2267]
Requesting to add 'Gift Card Space' to the 'E-commerce' category. 

Details follow: 
```yml 
- name: Gift Card Space
  url: https://giftcard-space.com/
  img: GiftCardSpace.png
  bch: true
  btc: true
  othercrypto: true
  email_address: support@giftcard-space.com
  city: No. It is global service.
  doc: https://giftcard-space.com/how-to-shop-with-cryptocurrency-at-gift-card-space/
  exceptions:
    text: "No."
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1720042495898193920/QOKcnjBV_400x400.jpg)
[Link to Gift Card Space](https://giftcard-space.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/giftcard-space.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/giftcard-space.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/giftcard-space.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
