### ISSUE TITLE
Add 'www.compartsystems.com' to the 'Electronic Repair Shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2269]
Requesting to add 'www.compartsystems.com' to the 'Electronic Repair Shop' category. 

Details follow: 
```yml 
- name: www.compartsystems.com
  url: https://www.compartsystems.pt
  img: wwwcompartsystemscom.png
  bch: true
  btc: true
  othercrypto: true
  region: eu
  country: PT
```

Resources for adding this merchant:
[Link to www.compartsystems.com](https://www.compartsystems.pt)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.compartsystems.pt)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.compartsystems.pt)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.compartsystems.pt)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
