### ISSUE TITLE
Fairlay

### ISSUE THREAD

**Issue by Fairlay** [acceptbitcoincash/acceptbitcoincash#227]
_Please fill in the template below, and don't worry about exact formatting, just do your best!_

Requesting to add {{Fairlay}} to the {{ Gambling }} category. Details follow:

```yml

- name: Fairlay.com - Bitcoin Prediction Market
  url: https://fairlay.com
  twitter: fairlayPM
  facebook: fairlay
  img: 
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: 
  exceptions:
    text: "general_comments_or_notes_here___do_not_remove_quotes"
```
