### ISSUE TITLE
Add 'Grade A Ink Tattoo and Piercing Studios' to the 'Tattoo and Piercing Studios' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2270]
Requesting to add 'Grade A Ink Tattoo and Piercing Studios' to the 'Tattoo and Piercing Studios' category. 

Details follow: 
```yml 
- name: Grade A Ink Tattoo and Piercing Studios
  url: www.gradeaink.com
  img: GradeAInkTattooandPiercingStudios.png
  bch: true
  btc: true
  othercrypto: true
  facebook: gradeainktattoostudios
  email_address: info@gradeaink.com
  region: na
  country: US
  city: Los Angeles and Atlanta
  doc: https://www.gradeaink.com/book-appointment/online-payments
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1774466703432257536/-QP6dWmt)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/gradeainktattoostudios/picture)
[Link to Grade A Ink Tattoo and Piercing Studios](www.gradeaink.com)
Check their Facebook Page: [fb.com/gradeainktattoostudios](https://fb.com/gradeainktattoostudios)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.gradeaink.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.gradeaink.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.gradeaink.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @n/a
Request made by Twitter user [gradeainktattoo](https://twitter.com/gradeainktattoo/), be sure to send out a tweet when this request has been added.
