### ISSUE TITLE
Add 'Beauty Shine' to the 'Shopping' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2272]
Requesting to add 'Beauty Shine' to the 'Shopping' category. 

Details follow: 
```yml 
- name: Beauty Shine
  url: www.beautyshineonesie.com
  img: BeautyShine.png
  bch: true
  btc: true
  othercrypto: true
  facebook: beautyshine
  email_address: support@beautyshineonesie.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://img.staticdj.com/0651c220b5bf10c57df23da0b0a66a9b.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/beautyshine/picture)
[Link to Beauty Shine](www.beautyshineonesie.com)
Check their Facebook Page: [fb.com/beautyshine](https://fb.com/beautyshine)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.beautyshineonesie.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.beautyshineonesie.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.beautyshineonesie.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
