### ISSUE TITLE
Add 'anotld' to the 'domains service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2273]
Requesting to add 'anotld' to the 'domains service' category. 

Details follow: 
```yml 
- name: anotld
  url: https://anotld.com/
  img: anotld.png
  bch: true
  btc: false
  othercrypto: true
  email_address: anotld@proton.me
```

Resources for adding this merchant:
[Link to anotld](https://anotld.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/anotld.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/anotld.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/anotld.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
