### ISSUE TITLE
Add 'Initech' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2274]
Requesting to add 'Initech' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: Initech
  url: https://initech.global
  img: Initech.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
[Link to Initech](https://initech.global)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/initech.global)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/initech.global)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/initech.global)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
