### ISSUE TITLE
Add 'RESSULTICKS' to the 'Cloud Computing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2275]
Requesting to add 'RESSULTICKS' to the 'Cloud Computing' category. 

Details follow: 
```yml 
- name: RESSULTICKS
  url: https://www.resulticks.com
  img: RESSULTICKS.png
  bch: false
  btc: false
  othercrypto: false
  facebook: resulticks
  email_address: marketing@resulticks.com
  region: as
  country: SG
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/1734903589448069120/TkT7SI8y_400x400.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/resulticks/picture)
[Link to RESSULTICKS](https://www.resulticks.com)
Check their Facebook Page: [fb.com/resulticks](https://fb.com/resulticks)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.resulticks.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.resulticks.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.resulticks.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
