### ISSUE TITLE
Add 'rdp.monster' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by HostingVerds** [acceptbitcoincash/acceptbitcoincash#2276]
Requesting to add 'rdp.monster' to the 'Hosting & VPS' category. 

Details follow:

```yml

- name: rdp.monster
  url: https://rdp.monster
  img: rdpmonster.png
  twitter: rdp_monster
  bch: true
  btc: true
  othercrypto: true
```
Resources for adding this merchant:
Logo provided :
![rdpmonster](https://github.com/acceptbitcoincash/acceptbitcoincash/assets/174010780/a8a98c85-3314-4cfd-a8f5-58f3d6174cab)

Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/rdp.monster

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:

- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with closes #[ISSUE NUMBER HERE].
