### ISSUE TITLE
Add 'Hermes VPN' to the 'VPN' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2277]
Requesting to add 'Hermes VPN' to the 'VPN' category. 

Details follow: 
```yml 
- name: Hermes VPN
  url: https://hermesvpn.pro
  img: HermesVPN.png
  bch: true
  btc: false
  othercrypto: true
  email_address: support@hermesvpn.pro
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://x.com/HermesVpn/photo)
[Link to Hermes VPN](https://hermesvpn.pro)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/hermesvpn.pro)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/hermesvpn.pro)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/hermesvpn.pro)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
