### ISSUE TITLE
Add 'Zain Hosting Ltd' to the 'Web Hosting, Servers, RDP' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2278]
Requesting to add 'Zain Hosting Ltd' to the 'Web Hosting, Servers, RDP' category. 

Details follow: 
```yml 
- name: Zain Hosting Ltd
  url: https://www.zainhosting.com
  img: ZainHostingLtd.png
  bch: true
  btc: true
  othercrypto: true
  facebook: zainhosting
  email_address: support@zainhosting.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.zainhosting.com/wp-content/uploads/2020/12/zainhosting-logo-84x84.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/zainhosting/picture)
[Link to Zain Hosting Ltd](https://www.zainhosting.com)
Check their Facebook Page: [fb.com/zainhosting](https://fb.com/zainhosting)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.zainhosting.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.zainhosting.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.zainhosting.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
