### ISSUE TITLE
Add 'Software Shop' to the 'Software sales' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2280]
Requesting to add 'Software Shop' to the 'Software sales' category. 

Details follow: 
```yml 
- name: Software Shop
  url: https://softwareshopk.com
  img: SoftwareShop.png
  bch: true
  btc: true
  othercrypto: true
  email_address: info@softwareshopk.com
  country: US
```

Resources for adding this merchant:
[Link to Software Shop](https://softwareshopk.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/softwareshopk.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/softwareshopk.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/softwareshopk.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
