### ISSUE TITLE
Add 'Cloudblast' to the 'Hosting Provider' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2282]
Requesting to add 'Cloudblast' to the 'Hosting Provider' category. 

Details follow: 
```yml 
- name: Cloudblast
  url: https://cloudblast.io/
  img: Cloudblast.png
  bch: true
  btc: true
  othercrypto: true
  email_address: hello@cloudblast.io
  region: eu
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/0NXbuIl.png)
[Link to Cloudblast](https://cloudblast.io/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cloudblast.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cloudblast.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cloudblast.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
