### ISSUE TITLE
Add 'Sexting AI' to the 'AI' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2283]
Requesting to add 'Sexting AI' to the 'AI' category. 

Details follow: 
```yml 
- name: Sexting AI
  url: https://sextingai.co/
  img: SextingAI.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://i.imgur.com/LRED8Ri.png)
[Link to Sexting AI](https://sextingai.co/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/sextingai.co/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/sextingai.co/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/sextingai.co/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
