### ISSUE TITLE
Add 'FITSAUNA' to the 'Health & Fitness' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2284]
Requesting to add 'FITSAUNA' to the 'Health & Fitness' category. 

Details follow: 
```yml 
- name: FITSAUNA
  url: https://www.fitsauna.com
  img: FITSAUNA.png
  bch: true
  btc: true
  othercrypto: true
  facebook: fitsaunas
  email_address: sales@fitsauna.com
  exceptions:
    text: "directly contact us to get access to deposit key"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](http://fitsauna.com/wp-content/uploads/2023/04/FINAL-ICON.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/fitsaunas/picture)
[Link to FITSAUNA](https://www.fitsauna.com)
Check their Facebook Page: [fb.com/fitsaunas](https://fb.com/fitsaunas)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.fitsauna.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.fitsauna.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.fitsauna.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
