### ISSUE TITLE
Add 'BPname' to the 'domain' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2285]
Requesting to add 'BPname' to the 'domain' category. 

Details follow: 
```yml 
- name: BPname
  url: https://bpname.com/
  img: BPname.png
  bch: true
  btc: true
  othercrypto: true
  country: CH
```

Resources for adding this merchant:
[Link to BPname](https://bpname.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bpname.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bpname.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bpname.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
