### ISSUE TITLE
Add 'CloudBlast' to the 'Web Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2287]
Requesting to add 'CloudBlast' to the 'Web Hosting & VPS' category. 

Details follow: 
```yml 
- name: CloudBlast
  url: https://cloudblast.io/
  img: CloudBlast.png
  bch: true
  btc: true
  othercrypto: true
  facebook: cloudblastio
  email_address: hello@cloudblast.io
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://avatars.githubusercontent.com/u/168455625?v=4)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/cloudblastio/picture)
[Link to CloudBlast](https://cloudblast.io/)
Check their Facebook Page: [fb.com/cloudblastio](https://fb.com/cloudblastio)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/cloudblast.io/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/cloudblast.io/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/cloudblast.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
