### ISSUE TITLE
Add 'James Fort' to the 'Bitcoincash' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2290]
Requesting to add 'James Fort' to the 'Bitcoincash' category. 

Details follow: 
```yml 
- name: James Fort
  url: http://webn2themouthofmaddness.net
  img: JamesFort.png
  bch: true
  btc: true
  othercrypto: true
  facebook: jesse
  email_address: fortjamey@icloud.com
  country: US
  city: Augusta 
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/jesse/picture)
[Link to James Fort](http://webn2themouthofmaddness.net)
Check their Facebook Page: [fb.com/jesse](https://fb.com/jesse)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/webn2themouthofmaddness.net)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/webn2themouthofmaddness.net)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/webn2themouthofmaddness.net)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
