### ISSUE TITLE
Add 'https://www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==' to the 'Street Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2292]
Requesting to add 'https://www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==' to the 'Street Food' category. 

Details follow: 
```yml 
- name: https://www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==
  url: https://www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==
  img: httpswwwinstagramcompastaladolcevitaprofilecardigshMTZMxpMXBieWcMQ.png
  bch: false
  btc: true
  othercrypto: false
  email_address: drizzled777@gmail.com
  region: eu
  country: GB
  city: London
```

Resources for adding this merchant:
[Link to https://www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==](https://www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.instagram.com/pastaladolcevita/profilecard/?igsh=MTZ0M2xpMXBieWc1MQ==)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
