### ISSUE TITLE
Add 'EcoDirect.com' to the 'Solar Distributor' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2294]
Requesting to add 'EcoDirect.com' to the 'Solar Distributor' category. 

Details follow: 
```yml 
- name: EcoDirect.com
  url: https://www.ecodirect.com
  img: EcoDirectcom.png
  bch: true
  btc: true
  othercrypto: false
  email_address: admin@ecodirect.com
```

Resources for adding this merchant:
[Link to EcoDirect.com](https://www.ecodirect.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.ecodirect.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.ecodirect.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.ecodirect.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
