### ISSUE TITLE
Add 'Bazaars' to the 'Cryptocommerce' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2297]
Requesting to add 'Bazaars' to the 'Cryptocommerce' category. 

Details follow: 
```yml 
- name: Bazaars
  url: https://bazaars.app
  img: Bazaars.png
  bch: false
  btc: false
  othercrypto: true
  facebook: bazaarsapp
  email_address: support@bazaars.app
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://avatars.githubusercontent.com/u/102147094?v=4)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/bazaarsapp/picture)
[Link to Bazaars](https://bazaars.app)
Check their Facebook Page: [fb.com/bazaarsapp](https://fb.com/bazaarsapp)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/bazaars.app)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/bazaars.app)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/bazaars.app)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by @bazaarsbzr
Request made by Twitter user [x.com/bazaarsbzr](https://twitter.com/x.com/bazaarsbzr/), be sure to send out a tweet when this request has been added.
