### ISSUE TITLE
Add 'MystoryTeapal' to the 'Tea sets' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2298]
Requesting to add 'MystoryTeapal' to the 'Tea sets' category. 

Details follow: 
```yml 
- name: MystoryTeapal
  url: https://mystoryteapal.com
  img: MystoryTeapal.png
  bch: false
  btc: false
  othercrypto: false
```

Resources for adding this merchant:
[Link to MystoryTeapal](https://mystoryteapal.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/mystoryteapal.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/mystoryteapal.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/mystoryteapal.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
