### ISSUE TITLE
Add 'Riviera Shore Excursions' to the 'Travel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2299]
Requesting to add 'Riviera Shore Excursions' to the 'Travel' category. 

Details follow: 
```yml 
- name: Riviera Shore Excursions
  url: https://riviera-shore-excursions.com/
  img: RivieraShoreExcursions.png
  bch: true
  btc: true
  othercrypto: false
  email_address: booking@riviera-shore-excursions.com
  region: eu
  country: FR
  city: Nice
```

Resources for adding this merchant:
[Link to Riviera Shore Excursions](https://riviera-shore-excursions.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/riviera-shore-excursions.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/riviera-shore-excursions.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/riviera-shore-excursions.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
