### ISSUE TITLE
Kawaii Crypto - we accept Bitcoin Cash

### ISSUE THREAD

**Issue by fluffywiggle** [acceptbitcoincash/acceptbitcoincash#230]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Kawaii Crypto to the Retail category. Details follow:

```yml

- name: Kawaii Crypto
  url: https://kawaiicrypto.com
  twitter: kawaii_crypto
  facebook: facebook_username
  img: https://kawaiicrypto.com/image/catalog/logo.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://kawaiicrypto.com/about-us-kawaii-crypto-vinyl-stickers
```

We sell adorable crypto themed stickers- represent your favorite Cryptocurrency in the most adorable way! Great gifts for friends, family, and kids!
