### ISSUE TITLE
Add 'VIKHOST' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2300]
Requesting to add 'VIKHOST' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: VIKHOST
  url: https://vikhost.com/
  img: VIKHOST.png
  bch: true
  btc: true
  othercrypto: true
  facebook: vikhost
  email_address: info@vikhost.com
  region: eu
  country: UA
  city: Kyiv
  doc: https://vikhost.com/bitcoin-vps
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://vikhost.com/wp-content/uploads/2025/01/vikhost-logo.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/vikhost/picture)
[Link to VIKHOST](https://vikhost.com/)
Check their Facebook Page: [fb.com/vikhost](https://fb.com/vikhost)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/vikhost.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/vikhost.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/vikhost.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [vikhost](https://twitter.com/vikhost/), be sure to send out a tweet when this request has been added.
