### ISSUE TITLE
Add 'eaewywuwnajaiwu@gmail.com' to the 'Bitcoin' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2301]
Requesting to add 'eaewywuwnajaiwu@gmail.com' to the 'Bitcoin' category. 

Details follow: 
```yml 
- name: eaewywuwnajaiwu@gmail.com
  url: eaewywuwnajaiwu@gmail.com
  img: eaewywuwnajaiwugmailcom.png
  bch: true
  btc: false
  othercrypto: true
  region: af
  country: AU
```

Resources for adding this merchant:
[Link to eaewywuwnajaiwu@gmail.com](eaewywuwnajaiwu@gmail.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/eaewywuwnajaiwu@gmail.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/eaewywuwnajaiwu@gmail.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/eaewywuwnajaiwu@gmail.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
