### ISSUE TITLE
Add 'Sheepy' to the 'Crypto payment gateway' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2302]
Requesting to add 'Sheepy' to the 'Crypto payment gateway' category. 

Details follow: 
```yml 
- name: Sheepy
  url: https://www.sheepy.com/
  img: Sheepy.png
  bch: true
  btc: false
  othercrypto: true
  facebook: sheepycrypto
  email_address: fg@sheepy.com
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://x.com/Sheepy_crypto/photo)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/sheepycrypto/picture)
[Link to Sheepy](https://www.sheepy.com/)
Check their Facebook Page: [fb.com/sheepycrypto](https://fb.com/sheepycrypto)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.sheepy.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.sheepy.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.sheepy.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [sheepy_crypto](https://twitter.com/sheepy_crypto/), be sure to send out a tweet when this request has been added.
