### ISSUE TITLE
Add 'RapidSeedbox' to the 'Hosting & VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2303]
Requesting to add 'RapidSeedbox' to the 'Hosting & VPS' category. 

Details follow: 
```yml 
- name: RapidSeedbox
  url: https://www.rapidseedbox.com/
  img: RapidSeedbox.png
  bch: true
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.rapidseedbox.com/wp-content/themes/rsb2020/img/logo-new-colors-new.svg)
[Link to RapidSeedbox](https://www.rapidseedbox.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.rapidseedbox.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.rapidseedbox.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.rapidseedbox.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
