### ISSUE TITLE
Add '0x0897fAD0A063A552233f29459DB91902140388F5' to the 'Alfatop.me' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2304]
Requesting to add '0x0897fAD0A063A552233f29459DB91902140388F5' to the 'Alfatop.me' category. 

Details follow: 
```yml 
- name: 0x0897fAD0A063A552233f29459DB91902140388F5
  url: https://learn.bybit.com/trading/
  img: xfADAAfDBF.png
  bch: true
  btc: true
  othercrypto: true
  facebook: 91902140388
  email_address: anakhuagborosigbemhe@gmail.com
  country: NG
  exceptions:
    text: "Yes 🥰"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](Alfatop.me)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/91902140388/picture)
[Link to 0x0897fAD0A063A552233f29459DB91902140388F5](https://learn.bybit.com/trading/)
Check their Facebook Page: [fb.com/91902140388](https://fb.com/91902140388)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/learn.bybit.com/trading/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/learn.bybit.com/trading/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/learn.bybit.com/trading/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
