### ISSUE TITLE
Add 'IT Deweloper' to the 'Web Development Agency' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2305]
Requesting to add 'IT Deweloper' to the 'Web Development Agency' category. 

Details follow: 
```yml 
- name: IT Deweloper
  url: https://it-deweloper.pl/en
  img: ITDeweloper.png
  bch: true
  btc: true
  othercrypto: true
  facebook: itdeweloper
  email_address: office@it-deweloper.pl
  region: eu
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://it-deweloper.pl/images/logo-dark.webp)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/itdeweloper/picture)
[Link to IT Deweloper](https://it-deweloper.pl/en)
Check their Facebook Page: [fb.com/itdeweloper](https://fb.com/itdeweloper)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/it-deweloper.pl/en)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/it-deweloper.pl/en)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/it-deweloper.pl/en)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
