### ISSUE TITLE
Add 'Deliveringparcel' to the 'parcel forwarding ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2306]
Requesting to add 'Deliveringparcel' to the 'parcel forwarding ' category. 

Details follow: 
```yml 
- name: Deliveringparcel
  url: www.deliveringparcel.com
  img: Deliveringparcel.png
  bch: true
  btc: true
  othercrypto: false
  email_address: admin@deliveringparcel.com
```

Resources for adding this merchant:
[Link to Deliveringparcel](www.deliveringparcel.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.deliveringparcel.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.deliveringparcel.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.deliveringparcel.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
