### ISSUE TITLE
Add 'Administrator' to the 'Administrator' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2307]
Requesting to add 'Administrator' to the 'Administrator' category. 

Details follow: 
```yml 
- name: Administrator
  url: https://Admin.com
  img: Administrator.png
  bch: true
  btc: true
  othercrypto: true
  region: as
  country: BR
  city: Administrator
  exceptions:
    text: "Administrator"
```

Resources for adding this merchant:
[Link to Administrator](https://Admin.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/Admin.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/Admin.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/Admin.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
