### ISSUE TITLE
Add 'Taller del Sur' to the 'Automotive, Car repair shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2308]
Requesting to add 'Taller del Sur' to the 'Automotive, Car repair shop' category. 

Details follow: 
```yml 
- name: Taller del Sur
  url: https://tallerdelsur.com/
  img: TallerdelSur.png
  bch: true
  btc: true
  othercrypto: true
  facebook: tallerdelsursabaneta
  email_address: matthias.schoenebeck@gmail.com
  region: sa
  country: CO
  city: Sabaneta, Antioquia
  doc: https://tallerdelsur.com
  exceptions:
    text: "simple checkout via QR code scanning"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://tallerdelsur.com/wp-content/uploads/2022/10/Artboard-1-1024x502.png)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/tallerdelsursabaneta/picture)
[Link to Taller del Sur](https://tallerdelsur.com/)
Check their Facebook Page: [fb.com/tallerdelsursabaneta](https://fb.com/tallerdelsursabaneta)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/tallerdelsur.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/tallerdelsur.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/tallerdelsur.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
