### ISSUE TITLE
Please add Wikileaks Shop

### ISSUE THREAD

**Issue by Albeos90** [acceptbitcoincash/acceptbitcoincash#231]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ wikileaks.shop }} to the {{ Retail }} category. Details follow:

```yml

- name: wikileaks.shop
https://wikileaks.shop/
  twitter: @wikileaksshop
  facebook: facebook_username
  img: URL_to_image
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_article_or_help_guide_etc
```

Add more information here if necessary
