### ISSUE TITLE
Add 'Dunk Legends Apparel' to the 'Apparel clothing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2311]
Requesting to add 'Dunk Legends Apparel' to the 'Apparel clothing' category. 

Details follow: 
```yml 
- name: Dunk Legends Apparel
  url: http://dunklegendsapparel.com
  img: DunkLegendsApparel.png
  bch: true
  btc: false
  othercrypto: true
  email_address: bob@dunklegendsapparel.com
  region: na
  country: US
  exceptions:
    text: "Check out cart"
```

Resources for adding this merchant:
[Link to Dunk Legends Apparel](http://dunklegendsapparel.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/dunklegendsapparel.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/dunklegendsapparel.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/dunklegendsapparel.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
