### ISSUE TITLE
Add 'Carriage Auto Sales' to the 'Car Sales' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2312]
Requesting to add 'Carriage Auto Sales' to the 'Car Sales' category. 

Details follow: 
```yml 
- name: Carriage Auto Sales
  url: https://profile.tecobi.com/carriage-used-cars/jockasn-lezama-29582
  img: CarriageAutoSales.png
  bch: true
  btc: true
  othercrypto: true
  email_address: Jlezama@choosecarriage.com
  region: na
  country: US
  city: Atlanta
  exceptions:
    text: "We would just need to send the link for the transfer and agree to numbers"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://storage.googleapis.com/algmedia/widgets/logos/2025/01/13/logo-header_1.png?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=184062445992-htoa7dfdgmvghsigffauah40rjtff3mo%40developer.gserviceaccount.com%2F20250322%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250322T153351Z&X-Goog-Expires=86400&X-Goog-SignedHeaders=host&X-Goog-Signature=71738910471c9dcfc9174feebace14ea52b0378774b86278f3f1f5f20e16504099205db66276ff0834ab94f22f10cea3a42c84442212726fb2ab391243824bacf3ca3c23bc9be56f897c6c01af5cc27f628af3822eaf5d1e19e2f370c24d32f7ede66a05a7e69ec8b7afbf48d83dce6baca8d5dc6682375f91e5fb3455c6345f36fc873f495e2cddeae270dce1e8a2c1ac868e7160a1859aa872afb7a2424bf31e4abaf54ede2edefd30b990c1031c5cc2f5815be6b3f01c59e77c371993be921157ebebf71c3597d50d4ef9bebf4f222cdefbf27f077577545374191c37ce21a1912978bddc6c530747272c073a1d5a6b96952a3f32663282da8f70ac59e716)
[Link to Carriage Auto Sales](https://profile.tecobi.com/carriage-used-cars/jockasn-lezama-29582)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/profile.tecobi.com/carriage-used-cars/jockasn-lezama-29582)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/profile.tecobi.com/carriage-used-cars/jockasn-lezama-29582)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/profile.tecobi.com/carriage-used-cars/jockasn-lezama-29582)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
