### ISSUE TITLE
Add 'Worldofbitcoin' to the 'History and Education & Shop ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2314]
Requesting to add 'Worldofbitcoin' to the 'History and Education & Shop ' category. 

Details follow: 
```yml 
- name: Worldofbitcoin
  url: Https://www.worldofbitcoin.com
  img: Worldofbitcoin.png
  bch: true
  btc: false
  othercrypto: false
  email_address: bitcoinotary@icloud.com
  exceptions:
    text: "Must have a Bitcoin Cash Node wallet or any other Bitcoin cash SPV wallet or POS paytaca"
```

Resources for adding this merchant:
[Link to Worldofbitcoin](Https://www.worldofbitcoin.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/Https://www.worldofbitcoin.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/Https://www.worldofbitcoin.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/Https://www.worldofbitcoin.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
