### ISSUE TITLE
Add 'Escrowfy' to the 'Marketplace' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2315]
Requesting to add 'Escrowfy' to the 'Marketplace' category. 

Details follow: 
```yml 
- name: Escrowfy
  url: https://www.escrowfy.net
  img: Escrowfy.png
  bch: false
  btc: true
  othercrypto: true
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.escrowfy.net/images/logo.svg)
[Link to Escrowfy](https://www.escrowfy.net)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.escrowfy.net)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.escrowfy.net)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.escrowfy.net)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
