### ISSUE TITLE
Add 'Umitech' to the 'Main > Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2317]
Requesting to add 'Umitech' to the 'Main > Services' category. 

Details follow: 
```yml 
- name: Umitech
  url: https://umitech.com.au/
  img: Umitech.png
  bch: true
  btc: true
  othercrypto: true
  facebook: umitech.com.au
  email_address: social@umitech.com.au
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://media.licdn.com/dms/image/v2/D4D0BAQEPXDJKPveyWQ/company-logo_200_200/B4DZZX0PoGG4AI-/0/1745230036123/umitech_au_logo?e=1750896000&v=beta&t=3dh5GUNOYSEQ1JAJn-Fhx07VwwGqTy3ixVZ752EBcSg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/umitech.com.au/picture)
[Link to Umitech](https://umitech.com.au/)
Check their Facebook Page: [fb.com/umitech.com.au](https://fb.com/umitech.com.au)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/umitech.com.au/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/umitech.com.au/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/umitech.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

Request made by Twitter user [umitechau](https://twitter.com/umitechau/), be sure to send out a tweet when this request has been added.
