### ISSUE TITLE
Add 'NoKYC.Card' to the 'Prepaid cards' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2318]
Requesting to add 'NoKYC.Card' to the 'Prepaid cards' category. 

Details follow: 
```yml 
- name: NoKYC.Card
  url: https://nokyc.cards/
  img: NoKYCCard.png
  bch: true
  btc: true
  othercrypto: true
  email_address: support@nokyc.cards
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://nokyc.cards/wp-content/uploads/2025/04/20250430_182905_0000.jpg)
[Link to NoKYC.Card](https://nokyc.cards/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/nokyc.cards/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/nokyc.cards/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/nokyc.cards/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
