### ISSUE TITLE
Add 'GUYA' to the 'Food & Drinks' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2319]
Requesting to add 'GUYA' to the 'Food & Drinks' category. 

Details follow: 
```yml 
- name: GUYA
  url: https://www.drinkguya.com/
  img: GUYA.png
  bch: true
  btc: true
  othercrypto: true
  region: eu
  doc: https://www.drinkguya.com/blogs/storys-und-neuheiten/mit-bitcoin-bezahlen-und-20-rabatt-erhalten-onlineshop-fur-nachhaltige-produkte
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://www.drinkguya.com/cdn/shop/files/20190117_GUYA_Logo_sRGB_Green_300px_SQUARE_WEBSITE.png?v=1649955247&width=200)
[Link to GUYA](https://www.drinkguya.com/)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.drinkguya.com/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.drinkguya.com/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.drinkguya.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
