### ISSUE TITLE
Cryptohabit - Buy T Shirts and Merchandise with Bitcoin Cash

### ISSUE THREAD

**Issue by theantnest** [acceptbitcoincash/acceptbitcoincash#232]
Requesting to add Cryptohabit to the Retail category. Details follow:

```yml

- name: Cryptohabit
  url: https://cryptohabit.com
  twitter: theantnest
  facebook: nope
  img: URL_to_image
  bcc: yes
  btc: no
  othercrypto: yes
  doc: 
```

Buy T-shirts and merchandise with Bitcoin Cash, Litecoin & DASH
