### ISSUE TITLE
Add 'blog7' to the 'Web development' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2320]
Requesting to add 'blog7' to the 'Web development' category. 

Details follow: 
```yml 
- name: blog7
  url: https://blog7.org
  img: blog.png
  bch: true
  btc: true
  othercrypto: true
  email_address: info@blog7.org
  region: eu
  country: BG
```

Resources for adding this merchant:
[Link to blog7](https://blog7.org)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/blog7.org)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/blog7.org)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/blog7.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
