### ISSUE TITLE
Add 'Lusol Canarias' to the 'Servicio técnico informático' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2323]
Requesting to add 'Lusol Canarias' to the 'Servicio técnico informático' category. 

Details follow: 
```yml 
- name: Lusol Canarias
  url: https://www.lusol.es
  img: LusolCanarias.png
  bch: true
  btc: true
  othercrypto: true
  facebook: lusolcanarias
  email_address: info@lusol.es
  region: eu
  country: ES
  city: Las Palmas de Gran Canaria
```

Resources for adding this merchant:
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/lusolcanarias/picture)
[Link to Lusol Canarias](https://www.lusol.es)
Check their Facebook Page: [fb.com/lusolcanarias](https://fb.com/lusolcanarias)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.lusol.es)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.lusol.es)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.lusol.es)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
