### ISSUE TITLE
Add 'Service Lab' to the 'Web Agency' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2324]
Requesting to add 'Service Lab' to the 'Web Agency' category. 

Details follow: 
```yml 
- name: Service Lab
  url: https://www.service-lab.com
  img: ServiceLab.png
  bch: false
  btc: false
  othercrypto: true
  email_address: servicelab@gmail.com
  region: eu
  country: IT
```

Resources for adding this merchant:
[Link to Service Lab](https://www.service-lab.com)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/www.service-lab.com)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/www.service-lab.com)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/www.service-lab.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
