### ISSUE TITLE
Add 'Buy RDP - Web Pundits' to the 'Technology' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2325]
Requesting to add 'Buy RDP - Web Pundits' to the 'Technology' category. 

Details follow: 
```yml 
- name: Buy RDP - Web Pundits
  url: https://webpundits.in
  img: BuyRDPWebPundits.png
  bch: true
  btc: true
  othercrypto: true
  facebook: webpundits
  email_address: support@webpundits.in
  exceptions:
    text: "We use Cryptomus as our gateway"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://webpundits.in/clients/assets/img/logo.jpg)
Facebook Profile Image:
![FacebookProfileImageURL](https://graph.facebook.com/v3.1/webpundits/picture)
[Link to Buy RDP - Web Pundits](https://webpundits.in)
Check their Facebook Page: [fb.com/webpundits](https://fb.com/webpundits)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/webpundits.in)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/webpundits.in)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/webpundits.in)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
