### ISSUE TITLE
Add 'Happymining' to the 'Crypto Mining' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#2326]
Requesting to add 'Happymining' to the 'Crypto Mining' category. 

Details follow: 
```yml 
- name: Happymining
  url: https://happymining.eu
  img: Happymining.png
  bch: true
  btc: true
  othercrypto: true
  email_address: contact@happymining.fr
  country: FR
  exceptions:
    text: "no, payment BTC accepted"
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://happymining.eu/cdn/shop/files/HAPPYMINING_No_Border.png?v=1630933967)
[Link to Happymining](https://happymining.eu)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/happymining.eu)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/happymining.eu)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/happymining.eu)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
