### ISSUE TITLE
Request to add Crypto Habit

### ISSUE THREAD

**Issue by ftrader** [acceptbitcoincash/acceptbitcoincash#233]
Requesting to add Crypto Habit to the Retail category. Details follow:

```yml

- name: Crypto Habit
  url: https://cryptohabit.com
  twitter: -
  facebook: -
  img: -
  bcc: yes
  btc: no
  othercrypto: yes
  doc: https://cryptohabit.com/faq ("Why don't we accept Bitcoin?" - goes on to explain why they accept Bitcoin Cash)
```

Found their site via a tweet which linked to their FAQ.
Not sure if you can add them as they don't seem to have a Twitter handle or Facebook.
