### ISSUE TITLE
State of Zug, Switzerland - Pay taxes with btc and eth

### ISSUE THREAD

**Issue by Tonio-ch** [acceptbitcoincash/acceptbitcoincash#234]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add State of Zug, Switzerland to the Government category. Details follow:

```yml

- name: Kanton Zug
  url: https://www.zg.ch/
  twitter:  stadtzug
  facebook: 
  img: https://www.zg.ch/logo.gif
  bcc: no
  btc: yes
  othercrypto: yes
  doc: https://www.zg.ch/behoerden/volkswirtschaftsdirektion/handelsregisteramt/aktuell/handelsregisteramt-zug-akzeptiert-kryptowaehrungen-bitcoin-und-ether-als-zahlungsmittel?searchterm=bitcoin
```

Add more information here if necessary
