### ISSUE TITLE
Adding Mercado Bitcoin

### ISSUE THREAD

**Issue by lvella** [acceptbitcoincash/acceptbitcoincash#243]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Mercado Bitcoin to the Crypto Exchanges category. Details follow:

```yml

- name: Mercado Bitcoin
  url: https://www.mercadobitcoin.com.br/
  twitter: MercadoBitcoin
  facebook: mbitcoin
  img: https://www.mercadobitcoin.com.br/static/img/logo/mb-logo-mini-only.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://www.mercadobitcoin.com.br/comprar-e-vender-bitcoin-cash/
```

Platform refers to Bitcoin Cash as "Bcash".
