### ISSUE TITLE
Request to add Braziliex exchange

### ISSUE THREAD

**Issue by lvella** [acceptbitcoincash/acceptbitcoincash#244]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Braziliex to the Crypto Exchanges category. Details follow:

```yml

- name: Braziliex
  url: https://braziliex.com/
  twitter: braziliextrades
  facebook: braziliex
  img: https://braziliex.com/img/logo_topo.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: 
```
