### ISSUE TITLE
Request to add Foxbit

### ISSUE THREAD

**Issue by lvella** [acceptbitcoincash/acceptbitcoincash#245]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Foxbit to the Crypto Exchanges category. Details follow:

```yml

- name: Foxbit
  url: https://foxbit.com.br/
  twitter: foxbitcoin
  facebook: foxbitcoin
  img: https://foxbit.com.br/Content/images/logo.png
  bcc: no
  btc: yes
  othercrypto: no
  doc:
```
