### ISSUE TITLE
Adding NiceVPS.net to merchants list

### ISSUE THREAD

**Issue by nicevps** [acceptbitcoincash/acceptbitcoincash#246]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add NiceVPS.net to the Hosting/VPS,Domains category. Details follow:

```yml

- name: NiceVPS.net - Anonymous Hosting, VPS, VPN and Domains.
  url: https://nicevps.net
  twitter: Nice_VPS
  facebook: -
  img: https://nicevps.net/media/logo_nicevps.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://nicevps.net/index/payments
```

Add more information here if necessary
Thanks!
