### ISSUE TITLE
Banking Category - Bitcoin ATMs accepting Bitcoin Cash

### ISSUE THREAD

**Issue by zan56** [acceptbitcoincash/acceptbitcoincash#248]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ BitcoinPlug }} to the {{ Banking }} category. Details follow:

```yml

- name: BitcoinPlug
  url: https://bitcoinplug.com/bitcoin-cash/
  twitter: BitcoinPlug@bitcoinplugatm
  facebook: facebook_username
  img: https://bitcoinplug.com/wp-content/uploads/2017/02/bitcoinplug-resided-by-RA.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://bitcoinplug.com/bitcoin-cash/
```

Bitcoin Cash ATM Locations Opening in Los Angeles.
