### ISSUE TITLE
Add Bees Brothers to Food category

### ISSUE THREAD

**Issue by t0p0lin0** [acceptbitcoincash/acceptbitcoincash#251]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ Bees Brothers }} to the {{ Food }} category. Details follow:

```yml

- name: Bees Brothers
  url: http://beesbros.com
  facebook: beesbros
  email_address: beesbrothers@gmail.com
  img: http://www.beesbros.com/uploads/7/7/6/8/7768839/1990970.jpg
  bcc: yes
  btc: yes
  othercrypto: no
  exceptions:
    text: "Bitcoin Cash is a manual payment at this time. Contact Bees Brothers: beesbrothers@gmail.com"
```
