### ISSUE TITLE
adding Bovado.com to merchant list

### ISSUE THREAD

**Issue by bigonsports** [acceptbitcoincash/acceptbitcoincash#252]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Bovado.com to the Gambling category. Details follow:

```yml

- name: Bovado.com
  url: http://www.bovado.com
  twitter: https://twitter.com/BovadaLV
  facebook: https://www.facebook.com/BovadaLV/
  img: URL_to_image
  bcc: yes
  btc: yes
  othercrypto: no
  doc: https://www.bovada.lv/help/bitcoin
```

Add more information here if necessary
