### ISSUE TITLE
LegalB

### ISSUE THREAD

**Issue by LegalB** [acceptbitcoincash/acceptbitcoincash#253]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ http://www.legalb.co.za }} to the {{ category_name_here }} category. Details follow:

```yml

- name: LegalB
  url: http://www.legalb.co.za/index.htm
  twitter: felgate
  facebook: 
  img: 
  bcc: yes
  btc: yes
  othercrypto: no
  doc: http://www.legalb.co.za/General/Help.htm
```
LegalB - for the World's 1st Rule of Law Standard
