### ISSUE TITLE
Bountysource

### ISSUE THREAD

**Issue by intermaxim** [acceptbitcoincash/acceptbitcoincash#255]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ Bountysource }} to the {{ developer }} category. Details follow:

```yml

- name: Bountysource
  url: https://www.bountysource.com/
  twitter: bountysource
  facebook: Bountysource
  bcc: no
  btc: yes
  othercrypto: no
```

Add more information here if necessary
