### ISSUE TITLE
Add Gigampz.com to sites accepting Bitcoin Cash

### ISSUE THREAD

**Issue by pmorici** [acceptbitcoincash/acceptbitcoincash#256]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Gigampz to the Mining category. Details follow:

```yml

- name: Gigampz
  url: http://www.gigampz.com
  twitter: gigampz
  facebook: None
  img: http://www.gigampz.com/uploads/2/8/0/3/28036155/s824349048445313476_p19_i4_w640.jpeg
  bcc: yes
  btc: no
  othercrypto: no
  doc: None
```

Add more information here if necessary
