### ISSUE TITLE
Scan computers uk

### ISSUE THREAD

**Issue by pekatete** [acceptbitcoincash/acceptbitcoincash#257]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ https://www.scan.co.uk/ }} to the {{ Retail }} category. Details follow:

```yml

- name: Scan computers
  url: https://www.scan.co.uk/
  twitter: https://twitter.com/scancomputers
  facebook: https://www.facebook.com/scancomputers
  img: URL_to_image
  bcc: no
  btc: yes
  othercrypto: no
  doc: URL_to_site_with_bitcoin_cash_article_or_help_guide_etc
```
