### ISSUE TITLE
Application for https://CashVid.io

### ISSUE THREAD

**Issue by cashvid** [acceptbitcoincash/acceptbitcoincash#264]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ CashVid.io }} to the {{ Entertainment }} category. Details follow:

```yml

- name: CashVid.io
  url: https://CashVid.io
  twitter: CashVidio
  facebook: https://www.facebook.com/CashVid.io/
  img: https://www.cashvid.io/images/logomid.png
  bcc: yes
  btc: _no
  othercrypto: _no
  doc: https://www.cashvid.io/Faq.php
```

We payout in Bitcoin Cash but do not accept it for payments, as we do not accept payments in any form. In the future if we do accept payments for some purpose, we will accept Bitcoin Cash as well.
