### ISSUE TITLE
Add BackupBox to "Backup and Sync". Accept Bitcoin (Bitcoin cash soon)

### ISSUE THREAD

**Issue by Aminadav** [acceptbitcoincash/acceptbitcoincash#265]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ BackupBox }} to the {{ Backup and Sync }} category. Details follow:

```yml

- name: BackupBox
  url: https://www.backupbox.com
  img: https://www.backupbox.com/images/logo-turquoise-black.png
  bcc: yes
  btc: no
  othercrypto: no
```

By the way, what is the most recommended method to accept Bitcoin cash ?
