### ISSUE TITLE
Pixelmind

### ISSUE THREAD

**Issue by ph1x** [acceptbitcoincash/acceptbitcoincash#266]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ Pixelmind }} to the {{ Developer }} category. Details follow:

```yml

- name: Pixelmind
  url: https://www.pixelmind.org
  twitter: ph1x
  facebook: pixelmind.org
  img: https://pixelmind.org/assets/images/pixelmind-logo-200x200.png
  email: pixelmindstudio@gmail.com
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://pixelmind.org/contact-us
```

Add more information here if necessary
We are Web Development and Graphic Design (UX/UI, Logo Design, Brand Identity...) Agency based in Plovdiv, Bulgaria. We accept Bitcoin since 2012.
