### ISSUE TITLE
Request to add Njalla to the Domains category

### ISSUE THREAD

**Issue by curyous** [acceptbitcoincash/acceptbitcoincash#268]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Njalla to the Domains category. Details follow:

```yml

- name: Njalla
  url: https://njal.la
  twitter: njal_la
  facebook: facebook_username
  img: https://pbs.twimg.com/profile_images/854832827870978048/UFJj7v7v_400x400.jpg
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://twitter.com/njal_la/status/930417225013628928
```

Add more information here if necessary
