### ISSUE TITLE
Kationickratom

### ISSUE THREAD

**Issue by kratatomi** [acceptbitcoincash/acceptbitcoincash#269]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ site_name_here }} to the {{ category_name_here }} category. Details follow:

```yml

- name: Kationickratom
  url: http://www.kationickratom.com
  twitter:
  facebook: 
  img: http://www.google.com/s2/favicons?domain=www.kationickratom.com
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: http://kationickratom.com/lovingkratom/pago-bitcoin-altcoin/
```

BCH and alts accepted only manually. Alts include ETH, LTC and IOTA.
