### ISSUE TITLE
Snusbase.com

### ISSUE THREAD

**Issue by publicdbhost** [acceptbitcoincash/acceptbitcoincash#270]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Snusbase to the Security category. Details follow:

```yml

- name: Snusbase
  url: https://snusbase.com
  twitter: publicdbhost
  facebook: facebook_username
  img: https://snusbase.com/assets/SnusH2O_blue.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: /purchase ?
```

Add more information here if necessary
