### ISSUE TITLE
Please add BetOnline.ag to the gambling section of acceptbitcoin.cash/#gambling

### ISSUE THREAD

**Issue by BPaul1705** [acceptbitcoincash/acceptbitcoincash#277]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ betonline.ag }} to the {{ gambling}} category. Details follow:

```yml

- name: BetOnline.ag
  url: https://www.betonline.ag/
  twitter: BetOnline.ag
  facebook: BetOnlineag
  img: https://ui-promotions.sportsbetting.ag/sportsbetting_slogo.png 
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://promotions.betonline.ag/bitcoin101
```

Add more information here if necessary
