### ISSUE TITLE
Please add SportsBetting.ag to the gambling section

### ISSUE THREAD

**Issue by BPaul1705** [acceptbitcoincash/acceptbitcoincash#278]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ site_name_here }} to the {{ category_name_here }} category. Details follow:

```yml

- name: SportsBetting.ag
  url: https://www.sportsbetting.ag/
  twitter: SportsBettingAG
  facebook: SportsBettingAG
  img: https://ui-promotions.sportsbetting.ag/sportsbetting_slogo.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_article_or_help_guide_etc
```

Add more information here if necessary
