### ISSUE TITLE
Mullvad VPN

### ISSUE THREAD

**Issue by patrikr** [acceptbitcoincash/acceptbitcoincash#280]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add Mullvad VPN to the Security category. Details follow:

```yml

- name: Mullvad VPN
  url: https://mullvad.net/
  twitter: mullvadnet
  email_address: support@mullvad.net
  facebook: 
  img: 
  bcc: no
  btc: yes
  othercrypto: no
  doc: 
```

Add more information here if necessary
