### ISSUE TITLE
Washington Intern Housing Network (student housing provider)

### ISSUE THREAD

**Issue by jacobdc76** [acceptbitcoincash/acceptbitcoincash#281]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ site_name_here }} to the {{ category_name_here }} category. Details follow:

```yml

- name: Washington Intern Housing Network
  url: https://www.thewihn.com
  twitter: n/a
  facebook: n/a
  img: http://thewihn.com/wp-content/uploads/2011/07/minilogo.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_article_or_help_guide_etc
```

Add more information here if necessary
I am the owner of this fully furnished housing provider for interns and college students in Washington, D.C. I don't currently have any documentation set up just yet explaining how to use bitcoin cash to pay your housing fees but that is forthcoming.
