### ISSUE TITLE
Blanke Briefhüllen GmbH (envelopes)

### ISSUE THREAD

**Issue by chrisst81** [acceptbitcoincash/acceptbitcoincash#282]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ site_name_here }} to the {{ category_name_here }} category. Details follow:

```yml

- name: Blanke Briefhüllen GmbH
  url: https://www.brief-huellen.de 
  facebook: BlankeBriefhuellen
  img: https://www.brief-huellen.de/bilder/intern/shoplogo/jtlshoplogo.png
  bcc: yes
  btc: no
  othercrypto: no
  
```

Add more information here if necessary
