### ISSUE TITLE
Bacloud.com - all data center services, accept Bitcoin cash.

### ISSUE THREAD

**Issue by flshs** [acceptbitcoincash/acceptbitcoincash#283]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ site_name_here }} to the {{ category_name_here }} category. Details follow:

```yml

- name: All data center services: dedicated servers, vps, domain names, hosting, ssl certificates, collocation
  url: http://www.bacloud.com
  twitter: https://twitter.com/bacloud
  facebook: https://www.facebook.com/Bacloudcom/
  img: https://hostadvice.com/wp-content/uploads/2017/09/bacloud-624x148.png
  bcc: Yes
  btc: Yes
  othercrypto: Yes
  doc: https://www.bacloud.com/en/payment-methods
```

Bacloud offers all data center services and accept 50+ Crypto coin payments.
