### ISSUE TITLE
Please add MyBookie

### ISSUE THREAD

**Issue by bigonsports** [acceptbitcoincash/acceptbitcoincash#285]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add MyBookie.ag to the sports betting category. Details follow:

```yml

- name: MyBookie.ag
  url: http://record.webpartners.co/_wS-vFubHQx4WqcfzuvZcQGNd7ZgqdRLk/1/
  twitter: betmybookie
  facebook: betmybookie
  img: http://record.webpartners.co/_wS-vFubHQx4WqcfzuvZcQGNd7ZgqdRLk/1/
  bcc: yes
  btc: yes
  othercrypto: yes_or_no
  doc: https://mybookie.ag/info/banking/
```

Add more information here if necessary
