### ISSUE TITLE
101 Studios

### ISSUE THREAD

**Issue by lifestylehut** [acceptbitcoincash/acceptbitcoincash#286]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ 101 Studios }} to the {{ Other }} category. Details follow:

```yml

- name: 101 Studios
  url: www.101studios.com
  twitter: 
  facebook:
  img: 
  bcc: yes
  btc: yes
  othercrypto: yes (Litecoin)
  doc: 
```

An audio production facility based in Malaysia doing dubbing, sound effects, music and servicing the film industry.
