### ISSUE TITLE
add alza.co.uk

### ISSUE THREAD

**Issue by tulasacra** [acceptbitcoincash/acceptbitcoincash#289]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ alza }} to the {{ retail }} category. Details follow:

```yml

- name: alza
  url: https://www.alza.co.uk/
  twitter: https://twitter.com/Alzacz
  facebook: https://www.facebook.com/alzacouk/
  img: https://i.alza.cz/Foto/imggalery/LandingPages/Logomanual/images/alza_cz.png
  bcc: no
  btc: yes
  othercrypto: no
  doc: URL_to_site_with_bitcoin_cash_article_or_help_guide_etc
```

Add more information here if necessary
