### ISSUE TITLE
Select Woodcraft

### ISSUE THREAD

**Issue by Austin17jm** [acceptbitcoincash/acceptbitcoincash#290]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ Select Woodcraft }} to the {{ Retail }} category. Details follow:

```yml

- name: Select Woodcraft
  url: https://www.selectwoodcraft.com
  twitter: SelectWoodcraft
  facebook: SelectWoodcraft
  img: https://i.imgur.com/lfZgq55.jpg
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://www.bitcoincash.org/
```

When buying something from this shop select "other payment options" during checkout, then message the shop owner expressing your interest in paying with Bitcoin Cash!
