### ISSUE TITLE
Add GearBest

### ISSUE THREAD

**Issue by MalkavianBilbao** [acceptbitcoincash/acceptbitcoincash#292]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ GearBest }} to the {{ Retail }} category. Details follow:

```yml

- name: GearBest
  url: https://www.gearbest.com/
  twitter: TheGearbest
  facebook: gearbest
  img: https://review.gbtcdn.com/public/images/gearbest/avatar/201603/AB44FC0E6CA9F2C21C8C3DE3B2305165.png
  bcc: no
  btc: no
  othercrypto: no
  doc: http://usebitcoin.cash
```

Add more information here if necessary
