### ISSUE TITLE
Add geekvida

### ISSUE THREAD

**Issue by MalkavianBilbao** [acceptbitcoincash/acceptbitcoincash#293]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ geekvida }} to the {{ Retail }} category. Details follow:

```yml

- name: geekvida
  url: http://www.geekvida.es/
  twitter: Geekvidacom
  facebook: geekvida
  img: http://www.geekvida.es/skin/frontend/default/geekvida/images/logo.png
  bcc: no
  btc: no
  othercrypto: no
  doc: http://usebitcoin.cash
```

Add more information here if necessary
