### ISSUE TITLE
Add RocketResponder.com

### ISSUE THREAD

**Issue by rocketresponder** [acceptbitcoincash/acceptbitcoincash#294]
Requesting to add RocketResponder.com to the Communication category. Details follow:

```yml

- name: RocketResponder.com
  url: https://www.rocketresponder.com/
  img: https://www.rocketresponder.com/img/logo.icon.32.png
  bcc: yes
  btc: no
  othercrypto: no
  doc: https://www.rocketresponder.com/blog/now-accept-bitcoin-cash/
```

RocketResponder is an email marketing platform much like MailChimp, GetResponse, ConstantContact. I put it as "Communication" because that's where they are listed.
