### ISSUE TITLE
Add BitcoinSexToys

### ISSUE THREAD

**Issue by bitcoinsextoys** [acceptbitcoincash/acceptbitcoincash#295]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ BitcoinSexToys }} to the {{ Adult }} category. Details follow:

```yml

- name: BitcoinSexToys
  url: https://bitcoinsextoys.co.uk
  twitter: 
  facebook: 
  img: https://bitcoinsextoys.co.uk/images/bst-small-logo.png
  bcc: yes
  btc: yes
  othercrypto: no
  doc: 
```

Add more information here if necessary
Thanks :-)
