### ISSUE TITLE
Add pcomponentes.com

### ISSUE THREAD

**Issue by MalkavianBilbao** [acceptbitcoincash/acceptbitcoincash#296]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ site_name_here }} to the {{ category_name_here }} category. Details follow:

```yml

- name: site_name_here
  url: https://www.pccomponentes.com
  twitter: pccomponentes
  facebook: pccomponentes
  img: https://cdn.pccomponentes.com/img/corporativo/pccomponentes-logo.svg
  bcc: no
  btc: no
  othercrypto: no
  doc:
```
