### ISSUE TITLE
Add Kimichisocks.com to Retail

### ISSUE THREAD

**Issue by memalley** [acceptbitcoincash/acceptbitcoincash#299]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add {{ kimchisocks.com }} to the {{ Retail }} category. Details follow:

```yml

- name: Kimchisocks
  url: http: https://kimchisocks.com/
  twitter: kimchisocks
  facebook: kimchisocks
  img: https://kimchisocks.com/wp-content/uploads/2016/04/%5EAF64E25F2674781F64F7F465DC9C126320A354B5F82D280429%5Epimgpsh_fullsize_distr.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: 
```

Add more information here if necessary
This is a new feature for kimchisocks. He currently will accept BCH if you email him for an address. He has said he is working on adding BCH to his payment flow on the site.
