### ISSUE TITLE
Add Ultraseedbox to Hosting/VPS

### ISSUE THREAD

**Issue by nacardin** [acceptbitcoincash/acceptbitcoincash#301]
Requesting to add Ultraseedbox to the Hosting/VPS category. Details follow:

```yml

- name: Ultraseedbox
  url: https://www.ultraseedbox.com/
  twitter: ultraseedbox
  facebook: ultrasbox
  img: https://pbs.twimg.com/profile_images/378800000450584170/def23f12cb409ab4b9376ee7b0d9a561.png
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://kb.ultraseedbox.com/display/DOC/Payments
```

I've confirmed that BTC (BitPay) and BCH (CoinGate) integrations are working.
