### ISSUE TITLE
Request to StreamWorks to Retail category

### ISSUE THREAD

**Issue by techremedy** [acceptbitcoincash/acceptbitcoincash#307]
*Please fill in the template below, and don't worry about exact formatting, just do your best!

Requesting to add StreamWorks to the Retail category. Details follow:

```yml

- name: StreamWorks
  url: http://streamworks.com/shop
  twitter: 
  facebook: 
  img: http://streamworks.com/wp-content/uploads/2016/08/streamworks_logo350x350.jpg
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_article_or_help_guide_etc
```

Add more information here if necessary
