### ISSUE TITLE
Requesting to add named.trade to the Domains category.

### ISSUE THREAD

**Issue by krisives** [acceptbitcoincash/acceptbitcoincash#309]
Requesting to add ___named.trade___ to the ___Domains___ category. Details follow:

```yml

- name: site_name_here
  url: https://named.trade
  twitter: NamedTrade
  facebook:  
  img: https://named.trade/wp-content/uploads/2017/12/bitcoincash.jpg
  bcc: Yes
  btc: No
  othercrypto: Yes
  doc: https://www.reddit.com/r/btc/comments/7iman8/namecheap_accepts_legacy_coin_only_using_bitpay/
```
