### ISSUE TITLE
Add BchTips.org

### ISSUE THREAD

**Issue by andrewcottage** [acceptbitcoincash/acceptbitcoincash#310]
Requesting to add BchTips.org to the cryptoservices category. 

```yml

 - name: BchTips.org
    url: https://bchtips.org
    img: https://bchtips.org/images/bitcoincashtips.png
    bcc: yes
    btc: no
    othercrypto: no
    doc:
```

Add more information here if necessary.
