### ISSUE TITLE
Please Add 1stboards.com and 1stboards.world - Asia's Electric Skateboard Authority

### ISSUE THREAD

**Issue by inktech** [acceptbitcoincash/acceptbitcoincash#311]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add http://1stboards.com & http://1stboards.world to the Retail category. Details follow:

```yml

- name: 1stboards
  url: http://1stboards.com || http://1stboards.world
  twitter: twitter_username_no_@_symbol
  facebook: https://www.facebook.com/1stboardstaiwan/
  img: https://i0.wp.com/1stboards.com/wp-content/uploads/2016/03/-3-1small-e1476827757385.jpg?fit=450%2C253
  bcc: yes
  btc: no
  othercrypto: yes_or_no
  doc: http://1stboards.com/cart/
```

Add more information here if necessary.
