### ISSUE TITLE
Listing request on the acceptbitcoincash initiative website

### ISSUE THREAD

**Issue by KVNHNF** [acceptbitcoincash/acceptbitcoincash#312]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___Fine Love Dolls___ to the ___Retail___ category. Details follow:

```yml

- name: Fine Love Dolls ® Ultra Realistic TPE Sex Dolls
  url: https://www.finelovedolls.com
  twitter: finelovedolls
  facebook: FineLoveDollsWorldwide
  img: https://www.facebook.com/288983221545852/photos/290648374712670/
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.
