### ISSUE TITLE
Add cryptogeneralstore.net

### ISSUE THREAD

**Issue by warden-j50** [acceptbitcoincash/acceptbitcoincash#317]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___site_name_here___ to the ___category_name_here___ category. Details follow:

```yml

- name: site_name_here
  url: URL_to_site_here_https_preferred
  twitter: twitter_username_no_@_symbol
  facebook: facebook_username
  img: URL_to_image
  bcc: yes_or_no
  btc: yes_or_no
  othercrypto: yes_or_no
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.
