### ISSUE TITLE
Add cryptogeneralstore.net

### ISSUE THREAD

**Issue by warden-j50** [acceptbitcoincash/acceptbitcoincash#318]
Requesting to https://cryptogeneralstore.net to the retail category. Details follow:

```yml

- name: Crypto General Store
  url: https://cryptogeneralstore.net
  bcc: yes
  btc: yes
  othercrypto: yes
  doc:
```

Add more information here if necessary.
