### ISSUE TITLE
Add takeaway.com

### ISSUE THREAD

**Issue by acidsploit** [acceptbitcoincash/acceptbitcoincash#319]
Requesting to add takeaway.com to the FOOD category. Details follow:

```yml

- name: takeaway.com
  url: https://www.takeaway.com
  twitter: takeaway
  bcc: no
  btc: yes
  othercrypto: no

```

Add more information here if necessary.
