### ISSUE TITLE
4dollarsmartphone.com

### ISSUE THREAD

**Issue by phabulu** [acceptbitcoincash/acceptbitcoincash#320]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___4$smartphone.com___ to the ___Electronics___ category. Details follow:

```yml

- name: Freedom 251 the 4$ Smartphone
  url: http://4dollarsmartphone.com/
  twitter: 
  facebook: https://www.facebook.com/shop251now
  img: https://image.ibb.co/bvYPEb/img_freedom251.jpg
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: http://4dollarsmartphone.com/cart.html
```

Add more information here if necessary.
