### ISSUE TITLE
bitcoincash-doubler.co.nf

### ISSUE THREAD

**Issue by phabulu** [acceptbitcoincash/acceptbitcoincash#321]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___bitcoincash-doubler.co.nf___ to the ___category_gambling___ category. Details follow:

```yml

- name: bitcoin cashdoubler
  url: http://bitcoincash-doubler.co.nf/
  twitter: l
  facebook: 
  img: https://image.ibb.co/nxiAKb/btcusd.jpg
  bcc: yes
  btc: no
  othercrypto: no
  doc: http://bitcoincash-doubler.co.nf/
```

Add more information here if necessary.
