### ISSUE TITLE
new addition

### ISSUE THREAD

**Issue by eronstrom** [acceptbitcoincash/acceptbitcoincash#322]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add "Crypto Armory" to the retail category. Details follow:

```yml

- name: Crypto Armory
  url: https://www.crypto-armory.com/
  img: https://www.crypto-armory.com/wp-content/uploads/2017/12/logo.png
  bcc: yes
  btc: yes
  othercrypto: yes
```

I haven't made any social media profiles for Crypto Armory yet, I'll make another git issue if/when I do
