### ISSUE TITLE
Chip-Chap POS

### ISSUE THREAD

**Issue by LuisTarifa** [acceptbitcoincash/acceptbitcoincash#323]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___site_name_here___ to the ___category_name_here___ category. Details follow:

```yml

- name: Chip-Chap
  url: https://chip-chap.com
  facebook: chipchapapp
  bcc: yes
  btc: no
  othercrypto: yes
```

Add more information here if necessary.
