### ISSUE TITLE
new addition: BarFoxx

### ISSUE THREAD

**Issue by monsterbitar** [acceptbitcoincash/acceptbitcoincash#325]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add Barfoxx (barfoxx.com) to the food category. Details follow:

```yml

- name: Bar Foxx
  url: barfoxx.com
  twitter: n/a
  facebook: barfoxx?
  img: n/a
  bcc: no way, but BCH is a strong YES.
  btc: no, absolutely no.
  othercrypto: nope
  doc: https://twitter.com/monsterbitar/status/940925040383746048
```

Add more information here if necessary.
