### ISSUE TITLE
Adding my website

### ISSUE THREAD

**Issue by mirzaian92** [acceptbitcoincash/acceptbitcoincash#326]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___site_name_here___ to the ___category_name_here___ category. Details follow:

```yml

- name: King Pen Vapes
  url: https://kingpenvapes.com/
  twitter: KingPenVapes
  facebook: kingpenv
  img: https://kingpenvapes.com/wp-content/themes/kpv/images/logo.png
  bcc: yes
  btc: yes
  othercrypto: yes (VTC and LTC)
  doc: https://www.reddit.com/r/btc/comments/7jq1hc/we_just_added_bitcoin_cash_as_a_payment_method_on/
```

Add more information here if necessary.
