### ISSUE TITLE
New addition

### ISSUE THREAD

**Issue by monsterbitar** [acceptbitcoincash/acceptbitcoincash#328]
Requesting to add Christers Hårvård to the Fashion? (or maybe Social? they're a Hair salon) category. Details follow:

```yml

- name: Christers Hårvård
  url: http://www.christersharvard.se/
  twitter: n/a
  facebook: christersharvard
  img: URL_to_image
  bcc: BCC? no, but BCH yes please.
  btc: yes
  othercrypto: no
  doc: http://www.christersharvard.se/priser/
```

Add more information here if necessary.
