### ISSUE TITLE
Shiny Leaf Beauty

### ISSUE THREAD

**Issue by shinyleaf** [acceptbitcoincash/acceptbitcoincash#329]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___Shiny Leaf___ to the ___retail___ category. Details follow:

```yml

- name:  Shiny Leaf
  url: https://www.shinyleaf.com
  twitter: ShinyLeafUSA
  facebook: shinyleafusa
  img: https://www.shinyleaf.com/wp-content/uploads/2016/10/logo-d.png
  bcc: yes
  btc: no
  othercrypto: no
  doc: https://www.shinyleaf.com/promotions/bitcoin-cash-payment/
```

Shiny Leaf is a leading natural beauty products company. Our products are natural and organic and our moto is: "Look Good, Love Yourself" which basically says it all. Enjoy our variety of natural oils, shampoo and conditioner sets and other products. Now accepting Bitcoin Cash!
