### ISSUE TITLE
Add Cryptonize.it

### ISSUE THREAD

**Issue by Cryptonize** [acceptbitcoincash/acceptbitcoincash#334]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___Cryptonize.it___ to the ___Retail___ category. Details follow:

```yml

- name: Cryptonize.ot
  url: https://www.cryptonize.it
  twitter: cryptonize_it
  facebook: no_facebook
  img: https://www.cryptonize.it/wp-content/uploads/2017/12/cryptonizelogo.png
  bcc: yes
  btc: no
  othercrypto: no
  doc: https://www.reddit.com/r/btc/comments/7jmcyz/pay_for_anything_online_with_bch_cryptonizeit/?st=jbam6prm&sh=8d206d5e
```

I noticed you named the bitcoin cash ticker BCC, most people call it BCH.
