### ISSUE TITLE
[new addition] Add pastecoin.com

### ISSUE THREAD

**Issue by bcashier** [acceptbitcoincash/acceptbitcoincash#342]
Requesting to add https://www.pastecoin.com to the Crypto Services category. Details follow:

```yml

- name: Pastecoin
  url: https://www.pastecoin.com
  twitter: Pastecoin
  facebook: X
  img: http://www.pastecoin.com/images/fb.png
  bch: YES
  btc: YES
  othercrypto: NO
  doc: https://twitter.com/PasteCoin/status/943562876513673216
```

They just started to accept BITCOIN CASH.
