### ISSUE TITLE
Add The Dog is Hot to Food category

### ISSUE THREAD

**Issue by conaman551** [acceptbitcoincash/acceptbitcoincash#346]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add "the dog is hot" (hot dog restaurant in Barcelona) to the food category. Details follow:

```yml

- name: The dog is hot, Barcelona
  url: http://thedogishot.com/
  twitter: twitter_username_no_@_symbol
  facebook: @thedogishot
  img: URL_to_image
  bch: yes
  btc: yes
  othercrypto: no
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```
