### ISSUE TITLE
Add ABACO Hosting to Hosting/VPS category

### ISSUE THREAD

**Issue by abacohosting** [acceptbitcoincash/acceptbitcoincash#352]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___ABACO Hosting___ to the ___Hosting/VPS___ category. Details follow:

```yml

- name: ABACO Hosting
  url: https://abacohosting.com/
  twitter: abacohosting
  facebook: abacohosting
  img: https://abacohosting.com/images/logo.png
  bch: YES
  btc: YES
  othercrypto: YES, Ethereum, Litecoin, Digibyte, Monero, Dash
  doc: https://abacohosting.com/we-are-now-accepting-bitcoincash-for-all-domain-registrations-hosting.html


```
ABACO Hosting is an Internet services company since 2007, we have solutions for small and medium businesses, from Email Hosting, GeoLocated Hosting Linux & Windows, Reseller, VPS, Cloud, Wordpress Hosting, SSL, Security, Servers and a portfolio of +500 domain extensions available.
