### ISSUE TITLE
Reservoir Mugs

### ISSUE THREAD

**Issue by alvinjoelsantos** [acceptbitcoincash/acceptbitcoincash#355]
Requesting to add Reservoir Mugs to the Retail category. Details follow:

```yml

- name: Reservoir Mugs
  url: https://reservoirmugs.com
  twitter: reservoirmugs
  img: https://cdn.shopify.com/s/files/1/2662/0872/files/m_320x320.png?v=1514141233
  bch: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.
