### ISSUE TITLE
Add Puroxy.org to list of sites that accept BCH

### ISSUE THREAD

**Issue by ex8** [acceptbitcoincash/acceptbitcoincash#356]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add Puroxy to the list of sites that accept BCH category. Details follow:

```yml

- name: Puroxy
  url: https://puroxy.org
  bch: yes
  btc: yes
  othercrypto: yes
```

Add more information here if necessary.
