### ISSUE TITLE
 Requesting to add 'Shiny Leaf' to the Retail category

### ISSUE THREAD

**Issue by jake---** [acceptbitcoincash/acceptbitcoincash#357]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___site_name_here___ to the ___category_name_here___ category. Details follow:

```yml

- name: Shiny Leaf
  url: https://www.shinyleaf.com/
  twitter: ShinyLeafUSA
  facebook: shinyleafusa
  img: https://www.shinyleaf.com/wp-content/uploads/2016/10/logo-d.png
  bch: yes
  btc: no
  othercrypto: no
  doc: https://www.shinyleaf.com/promotions/bitcoin-cash-payment/
```

Add more information here if necessary.
