### ISSUE TITLE
CRYPTOMATIC watches

### ISSUE THREAD

**Issue by ozopled** [acceptbitcoincash/acceptbitcoincash#358]
* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to cryptomatic.io to the jewelry/accessories/watches category. Details follow:

```yml

- name: CRYPTOMATIC
  url: https://cryptomatic.io
  twitter: cryptomatic_io
  facebook: cryptomatic
  img: https://cryptomatic.io/img/square2/cryptomatic_hodler_silver_metal.jpg
  bch: yes
  btc: yes
  othercrypto: yes
  doc: being updated
```

Add more information here if necessary.
