### ISSUE TITLE
Addition: privateinternetaccess

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#359]
Got this request from a user on Reddit.

A: The VPN company "PIA (Private Internet Access)" should be updated under the "Security" listings as a Bitcoin Cash accepting merchant, since they now accept it.

* Submission Notes *
- Please fill in the template below, and don't worry about exact formatting, just do your best!
- Before submitting, please assign an appropriate label (most likely "new addition").
---------------

Requesting to add ___site_name_here___ to the ___category_name_here___ category. Details follow:

```yml

- name: Private Internet Access
  url: https://www.privateinternetaccess.com/
  twitter:buyvpnservice
  facebook: privateinternetaccess
  img: URL_to_image
  bch: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.
