### ISSUE TITLE
Add Sugandya's Art to Retail

### ISSUE THREAD

**Issue by sinecadia** [acceptbitcoincash/acceptbitcoincash#362]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add **Sugandya's Art** to the **Retail** category. Details follow:

```yml

- name: Sugandya's Art
  region: na
  country: us
  city: Charlotte
  url: https://sugandya.com
  twitter: sugandyaart
  facebook: sugandyasart
  img: https://sugandya.com/wp-content/uploads/2017/10/lucihead.jpg
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://sugandya.com/store/crypto-accepted/
```

Add more information here if necessary.

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
