### ISSUE TITLE
sigavpn.com

### ISSUE THREAD

**Issue by sigavpn** [acceptbitcoincash/acceptbitcoincash#363]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add https://sigavpn.com to the security category. Details follow:

```yml

- name: SigaVPN
  region: na
  country: us
  url: https://sigavpn.com
  twitter: we don't use twitter
  facebook: we don't use facebook
  img: https://anonimage.net/db/full/eamN57jV09.png
  bch: yes
  btc: yes
  othercrypto: yes
  doc: none
```

We accept BCH donations, not sell stuff. (we're free)

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
