### ISSUE TITLE
Add Privcoin.io mixer

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#365]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Privcoin.io**}} to the {{**Crypto Services**}} category. Details follow:

```yml

- name: Privcoin.io
  url: https://www.privcoin.io/
  img: https://www.privcoin.io/favicon.ico
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://www.privcoin.io/bitcoincash/
```
