### ISSUE TITLE
Business Appraisal Firm 

### ISSUE THREAD

**Issue by rlandreth76** [acceptbitcoincash/acceptbitcoincash#366]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**site_name_here**}} to the {{**category_name_here**}} category. Details follow:

```yml

- name: medical valuations
  region: na
  country: US
  city: Scottsdale
  url: https://medicalvaluations.com
  twitter: medicalval
  facebook: MVincRoss
  img: 
  bch: yes
  btc: yes
  othercrypto: 
  doc: 
```

Add more information here if necessary.

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
