### ISSUE TITLE
Add Congrevape.com

### ISSUE THREAD

**Issue by johngrefe** [acceptbitcoincash/acceptbitcoincash#367]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{https://congrevape.com/shop}} to the {{**retail**}} category. Details follow:

```yml

- name: Congrevape
  region: na
  country: US
  city: Stockon
  url: https://congrevape.com/shop
  twitter: Congrevape
  facebook: Congrevape
  img: https://congrevape.com/wp-content/uploads/2017/10/Cv2017.png
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://congrevape.com/what-is-cryptocurrency-and-why-do-we-accept-it/
```

Congrevape is the Designer, Manufacture and Distributor of the Doge RDA, Catemizer RDA, Ignition RDA and DogeTank

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
