### ISSUE TITLE
Add Eruce.com

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#368]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**www.eruce.com**}} to the {{**Entertainment**}} category. Details follow:

```yml

- name: Eruce - Buy your music
  url: https://www.eruce.com/
  img: https://www.eruce.com/wp-content/uploads/2017/08/eruce-logo.png
  bch: yes
  btc: no
  othercrypto: no
  doc: https://www.eruce.com/bitcoin-cash-supported/
```
