### ISSUE TITLE
Add Eruce.com

### ISSUE THREAD

**Issue by anbinh** [acceptbitcoincash/acceptbitcoincash#369]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{ERUCE.COM}} to the {{Entertainment}} category. Details follow:

```yml

- name: eruce
  region: eu
  country: dk
  city: COPENHAGEN
  url: https://www.eruce.com
  twitter: eruceinc
  facebook: N/A
  img: https://www.eruce.com/wp-content/uploads/2017/08/eruce-logo.png
  bch: YES
  btc: NO
  othercrypto: YES
  doc: https://www.eruce.com/bitcoin-cash-supported/
```

Add more information here if necessary.

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
