### ISSUE TITLE
Add Wittson Custom Ti Cycles

### ISSUE THREAD

**Issue by rolic1** [acceptbitcoincash/acceptbitcoincash#370]
---------------
Requesting to add {{**Wittson_Custom_Ti_Cycles**}} to the {{**Retail**}} category. Details follow:

```yml

- name: Wittson_Custom_Ti_Cycles
  region: eu
  country: lt
  city: Klaipeda
  url: https://wittson.com/
  twitter: wittsoncycles
  facebook: wittson
  img: https://wittson.com/uploads/images/logo.png
  bch: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```
