### ISSUE TITLE
laptoppowerbank.com

### ISSUE THREAD

**Issue by MobiSolar** [acceptbitcoincash/acceptbitcoincash#371]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**laptoppowerbank.com**}} to the {{**category_name_here**}} category. Details follow:

```yml

- name: laptoppowerbank.com
  region: eu
  country: NL
  city: AMSTERDAM
  url: https://laptoppowerbank.com/
  twitter: mobisunenergy
  facebook: mobisunenergy
  img: https://laptoppowerbank.com/image/cache/catalog/OCS/Logo-RGB-Voor-een-donker-achtergrond-72-360x100-360x100.png
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://www.coinpayments.net/supported-coins
```

Add more information here if necessary.

We are offering the best available laptop power bank
We are shipping worldwide
Payment is possible with 50+ crypto currencies

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
