### ISSUE TITLE
Add Spotify to the list!

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#372]
Requesting to add {{**site_name_here**}} to the {{**category_name_here**}} category. Details follow:

```yml

- name:  Spotify
  url: https://www.spotify.com/
  img: URL_to_image
  twitter: spotify
  facebook: spotify
  bch: no
  btc: no
  othercrypto: no
  doc: 
```
