### ISSUE TITLE
Add Eruce

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#373]
https://www.eruce.com/bitcoin-cash-supported/

**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**site_name_here**}} to the {{**category_name_here**}} category. Details follow:

```yml

- name: Eruce
  region: see_region_code_table_below
  country: see_wikipedia_link_below
  city: capitalize_city_name
  url: https://www.eruce.com/
  twitter: twitter_username_no_@_symbol
  facebook: facebook_username
  img: URL_to_image
  bch: yes
  btc: yes_or_no
  othercrypto: yes_or_no
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
