### ISSUE TITLE
Add Nexwave as merchant

### ISSUE THREAD

**Issue by nexwave-mat** [acceptbitcoincash/acceptbitcoincash#375]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add Nexwave to the hosting category. Details follow:

```yml

- name: Nexwave
  region: na
  country: ca
  city: Montreal
  url: https://www.nexwave.ca/
  twitter: Nexwave
  facebook: nexwave.ca
  img: https://portal.nexwave.ca/assets/img/logo.png
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://twitter.com/Nexwave/status/948650799281917957
```

Add more information here if necessary.

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
