### ISSUE TITLE
Please add ttrss.info

### ISSUE THREAD

**Issue by markwaters** [acceptbitcoincash/acceptbitcoincash#377]
Requesting to add ttrss.info to the other category. Details follow:

```yml

- name: ttrss.info
  region: eu
  country: fr
  city: 
  url: https://ttrss.info/
  twitter: ttrss_info
  facebook: 
  img: https://ttrss.info/ttrss.info.logo.png
  bch: yes
  btc: yes
  othercrypto: no
  doc: https://ttrss.info/help.html
```

ttrss.info is a private instance of the TinyTinyRSS ( https://tt-rss.org/ ) web application.
We love Open Source.
We value Privacy.
Server hosted in the EU via OVH.
50% of profits are passed upstream to support TinyTinyRSS development.
