### ISSUE TITLE
CryptoGraffiti.info now has icon

### ISSUE THREAD

**Issue by 1Hyena** [acceptbitcoincash/acceptbitcoincash#383]
Requesting a fix to {{**CryptoGraffiti.info**}} in the {{**Crypto Services**}} category. Details follow:

```yml

- name: cryptograffiti.info
  region: eu
  country: EE
  city: Tallinn
  url: https://cryptograffiti.info
  twitter: 
  facebook: 
  img: https://github.com/1Hyena/cryptograffiti/blob/master/gfx/favicon.gif
  bch: yes
  btc: no
  othercrypto: no
  doc: http://www.newsbtc.com/2017/10/16/cryptograffiti-rejects-bitcoin-core-bch-now-available-payment-method/
```

add the missing logo image for the service
