### ISSUE TITLE
new site (BCH) Unity Automotive

### ISSUE THREAD

**Issue by CreativeName4** [acceptbitcoincash/acceptbitcoincash#386]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add Unity Automotive to the Transport category. Details follow:

```yml

- name: Unity Automotive
  region: NA
  country: CA
  city: Toronto
  url: http://unityauto.com
  twitter: UnityAuto 
  facebook: https://www.facebook.com/unityauto/
  img: http://www.unityauto.com/img/header/logo.png
  bch: yes
  btc: yes
  othercrypto: yes
  doc: http://unityauto.com/bitcoin.php 
```

Add more information here if necessary.

For 2-letter _country_ codes, use:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America
