### ISSUE TITLE
U.S. Electric and Control

### ISSUE THREAD

**Issue by wjacobsen** [acceptbitcoincash/acceptbitcoincash#389]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{U.S. Electric and Control}} to the {{Other}} category. Details follow:

```yml

- name: site_name_here
  url: https://us-elec.com/
  img: https://us-elec.com/wp-content/uploads/2017/11/US-Electric-e1510546560265-1.png
  twitter: 
  facebook: 
  region: na
  country: US
  city: Durham
  bch: no
  btc: yes
  othercrypto: no
  doc: https://us-elec.com/bitcoin/
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
