### ISSUE TITLE
Ukiah Brewing Company in California

### ISSUE THREAD

**Issue by odie808** [acceptbitcoincash/acceptbitcoincash#392]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{Ukiah Brewing Company}} to the {{food}} category. Details follow:

```yml

- name: Ukiah Brewing Company
  url: http://ukiahbrewing.com
  img: http://ukiahbrewing.com/wp-content/uploads/2017/05/UBCLogo-1.png
  twitter: twitter_username_no_@_symbol
  facebook: ukiahbrewing
  region: na
  country: us
  city: Ukiah
  bch: yes
  btc: yes
  othercrypto: yes
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
