### ISSUE TITLE
Praxis

### ISSUE THREAD

**Issue by cagrimmett** [acceptbitcoincash/acceptbitcoincash#393]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Praxis**}} to the {{**Education**}} category. Details follow:

```yml

- name: Praxis
  url: https://discoverpraxis.com
  img: http://portal.discoverpraxis.com/wp-content/uploads/2017/02/Screen-Shot-2016-07-03-at-12.54.39-PM.png
  twitter: discoverpraxis
  facebook: discoverpraxis
  region: na
  country: US
  city: Charleston
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://discoverpraxis.com/announcing-bitcoin-cash/
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
