### ISSUE TITLE
Greenleaf Nutrients

### ISSUE THREAD

**Issue by zanza321** [acceptbitcoincash/acceptbitcoincash#394]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Greenleaf Nutrients**}} to the {{**Other**}} category. Details follow:

```yml

- name: Greenleaf Nutrients
  url: https://greenleafnutrients.com
  img: https://greenleafnutrients.com/wp-content/uploads/2017/03/cropped-g11135.png
  twitter: greenleafnutes
  facebook: https://www.facebook.com/GreenleafNutrients/
  region: NA
  country: USA
  city: ships international
  bch: yes
  btc: no
  othercrypto: no
```

High quality Hydroponic and Soil plant nutrients.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
