### ISSUE TITLE
Add SwCPoker and Nitrogen Sports to the Gambling category

### ISSUE THREAD

**Issue by t0p0lin0** [acceptbitcoincash/acceptbitcoincash#395]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**SwCPoker** and **Nitrogen Sports**}} to the {{**Gambling**}} category. Details follow:

```yml

- name: SwCPoker
  url: https://swcpoker.eu/
  img: https://pbs.twimg.com/profile_images/568844073281134592/BxnRIc7m_400x400.png
  twitter: SwCPoker
  region: eu
  bch: no
  btc: yes
  othercrypto: no
  doc: https://swcpoker.eu/swcpoker-faq/#WhatIsBitcoin

- name: Nitrogen Sports
  url: https://nitrogensports.eu/
  img: https://pbs.twimg.com/profile_images/948741297648541696/eF_JCAPA_400x400.jpg
  twitter: NitrogenSports
  facebook: nitrogensports
  region: eu
  bch: no
  btc: yes
  othercrypto: no
```

Via https://www.reddit.com/r/btc/comments/7pl6as/are_there_any_texas_holdem_poker_or_blackjack/dsi3w40/
