### ISSUE TITLE
Consider adding latitude/longitude to YAML

### ISSUE THREAD

**Issue by t0p0lin0** [acceptbitcoincash/acceptbitcoincash#396]
In order to provide better data, consider starting to collect the latitude and longitude of merchant submissions (if brick and mortar). This can then be used in a multitude of beneficial ways, including being exposed via a simple API for other sites/apps to leverage the AB.C data from.

```
latitude: gps_coords
longitude: gps_coords
```

**Comment by kenman345** [comment]
nice thought I just dont know how practical it is since many places would have multiple latitude and longitudes

**Comment by t0p0lin0** [comment]
This would only be in the case of a brick and mortar, single location. The fields would not be mandatory either.

**Comment by kenman345** [comment]
I think we need a proof of concept on the utility of this information that separates us from others on this. I know localbitcoincash keeps this type of data but not sure how we'd adapt the site to consume it, and if it makes sense to track it differently than the rest of the data for the method we consume it (like a lat and longitude yml file that a map service consumes

**Comment by zander** [comment]
Personally, I'd say that if a 'store' has exact coordinates, then it belongs on openstreetmap.org, first and foremost.

That doesn't mean this site can't get 2nd hand data from OSM and publish it here, just that the original place should somehow be OSM.

**Comment by kenman345** [comment]
If we did this, I think we should implement like our websites are listed, or as a better example, look at this example: https://en.wikipedia.org/wiki/YAML#example where they show a receipt. Note that its got its normal tags and then the "items" tag where they define multiple items with its own set of tags.  Currently we do something like that but we separate out the parts of it to separate files. 

```yml
---
receipt:     Oz-Ware Purchase Invoice
date:        2012-08-06
customer:
    first_name:   Dorothy
    family_name:  Gale

items:
    - part_no:   A4786
      descrip:   Water Bucket (Filled)
      price:     1.47
      quantity:  4

```

I am just concerned too many locations would need to be added and where do we draw the line?
