### ISSUE TITLE
Dienmelinh

### ISSUE THREAD

**Issue by dienmelinh** [acceptbitcoincash/acceptbitcoincash#401]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**site_name_here**}} to the {{**category_name_here**}} category. Details follow:

```yml

- name: site_name_here
  url: URL_to_site_here_https_preferred
  img: URL_to_image
  twitter: twitter_username_no_@_symbol
  facebook: facebook_username
  region: see_region_code_table_below
  country: see_wikipedia_link_below
  city: capitalize_city_name
  bch: yes_or_no
  btc: yes_or_no
  othercrypto: yes_or_no
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
