### ISSUE TITLE
Bitcoin Cash Stickers

### ISSUE THREAD

**Issue by bitcoincashstickers** [acceptbitcoincash/acceptbitcoincash#404]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Bitcoin Cash Stickers**}} to the {{**Retail**}} category. Details follow:

```yml

- name: Bitcoin Cash Stickers
  url: http://bitcoincashstickers.com/
  img: http://bitcoincashstickers.com/img/bch-stickers.png
  twitter: bchstickers
  facebook: facebook_username
  region: na
  country: ISO 3166-2:US
  city: San Francisco
  bch: yes
  btc: no
  othercrypto: no
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

A marketplace for high quality Bitcoin Cash logo stickers.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
