### ISSUE TITLE
Elven Tower - RPG map illustrations

### ISSUE THREAD

**Issue by derekvonzarovich** [acceptbitcoincash/acceptbitcoincash#405]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Elven Tower RPG Cartography**}} to the {{**Art**}} category. Details follow:

```yml

- name: site_name_here
  url: http://www.elventower.com/
  img: https://www.elventower.com/wp-content/uploads/2017/02/cropped-Elven-Tower-Cartography-Logo.png
  twitter: elventower
  facebook: Elven Tower
  region: na
  country: MX
  city: Le
  bch: yes
  btc: no
  othercrypto: yes
  doc: https://www.elventower.com/commission-custom-maps
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
