### ISSUE TITLE
Adding CryptoMercado

### ISSUE THREAD

**Issue by eronstrom** [acceptbitcoincash/acceptbitcoincash#407]
---------------
Requesting to add CryptoMercady to the food category. Details follow:

```yml

- name: Crypto Mercado
  url: https://www.cryptomercado.com/
  img: https://scontent.ftpa1-2.fna.fbcdn.net/v/t1.0-9/12316648_200876800251116_1183965849246666295_n.png?oh=26fb38f54bdfc1c02a659722cc3abc81&oe=5AEC779E
  twitter: cryptomercado1
  facebook: cryptomercadodotcom
  region: na
  country: US
  city: capitalize_city_name
  bch: yes
  btc: yes
  othercrypto: yes
  doc: none, I bought on their store with BCH myself several times
```

If you explore their website, they say nothing about accepting BCH, but they say they accept many other cryptos.  If you actually add items to your cart and check out with coinpayments, BCH is an options.  I've bought from them a few times now.
