### ISSUE TITLE
Artisanhoney

### ISSUE THREAD

**Issue by Ameyumi** [acceptbitcoincash/acceptbitcoincash#411]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**site_name_here**}} to the {{**category_name_here**}} category. Details follow:

```yml

- name:Artisanhoney
  url: Artisanhoney.net
  img: https://artisanhoney.net/wp-content/uploads/2016/12/blossom_200g_%E9%80%8F%E9%81%8E-555x555.png
  twitter: rain_vc
  facebook: none
  region: as
  country: jp
  city: tokyo
  bch: yes
  btc: no
  othercrypto: no
  doc: none
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
