### ISSUE TITLE
Add 'topotest' to the 'testcat' category

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#412]
Requesting to add 'topotest' to the 'testcat' category. 

Details follow: 
```yml 
- name: topotest
  url: https://acceptbitcoin.cash
  img: 
  twitter: 
  facebook: 
  email_address: 
  region: 
  country: 
  city: 
  bch: Yes
  btc: No
  othercrypto: No
  doc: 
  exceptions: 
    text: ""
```
