### ISSUE TITLE
Add 'test 2' to the 'test category' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#415]
Requesting to add 'test 2' to the 'test category' category. 

Details follow: 
```yml 
- name: test 2
  url: http://test.com
  img: 
  twitter: 
  facebook: 
  email_address: 
  region: 
  country: 
  city: 
  bch: Yes
  btc: No
  othercrypto: No
  doc: 
  exceptions: 
    text: ""
```
