### ISSUE TITLE
Add 'Test Site' to the 'With LAbel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#416]
Requesting to add 'Test Site' to the 'With LAbel' category. 

Details follow: 
```yml 
- name: Test Site
  url: https://test.com
  img: 
  twitter: 
  facebook: 
  email_address: 
  region: 
  country: 
  city: 
  bch: Yes
  btc: No
  othercrypto: No
  doc: 
  exceptions: 
    text: ""
```
