### ISSUE TITLE
Adding Bittiraha.fi

### ISSUE THREAD

**Issue by teemujvi** [acceptbitcoincash/acceptbitcoincash#418]
---------------
Requesting to add Bittiraha.fi to the Crypto Exchanges category. Details follow:

```yml

- name: Bittiraha.fi
  url: https://bittiraha.fi
  img: 
  twitter: 
  facebook: bittiraha
  region: eu
  country: FI
  city: Helsinki
  bch: no
  btc: yes
  othercrypto: no
  doc: https://bittiraha.fi/nain-ryhdyt-bitcoin-kayttajaksi
```
Finnish Bitcoin market. Note that the site is in Finnish only.

Sister sites also owned by Prasos: 
https://coinmotion.com/ 
https://pikaosto.fi/ 
https://pikamyynti.fi/ 
https://bittimaatti.fi/
