### ISSUE TITLE
Add 'Wishosting' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#420]
Requesting to add 'Wishosting' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: Wishosting
      url: https://www.wishosting.com/
      img: https://www.wishosting.com/logo.png
      twitter: https://twitter.com/wishosting
      facebook: 
      email_address: 
      region: 
      country: 
      city: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: none that I know, I emailed months ago and asked. It was available at checkout few days ago :D (I host a BCH node there)
      exceptions: 
        text: ""
```
