### ISSUE TITLE
Add 'Test site' to the 'testing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#422]
Requesting to add 'Test site' to the 'testing' category. 

Details follow: 
```yml 
- name: Test site
      url: https://acceptbitcoin.cash
      img: 
      twitter: 
      facebook: 
      email_address: 
      region: 
      country: 
      city: 
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: 
      exceptions: 
        text: ""
```
