### ISSUE TITLE
Add 'Incognito Deals' to the 'Crypto-Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#426]
Requesting to add 'Incognito Deals' to the 'Crypto-Services' category. 

Details follow: 
```yml 
- name: Incognito Deals
      url: https://www.incognitodeals.com/index.html
      img: https://www.incognitodeals.com/silver.png
      twitter: IncognitoDeals
      facebook: 
      email_address: 
      region: 
      country: 
      city: 
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: 
      exceptions: 
        text: ""
```
