### ISSUE TITLE
Add 'mBit Casino' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#427]
Requesting to add 'mBit Casino' to the 'Gambling' category. 

Details follow: 
```yml 
- name: mBit Casino
      url: https://www.mbitcasino.com/
      img: https://dm9ybo02ktd7t.cloudfront.net/6e08fe077737e667ba9521b289533fde.svg
      twitter: mbitcasino
      facebook: mbitcasino
      email_address: 
      region: 
      country: 
      city: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: 
      exceptions: 
        text: ""
```
