### ISSUE TITLE
Add 'Cherry Jackpot' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#428]
Requesting to add 'Cherry Jackpot' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Cherry Jackpot
      url: https://cherryjackpot.com
      img: https://cherryjackpot.com/favicon.png
      twitter: 
      facebook: cherryjackpot
      email_address: 
      region: 
      country: 
      city: 
      bch: No
      btc: Yes
      othercrypto: No
      doc: 
      exceptions: 
        text: ""
```
