### ISSUE TITLE
Add 'Gyft' to the 'Crypto services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#429]
Requesting to add 'Gyft' to the 'Crypto services' category. 

Details follow: 
```yml 
- name: Gyft
      url: Https://gyft.com
      img: 
      twitter: Gyft
      facebook: 
      email_address: 
      region: 
      country: 
      city: 
      bch: No
      btc: Yes
      othercrypto: No
      doc: 
      exceptions: 
        text: ""
```
