### ISSUE TITLE
Add 'Petstarsell' to the 'Bags Cats Dogs Fashion Production' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#430]
Requesting to add 'Petstarsell' to the 'Bags Cats Dogs Fashion Production' category. 

Details follow: 
```yml 
- name: Petstarsell
      url: www.petstarsell.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
