### ISSUE TITLE
Add 'Villa Vvedene' to the 'Accommodation' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#431]
Requesting to add 'Villa Vvedene' to the 'Accommodation' category. 

Details follow: 
```yml 
- name: Villa Vvedene
      url: maxkite.wix.com/vvedene
      img: 
      email_address: max_kite@mail.ru
      region: eu
      country: RU
      city: Yaroslavl
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
