### ISSUE TITLE
Add 'QHoster' to the 'Hosting/VPA' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#432]
Requesting to add 'QHoster' to the 'Hosting/VPA' category. 

Details follow: 
```yml 
- name: QHoster
      url: https://qhoster.com
      img: https://acceptbitcoin.cash/img/hosting/qhoster.png
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.qhoster.com/payment-methods.html
```
