### ISSUE TITLE
Add 'Snel' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#433]
Requesting to add 'Snel' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: Snel
      url: https://snel.com
      img: https://keycdn.snel.com/wp-content/themes/snel/assets/images/logo-mini.png
      twitter: snelcom
      facebook: snelcom
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.snel.com/payment-methods/
```
