### ISSUE TITLE
Add 'FlokiNET' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#434]
Requesting to add 'FlokiNET' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: FlokiNET
      url: https://flokinet.is
      img: https://flokinet.is/img/logo.png
      email_address: info@flokinet.is
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://flokinet.is/en/index.php
```
