### ISSUE TITLE
Add 'VPS City' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#435]
Requesting to add 'VPS City' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: VPS City
      url: https://vps-city.com
      img: https://www.vps-city.com/images/logo.png
      twitter: vps_city
      email_address: office@vps-city.com
      country: SE
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://vps-city.com/
```
