### ISSUE TITLE
Add 'BitStickers' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#436]
Requesting to add 'BitStickers' to the 'Retail' category. 

Details follow: 
```yml 
- name: BitStickers
      url: https://bitstickers.net
      img: https://bitstickers.net/wp-content/uploads/2014/07/xfavicon-80x80.png.pagespeed.ic.Ekh_-UcTaK.png
      twitter: Bitstickersnet
      facebook: bitstickersnet
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://bitstickers.net/bitcoin-cash-accepted-here/
```
