### ISSUE TITLE
Add 'Crypto Jeweler' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#437]
Requesting to add 'Crypto Jeweler' to the 'Retail' category. 

Details follow: 
```yml 
- name: Crypto Jeweler
      url: https://cryptojeweler.com
      img: https://www.cryptojeweler.com/image/catalog/logos/logo-header-dark.png
      twitter: cryptojeweler
      facebook: CryptoJeweler
      email_address: sales@cryptojeweler.com
      region: na
      country: CA
      city: Oshawa
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.cryptojeweler.com/about-us
```
