### ISSUE TITLE
Add 'Blue Apron' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#438]
Requesting to add 'Blue Apron' to the 'Food' category. 

Details follow: 
```yml 
- name: Blue Apron
      url: https://www.blueapron.com/
      img: https://pbs.twimg.com/profile_images/821742281761951744/saxn3HvQ_400x400.jpg
      twitter: blueapron
      facebook: blueapron
      bch: No
      btc: No
      othercrypto: No
```
