### ISSUE TITLE
Add 'CryptoCribs' to the 'Accommodation' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#440]
Requesting to add 'CryptoCribs' to the 'Accommodation' category. 

Details follow: 
```yml 
- name: CryptoCribs
      url: https://www.cryptocribs.com/
      img: https://scontent.ftpa1-2.fna.fbcdn.net/v/t1.0-9/22519288_421058221624539_6847038911168068667_n.png?oh=5d1aec38372b531c5cc7da765a3394f0&oe=5AF1889D
      twitter: CryptoCribs
      facebook: CryptoCribs
      email_address: info@cryptocribs.com
      city: no
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
