### ISSUE TITLE
Add 'Yourserver.se' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#442]
Requesting to add 'Yourserver.se' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: Yourserver.se
      url: https://www.yourserver.se/
      img: https://drive.google.com/file/d/1AG6UbAR-QycSUEQousLowZJ7r7HHZaL_/view?usp=sharing
      twitter: yourserverse
      facebook: yourserverse
      email_address: tanja@yourserver.se
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
