### ISSUE TITLE
Add 'Renjer - Wild Jerky' to the 'Retail (food)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#444]
Requesting to add 'Renjer - Wild Jerky' to the 'Retail (food)' category. 

Details follow: 
```yml 
- name: Renjer - Wild Jerky
      url: https://www.renjer.ky
      img: https://www.renjer.ky/wp-content/uploads/2018/01/imageedit_2_4533642891.png
      twitter: @renjerjerky
      facebook: @renjer.ky
      email_address: renjer@renjer.ky
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/7r8l4s/our_company_producing_wild_jerky_out_of_reindeer/
```
