### ISSUE TITLE
Add 'myfreecams.com' to the 'cam sites' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#445]
Requesting to add 'myfreecams.com' to the 'entertainment' category. 

Details follow: 
```yml 
- name: myfreecams.com
      url: https://www.myfreecams.com/
      img: 
      twitter: @myfreecams
      bch: No
      btc: No
      othercrypto: No
```
