### ISSUE TITLE
Add 'Norton Anti-Virus' to the 'Antivirus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#447]
Requesting to add 'Norton Anti-Virus' to the 'Antivirus' category. 

Details follow: 
```yml 
- name: Norton Anti-Virus
      url: https://norton.com/
      img: https://pbs.twimg.com/profile_images/816328497694199808/oeI12_Ei_400x400.jpg
      twitter: nortononline
      facebook: norton
      bch: No
      btc: No
      othercrypto: No
```
