### ISSUE TITLE
Add 'ESET NOD32' to the 'Antivirus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#448]
Requesting to add 'ESET NOD32' to the 'Antivirus' category. 

Details follow: 
```yml 
- name: ESET NOD32
      url: https://www.eset.com/
      img: https://pbs.twimg.com/profile_images/870330530218115072/TToUuVDE_400x400.jpg
      twitter: eset
      facebook: eset
      bch: No
      btc: No
      othercrypto: No
```
