### ISSUE TITLE
Add 'McAfee' to the 'antivirus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#449]
Requesting to add 'McAfee' to the 'antivirus' category. 

Details follow: 
```yml 
- name: McAfee
      url: https://www.mcafee.com
      img: https://test.com/mcafee.png
      twitter: McAfee_Home
      facebook: McAfee
      bch: No
      btc: No
      othercrypto: No
```
