### ISSUE TITLE
Add 'Backpage' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#451]
Requesting to add 'Backpage' to the 'Services' category. 

Details follow: 
```yml 
- name: Backpage
      url: https://backpage.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
