### ISSUE TITLE
Add 'Mineralz.nl' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#452]
Requesting to add 'Mineralz.nl' to the 'Retail' category. 

Details follow: 
```yml 
- name: Mineralz.nl
      url: https://mineralz.nl
      img: https://mineralz.nl/img/mineralz-logo-1495367208.jpg
      twitter: MineralzNL
      facebook: https://www.facebook.com/MineralzNL/
      email_address: info@mineralz.nl
      region: eu
      country: NL
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://mineralz.nl/content/12-bitcoin-cash
```
