### ISSUE TITLE
Add 'SilverGoldBull.com' to the 'Precious Metals/Bullion' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#453]
Requesting to add 'SilverGoldBull.com' to the 'Precious Metals/Bullion' category. 

Details follow: 
```yml 
- name: SilverGoldBull.com
      url: www.silvergoldbull.com
      img: silvergoldbull.png
      twitter: silvergoldbull
      facebook: silvergoldbull
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
