### ISSUE TITLE
Add 'Shuriken Social' to the 'Social' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#455]
Requesting to add 'Shuriken Social' to the 'Social' category. 

Details follow: 
```yml 
- name: Shuriken Social
      url: https://shurikensocial.com
      img: https://i.imgur.com/2RoNHtj.png
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
