### ISSUE TITLE
Add 'Bitcoin Superstore' to the 'Online Retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#456]
Requesting to add 'Bitcoin Superstore' to the 'Online Retailer' category. 

Details follow: 
```yml 
- name: Bitcoin Superstore
      url: Https://bitcoinsuperstore.us
      img: https://bitcoinsuperstore.us
      twitter: @bitcoinsuperst1
      facebook: @bitcoinsuperstore
      email_address: customerservice@bitcoinsuperstore.us
      country: US
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/litecoin/comments/7nbdf7/new_online_store_buy_anything_on_amazon_with/
```
