### ISSUE TITLE
Add 'Buy Pi' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#457]
Requesting to add 'Buy Pi' to the 'Gaming' category. 

Details follow: 
```yml 
- name: Buy Pi
      url: https://buypi.net/
      img: https://buypi.net/wp-content/themes/pillar/style/img/logo-dark.png
      twitter: buypinet
      email_address: mark@buypi.net
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: No
```
