### ISSUE TITLE
Add 'GPU Mining Bios' to the 'mining' category

### ISSUE THREAD

**Issue by IndeedMiners** [acceptbitcoincash/acceptbitcoincash#458]
Requesting to add 'GPU Mining Bios' to the 'mining' category. Details follow:

```yml

- name: GPU Mining Bios
  url: https://mining-bios.eu/
  img: https://mining-bios.eu/wp-content/uploads/2018/01/miningbios-square.png
  facebook: indeedminers
  region: eu
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://mining-bios.eu/2018/01/21/more-native-crypto/
```
