### ISSUE TITLE
Add 'AVG AntiVirus' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#459]
Requesting to add 'AVG AntiVirus' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: AVG AntiVirus
      url: https://www.avg.com
      img: avg.png
      twitter: avgfree
      facebook: AVG
      bch: No
      btc: No
      othercrypto: No
```
