### ISSUE TITLE
Add 'BitDefender' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#460]
Requesting to add 'BitDefender' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: BitDefender
      url: bitdefender.com
      img: bitdefender.png
      twitter: Bitdefender
      facebook: 118554158281905
      bch: No
      btc: No
      othercrypto: No
```
