### ISSUE TITLE
Add 'Panda' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#461]
Requesting to add 'Panda' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: Panda
      url: https://www.pandasecurity.com/
      img: https://www.sololistas.net/wp-content/uploads/2011/08/panda.jpg
      twitter: Panda_Security
      facebook: PandaSecurity
      email_address: info@pandasecurity.com
      bch: No
      btc: No
      othercrypto: No
```
