### ISSUE TITLE
Add 'WebRoot' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#462]
Requesting to add 'WeebRoot' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: WeebRoot
      url: https://www.webroot.com
      img: https://www.sololistas.net/wp-content/uploads/2011/08/Webroot.jpeg
      twitter: Webroot
      facebook: Webroot
      bch: No
      btc: No
      othercrypto: No
```
