### ISSUE TITLE
Add 'Trend Micro' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#463]
Requesting to add 'Trend Micro' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: Trend Micro
      url: trendmicro.com 
      img: trendmicro.png
      twitter: TrendMicro
      facebook: Trendmicro
      bch: No
      btc: No
      othercrypto: No
```
