### ISSUE TITLE
Add 'Avira' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#464]
Requesting to add 'Avira' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: Avira
      url: https://www.avira.com/
      img: avira.png
      twitter: avira
      facebook: avira
      bch: No
      btc: No
      othercrypto: No
```
