### ISSUE TITLE
Add 'ZoneAlarm' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#465]
Requesting to add 'ZoneAlarm' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: ZoneAlarm
      url: https://www.zonealarm.com/
      img: zonealarm.png
      twitter: zonealarm
      facebook: ZoneAlarm2017
      bch: No
      btc: No
      othercrypto: No
```
