### ISSUE TITLE
Add 'BullGuard' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#466]
Requesting to add 'BullGuard' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: BullGuard
      url: https://www.bullguard.com
      img: bullguard.png
      twitter: BullGuard
      facebook: BullGuard
      bch: No
      btc: No
      othercrypto: No
```
