### ISSUE TITLE
Add 'F-Secure' to the 'Anti-Virus' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#467]
Requesting to add 'F-Secure' to the 'Anti-Virus' category. 

Details follow: 
```yml 
- name: F-Secure
      url: https://www.f-secure.com
      img: fsecure.png
      twitter: FSecure
      facebook: F-Secure-107471754306
      bch: No
      btc: No
      othercrypto: No
```
