### ISSUE TITLE
Add 'Ponti Partners' to the 'Accountants' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#468]
Requesting to add 'Ponti Partners' to the 'Accountants' category. 

Details follow: 
```yml 
- name: Ponti Partners
      url: https://pontipartners.com.au/
      img: 
      region: oc
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/7rht8s/bitcoin_cash_moving_beyond_just_merchant_adoption/
```
