### ISSUE TITLE
Add 'Scott Mills Art' to the 'Art' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#471]
Requesting to add 'Scott Mills Art' to the 'Art' category. 

Details follow: 
```yml 
- name: Scott Mills Art
      url: http://www.scottmillsart.com
      img: scottmillsart.png
      twitter: scottmillsart
      facebook: scottmillsart
      email_address: scottkmills@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

https://pbs.twimg.com/profile_images/776474389181304832/sjgIzp77_400x400.jpg
