### ISSUE TITLE
Add 'Treebark Termite and Pest Control' to the 'Pest Control' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#476]
Requesting to add 'Treebark Termite and Pest Control' to the 'Pest Control' category. 

Details follow: 
```yml 
- name: Treebark Termite and Pest Control
      url: Https://treebarktermiteandpestcontrol.com
      img: 
      twitter: Treebarktpc
      facebook: Treebarktermite
      email_address: Info@treebarktermiteandpestcontrol.com
      region: na
      country: US
      city: Los Angeles
      bch: Yes
      btc: Yes
      othercrypto: No
```
