### ISSUE TITLE
Add 'Focused Taiwan 佛克斯台灣' to the 'Supplements' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#478]
Requesting to add 'Focused Taiwan 佛克斯台灣' to the 'Supplements' category. 

Details follow: 
```yml 
- name: Focused Taiwan 佛克斯台灣
      url: https://focused.com.tw
      img: https://focused.com.tw/content/uploads/2017/12/focused_logo_with_chinese.png
      twitter: FocusedTaiwan
      facebook: focusedTaiwan
      email_address: kevin@majorbros.com
      region: as
      country: TW
      bch: Yes
      btc: No
      othercrypto: No
```
