### ISSUE TITLE
Add 'Village Catalog' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#479]
Requesting to add 'Village Catalog' to the 'Food' category. 

Details follow: 
```yml 
- name: Village Catalog
      url: https://villagecatalog.com
      img: https://instagram.fphl2-1.fna.fbcdn.net/t51.2885-19/s150x150/25008796_136580157051750_4424232634649935872_n.jpg
      email_address: dave@villagecatalog.com
      region: na
      country: US
      city: All of USA
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/7si1y3/new_project_ive_been_working_on_internet_general/
```
