### ISSUE TITLE
Add 'https://villagecatalog.com' to the 'Retail (household items, accessories, food, etc.)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#480]
Requesting to add 'https://villagecatalog.com' to the 'Retail (household items, accessories, food, etc.)' category. 

Details follow: 
```yml 
- name: https://villagecatalog.com
      url: https://villagecatalog.com
      img: 
      region: na
      country: US
      bch: Yes
      btc: No
      othercrypto: No
```
