### ISSUE TITLE
Add 'CrossFit Spaarne' to the 'Fitness and Health' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#482]
Requesting to add 'CrossFit Spaarne' to the 'Fitness and Health' category. 

Details follow: 
```yml 
- name: CrossFit Spaarne
      url: https://www.crossfitspaarne.nl/
      img: crossfitspaarne.png
      twitter: crossfitspaarne
      email_address: info@crossfitspaarne.nl
      region: eu
      country: NL
      city: Haarlem
      bch: Yes
      btc: No
      othercrypto: Yes
```
