### ISSUE TITLE
Add 'easyDNS' to the 'Domains' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#483]
Requesting to add 'easyDNS' to the 'Domains' category. 

Details follow: 
```yml 
- name: easyDNS
      url: https://www.easydns.com
      img: https://www.easydns.com/images/logo4.png
      twitter: @easydns
      facebook: https://www.facebook.com/easydns
      email_address: markjr@easydns.com
      city: Toronto
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.easydns.com/blog/2018/01/08/0-confirmations-now-accepting-bitcoin-cash-as-a-payment-method/
```
