### ISSUE TITLE
Add 'Biblioteca de Alejandría - IDVPS' to the '( Donations )  -This spanish website now accept Bitcoin Cash donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#486]
Requesting to add 'Biblioteca de Alejandría - IDVPS' to the '( Donations )  -This spanish website now accept Bitcoin Cash donations' category. 

Details follow: 
```yml 
- name: Biblioteca de Alejandría - IDVPS
      url: http://libros-prohibidos8.blogspot.com.es/
      img: http://1.bp.blogspot.com/-FIHnEZGWl60/USEGyARN-RI/AAAAAAAAAHE/Ru5w2WIRzPs/s1600/CARSON.jpg
      email_address: indexprohibido@gmail.com
      region: eu
      country: ES
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: http://libros-prohibidos8.blogspot.com.es/
```
