### ISSUE TITLE
Blockchain.info already implemented BCH but it's still in progress in the wallets category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#487]
Requesting to add ']]]]about Blockchain.info [[[[ Blockchain.info already implemented BCH but acceptbitcoin.cash says it's still in progress' to the 'Wallets' category. 

Details follow: 
```yml 
- name: ]]]]about Blockchain.info [[[[ Blockchain.info already implemented BCH but acceptbitcoin.cash says it's still in progress
      url: blockchain.info
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc:  
```
