### ISSUE TITLE
Add 'ORAN MERKEZI' to the 'Sports' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#488]
Requesting to add 'ORAN MERKEZI' to the 'Sports' category. 

Details follow: 
```yml 
- name: ORAN MERKEZI
      url: https://www.oranmerkezi.com
      img: oran-merkezi-logo.png
      facebook: oranmerkezi
      email_address: info@oranmerkezi.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.oranmerkezi.com/index.php/Giris/uyelik.html
```
