### ISSUE TITLE
Add 'Anti-Virus' to the 'eScan' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#492]
Requesting to add 'Anti-Virus' to the 'eScan' category. 

Details follow: 
```yml 
- name: eScan
      url: https://www.escanav.com/en/index.asp
      img: escan.png
      twitter: eScan_tweet
      facebook: eScanFanPage
      bch: No
      btc: No
      othercrypto: No
```
