### ISSUE TITLE
Add 'Sheet Music 2 Celebrate' to the 'Entertainment' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#493]
Requesting to add 'Sheet Music 2 Celebrate' to the 'Entertainment' category. 

Details follow: 
```yml 
- name: Sheet Music 2 Celebrate
      url: https://www.sheetmusic2celebrate.com
      img: https://www.sheetmusic2celebrate.com/wp-content/uploads/2018/01/fb-profile-sm2c.png
      facebook: https://www.facebook.com/Sheet-Music-to-Celebrate-2040933102814363/
      email_address: contact@sheetmusic2celebrate.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.sheetmusic2celebrate.com/2018/01/26/now-we-accept-bitcoin-bitcoincash-and-litecoin/
```
