### ISSUE TITLE
Add 'homedot' to the 'homedot' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#494]
Requesting to add 'homedot' to the 'homedot' category. 

Details follow: 
```yml 
- name: homedot
      url: bitcoincash:qzpxn8jcap2v6rmvhc7kxh0unjyvqeaqlu7u3525tu
      img: 
      email_address: badgang978@gmail.com
      region: na
      country: JE
      city: atlantic city
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: bitcoincash:qzpxn8jcap2v6rmvhc7kxh0unjyvqeaqlu7u3525tu
```
