### ISSUE TITLE
Add 'InstaSmarter' to the 'Social Media Marketing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#495]
Requesting to add 'InstaSmarter' to the 'Social Media Marketing' category. 

Details follow: 
```yml 
- name: InstaSmarter
      url: http://www.instasmarter.com/
      img: InstaSmarter.png
      twitter: InstaSmarter
      email_address: Service@InstaSmarter.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
