### ISSUE TITLE
Add 'Spatial Simulations' to the 'Computer Aided Design and Engineering' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#496]
Requesting to add 'Spatial Simulations' to the 'Computer Aided Design and Engineering' category. 

Details follow: 
```yml 
- name: Spatial Simulations
      url: https://www.spatialsim.com/
      img: spatialsimulations.png
      email_address: 3d@spatialsim.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
