### ISSUE TITLE
Add 'Bitcoin Superstore' to the 'Online Retailer: Buy From Any Online Shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#497]
Requesting to add 'Bitcoin Superstore' to the 'Online Retailer: Buy From Any Online Shop' category. 

Details follow: 
```yml 
- name: Bitcoin Superstore
      url: https://bitcoinsuperstore.us
      img: 
      twitter: BitcoinSuperst1
      email_address: customerservice@bitcoinsuperstore.us
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
