### ISSUE TITLE
Add 'Purism' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#498]
Requesting to add 'Purism' to the 'Retail' category. 

Details follow: 
```yml 
- name: Purism
      url: https://puri.sm/
      img: https://pbs.twimg.com/profile_images/644302545649664001/8tpw9QGp_400x400.jpg
      twitter: Puri_sm
      facebook: purismcomputer
      email_address: info@puri.sm
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
