### ISSUE TITLE
Add 'Bitrush.nl' to the 'Exchanges' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#499]
Requesting to add 'Bitrush.nl' to the 'Exchanges' category. 

Details follow: 
```yml 
- name: Bitrush.nl
      url: https://bitrush.nl/nl/shop/eur-bch/bitcoin-cash
      img: 
      twitter: BitrushGo
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
