### ISSUE TITLE
Add 'Treebark Termite and Pest Control Anaheim' to the 'Pest Control' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#505]
Requesting to add 'Treebark Termite and Pest Control Anaheim' to the 'Pest Control' category. 

Details follow: 
```yml 
- name: Treebark Termite and Pest Control Anaheim
      url: https://treebarktermiteandpestcontrol.com/anaheim/
      img: 
      twitter: TreebarkTPC
      facebook: TreebarkTermite
      email_address: acunningham@treebarktermiteandpestcontrol.com
      region: na
      country: US
      city: Anaheim
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://treebarktermiteandpestcontrol.com/Bitcoin
```
