### ISSUE TITLE
Add 'Betonline' to the 'gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#512]
Requesting to add 'Betonline' to the 'gambling' category. 

Details follow: 
```yml 
- name: Betonline
      url: betonline.ag
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
