### ISSUE TITLE
Add 'test site' to the 'Sites' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#513]
Requesting to add 'test site' to the 'Sites' category. 

Details follow: 
```yml 
- name: test site
      url: https://acceptbitcoin.cash
      bch: Yes
      btc: No
      othercrypto: No
```
