### ISSUE TITLE
Add 'test' to the 'test' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#514]
Requesting to add 'test' to the 'test' category. 

Details follow: 
```yml 
- name: test
      url: https://acceptbitcoin.cash
      img: https://twitter.com/useBitcoinCash
      twitter: useBitcoinCash
      bch: Yes
      btc: No
      othercrypto: No
```

https://twitter.com/useBitcoinCash
