### ISSUE TITLE
Add 'Taimine' to the 'Mining Hardware' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#518]
Requesting to add 'Taimine' to the 'Mining Hardware' category. 

Details follow: 
```yml 
- name: Taimine
      url: https://taimine.com
      img: https://i2.wp.com/taimine.com/wp-content/uploads/2018/01/cropped-taimine%E6%8C%96%E7%A4%A6%E6%A9%9F%E4%B8%AD%E5%BF%83logo-1-2.png
      twitter: taimineminer
      facebook: taimineindustries
      email_address: service@taimine.com
      region: as
      city: all of asia
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
