### ISSUE TITLE
Add 'Village Catalog' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#519]
Requesting to add 'Village Catalog' to the 'Food' category. 

Details follow: 
```yml 
- name: Village Catalog
      url: https://villagecatalog.com
      img: https://camo.githubusercontent.com/9b94876c98efcb2f68ad4e774b01b7656760b944/68747470733a2f2f692e696d6775722e636f6d2f474d3858684c582e6a70673f32
      email_address: dave@villagecatalog.com
      region: na
      country: US
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/7si1y3/new_project_ive_been_working_on_internet_general/
```

![Village Catalog](https://camo.githubusercontent.com/9b94876c98efcb2f68ad4e774b01b7656760b944/68747470733a2f2f692e696d6775722e636f6d2f474d3858684c582e6a70673f32)
