### ISSUE TITLE
mykolab.com

### ISSUE THREAD

**Issue by zander** [acceptbitcoincash/acceptbitcoincash#520]
Requesting to add mykolab.com to the Email category. Details follow:

```yml

- name: kolab now
  url: https://kolabnow.com
  img: mykolab.png
  twitter: kolabsys
  facebook: Kolab-Now-503394299799839
  region: eu
  country: ch
  city: KUESNACHT
  bch: no
  btc: yes
  othercrypto: no
  doc: https://kolabnow.com/support/payments
```
They use BitPay, so BCH should become available shortly (I hope..)
