### ISSUE TITLE
Add '1broker' to the 'Financial' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#521]
Requesting to add '1broker' to the 'Financial' category. 

Details follow: 
```yml 
- name: 1broker
      url: https://1broker.com/?c=en/home
      img: https://1broker.com/img/logo_blue.svg
      twitter: 1brokercom
      facebook: 1Brokercom
      email_address: support@1Broker.com
      bch: No
      btc: Yes
      othercrypto: No
```

![1broker](https://1broker.com/img/logo_blue.svg)
