### ISSUE TITLE
Add 'coinbought.com' to the 'Retail (buy anything you would on Amazon)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#522]
Requesting to add 'coinbought.com' to the 'Retail (buy anything you would on Amazon)' category. 

Details follow: 
```yml 
- name: coinbought.com
      url: https://coinbought.com/ 
      img: 
      email_address: support@coinbought.com
      region: na
      city: (They are planning on supporting Germany, France, and the UK as well!)
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/7ut8wh/buy_anything_off_of_amazoncom_with_bitcoincash/
```
