### ISSUE TITLE
Add 'WK End Eyeware' to the 'Retail (They sell sunglasses)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#523]
Requesting to add 'WK End Eyeware' to the 'Retail (They sell sunglasses)' category. 

Details follow: 
```yml 
- name: WK End Eyeware
      url: https://wkend.club/
      img: 
      facebook: https://www.facebook.com/wkend.club
      email_address: info@wkend.club
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://wkend.club/
```

If no image url provided or it is not of the right size, try the facebook handles profile image: https://fb.com/https://www.facebook.com/wkend.club
