### ISSUE TITLE
Add 'Bitstarz' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#525]
Requesting to add 'Bitstarz' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Bitstarz
      url: https://www.bitstarz.com/
      img: 
      twitter: bitstarzcasino
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://calvinayre.com/2018/02/02/bitcoin/bitstarz-starts-accepting-bitcoin-cash/
```

Logo Provided:
![Bitstarz](https://pbs.twimg.com/profile_images/605368907239723008/Jj4OcQmV_400x400.png)

[Link to Bitstarz](https://www.bitstarz.com/)
If no image url was provided or it is not of the right size, try the twitter handles profile image: https://twitter.com/bitstarzcasino
