### ISSUE TITLE
Add 'Bitcoin payment processing api' to the 'Bitcoin Payment Gateway ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#527]
Requesting to add 'Bitcoin payment processing api' to the 'Bitcoin Payment Gateway ' category. 

Details follow: 
```yml 
- name: Bitcoin payment processing api
      url: https://btcapi.org/
      img: 
      email_address: admin@btcapi.or
      country: US
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://btcapi.org/docs
```

Resources for adding this merchant:
[Link to Bitcoin payment processing api](https://btcapi.org/)
