### ISSUE TITLE
Add 'Xpresso' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#528]
Requesting to add 'Xpresso' to the 'Food' category. 

Details follow: 
```yml 
- name: Xpresso
      url: https://www.xpressoutah.com
      img: XpressOutah.png
      twitter: XpressOutah
      facebook: xpressoutah
      region: na
      country: US
      city: Salt Lake City
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Xpresso](https://www.xpressoutah.com)
![Logo](https://i.imgur.com/twEtspn.jpg?2)
