### ISSUE TITLE
Add 'Bitcoin Superstore' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#531]
Requesting to add 'Bitcoin Superstore' to the 'Retail' category. 

Details follow: 
```yml 
- name: Bitcoin Superstore
      url: https://bitcoinsuperstore.us
      img: 
      twitter: https://twitter.com/BitcoinSuperst1
      email_address: customersupport@bitcoinsuperstore.us
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Bitcoin Superstore](https://bitcoinsuperstore.us)
If no image url was provided or it is not of the right size, try the twitter handles profile image: https://twitter.com/https://twitter.com/BitcoinSuperst1
