### ISSUE TITLE
Add 'Coinbase' to the 'Wallets' Category

### ISSUE THREAD

**Issue by RichJeanes** [acceptbitcoincash/acceptbitcoincash#535]
```yml

- name: Coinbase
  url: https://coinbase.com
  img: https://www.coinbase.com/apple-touch-icon.png
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://support.coinbase.com/customer/en/portal/articles/2630943-supported-digital-currencies?b_id=13521
```

Turns out that forks are not considered their own unique repository on GitHub so I can't fork this project to make a PR since I already have 2factorauth/twofactorauth forked... Interesting...
