### ISSUE TITLE
Add 'Bit2Me' to the '#cryptoservices' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#536]
Requesting to add 'Bit2Me' to the '#cryptoservices' category. 

Details follow: 
```yml 
- name: Bit2Me
      url: https://bit2me.com
      img: 
      twitter: bit2me
      facebook: bit2me
      email_address: info@bit2me.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Bit2Me](https://bit2me.com)
If no image url was provided or it is not of the right size, try the twitter handles profile image: https://twitter.com/bit2me
If no image url was provided or it is not of the right size, try the facebook handles profile image: https://fb.com/bit2me
