### ISSUE TITLE
Add 'Tutanota' to the '#email' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#537]
Requesting to add 'Tutanota' to the '#email' category. 

Details follow: 
```yml 
- name: Tutanota
      url: http://www.tutanota.com
      img: 
      twitter: tutanotateam
      facebook: tutanota
      bch: No
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Tutanota](http://www.tutanota.com)
If no image url was provided or it is not of the right size, try the twitter handles profile image: https://twitter.com/tutanotateam
If no image url was provided or it is not of the right size, try the facebook handles profile image: https://fb.com/tutanota
