### ISSUE TITLE
Add 'Alia Armelle on GGB' to the 'Adult' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#540]
Requesting to add 'Alia Armelle on GGB' to the 'Adult' category. 

Details follow: 
```yml 
- name: Alia Armelle on GGB
      url: https://www.reddit.com/r/GirlsGoneBitcoin/comments/7t4w7a/can_someone_please_play_with_me/
      img: 
      email_address: alexcaze1234@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Alia Armelle on GGB](https://www.reddit.com/r/GirlsGoneBitcoin/comments/7t4w7a/can_someone_please_play_with_me/)

**Comment by kenman345** [comment]
Alright guys, I guess we were asking for it. 

Shall we add some tag support for Skype name? Reddit account? Wouldnt take much to add if we all agree to it.

**Comment by hegjon** [comment]
If we add Reddit, maybe use reddit_user(name) as the key, so we can specify reddit_sub(reddit) later.

Btw, how could/should we add tiprbot?

**Comment by kenman345** [comment]
oriinally i thought we would just store: r/btc or u/kenman345 as the values, but not a bad suggestion. I kinda like it

**Comment by hegjon** [comment]
Yeah, there are pros and cons.

Example:
```
reddit_user: alia_armelle
reddit_subreddit: GirlsGoneBitcoin 
```

**Comment by kenman345** [comment]
So every addition kinda adds length to the form, but, maybe if we added reddit tag then we do as such:
```yml
reddit:
  username: 
  sub: 
```

This would work for a listing of a pornstar/adult actress/actor that has a username and a subreddit

**Comment by kenman345** [comment]
though honestly, i'd prefer to keep the u/.... and r/.... in the strings in the tags so its easy to just straight out use. the issue with one tag is then we only get one listing when both may apply. 

An alternative is a complete break of structure to allow for new EVERYTHING!

```yml
social:
 - site: *twitter
   handle: usebitcoincash
 - site: *facebook
   handle: ......
 - site: *reddit
   handle r/GirlsGoneBitcoin
 - site: *reddit
   handle: u/alia_armelle
 - site: *skype
   handle: .....
```

Then we can go ahead and instead of using site name we use pointers that reference a list of social sites and they have tags we use when generating a page:

```yml
- name: &twitter
  url: https://twitter.com/
- name: &facebook
  url: https://fb.com/
- name: &reddit
  url: https://reddit.com
```

I think i just did those properly :-D 

It could be very interesting to do it this way, as we dont need to add a tag to accommodate new functionality, we just add a new social site to our data. this means less messing in the html when we dont have to. Doing this during a refactor effort already planned would be best timing.
