### ISSUE TITLE
Add 'Remitano' to the 'Local Peer to peer exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#541]
Requesting to add 'Remitano' to the 'Local Peer to peer exchange' category. 

Details follow: 
```yml 
- name: Remitano
      url: https://remitano.com
      img: 
      twitter: remitano
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Remitano](https://remitano.com)
If no image url was provided or it is not of the right size, try the twitter handles profile image: https://twitter.com/remitano
