### ISSUE TITLE
Add 'Yuthana' to the 'Bitcoin' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#544]
Requesting to add 'Yuthana' to the 'Bitcoin' category. 

Details follow: 
```yml 
- name: Yuthana
      url: http://www.Blockchain.com
      img: 
      email_address: patumsima2527@gmail.com
      region: eu
      country: TH
      city: Bangkok
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Yuthana](http://www.Blockchain.com)
