### ISSUE TITLE
Add 'IPTVPlanet' to the 'IPTV' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#546]
Requesting to add 'IPTVPlanet' to the 'IPTV' category. 

Details follow: 
```yml 
- name: IPTVPlanet
      url: https://www.iptvplanet.ca/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to IPTVPlanet](https://www.iptvplanet.ca/)
