### ISSUE TITLE
Add 'Pinoy Game Store' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#548]
Requesting to add 'Pinoy Game Store' to the 'Gaming' category. 

Details follow: 
```yml 
- name: Pinoy Game Store
      url: http://www.pinoygamestore.com
      img: 
      twitter: pinoygamestore
      facebook: pinoygamestore
      email_address: pinoygamestore@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: http://www.pinoygamestore.com/2018/02/pinoy-game-store-accepts-bitcoin-cash.html
```

Resources for adding this merchant:
[Link to Pinoy Game Store](http://www.pinoygamestore.com)
If needed, try the twitter handles profile image: [twitter.com/pinoygamestore](https://twitter.com/pinoygamestore)
If needed, try the facebook handles profile image: [fb.com/pinoygamestore](https://fb.com/pinoygamestore)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
