### ISSUE TITLE
Add 'BITCOIN CACH' to the 'MOYEL' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#550]
Requesting to add 'BITCOIN CACH' to the 'MOYEL' category. 

Details follow: 
```yml 
- name: BITCOIN CACH
      url: https://acceptbitcoin.cash/
      img: 
      email_address: mostaphafadi@gmail.com
      region: af
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to BITCOIN CACH](https://acceptbitcoin.cash/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
