### ISSUE TITLE
Add 'Btcinshop' to the 'Mining device hardwarewallet' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#551]
Requesting to add 'Btcinshop' to the 'Mining device hardwarewallet' category. 

Details follow: 
```yml 
- name: Btcinshop
      url: http://www.btcinshop.com
      img: 
      twitter: btcinshop
      email_address: info@btcinshop.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: http://www.btcinshop.com
```

Resources for adding this merchant:
[Link to Btcinshop](http://www.btcinshop.com)
If needed, try the twitter handles profile image: [twitter.com/btcinshop](https://twitter.com/btcinshop)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
