### ISSUE TITLE
Add 'OddEvenBets' to the 'Gambling, betting, casino' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#553]
Requesting to add 'OddEvenBets' to the 'Gambling, betting, casino' category. 

Details follow: 
```yml 
- name: OddEvenBets
      url: http://oddevenbets.com
      img: 
      twitter: OddEvenBets
      email_address: oddevenbets@mail333.com
      bch: Yes
      btc: No
      othercrypto: No
      doc: http://oddevenbets.com
```

Resources for adding this merchant:
[Link to OddEvenBets](http://oddevenbets.com)
If needed, try the twitter handles profile image: [twitter.com/OddEvenBets](https://twitter.com/OddEvenBets)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
