### ISSUE TITLE
Add 'PekTech' to the 'Technology, Fabrication, Prototyping Service, 3D Printing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#554]
Requesting to add 'PekTech' to the 'Technology, Fabrication, Prototyping Service, 3D Printing' category. 

Details follow: 
```yml 
- name: PekTech
      url: https://pek.tech
      img: 
      twitter: pek_tech
      email_address: contact@pek.tech
      region: na
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://twitter.com/pek_tech/status/962967524605231104?ref_src=twcamp%5Eshare%7Ctwsrc%5Em5%7Ctwgr%5Eemail%7Ctwcon%5E7046%7Ctwterm%5E1
```

Resources for adding this merchant:
[Link to PekTech](https://pek.tech)
If needed, try the twitter handles profile image: [twitter.com/pek_tech](https://twitter.com/pek_tech)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
