### ISSUE TITLE
Add 'Sportsbetting' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#555]
Requesting to add 'Sportsbetting' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Sportsbetting
      url: https://www.sportsbetting.ag
      img: 
      twitter: SportsBettingAG
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Sportsbetting](https://www.sportsbetting.ag)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
