### ISSUE TITLE
Add 'Bodog' to the 'gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#557]
Requesting to add 'Bodog' to the 'gambling' category. 

Details follow: 
```yml 
- name: Bodog
      url: https://www.bodog.eu/
      img: 
      facebook: BodogCanada
      twitter: BodogCa
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Bodog](https://www.bodog.eu/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
