### ISSUE TITLE
Add 'Many Coins' to the 'Lotto' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#558]
Requesting to add 'Many Coins' to the 'Lotto' category. 

Details follow: 
```yml 
- name: Many Coins
      url: http://manycoins.net
      img: 
      email_address: vladismile@i.ua
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Many Coins](http://manycoins.net)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
