### ISSUE TITLE
Add 'Action Outside LLC' to the 'Outdoor' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#559]
Requesting to add 'Action Outside LLC' to the 'Outdoor' category. 

Details follow: 
```yml 
- name: Action Outside LLC
      url: http://www.actionoutside.com
      img: 
      email_address: jswenson@gmail.com
      region: na
      city: Montana and Idaho
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Action Outside LLC](http://www.actionoutside.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
