### ISSUE TITLE
Add 'MOONLIMO.eu' to the 'Transport, Limousines' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#560]
Requesting to add 'MOONLIMO.eu' to the 'Transport, Limousines' category. 

Details follow: 
```yml 
- name: MOONLIMO.eu
      url: https://moonlimo.eu
      img: 
      twitter: moonlimoeu
      facebook: moonlimo.eu
      email_address: info@moonlimo.eu
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://moonlimo.eu/pay-with-crypto/
```

Resources for adding this merchant:
[Link to MOONLIMO.eu](https://moonlimo.eu)
If needed, try the twitter handles profile image: [twitter.com/moonlimoeu](https://twitter.com/moonlimoeu)
If needed, try the facebook handles profile image: [fb.com/moonlimo.eu](https://fb.com/moonlimo.eu)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
