### ISSUE TITLE
Add 'SV Breta' to the 'Lodging' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#561]
Requesting to add 'SV Breta' to the 'Lodging' category. 

Details follow: 
```yml 
- name: SV Breta
      url: https://breta.weebly.com/
      img: 
      twitter: RoyWessbecher
      email_address: BretaNet00@hotmail.com
      region: na
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to SV Breta](https://breta.weebly.com/)
If needed, try the twitter handles profile image: [twitter.com/RoyWessbecher](https://twitter.com/RoyWessbecher)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
