### ISSUE TITLE
Add 'Premiumize.me' to the 'Cloud downloader' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#562]
Requesting to add 'Premiumize.me' to the 'Cloud downloader' category. 

Details follow: 
```yml 
- name: Premiumize.me
      url: https://www.premiumize.me
      img: premiumizeme.png
      twitter: premiumizeme
      facebook: PremiumizeMe
      email_address: acceptbitcoin@guyrimmer.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.premiumize.me/news
```

Resources for adding this merchant:
[Link to Premiumize.me](https://www.premiumize.me)
If needed, try the twitter handles profile image: [twitter.com/premiumizeme](https://twitter.com/premiumizeme)
If needed, try the facebook handles profile image: [fb.com/PremiumizeMe](https://fb.com/PremiumizeMe)

- [ ] Verify site is legitimate and safe to list.
- [x] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
