### ISSUE TITLE
Add 'Baton Vapor' to the 'E-cigarette' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#564]
Requesting to add 'Baton Vapor' to the 'E-cigarette' category. 

Details follow: 
```yml 
- name: Baton Vapor
      url: https://batonvapor.com
      img: 
      facebook: batonvapor
      email_address: timmy@batonvapor.com
      country: US
      city: Seattle
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Baton Vapor](https://batonvapor.com)
If needed, try the facebook handles profile image: [fb.com/batonvapor](https://fb.com/batonvapor)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
