### ISSUE TITLE
Add 'Adultiful' to the 'Sites/Networks (Adult)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#565]
Requesting to add 'Adultiful' to the 'Sites/Networks (Adult)' category. 

Details follow: 
```yml 
- name: Adultiful
      url: https://adultiful.ca
      img: 
      twitter: adultiful
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://twitter.com/Adultiful/status/963885102928465923
```

Resources for adding this merchant:
[Link to Adultiful](https://adultiful.ca)
If needed, try the twitter handles profile image: [twitter.com/adultiful](https://twitter.com/adultiful)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
