### ISSUE TITLE
Add 'Campus Creations' to the 'Custom Apparel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#566]
Requesting to add 'Campus Creations' to the 'Custom Apparel' category. 

Details follow: 
```yml 
- name: Campus Creations
      url: https://www.getccgear.com
      img: 
      facebook: getccgear
      email_address: dan@getccgear.com
      region: na
      country: US
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.yours.org/content/campus-creations---barpay-to-accept-bitcoin-cash-payments-7b048f25efa7
```

Resources for adding this merchant:
[Link to Campus Creations](https://www.getccgear.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
