### ISSUE TITLE
Add 'cryptohearsay' to the 'crypto' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#567]
Requesting to add 'cryptohearsay' to the 'crypto' category. 

Details follow: 
```yml 
- name: cryptohearsay
      url: https://www.cryptohearsay.com/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to cryptohearsay](https://www.cryptohearsay.com/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
