### ISSUE TITLE
Add 'nVpn' to the 'Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#568]
Requesting to add 'nVpn' to the 'Security' category. 

Details follow: 
```yml 
- name: nVpn
      url: https://nvpn.net/
      img: 
      twitter: nVpnNet
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to nVpn](https://nvpn.net/)
If needed, try the twitter handles profile image: [twitter.com/nVpnNet](https://twitter.com/nVpnNet)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
