### ISSUE TITLE
Add 'BlockCypher' to the 'Crypto Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#569]
Requesting to add 'BlockCypher' to the 'Crypto Services' category. 

Details follow: 
```yml 
- name: BlockCypher
      url: https://www.blockcypher.com/
      img: 
      twitter: BlockCypher
      facebook: BlockCypher
      email_address: contact@blockcypher.com
      bch: No
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to BlockCypher](https://www.blockcypher.com/)
If needed, try the twitter handles profile image: [twitter.com/BlockCypher](https://twitter.com/BlockCypher)
If needed, try the facebook handles profile image: [fb.com/BlockCypher](https://fb.com/BlockCypher)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
