### ISSUE TITLE
Add 'AffordableJerseys.com' to the 'Apparel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#570]
Requesting to add 'AffordableJerseys.com' to the 'Apparel' category. 

Details follow: 
```yml 
- name: AffordableJerseys.com
      url: http://affordablejerseys.com
      img: 
      twitter: affordablejerz
      facebook: affordablejerz
      email_address: chapin@affordablejerseys.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://medium.com/chapin-labs/all-chapin-labs-e-commerce-companies-to-accept-bitcoin-cash-2bb40d95f94d
```

Resources for adding this merchant:
[Link to AffordableJerseys.com](http://affordablejerseys.com)
If needed, try the twitter handles profile image: [twitter.com/affordablejerz](https://twitter.com/affordablejerz)
If needed, try the facebook handles profile image: [fb.com/affordablejerz](https://fb.com/affordablejerz)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
