### ISSUE TITLE
Add 'Edge' to the 'Wallets' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#571]
Requesting to add 'Edge' to the 'Wallets' category. 

Details follow: 
```yml 
- name: Edge
      url: https://edgesecure.co
      img: 
      twitter: EdgeSecure 
      facebook: @EdgeSec
      email_address: support@edgesecure.co
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://blog.edgesecure.co/edge-wallet-is-live-d844cc483210
```

Resources for adding this merchant:
[Link to Edge](https://edgesecure.co)
If needed, try the twitter handles profile image: [twitter.com/EdgeSecure ](https://twitter.com/EdgeSecure )
If needed, try the facebook handles profile image: [fb.com/@EdgeSec](https://fb.com/@EdgeSec)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
