### ISSUE TITLE
Add 'Mullvad VPN' to the 'Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#573]
Requesting to add 'Mullvad VPN' to the 'Security' category. 

Details follow: 
```yml 
- name: Mullvad VPN
      url: https://mullvad.net
      img: 
      twitter: mullvadnet
      email_address: support@mullvad.net
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://mullvad.net/en/blog/2018/2/13/bitcoin-cash-now-accepted/
```

Resources for adding this merchant:
[Link to Mullvad VPN](https://mullvad.net)
If needed, try the twitter handles profile image: [twitter.com/mullvadnet](https://twitter.com/mullvadnet)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
