### ISSUE TITLE
Add 'Full Circle Clothing' to the 'Clothing/Fashion' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#574]
Requesting to add 'Full Circle Clothing' to the 'Clothing/Fashion' category. 

Details follow: 
```yml 
- name: Full Circle Clothing
      url: https://imfullcircle.com/
      img: 
      facebook: imfullcircle
      email_address: contact@imfullcircle.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Full Circle Clothing](https://imfullcircle.com/)
If needed, try the facebook handles profile image: [fb.com/imfullcircle](https://fb.com/imfullcircle)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
