### ISSUE TITLE
Add 'MusicPlug.com.au' to the 'Music & Clothing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#575]
Requesting to add 'MusicPlug.com.au' to the 'Music & Clothing' category. 

Details follow: 
```yml 
- name: MusicPlug.com.au
      url: https://musicplug.com.au
      img: 
      country: AU
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to MusicPlug.com.au](https://musicplug.com.au)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
