### ISSUE TITLE
Add 'Rock Stuff' to the 'retail clothing and jewellery' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#576]
Requesting to add 'Rock Stuff' to the 'retail clothing and jewellery' category. 

Details follow: 
```yml 
- name: Rock Stuff
      url: https://www.rockstuff.com.au/
      img: 
      facebook: RockStuffCheck12
      email_address: info@rockstuff.rocks
      bch: No
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Rock Stuff](https://www.rockstuff.com.au/)
If needed, try the facebook handles profile image: [fb.com/RockStuffCheck12](https://fb.com/RockStuffCheck12)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
