### ISSUE TITLE
Add 'Alfatop.me' to the 'Mobile top-up' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#580]
Requesting to add 'Alfatop.me' to the 'Mobile top-up' category. 

Details follow: 
```yml 
- name: Alfatop.me
      url: https://www.alfatop.me
      img: 
      twitter: ALFAtopme
      facebook: alfatop.me
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/ALFAtopme/status/965512505471721472
```

Resources for adding this merchant:
[Link to Alfatop.me](https://www.alfatop.me)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
