### ISSUE TITLE
Add 'PaySrc' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#581]
Requesting to add 'PaySrc' to the 'Payments' category. 

Details follow: 
```yml 
- name: PaySrc
      url: https://paysrc.com/
      img: 
      twitter: paysrc_com
      email_address: support@paysrc.com
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to PaySrc](https://paysrc.com/)
If needed, try the twitter handles profile image: [twitter.com/paysrc_com](https://twitter.com/paysrc_com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
