### ISSUE TITLE
Add 'dry.camp' to the 'Outdoor Goods' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#582]
Requesting to add 'dry.camp' to the 'Outdoor Goods' category. 

Details follow: 
```yml 
- name: dry.camp
      url: https://dry.camp
      img: 
      twitter: drycampteam
      facebook: drycampteam
      email_address: service@dry.camp
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/btc/comments/7yy0dw/because_of_coinbase_commerce_we_added_bitcoin/
```

Resources for adding this merchant:
[Link to dry.camp](https://dry.camp)
If needed, try the twitter handles profile image: [twitter.com/drycampteam](https://twitter.com/drycampteam)
If needed, try the facebook handles profile image: [fb.com/drycampteam](https://fb.com/drycampteam)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
