### ISSUE TITLE
Add 'muse.markraybin.com' to the 'Graphic Design / Web Development / Adobe Muse Widgets' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#583]
Requesting to add 'muse.markraybin.com' to the 'Graphic Design / Web Development / Adobe Muse Widgets' category. 

Details follow: 
```yml 
- name: muse.markraybin.com
      url: https://muse.markraybin.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to muse.markraybin.com](https://muse.markraybin.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
