### ISSUE TITLE
Add 'davidhpictures' to the 'Media Production Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#585]
Requesting to add 'davidhpictures' to the 'Media Production Services' category. 

Details follow: 
```yml 
- name: davidhpictures
      url: https://davidhpictures.com
      img: 
      email_address: david@davidhpictures.com
      region: na
      country: US
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to davidhpictures](https://davidhpictures.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
