### ISSUE TITLE
Add 'Contemporary Training' to the 'Education' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#586]
Requesting to add 'Contemporary Training' to the 'Education' category. 

Details follow: 
```yml 
- name: Contemporary Training
      url: http://contemporarytraining.co.za/
      img: 
      twitter: CTrainingZA
      facebook: ContemporaryTrainingZA
      email_address: info@contemporarytraining.co.za
      region: af
      country: ZA
      city: Johannesburg & Pretoria
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Contemporary Training](http://contemporarytraining.co.za/)
If needed, try the twitter handles profile image: [twitter.com/CTrainingZA](https://twitter.com/CTrainingZA)
If needed, try the facebook handles profile image: [fb.com/ContemporaryTrainingZA](https://fb.com/ContemporaryTrainingZA)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
