### ISSUE TITLE
Add 'Gutes Leben Ltd' to the 'Consumer Goods' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#587]
Requesting to add 'Gutes Leben Ltd' to the 'Consumer Goods' category. 

Details follow: 
```yml 
- name: Gutes Leben Ltd
      url: https://guteshome.com/
      img: 
      twitter: guteslebenltd
      facebook: guteslebenItd.
      email_address: gutesleben@consultant.com
      region: af
      country: GH
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Gutes Leben Ltd](https://guteshome.com/products.php)
If needed, try the twitter handles profile image: [twitter.com/guteslebenltd](https://twitter.com/guteslebenltd)
If needed, try the facebook handles profile image: [fb.com/guteslebenItd.](https://fb.com/guteslebenItd.)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
