### ISSUE TITLE
Add 'Selly.gg' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#588]
Requesting to add 'Selly.gg' to the 'Payments' category. 

Details follow: 
```yml 
- name: Selly.gg
      url: https://selly.gg
      img: 
      twitter: SellyLLC
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Selly.gg](https://selly.gg)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
