### ISSUE TITLE
Add '99japan' to the 'Japanese general shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#589]
Requesting to add '99japan' to the 'Japanese general shop' category. 

Details follow: 
```yml 
- name: 99japan
      url: https://99japan.com/
      img: 
      twitter: 99japancom
      facebook: 99japancom
      email_address: contact@99japan.com
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to 99japan](https://99japan.com/)
If needed, try the twitter handles profile image: [twitter.com/99japancom](https://twitter.com/99japancom)
If needed, try the facebook handles profile image: [fb.com/99japancom](https://fb.com/99japancom)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
