### ISSUE TITLE
Add 'Bitek' to the 'All' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#590]
Requesting to add 'Bitek' to the 'All' category. 

Details follow: 
```yml 
- name: Bitek
      url: https://bitek.co
      img: 
      twitter: bitekco
      facebook: bitekco
      email_address: contacto@bitek.co
      region: sa
      country: CO
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Bitek](https://bitek.co)
If needed, try the twitter handles profile image: [twitter.com/bitekco](https://twitter.com/bitekco)
If needed, try the facebook handles profile image: [fb.com/bitekco](https://fb.com/bitekco)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
