### ISSUE TITLE
Add 'Gof' to the 'Bitcoin' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#591]
Requesting to add 'Gof' to the 'Bitcoin' category. 

Details follow: 
```yml 
- name: Gof
      url: https://freebitco.in/?op=home#
      img: 
      region: as
      country: TH
      city: Pattani
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Gof](https://freebitco.in/?op=home#)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
