### ISSUE TITLE
Add 'CoinBought' to the 'eCommerce' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#592]
Requesting to add 'CoinBought' to the 'eCommerce' category. 

Details follow: 
```yml 
- name: CoinBought
      url: https://coinbought.com
      img: 
      twitter: CoinBought
      email_address: support@coinbought.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/btc/comments/7uvcj6/buy_anything_off_of_amazoncom_with_bitcoin_cash/
```

Resources for adding this merchant:
[Link to CoinBought](https://coinbought.com)
If needed, try the twitter handles profile image: [twitter.com/CoinBought](https://twitter.com/CoinBought)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
