### ISSUE TITLE
Add 'Vaporizers Direct' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#593]
Requesting to add 'Vaporizers Direct' to the 'Retail' category. 

Details follow: 
```yml 
- name: Vaporizers Direct
      url: https://vaporizersdirect.com.au
      img: 
      twitter: vaporizerdirect
      facebook: vaporizersdirect
      email_address: christian@vaporizersdirect.com.au
      region: oc
      country: AU
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Vaporizers Direct](https://vaporizersdirect.com.au)
If needed, try the twitter handles profile image: [twitter.com/vaporizerdirect](https://twitter.com/vaporizerdirect)
If needed, try the facebook handles profile image: [fb.com/vaporizersdirect/](https://fb.com/vaporizersdirect/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
