### ISSUE TITLE
Add 'KNW refrigeration' to the 'Refrigeration services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#594]
Requesting to add 'KNW refrigeration' to the 'Refrigeration services' category. 

Details follow: 
```yml 
- name: KNW refrigeration
      url: http://www.knw-refrigeration.co.za
      img: knwRefrigeration.png
      email_address: info@knw-refrigeration.co.za
      region: af
      country: ZA
      city: Cape Town
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to KNW refrigeration](http://www.knw-refrigeration.co.za)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
