### ISSUE TITLE
Add 'Diamondcard.us VOIP Service' to the 'Communication' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#595]
Requesting to add 'Diamondcard.us VOIP Service' to the 'Communication' category. 

Details follow: 
```yml 
- name: Diamondcard.us VOIP Service
      url: https://www.diamondcard.us
      img: 
      email_address: sales@diamondcard.us
      city: Thailand
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Diamondcard.us VOIP Service](https://www.diamondcard.us)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
