### ISSUE TITLE
Add 'Cryptreview' to the 'Other' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#596]
Requesting to add 'Cryptreview' to the 'Other' category. 

Details follow: 
```yml 
- name: Cryptreview
      url: https://cryptreview.com
      img: 
      email_address: info@cryptreview.com
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Cryptreview](https://cryptreview.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
