### ISSUE TITLE
Add 'AstorBond.com' to the 'Men's Watches and Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#597]
Requesting to add 'AstorBond.com' to the 'Men's Watches and Accessories' category. 

Details follow: 
```yml 
- name: AstorBond.com
      url: https://www.astorbond.com/
      img: 
      twitter: AstorBond
      facebook: astorbond
      email_address: info@astorbond.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to AstorBond.com](https://www.astorbond.com/)
If needed, try the twitter handles profile image: [twitter.com/AstorBond](https://twitter.com/AstorBond)
If needed, try the facebook handles profile image: [fb.com/astorbond](https://fb.com/astorbond)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
