### ISSUE TITLE
Add 'Street Cuts' to the 'Art' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#598]
Requesting to add 'Street Cuts' to the 'Art' category. 

Details follow: 
```yml 
- name: Street Cuts
      url: https://streetcuts.co/collections/street-cuts-stickers
      img: 
      facebook: streetcutsapp
      email_address: jeff@streetcuts.co
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://streetcuts.co/pages/press
```

Resources for adding this merchant:
[Link to Street Cuts](https://streetcuts.co/collections/street-cuts-stickers)
If needed, try the facebook handles profile image: [fb.com/streetcutsapp/](https://fb.com/streetcutsapp/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
