### ISSUE TITLE
Add 'Mermaid Perfume' to the 'Beauty, Hair Care, Perfumery' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#599]
Requesting to add 'Mermaid Perfume' to the 'Beauty, Hair Care, Perfumery' category. 

Details follow: 
```yml 
- name: Mermaid Perfume
      url: https://mermaidperfume.com/
      img: 
      twitter: mermaidperfume
      facebook: shopmermaidperfume
      email_address: info@mermaidperfume.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://mermaidperfume.com/
```

Resources for adding this merchant:
[Link to Mermaid Perfume](https://mermaidperfume.com/)
If needed, try the twitter handles profile image: [twitter.com/mermaidperfume](https://twitter.com/mermaidperfume)
If needed, try the facebook handles profile image: [fb.com/shopmermaidperfume](https://fb.com/shopmermaidperfume)

- [x] Verify site is legitimate and safe to list.
- [x] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [x] Assign to yourself when you begin work.
- [x] Download and resize the image and put it into the proper img folder.
- [x] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
