### ISSUE TITLE
Add 'Sandra Carroll' to the 'https://bit.ly/March1App#3duak' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#600]
Requesting to add 'Sandra Carroll' to the 'https://bit.ly/March1App#3duak' category. 

Details follow: 
```yml 
- name: Sandra Carroll
      url: https://bit.ly/March1App#3duak
      img: 
      twitter: https://bit.ly/March1App#3duak
      email_address: Sandraleanncarroll@gmail.com
      country: US
      city: visalia
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Sandra Carroll](https://bit.ly/March1App#3duak)
If needed, try the twitter handles profile image: [twitter.com/https://bit.ly/March1App#3duak](https://twitter.com/https://bit.ly/March1App#3duak)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
