### ISSUE TITLE
Add 'City Lounge' to the 'Bar' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#601]
Requesting to add 'City Lounge' to the 'Bar' category. 

Details follow: 
```yml 
- name: City Lounge
      url: http://www.ourcitylounge.com/
      img: 
      facebook: CityLoungeCudahy
      email_address: info@ourcitylounge.com
      region: na
      country: US
      city: Cudahy
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to City Lounge](http://www.ourcitylounge.com/)
If needed, try the facebook handles profile image: [fb.com/CityLoungeCudahy/](https://fb.com/CityLoungeCudahy/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
