### ISSUE TITLE
Add 'Fishmonger' to the 'Software' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#609]
Requesting to add 'Fishmonger' to the 'Software' category. 

Details follow: 
```yml 
- name: Fishmonger
      url: https://wowfishmonger.weebly.com/
      img: 
      twitter: WoW_Fishmonger
      email_address: wowfishmonger@yahoo.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Fishmonger](https://wowfishmonger.weebly.com/)
If needed, try the twitter handles profile image: [twitter.com/WoW_Fishmonger](https://twitter.com/WoW_Fishmonger)

- [x] Verify site is legitimate and safe to list.
- [x] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [x] Assign to yourself when you begin work.
- [x] Download and resize the image and put it into the proper img folder.
- [x] Add listing alphabetically to proper .yml file.
- [x] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
