### ISSUE TITLE
Add 'TekkFolio' to the 'Domains' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#610]
Requesting to add 'TekkFolio' to the 'Domains' category. 

Details follow: 
```yml 
- name: TekkFolio
      url: https://tekkfolio.com/
      img: 
      twitter: Blockchain_Name
      email_address: admin@tekkfolio.com
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to TekkFolio](https://tekkfolio.com/)
If needed, try the twitter handles profile image: [twitter.com/Blockchain_Name](https://twitter.com/Blockchain_Name)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
