### ISSUE TITLE
Add '9figures' to the 'General retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#611]
Requesting to add '9figures' to the 'General retail' category. 

Details follow: 
```yml 
- name: 9figures
      url: https://9figures.co.uk/
      img: 
      facebook: 9figuresuk
      email_address: 9figurescompany@gmail.com
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://9figures.co.uk/blogs/news/accepting-cryptocurrency-1
```

Resources for adding this merchant:
[Link to 9figures](https://9figures.co.uk/)
If needed, try the facebook handles profile image: [fb.com/9figuresuk](https://fb.com/9figuresuk)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
