### ISSUE TITLE
Add 'eGifter' to the 'Giftcards' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#612]
Requesting to add 'eGifter' to the 'Giftcards' category. 

Details follow: 
```yml 
- name: eGifter
      url: https://www.egifter.com
      img: 
      twitter: @eGifter
      email_address: aron@thebitcoincash.fund
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to eGifter](https://www.egifter.com)
If needed, try the twitter handles profile image: [twitter.com/@eGifter](https://twitter.com/@eGifter)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
