### ISSUE TITLE
Add 'VapeClubMY' to the 'Vaping' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#614]
Requesting to add 'VapeClubMY' to the 'Vaping' category. 

Details follow: 
```yml 
- name: VapeClubMY
      url: https://vapeclubmy.com
      img: 
      twitter: vapeclubmy
      facebook: vapeclubmy
      email_address: hello@vapeclubmy.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://vapeclubmy.com/blogs/features/vape-club-supports-cryptocurrency-payments-via-coinbase-commerce
```

Resources for adding this merchant:
[Link to VapeClubMY](https://vapeclubmy.com)
If needed, try the twitter handles profile image: [twitter.com/vapeclubmy](https://twitter.com/vapeclubmy)
If needed, try the facebook handles profile image: [fb.com/vapeclubmy](https://fb.com/vapeclubmy)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
