### ISSUE TITLE
Add '8Bet Crypto Lottery' to the 'Lottery' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#616]
Requesting to add '8Bet Crypto Lottery' to the 'Lottery' category. 

Details follow: 
```yml 
- name: 8Bet Crypto Lottery
      url: https://8bet.io
      img: 
      email_address: hello@8bet.io
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/8Bet/
```

Resources for adding this merchant:
[Link to 8Bet Crypto Lottery](https://8bet.io/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
