### ISSUE TITLE
Add 'Carbon Wallet ' to the 'Wallet ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#618]
Requesting to add 'Carbon Wallet ' to the 'Wallet ' category. 

Details follow: 
```yml 
- name: Carbon Wallet 
      url: https://carbonwallet.com/
      img: 
      twitter: Carbon_wallet
      email_address: john@carbonwallet.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/7vg4is/carbon_wallet_now_live_with_support_for_bch/
```

Resources for adding this merchant:
[Link to Carbon Wallet ](https://carbonwallet.com/)
If needed, try the twitter handles profile image: [twitter.com/Carbon_wallet](https://twitter.com/Carbon_wallet)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
