### ISSUE TITLE
Add 'Adultiful' to the 'Adult' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#619]
Requesting to add 'Adultiful' to the 'Adult' category. 

Details follow: 
```yml 
- name: Adultiful
      url: https://adultiful.ca
      img: 
      twitter: Adultiful
      facebook: Adultiful
      email_address: admin@adultiful.ca
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Adultiful](https://adultiful.ca)
If needed, try the twitter handles profile image: [twitter.com/Adultiful](https://twitter.com/Adultiful)
If needed, try the facebook handles profile image: [fb.com/Adultiful](https://fb.com/Adultiful)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
