### ISSUE TITLE
Add 'Asset Maintenance OU' to the 'Construction' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#620]
Requesting to add 'Asset Maintenance OU' to the 'Construction' category. 

Details follow: 
```yml 
- name: Asset Maintenance OU
      url: https://www.assetmaintenance.ee 
      img: 
      facebook: Asset-Maintenance-1267265646673586
      region: eu
      country: EE
      city: Tallinn
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Asset Maintenance OU](https://www.assetmaintenance.ee )
If needed, try the facebook handles profile image: [fb.com/Asset-Maintenance-1267265646673586](https://fb.com/Asset-Maintenance-1267265646673586)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
