### ISSUE TITLE
Add 'BTC EMPORIUM' to the 'Apparel, gaming, stickers. ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#621]
Requesting to add 'BTC EMPORIUM' to the 'Apparel, gaming, stickers. ' category. 

Details follow: 
```yml 
- name: BTC EMPORIUM
      url: https://btcemporium.store
      img: 
      twitter: BTC_Emporium
      email_address: btcemporium@protonmail.com
      country: US
      city: No
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/BTC_Emporium/status/971609628319547394
```

Resources for adding this merchant:
[Link to BTC EMPORIUM](https://btcemporium.store)
If needed, try the twitter handles profile image: [twitter.com/BTC_Emporium](https://twitter.com/BTC_Emporium)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
