### ISSUE TITLE
Add 'AQi Kaleidoscopes' to the 'Video Clips, Images & eBooks' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#622]
Requesting to add 'AQi Kaleidoscopes' to the 'Video Clips, Images & eBooks' category. 

Details follow: 
```yml 
- name: AQi Kaleidoscopes
      url: https://www.awarenessquizzes.com/online-store
      img: 
      facebook: AQiKaleidoscopes
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to AQi Kaleidoscopes](https://www.awarenessquizzes.com/online-store)
If needed, try the facebook handles profile image: [fb.com/AQiKaleidoscopes/](https://fb.com/AQiKaleidoscopes/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
