### ISSUE TITLE
Add 'KaffeBox ' to the 'Food / online web store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#623]
Requesting to add 'KaffeBox ' to the 'Food / online web store' category. 

Details follow: 
```yml 
- name: KaffeBox 
      url: https://www.kaffebox.no
      img: 
      twitter: KaffeBox
      facebook: KaffeBox
      email_address: post@kaffebox.no
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to KaffeBox ](https://www.kaffebox.no)
If needed, try the twitter handles profile image: [twitter.com/KaffeBox](https://twitter.com/KaffeBox)
If needed, try the facebook handles profile image: [fb.com/KaffeBox](https://fb.com/KaffeBox)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
