### ISSUE TITLE
Add 'Digital Keys' to the 'Crypto-service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#628]
Requesting to add 'Digital Keys' to the 'Crypto-service' category. 

Details follow: 
```yml 
- name: Digital Keys
      url: http://digitalkeys.biz/
      img: 
      email_address: digitalkeysshop@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Digital Keys](http://digitalkeys.biz/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
