### ISSUE TITLE
Add 'Mobile Vikings' to the 'Utilities' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#631]
Requesting to add 'Mobile Vikings' to the 'Utilities' category. 

Details follow: 
```yml 
- name: Mobile Vikings
      url: https://mobilevikings.be/en/v2/
      img: 
      twitter: mobilevikingsBE
      facebook: mobilevikings
      email_address: info@mobilevikings.be
      region: eu
      country: BE
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Mobile Vikings](https://mobilevikings.be/en/v2/)
If needed, try the twitter handles profile image: [twitter.com/mobilevikingsBE](https://twitter.com/mobilevikingsBE)
If needed, try the facebook handles profile image: [fb.com/mobilevikings](https://fb.com/mobilevikings)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
