### ISSUE TITLE
Add 'Usenet Bucket' to the 'Services? VPS?' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#632]
Requesting to add 'Usenet Bucket' to the 'Services? VPS?' category. 

Details follow: 
```yml 
- name: Usenet Bucket
      url: https://www.usenetbucket.com/en/
      img: 
      twitter: UsenetBucket
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Usenet Bucket](http://t.co/zF9unElAWM)
If needed, try the twitter handles profile image: [twitter.com/UsenetBucket](https://twitter.com/UsenetBucket)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
