### ISSUE TITLE
Add 'Takeaway' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#633]
Requesting to add 'Takeaway' to the 'Food' category. 

Details follow: 
```yml 
- name: Takeaway
      url: https://www.takeaway.com/
      img: 
      twitter: takeaway
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Takeaway](https://www.takeaway.com/)
If needed, try the twitter handles profile image: [twitter.com/takeaway](https://twitter.com/takeaway)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
