### ISSUE TITLE
Add 'pyxpub.io' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#634]
Requesting to add 'pyxpub.io' to the 'Payments' category. 

Details follow: 
```yml 
- name: pyxpub.io
      url: https://pyxpub.io/
      img: 
      twitter: pyxpub
      email_address: info@pyxpub.io
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to pyxpub.io](https://pyxpub.io/)
If needed, try the twitter handles profile image: [twitter.com/pyxpub](https://twitter.com/pyxpub)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
