### ISSUE TITLE
Add 'NForce' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#635]
Requesting to add 'NForce' to the 'Hosting' category. 

Details follow: 
```yml 
- name: NForce
      url: https://nforce.com
      img: 
      facebook: NFOrceInternetServices
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://nforce.com/news/item/67/Bitcoin-Cash-payments
```

Resources for adding this merchant:
[Link to NForce](https://nforce.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
