### ISSUE TITLE
Add 'cryptomined.com' to the 'computer hardware' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#636]
Requesting to add 'cryptomined.com' to the 'computer hardware' category. 

Details follow: 
```yml 
- name: cryptomined.com
      url: https://cryptomined.com
      img: 
      twitter: CryptominedCom
      email_address: cryptomined@cryptomined.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to cryptomined.com](https://cryptomined.com)
If needed, try the twitter handles profile image: [twitter.com/CryptominedCom](https://twitter.com/CryptominedCom)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
