### ISSUE TITLE
Add 'CJS CD Keys' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#637]
Requesting to add 'CJS CD Keys' to the 'Gaming' category. 

Details follow: 
```yml 
- name: CJS CD Keys
      url: https://www.cjs-cdkeys.com
      img: 
      twitter: CJS_CD_Keys
      facebook: CJSCDKEYS
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: No
```

Resources for adding this merchant:
[Link to CJS CD Keys](https://www.cjs-cdkeys.com)
If needed, try the twitter handles profile image: [twitter.com/CJS_CD_Keys](https://twitter.com/CJS_CD_Keys)
If needed, try the facebook handles profile image: [fb.com/CJSCDKEYS](https://fb.com/CJSCDKEYS)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
