### ISSUE TITLE
Add 'Thuisbezorgd.nl' to the 'Food (Order food for delivery)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#639]
Requesting to add 'Thuisbezorgd.nl' to the 'Food (Order food for delivery)' category. 

Details follow: 
```yml 
- name: Thuisbezorgd.nl
      url: https://www.thuisbezorgd.nl
      img: 
      twitter: thuisbezorgd
      facebook: thuisbezorgd
      region: eu
      country: NL
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.thuisbezorgd.nl/en/customerservice-consumer-topic-payment?fid=371#cs_item_371
```

Resources for adding this merchant:
[Link to Thuisbezorgd.nl](https://www.thuisbezorgd.nl)
If needed, try the twitter handles profile image: [twitter.com/thuisbezorgd](https://twitter.com/thuisbezorgd)
If needed, try the facebook handles profile image: [fb.com/thuisbezorgd](https://fb.com/thuisbezorgd)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
