### ISSUE TITLE
Add 'Lieferando.de' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#640]
Requesting to add 'Lieferando.de' to the 'Food' category. 

Details follow: 
```yml 
- name: Lieferando.de
      url: https://www.lieferando.de
      img: 
      twitter: lieferando
      facebook: https://www.facebook.com/lieferando
      region: eu
      country: DE
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.lieferando.de/en/customerservice-consumer-topic-payment?fid=831#cs_item_831
```

Resources for adding this merchant:
[Link to Lieferando.de](https://www.lieferando.de)
If needed, try the twitter handles profile image: [twitter.com/lieferando](https://twitter.com/lieferando)
If needed, try the facebook handles profile image: [fb.com/https://www.facebook.com/lieferando](https://fb.com/https://www.facebook.com/lieferando)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
