### ISSUE TITLE
Add 'Giftoff' to the 'Gift Cards' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#642]
Requesting to add 'Giftoff' to the 'Gift Cards' category. 

Details follow: 
```yml 
- name: Giftoff
      url: https://www.giftoff.com
      img: 
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Giftoff](https://www.giftoff.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
