### ISSUE TITLE
Add 'Lebanon Merch' to the 'Sweets ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#643]
Requesting to add 'Lebanon Merch' to the 'Sweets ' category. 

Details follow: 
```yml 
- name: Lebanon Merch
      url: https://www.lebanonmerch.com/
      img: 
      facebook: LebanonMerch
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/836dhi/lebanon_merch_enabled_bitcoin_payment_via_bitpay/dvhfnbh/?context=3
```

Resources for adding this merchant:
[Link to Lebanon Merch](https://www.lebanonmerch.com/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
