### ISSUE TITLE
Add 'lieferservice.at' to the 'Food delivery' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#644]
Requesting to add 'lieferservice.at' to the 'Food delivery' category. 

Details follow: 
```yml 
- name: lieferservice.at
      url: https://www.lieferservice.at/
      img: 
      region: eu
      country: AT
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to lieferservice.at](https://www.lieferservice.at/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
