### ISSUE TITLE
Add 'Teasenz' to the 'Food ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#645]
Requesting to add 'Teasenz' to the 'Food ' category. 

Details follow: 
```yml 
- name: Teasenz
      url: https://www.teasenz.com
      img: 
      twitter: teasenz
      facebook: Teasenz
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Teasenz](https://www.teasenz.com)
If needed, try the twitter handles profile image: [twitter.com/teasenz](https://twitter.com/teasenz)
If needed, try the facebook handles profile image: [fb.com/Teasenz/](https://fb.com/Teasenz/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
