### ISSUE TITLE
Add 'Sync' to the 'Backup and Sync' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#646]
Requesting to add 'Sync' to the 'Backup and Sync' category. 

Details follow: 
```yml 
- name: Sync
      url: https://sync.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Sync](https://sync.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
