### ISSUE TITLE
Add 'Brutal (styletokill)' to the 'Clothing Store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#649]
Requesting to add 'Brutal (styletokill)' to the 'Clothing Store' category. 

Details follow: 
```yml 
- name: Brutal (styletokill)
      url: https://www.facebook.com/styletokill/
      img: 
      twitter: styletokillx
      facebook: styletokill
      email_address: styletokill@icloud.com
      region: eu
      city: Shumen
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Brutal (styletokill)](https://www.facebook.com/styletokill/)
If needed, try the twitter handles profile image: [twitter.com/styletokillx](https://twitter.com/styletokillx)
If needed, try the facebook handles profile image: [fb.com/styletokill/](https://fb.com/styletokill/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
