### ISSUE TITLE
Add 'Webhallen' to the 'Games and Computer parts' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#651]
Requesting to add 'Webhallen' to the 'Games and Computer parts' category. 

Details follow: 
```yml 
- name: Webhallen
      url: https://webhallen.com
      img: 
      twitter: webhallen
      region: eu
      country: SE
      city: No
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Webhallen](https://webhallen.com)
If needed, try the twitter handles profile image: [twitter.com/webhallen](https://twitter.com/webhallen)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
