### ISSUE TITLE
Add 'Pyszne.pl' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#657]
Requesting to add 'Pyszne.pl' to the 'Food' category. 

Details follow: 
```yml 
- name: Pyszne.pl
      url: https://pyszne.pl
      img: 
      twitter: pysznepl
      region: eu
      country: PL
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Pyszne.pl](https://pyszne.pl)
If needed, try the twitter handles profile image: [twitter.com/pysznepl](https://twitter.com/pysznepl)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
