### ISSUE TITLE
Add 'BitInDigi' to the 'Computer & smartphones' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#658]
Requesting to add 'BitInDigi' to the 'Computer & smartphones' category. 

Details follow: 
```yml 
- name: BitInDigi
      url: https://bitindigi.com
      img: 
      twitter: Jbitindigi
      email_address: john@bitindigi.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to BitInDigi](https://bitindigi.com)
If needed, try the twitter handles profile image: [twitter.com/Jbitindigi](https://twitter.com/Jbitindigi)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
