### ISSUE TITLE
Add 'Lieferando' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#660]
Requesting to add 'Lieferando' to the 'Food' category. 

Details follow: 
```yml 
- name: Lieferando
      url: https://www.lieferando.de/
      img: 
      twitter: lieferando
      facebook: lieferando
      email_address:  info@lieferando.de 
      region: eu
      country: DE
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Lieferando](https://www.lieferando.de/)
If needed, try the twitter handles profile image: [twitter.com/lieferando](https://twitter.com/lieferando)
If needed, try the facebook handles profile image: [fb.com/lieferando](https://fb.com/lieferando)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
