### ISSUE TITLE
Add 'Tasteless' to the 'Adult' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#663]
Requesting to add 'Tasteless' to the 'Adult' category. 

Details follow: 
```yml 
- name: Tasteless
      url: https://tasteless.io
      img: 
      twitter: shoptasteless
      email_address: help@tasteless.io
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/btc/comments/7geqa8/bitcoinsextoys_accepts_bitcoin_cash_find/
```

Resources for adding this merchant:
[Link to Tasteless](https://tasteless.io)
If needed, try the twitter handles profile image: [twitter.com/shoptasteless](https://twitter.com/shoptasteless)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
