### ISSUE TITLE
Add 'Transparent Labs' to the 'Health' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#664]
Requesting to add 'Transparent Labs' to the 'Health ' category. 

Details follow: 
```yml 
- name: Transparent Labs
      url: https://www.transparentlabs.com/
      img: 
      facebook: transparentlabs
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Transparent Labs](https://www.transparentlabs.com/)
If needed, try the facebook handles profile image: [fb.com/transparentlabs](https://fb.com/transparentlabs)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
