### ISSUE TITLE
Add 'Newegg.com' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#665]
Requesting to add 'Newegg.com' to the 'Retail' category. 

Details follow: 
```yml 
- name: Newegg.com
      url: https://www.newegg.com/
      img: 
      twitter: Newegg
      facebook: Newegg
      email_address: info@newegg.com
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Newegg.com](https://www.newegg.com/)
If needed, try the twitter handles profile image: [twitter.com/Newegg](https://twitter.com/Newegg)
If needed, try the facebook handles profile image: [fb.com/Newegg](https://fb.com/Newegg)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
