### ISSUE TITLE
Add 'eGifter.com' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#666]
Requesting to add 'eGifter.com' to the 'Retail' category. 

Details follow: 
```yml 
- name: eGifter.com
      url: https://www.egifter.com
      img: 
      twitter: eGifter
      facebook: eGifter
      email_address: partnerships@eGifter.com
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to eGifter.com](https://www.egifter.com)
If needed, try the twitter handles profile image: [twitter.com/eGifter](https://twitter.com/eGifter)
If needed, try the facebook handles profile image: [fb.com/eGifter](https://fb.com/eGifter)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
