### ISSUE TITLE
Add 'Liberty VPS' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#667]
Requesting to add 'Liberty VPS' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: Liberty VPS
      url: https://libertyvps.net/
      img: 
      twitter: libertyvps
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Liberty VPS](https://libertyvps.net/)
If needed, try the twitter handles profile image: [twitter.com/libertyvps](https://twitter.com/libertyvps)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
