### ISSUE TITLE
Add 'Zion VPS' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#668]
Requesting to add 'Zion VPS' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: Zion VPS
      url: https://zionvps.com/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Zion VPS](https://zionvps.com/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
