### ISSUE TITLE
Add 'Laptop Power Bank' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#669]
Requesting to add 'Laptop Power Bank' to the 'Retail' category. 

Details follow: 
```yml 
- name: Laptop Power Bank
      url: https://laptoppowerbank.com/
      img: 
      twitter: Mobisunenergy
      facebook: mobisunenergy
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Laptop Power Bank](https://laptoppowerbank.com/)
If needed, try the twitter handles profile image: [twitter.com/Mobisunenergy](https://twitter.com/Mobisunenergy)
If needed, try the facebook handles profile image: [fb.com/mobisunenergy](https://fb.com/mobisunenergy)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
