### ISSUE TITLE
Add 'Mt.BetMore' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#670]
Requesting to add 'Mt.BetMore' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Mt.BetMore
      url: https://mtbetmore.com
      img: 
      email_address: contact@mtbetmore.com
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Mt.BetMore](https://mtbetmore.com)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
