### ISSUE TITLE
Add 'Vapour Depot' to the 'Tobacconist' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#672]
Requesting to add 'Vapour Depot' to the 'Tobacconist' category. 

Details follow: 
```yml 
- name: Vapour Depot
      url: https://vapourdepot.com
      img: 
      twitter: vapourdepot
      facebook: vapourdepot
      email_address: social@vapourdepot.com
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Vapour Depot](https://vapourdepot.com)
If needed, try the twitter handles profile image: [twitter.com/vapourdepot](https://twitter.com/vapourdepot)
If needed, try the facebook handles profile image: [fb.com/vapourdepot](https://fb.com/vapourdepot)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
