### ISSUE TITLE
Add 'Performance-PCs' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#673]
Requesting to add 'Performance-PCs' to the 'Retail' category. 

Details follow: 
```yml 
- name: Performance-PCs
      url: http://www.performance-pcs.com
      img: 
      facebook: PerformancePCs
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions:
        text: "Select Bitcoin as payment option during checkout to be presented with the option of Bitcoin and Bitcoin Cash"
```

Resources for adding this merchant:
[Link to Performance-PCs](http://www.performance-pcs.com)
If needed, try the facebook handles profile image: [fb.com/PerformancePCs](https://fb.com/PerformancePCs)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
