### ISSUE TITLE
Add 'HandCash' to the 'Wallets' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#674]
Requesting to add 'HandCash' to the 'Wallets' category. 

Details follow: 
```yml 
- name: HandCash
      url: http://www.handcash.io/
      img: 
      twitter: handcashapp
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to HandCash](http://www.handcash.io/)
If needed, try the twitter handles profile image: [twitter.com/handcashapp](https://twitter.com/handcashapp)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
