### ISSUE TITLE
Add 'eatBCH' to the 'human needs' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#675]
Requesting to add 'eatBCH' to the 'human needs' category. 

Details follow: 
```yml 
- name: eatBCH
      url: https://twitter.com/EatBCH
      img: 
      twitter: eatBCH
      email_address: vzlan@protonmail.com
      region: sa
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to eatBCH](https://twitter.com/EatBCH)
If needed, try the twitter handles profile image: [twitter.com/eatBCH](https://twitter.com/eatBCH)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
