### ISSUE TITLE
Add 'Liberty Store' to the 'Clothing/Merchandise/Propaganda' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#676]
Requesting to add 'Liberty Store' to the 'Clothing/Merchandise/Propaganda' category. 

Details follow: 
```yml 
- name: Liberty Store
      url: https://www.libertystore.de
      img: 
      twitter: LibertyStore_de
      facebook: Libertarismus
      email_address: janschmitz@libertystore.de
      region: eu
      country: DE
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Liberty Store](https://www.libertystore.de)
If needed, try the twitter handles profile image: [twitter.com/LibertyStore_de](https://twitter.com/LibertyStore_de)
If needed, try the facebook handles profile image: [fb.com/Libertarismus](https://fb.com/Libertarismus)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
