### ISSUE TITLE
Add 'computerbase.de' to the 'Magazine' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#677]
Requesting to add 'computerbase.de' to the 'Magazine' category. 

Details follow: 
```yml 
- name: computerbase.de
      url: https://www.computerbase.de/
      img: 
      twitter: computerbase
      facebook: computerbase
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to computerbase.de](https://www.computerbase.de/)
If needed, try the twitter handles profile image: [twitter.com/computerbase](https://twitter.com/computerbase)
If needed, try the facebook handles profile image: [fb.com/computerbase/](https://fb.com/computerbase/)

- [ ] Verify site is legitimate and safe to list.
- [x] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
