### ISSUE TITLE
Add 'Destinia' to the 'Travel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#678]
Requesting to add 'Destinia' to the 'Travel' category. 

Details follow: 
```yml 
- name: Destinia
      url: https://destinia.com/
      img: 
      twitter: Destinia
      facebook: https://www.facebook.com/Destinia.com/
      email_address: admincont@destinia.com
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://twitter.com/Destinia/status/972053118555967488
```

Resources for adding this merchant:
[Link to Destinia](https://destinia.com/)
If needed, try the twitter handles profile image: [twitter.com/Destinia](https://twitter.com/Destinia)
If needed, try the facebook handles profile image: [fb.com/https://www.facebook.com/Destinia.com/](https://fb.com/https://www.facebook.com/Destinia.com/)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
