### ISSUE TITLE
Add 'Storm & Leif' to the 'Health/Beauty' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#679]
Requesting to add 'Storm & Leif' to the 'Deodorants' category. 

Details follow: 
```yml 
- name: Storm & Leif
      url: https://www.stormandleif.com/
      img: 
      twitter: stormandleif
      facebook: stormandleif
      email_address: info@stormandleif.com
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.stormandleif.com/blogs/journal/the-all-natural-deodorant-thats-now-cryptocurrency-friendly
```

Resources for adding this merchant:
[Link to Storm & Leif](https://www.stormandleif.com/)
If needed, try the twitter handles profile image: [twitter.com/stormandleif](https://twitter.com/stormandleif)
If needed, try the facebook handles profile image: [fb.com/stormandleif](https://fb.com/stormandleif)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
