### ISSUE TITLE
 Add 'MMOGA' to the 'Gaming' category

### ISSUE THREAD

**Issue by MaxXor** [acceptbitcoincash/acceptbitcoincash#680]
Requesting to add MMOGA to the Gaming category. Details follow:

```yml

- name: MMOGA
  url: https://www.mmoga.com/
  img: https://i.imgur.com/tqPqPBV.png
  twitter: mmoga_ltd
  facebook: MMOGA
  region: EU
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://www.mmoga.com/payment_methods/Bitcoin-and-Altcoins.html
```
