### ISSUE TITLE
Add 'Wild Mushroom Hunting' to the 'Forums' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#681]
Requesting to add 'Wild Mushroom Hunting' to the 'Forums' category. 

Details follow: 
```yml 
- name: Wild Mushroom Hunting
      url: https://wildmushroomhunting.org
      img: 
      email_address: jason@webunraveling.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://wildmushroomhunting.org/index.php?/topic/3724-donations-via-bitcoin-cash-and-ethereum/
```

Resources for adding this merchant:
[Link to Wild Mushroom Hunting](https://wildmushroomhunting.org)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
