### ISSUE TITLE
Add 'CoinEx' to the 'Exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#683]
Requesting to add 'CoinEx' to the 'Exchange' category. 

Details follow: 
```yml 
- name: CoinEx
      url: https://www.coinex.com
      img: 
      twitter: coinexcom
      facebook: TheCoinEx
      email_address: support@coinex.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/coinexcom/status/940422816754671617
```

Resources for adding this merchant:
[Link to CoinEx](https://www.coinex.com)
If needed, try the twitter handles profile image: [twitter.com/coinexcom](https://twitter.com/coinexcom)
If needed, try the facebook handles profile image: [fb.com/TheCoinEx](https://fb.com/TheCoinEx)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
