### ISSUE TITLE
Add 'The Cloud Gallery - Artist Tony Schaefer' to the 'paintings, drawings, artwork and more' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#684]
Requesting to add 'The Cloud Gallery - Artist Tony Schaefer' to the 'paintings, drawings, artwork and more' category. 

Details follow: 
```yml 
- name: The Cloud Gallery - Artist Tony Schaefer
      url: http://thecloudgallery.org
      img: 
      twitter: thecloudgallery
      email_address: curator@thecloudgallery.org
      country: AU
      city: no
      bch: Yes
      btc: No
      othercrypto: No
      doc: http://thecloudgallery.org
```

Resources for adding this merchant:
[Link to The Cloud Gallery - Artist Tony Schaefer](http://thecloudgallery.org)
If needed, try the twitter handles profile image: [twitter.com/thecloudgallery](https://twitter.com/thecloudgallery)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
