### ISSUE TITLE
Add 'Rapid Car Key' to the 'Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#686]
Requesting to add 'Rapid Car Key' to the 'Services' category. 

Details follow: 
```yml 
- name: Rapid Car Key
      url: https://www.rapidcarkey.com/
      img: 
      facebook: RapidCarKey
      email_address: rapidcarkey@gmail.com
      region: na
      country: US
      city: Tucson
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Rapid Car Key](https://www.rapidcarkey.com/)
If needed, try the facebook handles profile image: [fb.com/RapidCarKey](https://fb.com/RapidCarKey)

- [ ] Verify site is legitimate and safe to list.
- [ ] Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- [ ] Assign to yourself when you begin work.
- [ ] Download and resize the image and put it into the proper img folder.
- [ ] Add listing alphabetically to proper .yml file.
- [ ] Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
