### ISSUE TITLE
Add 'Depot.co.ke' to the 'Retail and Wholesale' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#689]
Requesting to add 'Depot.co.ke' to the 'Retail and Wholesale' category. 

Details follow: 
```yml 
- name: Depot.co.ke
      url: https://www.depot.co.ke
      img: 
      twitter: depot254
      facebook: depotke
      email_address: depotke@gmail.com
      region: af
      country: KE
      city: Nairobi
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Depot.co.ke](https://www.depot.co.ke)
If needed, try the twitter handles profile image: [twitter.com/depot254](https://twitter.com/depot254)
If needed, try the facebook handles profile image: [fb.com/depotke](https://fb.com/depotke)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
