### ISSUE TITLE
Add 'Newxly' to the 'Online Store' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#690]
Requesting to add '  Newxly' to the 'Online Store' category. 

Details follow: 
```yml 
- name: Newxly
      url: https://www.newxly.com
      img: 
      twitter: NewxlyOfficial
      email_address: social@newxly.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to   Newxly](https://www.newxly.com)
If needed, try the twitter handles profile image: [twitter.com/NewxlyOfficial](https://twitter.com/NewxlyOfficial)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
