### ISSUE TITLE
Add 'Pi Supply' to the 'Electronics' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#691]
Requesting to add 'Pi Supply' to the 'Electronics' category. 

Details follow: 
```yml 
- name: Pi Supply
      url: https://pi-supply.com
      img: 
      twitter: PiSupply
      facebook: PiSupply/
      email_address: john@pi-supply.com
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://twitter.com/PiSupply/status/972228324721295360
```

Resources for adding this merchant:
[Link to Pi Supply](https://pi-supply.com)
If needed, try the twitter handles profile image: [twitter.com/PiSupply](https://twitter.com/PiSupply)
If needed, try the facebook handles profile image: [fb.com/PiSupply/](https://fb.com/PiSupply/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
