### ISSUE TITLE
Add 'StakeBox' to the 'Electronics' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#692]
Requesting to add 'StakeBox' to the 'Electronics' category. 

Details follow: 
```yml 
- name: StakeBox
      url: https://www.stakebox.org/
      img: 
      twitter: stakebox
      facebook: StakeBox/
      email_address: sales@stakebox.org
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://twitter.com/StakeBox/status/969621404818780166
```

Resources for adding this merchant:
[Link to StakeBox](https://www.stakebox.org/)
If needed, try the twitter handles profile image: [twitter.com/stakebox](https://twitter.com/stakebox)
If needed, try the facebook handles profile image: [fb.com/StakeBox/](https://fb.com/StakeBox/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
