### ISSUE TITLE
Add 'The Craft Revolt' to the 'Art and Craft Classes and Studio' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#695]
Requesting to add 'The Craft Revolt' to the 'Art and Craft Classes and Studio' category. 

Details follow: 
```yml 
- name: The Craft Revolt
      url: https://TheCraftRevolt.com
      img: 
      twitter: thecraftrevolt
      facebook: craftrevolt
      email_address: info@TheCraftRevolt.com
      region: na
      country: US
      city: Tucson, Arizona
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "Simply order classes online. "
```

Resources for adding this merchant:
[Link to The Craft Revolt](https://TheCraftRevolt.com)
If needed, try the twitter handles profile image: [twitter.com/thecraftrevolt](https://twitter.com/thecraftrevolt)
If needed, try the facebook handles profile image: [fb.com/craftrevolt](https://fb.com/craftrevolt)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
