### ISSUE TITLE
Add 'Diamondcard.us' to the 'Communications' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#696]
Requesting to add 'Diamondcard.us' to the 'Communications' category. 

Details follow: 
```yml 
- name: Diamondcard.us
      url: http://www.diamondcard.us/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: I'm a customer and received an email from them on February 24th.  Bitcoin Cash is also listed on their home page.
```

Resources for adding this merchant:
[Link to Diamondcard.us](http://www.diamondcard.us/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
