### ISSUE TITLE
Add 'Caseking.de' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#701]
Requesting to add 'Caseking.de' to the 'Retail' category. 

Details follow: 
```yml 
- name: Caseking.de
      url: https://www.caseking.de
      img: 
      twitter: Caseking
      facebook: caseking
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Caseking.de](https://www.caseking.de)
If needed, try the twitter handles profile image: [twitter.com/Caseking](https://twitter.com/Caseking)
If needed, try the facebook handles profile image: [fb.com/caseking](https://fb.com/caseking)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
