### ISSUE TITLE
Add 'KDE' to the 'Donations - Software' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#702]
Requesting to add 'KDE' to the 'Donations - Software' category. 

Details follow: 
```yml 
- name: KDE
      url: https://www.kde.org/
      img: 
      twitter: kdecommunity
      facebook: kde
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "https://www.kde.org/community/donations/others.php"
```

Resources for adding this merchant:
[Link to KDE](https://www.kde.org/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
