### ISSUE TITLE
Add 'caseking.de' to the 'Retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#703]
Requesting to add 'caseking.de' to the 'Retailer' category. 

Details follow: 
```yml 
- name: caseking.de
      url: https://www.caseking.de
      img: 
      twitter: Caseking
      facebook: caseking
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![caseking.de](https://pbs.twimg.com/profile_images/844830773777596416/TLQCf7CC_400x400.jpg)

[Link to caseking.de](https://www.caseking.de)
If needed, try the twitter handles profile image: [twitter.com/Caseking](https://twitter.com/Caseking)
If needed, try the facebook handles profile image: [fb.com/caseking](https://fb.com/caseking)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
