### ISSUE TITLE
Add 'Hawk Host Inc.' to the 'Hosting / VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#704]
Requesting to add 'Hawk Host Inc.' to the 'Hosting / VPS' category. 

Details follow: 
```yml 
- name: Hawk Host Inc.
      url: https://www.hawkhost.com
      img: 
      twitter: hawkhost
      facebook: hawkhost
      email_address: cody@hawkhost.com
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://twitter.com/HawkHost/status/971888229820616704
      exceptions: 
        text: "Select "Bitcoin" as a payment method and you can pay with Bitcoin Cash or Bitcoin Legacy"
```

Resources for adding this merchant:
Logo Provided:
![Hawk Host Inc.](https://pbs.twimg.com/profile_images/963826048013135872/Dx1wj4t6_400x400.jpg)

[Link to Hawk Host Inc.](https://www.hawkhost.com)
If needed, try the twitter handles profile image: [twitter.com/hawkhost](https://twitter.com/hawkhost)
If needed, try the facebook handles profile image: [fb.com/hawkhost](https://fb.com/hawkhost)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
