### ISSUE TITLE
Add 'Biblioteca de Alejandria - IDVPS' to the 'Donations -> Education' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#705]
Requesting to add 'Biblioteca de Alejandria - IDVPS' to the 'Donations -> Education' category. 

Details follow: 
```yml 
- name: Biblioteca de Alejandria - IDVPS
      url: http://libros-prohibidos8.blogspot.com.es/
      img: 
      email_address: indexprohibido@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Biblioteca de Alejandria - IDVPS](https://prnt.sc/itjknh)

[Link to Biblioteca de Alejandria - IDVPS](http://libros-prohibidos8.blogspot.com.es/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
