### ISSUE TITLE
Add 'JoyStream' to the 'Crypto-Service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#706]
Requesting to add 'JoyStream' to the 'Crypto-Service' category. 

Details follow: 
```yml 
- name: JoyStream
      url: http://joystream.co/
      img: 
      twitter: JoyStreamApp
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![JoyStream](https://i.imgur.com/BvDYR9v.png?1)

[Link to JoyStream](http://joystream.co/)
If needed, try the twitter handles profile image: [twitter.com/JoyStreamApp](https://twitter.com/JoyStreamApp)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
