### ISSUE TITLE
Add 'PiVPS Services' to the 'Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#707]
Requesting to add 'PiVPS Services' to the 'Security' category. 

Details follow: 
```yml 
- name: PiVPS Services
      url: https://pivps.com/
      img: 
      facebook: pivpscom
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to PiVPS Services](https://pivps.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
