### ISSUE TITLE
Add '101 Vape' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#708]
Requesting to add '101 Vape' to the 'Retail' category. 

Details follow: 
```yml 
- name: 101 Vape
      url: https://101vape.com/
      img: 
      twitter: 101vape
      facebook: 101vape
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![101 Vape](https://pbs.twimg.com/profile_images/938847019338145792/pK0RkcI0_400x400.jpg)

[Link to 101 Vape](https://101vape.com/)
If needed, try the twitter handles profile image: [twitter.com/101vape](https://twitter.com/101vape)
If needed, try the facebook handles profile image: [fb.com/101vape](https://fb.com/101vape)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
