### ISSUE TITLE
Add '143VPN' to the 'Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#709]
Requesting to add '143VPN' to the 'Security' category. 

Details follow: 
```yml 
- name: 143VPN
      url: https://143vpn.com
      img: 
      twitter: 143VPN
      facebook: 143VPN
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![143VPN](https://pbs.twimg.com/profile_images/802700253547794432/2ax3oN0l_400x400.jpg)

[Link to 143VPN](https://143vpn.com)
If needed, try the twitter handles profile image: [twitter.com/143VPN](https://twitter.com/143VPN)
If needed, try the facebook handles profile image: [fb.com/143VPN](https://fb.com/143VPN)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
