### ISSUE TITLE
Add 'UTop' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#710]
Requesting to add 'UTop' to the 'Hosting' category. 

Details follow: 
```yml 
- name: UTop
      url: http://utop.us/
      img: 
      twitter: utopus2
      facebook: www.uTop.us
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![UTop](https://pbs.twimg.com/profile_images/635069309312614401/4efACuhI_400x400.png)

[Link to UTop](http://utop.us/)
If needed, try the twitter handles profile image: [twitter.com/utopus2](https://twitter.com/utopus2)
If needed, try the facebook handles profile image: [fb.com/www.uTop.us](https://fb.com/www.uTop.us)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
