### ISSUE TITLE
Add 'Salts Worldwide' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#711]
Requesting to add 'Salts Worldwide' to the 'Food' category. 

Details follow: 
```yml 
- name: Salts Worldwide
      url: https://saltsworldwide.com
      img: 
      twitter: SaltsWorldwide
      facebook: saltsworldwide
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Salts Worldwide](https://pbs.twimg.com/profile_images/609202892839325696/xnxGo3vg_400x400.png)

[Link to Salts Worldwide](https://saltsworldwide.com)
If needed, try the twitter handles profile image: [twitter.com/SaltsWorldwide](https://twitter.com/SaltsWorldwide)
If needed, try the facebook handles profile image: [fb.com/saltsworldwide](https://fb.com/saltsworldwide)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
