### ISSUE TITLE
Add 'Host Havoc' to the 'Hosting or Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#712]
Requesting to add 'Host Havoc' to the 'Hosting or Gaming' category. 

Details follow: 
```yml 
- name: Host Havoc
      url: https://hosthavoc.com/
      img: 
      twitter: hosthavoc
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Host Havoc](https://pbs.twimg.com/profile_images/768582195309121538/FFBhtE6J_400x400.jpg)

[Link to Host Havoc](https://hosthavoc.com/)
If needed, try the twitter handles profile image: [twitter.com/hosthavoc](https://twitter.com/hosthavoc)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
