### ISSUE TITLE
Add 'Pex Peppers' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#713]
Requesting to add 'Pex Peppers' to the 'Food' category. 

Details follow: 
```yml 
- name: Pex Peppers
      url: https://www.pexpeppers.com/
      img: 
      twitter: pexpeppers
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Pex Peppers](https://www.pexpeppers.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
