### ISSUE TITLE
Add 'Shire Soaps' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#714]
Requesting to add 'Shire Soaps' to the 'Retail' category. 

Details follow: 
```yml 
- name: Shire Soaps
      url: http://shiresoaps.com/
      img: 
      twitter: shiresoaps
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Shire Soaps](http://shiresoaps.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
