### ISSUE TITLE
Add 'CoinHost' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#715]
Requesting to add 'CoinHost' to the 'Hosting' category. 

Details follow: 
```yml 
- name: CoinHost
      url: https://www.coinhost.io/
      img: 
      twitter: hostcoin
      facebook: coinhost
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to CoinHost](https://www.coinhost.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
