### ISSUE TITLE
Add 'Hostlic' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#716]
Requesting to add 'Hostlic' to the 'Hosting' category. 

Details follow: 
```yml 
- name: Hostlic
      url: https://www.hostlic.com
      img: 
      facebook: hostlic
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Hostlic](https://i.imgur.com/btCkQMS.png)

[Link to Hostlic](https://www.hostlic.com)
If needed, try the facebook handles profile image: [fb.com/hostlic](https://fb.com/hostlic)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
