### ISSUE TITLE
Add 'Triton Aquariums' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#717]
Requesting to add 'Triton Aquariums' to the 'Retail' category. 

Details follow: 
```yml 
- name: Triton Aquariums
      url: https://www.tritonaquariums.com
      img: 
      twitter: tritonaquariums
      facebook: Triton-Aquariums
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Triton Aquariums](https://pbs.twimg.com/profile_images/773362608984330242/dsiZC5eI_400x400.jpg)

[Link to Triton Aquariums](https://www.tritonaquariums.com)
If needed, try the twitter handles profile image: [twitter.com/tritonaquariums](https://twitter.com/tritonaquariums)
If needed, try the facebook handles profile image: [fb.com/Triton-Aquariums](https://fb.com/Triton-Aquariums)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
