### ISSUE TITLE
Add 'GPS Tracking Made Easy' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#718]
Requesting to add 'GPS Tracking Made Easy' to the 'Retail' category. 

Details follow: 
```yml 
- name: GPS Tracking Made Easy
      url: https://gpstrackingmadeeasy.com/
      img: 
      twitter: GPStme
      facebook: gpstrackingmadeeasy
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![GPS Tracking Made Easy](https://pbs.twimg.com/profile_images/962542803053096960/BJMHGr2t_400x400.jpg)

[Link to GPS Tracking Made Easy](https://gpstrackingmadeeasy.com/)
If needed, try the twitter handles profile image: [twitter.com/GPStme](https://twitter.com/GPStme)
If needed, try the facebook handles profile image: [fb.com/gpstrackingmadeeasy](https://fb.com/gpstrackingmadeeasy)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
