### ISSUE TITLE
Add 'Monster Megs' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#719]
Requesting to add 'Monster Megs' to the 'Hosting' category. 

Details follow: 
```yml 
- name: Monster Megs
      url: https://www.monstermegs.com/
      img: 
      twitter: MonsterMegsHost
      facebook: MonsterMegs
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Monster Megs](https://pbs.twimg.com/profile_images/972567022008758272/SXq6T7x9_400x400.jpg)

[Link to Monster Megs](https://www.monstermegs.com/)
If needed, try the twitter handles profile image: [twitter.com/MonsterMegsHost](https://twitter.com/MonsterMegsHost)
If needed, try the facebook handles profile image: [fb.com/MonsterMegs](https://fb.com/MonsterMegs)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
