### ISSUE TITLE
Add 'Bitit' to the 'Crypto-Exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#720]
Requesting to add 'Bitit' to the 'Crypto-Exchange' category. 

Details follow: 
```yml 
- name: Bitit
      url: https://bitit.io/
      img: 
      twitter: Bitit_Gift
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://support.bitit.io/hc/en-us/articles/360000566429-How-to-buy-Bitcoin-Cash-BCH-on-Bitit-by-credit-card-cash-and-wire-transfer-
```

Resources for adding this merchant:
Logo Provided:
![Bitit](https://i.imgur.com/1Ue4Bpn.jpg?2)

[Link to Bitit](https://bitit.io/)
If needed, try the twitter handles profile image: [twitter.com/Bitit_Gift](https://twitter.com/Bitit_Gift)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
