### ISSUE TITLE
Add 'Tipcrypto' to the 'Stream Donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#721]
Requesting to add 'Tipcrypto' to the 'Stream Donations' category. 

Details follow: 
```yml 
- name: Tipcrypto
      url: https://tipcrypto.net
      img: 
      twitter: tipcryptonet
      facebook: tipcryptonet
      email_address: simonbruchmann@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Tipcrypto](https://tipcrypto.net/favicon.png)

[Link to Tipcrypto](https://tipcrypto.net)
If needed, try the twitter handles profile image: [twitter.com/tipcryptonet](https://twitter.com/tipcryptonet)
If needed, try the facebook handles profile image: [fb.com/tipcryptonet](https://fb.com/tipcryptonet)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
