### ISSUE TITLE
Add 'Webhallen' to the 'retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#722]
Requesting to add 'Webhallen' to the 'retailer' category. 

Details follow: 
```yml 
- name: Webhallen
      url: https://new.webhallen.com/
      img: 
      twitter: webhallen
      facebook: webhallen
      region: eu
      country: SE
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Webhallen](https://pbs.twimg.com/profile_images/1335733540/wh_ic_launcher_512_400x400.png)

[Link to Webhallen](https://new.webhallen.com/)
If needed, try the twitter handles profile image: [twitter.com/webhallen](https://twitter.com/webhallen)
If needed, try the facebook handles profile image: [fb.com/webhallen](https://fb.com/webhallen)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
