### ISSUE TITLE
Add 'OMGSERV' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#723]
Requesting to add 'OMGSERV' to the 'Gaming' category. 

Details follow: 
```yml 
- name: OMGSERV
      url: https://www.omgserv.com
      img: 
      twitter: OMGSERV_COM
      facebook: OMGSERV
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![OMGSERV](https://i.imgur.com/JMYRCPS.jpg?2)

[Link to OMGSERV](https://www.omgserv.com)
If needed, try the twitter handles profile image: [twitter.com/OMGSERV_COM](https://twitter.com/OMGSERV_COM)
If needed, try the facebook handles profile image: [fb.com/OMGSERV](https://fb.com/OMGSERV)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
