### ISSUE TITLE
Add 'Apmex' to the 'Jewels and Precious Metals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#724]
Requesting to add 'Apmex' to the 'Retailer' category. 

Details follow: 
```yml 
- name: Apmex
      url: https://www.apmex.com/
      img: 
      twitter: APMEX
      facebook: APMEX
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Apmex](https://apmex.exceda.com/content/images/content/apmex-blue-logo.png)

[Link to Apmex](https://www.apmex.com/)
If needed, try the twitter handles profile image: [twitter.com/APMEX](https://twitter.com/APMEX)
If needed, try the facebook handles profile image: [fb.com/APMEX](https://fb.com/APMEX)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
