### ISSUE TITLE
Add 'Jewelry Affairs' to the 'precious-metals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#725]
Requesting to add 'Jewelry Affairs' to the 'precious-metals' category. 

Details follow: 
```yml 
- name: Jewelry Affairs
      url: https://www.jewelryaffairs.com/
      img: 
      twitter: JewelryAffairs
      facebook: JewelryAffairs
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Jewelry Affairs](https://i.imgur.com/mUoAypW.jpg?2)

[Link to Jewelry Affairs](https://www.jewelryaffairs.com/)
If needed, try the twitter handles profile image: [twitter.com/JewelryAffairs](https://twitter.com/JewelryAffairs)
If needed, try the facebook handles profile image: [fb.com/JewelryAffairs](https://fb.com/JewelryAffairs)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
