### ISSUE TITLE
Add 'Schiff Gold' to the 'precious-metals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#726]
Requesting to add 'Schiff Gold' to the 'precious-metals' category. 

Details follow: 
```yml 
- name: Schiff Gold
      url: https://schiffgold.com/
      img: 
      twitter: schiffgold
      facebook: schiffgold
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Schiff Gold](https://i.imgur.com/oz4W48N.png?1)

[Link to Schiff Gold](https://schiffgold.com/)
If needed, try the twitter handles profile image: [twitter.com/schiffgold](https://twitter.com/schiffgold)
If needed, try the facebook handles profile image: [fb.com/schiffgold](https://fb.com/schiffgold)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
