### ISSUE TITLE
Add 'GoldSilver' to the 'precious-metals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#727]
Requesting to add 'GoldSilver' to the 'precious-metals' category. 

Details follow: 
```yml 
- name: GoldSilver
      url: https://goldsilver.com/
      img: 
      twitter: GoldSilver_com
      facebook: GoldSilverDotCom
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![GoldSilver](https://i.imgur.com/giNa952.jpg)

[Link to GoldSilver](https://goldsilver.com/)
If needed, try the twitter handles profile image: [twitter.com/GoldSilver_com](https://twitter.com/GoldSilver_com)
If needed, try the facebook handles profile image: [fb.com/GoldSilverDotCom](https://fb.com/GoldSilverDotCom)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
