### ISSUE TITLE
Add 'BitGild' to the 'precious metals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#728]
Requesting to add 'BitGild' to the 'precious metals' category. 

Details follow: 
```yml 
- name: BitGild
      url: https://www.bitgild.com/
      img: 
      twitter: Bitgildcom
      facebook: bitgild
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![BitGild](https://i.imgur.com/n44Ut7x.jpg)

[Link to BitGild](https://www.bitgild.com/)
If needed, try the twitter handles profile image: [twitter.com/Bitgildcom](https://twitter.com/Bitgildcom)
If needed, try the facebook handles profile image: [fb.com/bitgild](https://fb.com/bitgild)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
