### ISSUE TITLE
Add '24k Wholesale Jewelry' to the 'precious metals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#729]
Requesting to add '24k Wholesale Jewelry' to the 'precious metals' category. 

Details follow: 
```yml 
- name: 24k Wholesale Jewelry
      url: http://www.24kwholesalejewelry.com/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![24k Wholesale Jewelry](https://i.imgur.com/bE5ktTN.jpg?2)

[Link to 24k Wholesale Jewelry](http://www.24kwholesalejewelry.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
