### ISSUE TITLE
Add 'Super Byte Hosting' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#730]
Requesting to add 'Super Byte Hosting' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: Super Byte Hosting
      url: https://www.superbytehosting.com/
      img: 
      twitter: superbytehostin
      facebook: superbytehosting
      region: as
      country: IN
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Super Byte Hosting](https://i.imgur.com/VqvlZDE.png?1)

[Link to Super Byte Hosting](https://www.superbytehosting.com/)
If needed, try the twitter handles profile image: [twitter.com/superbytehostin](https://twitter.com/superbytehostin)
If needed, try the facebook handles profile image: [fb.com/superbytehosting](https://fb.com/superbytehosting)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
