### ISSUE TITLE
Add 'Giacobbe and Co' to the 'precious metals/jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#731]
Requesting to add 'Giacobbe and Co' to the 'precious metals/jewelry' category. 

Details follow: 
```yml 
- name: Giacobbe and Co
      url: https://giacobbeandco.com/
      img: 
      twitter: Giacobbeandco
      facebook: GiacobbeandCo
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Giacobbe and Co](https://i.imgur.com/zn9SPwX.jpg?2)

[Link to Giacobbe and Co](https://giacobbeandco.com/)
If needed, try the twitter handles profile image: [twitter.com/Giacobbeandco](https://twitter.com/Giacobbeandco)
If needed, try the facebook handles profile image: [fb.com/GiacobbeandCo](https://fb.com/GiacobbeandCo)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
