### ISSUE TITLE
Add 'Earth VPN' to the 'Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#732]
Requesting to add 'Earth VPN' to the 'Security' category. 

Details follow: 
```yml 
- name: Earth VPN
      url: http://www.earthvpn.com/
      img: 
      twitter: Earthvpn
      facebook: Earthvpn
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to Earth VPN](http://www.earthvpn.com/)
If needed, try the twitter handles profile image: [twitter.com/Earthvpn](https://twitter.com/Earthvpn)
If needed, try the facebook handles profile image: [fb.com/Earthvpn](https://fb.com/Earthvpn)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
