### ISSUE TITLE
Add 'HostWinds' to the 'hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#733]
Requesting to add 'HostWinds' to the 'hosting' category. 

Details follow: 
```yml 
- name: HostWinds
      url: https://www.hostwinds.com
      img: 
      twitter: HostWinds
      facebook: HostWinds
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![HostWinds](https://i.imgur.com/fAt3kUZ.png?1)

[Link to HostWinds](https://www.hostwinds.com)
If needed, try the twitter handles profile image: [twitter.com/HostWinds](https://twitter.com/HostWinds)
If needed, try the facebook handles profile image: [fb.com/HostWinds](https://fb.com/HostWinds)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
