### ISSUE TITLE
Add 'Zomex' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#734]
Requesting to add 'Zomex' to the 'Hosting' category. 

Details follow: 
```yml 
- name: Zomex
      url: https://www.zomex.com
      img: 
      twitter: z0mex
      facebook: zomex
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Zomex](https://i.imgur.com/gxELbGo.jpg?2)

[Link to Zomex](https://www.zomex.com)
If needed, try the twitter handles profile image: [twitter.com/z0mex](https://twitter.com/z0mex)
If needed, try the facebook handles profile image: [fb.com/zomex](https://fb.com/zomex)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
