### ISSUE TITLE
Add 'Get Ballistic' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#735]
Requesting to add 'Get Ballistic' to the 'Retail' category. 

Details follow: 
```yml 
- name: Get Ballistic
      url: http://www.getballistic.com/
      img: 
      twitter: BallisticBoards
      facebook: ballistic.boards
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Get Ballistic](https://i.imgur.com/jha7yWv.jpg?2)

[Link to Get Ballistic](http://www.getballistic.com/)
If needed, try the twitter handles profile image: [twitter.com/BallisticBoards](https://twitter.com/BallisticBoards)
If needed, try the facebook handles profile image: [fb.com/ballistic.boards](https://fb.com/ballistic.boards)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
