### ISSUE TITLE
Add 'European Class Limousine' to the 'Transport' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#736]
Requesting to add 'European Class Limousine' to the 'Transport' category. 

Details follow: 
```yml 
- name: European Class Limousine
      url: http://euclasslimo.com/
      img: 
      twitter: euclasslimo
      facebook: euclasslimo
      region: na
      country: US
      city: Chicago
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![European Class Limousine](https://i.imgur.com/KUItdJ6.jpg?2)

[Link to European Class Limousine](http://euclasslimo.com/)
If needed, try the twitter handles profile image: [twitter.com/euclasslimo](https://twitter.com/euclasslimo)
If needed, try the facebook handles profile image: [fb.com/euclasslimo](https://fb.com/euclasslimo)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
