### ISSUE TITLE
Add 'Underlabs Inc.' to the 'Software Development' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#740]
Requesting to add 'Underlabs Inc.' to the 'Software Development' category. 

Details follow: 
```yml 
- name: Underlabs Inc.
      url: https://underlabs.ca
      img: 
      twitter: underlabs
      email_address: hello@underlabs.ca
      region: na
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://underlabs.ca/smart-contracts.html
      exceptions: 
        text: "Should to get in touch with them on the terms."
```

Resources for adding this merchant:
Logo Provided:
![Underlabs Inc.](https://underlabs.ca/img/underlabs_logo@2x.png)

[Link to Underlabs Inc.](https://underlabs.ca)
If needed, try the twitter handles profile image: [twitter.com/underlabs](https://twitter.com/underlabs)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
