### ISSUE TITLE
Add 'Goldsilver' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#741]
Requesting to add 'Goldsilver' to the 'Retail' category. 

Details follow: 
```yml 
- name: Goldsilver
      url: https://goldsilver.com/
      img: 
      twitter: GoldSilver_com
      facebook: GoldSilverDotCom
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Goldsilver](https://pbs.twimg.com/profile_images/968572761198047233/388biOmw_400x400.jpg)

[Link to Goldsilver](https://goldsilver.com/)
If needed, try the twitter handles profile image: [twitter.com/GoldSilver_com](https://twitter.com/GoldSilver_com)
If needed, try the facebook handles profile image: [fb.com/GoldSilverDotCom](https://fb.com/GoldSilverDotCom)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
