### ISSUE TITLE
Add 'Appalachian Lawn Care ' to the 'Home Servies' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#742]
Requesting to add 'Appalachian Lawn Care ' to the 'Home Servies' category. 

Details follow: 
```yml 
- name: Appalachian Lawn Care 
      url: http://www.applawncare.com
      img: 
      email_address: info@applawncare.com
      region: na
      country: US
      city: Whitesburg
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Contact Merchant for payment invoice and address"
```

Resources for adding this merchant:
[Link to Appalachian Lawn Care ](http://www.applawncare.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
