### ISSUE TITLE
Add 'Instant cPanel Hosting' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#747]
Requesting to add 'Instant cPanel Hosting' to the 'Hosting' category. 

Details follow: 
```yml 
- name: Instant cPanel Hosting
      url: http://instantcpanelhosting.com/
      img: 
      twitter: ICPHTweet
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Instant cPanel Hosting](https://i.imgur.com/Vt1QBtE.png?1)

[Link to Instant cPanel Hosting](http://instantcpanelhosting.com/)
If needed, try the twitter handles profile image: [twitter.com/ICPHTweet](https://twitter.com/ICPHTweet)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
