### ISSUE TITLE
Add 'Hoster Box' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#748]
Requesting to add 'Hoster Box' to the 'Hosting' category. 

Details follow: 
```yml 
- name: Hoster Box
      url: https://hosterbox.com/
      img: 
      twitter: Hosterbox_com
      facebook: Hosterboxcom
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Hoster Box](https://i.imgur.com/IO2ewWi.png?1)

[Link to Hoster Box](https://hosterbox.com/)
If needed, try the twitter handles profile image: [twitter.com/Hosterbox_com](https://twitter.com/Hosterbox_com)
If needed, try the facebook handles profile image: [fb.com/Hosterboxcom](https://fb.com/Hosterboxcom)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
