### ISSUE TITLE
Add 'Hostinger' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#749]
Requesting to add 'Hostinger' to the 'Hosting' category. 

Details follow: 
```yml 
- name: Hostinger
      url: https://www.hostinger.com/
      img: 
      twitter: HostingerCOM
      facebook: Hostinger
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Hostinger](https://i.imgur.com/ZQIMF3Z.png?1)

[Link to Hostinger](https://www.hostinger.com/)
If needed, try the twitter handles profile image: [twitter.com/HostingerCOM](https://twitter.com/HostingerCOM)
If needed, try the facebook handles profile image: [fb.com/Hostinger](https://fb.com/Hostinger)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
