### ISSUE TITLE
Add 'Beard Head' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#750]
Requesting to add 'Beard Head' to the 'Retail' category. 

Details follow: 
```yml 
- name: Beard Head
      url: https://www.beardhead.cz
      img: 
      twitter: beardheadcz
      facebook: Beardheadcz-282340418473610
      country: CZ
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Beard Head](https://i.imgur.com/q77zB0P.jpg?2)

[Link to Beard Head](https://www.beardhead.cz)
If needed, try the twitter handles profile image: [twitter.com/beardheadcz](https://twitter.com/beardheadcz)
If needed, try the facebook handles profile image: [fb.com/Beardheadcz-282340418473610](https://fb.com/Beardheadcz-282340418473610)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
