### ISSUE TITLE
Add 'Frank & Beans' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#751]
Requesting to add 'Frank & Beans' to the 'Retail' category. 

Details follow: 
```yml 
- name: Frank & Beans
      url: https://www.frankandbeans.com.au/
      img: 
      twitter: fbunderwear
      facebook: frankandbeansunderwear
      region: af
      country: AU
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Frank & Beans](https://www.frankandbeans.com.au/)
If needed, try the twitter handles profile image: [twitter.com/fbunderwear](https://twitter.com/fbunderwear)
If needed, try the facebook handles profile image: [fb.com/frankandbeansunderwear](https://fb.com/frankandbeansunderwear)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
