### ISSUE TITLE
Add 'Coins 4 Clothes' to the 'Non-Profit/Charity' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#753]
Requesting to add 'Coins 4 Clothes' to the 'Non-Profit/Charity' category. 

Details follow: 
```yml 
- name: Coins 4 Clothes
      url: https://www.coins4clothes.com
      img: 
      twitter: coins4clothes
      facebook: coins4clothes
      region: na
      country: CA
      city: Toronto
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to Coins 4 Clothes](https://www.coins4clothes.com)
If needed, try the twitter handles profile image: [twitter.com/coins4clothes](https://twitter.com/coins4clothes)
If needed, try the facebook handles profile image: [fb.com/coins4clothes](https://fb.com/coins4clothes)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
