### ISSUE TITLE
Add 'Silicone sex doll ' to the 'adult sex toys' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#754]
Requesting to add 'Silicone sex doll ' to the 'adult sex toys' category. 

Details follow: 
```yml 
- name: Silicone sex doll 
      url: https://www.ovdoll.com/
      img: 
      twitter: sexdolluk
      facebook: Uksiliconesexdoll
      email_address: ovdollt@yeah.net
      country: US
      city: New York
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Silicone sex doll ](https://cdn.ovdoll.com/wp-content/uploads/2015/11/logoovdoll.png)

[Link to Silicone sex doll ](https://www.ovdoll.com/)
If needed, try the twitter handles profile image: [twitter.com/sexdolluk](https://twitter.com/sexdolluk)
If needed, try the facebook handles profile image: [fb.com/Uksiliconesexdoll](https://fb.com/Uksiliconesexdoll)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
