### ISSUE TITLE
Add 'Crypto Kid Games' to the 'Games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#755]
Requesting to add 'Crypto Kid Games' to the 'Games' category. 

Details follow: 
```yml 
- name: Crypto Kid Games
      url: https://www.cryptokidgames.com
      img: 
      twitter: billdlabs
      email_address: bill@billdlabs.com
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Crypto Kid Games](https://pbs.twimg.com/profile_images/963404681702617090/zF1bLKTk_400x400.jpg)

[Link to Crypto Kid Games](https://www.cryptokidgames.com)
If needed, try the twitter handles profile image: [twitter.com/billdlabs](https://twitter.com/billdlabs)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
