### ISSUE TITLE
Add 'Menē' to the 'Jewerly' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#757]
Requesting to add 'Menē' to the 'Jewerly' category. 

Details follow: 
```yml 
- name: Menē
      url: https://mene.com/
      img: 
      twitter: mene
      facebook: Mene24k
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Menē](https://pbs.twimg.com/profile_images/873208023736623104/zfZv_eni_400x400.jpg)

[Link to Menē](https://mene.com/)
If needed, try the twitter handles profile image: [twitter.com/mene](https://twitter.com/mene)
If needed, try the facebook handles profile image: [fb.com/Mene24k](https://fb.com/Mene24k)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
