### ISSUE TITLE
Add 'AirVPN' to the 'VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#760]
Requesting to add 'AirVPN' to the 'VPS' category. 

Details follow: 
```yml 
- name: AirVPN
      url: https://airvpn.org/
      img: 
      twitter: airvpn
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![AirVPN](https://pbs.twimg.com/profile_images/2812060055/33fa8d9e3084debda8c29cb7e33d9ec0_400x400.png)

[Link to AirVPN](https://airvpn.org/)
If needed, try the twitter handles profile image: [twitter.com/airvpn](https://twitter.com/airvpn)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
