### ISSUE TITLE
Add 'phun.io' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#762]
Requesting to add 'phun.io' to the 'Gambling' category. 

Details follow: 
```yml 
- name: phun.io
      url: https://www.phun.io
      img: 
      twitter: phun_io
      facebook: playphun.io
      bch: Yes
      btc: No
      othercrypto: No
      exceptions: 
        text: "https://www.phun.io/faq"
```

Resources for adding this merchant:
Logo Provided:
![phun.io](https://i.imgur.com/eIzqUFA.png)

[Link to phun.io](https://www.phun.io)
If needed, try the twitter handles profile image: [twitter.com/phun_io](https://twitter.com/phun_io)
If needed, try the facebook handles profile image: [fb.com/playphun.io](https://fb.com/playphun.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
