### ISSUE TITLE
Add 'Crypto Traders Pro' to the 'Professional Trading Education Course' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#763]
Requesting to add 'Crypto Traders Pro' to the 'Professional Trading Education Course' category. 

Details follow: 
```yml 
- name: Crypto Traders Pro
      url: https://cryptotraderspro.com/
      img: 
      facebook: CryptoTradersNews/
      email_address: kurt@cryptotraderspro.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Simple checkout with GoURL! "
```

Resources for adding this merchant:
Logo Provided:
![Crypto Traders Pro](https://cryptotraderspro.com/wp-content/uploads/2017/11/logo-footer.png)

[Link to Crypto Traders Pro](https://cryptotraderspro.com/)
If needed, try the facebook handles profile image: [fb.com/CryptoTradersNews/](https://fb.com/CryptoTradersNews/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
