### ISSUE TITLE
Add 'Play-Asia.com' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#764]
Requesting to add 'Play-Asia.com' to the 'Gaming' category. 

Details follow: 
```yml 
- name: Play-Asia.com
      url: https://www.play-asia.com/
      img: 
      twitter: playasia
      facebook: playasia
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://twitter.com/playasia/status/972079670815612930
```

Resources for adding this merchant:
Logo Provided:
![Play-Asia.com](https://pbs.twimg.com/profile_images/923851830383095808/eLS1JUBG_bigger.jpg)

[Link to Play-Asia.com](https://www.play-asia.com/)
If needed, try the twitter handles profile image: [twitter.com/playasia](https://twitter.com/playasia)
If needed, try the facebook handles profile image: [fb.com/playasia](https://fb.com/playasia)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
