### ISSUE TITLE
Add 'TAB.DIGITAL' to the 'cPanel Licenses/Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#767]
Requesting to add 'TAB.DIGITAL' to the 'cPanel Licenses/Hosting' category. 

Details follow: 
```yml 
- name: TAB.DIGITAL
      url: http://tab.digital
      img: 
      twitter: tab_digital
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![TAB.DIGITAL](https://tab.digital/assets/img/logo.png)

[Link to TAB.DIGITAL](http://tab.digital)
If needed, try the twitter handles profile image: [twitter.com/tab_digital](https://twitter.com/tab_digital)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
