### ISSUE TITLE
Add 'opwaarderen.nl' to the 'Utilities' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#768]
Requesting to add 'opwaarderen.nl' to the 'Utilities' category. 

Details follow: 
```yml 
- name: opwaarderen.nl
      url: https://www.opwaarderen.nl
      img: 
      twitter: opwaarderen
      facebook: opwaarderen
      region: eu
      country: NL
      bch: Yes
      btc: Yes
      othercrypto: No
      exceptions: 
        text: "Choose Bitcoin"
```

Resources for adding this merchant:
Logo Provided:
![opwaarderen.nl](https://pbs.twimg.com/profile_images/971040676350758914/_B_cxilh_400x400.jpg)

[Link to opwaarderen.nl](https://www.opwaarderen.nl)
If needed, try the twitter handles profile image: [twitter.com/opwaarderen](https://twitter.com/opwaarderen)
If needed, try the facebook handles profile image: [fb.com/opwaarderen](https://fb.com/opwaarderen)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
