### ISSUE TITLE
Add 'CheapAir' to the 'Transport' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#771]
Requesting to add 'CheapAir' to the 'Transport' category. 

Details follow: 
```yml 
- name: CheapAir
      url: https://cheapair.com
      img: 
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to CheapAir](https://cheapair.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
