### ISSUE TITLE
Add 'Lamassu' to the 'crypto services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#772]
Requesting to add 'Lamassu' to the 'crypto services' category. 

Details follow: 
```yml 
- name: Lamassu
      url: https://lamassu.is/
      img: 
      twitter: LamassuBTC
      facebook: lamassubtc
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Lamassu](https://i.imgur.com/7vZRbKi.png?1)

[Link to Lamassu](https://lamassu.is/)
If needed, try the twitter handles profile image: [twitter.com/LamassuBTC](https://twitter.com/LamassuBTC)
If needed, try the facebook handles profile image: [fb.com/lamassubtc](https://fb.com/lamassubtc)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
