### ISSUE TITLE
Add 'bitcoin.com Store' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#773]
Requesting to add 'bitcoin.com Store' to the 'Retail' category. 

Details follow: 
```yml 
- name: bitcoin.com Store
      url: https://store.bitcoin.com/
      img: 
      twitter: BTCTN
      facebook: buy.bitcoin.news
      email_address: store@bitcoin.com
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![bitcoin.com Store](https://imgur.com/a/VL3uE)

[Link to bitcoin.com Store](https://store.bitcoin.com/)
If needed, try the twitter handles profile image: [twitter.com/BTCTN](https://twitter.com/BTCTN)
If needed, try the facebook handles profile image: [fb.com/buy.bitcoin.news](https://fb.com/buy.bitcoin.news)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
