### ISSUE TITLE
Add 'RouterHosting' to the 'Hosting' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#774]
Requesting to add 'RouterHosting' to the 'Hosting' category. 

Details follow: 
```yml 
- name: RouterHosting
      url: https://www.routerhosting.com
      img: 
      twitter: routerhosting
      facebook: RouterHosting
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![RouterHosting](https://i.imgur.com/iAHIc0G.png?1)

[Link to RouterHosting](https://www.routerhosting.com)
If needed, try the twitter handles profile image: [twitter.com/routerhosting](https://twitter.com/routerhosting)
If needed, try the facebook handles profile image: [fb.com/RouterHosting](https://fb.com/RouterHosting)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
