### ISSUE TITLE
Add 'CheapAir' to the 'Transport Accommodation' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#775]
Requesting to add 'CheapAir' to the 'Transport Accommodation' category. 

Details follow: 
```yml 
- name: CheapAir
      url: https://www.cheapair.com
      img: 
      twitter: cheapair
      facebook: cheapair
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![CheapAir](https://pbs.twimg.com/profile_images/705897532933582849/jRDrfCWN_400x400.jpg)

[Link to CheapAir](https://www.cheapair.com)
If needed, try the twitter handles profile image: [twitter.com/cheapair](https://twitter.com/cheapair)
If needed, try the facebook handles profile image: [fb.com/cheapair](https://fb.com/cheapair)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
