### ISSUE TITLE
Add Coin Dance to donations category

### ISSUE THREAD

**Issue by Klakurka** [acceptbitcoincash/acceptbitcoincash#776]
Requesting to add Coin Dance to the donations category. Details follow:

```yml

- name: Coin Dance
  url: https://coin.dance (or https://cash.coin.dance, take your pick).
  img: https://coin.dance/assets/image/logo.png
  twitter: coin_dance
  facebook: --
  region: --
  country: --
  city: --
  bch: YES
  btc: YES
  othercrypto: NO
  doc: --
```
