### ISSUE TITLE
Add 'Anna Sikorska' to the 'Donations/Art' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#777]
Requesting to add 'Anna Sikorska' to the 'Donations/Art' category. 

Details follow: 
```yml 
- name: Anna Sikorska
      url: http://annasikorska.net/en/donations/
      img: 
      twitter: AnnaSikorskaAut
      region: eu
      country: PL
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Anna Sikorska](https://pbs.twimg.com/profile_images/959185974600306688/6QstK92R_400x400.jpg)

[Link to Anna Sikorska](http://annasikorska.net/en/donations/)
If needed, try the twitter handles profile image: [twitter.com/AnnaSikorskaAut](https://twitter.com/AnnaSikorskaAut)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
