### ISSUE TITLE
Add 'Seedboxes.cc' to the 'Vps' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#779]
Requesting to add 'Seedboxes.cc' to the 'Vps' category. 

Details follow: 
```yml 
- name: Seedboxes.cc
      url: https://www.seedboxes.cc
      img: 
      twitter: seedboxescc
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://blog.seedboxes.cc/post/168895178115/extending-cryptocurrency-support
```

Resources for adding this merchant:
[Link to Seedboxes.cc](https://www.seedboxes.cc)
If needed, try the twitter handles profile image: [twitter.com/seedboxescc](https://twitter.com/seedboxescc)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
