### ISSUE TITLE
Add 'Cobinhood' to the 'exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#781]
Requesting to add 'Cobinhood' to the 'exchange' category. 

Details follow: 
```yml 
- name: Cobinhood
      url: https://cobinhood.com/
      img: 
      twitter: cobinhood
      facebook: cobinhood.exchange
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Cobinhood](https://pbs.twimg.com/profile_images/907819119927537670/Z3hjGZSC_400x400.jpg)

[Link to Cobinhood](https://cobinhood.com/)
If needed, try the twitter handles profile image: [twitter.com/cobinhood](https://twitter.com/cobinhood)
If needed, try the facebook handles profile image: [fb.com/cobinhood.exchange](https://fb.com/cobinhood.exchange)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
