### ISSUE TITLE
Add '6 Dollar Shirts' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#792]
Requesting to add '6 Dollar Shirts' to the 'Retail' category. 

Details follow: 
```yml 
- name: 6 Dollar Shirts
      url: http://6dollarshirts.com
      img: 
      twitter: ‪6DollarShirts
      facebook: sixdollarshirts
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to 6 Dollar Shirts](http://6dollarshirts.com)
If needed, try the twitter handles profile image: [twitter.com/‪6DollarShirts](https://twitter.com/‪6DollarShirts)
If needed, try the facebook handles profile image: [fb.com/sixdollarshirts](https://fb.com/sixdollarshirts)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
