### ISSUE TITLE
Add 'Shirtwascash' to the 'retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#793]
Requesting to add 'Shirtwascash' to the 'retail' category. 

Details follow: 
```yml 
- name: Shirtwascash
      url: https://thatshirtwascash.com/
      img: 
      twitter: shirtwascash
      facebook: shirtwascash
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Shirtwascash](https://pbs.twimg.com/profile_images/954750970600218625/R39ZzT_A_400x400.jpg)

[Link to Shirtwascash](https://thatshirtwascash.com/)
If needed, try the twitter handles profile image: [twitter.com/shirtwascash](https://twitter.com/shirtwascash)
If needed, try the facebook handles profile image: [fb.com/shirtwascash](https://fb.com/shirtwascash)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
