### ISSUE TITLE
Add 'veldtgold.com' to the 'Precious Metals/Jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#796]
Requesting to add 'veldtgold.com' to the 'Precious Metals/Jewelry' category. 

Details follow: 
```yml 
- name: veldtgold.com
      url: https://veldtgold.com/
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Bitcoin Cash is not listed, but they do support it (my understanding)"
```

Resources for adding this merchant:
[Link to veldtgold.com](https://veldtgold.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
