### ISSUE TITLE
Add 'AbrahamArtist' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#798]
Requesting to add 'AbrahamArtist' to the 'Retail' category. 

Details follow: 
```yml 
- name: AbrahamArtist
      url: https://abrahamartist.myshopify.com/
      img: 
      twitter: Mad_spinner
      email_address: abrahama@abrahamartist.com
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![AbrahamArtist](https://drive.google.com/open?id=18MM9phgspxJB35InXH2WwnvkJRZeISbf)

[Link to AbrahamArtist](https://abrahamartist.myshopify.com/)
If needed, try the twitter handles profile image: [twitter.com/Mad_spinner](https://twitter.com/Mad_spinner)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
