### ISSUE TITLE
Add 'Riddell Travel' to the 'Tourism' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#803]
Requesting to add 'Riddell Travel' to the 'Tourism' category. 

Details follow: 
```yml 
- name: Riddell Travel
      url: https://www.riddelltravel.com
      img: riddelltravel.png
      email_address: bookings@riddelltravel.com
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://www.reddit.com/r/btc/comments/88yb6o/crypto_giving_you_sleepless_nights_rather_go_on_a/
      exceptions: 
        text: "Bitcoin cash address will be provided once you've decided on your preferred package."
```

Resources for adding this merchant:
[Link to Riddell Travel](https://www.riddelltravel.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
