### ISSUE TITLE
Add 'H-O-D-L' to the 'Apparel + Accessories' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#804]
Requesting to add 'H-O-D-L' to the 'Apparel + Accessories' category. 

Details follow: 
```yml 
- name: H-O-D-L
      url: https://h-o-d-l.co
      img: hodl.png
      country: US
      bch: Yes
      btc: No
      othercrypto: Yes
      exceptions: 
        text: "select Coinbase Commerce as payment option upon checkout and follow the prompts"
```

Resources for adding this merchant:
Logo Provided:
![H-O-D-L](https://cdn.shopify.com/s/files/1/0002/4766/0580/files/hodl-logo_540x.png?v=1519624509)

[Link to H-O-D-L](https://h-o-d-l.co)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
