### ISSUE TITLE
Add 'Common Crawl' to the 'Donations' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#805]
Requesting to add 'Common Crawl' to the 'Donations' category. 

Details follow: 
```yml 
- name: Common Crawl
      url: http://commoncrawl.org/
      img: 
      twitter: commoncrawl
      email_address: info@commoncrawl.org
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Common Crawl](http://commoncrawl.org/wp-content/themes/commoncrawl/img/spider.png)

[Link to Common Crawl](http://commoncrawl.org/)
If needed, try the twitter handles profile image: [twitter.com/commoncrawl](https://twitter.com/commoncrawl)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
