### ISSUE TITLE
Add 'Peddler' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#808]
Requesting to add 'Peddler' to the 'Retail' category. 

Details follow: 
```yml 
- name: Peddler
      url: https://www.peddler.com/
      img: 
      twitter: peddle_it
      facebook: peddlerdotcom
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Peddler](https://i.imgur.com/VHjCgoC.jpg?2)

[Link to Peddler](https://www.peddler.com/)
If needed, try the twitter handles profile image: [twitter.com/peddle_it](https://twitter.com/peddle_it)
If needed, try the facebook handles profile image: [fb.com/peddlerdotcom](https://fb.com/peddlerdotcom)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
