### ISSUE TITLE
Add 'Okami Knives' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#809]
Requesting to add 'Okami Knives' to the 'Retail' category. 

Details follow: 
```yml 
- name: Okami Knives
      url: https://www.okamiknives.com/
      img: 
      facebook: okamiknives
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Okami Knives](https://i.imgur.com/LIqlR5g.jpg?2)

[Link to Okami Knives](https://www.okamiknives.com/)
If needed, try the facebook handles profile image: [fb.com/okamiknives](https://fb.com/okamiknives)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
