### ISSUE TITLE
Add 'oVPN Anonymous Services' to the 'Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#814]
Requesting to add 'oVPN Anonymous Services' to the 'Security' category. 

Details follow: 
```yml 
- name: oVPN Anonymous Services
      url: https://vcp.ovpn.to
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![oVPN Anonymous Services](https://i.imgur.com/oUvaFIQ.png?1)

[Link to oVPN Anonymous Services](https://vcp.ovpn.to)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
