### ISSUE TITLE
Add 'Headphones.com' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#815]
Requesting to add 'Headphones.com' to the 'Retail' category. 

Details follow: 
```yml 
- name: Headphones.com
      url: https://www.headphones.com/
      img: 
      facebook: headphonesdotcom
      email_address: info@headphones.com
      bch: No
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Headphones.com](https://i.imgur.com/d2JyDpL.png?1)

[Link to Headphones.com](https://www.headphones.com/)
If needed, try the facebook handles profile image: [fb.com/headphonesdotcom](https://fb.com/headphonesdotcom)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
