### ISSUE TITLE
Add 'PenceBit' to the 'Jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#816]
Requesting to add 'PenceBit' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: PenceBit
      url: http://pencebit.com/
      img: 
      twitter: PenceBIT
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![PenceBit](https://i.imgur.com/UFQh1Wy.jpg?2)

[Link to PenceBit](http://pencebit.com/)
If needed, try the twitter handles profile image: [twitter.com/PenceBIT](https://twitter.com/PenceBIT)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
