### ISSUE TITLE
Add 'Lulu's Market' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#817]
Requesting to add 'Lulu's Market' to the 'Retail' category. 

Details follow: 
```yml 
- name: Lulu's Market
      url: https://livelove.organic/
      img: 
      twitter: ShopLuLusMarket
      facebook: liveloveorganics
      region: na
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Lulu's Market](https://i.imgur.com/v0VE7OY.jpg?2)

[Link to Lulu's Market](https://livelove.organic/)
If needed, try the twitter handles profile image: [twitter.com/ShopLuLusMarket](https://twitter.com/ShopLuLusMarket)
If needed, try the facebook handles profile image: [fb.com/liveloveorganics](https://fb.com/liveloveorganics)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
