### ISSUE TITLE
Add 'Wei of Chocolate' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#818]
Requesting to add 'Wei of Chocolate' to the 'Food' category. 

Details follow: 
```yml 
- name: Wei of Chocolate
      url: https://weiofchocolate.com/
      img: 
      twitter: WeiChocolate
      facebook: weichocolate
      region: na
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Wei of Chocolate](https://i.imgur.com/HgUmRVO.jpg?2)

[Link to Wei of Chocolate](https://weiofchocolate.com/)
If needed, try the twitter handles profile image: [twitter.com/WeiChocolate](https://twitter.com/WeiChocolate)
If needed, try the facebook handles profile image: [fb.com/weichocolate](https://fb.com/weichocolate)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
