### ISSUE TITLE
Add 'Emuparadise' to the 'Donations - Software' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#820]
Requesting to add 'Emuparadise' to the 'Donations - Software' category. 

Details follow: 
```yml 
- name: Emuparadise
      url: https://www.emuparadise.me
      img: 
      twitter: emuparadise
      facebook: emuparadise
      email_address: info@emuparadise.org
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.emuparadise.me/donatebtc.php
```

Resources for adding this merchant:
Logo Provided:
![Emuparadise](https://b64459531885200b3efb-5206a7b3a50a3f5974248375cd863061.ssl.cf1.rackcdn.com/graphics/eplogo-tag.jpg)

[Link to Emuparadise](https://www.emuparadise.me)
If needed, try the twitter handles profile image: [twitter.com/emuparadise](https://twitter.com/emuparadise)
If needed, try the facebook handles profile image: [fb.com/emuparadise](https://fb.com/emuparadise)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
