### ISSUE TITLE
Add 'TONG!' to the 'Beef Jerky (food)' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#822]
Requesting to add 'TONG!' to the 'Beef Jerky (food)' category. 

Details follow: 
```yml 
- name: TONG!
      url: https://tongjerky.com
      img: 
      twitter: TongJerky
      facebook: TongJerky
      region: na
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![TONG!](https://pbs.twimg.com/profile_images/940723915919204352/QtdX9AaJ_400x400.jpg)

[Link to TONG!](https://tongjerky.com)
If needed, try the twitter handles profile image: [twitter.com/TongJerky](https://twitter.com/TongJerky)
If needed, try the facebook handles profile image: [fb.com/TongJerky](https://fb.com/TongJerky)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
