### ISSUE TITLE
Add 'Pro Crypto' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#823]
Requesting to add 'Pro Crypto' to the 'Retail' category. 

Details follow: 
```yml 
- name: Pro Crypto
      url: http://procrypto.net/
      img: 
      twitter: Be_Pro_Crypto
      facebook: procrypto
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Pro Crypto](https://i.imgur.com/ozXtkxP.png?1)

[Link to Pro Crypto](http://procrypto.net/)
If needed, try the twitter handles profile image: [twitter.com/Be_Pro_Crypto](https://twitter.com/Be_Pro_Crypto)
If needed, try the facebook handles profile image: [fb.com/procrypto](https://fb.com/procrypto)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
