### ISSUE TITLE
Add 'Pokemon Bitcoin' to the 'retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#824]
Requesting to add 'Pokemon Bitcoin' to the 'retail' category. 

Details follow: 
```yml 
- name: Pokemon Bitcoin
      url: http://pokemonbtc.com/
      img: 
      twitter: pokemonbitcoin
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Pokemon Bitcoin](https://i.imgur.com/sfWcByw.png?1)

[Link to Pokemon Bitcoin](http://pokemonbtc.com/)
If needed, try the twitter handles profile image: [twitter.com/pokemonbitcoin](https://twitter.com/pokemonbitcoin)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
