### ISSUE TITLE
Add 'ShinyBars' to the 'Jewelry' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#825]
Requesting to add 'ShinyBars' to the 'Jewelry' category. 

Details follow: 
```yml 
- name: ShinyBars
      url: https://www.shinybars.com
      img: 
      twitter: shinybarsdotcom
      facebook: shinybars
      bch: No
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![ShinyBars](https://i.imgur.com/cZxTnCZ.png?1)

[Link to ShinyBars](https://www.shinybars.com)
If needed, try the twitter handles profile image: [twitter.com/shinybarsdotcom](https://twitter.com/shinybarsdotcom)
If needed, try the facebook handles profile image: [fb.com/shinybars](https://fb.com/shinybars)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
