### ISSUE TITLE
Add 'LV.Net' to the 'Utility' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#826]
Requesting to add 'LV.Net' to the 'Utility' category. 

Details follow: 
```yml 
- name: LV.Net
      url: https://www.lv.net
      img: 
      twitter: LVNet
      region: na
      country: US
      bch: No
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![LV.Net](https://pbs.twimg.com/profile_images/685594086917578752/rF3zHx45_400x400.jpg)

[Link to LV.Net](https://www.lv.net)
If needed, try the twitter handles profile image: [twitter.com/LVNet](https://twitter.com/LVNet)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
