### ISSUE TITLE
Requesting to add Blockchain Poker to the gambling category

### ISSUE THREAD

**Issue by Klakurka** [acceptbitcoincash/acceptbitcoincash#831]
Requesting to add Blockchain Poker to the gambling category. Details follow:

```yml

- name: Blockchain Poker
  url: https://blockchain.poker/#/cash
  img: https://blockchain.poker/images/bplogo.png
  twitter: BlockchainPoker
  bch: yes
  btc: yes
  othercrypto: no
```

[twitter](https://twitter.com/blockchainpoker)
