### ISSUE TITLE
Add 'DT - Group' to the 'Citizenships, Immigration ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#833]
Requesting to add 'DT - Group' to the 'Citizenships, Immigration ' category. 

Details follow: 
```yml 
- name: DT - Group
      url: https://second-passport-citizenship.associates
      img: 
      twitter: esparageeks
      email_address: dtgroup@mailfence.com
      country: PA
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://second-passport-citizenship.associates/second_citizenship_contact/residency_contact.htm
```

Resources for adding this merchant:
[Link to DT - Group](https://second-passport-citizenship.associates)
If needed, try the twitter handles profile image: [twitter.com/esparageeks](https://twitter.com/esparageeks)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
