### ISSUE TITLE
Add 'Coldwell Diplomatic Consultants ' to the 'Legal, immigration, diplomatic positions' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#835]
Requesting to add 'Coldwell Diplomatic Consultants ' to the 'Legal, immigration, diplomatic positions' category. 

Details follow: 
```yml 
- name: Coldwell Diplomatic Consultants 
      url: https://diplomaticsecondpassports.com/
      img: 
      twitter: esparamachos
      email_address: coldwellconsultants@mailfence.com
      country: PA
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://diplomaticsecondpassports.com
```

Resources for adding this merchant:
[Link to Coldwell Diplomatic Consultants ](https://diplomaticsecondpassports.com/)
If needed, try the twitter handles profile image: [twitter.com/esparamachos](https://twitter.com/esparamachos)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
