### ISSUE TITLE
Add 'ALLGIRLSFLASH' to the 'Adult Live Cams' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#836]
Requesting to add 'ALLGIRLSFLASH' to the 'Adult Live Cams' category. 

Details follow: 
```yml 
- name: ALLGIRLSFLASH
      url: https://www.allgirlsflash.me/en
      img: 
      twitter: bitcoincams
      email_address: billyweb90@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![ALLGIRLSFLASH](https://pbs.twimg.com/profile_images/936277414912647170/T8NgLz2t_400x400.jpg)

[Link to ALLGIRLSFLASH](https://www.allgirlsflash.me/en)
If needed, try the twitter handles profile image: [twitter.com/bitcoincams](https://twitter.com/bitcoincams)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
