### ISSUE TITLE
Add 'iPayYou.io' to the 'wallet, e-commerce, gift cards' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#837]
Requesting to add 'iPayYou.io' to the 'wallet, e-commerce, gift cards' category. 

Details follow: 
```yml 
- name: iPayYou.io
      url: https://www.ipayyou.io
      img: 
      twitter: ipayyouwallet
      email_address: partners@ipayyou.io
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![iPayYou.io](https://www.ipayyou.io/images/logo_blue001.png)

[Link to iPayYou.io](https://www.ipayyou.io)
If needed, try the twitter handles profile image: [twitter.com/ipayyouwallet](https://twitter.com/ipayyouwallet)
If needed, try the facebook handles profile image: [fb.com/ipayyou.io/](https://fb.com/ipayyou.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
