### ISSUE TITLE
Add 'MyMillennialGuide.com' to the 'Career' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#838]
Requesting to add 'MyMillennialGuide.com' to the 'Career' category. 

Details follow: 
```yml 
- name: MyMillennialGuide.com
      url: https://www.mymillennialguide.com/resume-writing
      img: 
      twitter: themillennialmg
      facebook: mymillennialguide
      email_address: brian@mymillennialguide.com
      bch: No
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![MyMillennialGuide.com](https://www.mymillennialguide.com/wp-content/uploads/MyMillennialGuide-Logo.png)

[Link to MyMillennialGuide.com](https://www.mymillennialguide.com/resume-writing)
If needed, try the twitter handles profile image: [twitter.com/themillennialmg](https://twitter.com/themillennialmg)
If needed, try the facebook handles profile image: [fb.com/mymillennialguide](https://fb.com/mymillennialguide)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
