### ISSUE TITLE
Add 'Safe Movers of New England LLC' to the 'Moving Help ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#839]
Requesting to add 'Safe Movers of New England LLC' to the 'Moving Help ' category. 

Details follow: 
```yml 
- name: Safe Movers of New England LLC
      url: https://www.safemoversofnewengland.com
      img: 
      region: na
      country: US
      city: New England States (VT, NH, MA, RI, CT and Maine)
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Safe Movers of New England LLC](https://www.safemoversofnewengland.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
