### ISSUE TITLE
Add 'Atlantis' to the 'Payment processor' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#840]
Requesting to add 'Atlantis' to the 'Payment processor' category. 

Details follow: 
```yml 
- name: Atlantis
      url: http://atlantislabs.co/
      img: 
      twitter: AtlantisLabs
      email_address: sumanth@atlantislabs.co
      city: No
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://medium.com/atlantislabs/money-is-now-an-api-7164514d4383
```

Resources for adding this merchant:
Logo Provided:
![Atlantis](https://pbs.twimg.com/profile_images/981796155779530752/RsOeOHTq_400x400.jpg)

[Link to Atlantis](http://atlantislabs.co/)
If needed, try the twitter handles profile image: [twitter.com/AtlantisLabs](https://twitter.com/AtlantisLabs)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
