### ISSUE TITLE
Add 'AliseLab' to the 'Web development' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#842]
Requesting to add 'AliseLab' to the 'Web development' category. 

Details follow: 
```yml 
- name: AliseLab
      url: https://aliselab.com/
      img: 
      facebook: AliseLabCom/
      email_address: aliselab.com@gmail.com
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![AliseLab](https://aliselab.com/img/logo_text.png)

[Link to AliseLab](https://aliselab.com/)
If needed, try the facebook handles profile image: [fb.com/AliseLabCom/](https://fb.com/AliseLabCom/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
