### ISSUE TITLE
Add 'Cloudbet.com' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#843]
Requesting to add 'Cloudbet.com' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Cloudbet.com
      url: https://www.cloudbet.com/en/
      img: 
      twitter: cloudbet
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.cloudbet.com/en/bitcoin-cash-promotion
```

Resources for adding this merchant:
Logo Provided:
![Cloudbet.com](https://cdn.cloudbet.com/images/logo.png)

[Link to Cloudbet.com](https://www.cloudbet.com/en/)
If needed, try the twitter handles profile image: [twitter.com/cloudbet](https://twitter.com/cloudbet)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
