### ISSUE TITLE
Add 'MCT WATCHES' to the 'Accessory' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#844]
Requesting to add 'MCT WATCHES' to the 'Accessory' category. 

Details follow: 
```yml 
- name: MCT WATCHES
      url: http://www.mctwatches.com
      img: 
      twitter: mct_watches
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: http://www.mctwatches.com/news/buy-bitcoin-swiss-luxury-click
```

Resources for adding this merchant:
Logo Provided:
![MCT WATCHES](http://www.mctwatches.com/sites/default/files/MCT-Logo.png)

[Link to MCT WATCHES](http://www.mctwatches.com/news/buy-bitcoin-swiss-luxury-click)
If needed, try the twitter handles profile image: [twitter.com/mct_watches](https://twitter.com/mct_watches)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
