### ISSUE TITLE
Add 'Trader's Way' to the 'Jonald needs to say' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#845]
Requesting to add 'Trader's Way' to the 'Jonald needs to say' category. 

Details follow: 
```yml 
- name: Trader's Way
      url: https://www.tradersway.com
      img: 
      twitter: TradersWay
      facebook: tradersway.forex.broker
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Trader's Way](https://i.imgur.com/Vshp2DN.png?1)

[Link to Trader's Way](https://www.tradersway.com)
If needed, try the twitter handles profile image: [twitter.com/TradersWay](https://twitter.com/TradersWay)
If needed, try the facebook handles profile image: [fb.com/tradersway.forex.broker](https://fb.com/tradersway.forex.broker)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
