### ISSUE TITLE
Add 'Sklep Internetowy KomBo' to the 'Online shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#848]
Requesting to add 'Sklep Internetowy KomBo' to the 'Online shop' category. 

Details follow: 
```yml 
- name: Sklep Internetowy KomBo
      url: https://www.kombo.krakow.pl
      img: 
      facebook: kombo.sklep
      email_address: biuro@kombo.krakow.pl
      region: eu
      country: PL
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.kombo.krakow.pl/Regulamin.htm#krypto
```

Resources for adding this merchant:
Logo Provided:
![Sklep Internetowy KomBo](https://www.kombo.krakow.pl/img/logo.jpg)

[Link to Sklep Internetowy KomBo](https://www.kombo.krakow.pl)
If needed, try the facebook handles profile image: [fb.com/kombo.sklep](https://fb.com/kombo.sklep)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
