### ISSUE TITLE
Add 'Money Metals Exchange' to the 'Precious Metals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#851]
Requesting to add 'Money Metals Exchange' to the 'Precious Metals' category. 

Details follow: 
```yml 
- name: Money Metals Exchange
      url: https://www.moneymetals.com/
      img: 
      email_address: inquiry@moneymetals.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Money Metals Exchange](https://www.moneymetals.com/uploads/content/money-metals-logo.png)

[Link to Money Metals Exchange](https://www.moneymetals.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
