### ISSUE TITLE
Add 'prsales.club' to the 'products + reviews = $ales' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#852]
Requesting to add 'prsales.club' to the 'products + reviews = $ales' category. 

Details follow: 
```yml 
- name: prsales.club
      url: http://www.prsales.club
      img: 
      twitter: prsales.clubprsales.club
      facebook: prsales.club
      email_address: prsalesclub@gmail.com
      country: US
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![prsales.club](http://www.prsales.club/home)

[Link to prsales.club](http://www.prsales.club)
If needed, try the twitter handles profile image: [twitter.com/prsales.clubprsales.club](https://twitter.com/prsales.clubprsales.club)
If needed, try the facebook handles profile image: [fb.com/prsales.club](https://fb.com/prsales.club)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
