### ISSUE TITLE
Add 'GimbalZone' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#853]
Requesting to add 'GimbalZone' to the 'Retail' category. 

Details follow: 
```yml 
- name: GimbalZone
      url: https://www.gimbalzone.com/
      img: 
      facebook: GimbalZone-152411641998649
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![GimbalZone](https://cdn.shopify.com/s/files/1/1765/5383/files/gimbal_trans01_d7a060e2-f755-400b-8b50-a02bef0fb9f4_350x@2x.png)

[Link to GimbalZone](https://www.gimbalzone.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
