### ISSUE TITLE
Add 'CZIP' to the 'Crypto Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#858]
Requesting to add 'CZIP' to the 'Crypto Services' category. 

Details follow: 
```yml 
- name: CZIP
      url: https://czip.org
      img: czip.png
      twitter: cziporg
      facebook: CZIP-431239467316507
      email_address: support@czip.org
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://bitcointalk.org/index.php?topic=3352434.0
```

Resources for adding this merchant:
Logo Provided:
![CZIP](https://czip.org/img/fb.png)

[Link to CZIP](https://czip.org)
If needed, try the twitter handles profile image: [twitter.com/cziporg](https://twitter.com/cziporg)
If needed, try the facebook handles profile image: [fb.com/pg/CZIP-431239467316507](https://fb.com/pg/CZIP-431239467316507)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
