### ISSUE TITLE
Requesting to add CZIP to the Crypto Services category.

### ISSUE THREAD

**Issue by miranos** [acceptbitcoincash/acceptbitcoincash#859]
```yml

- name: CZIP
  url: https://czip.org
  img: https://czip.org/img/fb.png
  twitter: cziporg
  facebook: CZIP-431239467316507
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://bitcointalk.org/index.php?topic=3352434.0
```
