### ISSUE TITLE
Add 'CFINEX' to the 'cryptoexchanges' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#862]
Requesting to add 'CFINEX' to the 'Exchange' category. 

Details follow: 
```yml 
- name: CFINEX
      url: https://cfinex.com/
      img: https://i.imgur.com/dkW4qSR.jpg?2
      twitter: cfinex
      email_address: support@cfinex.info
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/cfinex/status/984134767288438784
```

Resources for adding this merchant:
Logo Provided:
![CFINEX](https://cfinex.com/CSS/img/cfinex_green.png)

[Link to CFINEX](https://cfinex.com/#BCH-BTC)
If needed, try the twitter handles profile image: [twitter.com/cfinex](https://twitter.com/cfinex)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
