### ISSUE TITLE
Add 'Ketolent' to the 'Retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#863]
Requesting to add 'Ketolent' to the 'Retailer' category. 

Details follow: 
```yml 
- name: Ketolent
      url: https://ketolent.com/
      img: Ketolent.png
      twitter: eatketolent
      facebook: eatketolent
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Ketolent](https://i.imgur.com/P2KGi3u.jpg?2)

[Link to Ketolent](https://ketolent.com/)
If needed, try the twitter handles profile image: [twitter.com/eatketolent](https://twitter.com/eatketolent)
If needed, try the facebook handles profile image: [fb.com/eatketolent](https://fb.com/eatketolent)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
