### ISSUE TITLE
Add 'BuyPrivacy' to the 'Security' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#864]
Requesting to add 'BuyPrivacy' to the 'Security' category. 

Details follow: 
```yml 
- name: BuyPrivacy
      url: https://www.buyprivacy.net
      img: buyprivacy.png
      twitter: TheBuyPrivacy
      email_address: socialmedia@buyprivacy.net
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![BuyPrivacy](https://pbs.twimg.com/profile_images/975997080064876544/tiJZ-yoS_400x400.jpg)

[Link to BuyPrivacy](https://www.buyprivacy.net)
If needed, try the twitter handles profile image: [twitter.com/TheBuyPrivacy](https://twitter.com/TheBuyPrivacy)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
