### ISSUE TITLE
Add 'CoinTracking.Info' to the 'Crytpo Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#865]
Requesting to add 'CoinTracking.Info' to the 'Crytpo Services' category. 

Details follow: 
```yml 
- name: CoinTracking.Info
      url: https://cointracking.info/
      img: 
      twitter: Coin_Tracking
      facebook: CoinReporting/
      email_address: support@cointracking.info
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "As payments in altcoins are done via CoinPayments.net, one needs to give the first name, the last name and an email address (CoinPayments.net requirement)"
```

Resources for adding this merchant:
[Link to CoinTracking.Info](https://cointracking.info/)
If needed, try the twitter handles profile image: [twitter.com/Coin_Tracking](https://twitter.com/Coin_Tracking)
If needed, try the facebook handles profile image: [fb.com/CoinReporting/](https://fb.com/CoinReporting/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
