### ISSUE TITLE
Add 'Willie Jordaan Attorneys' to the 'Legal Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#866]
Requesting to add 'Willie Jordaan Attorneys' to the 'Legal Services' category. 

Details follow: 
```yml 
- name: Willie Jordaan Attorneys
      url: https://www.facebook.com/Willie-Jordaan-AttorneysProkureurs-124963854241844/
      img: 
      facebook: Willie-Jordaan-AttorneysProkureurs-124963854241844/
      email_address: law@icon.co.za
      region: af
      country: ZA
      city: Potchefstroom
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "No"
```

Resources for adding this merchant:
Logo Provided:
![Willie Jordaan Attorneys](https://www.facebook.com/Willie-Jordaan-AttorneysProkureurs-124963854241844/)

[Link to Willie Jordaan Attorneys](https://www.facebook.com/Willie-Jordaan-AttorneysProkureurs-124963854241844/)
If needed, try the facebook handles profile image: [fb.com/Willie-Jordaan-AttorneysProkureurs-124963854241844/](https://fb.com/Willie-Jordaan-AttorneysProkureurs-124963854241844/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
