### ISSUE TITLE
Add 'Wise Owl Technologies' to the 'Information Technology' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#868]
Requesting to add 'Wise Owl Technologies' to the 'Information Technology' category. 

Details follow: 
```yml 
- name: Wise Owl Technologies
      url: http://www.wiseowltechnologies.com
      img: 
      twitter: wiseowlsoo
      facebook: wiseowlcomputers/
      email_address: elliot@wiseodc.com
      region: na
      country: US
      city: Sault Ste. Marie, MI
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://twitter.com/wiseowlsoo/status/988781341541101568
      exceptions: 
        text: "Scan QR Code, or enter Wallet Address in "Send" Field"
```

Resources for adding this merchant:
Logo Provided:
![Wise Owl Technologies](https://imgur.com/IsVvu3A)

[Link to Wise Owl Technologies](http://www.wiseowltechnologies.com)
If needed, try the twitter handles profile image: [twitter.com/wiseowlsoo](https://twitter.com/wiseowlsoo)
If needed, try the facebook handles profile image: [fb.com/wiseowlcomputers/](https://fb.com/wiseowlcomputers/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
