### ISSUE TITLE
Add 'Gana Control' to the 'Digital Marketing Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#869]
Requesting to add 'Gana Control' to the 'Digital Marketing Services' category. 

Details follow: 
```yml 
- name: Gana Control
      url: https://ganacontrol.com/
      img: 
      email_address: contact@ganacontrol.com
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: htts://ganacontrol.com/
      exceptions: 
        text: "Standard"
```

Resources for adding this merchant:
Logo Provided:
![Gana Control](https://ganacontrol.com/wp-content/uploads/2016/07/pnglogo.png)

[Link to Gana Control](https://ganacontrol.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
