### ISSUE TITLE
Add 'Osaru Coffee' to the 'coffee shop' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#871]
Requesting to add 'Osaru Coffee' to the 'coffee shop' category. 

Details follow: 
```yml 
- name: Osaru Coffee
      url: https://osarucoffee.thebase.in
      img: 
      twitter: sakuranobonsai
      facebook: osarucoffee
      email_address: osarucoffee@gmail.com
      region: as
      country: JP
      city: Osaka
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://morizocoin.com/bchpayment_osarucoffee/
```

Resources for adding this merchant:
[Link to Osaru Coffee](https://osarucoffee.thebase.in)
If needed, try the twitter handles profile image: [twitter.com/sakuranobonsai](https://twitter.com/sakuranobonsai)
If needed, try the facebook handles profile image: [fb.com/osarucoffee](https://fb.com/osarucoffee)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
