### ISSUE TITLE
Add 'Cryptopiece' to the 'Advertising' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#876]
Requesting to add 'Cryptopiece' to the 'Advertising' category. 

Details follow: 
```yml 
- name: Cryptopiece
      url: https://www.cryptopiece.com
      img: 
      email_address: advertise@Cryptopiece.com
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Cryptopiece](https://pbs.twimg.com/profile_images/947840932887629824/UcI6drwQ_400x400.jpg)

[Link to Cryptopiece](https://www.cryptopiece.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
