### ISSUE TITLE
Add 'Menufy' to the 'Food' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#877]
Requesting to add 'Menufy' to the 'Food' category. 

Details follow: 
```yml 
- name: Menufy
      url: https://www.menufy.com
      img: 
      twitter: menufy
      facebook: menufy
      email_address: info@menufy.com
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.menufy.com/bitcoin-cash
      exceptions: 
        text: "Bitpay"
```

Resources for adding this merchant:
Logo Provided:
![Menufy](https://portalcontent-menufycom.netdna-ssl.com/MenufyLogo-500.png?lu=90173a1768dc6125df33728d4e1061c2)

[Link to Menufy](https://www.menufy.com)
If needed, try the twitter handles profile image: [twitter.com/menufy](https://twitter.com/menufy)
If needed, try the facebook handles profile image: [fb.com/menufy](https://fb.com/menufy)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
