### ISSUE TITLE
Add 'Wall of Coins' to the 'Fiat-Crypto Exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#893]
Requesting to add 'Wall of Coins' to the 'Fiat-Crypto Exchange' category. 

Details follow: 
```yml 
- name: Wall of Coins
      url: https://wallofcoins.com/en/
      img: 
      twitter: WallofCoins
      facebook: wallofcoins
      email_address: accounts@genitrust.com
      bch: Yes
      btc: No
      othercrypto: Yes
      exceptions: 
        text: "Upgrade your cash to Bitcoin Cash on our easy to use platform for buying and selling Bitcoin Cash. "
```

Resources for adding this merchant:
Logo Provided:
![Wall of Coins](https://wallofcoins-static.s3.amazonaws.com/wallofcoins/img/logo-full.png)

[Link to Wall of Coins](https://wallofcoins.com/en/)
If needed, try the twitter handles profile image: [twitter.com/WallofCoins](https://twitter.com/WallofCoins)
If needed, try the facebook handles profile image: [fb.com/wallofcoins](https://fb.com/wallofcoins)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
