### ISSUE TITLE
Add 'Keys4Coins' to the 'Games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#895]
Requesting to add 'Keys4Coins' to the 'Games' category. 

Details follow: 
```yml 
- name: Keys4Coins
      url: https://www.keys4coins.com
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Keys4Coins](https://www.keys4coins.com/wp-content/uploads/2015/10/keys4coins-logo.png)

[Link to Keys4Coins](https://www.keys4coins.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
