### ISSUE TITLE
Add 'BCHSticker.com' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#897]
Requesting to add 'BCHSticker.com' to the 'Retail' category. 

Details follow: 
```yml 
- name: BCHSticker.com
      url: http://BCHSticker.com
      img: 
      twitter: https://yours.org/bchsticker
      email_address: contact@bchsticker.com
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.yours.org/content/excited-to-announce-the-launch-of-bchstickercom--dc5394649d16
```

Resources for adding this merchant:
Logo Provided:
![BCHSticker.com](http://bchsticker.com/128bchsticker.jpg)

[Link to BCHSticker.com](http://BCHSticker.com)
If needed, try the twitter handles profile image: [twitter.com/https://yours.org/bchsticker](https://twitter.com/https://yours.org/bchsticker)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
