### ISSUE TITLE
Add 'Nozzles.Online' to the 'Retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#905]
Requesting to add 'Nozzles.Online' to the 'Retailer' category. 

Details follow: 
```yml 
- name: Nozzles.Online
      url: http://nozzles.online
      img: nozzlesonline.png
      twitter: nozzlesonline
      email_address: fantastic.nozzles@nozzles.online
      region: oc
      country: AU
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Nozzles.Online](https://i.imgur.com/GMP6fHF.jpg?2)

[Link to Nozzles.Online](http://nozzles.online)
If needed, try the twitter handles profile image: [twitter.com/nozzlesonline](https://twitter.com/nozzlesonline)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
