### ISSUE TITLE
Add 'The Computer Wellness Center' to the 'IT services for small offices' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#907]
Requesting to add 'The Computer Wellness Center' to the 'IT services for small offices' category. 

Details follow: 
```yml 
- name: The Computer Wellness Center
      url: http://www.computer-wellness.com
      img: 
      email_address: eric@computer-wellness.com
      region: na
      country: US
      city: Boston
      bch: Yes
      btc: No
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![The Computer Wellness Center](http://computer-wellness.com/wp-content/uploads/2013/10/Logo42.jpg)

[Link to The Computer Wellness Center](http://www.computer-wellness.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
