### ISSUE TITLE
Add 'Wall of Coins' to the 'Marketplace' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#908]
Requesting to add 'Wall of Coins' to the 'Marketplace' category. 

Details follow: 
```yml 
- name: Wall of Coins
      url: https://wallofcoins.com/
      img: 
      twitter: WallofCoins
      facebook: wallofcoins
      email_address: support@wallofcoins.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/WallofCoins/status/988889599811473409
```

Resources for adding this merchant:
Logo Provided:
![Wall of Coins](https://wallofcoins.com/)

[Link to Wall of Coins](https://wallofcoins.com/)
If needed, try the twitter handles profile image: [twitter.com/WallofCoins](https://twitter.com/WallofCoins)
If needed, try the facebook handles profile image: [fb.com/wallofcoins](https://fb.com/wallofcoins)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
