### ISSUE TITLE
Add 'max badger' to the 'Apparel/Goods' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#909]
Requesting to add 'max badger' to the 'Apparel/Goods' category. 

Details follow: 
```yml 
- name: max badger
      url: https://www.maxbadger.com/
      img: 
      twitter: heymaxbadger
      email_address: hey@maxbadger.com
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![max badger](https://raw.githubusercontent.com/dereksnow/maxbadger/master/maxbadger-BW-brand-500px.png)

[Link to max badger](https://www.maxbadger.com/)
If needed, try the twitter handles profile image: [twitter.com/heymaxbadger](https://twitter.com/heymaxbadger)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
