### ISSUE TITLE
Add 'Unisoftdev' to the 'Developer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#910]
Requesting to add 'Unisoftdev' to the 'Developer' category. 

Details follow: 
```yml 
- name: Unisoftdev
      url: https://www.unisoftdev.tech
      img: Unisoftdev.png
      twitter: Unisoftdev1
      facebook: Unisoftdev
      email_address: admin@unisoftdev.tech
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.unisoftdev.tech/services/we-accept-bitcoin
```

Resources for adding this merchant:
Logo Provided:
![Unisoftdev](https://www.unisoftdev.tech/images/logo.jpg)

[Link to Unisoftdev](https://www.unisoftdev.tech)
If needed, try the twitter handles profile image: [twitter.com/Unisoftdev1](https://twitter.com/Unisoftdev1)
If needed, try the facebook handles profile image: [fb.com/Unisoftdev](https://fb.com/Unisoftdev)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
