### ISSUE TITLE
Add 'cheddr' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#911]
Requesting to add 'cheddr' to the 'Payments' category. 

Details follow: 
```yml 
- name: cheddr
      url: https://pos.cheddr.cash/#landingDonate
      img: cheddr.png
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![cheddr](https://pos.cheddr.cash/images/cheese.png)

[Link to cheddr](https://pos.cheddr.cash/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
