### ISSUE TITLE
Add 'CryptoSportsBet.World' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#912]
Requesting to add 'CryptoSportsBet.World' to the 'Gambling' category. 

Details follow: 
```yml 
- name: CryptoSportsBet.World
      url: https://cryptosportsbet.world
      img: 
      twitter: CryptoSportBets
      email_address: admin@cryptosportsbet.world
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://memo.cash/post/4a2a20c23556482a50d66364d23d60117dde785ddc3b4c7aba352a36b30b2728
```

Resources for adding this merchant:
Logo Provided:
![CryptoSportsBet.World](https://i.imgur.com/rGpwZ4h.png?1)

[Link to CryptoSportsBet.World](https://cryptosportsbet.world)
If needed, try the twitter handles profile image: [twitter.com/CryptoSportBets](https://twitter.com/CryptoSportBets)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
