### ISSUE TITLE
Add 'Thoughtlab' to the 'Website Developer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#914]
Requesting to add 'Thoughtlab' to the 'Website Developer' category. 

Details follow: 
```yml 
- name: Thoughtlab
      url: https://www.thoughtlab.com/
      img: 
      twitter: thoughtlabllc
      facebook: ThoughtLabLLC
      email_address: gen@thoughtlab.com
      region: na
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.thoughtlab.com/blog/post/we-now-accept-cryptocurrency
```

Resources for adding this merchant:
Logo Provided:
![Thoughtlab](https://www.thoughtlab.com/uploads/cms/brain.jpg)

[Link to Thoughtlab](https://www.thoughtlab.com/)
If needed, try the twitter handles profile image: [twitter.com/thoughtlabllc](https://twitter.com/thoughtlabllc)
If needed, try the facebook handles profile image: [fb.com/ThoughtLabLLC](https://fb.com/ThoughtLabLLC)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
