### ISSUE TITLE
Add 'B12 Vitamin Store' to the 'Health and Beauty' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#916]
Requesting to add 'B12 Vitamin Store' to the 'Health and Beauty' category. 

Details follow: 
```yml 
- name: B12 Vitamin Store
      url: https://b12vitaminstore.com/
      img: 
      twitter: B12VitaminStore
      facebook: b12vitaminstore
      email_address: support@b12vitaminstore.com
      region: na
      country: US
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to B12 Vitamin Store](https://b12vitaminstore.com/)
If needed, try the twitter handles profile image: [twitter.com/B12VitaminStore](https://twitter.com/B12VitaminStore)
If needed, try the facebook handles profile image: [fb.com/b12vitaminstore/](https://fb.com/b12vitaminstore/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
