### ISSUE TITLE
Add 'Creamy Taiwan' to the 'Used Apparel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#917]
Requesting to add 'Creamy Taiwan' to the 'Used Apparel' category. 

Details follow: 
```yml 
- name: Creamy Taiwan
      url: https://creamytaiwan.com
      img: 
      twitter: creamytaiwan
      email_address: abby@creamytaiwan.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Creamy Taiwan](https://creamytaiwan.com/content/uploads/2018/04/creamy_logo_lavender.png)

[Link to Creamy Taiwan](https://creamytaiwan.com)
If needed, try the twitter handles profile image: [twitter.com/creamytaiwan](https://twitter.com/creamytaiwan)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
