### ISSUE TITLE
Add 'Pinnacle Sports' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#918]
Requesting to add 'Pinnacle Sports' to the 'Gambling' category. 

Details follow: 
```yml 
- name: Pinnacle Sports
      url: https://www.pinnacle.com
      img: PinnacleSports.png
      twitter: PinnacleSports
      facebook: PinnacleSports
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Pinnacle Sports](https://pbs.twimg.com/profile_images/738330270022012928/yG3HwaeQ_400x400.jpg)

[Link to Pinnacle Sports](https://www.pinnacle.com)
If needed, try the twitter handles profile image: [twitter.com/PinnacleSports](https://twitter.com/PinnacleSports)
If needed, try the facebook handles profile image: [fb.com/PinnacleSports/](https://fb.com/PinnacleSports/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
