### ISSUE TITLE
Add 'Inkwell Ideas' to the 'Gaming' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#919]
Requesting to add 'Inkwell Ideas' to the 'Gaming' category. 

Details follow: 
```yml 
- name: Inkwell Ideas
      url: https://store.inkwellideas.com/
      img: 
      twitter: InkwellIdeas
      email_address: joe@inkwellideas.com
      country: US
      bch: Yes
      btc: Yes
      othercrypto: No
      keywords: 
        - bitpay
```

Resources for adding this merchant:
Logo Provided:
![Inkwell Ideas](https://pbs.twimg.com/profile_images/790459143/hexographer200x200_400x400.png)

[Link to Inkwell Ideas](https://store.inkwellideas.com/)
If needed, try the twitter handles profile image: [twitter.com/InkwellIdeas](https://twitter.com/InkwellIdeas)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
