### ISSUE TITLE
Add 'Dyrdahl Lumber' to the 'Building Supply' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#922]
Requesting to add 'Dyrdahl Lumber' to the 'Building Supply' category. 

Details follow: 
```yml 
- name: Dyrdahl Lumber
      url: https://www.dyrdahl-lumber.com/
      img: 
      facebook: dyrdahllumber
      email_address: rdyrdahl@yahoo.com
      region: na
      country: US
      city: Minnesota
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Just contact us."
```

Resources for adding this merchant:
Logo Provided:
![Dyrdahl Lumber](https://static.wixstatic.com/media/a77bb7_0027df634f7d42cbba8593396241a15c~mv2.png/v1/fill/w_122,h_122,al_c,usm_0.66_1.00_0.01/a77bb7_0027df634f7d42cbba8593396241a15c~mv2.png)

[Link to Dyrdahl Lumber](https://www.dyrdahl-lumber.com/)
If needed, try the facebook handles profile image: [fb.com/dyrdahllumber](https://fb.com/dyrdahllumber)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
