### ISSUE TITLE
Add 'BCH Dice (Telegram Bot)' to the 'Gambling' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#923]
Requesting to add 'BCH Dice (Telegram Bot)' to the 'Gambling' category. 

Details follow: 
```yml 
- name: BCH Dice (Telegram Bot)
      url: https://t.me/BCH_Dice_Bot
      img: 
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to BCH Dice (Telegram Bot)](https://t.me/BCH_Dice_Bot)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
