### ISSUE TITLE
Add 'Snel.com B.V.' to the 'Hosting/VPS' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#924]
Requesting to add 'Snel.com B.V.' to the 'Hosting/VPS' category. 

Details follow: 
```yml 
- name: Snel.com B.V.
      url: https://www.snel.com
      img: 
      twitter: snelcom
      facebook: snelcom
      email_address: sales@snel.com
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://www.snel.com/support/which-payment-methods-do-you-offer/
```

Resources for adding this merchant:
Logo Provided:
![Snel.com B.V.](https://pbs.twimg.com/profile_images/771311551743524867/tIMdqhyd_400x400.jpg)

[Link to Snel.com B.V.](https://www.snel.com)
If needed, try the twitter handles profile image: [twitter.com/snelcom](https://twitter.com/snelcom)
If needed, try the facebook handles profile image: [fb.com/snelcom](https://fb.com/snelcom)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
