### ISSUE TITLE
Add 'Umami Snack Import' to the 'Retailer' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#926]
Requesting to add 'Umami Snack Import' to the 'Retailer' category. 

Details follow: 
```yml 
- name: Umami Snack Import
      url: https://www.umamisnack.ch/
      img: 
      twitter: umamisnack
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://twitter.com/umamisnack/status/992325968437104641
```

Resources for adding this merchant:
Logo Provided:
![Umami Snack Import](https://www.umamisnack.ch/wp-content/uploads/2017/07/umami-logo.png)

[Link to Umami Snack Import](https://www.umamisnack.ch/)
If needed, try the twitter handles profile image: [twitter.com/umamisnack](https://twitter.com/umamisnack)

- Verify site is legitimate and safe to list.
- Correct data in form if any is innacurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with 'closes #[ISSUE NUMBER HERE]'.
