### ISSUE TITLE
Add 'BitPro' to the 'Payments' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#927]
Requesting to add 'BitPro' to the 'Payments' category. 

Details follow: 
```yml 
- name: BitPro
      url: https://bitpro.cc
      img: 
      email_address: info@bitpro.cc
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/8gqi5v/payment_gateway_bch_surpassed_btc/
```

Resources for adding this merchant:
[Link to BitPro](https://bitpro.cc)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
