### ISSUE TITLE
Add 'Autodekor-Cars Interior Dash Kits - real Wood Grain, Carbon Fiber, Camouflage, Aluminum, Stainless Steel dashboard kits' to the 'Auto' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#930]
Requesting to add 'Autodekor-Cars Interior Dash Kits - real Wood Grain, Carbon Fiber, Camouflage, Aluminum, Stainless Steel dashboard kits' to the 'Auto' category. 

Details follow: 
```yml 
- name: Autodekor-Cars Interior Dash Kits - real Wood Grain, Carbon Fiber, Camouflage, Aluminum, Stainless Steel dashboard kits
      url: https://cockpitdekor.com
      img: 
      twitter: Fityourselfcouk
      facebook: cockpitdekor/
      email_address: info@cockpitdekor.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://cockpitdekor.com/en/content/5-secure-payment
```

Resources for adding this merchant:
Logo Provided:
![Autodekor-Cars Interior Dash Kits - real Wood Grain, Carbon Fiber, Camouflage, Aluminum, Stainless Steel dashboard kits](https://cockpitdekor.com/img/my-shop-logo-1522995744.jpg)

[Link to Autodekor-Cars Interior Dash Kits - real Wood Grain, Carbon Fiber, Camouflage, Aluminum, Stainless Steel dashboard kits](https://cockpitdekor.com)
If needed, try the twitter handles profile image: [twitter.com/Fityourselfcouk](https://twitter.com/Fityourselfcouk)
If needed, try the facebook handles profile image: [fb.com/cockpitdekor/](https://fb.com/cockpitdekor/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
