### ISSUE TITLE
Add 'PekTech' to the '3D Printing Services' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#931]
Requesting to add 'PekTech' to the '3D Printing Services' category. 

Details follow: 
```yml 
- name: PekTech
      url: https://pek.tech/
      img: 
      twitter: pek_tech
      facebook: https://www.instagram.com/pektech/
      email_address: contact@pek.tech
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://pek.tech/crypto.php
      exceptions: 
        text: "https://pek.tech/crypto.php"
```

Resources for adding this merchant:
Logo Provided:
![PekTech](https://pek.tech/assets/images/Logowringblue128.png)

[Link to PekTech](https://pek.tech/)
If needed, try the twitter handles profile image: [twitter.com/pek_tech](https://twitter.com/pek_tech)
If needed, try the facebook handles profile image: [fb.com/https://www.instagram.com/pektech/](https://fb.com/https://www.instagram.com/pektech/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
