### ISSUE TITLE
Add steam games back into the Bitcoin community via BCH

### ISSUE THREAD

**Issue by keshavnarla** [acceptbitcoincash/acceptbitcoincash#936]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add https://store.steampowered.com/ to the **Games** category. Details follow:

```yml

- name: Steam Games
  url: https://store.steampowered.com/
  img: http://www.stickpng.com/img/icons-logos-emojis/tech-companies/steam-logo
  twitter: @steam_games
  facebook: @Steam
  region: see_region_code_table_below
  country: see_wikipedia_link_below
  city: capitalize_city_name
  bch: no
  btc: no
  othercrypto: no
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
