### ISSUE TITLE
Add TradingView.com to accept BitcoinCash for PRO account along with Bitcoin

### ISSUE THREAD

**Issue by keshavnarla** [acceptbitcoincash/acceptbitcoincash#937]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Tradingview**}} to the {{**Analysis**}} category. Details follow:

```yml

- name: Tradingview
  url: https://www.tradingview.com/
  img: https://static1.squarespace.com/static/590685b2f5e2319ca13c63e5/5907632dbf629aab7637d02f/5941490203596ed295e35409/1497456271324/tradingview+logo.jpg?format=500w
  twitter: @tradingview
  facebook: @tradingview
  region: see_region_code_table_below
  country: see_wikipedia_link_below
  city: capitalize_city_name
  bch: no
  btc: yes
  othercrypto: no
  doc: URL_to_site_with_bitcoin_cash_announcement_or_help/support_article_etc
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
