### ISSUE TITLE
Add 'BlockPress' to the 'Social' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#941]
Requesting to add 'BlockPress' to the 'Social' category. 

Details follow: 
```yml 
- name: BlockPress
      url: https://blockpress.com
      img: 
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to BlockPress](https://blockpress.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
