### ISSUE TITLE
Add 'Grow Kit' to the 'Garden ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#942]
Requesting to add 'Grow Kit' to the 'Garden ' category. 

Details follow: 
```yml 
- name: Grow Kit
      url: https://thegrowkit.ca/
      img: 
      twitter: grow_kit
      email_address: thegrowkit@gmail.com
      region: na
      city: Toronto, Canada
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Grow Kit](https://thegrowkit.ca/wp-content/uploads/2018/04/gk-1.png)

[Link to Grow Kit](https://thegrowkit.ca/)
If needed, try the twitter handles profile image: [twitter.com/grow_kit](https://twitter.com/grow_kit)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
