### ISSUE TITLE
Add 'CrossFit Shohaku' to the 'gym' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#943]
Requesting to add 'CrossFit Shohaku' to the 'gym' category. 

Details follow: 
```yml 
- name: CrossFit Shohaku
      url: https://www.crossfitshohaku.com
      img: 
      facebook: CrossfitShohaku
      region: as
      country: JP
      city: Kyoto
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.instagram.com/p/Big1SVugaAD/?hl=ja&taken-at=129768457690153
      exceptions: 
        text: "no"
```

Resources for adding this merchant:
[Link to CrossFit Shohaku](https://www.crossfitshohaku.com)
If needed, try the facebook handles profile image: [fb.com/CrossfitShohaku](https://fb.com/CrossfitShohaku)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
