### ISSUE TITLE
Add 'Float Away Spa' to the 'Alternative Medicine' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#945]
Requesting to add 'Float Away Spa' to the 'Alternative Medicine' category. 

Details follow: 
```yml 
- name: Float Away Spa
      url: https://www.floatawayspa.com/
      img: 
      twitter: floatawayspa
      facebook: floatawayspa
      email_address: sean@floatawayspa.com
      region: na
      country: US
      city: Highland Village
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.facebook.com/floatawayspa/posts/1370645059748005
      exceptions: 
        text: "Payment is only accepted in person at this point."
```

Resources for adding this merchant:
Logo Provided:
![Float Away Spa](https://pbs.twimg.com/profile_images/499539415124176897/cPvpETD2_400x400.jpeg)

[Link to Float Away Spa](https://www.floatawayspa.com/)
If needed, try the twitter handles profile image: [twitter.com/floatawayspa](https://twitter.com/floatawayspa)
If needed, try the facebook handles profile image: [fb.com/floatawayspa](https://fb.com/floatawayspa)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
