### ISSUE TITLE
Please Add CreamyTaiwan.com

### ISSUE THREAD

**Issue by kmajor** [acceptbitcoincash/acceptbitcoincash#948]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {CreamyTaiwan.com} to the {Retail} category. Details follow:

```yml

- name: Creamy Taiwan
  url: https://creamytaiwan.com
  img: https://creamytaiwan.com/content/uploads/2018/04/creamy_logo_lavender-e1523125376405.png
  twitter: creamytaiwan
  facebook: 
  region: as
  country: TW
  city: 
  bch: yes
  btc: yes
  othercrypto: yes
  doc: 
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
