### ISSUE TITLE
Add 'kvchnoida' to the 'LANGUAGE ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#953]
Requesting to add 'kvchnoida' to the 'LANGUAGE ' category. 

Details follow: 
```yml 
- name: kvchnoida
      url: https://kvch.in/best-german-training-noida.html
      img: 
      email_address: nipurn.kvch@gmail.com
      region: as
      country: IN
      city: Noida
      bch: No
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to kvchnoida](https://kvch.in/best-german-training-noida.html)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
