### ISSUE TITLE
Add 'Bitmarket' to the 'Exchange' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#957]
Requesting to add 'Bitmarket' to the 'Exchange' category. 

Details follow: 
```yml 
- name: Bitmarket
      url: https://www.bitmarket.net/
      img: Bitmarket.png
      twitter: BitmarketNet
      facebook: bitmarketpl
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Bitmarket](https://www.bitmarket.net/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
