### ISSUE TITLE
Add 'Storm Computers' to the 'Computer Hardware' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#959]
Requesting to add 'Storm Computers' to the 'Computer Hardware' category. 

Details follow: 
```yml 
- name: Storm Computers
      url: https://www.stormcomputers.com.au/
      img: 
      twitter: StormComputers
      email_address: cannington@stormcomputers.com.au
      region: oc
      country: AU
      city: Perth
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: https://www.stormcomputers.com.au/catalog/bitcoininfo.php
```

Resources for adding this merchant:
Logo Provided:
![Storm Computers](https://pbs.twimg.com/profile_images/362156880/stormlogo_400x400.gif)

[Link to Storm Computers](https://www.stormcomputers.com.au/)
If needed, try the twitter handles profile image: [twitter.com/StormComputers](https://twitter.com/StormComputers)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
