### ISSUE TITLE
Add 'ModMyPi.com' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#960]
Requesting to add 'ModMyPi.com' to the 'Retail' category. 

Details follow: 
```yml 
- name: ModMyPi.com
      url: https://modmypi.com
      twitter: modmypi
      facebook: modmypi
      img: modmypi.png
      bch: Yes
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
[Link to ModMyPi.com](https://modmypi.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
