### ISSUE TITLE
Add 'Dyrdahl Lumber' to the 'Building Materials Supplier' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#961]
Requesting to add 'Dyrdahl Lumber' to the 'Building Materials Supplier' category. 

Details follow: 
```yml 
- name: Dyrdahl Lumber
      url: https://dyrdahl-lumber.com
      img: DyrdahlLumber.png
      twitter: DyrdahlLumber
      facebook: dyrdahllumber
      email_address: kevintores1992@gmail.com
      region: na
      country: US
      state: Minnesota
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.facebook.com/dyrdahllumber/photos/a.929204377258037.1073741829.266220780223070/929203443924797/?type=3&theater
      exceptions: 
        text: "Contact us at https://www.dyrdahl-lumber.com/contact"
```

Resources for adding this merchant:
Logo Provided:
![Dyrdahl Lumber](https://static.wixstatic.com/media/a77bb7_0027df634f7d42cbba8593396241a15c~mv2.png/v1/fill/w_125,h_122,al_c,usm_0.66_1.00_0.01/a77bb7_0027df634f7d42cbba8593396241a15c~mv2.png)

[Link to Dyrdahl Lumber](https://dyrdahl-lumber.com)
If needed, try the twitter handles profile image: [twitter.com/DyrdahlLumber](https://twitter.com/DyrdahlLumber)
If needed, try the facebook handles profile image: [fb.com/dyrdahllumber](https://fb.com/dyrdahllumber)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
