### ISSUE TITLE
Add 'Working For Bitcoins' to the 'Service' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#962]
Requesting to add 'Working For Bitcoins' to the 'Service' category. 

Details follow: 
```yml 
- name: Working For Bitcoins
      url: https://workingforbitcoins.com
      img: workingforbitcoins.png
      twitter: working4Bitcoin
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Working For Bitcoins](https://workingforbitcoins.com)
If needed, try the twitter handles profile image: [twitter.com/working4Bitcoin](https://twitter.com/working4Bitcoin)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
