### ISSUE TITLE
Add 'Franklin Arms' to the 'Ammunition and Firearms - Home Security ' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#964]
Requesting to add 'Franklin Arms' to the 'Ammunition and Firearms - Home Security ' category. 

Details follow: 
```yml 
- name: Franklin Arms
      url: https://www.franklinarms.ca
      img: FranklinArms.png
      twitter: franklin_arms
      email_address: info@franklinarms.ca
      region: na
      country: CA
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Franklin Arms](https://twitter.com/franklin_arms)

[Link to Franklin Arms](https://www.franklinarms.ca)
If needed, try the twitter handles profile image: [twitter.com/franklin_arms](https://twitter.com/franklin_arms)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
