### ISSUE TITLE
Add 'SPAZ radio' to the 'streaming music/entertainment' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#965]
Requesting to add 'SPAZ radio' to the 'streaming music/entertainment' category. 

Details follow: 
```yml 
- name: SPAZ radio
      url: http://spaz.radio
      img: 
      email_address: aaron@spaz.org
      city: no
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://www.reddit.com/r/btc/comments/8dc0vr/please_help_us_beta_test_our_new_bch_dj_tipping/
      exceptions: 
        text: "scan qr code or copy wallet address"
```

Resources for adding this merchant:
Logo Provided:
![SPAZ radio](http://spaz.org/images/boombox/spazBox3.gif)

[Link to SPAZ radio](http://spaz.radio)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
