### ISSUE TITLE
Add 'Trading Shenzen' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#967]
Requesting to add 'Trading Shenzen' to the 'Retail' category. 

Details follow: 
```yml 
- name: Trading Shenzen
      url: https://tradingshenzhen.com/en/
      img: 
      twitter: tradingshenzhen
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
[Link to Trading Shenzen](https://tradingshenzhen.com/en/)
If needed, try the twitter handles profile image: [twitter.com/tradingshenzhen](https://twitter.com/tradingshenzhen)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/tradingshenzhen.com/](https://www.alexa.com/siteinfo/tradingshenzhen.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
