### ISSUE TITLE
Add 'Hat Like Dad' to the 'Crypto Apparel - Hats' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#968]
Requesting to add 'Hat Like Dad' to the 'Crypto Apparel - Hats' category. 

Details follow: 
```yml 
- name: Hat Like Dad
      url: https://hatlikedad.com
      img: 
      facebook: hatlikedad
      email_address: hatlikedad@gmail.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: Please send me an email- I will be posted a blog post on the site later today. 
```

Resources for adding this merchant:
[Link to Hat Like Dad](https://hatlikedad.com)
If needed, try the facebook handles profile image: [fb.com/hatlikedad](https://fb.com/hatlikedad)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/hatlikedad.com](https://www.alexa.com/siteinfo/hatlikedad.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
