### ISSUE TITLE
Add 'Beardstyle' to the 'Cosmetics' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#969]
Requesting to add 'Beardstyle' to the 'Cosmetics' category. 

Details follow: 
```yml 
- name: Beardstyle
      url: https://www.beardstyle.de
      img: 
      facebook: beardstylegermany
      email_address: info@beardstyle.de
      region: eu
      bch: No
      btc: Yes
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![Beardstyle](https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-1/p200x200/17796659_1793380984314724_4085758323049328643_n.png?_nc_cat=0&oh=6bd4dfc61bd84a731c1fda7227a61f9a&oe=5B834919)

[Link to Beardstyle](https://www.beardstyle.de)
If needed, try the facebook handles profile image: [fb.com/beardstylegermany](https://fb.com/beardstylegermany)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.beardstyle.de](https://www.alexa.com/siteinfo/www.beardstyle.de)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
