### ISSUE TITLE
Add 'Just Hodl Apparel' to the 'Apparel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#970]
Requesting to add 'Just Hodl Apparel' to the 'Apparel' category. 

Details follow: 
```yml 
- name: Just Hodl Apparel
      url: https://justhodlapparel.com
      img: 
      region: na
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/8k93jt/recently_launched_a_crypto_store_and_naturally/
```

Resources for adding this merchant:
[Link to Just Hodl Apparel](https://justhodlapparel.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/justhodlapparel.com](https://www.alexa.com/siteinfo/justhodlapparel.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
