### ISSUE TITLE
Add 'Loomenaughty' to the 'Apparel' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#971]
Requesting to add 'Loomenaughty' to the 'Apparel' category. 

Details follow: 
```yml 
- name: Loomenaughty
      url: https://loomenaughty.com
      img: 
      twitter: loomenaughty
      email_address: intl@loomenaughty.com
      bch: Yes
      btc: No
      othercrypto: No
      doc: https://loomenaughty.com/help/
```

Resources for adding this merchant:
Logo Provided:
![Loomenaughty](https://s3.amazonaws.com/com.loomenaughty.images/AcceptsBitcoinCashThumbnail.png)

[Link to Loomenaughty](https://loomenaughty.com)
If needed, try the twitter handles profile image: [twitter.com/loomenaughty](https://twitter.com/loomenaughty)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/loomenaughty.com](https://www.alexa.com/siteinfo/loomenaughty.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
