### ISSUE TITLE
Add 'Astronaut Apparel' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#973]
Requesting to add 'Astronaut Apparel' to the 'Retail' category. 

Details follow: 
```yml 
- name: Astronaut Apparel
      url: https://www.astronautapparel.com
      img: 
      twitter: apparelastro
      facebook: astronautapparel
      email_address: brandon@astronautapparel.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://twitter.com/apparelastro/status/993870025294536705
      exceptions: 
        text: "Coinbase Commerce on checkout!"
```

Resources for adding this merchant:
Logo Provided:
![Astronaut Apparel](https://pbs.twimg.com/profile_images/968683278155706368/rrQBkjXY_400x400.jpg)

[Link to Astronaut Apparel](https://www.astronautapparel.com)
If needed, try the twitter handles profile image: [twitter.com/apparelastro](https://twitter.com/apparelastro)
If needed, try the facebook handles profile image: [fb.com/astronautapparel](https://fb.com/astronautapparel)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.astronautapparel.com](https://www.alexa.com/siteinfo/www.astronautapparel.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
