### ISSUE TITLE
Add 'BullionStar' to the 'Precious Metals' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#975]
Requesting to add 'BullionStar' to the 'Precious Metals' category. 

Details follow: 
```yml 
- name: BullionStar
      url: https://www.bullionstar.com/
      img: 
      twitter: BullionStar
      facebook: bullionstar
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.bullionstar.com/blogs/bullionstar/bullionstar-adds-ethereum-bitcoin-cash-litecoin-payment-options-currencies/
      exceptions: 
        text: "Select your preferred currency on right-hand side of main menu bar."
```

Resources for adding this merchant:
[Link to BullionStar](https://www.bullionstar.com/)
If needed, try the twitter handles profile image: [twitter.com/BullionStar](https://twitter.com/BullionStar)
If needed, try the facebook handles profile image: [fb.com/bullionstar](https://fb.com/bullionstar)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.bullionstar.com/](https://www.alexa.com/siteinfo/www.bullionstar.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
