### ISSUE TITLE
Add 'BullionStar' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#978]
Requesting to add 'BullionStar' to the 'Retail' category. 

Details follow: 
```yml 
- name: BullionStar
      url: https://www.bullionstar.com
      img: 
      twitter: BullionStar
      facebook: bullionstar/
      email_address: ronan.manly@bullionstar.com
      country: SG
      city: Singapore
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.bullionstar.com/blogs/bullionstar/bullionstar-adds-ethereum-bitcoin-cash-litecoin-payment-options-currencies/
      exceptions: 
        text: "https://www.bullionstar.com/help/bitcoin"
```

Resources for adding this merchant:
Logo Provided:
![BullionStar](https://www.bullionstar.com/blogs/bullionstar/b-logo/)

[Link to BullionStar](https://www.bullionstar.com)
If needed, try the twitter handles profile image: [twitter.com/BullionStar](https://twitter.com/BullionStar)
If needed, try the facebook handles profile image: [fb.com/bullionstar/](https://fb.com/bullionstar/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.bullionstar.com](https://www.alexa.com/siteinfo/www.bullionstar.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
