### ISSUE TITLE
Add 'CryptAPI' to the 'Payment Processor' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#981]
Requesting to add 'CryptAPI' to the 'Payment Processor' category. 

Details follow: 
```yml 
- name: CryptAPI
      url: https://cryptapi.io
      img: 
      twitter: CryptAPI_io
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://cryptapi.io/blog/post/2/
      exceptions: 
        text: "Follow the interactive documentation @ https://cryptapi.io/docs/"
```

Resources for adding this merchant:
Logo Provided:
![CryptAPI](https://cryptapi.io/static/index/images/ca3.png)

[Link to CryptAPI](https://cryptapi.io)
If needed, try the twitter handles profile image: [twitter.com/CryptAPI_io](https://twitter.com/CryptAPI_io)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/cryptapi.io](https://www.alexa.com/siteinfo/cryptapi.io)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
