### ISSUE TITLE
Add 'BCH Ad Spot' to the 'Advertising Network' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#982]
Requesting to add 'BCH Ad Spot' to the 'Advertising Network' category. 

Details follow: 
```yml 
- name: BCH Ad Spot
      url: https://bchadspot.com
      img: 
      email_address: info@bchadspot.com
      bch: Yes
      btc: No
      othercrypto: No
      exceptions: 
        text: "Coinpayments.net"
```

Resources for adding this merchant:
Logo Provided:
![BCH Ad Spot](https://i.imgur.com/Taar68t.png)

[Link to BCH Ad Spot](https://bchadspot.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/bchadspot.com](https://www.alexa.com/siteinfo/bchadspot.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
