### ISSUE TITLE
Add 'Joomstore' to the 'Web Development' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#985]
Requesting to add 'Joomstore' to the 'Web Development' category. 

Details follow: 
```yml 
- name: Joomstore
      url: https://joomstore.com.au/
      img: 
      twitter: johnpitchers
      facebook: Joomstore
      email_address: john@joomstore.com.au
      region: oc
      country: AU
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Payment instructions provided on invoice."
```

Resources for adding this merchant:
Logo Provided:
![Joomstore](https://joomstore.com.au/images/template/joomstore-logo-sq-128.png)

[Link to Joomstore](https://joomstore.com.au/)
If needed, try the twitter handles profile image: [twitter.com/johnpitchers](https://twitter.com/johnpitchers)
If needed, try the facebook handles profile image: [fb.com/Joomstore](https://fb.com/Joomstore)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/joomstore.com.au/](https://www.alexa.com/siteinfo/joomstore.com.au/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
