### ISSUE TITLE
Add 'COOL Networks' to the 'IT, Support, Sales & Maintenance' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#987]
Requesting to add 'COOL Networks' to the 'IT, Support, Sales & Maintenance' category. 

Details follow: 
```yml 
- name: COOL Networks
      url: http://cool.net.au
      img: 
      twitter: coolnetau
      facebook: CoolNetworks/
      region: oc
      country: AU
      city: ADELAIDE
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: not available yet
      exceptions: 
        text: "Ask the guy if he takes crypto"
```

Resources for adding this merchant:
Logo Provided:
![COOL Networks](http://cool.net.au/wp-content/uploads/2018/02/COOL-NETWORKS_Logo_3_Final_300-384x160-7666.png)

[Link to COOL Networks](http://cool.net.au)
If needed, try the twitter handles profile image: [twitter.com/coolnetau](https://twitter.com/coolnetau)
If needed, try the facebook handles profile image: [fb.com/CoolNetworks/](https://fb.com/CoolNetworks/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/cool.net.au](https://www.alexa.com/siteinfo/cool.net.au)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
