### ISSUE TITLE
Add 'myFINBEC' to the 'art gallery' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#988]
Requesting to add 'myFINBEC' to the 'art gallery' category. 

Details follow: 
```yml 
- name: myFINBEC
      url: http://coin.myfinbec.com/shop15_INDEX.html
      img: 
      facebook: myFINBEC/
      email_address: sales@myfinbec.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "through Bitpay"
```

Resources for adding this merchant:
Logo Provided:
![myFINBEC](https://pbs.twimg.com/profile_images/717612794955345920/WmMG8NB4_400x400.jpg)

[Link to myFINBEC](http://coin.myfinbec.com/shop15_INDEX.html)
If needed, try the facebook handles profile image: [fb.com/myFINBEC/](https://fb.com/myFINBEC/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/coin.myfinbec.com/shop15_INDEX.html](https://www.alexa.com/siteinfo/coin.myfinbec.com/shop15_INDEX.html)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
