### ISSUE TITLE
Hipptee.com

### ISSUE THREAD

**Issue by hipptee** [acceptbitcoincash/acceptbitcoincash#989]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add hipptee.com to the clothing category. Details follow:

```yml

- name: hipptee
  url: https://hipptee.com
  img: https://cdn.shopify.com/s/files/1/0786/2611/files/ht_logo.png
  twitter: @hipptees
  facebook: hipptee
  region: NA
  country: US
  city: Internet
  bch: yes
  btc: yes
  othercrypto: yes
  doc: https://www.reddit.com/r/btc/comments/8kxprt/hippteecom_now_accepts_bch_and_prices_in_bch_too/
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
