### ISSUE TITLE
Add 'Otaku Taku Toys' to the 'Toys/Games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#990]
Requesting to add 'Otaku Taku Toys' to the 'Toys/Games' category. 

Details follow: 
```yml 
- name: Otaku Taku Toys
      url: https://otakutaku.com/
      img: 
      twitter: otakutakutoys
      facebook: otakutakutoys
      email_address: senpai@otakutaku.com
      region: na
      country: US
      bch: Yes
      btc: No
      othercrypto: Yes
      exceptions: 
        text: "Payment accepted at checkout."
```

Resources for adding this merchant:
Logo Provided:
![Otaku Taku Toys](https://pbs.twimg.com/profile_images/982086091829403649/KvHhcRgx_bigger.jpg)

[Link to Otaku Taku Toys](https://otakutaku.com/)
If needed, try the twitter handles profile image: [twitter.com/otakutakutoys](https://twitter.com/otakutakutoys)
If needed, try the facebook handles profile image: [fb.com/otakutakutoys](https://fb.com/otakutakutoys)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/otakutaku.com/](https://www.alexa.com/siteinfo/otakutaku.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
