### ISSUE TITLE
Add 'LIVECARDS' to the 'Games' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#991]
Requesting to add 'LIVECARDS' to the 'Games' category. 

Details follow: 
```yml 
- name: LIVECARDS
      url: https://livecards.eu/
      img: 
      twitter: NA
      facebook: NA
      email_address: support@supportprofessionals.net
      city: NA
      bch: Yes
      btc: Yes
      othercrypto: No
      doc: NA
      exceptions: 
        text: "Processed through Bitpay"
```

Resources for adding this merchant:
Logo Provided:
![LIVECARDS](https://s3-eu-west-1.amazonaws.com/tpd/logos/5810a57b0000ff000596959c/0x0.png)

[Link to LIVECARDS](https://livecards.eu/)
If needed, try the twitter handles profile image: [twitter.com/NA](https://twitter.com/NA)
If needed, try the facebook handles profile image: [fb.com/NA](https://fb.com/NA)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/livecards.eu/](https://www.alexa.com/siteinfo/livecards.eu/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
