### ISSUE TITLE
Add 'Shenova Fashion ' to the 'Ladies STEM themed clothing: Bitcoin Black Dress' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#993]
Requesting to add 'Shenova Fashion ' to the 'Ladies STEM themed clothing: Bitcoin Black Dress' category. 

Details follow: 
```yml 
- name: Shenova Fashion 
      url: https://www.shenovafashion.com
      img: 
      region: na
      country: US
      bch: No
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "You must download Bitpay to purchase using Cryptocurrency on the website. I want to pay directly from my Bitcoin.com Cash wallet to buy the Bitcoin Dress. Is that capability not yet developed or live? "
```

Resources for adding this merchant:
[Link to Shenova Fashion ](https://www.shenovafashion.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.shenovafashion.com](https://www.alexa.com/siteinfo/www.shenovafashion.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
