### ISSUE TITLE
Add 'Hipptee' to the 'Retail' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#995]
Requesting to add 'Hipptee' to the 'Retail' category. 

Details follow: 
```yml 
- name: Hipptee
      url: https://hipptee.com/
      img: 
      twitter: hipptees
      bch: Yes
      btc: Yes
      othercrypto: Yes
```

Resources for adding this merchant:
Logo Provided:
![Hipptee](https://pbs.twimg.com/profile_images/987647705789943808/7mCPfoz9_400x400.jpg)

[Link to Hipptee](https://hipptee.com/)
If needed, try the twitter handles profile image: [twitter.com/hipptees](https://twitter.com/hipptees)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/hipptee.com/](https://www.alexa.com/siteinfo/hipptee.com/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
