### ISSUE TITLE
Add 'eatBCH South Sudan' to the 'Human Needs/Rights' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#996]
Requesting to add 'eatBCH South Sudan' to the 'Human Needs/Rights' category. 

Details follow: 
```yml 
- name: eatBCH South Sudan
      url: https://twitter.com/eatbch_ss
      img: 
      twitter: eatbch_ss
      email_address: lizzie.lace@gmail.com
      region: af
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
Logo Provided:
![eatBCH South Sudan](https://pbs.twimg.com/profile_images/1000140330551803904/b-_TO1EN_400x400.jpg)

[Link to eatBCH South Sudan](https://twitter.com/eatbch_ss)
If needed, try the twitter handles profile image: [twitter.com/eatbch_ss](https://twitter.com/eatbch_ss)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/twitter.com/eatbch_ss](https://www.alexa.com/siteinfo/twitter.com/eatbch_ss)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
