### ISSUE TITLE
Add 'CryptAPI' to the 'Payment processor' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#997]
Requesting to add 'CryptAPI' to the 'Payment processor' category. 

Details follow: 
```yml 
- name: CryptAPI
      url: https://cryptapi.io/
      img: 
      twitter: ryptAPI_io
      facebook: cryptapi/
      email_address: cryptapi@protonmail.com
      city: no
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://bitcointalk.org/index.php?topic=3452512.msg37396527#msg37396527
      exceptions: 
        text: "https://cryptapi.io/docs/#/Bitcoin_Cash/bchcreate
Our support Telehgram group: https://t.me/cryptapi"
```

Resources for adding this merchant:
Logo Provided:
![CryptAPI](https://pbs.twimg.com/profile_images/990986952643174400/RD4aB87A_400x400.jpg)

[Link to CryptAPI](https://cryptapi.io/)
If needed, try the twitter handles profile image: [twitter.com/ryptAPI_io](https://twitter.com/ryptAPI_io)
If needed, try the facebook handles profile image: [fb.com/cryptapi/](https://fb.com/cryptapi/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/cryptapi.io/](https://www.alexa.com/siteinfo/cryptapi.io/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
