### ISSUE TITLE
Add 'SexRoulette   @SexRouletteBot_bot' to the 'Bot telegram' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#998]
Requesting to add 'SexRoulette   @SexRouletteBot_bot' to the 'Bot telegram' category. 

Details follow: 
```yml 
- name: SexRoulette   @SexRouletteBot_bot
      url: https://www.nosite.com
      img: 
      bch: Yes
      btc: No
      othercrypto: No
```

Resources for adding this merchant:
[Link to SexRoulette   @SexRouletteBot_bot](https://www.nosite.com)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.nosite.com](https://www.alexa.com/siteinfo/www.nosite.com)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
