### ISSUE TITLE
Add 'KiT systems' to the 'Air conditioning equipment and security systems' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#999]
Requesting to add 'KiT systems' to the 'Air conditioning equipment and security systems' category. 

Details follow: 
```yml 
- name: KiT systems
      url: https://www.kitsystem.ru/
      img: 
      email_address: info@kitsystem.ru
      country: RU
      bch: Yes
      btc: No
      othercrypto: Yes
      doc: https://www.kitsystem.ru/blog/info/oplachivayte-tovary-i-uslugi-kriptovalyutoy
```

Resources for adding this merchant:
Logo Provided:
![KiT systems](https://www.kitsystem.ru/sites/default/files/0_my_files/img/logo/logo_ok.png)

[Link to KiT systems](https://www.kitsystem.ru/)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/www.kitsystem.ru/](https://www.alexa.com/siteinfo/www.kitsystem.ru/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.
